### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by holgado1** [SmileiPIC/Smilei#1]
I am running into a compiling error after running 'make':
```
--------------
Creating binary char for src/Python/pyprofiles.py : build/src/Python/pyprofiles.pyh
/bin/sh: xxd: command not found
Checking dependencies for src/Params/Params.cpp
Creating binary char for src/Python/pyprofiles.py : build/src/Python/pyprofiles.pyh
/bin/sh: xxd: command not found
Checking dependencies for src/Params/Params.cpp
Creating binary char for src/Python/pyprofiles.py : build/src/Python/pyprofiles.pyh
/bin/sh: xxd: command not found
Checking dependencies for src/Params/Params.cpp
.
.
.
--------------
```
which continues recursively.

**Comment by iltommi** [comment]
You need to install `xxd` package. I don't know which OS you're trying to install Smilei on, but on Debian based systems, xxd should come in the base system.

On Redhat based Fedora I got a Report from a  user so kind to provide instructions:

1. openmpi install:

  download the source file `openmpi-xxx.tar.gz`
  ```bash
tar -zxvf openmpi-xxx.tar.gz
cd openmpi-xxx
./configure --prefix=/home/XXXX/openmpi --enable-mpi-thread-multiple
make
make install
  ```
  Add the following two lines in the .bashrc file,
  ```bash
export PATH="$PATH:/home/XXXX/openmpi/bin"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/home/XXXX/openmpi/lib/"
  ````
2. HDF5 install

  download the source file HDF5 from http://www.hdfgroup.org/HDF5/

  ```bash
CC=mpicc ./configure --prefix=/home/xxx/HDF5-parallel --enable-parallel
make
make install
Add the folowing line in the .bashrc file,
export LD_LIBRARY_PATH="/home/xxx/HDF5-parallel/lib":$LD_LIBRARY_PATH
  ```
3. If ``xxd`` is not installed, you should do the commands

  ```bash
 sudo yum update vim-minimal 
 sudo yum install vim-enhanced
  ```
4. add the following lines in the .bashrc file,

  ```bash
export SMILEICXX=mpicxx
export HDF5_ROOT_DIR=/home/xxx/HDF5-parallel
  ```
 5. Go in the `smilei` dir and compile:

**Comment by iltommi** [comment]
Anyway, 
in the next release we plan to remove the `xxd` dependency, so stay tuned!

Feel free to close the issue if the above commands work for you.

**Comment by holgado1** [comment]
Thanks! I solved the problem by loading a vim module.
