### ISSUE TITLE
MPI/OpenMP optimisation on CURTA cluster (BORDEAUX)

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#100]
Hi

I installed Smilei on the new cluster of MCIA (BORDEAUX).
And I am seeking to set the good number of MPTHREADS and MPI process.

Intel® Xeon® Gold SKL-6130 @ 2,1 GHz (2 per node)

Have you got some advices?

Julien
CELIA

**Comment by mccoys** [comment]
Looks like 2 sockets per node and 16 cores per process. So logically, 1 MPI per socket (2 MPI per node) and 16 threads per MPI (total 32 threads per node).

But you should test instead of taking our advice. Remember to bind correctly processes to sockets.

**Comment by xxirii** [comment]
Following recommendation of @mccoys:
- To use 16 OMP threads means: `export OMP_NUM_THREADS=16`
- To bind correctly the processes, you can use `export OMP_PROC_BIND=TRUE` and `export OMP_PLACES=cores` with GNU. If you use Intel, use `export KMP_AFFINITY=granularity=fine,scatter`. This is very important if hyperthreading is activated and you do not want to use it. You can try with and without these parameters to check that does not kill your performance.

**Comment by mccoys** [comment]
I was referring to binding processes, not threads, but it is important as well.

To bind processes to sockets, use the option `--bind-to socket` of `mpirun`

**Comment by juliencelia** [comment]
Hi SMILEI users,

On Curta cluster, openmpi module 3.1.3 is installed. When I use it, a simulation of one hour on my station becomes very longer (4times longer). So I installed the last openmpi version and I load my own module openmpi with "use.own" module. But I always have an error in smilei with this issue:

cmdTrace.c(713):ERROR:104: '/gpfs/home/jbonvalet/privatemodules/openmpi' is an $
cmdModule.c(411):ERROR:104: '/gpfs/home/jbonvalet/privatemodules/openmpi' is an$
--------------------------------------------------------------------------
WARNING: No preset parameters were found for the device that Open MPI
detected:

Local host:            n056
  Device name:           i40iw0
  Device vendor ID:      0x8086
  Device vendor part ID: 14290

Default device parameters will be used, which may result in lower
performance. You can edit any of the files specified by the
btl_openib_device_param_files MCA parameter to set values for your
device.

NOTE: You can turn off this warning by setting the MCA parameter
btl_openib_warn_no_device_params_found to 0.

...

By default, for Open MPI 4.0 and later, infiniband ports on a device
are not used by default. The intent is to use UCX for these devices.
You can override this policy by setting the btl_openib_allow_ib MCA parameter
to true.

Local host:              n056
  Local adapter:           hfi1_0
  Local port:              1

--------------------------------------------------------------------------
--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

Local host:   n056
  Local device: hfi1_0

------------------------------------------------------------------------------$
        timestep       sim time   cpu time [s]   (    diff [s] )
[n056:359749] 1 more process has sent help message help-mpi-btl-openib.txt / no$
[n056:359749] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help$
[n056:359749] 1 more process has sent help message help-mpi-btl-openib.txt / ib$
[n056:359749] 1 more process has sent help message help-mpi-btl-openib.txt / er$

Someone could help me?

Thanks

Julien CELIA

**Comment by mccoys** [comment]
Openmpi 3.1 should be fine. It works well for me. Have you tried ?

**Comment by mccoys** [comment]
You should use openmpi 3.1. It should be ok. However, it might not be set properly. For example, have you specified correctly the `OMP_NUM_THREADS`, the `OMP_PROC_BIND` and the `bind-to core` ?

Also, check the performance of each core of your cluster. It might be lower than your laptop.

**Comment by juliencelia** [comment]
Yes I tried many configurations but the most efficient is:
OMP_NUM_THREADS=16
OMP_SCHEDULE=dynamic
OMP_PROC_BIND=true

bind_to core is also efficient contrary to bind-to socket.
The node has 2 Intel® Xeon® Gold SKL-6130 @ 2,1 GHz on th cluster. On my station it's Intel Xeon (R) CPU E5-1660 v4 @ 3.20GHz. That can't explain the multiplication of time simulation by 4 I think....

**Comment by mccoys** [comment]
have you tried making the same simulation on both machines with only 1 thread and 1 MPI ?

**Comment by mccoys** [comment]
Also check the memory available per core. There can also be issues with cache access which can slow down a simulation.

**Comment by jderouillat** [comment]
Managing only binding (for OpenMP threads and/or MPI process) could be not enough. Whatever the version of OpenMPI you are using. It should work with the 3.1 release.  

First check that your MPI processes are distributed over all your resources using `mpirun -report-bindings ...`.
Below an example of a simulation launching on a classical double socket node (8 cores per socket). We want to use 1 MPI per socket so 2 MPI x 8 threads :
```bash
$ mpirun --report-bindings -np 2 ../smilei tst2d_02_radiation_pressure_acc.py 
[node032:06122] MCW rank 0 bound to socket 0[core 0[hwt 0]]: [B/././././././.][./././././././.]
[node032:06122] MCW rank 1 bound to socket 0[core 1[hwt 0]]: [./B/./././././.][./././././././.]
                    _            _
  ___           _  | |        _  \ \   Version : v4.1-321-g808d4524-develop
 / __|  _ __   (_) | |  ___  (_)  | |   
 \__ \ | '  \   _  | | / -_)  _   | |
 |___/ |_|_|_| |_| |_| \___| |_|  | |  
                                 /_/    
...
    150/1500     6.3041e+00     3.8624e+01   (  3.8624e+01 )
...
```
All threads will be pinned on the 2 first cores.  
Then with the binding : 
```bash
$ mpirun --report-bindings -np 2 --bind-to socket ../smilei tst2d_02_radiation_pressure_acc.py 
[node032:06156] ... : [B/B/B/B/B/B/B/B][./././././././.]
[node032:06156] ... : [B/B/B/B/B/B/B/B][./././././././.]
...
    150/1500     6.3041e+00     1.3280e+01   (  1.3280e+01 )
...
```
Threads can access all cores of the socket but they are associated to the same socket.
Then managing the distribution :  
```bash
$ mpirun -report-bindings -np 2 -map-by ppr:1:socket --bind-to socket ../smilei tst2d_02_radiation_pressure_acc.py 
[node032:06217] ... : [B/B/B/B/B/B/B/B][./././././././.]
[node032:06217] ... : [./././././././.][B/B/B/B/B/B/B/B]
...
    150/1500     6.3041e+00     3.5232e+00   (  3.5232e+00 )
...
...
```
This has been run with the 3.1.3 OpenMPI library, the `-map-by ppr:1:socket` is maybe not the most up-to-date option, you'll find a warning starting the simulation but it's still managing the distribution. All MPI distribution/version have their dedicated options, when I'll find the durable way to specify it, I'll send you.

**Comment by juliencelia** [comment]
Hi Julien

I did the last issue with map-by and it's surprising:
[n047:401179] MCW rank 0 bound to socket 0[core 0[hwt 0]]: [B/././././././././././././././.][./././././././././././././././.]
[n047:401179] MCW rank 1 bound to socket 1[core 16[hwt 0]]: [./././././././././././././././.][B/././././././././././././././.]

I have 16 THREADS OPENMP because the core are  hexadécacœurs (32 cores per node on 2 sockets).
I have a problem of threads?

My script is:

#!/bin/bash

#############################
# les directives Slurm vont ici:

# Your job name (displayed by the queue)
#SBATCH -J simu1d

# walltime (hh:mm::ss)
#SBATCH -t 01:00:00

# Specify the number of nodes(nodes=) and the number of cores per nodes(tasks-pernode=) to be used
#SBATCH -N 1
#SBATCH --tasks-per-node=32
#SBATCH --constraint=compute

# change working directory
# SBATCH --chdir=/scratch/jbonvalet/sim1d


# fin des directives PBS
#############################

# modules cleaning
module purge
module load mpi/openmpi/3.1.3

# What you actually want to launch
export OMP_NUM_THREADS=16
export OMP_SCHEDULE=dynamic
export OMP_PROC_BIND=TRUE
export OMP_PLACES=cores
export KMP_AFFINITY=granularity=fine,scatter

mpirun -report-bindings -np 2 -map-by ppr:1:socket /gpfs/home/jbonvalet/Smilei-4.1/smilei /gpfs/home/jbonvalet/sim1d/gas1d.py

# all done
echo "Job finished"


Thank you for your help
Julien

**Comment by jderouillat** [comment]
You have to do both :  `-map-by ppr:1:socket` to distribute as you see it in your logs and `--bind-to socket` to bind on the full socket and not on a single core.

**Comment by juliencelia** [comment]
Hi Julien! 

It works very well!! 
Thank you very much. 

Just a question: in the option -map-by ppr:1:socket, what does mean ppr? and 1? 
I'm looking for that but on the openmpi site, it's not clear... Sorry but I will increase the number of nodes so I have to really understand. 

Julien 


De: "jderouillat" <notifications@github.com> 
À: "SmileiPIC/Smilei" <Smilei@noreply.github.com> 
Cc: "Julien Bonvalet" <julien.bonvalet@u-bordeaux.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 16 Avril 2019 16:09:19 
Objet: Re: [SmileiPIC/Smilei] MPI/OpenMP optimisation on CURTA cluster (BORDEAUX) (#100) 



You have to do both : -map-by ppr:1:socket to distribute as you see it in your logs and --bind-to socket to bind on the full socket and not on a single core.

**Comment by jderouillat** [comment]
`ppr` is for process per resource.
When we think in terms of binding/distribution of processes we are mainly thinking to the memory access. 

Memory is closely associated to socket, so that why the resource considered here is `socket`.  
With 1 process per socket, you are ensuring to maintain the privileged/shortest access of a MPI process (and of OpenMP threads associated to this process) to the data store in the memory associated that it will need.
With more nodes you should keep `-map-by ppr:1:socket --bind-to socket` and just change the -np option.
