### ISSUE TITLE
Time units in S.I.

### ISSUE THREAD

**Issue by emil-mouz** [SmileiPIC/Smilei#102]
Bonjour everyone! 
I'm trying to visualize some data using the happi module and convert the quantities into S.I. units. While I succeed into converting x,y axis and data, I cannot figure out how to convert the time in my plot diagram, into S.I. units.

I tried something like

Rho=S.Field(0,"Rho",moving=True, units=["cm^-3", "um", "fs"]) or 
Rho=S.Field(0,"Rho",moving=True, units=["cm^-3", "um", "second"]) or even
Rho=S.Field(0,"Rho",moving=True, units=["cm^-3", "um", "seconds"])

Since i saw in happi python script that you use something like "second" argument for time units, but it didn't work either. 

Thank you in advance...

**Comment by iltommi** [comment]
Hi,
Smilei is an agnostic unit code. Did you define the `reference_angular_frequency_SI`: https://smileipic.github.io/Smilei/units.html ?

**Comment by emil-mouz** [comment]
Hi,
thanks for the reply. Yes, my script look like this (I use the for loop for saving the figures)

```
import happi
import pint   
import math
import matplotlib.pyplot as plt

S=happi.Open("./", reference_angular_frequency_SI=2.*math.pi*299792458/0.8e-6) 

for t in range (0,30000,750):
#######   Field Diagnostics  ##########
 t=int(t)
 Rho=S.Field(0,"Rho",moving=True, units=["cm^-3", "um","fs"])
 R=Rho.plot(timestep=t)
 plt.savefig('R'+str(t)+'.png')
```

And i get the following picture
![R3000](https://user-images.githubusercontent.com/45740200/55731209-7cc23100-5a22-11e9-895b-d38b860b2213.png)

**Comment by iltommi** [comment]
You are doing it right, there was an issue with the time label in the plot title which has been corrected recently. 

Could you test with the latest commit? You do not need to re-run the case, but just update the code and do a `make happi` to update the post processing module

**Comment by emil-mouz** [comment]
I tried to compile the new version but It seems have some problem with hdf5. Could this affect happi module?

<pre>Compiling src/Species/SpeciesV.cpp
Compiling src/Species/SpeciesAdaptiveV2.cpp
Compiling src/Tools/tabulatedFunctions.cpp
Compiling src/Tools/Timer.cpp
Compiling src/Tools/Timers.cpp
Compiling src/Tools/userFunctions.cpp
Compiling src/Tools/backward.cpp
Compiling src/Tools/Tools.cpp
Compiling src/picsar_interface/interface.cpp
Linking smilei
/usr/bin/ld: warning: libmpi.so.20, needed by /usr/local/hdf5/lib/libhdf5.so, not found (try using -rpath or -rpath-link)
Compiling src/Smilei.cpp for test mode
Linking smilei_test for test mode
/usr/bin/ld: warning: libmpi.so.20, needed by /usr/local/hdf5/lib/libhdf5.so, not found (try using -rpath or -rpath-link)
<font color="#8AE234"><b>emilios@emilios-Aspire-E5-553G</b></font>:<font color="#729FCF">

Then i tried make happi

<b>~/Downloads/Smilei-4.1</b></font>$ make happi
Unknown smilei version
Installing /home/emilios/.local/lib/python2.7/site-packages/smilei.pth
</pre>

Then when i tried to run my python script, it get the following.

<pre>Loaded simulation &apos;./&apos;
Scanning for Scalar diagnostics
Scanning for Field diagnostics
Scanning for Probe diagnostics
/home/emilios/.local/lib/python2.7/site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  &quot;Use dataset[()] instead.&quot;, H5pyDeprecationWarning)
Scanning for ParticleBinning diagnostics
Scanning for Screen diagnostics
Scanning for Tracked particle diagnostics
0.314159265359
Field diagnostic #0: Rho
Field diagnostic #0: Rho
Field diagnostic #0: Rho
Field diagnostic #0: Rho
Field diagnostic #0: Rho
Field diagnostic #0: Rho
Field diagnostic #0: Rho
Field diagnostic #0: Rho
Field diagnostic #0: Rho
^CTraceback (most recent call last):
  File &quot;Unit2.py&quot;, line 40, in &lt;module&gt;
    R=Rho1.plot(timestep=t)
  File &quot;/home/emilios/Downloads/Smilei-4.1/happi/_Diagnostics/Diagnostic.py&quot;, line 280, in plot
    self._animateOnAxes(ax, timestep)
  File &quot;/home/emilios/Downloads/Smilei-4.1/happi/_Diagnostics/Diagnostic.py&quot;, line 629, in _animateOnAxes_2D
    im = self._animateOnAxes_2D_(ax, self._vfactor*A)
KeyboardInterrupt
<font color="#8AE234"><b>emilios@emilios-Aspire-E5-553G</b></font>:<font color="#729FCF"><b>~/Desktop/First_test_Smilei</b></font>$ 
</pre>

Any ideas?

**Comment by emil-mouz** [comment]
You guessed right @iltommi  I hitted ctrl+c after 
`^CTraceback (most recent call last):`

Well, I installed Smilei-4.1 succesfully as you told me ( here are the last lines)

<pre>Compiling src/Species/SpeciesV.cpp
Compiling src/Species/SpeciesAdaptiveV2.cpp
Compiling src/Tools/tabulatedFunctions.cpp
Compiling src/Tools/Timer.cpp
Compiling src/Tools/Timers.cpp
Compiling src/Tools/userFunctions.cpp
Compiling src/Tools/backward.cpp
Compiling src/Tools/Tools.cpp
Compiling src/picsar_interface/interface.cpp
Linking smilei
Compiling src/Smilei.cpp for test mode
</pre>


Then i tied re-install happi, after unistalling the previous happi

<pre><font color="#8AE234"><b>emilios@emilios-Aspire-E5-553G</b></font>:<font color="#729FCF"><b>~/Downloads</b></font>$ cd Smilei-4.1/
<font color="#8AE234"><b>emilios@emilios-Aspire-E5-553G</b></font>:<font color="#729FCF"><b>~/Downloads/Smilei-4.1</b></font>$ make happi
Unknown smilei version
Installing /home/emilios/.local/lib/python2.7/site-packages/smilei.pth
</pre>


and I runned the following script again
```

import happi
import pint   #pint should be installed for units
import math
import matplotlib.pyplot as plt

S=happi.Open("./", reference_angular_frequency_SI=2.*math.pi*299792458/0.8e-6) 

#######   Field Diagnostics  ##########

 Rho1=S.Field(0,"Rho",moving=True, units=["cm^-3", "um","fs"])
 R=Rho1.plot(timestep=750)
```

Getting the following ouput (Nothing really changed)

<pre><font color="#8AE234"><b>emilios@emilios-Aspire-E5-553G</b></font>:<font color="#729FCF"><b>~/Downloads/Smilei-4.1/First_test_Smilei</b></font>$ python Unit2.py 
Loaded simulation &apos;./&apos;
Scanning for Scalar diagnostics
Scanning for Field diagnostics
Scanning for Probe diagnostics
/home/emilios/.local/lib/python2.7/site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  &quot;Use dataset[()] instead.&quot;, H5pyDeprecationWarning)
Scanning for ParticleBinning diagnostics
Scanning for Screen diagnostics
Scanning for Tracked particle diagnostics
Field diagnostic #0: Rho

</pre>

Then i though that I didnt update previous happi module  correctly (because i took basically the same results as yesterday)
So i though to try the execfile command that you suggest as an alternative (but I really don't know if I did it right)
```

execfile("/home/emilios/Downloads/Smilei-4.1/scripts/Diagnostics.py")

import pint   #pint should be installed for units
import math
import matplotlib.pyplot as plt
```

But again I got the same output 

<pre><font color="#8AE234"><b>emilios@emilios-Aspire-E5-553G</b></font>:<font color="#729FCF"><b>~/Downloads/Smilei-4.1/First_test_Smilei</b></font>$ python Unit2.py 
Loaded simulation &apos;./&apos;
Scanning for Scalar diagnostics
Scanning for Field diagnostics
Scanning for Probe diagnostics
/home/emilios/.local/lib/python2.7/site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  &quot;Use dataset[()] instead.&quot;, H5pyDeprecationWarning)
Scanning for ParticleBinning diagnostics
Scanning for Screen diagnostics
Scanning for Tracked particle diagnostics
0.314159265359
Field diagnostic #0: Rho
</pre>

So, think basically I cannot update the happi module from v4.0 into v4.1.

**Comment by mccoys** [comment]
did you try the latest version from the github instead of v4.1 ?

**Comment by emil-mouz** [comment]
No I downloaded from maisondesimulation

**Comment by mccoys** [comment]
This is the problem. @iltommi said the latest from github. Not v4.1

**Comment by emil-mouz** [comment]
I'm sorry I didn't really know that you upload it on github.

Anyways, fixed

![R3750](https://user-images.githubusercontent.com/45740200/55877149-f59bc700-5ba1-11e9-82a7-054c62c055a9.png)

Thank you very much for your help, have a nice evening...
