### ISSUE TITLE
ParticleBinning, data_log=True

### ISSUE THREAD

**Issue by emil-mouz** [SmileiPIC/Smilei#107]
## Description

Bonjour everyone, 

I tried to post process using ParticleBinning with logarithm scale on y axis with something like
```
eenspectr=S.ParticleBinning(0,sum={"moving_x":"all"},units=("m^-3/eV","fs", "MeV"), data_log=True)
```
and I got negative values on y axis.
![spectra22500log](https://user-images.githubusercontent.com/45740200/56119707-539b2680-5f75-11e9-9833-d2b19b9dc2fd.png)

Without `data_log=True ` I get the following
![spectra22500](https://user-images.githubusercontent.com/45740200/56119905-af65af80-5f75-11e9-8ddf-780c93fee1aa.png)

A possible bug in calculation of logarithm or I miss something?

**Comment by mccoys** [comment]
I have found the error and will correct soon. The units conversion happens after changing to log scale, which is completely wrong.

**Comment by emil-mouz** [comment]
Ok, thank you.

**Comment by mccoys** [comment]
Could you try the latest commit?

**Comment by emil-mouz** [comment]
I think it's fine. Take a look on your own to verify

![spectra_no_log18750](https://user-images.githubusercontent.com/45740200/56285442-e8418800-611f-11e9-85cd-c490fda8d607.png)


![spectra18750](https://user-images.githubusercontent.com/45740200/56285411-d7911200-611f-11e9-9fe0-0d77be2eed9e.png)
