### ISSUE TITLE
Seg fault when  'ionization_electrons' name is mis-matched

### ISSUE THREAD

**Issue by JimmyHolloway** [SmileiPIC/Smilei#11]
A small issue. 

When the name given to 'ionization_electrons' of a species block does not exist or is misspelt, SMILEI segfaults. A check when parsing the input deck would be useful as this kind of error can be missed by the user when double checking the input deck.

Example:

Species(
        species_type = 'hydrogen',
        atomic_number = 1.0,
        ionization_model = 'tunnel',
        **ionization_electrons = 'ionisede',**
        etc
)

Species(
        **species_type = 'Ionisede',**
        etc
)

Attached is the input deck which exhibits this seg fault.

All the best,
Jimmy.

[input.txt](https://github.com/SmileiPIC/Smilei/files/1135321/input.txt)

**Comment by iltommi** [comment]
Thanks for reporting, I created a branch `fix_ionization_undefined` that will be merged soon

**Comment by JimmyHolloway** [comment]
Great, thanks!

**Comment by iltommi** [comment]
Done in d185eea94efe837b65976b465a49c08366f3f768
