### ISSUE TITLE
pint module / TrackParticle diag

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#112]
Dear all,

It seems that pint module doesn't change units in TrackParticle diagnostic.
I try this:

pp=S.TrackParticles("pon",units=["um","fs","MeV/c"],sort=False).getData()

With or without "units=[...], distances are in code units not in µm.
Is it normal or did I forget something?

Thanks

Julien
CELIA

**Comment by mccoys** [comment]
Can you specify which type of plot ? What quantities are plotted ?

**Comment by juliencelia** [comment]
I don't plot anything.
I just want a phase space in array to export it in FLUKA in .dat or .txt.

If pint does not work with this diag, I can do my own changes of units.

**Comment by mccoys** [comment]
I spotted an issue with units when you don't define the argument `axes`. Please try `axes=["x","px"]` for the moment.

Note that this is not the proper diagnostic for phase-space. You should try `ParticleBinning`.

**Comment by juliencelia** [comment]
S.TrackParticles(species="pon",axes=["x","px"],sort=False,units=["um","
    ...: MeV/c"]).plot()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-f5786efbfe17> in <module>()
----> 1 S.TrackParticles(species="pon",axes=["x","px"],sort=False,units=["um","MeV/c"]).plot()

/home/jbonvalet/smilei/happi/_Diagnostics/Diagnostic.pyc in plot(self, timestep, saveAs, axes, **kwargs)
    265 		"""
    266                 if not self._validate(): return
--> 267                 if not self._prepare(): return
    268                 if not self._setAndCheck(**kwargs): return
    269                 self.info()

/home/jbonvalet/smilei/happi/_Diagnostics/Diagnostic.pyc in _prepare(self)
    523         def _prepare(self):
    524                 self._prepare1()
--> 525                 if not self._prepare2(): return False
    526                 if not self._prepare3(): return False
    527                 self._prepare4()

/home/jbonvalet/smilei/happi/_Diagnostics/Diagnostic.pyc in _prepare2(self)
    576                 self._vlabel = ""
    577                 if self.units.vname: self._vlabel += " (" + self.units.vname + ")"
--> 578                 if self._title     : self._vlabel = self._title + self._vlabel
    579                 if self._data_log  : self._vlabel = "Log[ "+self._vlabel+" ]"
    580                 if self.dim==1:

AttributeError: 'TrackParticles' object has no attribute '_title'

**Comment by mccoys** [comment]
You are trying to plot non-sorted data, which is impossible. However, you are supposed to get an explicit error. Which version of smilei is it ? If you have recently updated smilei in a new folder, have you done `make happi`?

Try again your same command with `getData` instead of `plot`
