### ISSUE TITLE
Particles per cell

### ISSUE THREAD

**Issue by ottcsconsult** [SmileiPIC/Smilei#114]
Hi Smilei Team!

I'm trying to run a Smilei simulation with a thermal CH plasma (working on ICF, looking to simulate laser plasma instabilities). So I have electrons and "CH" ions with A=6.5 and Z=3.5 and n_i = n_e / 3.5 so that the plasma is neutral. I'm using 16 particles per cell for the electrons, but I'm confused about what to set for the ions for particles per cell. Should I be setting 16/3.5 (which won't work, because the number has to be integer, right?) or is the number of pseudoparticles per cell of the ion species just a resolution thing and not influencing the physics (except if its too low resolution, through numerics)?

Thanks in advance for your kind support. I'm asking somewhat naive question as I'm a novice in PIC. My background is hydro/mdh/radiation.

**Comment by mccoys** [comment]
The `number_density` or `charge_density` parameters set the physical density, while the number of particles per cell is a numerical approximation similar to a *resolution* indeed. To accommodate for different numbers of particles per cell among species, each particle is assigned a statistical `weight` that represents its contribution to the plasma density. This weight is automatically computed.

**Comment by ottcsconsult** [comment]
Thank you! Very helpful!
