### ISSUE TITLE
install Smlei code errors

### ISSUE THREAD

**Issue by QJohn2017** [SmileiPIC/Smilei#118]
Hi, when I installed the SmleiPIC code on Super computing center, when I type the command `make`, some errors are occurred:

![13](https://user-images.githubusercontent.com/31507149/58876831-c61cbd00-8701-11e9-817a-f3d7906f605f.jpg)
.....
![14](https://user-images.githubusercontent.com/31507149/58876850-d339ac00-8701-11e9-8162-257bc6649c99.jpg)

And when I type some other command , it returns:
![Inked15_LI](https://user-images.githubusercontent.com/31507149/58877018-47744f80-8702-11e9-92a5-69de15af4fd6.jpg)

![16](https://user-images.githubusercontent.com/31507149/58877046-5c50e300-8702-11e9-9d26-a55607452560.jpg)

![17](https://user-images.githubusercontent.com/31507149/58877079-768ac100-8702-11e9-9c49-ae63796424a7.jpg)

![18](https://user-images.githubusercontent.com/31507149/58877100-82768300-8702-11e9-9488-f0e2b50b566d.jpg)

![19](https://user-images.githubusercontent.com/31507149/58877112-899d9100-8702-11e9-86bd-d8aae827012a.jpg)

![20](https://user-images.githubusercontent.com/31507149/58877117-8efadb80-8702-11e9-919e-4ea6bdbb5bb7.jpg)

So, I don't know how to resolve it , can you help me ?

**Comment by QJohn2017** [comment]
@jderouillat , I reinstalled the `picsar` again and setting PICSAR to TRUE in the makefile, then when I compile the Smlei code again, it is successful. Thank you !
PS: in your reply above, you said that  the current implementation (domain splitting, boundary conditions) of the picsar coupling is very constraining and you are working on a new one. Is it means that i can't use the pseudo spectral solver in Smlei code ?

**Comment by jderouillat** [comment]
if you really want to test the current status check that `$FFTW3_LIB/libfftw3.*`, `$FFTW3_LIB/libfftw3_mpi.*`, `$FFTW3_LIB/libfftw3_threads.*` and `$LIBPXR/libpxr.*` exist.  

To be clear, we let aside the cartesian coupling for the moment for 2 main reasons :
- the domain decomposition used with the PS solver locked strongly the patch decomposition used in Smilei
- PML boundary conditions are not implemented, it worked correctly in a periodic environment.

But we took over this problem some time ago in a slightly different context, which I hope, will benefit you.

**Comment by QJohn2017** [comment]
Okay, i will test the PICSAR later. Here i have already compiled the Smilei code successful. Now i want to test this code in parallel mode. In my super computing center, I want to use 4 nodes, and 1 node has 24 cores, How should I write the script file to submit a job?

**Comment by beck-llr** [comment]
You have to see that with your system admin. Typically, try to set a single MPI process per socket and a number of openMP threads equal to the number of cores per socket.
