### ISSUE TITLE
Wrong time on postprocessing

### ISSUE THREAD

**Issue by emil-mouz** [SmileiPIC/Smilei#119]
## Description
Hello,

I'm trying to run a simple case of ion acceleration and I've encounter a problem while I try to visualize some diagnostics. Specifically, I don't get the simulation time that I expected. 
I expected around 110 femto at the end of the simulation, while I get 776 femto.
(Attached I have the python script)

![Figure_7-1](https://user-images.githubusercontent.com/45740200/58877919-bb026680-86da-11e9-9924-fd03fdf6f136.png)

Post-Processing:
```
import happi
import pint   
import math
S=happi.Open("./", reference_angular_frequency_SI=2.*math.pi*299792458/(0.8e-6))
Ekin=S.ParticleBinning(0,units=["MeV","um","m^-3/MeV","fs"])
Ekin.plot(figure=7)
```

Any ideas? Thank you in advance...

[SMILEI_IONS_output.txt](https://github.com/SmileiPIC/Smilei/files/3252211/SMILEI_IONS_output.txt)
[2d_ion_acceleration (python input scirpt).txt](https://github.com/SmileiPIC/Smilei/files/3252215/2d_ion_acceleration.python.input.scirpt.txt)

**Comment by mccoys** [comment]
What time is displayed when you don't specify `reference_angular_frequency_SI` ?

**Comment by emil-mouz** [comment]
![Figure_7-1](https://user-images.githubusercontent.com/45740200/58914292-cda28d00-8726-11e9-80c6-8c47ddf3a009.png)

**Comment by mccoys** [comment]
Well, dividing this time by your reference frequency seems to give 776 fs.

Your output file does not show the same value. Are you sure this is the correct simulation?

**Comment by emil-mouz** [comment]
I think it is. But in any case, just to be sure, I just did one more simulation with different Tsim.


[SMILEI_IONS(output).txt](https://github.com/SmileiPIC/Smilei/files/3256353/SMILEI_IONS.output.txt)
[2d_ion_acceleration_(python).txt](https://github.com/SmileiPIC/Smilei/files/3256354/2d_ion_acceleration_.python.txt)
```
```
import happi
import pint   
import math

S=happi.Open("./", reference_angular_frequency_SI=2.*math.pi * 299792458/(0.8e-6)) 
Ekin=S.ParticleBinning(0,units=["MeV","um","m^-3/MeV","fs"])
Ekin.plot(figure=7)
```

```

![Figure_8-1](https://user-images.githubusercontent.com/45740200/58944017-9618fc80-8789-11e9-839b-4a50eee354ac.png)

import happi
import pint   
import math
S=happi.Open("./")
Ekin=S.ParticleBinning(0,units=["MeV","um","m^-3/MeV","fs"])
Ekin.plot(figure=7)

![Figure_8-2](https://user-images.githubusercontent.com/45740200/58944019-987b5680-8789-11e9-9ef6-570c11dc5c8c.png)

**Comment by mccoys** [comment]
Which version of the code are you using ?

**Comment by emil-mouz** [comment]
4.1

**Comment by mccoys** [comment]
How come your plots are in log scale, whereas your commands don't require log scale ?

Note that I tried on my machine and everything works

**Comment by emil-mouz** [comment]
You are right,  I posted a wrong post-processing script 

```
Ekin=S.ParticleBinning(0,units=["MeV","um","m^-3/MeV","fs"],data_log=True)
Ekin.plot(figure=7)
Ekin.animate(figure=7)
```
But not another simulation. I've triple checked it, I would check it once more but I'm sure that  the result it's the one that  I posted

I'm running SMILEI-4.1 and then I postprocess the ParticleBinning0.h5 file, with  the latest commit. In principle it shouldn't affect this  but  I just mentioned it.

**Comment by mccoys** [comment]
I am still unable to reproduce the error :/

Did you remove all the output files before running again the simulation ? Did you use a new folder ?

**Comment by emil-mouz** [comment]
Ok now I got my wrong, I only transferred the ParticleBinning0.h5 file into my postprocessing file, instead of the whole folder.. Didn't know that time data was on another file, I though was included into ParticleBinning0.h5.

Thank you for you help, have a nice day.
