### ISSUE TITLE
Momentum spread 

### ISSUE THREAD

**Issue by arsampath** [SmileiPIC/Smilei#122]
Dear developers,

We initialize a relativistic electron beam of gamma ~20000. We specify maxwell-juettner momentum distribution and temperature = [0.6, 0.6, 0.6].
The plot of momentum distribution in x, also the kinetic energy of the electron beam at t=0 shows an unusually large spread not compatible with a temperature of just 0.6mc^2.

Even when we try with a temperature of [0.0001, 0.6, 0.6], the momentum distribution in x and ekin at t=0 show an unusually large spread.

Kindly find the attached test input file and figures.
![ekin](https://user-images.githubusercontent.com/27001896/59446715-50e87080-8e02-11e9-924a-f36862c46fc4.png)
![px](https://user-images.githubusercontent.com/27001896/59446722-534aca80-8e02-11e9-8b81-05488327703d.png)
[test_beam.txt](https://github.com/SmileiPIC/Smilei/files/3286998/test_beam.txt)

**Comment by mccoys** [comment]
For a relativistic species, there is no good definition of an anisotropic temperature.
Please use an isotropic temperature, such as `[0.0001, 0.0001, 0.0001]`

**Comment by arsampath** [comment]
Thank you for the reply. The figure shown above was obtained using isotropic temperature = [0.6, 0.6, 0.6]. Could you please explain why the momentum spread is so broad?

**Comment by mccoys** [comment]
@MickaelGrechX , is it possible that the temperature of 0.6 (in the drifting frame) makes such a wide spectrum in the lab frame ?

**Comment by MickaelGrech** [comment]
Sorry for the late answer.
SMILEI actually provides correct results.
In the figure below, I compare SMILEI results to the theory for the distribution in p_x.
This is done for T=0.6mc^2, drift velocity along x at a velocity corresponding to a Lorentz factor g0=20000 (close to your conditions).
You can see that there is a perfect match.
![image](https://user-images.githubusercontent.com/18305634/60411744-83e67e80-9bce-11e9-99bd-e266783c0196.png)

Btw, note that it is customary to define the temperature (of e.g. a Maxwell-Juttner distribution as done here) in the proper frame of the distribution. This is why, even though T=0.6mc^2 looks small, if leads to quite a broad distribution in the frame were the beam drifts.

**Comment by arsampath** [comment]
Thank you for your time and explanation.
