### ISSUE TITLE
Incorrect initialisation with collisions

### ISSUE THREAD

**Issue by arsampath** [SmileiPIC/Smilei#124]
We started the same simulation WITH and WITHOUT collisions. 
The simulation WITHOUT collisions runs without problems and initialises the fields and the beam consistently. 
The simulation WITH collisions either crashes or does not initialise the field correctly.
The input file and the stdout and stderr files are attached. 

The problem occurs also with a 'cold' beam. 

[Test_NO_collisions copy.txt](https://github.com/SmileiPIC/Smilei/files/3290655/Test_NO_collisions.copy.txt)
[Test_YES_collisions copy.txt](https://github.com/SmileiPIC/Smilei/files/3290657/Test_YES_collisions.copy.txt)

[YES_COLLISION_stderr.4872997.txt](https://github.com/SmileiPIC/Smilei/files/3290666/YES_COLLISION_stderr.4872997.txt)
[YES_COLLISION_stdout.4872997.txt](https://github.com/SmileiPIC/Smilei/files/3290667/YES_COLLISION_stdout.4872997.txt)

[NO_COLLISION_stdout.4872573.txt](https://github.com/SmileiPIC/Smilei/files/3290677/NO_COLLISION_stdout.4872573.txt)

 Smilei version : 4.1

**Comment by mccoys** [comment]
You already have reported issues with collisions : #110 
We know that this is related to incompatibilities with QED.

We are working on it

**Comment by arsampath** [comment]
Thank you for the response. 
This issue remains without the use of QED module. Kindly find the attached input and std files.
[stderr.4900643.txt](https://github.com/SmileiPIC/Smilei/files/3296006/stderr.4900643.txt)
[stdout.4900643.txt](https://github.com/SmileiPIC/Smilei/files/3296007/stdout.4900643.txt)
[Test_YES_collisions.py.txt](https://github.com/SmileiPIC/Smilei/files/3296008/Test_YES_collisions.py.txt)

**Comment by mccoys** [comment]
I am actually unable to reproduce your issue on my machine.

Could you try the latest push, and see if it still happens ?

**Comment by mccoys** [comment]
@arsampath Could you try the latest version and see if the problem still persists ?

**Comment by arsampath** [comment]
I do not get the error with the latest version.
