### ISSUE TITLE
Tunnel ionization + Radiation Reaction

### ISSUE THREAD

**Issue by arsampath** [SmileiPIC/Smilei#126]
Dear developers,

Does the tunnel ionization model work with radiation reaction model? 
Can the species where ionized electrons are added radiate in SMILEI?

Thank you for your time.

**Comment by mccoys** [comment]
This possibility has not been tried yet (i think). We have recently been working towards having all effects with particle creation (ionization, QED, ..) to work well together, but this is not really well tested yet.

Please provide an example if it does not work for you

**Comment by arsampath** [comment]
Thank you for your prompt response and sorry for these many questions. 
The following input file was used for my test run.
*Tunnel ionization* is switched on for *Gold ion*.
And *radiation reaction* for the corresponding *plasma electrons*.
I am using the latest master branch from the SMILEI github page. 
I am attaching the output and error file I receive. 
[stderr.5018094.txt](https://github.com/SmileiPIC/Smilei/files/3307034/stderr.5018094.txt)
[stdout.5018094.txt](https://github.com/SmileiPIC/Smilei/files/3307035/stdout.5018094.txt)
[text_ionization_radiation.txt](https://github.com/SmileiPIC/Smilei/files/3307036/text_ionization_radiation.txt)

**Comment by arsampath** [comment]
Dear developers, 

Were you able to reproduce the error/investigate this question?
Thank you for your time.

**Comment by mccoys** [comment]
I have not had time yet. Will do when possible

**Comment by mccoys** [comment]
Please try the latest version. Close the issue if it fixes your problem.

**Comment by arsampath** [comment]
It works. Thank you for the fix.
