### ISSUE TITLE
Linking hydro code with Smilei : Warnings in charge profile initialization

### ISSUE THREAD

**Issue by lesnat** [SmileiPIC/Smilei#129]
Hi !

I'm working on e- acceleration using laser-solid interaction, and as you maybe know, the initial state of the target (mainly the density gradient of the pre-plasma) can strongly influence the energy of accelerated e-.

In order to model this properly, it is possible to simulate the pre-plasma formation with hydro code, and initialize PIC simulation with hydro output. What is often done in this case is taking an exponential fit of the pre-plasma density, and re-create this function in the PIC initialization.

However, thank to Smilei's Python initialization file, I think it could be quite easy to really initialize the PIC profiles (densities, temperatures, velocity, charge) with hydro output. Since the hydro grids and the PIC grids have no reason to be the same, an interpolation have to be done (it seems that in my case, the function scipy.interpolate.griddata works well while scipy.interpolate.interp2d takes a lot of time to compute the interpolated profiles).

I got some hydro (FLASH) results, and I can get a slice in it to get 1D or 2D profiles from 3D simulation. I'm then exporting the profiles in columns in a text file, and interpolate it to initialize my Smilei input profiles. It seems to work, but when initializing patches I got this warning :

> [WARNING] Could not match exactly charge=7.28 for species iZ13 (difference of 0.08). Try to add particles.

I'm then trying to understand how does the profiles are initialized to avoid this warning, and this is here you can maybe help me !

I think the condition `ne = Zstar * ni` must be fulfilled (with `ni` being ion density, `Zstar` ion charge state and `ne` electron density), and so I tried to initialize `ne` with `Zstar * ni` profile, to avoid numerical uncertainties, but the warning remain.

When I add many particles the warning disappear, so I don't think this is a bug but only a lack of understanding for me. However I would like to not have so many particles because in 2D it saturate the memory of the computer where I'm performing my simulations.

I join you a typical 1D namelist and hydro profiles if you want to do some tests. Even with no laser the target spontaneously explode because there is a huge Ex field in the initialization. I'm currently trying to fix it, but my question on how the charge profile is initialized remain.
[Smilei_1D.zip](https://github.com/SmileiPIC/Smilei/files/3324745/Smilei_1D.zip)

(To reproduce the warning you'll just need to lower the number of mepc and mipc, or change the interpolation method in griddata to "cubic")

Thank's by advance !
Léo.

**Comment by beck-llr** [comment]
Hi Leo
Always nice to read from you.
I insert real laser measurement into my Smilei simulations and I also have to do the kind of interpolation you're doing. I use `scipy.interpolate.RectBivariateSpline` which does a great job on regular meshes such as the ones we use in Smilei.

Technically, you are not forced to use an initially neutral plasma. That's why the Poisson equation is solved initially. But if your solution comes out of an hydro code, it is probably much safer to do so since the code probably assumes quasi neutrality.

When `Zstar` is not an integer, some particles in the cell will have Z and some other Z+1. You are not certain that the code will manage to find a configuration which has the mean value you specified. And the less particles you have, the less likely it is that there is one. See function initCharge in src/Species/Species.cpp.

Cheers

**Comment by lesnat** [comment]
Ok I get it ! Thank you for your answer :)

If some are interested by the solution I post it here :
Since macro-particles charge must be an integer, I had to round the values of the Zstar profile : for 1 decimals the number of macro-ion per cell must be at least 10, for 2 decimals it must be 100, ... 
The interpolation method must also not add decimals to Zstar, so one solution is to use a "nearest" interpolation method, or round the interpolated result to needed number of decimals.

It also seems that if the number of macro-ions per cell is not sufficient to correctly represent the charge profile, the non-neutrality of the plasma create huge Ex field in the simulation. However when the number of macro-ions per cell is correct there is no problem.

Thank's again !
Cheers,
Léo.

**Comment by beck-llr** [comment]
Actually it depends on the decimal. For instance Z=1.5 can be easily reproduced with only 2 particles. Z=1.3 is more complicated and you do need a minimum of 10 particles.
Glad we could help.
