### ISSUE TITLE
Density number: Issue with multiplied cos() values for trapezoidal()

### ISSUE THREAD

**Issue by T069** [SmileiPIC/Smilei#130]
I try to define the area/target where I have a density number `n0` for my plasma and `l0` is the wavelength. There is not only a rectangular target, but also a modulation on the left side of it before the Laser hits it.
So what I did is: defining a function for the `number_density` and puting the value of it inside the `trapezoidal()` function like this:
```
import math
import numpy

l0=2.0*math.pi

def den_profile(x,y):
    if ( 2.0*l0 < x < 4*l0):
        return n0 * ( 1 + numpy.cos (10.0 * numpy.pi* y) )
    else:
        return 0
```
And for the Species:
```
Species(
...
number_density = trapezoidal(den_profile,xvacuum=l0,xplateau=0.44*l0),
)
```

I get the message " [Python] TypeError: 'NoneType' object has no attribute \'__getitem\__' "
What I'm doing wrong?

**Comment by mccoys** [comment]
This is not the correct approach. The first argument of `trapezoidal()` must be a number, not a function.

Instead, you may first create a function earlier in your script: `trap=trapezoidal(...)`. Then use this function as `trap(x,y)` inside another function.

**Comment by Tissot11** [comment]
I have the same question/questions.

1. Can one construct and new density profile by multiplying built-in functions like _trapezoidal_ and _cosine_?  On taking a cue from _laser_wake_AM.py_ namelist (listed on tutorials), I tried to define _trapezoidal_ profile before and try to define a _cosine_ profile inside and multiply it with the _trapezoidal_ profile. However, I see error that _'function * function isn't allowed'_ and _'profile does not seem to return a correct value'_.  I could suppress the _function * function error_ by forcing the function to be Numpy array but it still says 'profile does not seem to return a correct value'.

2. Is it possible to pass somehow the plasma density as an argument in the _cosine_ function?

3. I also tried to understand text parsing and did two trials by defining the density profile in following way

    def denProfile(x,y):
    
           den = trapezoidal(n0,xvacuum=l0,xplateau=0.44*l0),

            return den,

    or 

     def denProfile(x,y):
    
            return trapezoidal(n0,xvacuum=l0,xplateau=0.44*l0),

   On both occasions, it complains about the _'profile does not seem to return a correct value'_. Of   course, calling these _functions_ directly inside the _Species_ block works fine though again not their product.

4. Lastly, any hints on how one can create a thin slab target (in _x_ direction) with a fixed density and a small external density modulations (in _y_ direction) imposed either on left or both sides of the target?

Thanks in advance!

**Comment by mccoys** [comment]
Let me explain, more clearly, my previous answer

```
trap = trapezoidal( n0, ... )

def den(x,y):
    return cos(x) * trap(x,y)
```

**Comment by Tissot11** [comment]
Sorry this doesn't seem to work either. I paste the _Namelist_ and _stdout_ files content

trap = trapezoidal(n0,xvacuum=l0,xplateau=0.44*l0),

def denProfile(x,y):
    
    return math.cos(x) * trap(x,y)


Species(
    name = 'ion',
    position_initialization = 'random',
    momentum_initialization = 'cold',
    particles_per_cell = 16,
    mass = 1836.0,
    charge = 1.0,
    number_density = denProfile,
    #number_density = trapezoidal(n0,xvacuum=l0,xplateau=0.44*l0),
    #number_density = cosine (0, yamplitude=0.01, ylength=Ly, yphi=0.0, ynumber=10.0 ),
    #number_density = trapezoidal(n0,xvacuum=l0,xplateau=0.44*l0),
    boundary_conditions = [
        ["remove", "remove"],
        ["periodic", "periodic"],
    ],
)
Species(
    name = 'eon',
    position_initialization = 'random',
    momentum_initialization = 'mj',
    particles_per_cell = 16,
    mass = 1.0,
    charge = -1.0,
    number_density = denProfile,
        #number_density = np.asarray(cosine (0, yamplitude=0.01, ylength=Ly, yphi=0.0, ynumber=10.0 ))*np.asarray(trapezoidal(n0,xvacuum=l0,xplateau=0.44*l0)),
    temperature = [0.001],
    boundary_conditions = [
        ["remove", "remove"],
        ["periodic", "periodic"],
    ], 
        # time_frozen = 0.1
)

and

Got 64.
                    _            _
  ___           _  | |        _  \ \   Version : v4.1-406-g1e82f25e-master
 / __|  _ __   (_) | |  ___  (_)  | |   
 \__ \ | '  \   _  | | / -_)  _   | |
 |___/ |_|_|_| |_| |_| \___| |_|  | |  
                                 /_/    
 
 

 Reading the simulation parameters
 --------------------------------------------------------------------------------
 HDF5 version 1.8.16
	 Python version 2.7.5
	 Parsing pyinit.py
	 Parsing v4.1-406-g1e82f25e-master
	 Parsing pyprofiles.py
	 Parsing RPA.py
	 Parsing pycontrol.py
	 Check for function preprocess()
	 python preprocess function does not exist
	 Calling python _smilei_check
	 Calling python _prepare_checkpoint_dir
	[WARNING] Change patches distribution to hilbertian
	[WARNING] simulation_time has been redefined from 125.663706 to 125.663706 to match timestep.
	[WARNING] Particles cluster width set to : 15
 

 Geometry: 2Dcartesian
 --------------------------------------------------------------------------------
	 Interpolation order : 2
	 Maxwell solver : Yee
	 (Time resolution, Total simulation time) : (23.873241, 125.663706)
	 (Total number of iterations,   timestep) : (3000, 0.041888)
	            timestep  = 0.942809 * CFL
	 dimension 0 - (Spatial resolution, Grid length) : (15.915494, 37.699112)
	             - (Number of cells,    Cell length)  : (600, 0.062832)
	             - Electromagnetic boundary conditions: (silver-muller, silver-muller)
                     - Electromagnetic boundary conditions k    : ( [1.00, 0.00] , [-1.00, -0.00] )
	 dimension 1 - (Spatial resolution, Grid length) : (15.92, 62.83)
	             - (Number of cells,    Cell length)  : (1000, 0.06)
	             - Electromagnetic boundary conditions: (periodic, periodic)
                     - Electromagnetic boundary conditions k    : ( [0.00, 1.00] , [-0.00, -1.00] )
 

 Vectorization: 
 --------------------------------------------------------------------------------
	 Mode: off
 

 Patch arrangement : 
 --------------------------------------------------------------------------------
 

 Initializing MPI
 --------------------------------------------------------------------------------
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	 [Python] TypeError: 'tuple' object is not callable
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
	[ERROR](0) src/Profiles/Profile.cpp:284 (Profile) Profile `nb_density ion`: does not seem to return a correct value
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[58936,1],0]
  Exit code:    1
--------------------------------------------------------------------------

**Comment by Tissot11** [comment]
Even if I try this

trap = trapezoidal(n0,xvacuum=l0,xplateau=0.44*l0),

def denProfile(x,y):
    
    return trap(x,y)

It says the same as before that _'profile does not seem to return a correct value'_. In this case I also get an extra _python_ error _[Python] TypeError: 'tuple' object is not callable_. I'm a bit perplexed.

**Comment by mccoys** [comment]
it could be because you have a comma `,` after your first line. This tells python that the object is a tuple. Could you try without the comma ?

**Comment by Tissot11** [comment]
Thanks for the tip! This mistake was annoying. Now it seems to be working.
