### ISSUE TITLE
smilei stops during initialization

### ISSUE THREAD

**Issue by flavorenti** [SmileiPIC/Smilei#134]
## Description

Hello, I'm trying to run smilei on a supercomputer in Nice (I already reported some issues with the installation, some days ago, but in the end it was solved). 
Now I'm trying to run a simulation (pretty small 272x272 grid with 25 ppc) you can see the initialization file attached:
[KH_test2_init.txt](https://github.com/SmileiPIC/Smilei/files/3358567/KH_test2_init.txt)

But the problem is that the code is hanging at the 'initialization diagnostic' point. As you can see from the output attached:
[Run_out.txt](https://github.com/SmileiPIC/Smilei/files/3358577/Run_out.txt)

I've also run the same code on marconi knl and it worked well (finished in 11 seconds), so I guess the problem is not in the init file, but on the nice machine (still using 1 node and 1 core on both machines) the code has ran for hours doing nothing.

I don't understand where this issue come from, please help me, I'm attaching the sbatch script as well:
[job_KH_test2.txt](https://github.com/SmileiPIC/Smilei/files/3358586/job_KH_test2.txt)

I have to say that in RUN.err (the error output) no problems were reported.

**Comment by jderouillat** [comment]
Hi,
Can you send the status on your working directory (`$ls -lrt workdir`) ?  
The idea is to now on with diagnostic is it hanging.
Julien

**Comment by flavorenti** [comment]
OK, sorry, problem solved. I've recompiled smilei using configuration='noopenmpi' and now it works. 
The problem was probably due to the fact that I'm using mpi not openmpi and in the compilation openmpi was considered as well.

**Comment by flavorenti** [comment]
Hi, I've realized that maybe I need openmpi for the simulation I will do. So I'm stuck with the same issue reported above. Here i report the result of ls -lrt:

##################

[flavorenti@pollux flavorenti]$ ls -lrt        
total 15601592
drwxr-xr-x 9 flavorenti lagrange           7 Jul 15 17:58 data_rosetta
drwxr-xr-x 2 flavorenti lagrange           0 Jul 16 09:34 checkpoints
-rw-r--r-- 1 flavorenti lagrange         124 Jul 16 10:37 pigeon.py
-rw-r--r-- 1 flavorenti lagrange        7939 Jul 16 11:36 RUN.out
-rw-r--r-- 1 flavorenti lagrange         512 Jul 16 11:41 RUN.err
-rwxr-xr-x 1 flavorenti lagrange       14765 Jul 16 12:03 test3D_init.py
-rw-r--r-- 1 flavorenti lagrange          30 Jul 16 13:48 end
-rw-r--r-- 1 flavorenti lagrange        7829 Jul 16 13:48 RUN1.out
-rw-r--r-- 1 flavorenti lagrange        3754 Jul 16 13:48 RUN1.err
-rw-r--r-- 1 flavorenti lagrange 15935676856 Jul 16 14:13 Fields0.h5
-rw-r--r-- 1 flavorenti lagrange        7101 Jul 16 14:13 RUN2.out
-rw-r--r-- 1 flavorenti lagrange         512 Jul 16 14:51 RUN2.err
-rw-r--r-- 1 flavorenti lagrange           0 Jul 16 15:24 scalars.txt
-rw-r--r-- 1 flavorenti lagrange        5315 Jul 16 15:24 RUNnew.out
-rw-r--r-- 1 flavorenti lagrange         512 Jul 16 15:41 RUNnew.err
-rw-r--r-- 1 flavorenti lagrange          30 Jul 16 15:41 start
-rwxr-xr-x 1 flavorenti lagrange    40227056 Jul 16 15:41 smilei
-rw-r--r-- 1 flavorenti lagrange         274 Jul 16 15:41 RUN2new.err
-rw-r--r-- 1 flavorenti lagrange       64775 Jul 16 15:41 smilei.py
-rw-r--r-- 1 flavorenti lagrange           0 Jul 16 15:41 profil.txt
-rw-r--r-- 1 flavorenti lagrange         705 Jul 16 15:41 patch_load.txt
-rw-r--r-- 1 flavorenti lagrange        5315 Jul 16 15:47 RUN2new.out
-rwxr-xr-x 1 flavorenti lagrange        1041 Jul 16 16:03 job_test3D.ll

############################################

The code is running (called test3D and writing in RUN2new.out) but it is hanging in the 'DIAGNOSTIC INIZIALIZATION' part, I attach the output file as well.
[RUN2new.txt](https://github.com/SmileiPIC/Smilei/files/3397486/RUN2new.txt)
Let me know, Thanks

**Comment by mccoys** [comment]
I can run your input file without any bug. I suspect that there is an issue with the way you use MPI and OpenMP.

Could you try running only 1 MPI process ?

**Comment by flavorenti** [comment]
If I use 1 MPI process I get the same problem: the  code hangs at 'initializing diagnostics' (output file attached). 
[RUN.txt](https://github.com/SmileiPIC/Smilei/files/3401003/RUN.txt)

Anyways I'm not sure about how MPI and OpenMP are installed on the cluster, these are the modules  loaded:
#####################################
[flavorenti@castor test0]$ module list
Currently Loaded Modulefiles:
  1) userspace/OCA                4) intel/mkl/2019.1.053         7) intel/python3/2019.1.053
  2) gnurt/8.3                    5) intel/compilers/2019.1.053
  3) mpi/2019.1.053               6) intel/tbb/2019.1.053
###############################################

**Comment by jderouillat** [comment]
On another supercomputer, I observed this kind of behavior if diagnostics files exist from a previous simulation.  
Deleting its, permits to run correctly the simulation.

**Comment by flavorenti** [comment]
The problem persists

**Comment by flavorenti** [comment]
Ok, I've made a bunch of tests and I hope these can shade a bit of light on the problem.
I've decided to run smilei without openMP, just using MPI with as much MPI processes as cores I have. 
But I keep having problems, the code runs well if I do pretty small box with not so many particles (like 640x320x80 and 25 ppc and patches 16x8x2) on something like 80 cores.
But when I increase the resolution (doubling resolution and patches in all directions and doubling ppc), and so the number of cores to 256, the code gets stuck at "Diagnostic Initialization" and usually returns error (sometimes it just get stuck for a long time). As you can see from the output file attached:
[RUN_err.txt](https://github.com/SmileiPIC/Smilei/files/3409674/RUN_err.txt)
[RUN_out.txt](https://github.com/SmileiPIC/Smilei/files/3409675/RUN_out.txt)
The error look like something related to the MPI protocols, I get something similar even in other tests when I try to do heavy simulations on many cores (like >200).
Let me know if you have any ideas...

**Comment by jderouillat** [comment]
We don't use `MPI_Comm_dup`, it's used in HDF5 to open diagnostics files in parallel's writing.  
I remember an error which occurred at the very beginning of Irene on this function, with the OpenMPI provided, but it was linked to the `MPI_THREAD_MULTIPLE` mode that you have disable compiling without `OpenMP` (even if the code logs `MPI_THREAD_MULTIPLE enabled` with `config=noopenmp`, only `mpi_no_tm` disable it).   
What the MPI library that you are using, the supercomputer's module prints mpi/version. Could you send the result of `mpirun --version` ?

**Comment by flavorenti** [comment]
Well this is the mpi version:
###################################
[flavorenti@pollux ~]$ mpirun --version
Intel(R) MPI Library for Linux* OS, Version 2019 Update 4 Build 20190430 (id: cbdd16069)
Copyright 2003-2019, Intel Corporation.
#######################################
And the module loaded (in which there is also mpi) are:
Currently Loaded Modulefiles:
  1) userspace/OCA            5) intel/compilers/2019.4
  2) gnurt/8.3                6) intel/tbb/2019.4
  3) mpi/2019.4               7) intel/python3/2019.4
  4) intel/mkl/2019.4

**Comment by jderouillat** [comment]
It 's the library that we use the more.  
Could you try to reinstall a HDF5 library according to what we use :
```bash
$ tar zxvf hdf5-*.*.*.tar.gz
$ cd hdf5-*.*.*
$ ./configure --prefix=${INSTALL_DIR}/hdf5 --enable-parallel --with-pic --enable-linux-lfs --enable-shared --enable-build-mode=production --disable-sharedlib-rpath --enable-static CC=mpicc FC=mpif90
make
$ export HDF5_ROOT_DIR=${INSTALL_DIR}/hdf5
```
And then for Smilei make clean ; make config=noopenmp
