### ISSUE TITLE
Use of Smilei on TGCC (KNL)

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#135]
Hi Smilei users,

I installed smilei on TGCC with KNL flags for compilation.
When I launch a job, I always have the same error:

[0] MPI startup(): ofa fabric is not available and fallback fabric is not enabled
srun: error: irene3379: task 0: Exited with exit code 254

Any ideas?
Thanks a lot

**Comment by juliencelia** [comment]
And to complete, I had no error when I compiled Smilei...

**Comment by mccoys** [comment]
Could you include your submission script, your relevant `bash_profile` or other environment configuration ?

**Comment by juliencelia** [comment]
[2189798err.txt](https://github.com/SmileiPIC/Smilei/files/3361450/2189798err.txt)

[job_sub.txt](https://github.com/SmileiPIC/Smilei/files/3361451/job_sub.txt)

[baschrc_irene.txt](https://github.com/SmileiPIC/Smilei/files/3361460/baschrc_irene.txt)


Here are : 1) the .err 2) the submission script (you will recognize it) and 3) bashrc

Thank you for your help mccoys

**Comment by jderouillat** [comment]
Hi Julien,
The Irene's KNL environment do not allow to use IntelMPI because of its specific interconnection network.  
So the environment that we use is :
```bash
$ module load hdf5
$ module switch flavor/hdf5/serial flavor/hdf5/parallel
$ export HDF5_ROOT_DIR=${HDF5_ROOT}
$ export OMPI_MCA_btl_portals4_use_rdma=0
```
The last command of this list is to disable a MPI protocol which hangs on Irene for some Smilei's simulations.  
With OpenMPI on Irene we have another constraint on communications that we can't operate from threads, so we have to disable this feature compiling with the option `config="no_mpi_tm"`.
Be careful to clean the first compilation before compiling in this way : 
```bash
$ make clean
$ make config="no_mpi_tm"
```
Regards

Julien

**Comment by jderouillat** [comment]
`make config="no_mpi_tm" machine="irene_knl"` !

**Comment by juliencelia** [comment]
Hi Julien

I est the environment as you said me.
When I try to make config="no_mpi_tm" I have this error:

src/Tools/H5.h(9): catastrophic error: cannot open source file "hdf5.h"
  #include <hdf5.h>

Smilei doesnt find hdf5...

Sorry I am not an expert in installation...

**Comment by juliencelia** [comment]
It's OK! 
Thank you very much Julien!

**Comment by juliencelia** [comment]
Compilation is ok. Smilei runs.
But I have a problem, simulation crashes in creation of patches (80%) and I have this error message:

slurmstepd-irene3272: error: Detected 1 oom-kill event(s) in step 2190749.0 cgroup.
srun: error: irene3272: task 0: Out Of Memory

The simulation has no problem on the cluster CURTA.

**Comment by beck-llr** [comment]
You are using a single KNL node and a single MPI process. Was it already the case on CURTA ? How does a single node memory of CURTA compare to the memory of an Irene KNL node ?

**Comment by juliencelia** [comment]
Sorry I didn't change these parameters since my 1D simulation.
It works fine.

Thanks to everyone.
