### ISSUE TITLE
Laser normalized vector potential when omega is set to other values than 1

### ISSUE THREAD

**Issue by deuterium33** [SmileiPIC/Smilei#136]
Dear Smilei developers,

This is not an issue but a more basic question that would save me some time not looking at the source code.
When in the input python file you define omega=2 in the Laser section, does the a0 needs to be given as if omega was equal to 1 (as for the reference frequency across the units in the code) or is it the corrected a0 for omega=2. which needs to be given?

Thanks!

**Comment by mccoys** [comment]
This has actually been changed very recently. Which version are you using? And how and where did you download it from?

**Comment by deuterium33** [comment]
Hi! I use the release version 4.1, downloaded from https://smileipic.github.io/Smilei/_downloads/smilei-v4.1.tar.gz

**Comment by beck-llr** [comment]
In that version the computation of a0 always assumes omega=1. If I'm not mistaken, only the latest release obtained from the git repo uses the proper user defined omega to evaluate a0.

**Comment by deuterium33** [comment]
Thanks!

**Comment by takumiminami** [comment]
I faced this problem with version 4.6.
In use of omega=2*pi, a0 is needed to be 1/(2*pi) to make a0=1.
Is that a correct behavior??
Or could you tell me from which version the behavior has changed??
Thanks!

**Comment by mccoys** [comment]
What do you mean by `a0 is needed to be 1/(2pi) to make a0=1` ??
If you set `a0` to 1, then the value of `a0` is 1.

If you are talking about the value of fields, then be careful. If I remember correctly, the peak field value is proportional to `a0 x omega`.

**Comment by takumiminami** [comment]
Thank you for replying!

I'm sorry to use ambiguous words.
I meant the value of fields.
So, your answer is, 
" In the newest version of Smilei, if we want to make the field value at a0=1, we have to describe a0=1/(2*pi) in the case with the input parameter of omega=2*pi in the namelist file," isn't it??

**Comment by mccoys** [comment]
`a0` is not the field. If you want field value = 1, then you need to adapt your `a0` as you said.

**Comment by mccoys** [comment]
Still I don't understand why you would ever need omega =  2 pi

**Comment by takumiminami** [comment]
Thank you for your comment, I understand.

The reason why we put omega=2pi is we input reference length as 1.
In my current use, reference length l0 =1, reference time t0 = 1, then I have to input as omega=2pi to make sure the laser wavelength is proper in the case.

Such use causes something bad??
I don't see such use, i.e. omega=2pi, in exercise namelists.

**Comment by mccoys** [comment]
We always use omega=1. I don't see anything wrong with 2 pi
