### ISSUE TITLE
Relativistic field initialization in 2D

### ISSUE THREAD

**Issue by Mi3Sangal** [SmileiPIC/Smilei#137]
Dear developers,

We plot the initial fields for the electron bunch in Smilei's benchmark "tst3d_electron_bunch_wake.py" using the latest GitHub version downloaded today.

Here is a contour plot and lineout of "Ey" at t = 0 obtained with this benchmark file.
![benchmark_Ey](https://user-images.githubusercontent.com/34055763/60717728-0b135980-9f23-11e9-85ff-8153e0243513.png)
![benchmark_Ey_lineout](https://user-images.githubusercontent.com/34055763/60717729-0b135980-9f23-11e9-83da-cc5b2fd8e3fb.png)

However, we just modified the same benchmark file and ran it in 2D.
Here are the corresponding plots for "Ey" at t = 0 and the modified 2d input benchmark file.
![benchmark_2d_Ey](https://user-images.githubusercontent.com/34055763/60717745-136b9480-9f23-11e9-9dcb-2999b1f55e65.png)
![benchmark_2d_Ey_lineout](https://user-images.githubusercontent.com/34055763/60717746-136b9480-9f23-11e9-8e20-b7e031d7f45c.png)
[2d_benchmark.txt](https://github.com/SmileiPIC/Smilei/files/3362386/2d_benchmark.txt)

In 3D, we see that the fields drop towards the transverse boundaries, as is expected.
However, we don't observe this in 2D.
We understand that the fields would drop faster in 3D than in 2D. But we don't see even a small decrease in the fields towards the boundaries in 2D. 

We also tried the same but with 6 times increased transverse box size. However, we do not see any change even in this case.

Could you explain why this is happening? Could it be a problem with the relativistic Poisson solver in 2D? 

Thank you for your help.

**Comment by mccoys** [comment]
You might have a very small box compared to the bunch size.

**Comment by Mi3Sangal** [comment]
sftp://sangal@lfs1.mpi-hd.mpg.de/home/theo/sangal/l1/largebox_benchmark_Ey.png
sftp://sangal@lfs1.mpi-hd.mpg.de/home/theo/sangal/l1/largebox_benchmark_Ey_lineout.png

**Comment by Mi3Sangal** [comment]
As I mentioned above, we also tried with a 6 times larger box size in the transverse direction. We did this in the benchmark of Smilei in 3D and 2D (the modified input file of the benchmark for 2d attached above). And as mentioned, we saw the same issue in field initialisation in 2D. 

Here are the plots for 3D. As expected, the fields decrease towards the boundaries.
![largebox_benchmark_Ey](https://user-images.githubusercontent.com/34055763/60723288-87ae3400-9f33-11e9-96c7-3f01478ea515.png)
![largebox_benchmark_Ey_lineout](https://user-images.githubusercontent.com/34055763/60723290-87ae3400-9f33-11e9-9f17-c9a3e1b897c8.png)



Here are the plots for 2D. Even with a 6 times bigger box size transversely, the fields do not decrease towards the boundaries.
![largebox_benchmark_2d_Ey](https://user-images.githubusercontent.com/34055763/60723297-90066f00-9f33-11e9-885a-72156681500b.png)
![largebox_benchmark_2d_Ey_lineout](https://user-images.githubusercontent.com/34055763/60723298-90066f00-9f33-11e9-9506-1b7e262cf991.png)

**Comment by Z10Frank** [comment]
Thank you for your question.
As you said, the field decreases more slowly in 2D than in 3D. Remember that a 2D simulation is like having all the derivatives along z equal to zero, so it's like having a bunch that is gaussian in the x-y plane, but infinite in the z direction. 

Besides, the higher the relativistic Lorentz factor gamma, the more large the field will be transversally. If you use a gamma=10, having a window 6 times larger will allow to see the field decrease as desired. With a gamma =200, I run the same simulation with trans = 4. and ntrans = 1600 (a window 80 times larger than in your case) and I only start to see it decreasing. 

From a numerical point of view, the implemented Poisson solver (and the relativistic Poisson solver) for the initialisation have a fixed boundary condition. You could experiment implementing different transverse boundary conditions, in the routine `ElectroMagn2D::compute_Ap_relativistic_Poisson` in `Electromagn2D.cpp`, to obtain a more realistic decrease of the fields. Indeed in the future it could be useful to be able to choose the Poisson boundary conditions (periodic, von Neumann or Dirichlet). I will discuss this improvement with the other developers. 

Soon the relativistic beam field initialization will be released in cylindrical geometry, so you'll be able to obtain a quasi-3D accuracy at the cost comparable to 2D simulations.

**Comment by Mi3Sangal** [comment]
Thank you very much for your detailed response.!

**Comment by MickaelGrech** [comment]
Ok, so after discussing with Matteo here at the EPS I had another look at this issue.
Clearly, and as far as we are looking at initial fields (at time t=0), I think that the 2D field not decreasing is first correct, and second can be easily explained.
Indeed, to get the (quasi-static) electromagnetic fields around the electron bunch, we go in a frame where the bunch is standing (proper frame of the bunch), and consider that the bunch has existed for a time long enough for the static electric field to have built up and satisfy the Poisson equation. 
(Later these fields will be transformed back to the lab/simulation frame, but for now, let us remain in the bunch proper frame!).

In the bunch proper frame, the electron bunch is a very elongated cylinder, its length in the propagation direction being increased by a factor \gamma (\gamma being the bunch electrons' Lorentz factor) while its transverse size remains unchanged. In 3D, the perpendicular electric field produced by an infinite cylinder decreases as 1/r (this by the way works also really nicely close to a finite cylinder, i.e. at a distance r smaller than the cylinder length). In 2D, however, the elongated bunch can actually be approximated by an infinite (in the direction of propagation) slab! In that case, the perpendicular field does not decay with the distance to the cylinder! It is what you observe in your 2D simulations! 

Now, you may argue that your electron bunch as a finite size in the propagation x-direction. If I check the input file you refer to, the characteristic length of the bunch is of the order of lx~15 c/omega_p in the lab/simulation frame, which translate in the proper frame to lx' = \gamma lx ~ 3 10^5 c/omega_p. Hence, you can expect the perpendicular field to remain constant on a length of the order of lx', or at least 1 tenth of lx', way larger than the width of your simulation box!
Note btw that this is the case in both the proper frame & lab frame as the field spatial dependence along the perpendicular direction is not changed by a Lorentz boost.

I hope this convince you that SMILEI results are correct.
In a next post, I will try to explain why you may actually work around this by just not considering these electromagnetic fields.

**Comment by MickaelGrech** [comment]
OK, so first, let me estimate the maximum perpendicular electric field you should get in your 2D simulation. 
As I said before, you can approximate the electron bunch in the proper frame by an infinite slab with max density ne' = ne/gamma, and profile \propto exp(-y^2/2/R^2), with R the radius (unchanged from the lab frame). The maximum field you get in the proper frame is Ex_max' = \sqrt{\pi/2} R ne'; which translate in the lab/simulation frame to Ex_max = \gamma Ex_max' = \sqrt{\pi/2} R \gamma ne' = \sqrt{\pi/2} R ne. Plugging your numbers \gamma = 2x10^4, ne = 0.0017 n0,  R = 8 c/omega_p; one gets Ex_max =  0.017 Er, with Er = me c \omega_p / e the normalization field.
This is exactly what SMILEI returns!

Now this field is extremely small. So my question is, are you sure you need to account for it?
Can you not start not solving Poisson equation for this species?

**Comment by Z10Frank** [comment]
The 4.2 version of the code has just been released. In the benchmarks folder, the files
`tst3d_12_relativistic_electron_beam_field_initialization.py`
`tstAM_12_relativistic_electron_beam_field_initialization.py`
can be found. 

The first one performs the usual initialisation of the relativistic beam field in 3D. The second file initialises the fields of the same beam, but with the azimuthal Fourier decomposition (for the beam field equivalent to cylindrical geometry). They use the same resolution and equivalent box dimension, so the results are in good agreement, but the computational time of the second simulation will be far smaller.

I hope this can help.

<img width="592" alt="Ey_bunch_3D_vs_AM" src="https://user-images.githubusercontent.com/9608804/60979710-769a6400-a333-11e9-88da-17e726b6b6e3.png">
