### ISSUE TITLE
Documentation error: TrackParticles diagnostics

### ISSUE THREAD

**Issue by andsunds** [SmileiPIC/Smilei#139]
## Description
In the documentation on the web page for the `TrackParticles` diagnostics, it is stated that you can get a particle's electrical charge through the attribute `"q"`. However that generates the error message 
```
[ERROR](0) src/Diagnostic/DiagnosticTrack.cpp:132 (DiagnosticTrack) DiagTrackParticles #1: attribute `q` unknown
```
I have found instead that specifying the attribute `"charge"` does not generate this error message. I don't know if/how this will affect downstream behavior (e.g. post processing).

I guess this is an easy fix.

## Parameters

- Smilei version: bv4.1-552-g2445d95-bmaster

**Comment by mccoys** [comment]
Correct, it should be ``"charge"``. Will be fixed soon.

**Comment by andsunds** [comment]
But now, when the simulation has run, I find that the charge information is stored under a dataset `"q"`. Perhaps just allowing the use of `"q"` in the namelist is the easiest way to unify the conventions.

**Comment by mccoys** [comment]
Good idea. I will actually keep both possibilities (backward compatibility), and submit the fix soon.

**Comment by mccoys** [comment]
Done in  6530a06
