### ISSUE TITLE
Input parameters species in SMILEI from hydrodynamic simulation

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#140]
## Description
When I run smieli importing ne, Te, Ti,... for species from a txt file, Smilei runs and craches after 3000 timesteps... Several tests and each time, I have the same result.

Any idea? Perhaps it's the scipy method griddata that can be a problem...

Thanks

Julien

My SMILEI input:
[gas2d.txt](https://github.com/SmileiPIC/Smilei/files/3396959/gas2d.txt)

My txt file from Hydro code:
[hydro.txt](https://github.com/SmileiPIC/Smilei/files/3396960/hydro.txt)

The log file smilei:
[log.txt](https://github.com/SmileiPIC/Smilei/files/3396964/log.txt)

**Comment by mccoys** [comment]
```
[WARNING] CFL problem: timestep=0.468971 should be smaller than 0.467025
```

;)

**Comment by juliencelia** [comment]
shame on me... close this issue ;)

**Comment by juliencelia** [comment]
Before closing this issue, an additional question... On CURTA cluster, the simulations runs. But when I try that type of input on IRENE_KNL, scipy is not found and simulation crashes... Do you know which module have I to load?

**Comment by mccoys** [comment]
I just load python

**Comment by beck-llr** [comment]
You can have a look at the `irene_knl` machine file in `scripts/CompileTools/machine/`. And don't forget to compile with `machine=irene_knl` and `config=no_mpi_tm`.

**Comment by juliencelia** [comment]
Smilei works perfectly on IRENE_KNL... 
But:
It's just I need scipy to read and interpolate my hydrocode parameters in smilei input (ne, Vi, Ti, Te...).
Even if I load python module (module load python/2.7.15) I have this error message in smilei log:

[ERROR](0) src/Params/Params.cpp:1165 (runScript) error parsing gas2d.py
         [Python] ImportError: No module named scipy.interpolate

So I tried pip install scipy --user then :
Requirement already satisfied (use --upgrade to upgrade): scipy in /ccc/products2/python-2.7.15/Atos_7__x86_64/intel--17.0.4.196__openmpi--2.0.4/default/lib/python2.7/site-packages

But smilei crashes also...

**Comment by mccoys** [comment]
Use the default python 2.7.14

**Comment by juliencelia** [comment]
I tried but I always have the same error...
And it's strange because in the python log I have that :


                    _            _
  ___           _  | |        _  \ \   Version : ??-??
 / __|  _ __   (_) | |  ___  (_)  | |
 \__ \ | '  \   _  | | / -_)  _   | |
 |___/ |_|_|_| |_| |_| \___| |_|  | |
                                 /_/



 Reading the simulation parameters
 --------------------------------------------------------------------------------
 HDF5 version 1.8.20
         Python version 2.7.5    : Alors que je fait bien le load python/2.7.14 (et dans le job_sub et dans mon baschrc)
         Parsing pyinit.py
         Parsing ??-??
         Parsing pyprofiles.py
         Parsing gas2d.py
        [ERROR](0) src/Params/Params.cpp:1165 (runScript) error parsing gas2d.py
        [ERROR](0) src/Params/Params.cpp:1165 (runScript) error parsing gas2d.py
         [Python] ImportError: No module named scipy.interpolate
        [ERROR](0) src/Params/Params.cpp:1165 (runScript) error parsing gas2d.py
        [ERROR](0) src/Params/Params.cpp:1165 (runScript) error parsing gas2d.py
        [ERROR](0) src/Params/Params.cpp:1165 (runScript) error parsing gas2d.py
        [ERROR](0) src/Params/Params.cpp:1165 (runScript) error parsing gas2d.py
        [ERROR](0) src/Params/Params.cpp:1165 (runScript) error parsing gas2d.py
        [ERROR](0) src/Params/Params.cpp:1165 (runScript) error parsing gas2d.py
        [ERROR](0) src/Params/Params.cpp:1165 (runScript) error parsing gas2d.py
        [ERROR](0) src/Params/Params.cpp:1165 (runScript) error parsing gas2d.py


________________________________
De : mccoys <notifications@github.com>
Envoyé : mercredi 17 juillet 2019 13:35
À : SmileiPIC/Smilei <Smilei@noreply.github.com>
Cc : juliencelia <julien.bonvalet@u-bordeaux.fr>; Author <author@noreply.github.com>
Objet : Re: [SmileiPIC/Smilei] Input parameters species in SMILEI from hydrodynamic simulation (#140)


Use the default python 2.7.14

**Comment by mccoys** [comment]
This is a question for the hotline I think

**Comment by juliencelia** [comment]
I try thé hotline. Thanks.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by xxirii** [comment]
Try to load scipy interpolate outside Smilei. For instance you can try one of the web example in ipython to check that Python alone works fine

**Comment by juliencelia** [comment]
Message from TGCC hotline:

Bonjour,

Il y a une erreur dans l'installation de smilei. L'installation utilise le python système qui ne contient pas la bibliothèque scipy.interpolate.

ldd /ccc/products/smilei-4.1/intel--17.0.4.196__openmpi--2.0.2/default/smilei
        linux-vdso.so.1 =>  (0x00007ffd22988000)
        /usr/$LIB/libshook.so => /usr/lib64/libshook.so (0x00002b9174f18000)
        libhdf5.so.10 => /ccc/products/hdf5-1.8.20/intel--17.0.4.196__openmpi--2.0.2/parallel/lib/libhdf5.so.10 (0x00002b9175123000)
        libpython2.7.so.1.0 => /lib64/libpython2.7.so.1.0 (0x00002b91756ed000)

Le cluster n'a pas de connexion internet, vous ne pouvez pas installer de paquet python avec la commande pipe.

En attendant la réinstallation de smilei vous pouvez utiliser le contournement suivant dans votre script de soumission :
 bash -c 'LD_PRELOAD=/ccc/products/python-2.7.14/intel--17.0.4.196__openmpi--2.0.2/default/lib/libpython2.7.so.1.0:$LD_PRELOAD smilei'

Cordialement,
Pascal

**Comment by juliencelia** [comment]
For information:

If you put the command 
bash -c 'LD_PRELOAD=/ccc/products/python-2.7.14/intel--17.0.4.196__openmpi--2.0.2/default/lib/libpython2.7.so.1.0:$LD_PRELOAD smilei'
in your submission script between ccc_mprun and smilei it works!

Thanks to everyone.
