### ISSUE TITLE
Laser Rayleigh length or beam focusing f number

### ISSUE THREAD

**Issue by deuterium33** [SmileiPIC/Smilei#141]
Dear Smilei developers, 

I was wondering how to take into account the Rayleigh length of the laser, using the functions Laser or LaserGaussian2D. I am simulating a laser focused with a low f number optic and therefore the focusing/divergence angle (or Rayleigh length) is important to me in that case. Please let me know if this is implemented, or easily doable with the current code.

Thanks!

**Comment by mccoys** [comment]
The Rayleigh length is directly related to the waist. Choose your waist accordingly

**Comment by deuterium33** [comment]
Thanks I will check that. I asked because it seems like my LaserGaussian2D, defining waist=laser_r_fwhm/(math.sqrt(2.0*math.log(2.0))), looked like a planar wave... Maybe not enough distance from xmin to focus position in the box, or wrong value of waist in smilei units.

**Comment by deuterium33** [comment]
It looks that I did a typo in the distance before focus from which I was expecting to see the beam focusing, that is the reason. I close the question. Thanks!
