### ISSUE TITLE
Collisional ionisation "disperses" 10GeV beam

### ISSUE THREAD

**Issue by arsampath** [SmileiPIC/Smilei#142]
Dear developers,

In the attached input file, we have a 10GeV electron beam interacting with a stationary target.
We have used the latest SMILEI pull from GitHub.
The extra physics modules that we use are: Binary Coulomb collisions and collisional ionisation.

We see that this 10GeV electron beam “disperses” as soon as it starts interacting with the target. 
This is seen in the attached beam charge density plots.
This happens when the collisional ionisation module is switched ON.

Kindly help us in understanding the reason behind this.

![Rho_beam0](https://user-images.githubusercontent.com/27001896/61470792-eaff8380-a981-11e9-811d-ffa7262d041e.png)
![Rho_beam1500](https://user-images.githubusercontent.com/27001896/61470793-eaff8380-a981-11e9-833a-5bb106e33ca1.png)
![Rho_beam2000](https://user-images.githubusercontent.com/27001896/61470794-eaff8380-a981-11e9-9756-f14c96ce295e.png)
[no_poisson_yes_coll.py.txt](https://github.com/SmileiPIC/Smilei/files/3407256/no_poisson_yes_coll.py.txt)

**Comment by mccoys** [comment]
What do you mean 'disperse'?

There is still some electron cloud. Now there is a very dense electron layer, maybe this is where your target is ? These electrons are probably the ionized electrons.

**Comment by arsampath** [comment]
Thank you for the response. 

From what we see in the SMILEI collisional ionization module, the ***ionized*** electron species are being added to the ***ionizing*** electron species (in this case, the beam electrons). And this could be the reason why we are seeing this density plot for the beam electrons.

I would like to know if it is possible to specify the species in which the **_ionized_** electrons are added. 
In this case, we want the ionized electrons to be added to the electrons of the plasma.

**Comment by mccoys** [comment]
Yes, this possibility has been implemented recently: http://www.maisondelasimulation.fr/smilei/namelist.html#ionizing

**Comment by arsampath** [comment]
Thank you for the information!
