### ISSUE TITLE
set particle IDs in the beginning of simulation

### ISSUE THREAD

**Issue by jpsikal** [SmileiPIC/Smilei#143]
Dear Smilei developers,

I would be grateful if the code would enable to initialize particle IDs in the beginning of simulation. 
Alternatively, it could enable to use two TrackParticles diagnostics for the same particle species (that would also solve my problem). 

For my simulation study, I would need to select particle IDs after the first simulation run and then to track these particles (based on the selected IDs) from the beginning of the second simulation run (with otherwise the same simulation parameters). 

I tried to use two DiagTrackParticles blocks for the same species, but the simulation stopped with error message: In this version, species 'proton' cannot be tracked by two DiagTrackParticles. 

DiagTrackParticles(
    species = 'proton',
    every = [0, 1000000]
)

DiagTrackParticles(
    species = 'proton',
    every = [diagFirstTrack, 10],
    filter = myfilter1, 
    attributes = ['x', 'y', 'px', 'py', 'pz', 'weight', 'Ex', 'Ey', 'Bz']
)

I need to select high-energy particles from the first run and then to track the same high-energy particles (based on their IDs) from the beginning of the second run. 
I cannot track all particles from the beginning in the first run since it would generate enormous amount of data. 

Thanks for your help.

Jan

**Comment by mccoys** [comment]
The trick is to make a checkpoint early in the simulation, so that you can restart with the exact same particles IDs. The second simulation can have a different diagnostic.

**Comment by mccoys** [comment]
I forgot to mention that you should use the `filter` option to select the necessary IDs.

**Comment by jpsikal** [comment]
Thanks for your advice. Making a checkpoint early in the simulation and setting random_seed=0 in each simulation run solved my problem.

**Comment by mccoys** [comment]
Just a small piece of advice: `random_seed=smilei_mpi_rank`

This gives a different seed to the various MPI processes so that there is no periodicity artifact.

**Comment by jpsikal** [comment]
I tried random_seed=smilei_mpi_rank even before random_seed=0 but I found a slight discrepancy in the two simulation runs starting from the same checkpoint (energies of particles with the same ID differ, the difference was mostly below 5 percent in energy for the same ID). Then I tried random_seed=0 and it works well (no difference found in the energies of particles).
