### ISSUE TITLE
TrackParticles gets stuck

### ISSUE THREAD

**Issue by Tissot11** [SmileiPIC/Smilei#144]
I have a question regarding the TrackParticles sorting. When I sort the particle trajectories of "testelectron" using the following command

S.TrackParticles("testelectron", axes=["x","y"]).plot()

it starts reading the data at different timesteps but at the end it gets stuck on "Finalizing the ordering process". It takes sometimes few hours or even a day (around 24000 particle tracks) for it to finish. Afterwards while plotting it gives the following error

AttributeError: 'TrackParticles' object has no attribute '_getDataAtTime'

I also tried

TracElec=S.TrackParticles("testelectron",axes=["x","y"])

TracElec.getData()

TracElec.animate()

Sorting goes really fast this time. However, again I see the same error

'TrackParticles' object has no attribute '_getDataAtTime'

The generated figure window does flash for a second and it look like data being plotted but eventually it's a blank window with no data being shown.

It seems to an issue with Python environment as a colleague of mine seems not to have this problem (with plot() command). To avoid this problem, I tried with anaconda 2 and 3 virtual environment and complied the Smilei with PythonEXE from anaconda. Since anaconda doesn't provide a parallel version of hdf5, we had to install it separately and gave path to Smilei while compiling.  After these steps I would have thought that I could sort and plot particles tracks reasonable fast. Any thought what could be the cause of problem and what I could do to fix it? 

Thanks in advance!

**Comment by mccoys** [comment]
First, sorting many particles is a very costly operation. It is not very surprising that it is slow, especially with many timesteps. We have been thinking of better ways to do it, but it is unclear how much better it can get. Furthermore, making this process parallel is not easy either.

Now, if the sorting has been done once for a given simulation, it will not be needed again. Your second use of the same data will thus be much faster.

Concerning the error, I am not sure. I will need to test it. Were you able to reproduce it on smaller cases?  Which version of the code are you using?  If you have recently changed version, it is worth trying to `make happi` and see if this helps.

Concerning your plotting issue, does it happen only for this diagnostic? If yes, it could be related to the error above. Otherwise, this is a problem with the way python is called. If you start python from the command line to call a script, try `python -i myscript.py`.

**Comment by Tissot11** [comment]
Thanks for the quick reply! Yeah, for me it happens always though once with the smaller number of particle (4000) it did work. What I meant that using the .getData and .animate() commands were faster than .plot() command as mentioned in the first post. At the moment I have only encountered the plotting issue is only with this diagnostic. I paste below the output of running python -i command on my script. I had also forgotten to paste a warning before but it now included.

Process broken lines ...
/lfs/l8/theo/kumar/Code_Reposit_l8/smilei-v4.2/happi/_Diagnostics/TrackParticles.py:595: RuntimeWarning: invalid value encountered in greater
  self._rawData['brokenLine'] += self._np.abs(dudt).max(axis=0) > 1.
... done
Track particles: species 'testelectron' containing 24576 particles
Fontconfig warning: ignoring UTF-8: not a valid region tag
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "OrderedTrackFiles.py", line 23, in <module>
    TracElec.animate()
  File "/lfs/l8/theo/kumar/Code_Reposit_l8/smilei-v4.2/happi/_Diagnostics/Diagnostic.py", line 423, in animate
    self._plotOnAxes(ax, self._timesteps[0])
  File "/lfs/l8/theo/kumar/Code_Reposit_l8/smilei-v4.2/happi/_Diagnostics/Diagnostic.py", line 698, in _plotOnAxes_2D
    A = self._dataAtTime(t)
  File "/lfs/l8/theo/kumar/Code_Reposit_l8/smilei-v4.2/happi/_Diagnostics/Diagnostic.py", line 793, in _dataAtTime
    return self._vfactor*self._getDataAtTime(t)
AttributeError: 'TrackParticles' object has no attribute '_getDataAtTime'
>>> /usr/local/Packages/PIC/anaconda3/lib/python3.7/site-packages/matplotlib/font_manager.py:1241: UserWarning: findfont: Font family ['serif'] not found. Falling back to DejaVu Sans.
  (prop.get_family(), self.defaultFamily[fontext]))

**Comment by mccoys** [comment]
I just fixed the plotting issue. I forgot to update the tracked particles plotting after some plotting changes for v4.2. My bad.

Now, concerning the ordering process being very long, I suspect it is due to your usage of a filter in the namelist. Is this correct ? In that case, many particles are discarded, but they will still appear as `Nan` in the ordering process, just in case they are going to be filtered in later. This makes very large files with useless information. I have a plan to change that in the future, but right now, it is necessary. There is a hidden parameter in the `TrackParticles` happi diagnostic called `chunksize`, by default set to 20000000. It sets the portion of particles that will be treated at once for the ordering process. It is worth trying to set this parameter to a smaller value, although it is not clear it will help.

Is it really slow only after "Finalizing the ordering process", or is it slow before that as well ?

**Comment by Tissot11** [comment]
Thanks or looking into it. I'll fetch you commit and use the updated happi module. before I wasn't actually using filter but experimenting different number of particles from different simulations. I'll try also with the chunksize. After "Finalizing the ordering process" is done in couple of hours or in a whole night, it is definitely faster. However, after plot() command fails, python becomes unresponsive for few minutes at least.

**Comment by mccoys** [comment]
If you were not using the `filter` option and still experienced slow ordering, then there is something wrong. In a simulation with 6 million tracked particles, my laptop computer does the whole ordering in only 10 seconds.

Could you share the simulation input?

**Comment by Tissot11** [comment]
Ok. This is puzzeling then. I attach the content of the namelist below

---------
import math

Lx=128
Ly=32
Lz=32
ncellsx=Lx*8.0
ncellsy=Ly*8.0
ncellsz=Lz*8.0
dx=Lx/ncellsx
dy=Ly/ncellsy
dz=Lz/ncellsz
courdt  = 1./math.sqrt(1./(dx*dx) + 1./(dy*dy) + 1./(dz*dz))
dt = courdt/math.sqrt(3.)
gamma = 50
beta = math.sqrt(gamma*gamma - 1.0)/gamma
lxplasma = 0.85*Lx
lxvacuum = 0.5*(Lx - lxplasma)
lyplasma = 0.8*Ly
lyvacuum = 0.5*(Ly - lyplasma)
rest = 100.
gammalimit = 2*gamma

def f(x, y, z):
    if x<1.5*Lx: return 0.
    else: return 1.

def g(x, y, z):
    if x<1.5*Lx: return 0.
    else: return 0.5

Main(
    geometry = "3Dcartesian",
    
    interpolation_order = 2,

    timestep = dt,
    simulation_time = int(800/dt)*dt,

    cell_length  = [dx, dy, dz],
    grid_length = [ Lx, Ly, Lz],

    number_of_patches = [128, 4, 1],

#    clrw = ncellsx/32.,
    
    EM_boundary_conditions = [
        ["silver-muller", "silver-muller"],["periodic", "periodic"],["periodic", "periodic"],
    ],
    
    solve_poisson = False,
    print_every = 100,

    random_seed = smilei_mpi_rank
)

ExternalField(
    field = "Bx",
    profile = constant(2.0)
)

MovingWindow(
    time_start = 0.,
    velocity_x = beta,
)

LoadBalancing(
    initial_balance = False,
    every = 20,
    cell_load = 1.,
    frozen_particle_load = 0.1
)

Species( 
    name = "beamelectron",
    position_initialization = "random",
    momentum_initialization = "maxwell-juettner",
    particles_per_cell = 4,
    c_part_max = 1.0,
    mass = 1.0,
    charge = -1.0,
    charge_density = gaussian(0.1, xvacuum=lxvacuum, xlength=lxplasma, xfwhm=lxplasma/3.0, xcenter=Lx/2.0, xorder=2, yvacuum=lyvacuum, ylength=lyplasma, yfwhm=lyplasma/3.0, ycenter=Ly/2.0, yorder=2 ,zvacuum=lyvacuum, zlength=lyplasma, zfwhm=lyplasma/3.0, zcenter=Ly/2.0, zorder=2 ),
    mean_velocity = [beta, 0.0, 0.0],
    temperature = [0.001],
    pusher = "boris",    
    time_frozen = 0.0,
    boundary_conditions = [
        ["remove", "remove"],["periodic", "periodic"],["periodic", "periodic"],
    ],
)

Species(
    name = "beampositron",
    position_initialization = "random",
    momentum_initialization = "maxwell-juettner",
    particles_per_cell = 4,
    c_part_max = 1.0,
    mass = 1.0,
    charge = 1.0,
    charge_density = gaussian(0.1, xvacuum=lxvacuum, xlength=lxplasma, xfwhm=lxplasma/3.0, xcenter=Lx/2.0, xorder=2, yvacuum=lyvacuum, ylength=lyplasma, yfwhm=lyplasma/3.0, ycenter=Ly/2.0, yorder=2 ,zvacuum=lyvacuum, zlength=lyplasma, zfwhm=lyplasma/3.0, zcenter=Ly/2.0, zorder=2 ),
    mean_velocity = [beta, 0.0, 0.0],
    temperature = [0.001],
    pusher = "boris",
    time_frozen = 0.0,
    boundary_conditions = [
        ["remove", "remove"],["periodic", "periodic"],["periodic", "periodic"],
    ],
)

Species(
    name = "testpositron",
    position_initialization = "random",
    momentum_initialization = "maxwell-juettner",
    particles_per_cell = 4,
    c_part_max = 1.0,
    mass = 1.0,
    charge = 1.0,
    charge_density = gaussian(0.1, xvacuum=lxvacuum + 1.0*lxplasma/3.0, xlength=lxplasma/3.0, xfwhm=lxplasma/3.0, xcenter=Lx/2.0, xorder=2, yvacuum=lyvacuum + lyplasma/3.0, ylength=lyplasma/3.0, yfwhm=lyplasma/3.0, ycenter=Ly/2.0, yorder=2 ,zvacuum=lyvacuum + lyplasma/2.0 - 0.125, zlength=0.25, zfwhm=lyplasma/3.0, zcenter=Ly/2.0, zorder=2 ),
    mean_velocity = [beta, 0.0, 0.0],
    temperature = [0.001],
    pusher = "boris",
    time_frozen = 0.0,
    boundary_conditions = [
        ["remove", "remove"],["periodic", "periodic"],["periodic", "periodic"],
    ],
    is_test = True,
)



Species(
    name = "testelectron",
    position_initialization = "random",
    momentum_initialization = "maxwell-juettner",
    particles_per_cell = 4,
    c_part_max = 1.0,
    mass = 1.0,
    charge = -1.0,
    charge_density = gaussian(0.1, xvacuum=lxvacuum + 1.0*lxplasma/3.0, xlength=lxplasma/3.0, xfwhm=lxplasma/3.0, xcenter=Lx/2.0, xorder=2, yvacuum=lyvacuum + lyplasma/3.0, ylength=lyplasma/3.0, yfwhm=lyplasma/3.0, ycenter=Ly/2.0, yorder=2 ,zvacuum=lyvacuum + lyplasma/2.0 - 0.125, zlength=0.25, zfwhm=lyplasma/3.0, zcenter=Ly/2.0, zorder=2 ),
    mean_velocity = [beta, 0.0, 0.0],
    temperature = [0.001],
    pusher = "boris",
    time_frozen = 0.0,
    boundary_conditions = [
        ["remove", "remove"],["periodic", "periodic"],["periodic", "periodic"],
    ],
    is_test = True,
)


Species(
    name = "electron",
    position_initialization = "random",
    momentum_initialization = "maxwell-juettner",
    particles_per_cell = 4,
    c_part_max = 1.0,
    mass = 1.0,
    charge = -1.0,
    charge_density = 1.0,
    mean_velocity = [0.0, 0.0, 0.0],
    temperature = [0.01],
    pusher = "boris",
    time_frozen = 0.0,
    boundary_conditions = [
        ["remove", "remove"],["periodic", "periodic"],["periodic", "periodic"],
    ],
)

Species(
    name = "proton",
    position_initialization = "random",
    momentum_initialization = "maxwell-juettner",
    particles_per_cell = 4,
    c_part_max = 1.0,
    mass = 1836.0,
    charge = 1.0,
    charge_density = 1.0,
    mean_velocity = [0.0, 0.0, 0.0],
    temperature = [0.000000545],
    pusher = "boris",
    time_frozen = 1600.0,
    boundary_conditions = [
        ["remove", "remove"],["periodic", "periodic"],["periodic", "periodic"],
    ],
)

#DiagScalar(
#    every = 1000,
#)
DiagFields(
    every = 500,
)

DiagParticleBinning(
    deposited_quantity = "weight",
    every = 100,
    time_average = 1,
    species = ["beamelectron"],
    axes = [ ["moving_x",    0.,    Lx,    64],
             ["ekin",    1.,    gammalimit,    gammalimit] ]
)

DiagParticleBinning(
    deposited_quantity = "weight",
    every = 100,
    time_average = 1,
    species = ["beampositron"],
    axes = [ ["moving_x",    0.,    Lx,    64],
             ["ekin",    1.,    gammalimit,    gammalimit] ]
)

DiagParticleBinning(
    deposited_quantity = "weight",
    every = 100,
    time_average = 1,
    species = ["electron"],
    axes = [ ["moving_x",    0.,    Lx,    64],
             ["ekin",    1.,    gammalimit,    gammalimit] ]
)

DiagParticleBinning(
    deposited_quantity = "weight",
    every = 100,
    time_average = 1,
    species = ["proton"],
    axes = [ ["moving_x",    0.,    Lx,    64],
             ["ekin",    1.,    gammalimit,    gammalimit] ]
)

DiagTrackParticles(
    species = "testelectron",
    every = 1,
    flush_every = 1000,
#    filter = my_filter,
)

DiagTrackParticles(
    species = "testpositron",
    every = 1,
    flush_every = 1000,
#    filter = my_filter,
)

**Comment by mccoys** [comment]
This simulation is too large for a test. The number of tracked particles is closer to 200000 at the beginning of the simulation. Furthermore, I suspect that the moving window causes many many more particles to be created and tracked when the simulation advances. You might end up with billion of particles. Is that what happens ? How large is your `TrackParticlesDisordered_testelectron.h5` file ?

Do you really need so many test particles ? Why not choose less per cell ? Note that you can have less than 1 particle per cell.

**Comment by Tissot11** [comment]
The TrackParticlesDisordered_testelectron.h5 file is around 170 GB and indeed there are close 160000 particles but it's less than 6 million you were writing about. In the beginning we need to more particles but later on I select less particles to ensure  ergodicity of the radiation computation.

 But I have another simulation with less no of particles ~25000 and the TrackParticlesDisordered_testelectron.h5 file is only 20 GB. I still face the same issue (with Smilei 4.2 happi). I paste the content of that Namelist below.

import math

Lx=64
Ly=12
ncellsx=Lx*16.0
ncellsy=Ly*8.0
dx=Lx/ncellsx
dy=Ly/ncellsy
courdt  = 1./math.sqrt(1./(dx*dx) + 1./(dy*dy))
dt = courdt/math.sqrt(2.)
gamma = 50
beta = math.sqrt(gamma*gamma - 1.0)/gamma
lxplasma = 0.5*Lx
lxvacuum = 0.5*(Lx - lxplasma)
lyplasma = 0.5*Ly
lyvacuum = 0.5*(Ly - lyplasma)
rest = 100.
gammalimit = 2*gamma

def f(x, y, z):
    if x<1.5*Lx: return 0.
    else: return 1.

def g(x, y, z):
    if x<1.5*Lx: return 0.
    else: return 0.5

Main(
    geometry = "2Dcartesian",
    
    interpolation_order = 2,

    timestep = dt,
    simulation_time = 3000.,

    cell_length  = [dx, dy],
    grid_length = [ Lx, Ly],

    number_of_patches = [64, 8],
    
    EM_boundary_conditions = [
        ["silver-muller", "silver-muller"],["silver-muller", "silver-muller"],
    ],
    
    solve_poisson = True,
    print_every = 100,

    random_seed = smilei_mpi_rank
)

MovingWindow(
    time_start = 0.,
    velocity_x = beta,
)

LoadBalancing(
    initial_balance = False,
    every = 20,
    cell_load = 1.,
    frozen_particle_load = 0.1
)

Species( 
    name = "beamelectron",
    position_initialization = "regular",
    momentum_initialization = "maxwell-juettner",
    particles_per_cell = 36,
    c_part_max = 1.0,
    mass = 1.0,
    charge = -1.0,
    charge_density = gaussian(1.0, xvacuum=lxvacuum, xlength=lxplasma, xfwhm=lxplasma/3.0, xcenter=Lx/2.0, xorder=2, yvacuum=lyvacuum, ylength=lyplasma, yfwhm=lyplasma/3.0, ycenter=Ly/2.0, yorder=2 ),
    mean_velocity = [beta, 0.0, 0.0],
    temperature = [0.001],
    pusher = "boris",    
    time_frozen = 0.0,
    boundary_conditions = [
        ["remove", "remove"],["remove", "remove"],
    ],
)

Species(
    name = "beampositron",
    position_initialization = "regular",
    momentum_initialization = "maxwell-juettner",
    particles_per_cell = 36,
    c_part_max = 1.0,
    mass = 1.0,
    charge = 1.0,
    charge_density = gaussian(1.0, xvacuum=lxvacuum, xlength=lxplasma, xfwhm=lxplasma/3.0, xcenter=Lx/2.0, xorder=2, yvacuum=lyvacuum, ylength=lyplasma, yfwhm=lyplasma/3.0, ycenter=Ly/2.0, yorder=2),
    mean_velocity = [beta, 0.0, 0.0],
    temperature = [0.001],
    pusher = "boris",
    time_frozen = 0.0,
    boundary_conditions = [
        ["remove", "remove"],["remove", "remove"],
    ],
)

Species( 
    name = "testelectron",
    position_initialization = "regular",
    momentum_initialization = "maxwell-juettner",
    particles_per_cell = 1,
    c_part_max = 1.0,
    mass = 1.0,
    charge = -1.0,
    charge_density = gaussian(1.0, xvacuum=lxvacuum, xlength=lxplasma, xfwhm=lxplasma/3.0, xcenter=Lx/2.0, xorder=2, yvacuum=lyvacuum, ylength=lyplasma, yfwhm=lyplasma/3.0, ycenter=Ly/2.0, yorder=2 ),
    mean_velocity = [beta, 0.0, 0.0],
    temperature = [0.001],
    pusher = "boris",    
    time_frozen = 0.0,
    is_test = True,
    boundary_conditions = [
        ["remove", "remove"],["remove", "remove"],
    ],
)

Species(
    name = "testpositron",
    position_initialization = "regular",
    momentum_initialization = "maxwell-juettner",
    particles_per_cell = 1,
    c_part_max = 1.0,
    mass = 1.0,
    charge = 1.0,
    charge_density = gaussian(1.0, xvacuum=lxvacuum, xlength=lxplasma, xfwhm=lxplasma/3.0, xcenter=Lx/2.0, xorder=2, yvacuum=lyvacuum, ylength=lyplasma, yfwhm=lyplasma/3.0, ycenter=Ly/2.0, yorder=2),
    mean_velocity = [beta, 0.0, 0.0],
    temperature = [0.001],
    pusher = "boris",
    time_frozen = 0.0,
    is_test = True,
    boundary_conditions = [
        ["remove", "remove"],["remove", "remove"],
    ],
)


Species(
    name = "electron",
    position_initialization = "regular",
    momentum_initialization = "maxwell-juettner",
    particles_per_cell = 36,
    c_part_max = 1.0,
    mass = 1.0,
    charge = -1.0,
    charge_density = 1.0,
    mean_velocity = [0.0, 0.0, 0.0],
    temperature = [0.01],
    pusher = "boris",
    time_frozen = 0.0,
    boundary_conditions = [
        ["remove", "remove"],["remove", "remove"],
    ],
)

Species(
    name = "proton",
    position_initialization = "regular",
    momentum_initialization = "maxwell-juettner",
    particles_per_cell = 36,
    c_part_max = 1.0,
    mass = 1836.0,
    charge = 1.0,
    charge_density = 1.0,
    mean_velocity = [0.0, 0.0, 0.0],
    temperature = [0.000000545],
    pusher = "boris",
    time_frozen = 3000.0,
    boundary_conditions = [
        ["remove", "remove"],["remove", "remove"],
    ],
)

DiagScalar(
    every = 1000,
)
DiagFields(
    every = 100,
)

DiagParticleBinning(
    deposited_quantity = "weight",
    every = 100,
    time_average = 1,
    species = ["beamelectron"],
    axes = [ ["moving_x",    0.,    Lx,    64],
             ["ekin",    1.,    gammalimit,    gammalimit] ]
)

DiagParticleBinning(
    deposited_quantity = "weight",
    every = 100,
    time_average = 1,
    species = ["beampositron"],
    axes = [ ["moving_x",    0.,    Lx,    64],
             ["ekin",    1.,    gammalimit,    gammalimit] ]
)

DiagParticleBinning(
    deposited_quantity = "weight",
    every = 100,
    time_average = 1,
    species = ["electron"],
    axes = [ ["moving_x",    0.,    Lx,    64],
             ["ekin",    1.,    gammalimit,    gammalimit] ]
)

DiagParticleBinning(
    deposited_quantity = "weight",
    every = 100,
    time_average = 1,
    species = ["proton"],
    axes = [ ["moving_x",    0.,    Lx,    64],
             ["ekin",    1.,    gammalimit,    gammalimit] ]
)

DiagTrackParticles(
    species = "testelectron",
    every = 1,
)

DiagTrackParticles(
    species = "testpositron",
    every = 1,
)

**Comment by mccoys** [comment]
Would it be possible for you to zip and send me the 20GB file ? Use, for example, send.firefox.com.
For more privacy, you can send me the link using https://gitter.im.

I would need also the `smilei.py` file that is located in the simulation directory.

Note also that, instead of copy-pasting large input files in GitHub, please attach them as files.

**Comment by Tissot11** [comment]
I attach the pdf of smieli.py since attaching any other textfile isn't supported here. This was the reason I was pasting the content before. I'm also trying to compress the tracks.h5 file and I'll send you the link on gitter.im if I can succeed.
[smilei.pdf](https://github.com/SmileiPIC/Smilei/files/3457681/smilei.pdf)

**Comment by mccoys** [comment]
I cannot use the pdf file, sorry. It is definitely supported to attach text files as other users usually do. Simply click on the panel below the text, where it indicates `attach files...`.

**Comment by Tissot11** [comment]
It's strange. When I try to attach from Safari Browser it shows the following message. Which I can attach since it's a screenshot.It appears that I can upload only certain files.


<img width="645" alt="Screenshot 2019-08-01 at 19 37 52" src="https://user-images.githubusercontent.com/31315017/62314740-02676200-b494-11e9-964c-29b05bcd7adf.png">

**Comment by mccoys** [comment]
Yes, you have to change the extension to .txt

**Comment by Tissot11** [comment]
[smilei.txt](https://github.com/SmileiPIC/Smilei/files/3458784/smilei.txt)

Ok. attached it. I'll try a new run with smaller time step tomorrow and send you file on gitter.im

**Comment by Tissot11** [comment]
I ran the simulation for short amount of time and used the newer version of happi on GitHub with your corrections. To my it didn't get stuck at "Finalizing the ordering process" for 39000 particles. However the plotted figure doesn't look correct. I attach the Namelist where one can choose a larger number e.g. (200 in line no. 37) for running the simulation for longer time. When I run for longer time it again gets stuck at "Finalizing the ordering process" however not for smaller time using the new version of happi. I attach the files here. Since for smaller simulation time it doesn't get stuck, there is no need to send the trackfiles? For longer time, the files are around 20 GB so I can't send on firefox.

[smilei.txt](https://github.com/SmileiPIC/Smilei/files/3461393/smilei.txt)
![fig1](https://user-images.githubusercontent.com/31315017/62372855-cf2ade80-b538-11e9-8d20-80e86d890e50.png)
[fireball.txt](https://github.com/SmileiPIC/Smilei/files/3461394/fireball.txt)

**Comment by mccoys** [comment]
No need to send the file of it works for you. When I have time (not before a couple weeks) I can try running a longer simulation and see what is going on.

Concerning your graph, it is hard to see if things are wrong or not. There are too many particles. Try using the select option to reduce their number and investigate their trajectories.

If you have time, you could try to investigate a simulation with tracked particles but no moving window (search in the benchmarks for instance), and see if it causes the slow post process. I suspect the moving window could perturb that. On my machine, the post process is very fast, even for many millions of particles

**Comment by Tissot11** [comment]
I'll try it without the moving window and also check the plotting for fewer number of particles. I'll let you on Monday.

**Comment by mccoys** [comment]
@Tissot11 How many processes/threads do you use in your cases where the analysis is long ?

**Comment by Tissot11** [comment]
For this simulation I had try both 256✕1 and 4✕32 type configurations. The later configuration I only used for short-run simulation where things could work. For running simulations at longer time I used 256✕1 and 512✕1 configurations and I saw the problem. I'm sorry I couldn't run a simulation without moving window as I need to do some other simulations urgently and one of them is also taking too long to finish in a 512✕1 configuration. If that doesn't finish that I'll post it another thread.

**Comment by mccoys** [comment]
I tried your case without any difficulties so I am not sure what could be the problem.

**Comment by Tissot11** [comment]
This is peculiar. Which version of python you use? I tried using ipython and Spyder from both anaconda2 and anaconda3 distributions and I'm still having the same issues as before. Any suggestion what I can try? A colleague of mine managed to have this worked without problems by using some other virtual environments.

**Comment by mccoys** [comment]
I think the problem is unrelated to python. It sounds like an issue with HDF5 or your filesystem configuration. It might also be the python wrapper h5py

**Comment by Tissot11** [comment]
Since anaconda does not ship a parallel version of hdf5, our SysAdmin installed hdf5 seperately and used the same version of hdf5 as with anaconda distribution. When I compile the SMILEI, I use the following commands

PYTHON_CONFIG=/usr/local/Packages/PIC/anaconda2/bin/python-config HDF5_ROOT=/usr/local/Packages/PIC/hdf5 LDFLAGS='-Wl,-rpath,/usr/local/Packages/PIC/hdf5/lib,-rpath,/usr/local/Packages/PIC/anaconda2/lib' make SHELL='sh -x' -j4

Does anything look suspicious to you? And if yes, then do you recommend something?

**Comment by mccoys** [comment]
The problem would not be in how you compile smilei, but on how hdf5 was compiled. The problem might be elsewhere, for instance in the filesystem structure. Maybe large files are treated differently?

**Comment by Tissot11** [comment]
Ok. I switched to lfs (luster file system) a while ago due to high I/O needed by SMILEI. I'll talk with our SysAdmin to figure something out. Thanks.

**Comment by mccoys** [comment]
By the way, you did not specify whether the chunksize parameter helped. Did you try?

**Comment by Tissot11** [comment]
Ahh sorry I forgot to try this _chunksize_ parameter. I’ll try it tonight. Should settings it to 1000 be sufficient?

**Comment by mccoys** [comment]
Too small. Try from 100000 to 10000000

**Comment by Tissot11** [comment]
I tried with 10000000, 1000000 and 100000. Same result. It gets stuck after Finalising the order process.

**Comment by Tissot11** [comment]
An update: I finished one simulation with 40000 tracking particles. For this I used hdf5 1.8.21 and the current versions of _smilei_ and _happi_ from Github. I can plot the trajectories in _iPython_. It takes 20-30 minutes  for it create a _trackparticle.h5_ file and display the result (unlike 8-9 hours it took before) I attach one snapshot here. You can see that it looks physical unlike the figure I posted before in this thread. I still need to see what happens if I use 80000 track particles. Incidentally,  plotting the same trajectories in _Spyder_ doesn't work and I get the following error

self._xy = np.column_stack(np.broadcast_arrays(x, y)).astype(float)

MemoryError

I just thought to let you know in case this error in _Spyder_ helps in understanding the issues.

**Comment by mccoys** [comment]
Thank you for reporting. The MemoryError simply means that python does not have access to enough memory for all the particles. It is probably unrelated to you other problem.

**Comment by mccoys** [comment]
I just realized that your issue might be cause by the h5py package. Could you find out your version using:
```
import h5py
print(h5py.version.info)
```

I solved another problem today related to `h5py`. I am still unsure how it could affect your case.

**Comment by mccoys** [comment]
I am also a bit lost in the long exchange we have had. Could you confirm that only the ordering is slow, or is it also the plotting ?

You can separate both steps using:
```
D=S.TrackParticles(.....)
```

and then
```
D.plot()
```

**Comment by Tissot11** [comment]
Sorry I didn't clarify before. It appears to be the problem with sorting than plotting. Sorting get's stuck for 20-30 minutes on _Finalising the ordering process_. But it's still better than the 8-9 hours it took before. Plotting works fine in _iPython_ but not in _Spyder_. And if I use a cluster with higher CPU clock frequency then plotting doesn't take more than 3-4 minutes for 40000 particles (For higher than 40000 I have to still see).

**Comment by Tissot11** [comment]
> I just realized that your issue might be cause by the h5py package. Could you find out your version using:
> 
> ```
> import h5py
> print(h5py.version.info)
> ```
> 
> I solved another problem today related to `h5py`. I am still unsure how it could affect your case.


Sorry, I didn't notice the  question about h5py earlier. I was using _hdf5 1.10.4_ and _h5py 2.9.0_ before. Now I'm using _hdf5 1.8.21_ and _h5py 2.10.0_.

**Comment by mccoys** [comment]
I might have stumbled upon one possible reason for the slow processing. It might be related to the number of timesteps in the output. How many timesteps did you output ? Did you try with different numbers of outputs ?

**Comment by mccoys** [comment]
@Tissot11 please try the latest fix. It might solve your issue

**Comment by Tissot11** [comment]
> I might have stumbled upon one possible reason for the slow processing. It might be related to the number of timesteps in the output. How many timesteps did you output ? Did you try with different numbers of outputs ?

I had about 54000 times-steps. For smaller number of time-steps (20000) it was working probably alright as I had tried it few months ago and discussed here as well. Thanks for looking into this again. I'll fetch the latest commit and sort the trajectories. Do I need to run the simulation again or just using new Happi module with the latest corrections is sufficient?

**Comment by mccoys** [comment]
you dont need to run a new simulation

**Comment by mccoys** [comment]
I forgot to specify that you need to remove the TrackParticles_***.h5 file so that the ordering will be fine again. Keep the file that contains `Disordered`!!

**Comment by Tissot11** [comment]
Thanks for tip! I was going to do this. Sorry I couldn't find time yet to give you feedback but I try to do as soon as possible.

**Comment by Tissot11** [comment]
I tried it but unfortunately it got worse for me. Before on a CPU with higher clock frequency it can take 3-4 minutes to _Finalizing the ordering process_, now it takes more than an hour.

**Comment by mccoys** [comment]
This is very strange. Are you sure you updated? Did you do `make happi` again? 
How many processes did you run use?

**Comment by Tissot11** [comment]
yes, I fetched the latest commits from GitHub and compiled the _code_ and _happi_ again. What do you mean my processes? I had ran this simulation a while back in 512✕1 configuration.

**Comment by mccoys** [comment]
Ok. I think it has to do with the number of processes. I'll have to work on that aspect

**Comment by mccoys** [comment]
I have tried new changes recently. Please try when possible

**Comment by Tissot11** [comment]
Thanks! Should I try 4.3 or pull the latest version on GitHub?

**Comment by mccoys** [comment]
The latest

**Comment by Tissot11** [comment]
Thanks. I'll try.

**Comment by mccoys** [comment]
Any success ?

**Comment by Tissot11** [comment]
Sorry for delay in replying! I tried it with new _happi_ version. Now it takes 10-15 minutes to plot all the 40000 trajectories, even on a machine with faster _CPU_ where it took 3-4 minutes two months ago.  But it's better than 1 hours which the last version of _happi_ took. Now the finalizing the ordering is fast. The most time is taken on loading the data and plotting the results.

On a side note, somehow _make happi_ doesn't install newer version of _happi_ in my virtual enviroment. I had to also manually copy the _happi_ folder in the _python_ library of my virtual environment after _make happi_. Is this expected?

**Comment by mccoys** [comment]
The long plotting time might be solved by changing the chunksize.

Good that the ordering is now faster. 

To install a newer version of happi, you need to make sure that the variable PYTHONEXE is set to the python executable you are using. For instance, if you use python3, you have to set it to that version.

**Comment by mccoys** [comment]
By the way, the time for plotting trajectories is probably not related to the cpu, but to the disk access, and the memory. I am not sure how good is the comparison on a different machine. Anyways, please open a fresh issue if you find it went slower on the same machine.
