### ISSUE TITLE
Segfault on a cluster using radiation model

### ISSUE THREAD

**Issue by Iuliana19** [SmileiPIC/Smilei#145]
Hello,

I am trying to study photons production in laser - plasma (electrons + protons) simulation, using the radiation model Monte Carlo. On my computer, the code works fine, but on a cluster (I am using Curta-Mcia ), I am continuously getting the error "Segmentation fault" when the laser hits the plasma (the error is reproducible using different number of nodes and mpi processes). 

I saw another issues regarding this, I also tried the Boris pusher instead of vay, and I got the same error. 
Also, the radiation module works fine on the cluster in the case of laser and electron beam simulation.

Am I missing something in my namelist regarding the laser interaction with ions ? 

I attached my namelist:
[laserplasma.txt](https://github.com/SmileiPIC/Smilei/files/3455402/laserplasma.txt)

Thank you!
Iuliana

**Comment by xxirii** [comment]
Dear @Iuliana19,

I will have a look at your case. Can you give me more information about your environment : compiler, mpi library, number of nodes, cores, processors...

Thank you

**Comment by Iuliana19** [comment]
Thank you!

So, the characteristics of the cluster:
300 nodes, 2 processors Intel® Xeon® Gold SKL-6130 @ 2,1 GHz per node (32 cores per node)

compiler gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
module mpi/intel/2019.3.199

When I submitted the simulation, I used:

#SBATCH -N 4
#SBATCH -tasks-per-node=32
#SBATCH --constraint=compute
#SBATCH --time=36:00:00
export OMP_NUM_THREADS=16
export OMP_SCHEDULE=dynamic
export KMP_AFFINITY=granularity=fine,scatter

mpirun -np 8 -ppn 2 -bind-to socket ./smilei laserplasma2.py >log 2>err

I tried with 2 node, 3, 8, 10, 20 (and I changed the number of MPI processes accordingly).
Also, I tried with only 1 node, but in this case the simulation crashed after initializing patches

Thank you!
Iuliana

**Comment by xxirii** [comment]
Dear @Iuliana19,

The work well on our Skylake machine. I suggest few correctiions for you:

- First, since you have the Intel compiler, I suggest you compile with it instead of GCC. Can you give me the result of the command `mpicxx -show` and `module list` on your cluster?
- Then, I have some doubt about your sbatch script. I do not have `-tasks-per-node` but `-ntasks-per-node`. For me, this is the number of MPI processes per node. Therefore, you an't specify `#SBATCH -tasks-per-node=32` and `OMP_NUM_THREADS=16`. Can you try:
```bash
#SBATCH -N 4 # Number of nodes
#SBATCH -ntasks-per-node=2  # MPI per node
#SBATCH --constraint=compute
#SBATCH --time=36:00:00
export OMP_NUM_THREADS=16
export OMP_SCHEDULE=dynamic
export KMP_AFFINITY=granularity=fine,scatter

mpirun -np 8 -ppn 2 -bind-to socket ./smilei laserplasma2.py >log 2>err
```

Note that I did 6000 iteration in 17 minutes with 2 nodes.

**Comment by Iuliana19** [comment]
Thank you! Here are the results:

[ivladisavlev@login02 case2]$ mpicxx -show
g++ -I/gpfs/softs/cluster/intel/psxe/2019.3/compilers_and_libraries_2019.3.199/linux/mpi/intel64/include -L/gpfs/softs/cluster/intel/psxe/2019.3/compilers_and_libraries_2019.3.199/linux/mpi/intel64/lib/release -L/gpfs/softs/cluster/intel/psxe/2019.3/compilers_and_libraries_2019.3.199/linux/mpi/intel64/lib -Xlinker --enable-new-dtags -Xlinker -rpath -Xlinker /gpfs/softs/cluster/intel/psxe/2019.3/compilers_and_libraries_2019.3.199/linux/mpi/intel64/lib/release -Xlinker -rpath -Xlinker /gpfs/softs/cluster/intel/psxe/2019.3/compilers_and_libraries_2019.3.199/linux/mpi/intel64/lib -lmpicxx -lmpifort -lmpi -lrt -lpthread -Xlinker --enable-new-dtags -ldl

[ivladisavlev@login02 case2]$ module list
Currently Loaded Modulefiles:
  1) compiler/intel/2019.3.199   2) mpi/intel/2019.3.199

I will try now the other corrections! Thank you

**Comment by xxirii** [comment]
Thank you,

Can you check that you have `mpiicpc`? In fact `mpicxx` is the general (and default) wrapper that is currently used by GCC. `mpiicpc` is the Intel MPI wrapper. I suggest you recompile by doing this:

- `make clean`
- `export SMILEICXX=mpiicpc` # This tells Smilei to use Intel
- `make -j 4 machine=irene_skl`   # you can use more than 4 cores if you want

The machine file `irene_skl` contains specific compiler flags for skylake processors and it will speedup your execution.

**Comment by Iuliana19** [comment]
Thank you!

I recompile it and I submitted the job on cluster. Is still running for the moment

**Comment by Iuliana19** [comment]
And I have mpiicpc:

[ivladisavlev@login02 case2]$ mpiicpc --version
icpc (ICC) 19.0.3.199 20190206
Copyright (C) 1985-2019 Intel Corporation.  All rights reserved.

**Comment by xxirii** [comment]
How is the new attempt?

**Comment by Iuliana19** [comment]
Well, 3h and is still running :)

**Comment by xxirii** [comment]
Good, I guess the photon exponential growth makes the simulation slower and slower. How many iterations have you run so far?

**Comment by Iuliana19** [comment]
Only 3000. I really hope it won't crash cause usually after 3000 it crashes

**Comment by xxirii** [comment]
I am very surprised you are still at this point. Is it the same input file as you propose above?

**Comment by Iuliana19** [comment]
Yes, is exactly the same input file. 
And here is my script:

#SBATCH -N 4
#SBATCH --ntasks-per-node=2
#SBATCH --constraint=compute

#SBATCH --time=36:00:00

export OMP_NUM_THREADS=16
export OMP_SCHEDULE=dynamic
export KMP_AFFINITY=granularity=fine,scatter

FOLDER=/scratch/ivladisavlev/case2
SMILEI=/gpfs/home/ivladisavlev/.local/Smilei/smilei


cp $SMILEI $FOLDER
cd $FOLDER
mpirun -np 8 -ppn 2 -bind-to socket ./smilei laserplasma2.py >log 2>err

**Comment by xxirii** [comment]
I read carefully the [doc](https://redmine.mcia.fr/projects/cluster-curta/wiki/Wiki) of your cluster. First of all, they put many times `-tasks-per-node` in their example but I think they did a mistake. On the [slurm help page](https://slurm.schedmd.com/sbatch.html), It is clearly written `-ntasks-per-node`. But this does not explain the performance issue.

It is possible that there is still a problem of thread placement. Therefore, I suggest a new sbatch script with a maximum of information:

```bash
#!/bin/bash
#SBATCH --job-name=smilei
#SBATCH --constraint=compute
#SBATCH --time=36:00:00
#SBATCH --ntasks=4                  # Number of nodes
#SBATCH --ntasks-per-node=2         # Number of MPI per node
#SBATCH --cpus-per-task=16          # Number of threads OpenMP
#SBATCH --threads-per-core=1        # 1 physical core per OpenMP thread
#SBATCH --time=00:30:00            
#SBATCH --output=smilei.err        
#SBATCH --error=smilei.out  

# Affinity if necessary
export KMP_AFFINITY="granularity=fine,scatter"

# Set of the environment with the modules
module load ....

# OMP properties
export OMP_NUM_THREADS=16
export OMP_SCHEDULE=dynamic
export OMP_PROC_BIND=true

# cleaning
rm *.h5

# Copy the latest executable
FOLDER=/scratch/ivladisavlev/case2
SMILEI=/gpfs/home/ivladisavlev/.local/Smilei/smilei

cp $SMILEI $FOLDER
cd $FOLDER

# Launch of the job
srun --mpi=pmi2 --cpu-bind=sockets,verbose ./smilei laserplasma2.py
```

Here I am using `srun` instead of `mpirun`. `srun` is wrapper `mpirun` for SLURM. It should include and understand the information you pass above more than mpirun. Try also to reload the modules in case of but I do not think it is the issue.

**Comment by xxirii** [comment]
If you run this script, can you show me what you get in the smilei.err and smilei.out. thank you

**Comment by Iuliana19** [comment]
Can you tell me which modules should I load at module load ... ? 
Are the ones when I am doing module list ?

**Comment by xxirii** [comment]
If the modules in the module list are automatically loaded, then it is not necessary to reload them I think. This means that it is the default environment.

**Comment by Iuliana19** [comment]
[ivladisavlev@login01 case2]$ cat smilei.out

ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for '....'
rm: cannot remove ‘*.h5’: No such file or directory
cpu-bind=MASK - n012, task  0  0 [350642]: mask 0xffff set
cpu-bind=MASK - n013, task  2  0 [428273]: mask 0xffff set
cpu-bind=MASK - n012, task  1  1 [350643]: mask 0xffff0000 set
cpu-bind=MASK - n013, task  3  1 [428274]: mask 0xffff0000 set
OMP: Warning #181: OMP_PROC_BIND: ignored because KMP_AFFINITY has been defined
OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
OMP: Warning #181: OMP_PROC_BIND: ignored because KMP_AFFINITY has been defined
OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #210: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 16-31
OMP: Info #156: KMP_AFFINITY: 16 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #179: KMP_AFFINITY: 1 packages x 16 cores/pkg x 1 threads/core (16 total cores)
OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 16 maps to package 1 core 0
OMP: Info #171: KMP_AFFINITY: OS proc 17 maps to package 1 core 1
OMP: Info #171: KMP_AFFINITY: OS proc 18 maps to package 1 core 2
OMP: Info #171: KMP_AFFINITY: OS proc 19 maps to package 1 core 3
OMP: Info #171: KMP_AFFINITY: OS proc 20 maps to package 1 core 4
OMP: Info #171: KMP_AFFINITY: OS proc 21 maps to package 1 core 5
OMP: Info #171: KMP_AFFINITY: OS proc 22 maps to package 1 core 6
OMP: Info #171: KMP_AFFINITY: OS proc 23 maps to package 1 core 7
OMP: Info #171: KMP_AFFINITY: OS proc 24 maps to package 1 core 8
OMP: Info #171: KMP_AFFINITY: OS proc 25 maps to package 1 core 9
OMP: Info #171: KMP_AFFINITY: OS proc 26 maps to package 1 core 10
OMP: Info #171: KMP_AFFINITY: OS proc 27 maps to package 1 core 11
OMP: Info #171: KMP_AFFINITY: OS proc 28 maps to package 1 core 12
OMP: Info #171: KMP_AFFINITY: OS proc 29 maps to package 1 core 13
OMP: Info #171: KMP_AFFINITY: OS proc 30 maps to package 1 core 14
OMP: Info #171: KMP_AFFINITY: OS proc 31 maps to package 1 core 15
OMP: Info #250: KMP_AFFINITY: pid 350643 tid 350643 thread 0 bound to OS proc set 16
OMP: Info #210: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-15
OMP: Info #156: KMP_AFFINITY: 16 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #179: KMP_AFFINITY: 1 packages x 16 cores/pkg x 1 threads/core (16 total cores)
OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 core 0
OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to package 0 core 1
OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to package 0 core 2
OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to package 0 core 3
OMP: Info #171: KMP_AFFINITY: OS proc 4 maps to package 0 core 4
OMP: Info #171: KMP_AFFINITY: OS proc 5 maps to package 0 core 5
OMP: Info #171: KMP_AFFINITY: OS proc 6 maps to package 0 core 6
OMP: Info #171: KMP_AFFINITY: OS proc 7 maps to package 0 core 7
OMP: Info #171: KMP_AFFINITY: OS proc 8 maps to package 0 core 8
OMP: Info #171: KMP_AFFINITY: OS proc 9 maps to package 0 core 9
OMP: Info #171: KMP_AFFINITY: OS proc 10 maps to package 0 core 10
OMP: Info #171: KMP_AFFINITY: OS proc 11 maps to package 0 core 11
OMP: Info #171: KMP_AFFINITY: OS proc 12 maps to package 0 core 12
OMP: Info #171: KMP_AFFINITY: OS proc 13 maps to package 0 core 13
OMP: Info #171: KMP_AFFINITY: OS proc 14 maps to package 0 core 14
OMP: Info #171: KMP_AFFINITY: OS proc 15 maps to package 0 core 15
OMP: Info #250: KMP_AFFINITY: pid 350642 tid 350642 thread 0 bound to OS proc set 0
OMP: Warning #181: OMP_PROC_BIND: ignored because KMP_AFFINITY has been defined
OMP: Warning #181: OMP_PROC_BIND: ignored because KMP_AFFINITY has been defined
OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #210: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-15
OMP: Info #156: KMP_AFFINITY: 16 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #179: KMP_AFFINITY: 1 packages x 16 cores/pkg x 1 threads/core (16 total cores)
OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 core 0
OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to package 0 core 1
OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to package 0 core 2
OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to package 0 core 3
OMP: Info #171: KMP_AFFINITY: OS proc 4 maps to package 0 core 4
OMP: Info #171: KMP_AFFINITY: OS proc 5 maps to package 0 core 5
OMP: Info #171: KMP_AFFINITY: OS proc 6 maps to package 0 core 6
OMP: Info #171: KMP_AFFINITY: OS proc 7 maps to package 0 core 7
OMP: Info #171: KMP_AFFINITY: OS proc 8 maps to package 0 core 8
OMP: Info #171: KMP_AFFINITY: OS proc 9 maps to package 0 core 9
OMP: Info #171: KMP_AFFINITY: OS proc 10 maps to package 0 core 10
OMP: Info #171: KMP_AFFINITY: OS proc 11 maps to package 0 core 11
OMP: Info #171: KMP_AFFINITY: OS proc 12 maps to package 0 core 12
OMP: Info #171: KMP_AFFINITY: OS proc 13 maps to package 0 core 13
OMP: Info #171: KMP_AFFINITY: OS proc 14 maps to package 0 core 14
OMP: Info #171: KMP_AFFINITY: OS proc 15 maps to package 0 core 15
OMP: Info #250: KMP_AFFINITY: pid 428273 tid 428273 thread 0 bound to OS proc set 0
OMP: Info #210: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 16-31
OMP: Info #156: KMP_AFFINITY: 16 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #179: KMP_AFFINITY: 1 packages x 16 cores/pkg x 1 threads/core (16 total cores)
OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 16 maps to package 1 core 0
OMP: Info #171: KMP_AFFINITY: OS proc 17 maps to package 1 core 1
OMP: Info #171: KMP_AFFINITY: OS proc 18 maps to package 1 core 2
OMP: Info #171: KMP_AFFINITY: OS proc 19 maps to package 1 core 3
OMP: Info #171: KMP_AFFINITY: OS proc 20 maps to package 1 core 4
OMP: Info #171: KMP_AFFINITY: OS proc 21 maps to package 1 core 5
OMP: Info #171: KMP_AFFINITY: OS proc 22 maps to package 1 core 6
OMP: Info #171: KMP_AFFINITY: OS proc 23 maps to package 1 core 7
OMP: Info #171: KMP_AFFINITY: OS proc 24 maps to package 1 core 8
OMP: Info #171: KMP_AFFINITY: OS proc 25 maps to package 1 core 9
OMP: Info #171: KMP_AFFINITY: OS proc 26 maps to package 1 core 10
OMP: Info #171: KMP_AFFINITY: OS proc 27 maps to package 1 core 11
OMP: Info #171: KMP_AFFINITY: OS proc 28 maps to package 1 core 12
OMP: Info #171: KMP_AFFINITY: OS proc 29 maps to package 1 core 13
OMP: Info #171: KMP_AFFINITY: OS proc 30 maps to package 1 core 14
OMP: Info #171: KMP_AFFINITY: OS proc 31 maps to package 1 core 15
OMP: Info #250: KMP_AFFINITY: pid 428274 tid 428274 thread 0 bound to OS proc set 16

**Comment by Iuliana19** [comment]
[ivladisavlev@login01 case2]$ cat smilei.err

                    _            _
  ___           _  | |        _  \ \   Version : 6530a06-master
 / __|  _ __   (_) | |  ___  (_)  | |
 \__ \ | '  \   _  | | / -_)  _   | |
 |___/ |_|_|_| |_| |_| \___| |_|  | |
                                 /_/



 Reading the simulation parameters
 --------------------------------------------------------------------------------
 HDF5 version 1.10.5
         Python version 2.7.5
         Parsing pyinit.py
         Parsing 6530a06-master
         Parsing pyprofiles.py
         Parsing laserplasma2.py
         Parsing pycontrol.py
         Check for function preprocess()
         python preprocess function does not exist
         Calling python _smilei_check
         Calling python _prepare_checkpoint_dir
        [WARNING] Change patches distribution to hilbertian
        [WARNING] simulation_time has been redefined from 502.654825 to 502.610646 to match timestep.
        [WARNING] Particles cluster width set to : 15


 Geometry: 2Dcartesian
 --------------------------------------------------------------------------------
         Interpolation order : 4
         Maxwell solver : Yee
         (Time resolution, Total simulation time) : (21.444034, 502.610646)
         (Total number of iterations,   timestep) : (10778, 0.046633)
                    timestep  = 0.671751 * CFL
         dimension 0 - (Spatial resolution, Grid length) : (10.185916, 376.991118)
                     - (Number of cells,    Cell length)  : (3840, 0.098175)
                     - Electromagnetic boundary conditions: (silver-muller, silver-muller)
                     - Electromagnetic boundary conditions k    : ( [1.00, 0.00] , [-1.00, -0.00] )
         dimension 1 - (Spatial resolution, Grid length) : (10.19, 376.99)
                     - (Number of cells,    Cell length)  : (3840, 0.10)
                     - Electromagnetic boundary conditions: (silver-muller, silver-muller)
                     - Electromagnetic boundary conditions k    : ( [0.00, 1.00] , [-0.00, -1.00] )


 Vectorization:
 --------------------------------------------------------------------------------
         Mode: off


 Patch arrangement :
 --------------------------------------------------------------------------------


 Initializing MPI
 --------------------------------------------------------------------------------
         MPI_THREAD_MULTIPLE enabled
         Number of MPI process : 4
         Number of patches :
                 dimension 0 - number_of_patches : 32
                 dimension 1 - number_of_patches : 32
         Patch size :
                 dimension 0 - n_space : 120 cells.
                 dimension 1 - n_space : 120 cells.
         Dynamic load balancing: never


 OpenMP
 --------------------------------------------------------------------------------
         Number of thread per MPI process : 16


 Initializing the restart environment
 --------------------------------------------------------------------------------


 Initializing moving window
 --------------------------------------------------------------------------------


 Initializing particles & fields
 --------------------------------------------------------------------------------
         Creating Species : ion
        [WARNING] For species 'ion' Using thermal_boundary_temperature[0] in all directions
         Creating Species : electron
                 > Radiating species with the stochastic Monte-Carlo model
                 > Macro-photon emission activated
                 > Emitted photon species set to `photon`
                 > Number of macro-photons emitted per MC event: 1
                 > Photon energy threshold for macro-photon emission: 2.00
        [WARNING] For species 'electron' Using thermal_boundary_temperature[0] in all directions
         Creating Species : photon
                 > photon is a photon species (mass==0).
                 > Radiation model set to none.
                 > Pusher set to norm.
         Laser parameters :
                Laser #0: separable profile
                        omega              : 1
                        chirp_profile      : 1D built-in profile `tconstant`
                        time envelope      : 1D built-in profile `tgaussian`
                        space envelope (y) : 1D user-defined function
                        space envelope (z) : 1D user-defined function
                        phase          (y) : 1D user-defined function
                        phase          (z) : 1D user-defined function
                delay phase      (y) : 0
                delay phase      (z) : 1.5708
         Adding particle walls:
                 Nothing to do


 Initializing Patches
 --------------------------------------------------------------------------------
         First patch created
                 Approximately 10% of patches created
                 Approximately 20% of patches created
                 Approximately 30% of patches created
                 Approximately 40% of patches created
                 Approximately 50% of patches created
                 Approximately 60% of patches created
                 Approximately 70% of patches created
                 Approximately 80% of patches created
                 Approximately 90% of patches created
         All patches created


 Creating Diagnostics, antennas, and external fields
 --------------------------------------------------------------------------------
         Created ParticleBinning diagnostic #0: species electron
                 Axis x from 0 to 376.991 in 100 steps
                 Axis y from 0 to 376.991 in 100 steps
         Created ParticleBinning diagnostic #1: species electron
                 Axis x from 0 to 376.991 in 100 steps
                 Axis px from -150 to 150 in 100 steps
         Created ParticleBinning diagnostic #2: species electron
                 Axis y from 0 to 376.991 in 100 steps
                 Axis py from -150 to 150 in 100 steps
         Created ParticleBinning diagnostic #3: species photon
                 Axis x from 0 to 376.991 in 100 steps
                 Axis y from 0 to 376.991 in 100 steps
         Created ParticleBinning diagnostic #4: species photon
                 Axis x from 0 to 376.991 in 100 steps
                 Axis px from -150 to 150 in 100 steps
         Created ParticleBinning diagnostic #5: species photon
                 Axis y from 0 to 376.991 in 100 steps
                 Axis py from -150 to 150 in 100 steps
         Created ParticleBinning diagnostic #6: species ion
                 Axis x from 0 to 376.991 in 100 steps
                 Axis y from 0 to 376.991 in 100 steps
         Created ParticleBinning diagnostic #7: species electron
                 Axis gamma from 10 to 6000 in 200 steps [LOGSCALE]
         Created ParticleBinning diagnostic #8: species photon
                 Axis user_function0 from -3.14159 to 3.14159 in 48 steps
                 Axis gamma from 10 to 6000 in 200 steps [LOGSCALE]
         Diagnostic Fields #0  :
                 Ex Ey Ez Bx By Bz
         Done initializing diagnostics, antennas, and external fields


 Applying external fields at time t = 0
 --------------------------------------------------------------------------------


 Initializing radiation reaction
 --------------------------------------------------------------------------------
         The Monte-Carlo Compton radiation module is requested by some species.

         Factor classical radiated power: 2005.06
         Minimum quantum parameter for continuous radiation: 0.00100
         Minimum quantum parameter for discontinuous radiation: 0.00100
         Table path: /gpfs/home/ivladisavlev/.local/Smilei/databases

         --- Integration F/particle_chi table:
             Reading of the external database
             Dimension quantum parameter: 256
             Minimum particle quantum parameter chi: 0.00100
             Maximum particle quantum parameter chi: 10.00000
             Buffer size: 2068
         done in 0.00163s
         --- Table chiphmin and xip:
             Reading of the external database
             Dimension particle chi: 128
             Dimension photon chi: 128
             Minimum particle chi: 0.00100
             Maximum particle chi: 10.00000
             Buffer size for MPI exchange: 132120
         done in 0.00116s



 Solving Poisson at time t = 0
 --------------------------------------------------------------------------------

**Comment by xxirii** [comment]
Ha yes, I forgot to tell you that I have switched off the Poisson computation at the beginning since you have cold particles. You can gain some computational time and it won't affect the physics I think. You can at least switch off for the tests. The Poisson takes a lot of time.

this means you have to use the parameters in the namelist:
```python
solve_relativistic_poisson = False,
solve_poisson = False,
```

**Comment by Iuliana19** [comment]
So, this is what I have in those files

**Comment by Iuliana19** [comment]
Ok, I will change it

**Comment by xxirii** [comment]
The thread placement seems good. Let us see if we run faster.

**Comment by Iuliana19** [comment]
Now, it already finished 1000 steps :D

**Comment by xxirii** [comment]
Yeess !

**Comment by Iuliana19** [comment]
So, now I have 4300 steps. Still running, but seems well. Thank you a lot!!!
I will let you know when it finishes

**Comment by Iuliana19** [comment]
It worked!! Thank you :)

**Comment by xxirii** [comment]
You're welcome.
If you go to 3D, you can activate the vectorization and speedup the code by adding this:
```python
Vectorization(
    mode = "adaptive",
)
```
But in 2D it won't change a lot your computational time.

**Comment by Iuliana19** [comment]
Thank you!!
