### ISSUE TITLE
No positrons created with Landau-Lifshitz

### ISSUE THREAD

**Issue by Viveal** [SmileiPIC/Smilei#147]
I used the benchmark file tst1d_10_pair_electron_laser_collision.py and tried to change the radiation model to LL. For MC it created positrons but for Landau-Lifshitz and the other models it didn't work. Would you be so kind to point out what I must change to be able to 
also generate positrons with LL?
Here is my input file:
[tst1d_10_pair_electron_laser_collision.txt](https://github.com/SmileiPIC/Smilei/files/3461730/tst1d_10_pair_electron_laser_collision.txt)

**Comment by MickaelGrech** [comment]
Dear @Viveal,

The Landau-Lifshitz (LL) model, as well as corrected LL (cLL) and Fokker-Planck models, are valid for small electron quantum parameter (\chi < 1) for which no pair are expected.
When you specify LL as your radiation model, only a radiation friction force is applied to the electrons, and most importantly no macro-photons are generated.
Therefore, it is perfectly normal you cannot see pair production in that case!
If you want to study pair production, you have to use the Monte-Carlo description of high-energy photon production and their back-reaction.

**Comment by xxirii** [comment]
Dear @Viveal, if you are satisfied with our reply let us know so that we can close this issue. Thanks
