### ISSUE TITLE
Stripe formation in density plot (patch dependant)

### ISSUE THREAD

**Issue by arsampath** [SmileiPIC/Smilei#150]
Dear developers,

We ran the attached input file in Smilei v4.2.
We see a stripe formation in our electron beam density as soon as the interaction starts. We believe this is a numerical artefact. 
This happens when **binary collisions** are activated.

The number of obtained stripes vary with the number of patches in the transverse direction.
The thickness of these stripes also decrease when we increase the resolution used in our simulation.

![Rho_SMILEI_16patches](https://user-images.githubusercontent.com/27001896/63039338-60983a00-bec3-11e9-997a-f9984c4311c9.png)
![Rho_SMILEI_hres](https://user-images.githubusercontent.com/27001896/63039351-642bc100-bec3-11e9-9d6c-df0c087000b9.png)
![Rho_SMILEI_4patches](https://user-images.githubusercontent.com/27001896/63039355-68f07500-bec3-11e9-8b17-7831d7d1b727.png)
![Rho_SMILEI_2patches](https://user-images.githubusercontent.com/27001896/63039363-6beb6580-bec3-11e9-9398-374842a8f9d8.png)
[small_beam.txt](https://github.com/SmileiPIC/Smilei/files/3502410/small_beam.txt)

**Comment by mccoys** [comment]
I assume this is obtained from the Fields diagnostics. Is this also true with ParticleBinning?

**Comment by arsampath** [comment]
Dear developers,

Yes, the plots attached in the previous post were made using Fields Diagnostics. 
A stripe formation is seen in the beam density plot also with ParticleBinning diagnostics. Kindly see the attached figure.

![Rho2948 43616131](https://user-images.githubusercontent.com/27001896/63085965-1ceb1200-bf4f-11e9-92b3-ad97076f461d.png)

**Comment by mccoys** [comment]
I noticed that your timestep is exactly CFL. I suggest you choose a slightly lower value because it might create some inconsistencies at patch borders. However I am not sure this is the explanation.

**Comment by arsampath** [comment]
We made our new timestep as half of the old CFL condition timestep. The stripe pattern on the density plots are still present. 

![rho_field_beam](https://user-images.githubusercontent.com/27001896/63281618-64560300-c2ad-11e9-917f-c9e2a6718850.png)

Also for comparison, I am attaching the results with a single patch along the transverse direction. 
![Rho_1patch](https://user-images.githubusercontent.com/27001896/63281673-82bbfe80-c2ad-11e9-9386-fa92c9d52a49.png)

**Comment by xxirii** [comment]
@mccoys it seems that the issue is related to **binary collision**, it should therefore appear with all diags.
@arsampath Does this happen at the beginning of the simulation ? Else, at which timestep can I start to see the phenomenon ?

**Comment by mccoys** [comment]
Ah, I did not realize that. @arsampath are you sure it disappears when there are no collisions?

**Comment by arsampath** [comment]
@xxirii  The stripe formation is visibly noticeable in the plots from around 3500-4000 time-steps. This is after the beam starts interacting with the target. The beam and target start interacting from around 1500th time-step.
@mccoys Yes, as mentioned before, we are sure these stripes disappear
when binary collisions are deactivated. 
![Rho2948 436161308791](https://user-images.githubusercontent.com/27001896/63346597-9de24900-c355-11e9-980f-9545f2288266.png)

**Comment by mccoys** [comment]
Thanks.

Binary collisions are truly local, so they should have no influence on patch borders. However, they force some different particle sorting algorithms, which we will investigate.

**Comment by mccoys** [comment]
I think we have an explanation on this problem. A recent change could explain your results and I will work on it ASAP

**Comment by mccoys** [comment]
The latest version should solve your issue. It was due to a very recent change on the way particles are ordered. Thanks for reporting.

Could you update and check it works for you?

**Comment by Mi3Sangal** [comment]
Dear @mccoys ,

I am replying to this on behalf of @arsampath, since both she and I are working on this together. 
We thank you very much for the quick response and for promptly solving this issue! 

We will check this with the updated version and get back to you!.

Also, thank you @MickaelGrech for looking into this with us and helping us with your inputs too!

**Comment by mccoys** [comment]
Actually, please wait a bit more. I think my fix will not always work. I will get back to you soon.

**Comment by mccoys** [comment]
Please reopen if the issue reappears
