### ISSUE TITLE
3rd SMILEI training workshop?

### ISSUE THREAD

**Issue by BenK3nobi** [SmileiPIC/Smilei#151]
Hello everybody, 
I am not sure who to contact, therefore here: 
Are there any plans for a third SMILEI training workshop any time soon? 
I am asking because the amount if PIC users in my group is increasing and some introductory workshop on how to properly work with SMILEI might be a very good thing to have. 

It would be awesome if someone of you who is somehow "responsible" or has an overview about that could message me :) 

Cheers, 
Benedikt

**Comment by MickaelGrech** [comment]
Dear Benedikt,

Thanks a lot for your interest in SMILEI & our training workshops.
Last training workshop was in March 2019, and we were planning to have such workshop every 1.5 yr, which would place next workshop some time in autumn 2020.
We are you guys from and when would you need to have a workshop?

Best,
Micka

**Comment by BenK3nobi** [comment]
Dear Micka, 
we are based at Darmstadt, Germany. Institutes at the Technical University and GSI. 
I found out about the 2nd workshop a week after it happened. So somehow unlucky. 

We are basically flexible concerning the date. There is still some funding left for this year but I assume that might be highly difficult because of the remaining time? 
Personally I would greet if it was before autumn 2020, but I do understand if that is somehow complicated or too much effort. 

Cheers,
Benedikt

**Comment by mccoys** [comment]
In my opinion, if more people express their interest for another workshop, we could advance it to sometime early in 2020. We will see how that goes.

Now, concerning the previous workshop this year, it was already full some time in advance, and we had to accommodate for a separate session. So we could expect more people to be interested soon. Maybe

**Comment by BenK3nobi** [comment]
What would  be a critical mass for a workshop? 
When would be a realistic time frame if the critical mass is met?

**Comment by mccoys** [comment]
We have not discussed anything yet. But the place were we have organized it has 26 seats I believe. I guess half the room could be enough to start organising.

Now, we already have things ready from last time. It is just a matter of finding the funding and having people available. I'd say at least two or three months. I'm not saying this is going to happen though. Maybe we should think of another format for urgent matters

**Comment by mccoys** [comment]
I forgot to mention that we have a page with tutorials, which is a portion of our teaching material during the workshop.

It could be a good place to start:
https://smileipic.github.io/tutorials/

**Comment by mccoys** [comment]
It has been a long time, but we are preparing a user & training workshop in March 2022. Registrations should open soon
https://indico.math.cnrs.fr/e/smilei3

**Comment by mccoys** [comment]
# Registrations are open !

## https://indico.math.cnrs.fr/e/smilei3
