### ISSUE TITLE
Problem pint & some axis in DiagFields

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#153]
Hi guys,

I have an issue with pint.
When I wanted to come back to SI with DiagFields:
If I wants lengths in µm :+1: 
x=S.Field(0,"Ex",units=['V/m','um']).getAxis('x') I have to multiply x by Lr/1e-6...
y=S.Field(0,"Ex",units=['V/m','um']).getAxis('y') the y quantity is in µm and I must not multiply by Lr/1e-6.

A bug in happi?

**Comment by mccoys** [comment]
A bug indeed.

Should be fixed in edead70
