### ISSUE TITLE
Probe diag & Field Diag

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#155]
Dear Smilei users,

I have a question about Probe diagnostic. 
I'm developping a python module to be able to work on Fields (Fourier transform, Poynting, ...). So I want to obtain datas from Field and Probe diags from Smilei.

As you can see in attached input file, DiagField and DiagProbe are defined to get the same datas.

Everything is OK with DiagField but I have a problem with Probe diagnostic:
S.Probe(0,'Ex').getAxis('x') give me an empty list. Same thing with ('y').
The methods .getTimesteps() and .getData() are OK.

Have I missed something? Or perhaps I must reconstruct my axis by myself?
[laser_test.txt](https://github.com/SmileiPIC/Smilei/files/3549598/laser_test.txt)

Thank you

Julien

**Comment by mccoys** [comment]
Probes axes are "axis1",  "axis2",  "axis3".

This has been clarified in the doc.

**Comment by juliencelia** [comment]
Thanks. It's fine. 


De: "mccoys" <notifications@github.com> 
À: "SmileiPIC/Smilei" <Smilei@noreply.github.com> 
Cc: "Julien Bonvalet" <julien.bonvalet@u-bordeaux.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 28 Août 2019 09:54:24 
Objet: Re: [SmileiPIC/Smilei] Probe diag & Field Diag (#155) 



Probes axes are "axis1", "axis2", "axis3". 

This has been clarified in the doc.
