### ISSUE TITLE
bug in pre-defined gaussian profile in two (and three) spatial dimensions

### ISSUE THREAD

**Issue by jpsikal** [SmileiPIC/Smilei#156]
I initialized a gaussian density spatial profile in my 2D simulation (gaussian over x, constant over y), for example:    
number_density = gaussian(ne, xvacuum=18.75*l0, xlength=62.5*l0, xfwhm=26.*l0, xcenter=50.*l0, xorder=2, yorder=0),
where ne is the value of maximum density, for example ne=10. 

I have seen maximum density ne=5 instead of expected ne=10 in the output after the initialization. 

Then, I tested it in 1D simulation, where I have seen the correct value of max ne=10. 

Finally, I looked into the source code, where is the definition of ysigma in pyprofiles.py and invysigma, yfactor in Function.cpp.
By simple calculations, it seems that yfactor=1/2 when yorder==0.

Therefore, I expect that the same problem should happen in 3D simulation. 

So, I suggest to add a few lines into the source code file Function.cpp
Something like: 
if (yorder==0) {yfactor=1.;}
and similarly to 3D case.

**Comment by mccoys** [comment]
yorder==0 is not very reasonable for a gaussian. It creates `exp(-1.)` which is about 0.36.

Instead, choose yfwhm= 1000000000.

**Comment by jpsikal** [comment]
Of course, you are right, we can use very large yfwhm giving almost constant profile over y. 

However, there is written in the documentation to SMILEI (see pre-defined spatial profiles at http://www.maisondelasimulation.fr/smilei/namelist.html):
"Note: if yorder equals 0, then the profile is constant over y."

This note in the documentation is confusing. 
Indeed, using yorder=0 gives you constant profile over y (since this case is treated in source code file pyprofiles.py). 
On the other hand, the maximum density is twice lower than expected since the case yorder=0 is not well treated in Function.cpp (as described in my first comment above)

Jan

**Comment by mccoys** [comment]
Ok, you are right. I will change the gaussian profile so that it reflects the doc.

**Comment by mccoys** [comment]
This has been fixed in the latest available version.
