### ISSUE TITLE
Bug with KNL

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#157]
For one week, I have a problem on TGCC.
The simulations crach with these log/err files:

[err.txt](https://github.com/SmileiPIC/Smilei/files/3554601/err.txt)
[out.txt](https://github.com/SmileiPIC/Smilei/files/3554602/out.txt)

[job_sub.txt](https://github.com/SmileiPIC/Smilei/files/3554624/job_sub.txt)

I didnt change smilei version...

Any idea?

**Comment by jderouillat** [comment]
Hi, 
Unfortunately no, I didn't remember a such sorting bug during initialization.
Could you call back the code's version you are using ? And if possible provide the namelist ?
Regards

**Comment by juliencelia** [comment]
Hi Julien,

I recompile the last version of SMILEI. It works... So it's OK.
Thank you.

Julien
