### ISSUE TITLE
Problem with marconi_knl_intel

### ISSUE THREAD

**Issue by flavorenti** [SmileiPIC/Smilei#160]
Hello there,
I've been running Smilei-4.1 on marconi for several months before but in the last weeks it doesn't want to work. Probably some library, modules ecc... have been updated and during the installation ( make machine=marconi_knl_intel ) I get the following error at the end of the compilation:

...
Compiling src/Tools/Tools.cpp
Linking smilei
/usr/bin/ld: build/src/Collisions/Collisions.o: undefined reference to symbol '__libm_sse2_sincos'
/usr/bin/ld: note: '__libm_sse2_sincos' is defined in DSO /cineca/prod/opt/compilers/intel/pe-xe-2018/binary/lib/intel64/libimf.so so try adding it to the linker command line
/cineca/prod/opt/compilers/intel/pe-xe-2018/binary/lib/intel64/libimf.so: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make: *** [smilei] Errore 1

 Here are the modules loaded:

[flavoren@r000u08l03 Smilei-4.1]$ module list
Currently Loaded Modulefiles:
 1) profile/base                         5) szip/2.1--gnu--6.1.0                
 2) intel/pe-xe-2018--binary             6) zlib/1.2.8--gnu--6.1.0              
 3) intelmpi/2018--binary                7) hdf5/1.10.4--intelmpi--2018--binary 
 4) mkl/2018--binary                     8) profile/archive   

Please help me, I guess I have to change something in the makefile or similar. Thanks,

Federico Lavorenti

**Comment by mccoys** [comment]
This looks like there are links missing in the Intel module. This has to do with your system admin. They should be able to fix those modules.

**Comment by xxirii** [comment]
Hi,

Have you tried a `make clean` first before your normal `make `?

Normally, admins should notify you when they upgrade the system. If you can find what they have changed in an email, it can help.

A last thing you can try is this:
- in the makefile, find the LDFLAGS variable
- add the following: -L/cineca/prod/opt/compilers/intel/pe-xe-2018/binary/lib/intel64 -limf

Normally, it should work without it as @mccoys suggests if the library is well installed with all environment variables defined.

**Comment by jderouillat** [comment]
Hi,
Can you confirm that you can access the library `ls -l /cineca/prod/opt/compilers/intel/pe-xe-2018/binary/lib/intel64/libimf.so` ?  
If yes, then that the library contains the desire object using the command : `nm -o /cineca/prod/opt/compilers/intel/pe-xe-2018/binary/lib/intel64/libimf.so|grep T __libm_sse2_sincos` ?

**Comment by flavorenti** [comment]
Ok, to answer in order:

@jderouillat I can confirm that I access the library (first line) but when running the second line I get file not existent, so the library doesn't contain the desire object:

##################
[flavoren@r000u06l01 Smilei-4.1]$ ls -l /cineca/prod/opt/compilers/intel/pe-xe-2018/binary/lib/intel64/libimf.so
-rwxr-xr-x 1 propro01 product 4036337 26 nov  2018 /cineca/prod/opt/compilers/intel/pe-xe-2018/binary/lib/intel64/libimf.so
[flavoren@r000u06l01 Smilei-4.1]$ nm -o /cineca/prod/opt/compilers/intel/pe-xe-2018/binary/lib/intel64/libimf.so|grep T __libm_sse2_sincos
grep: __libm_sse2_sincos: File o directory non esistente
#################


@xxirii yes I've made a clean before, and I've added the following lines to the makefile:
#Addition flavorenti
LDFLAGS += -L/cineca/prod/opt/compilers/intel/pe-xe-2018/binary/lib/intel64 -limf
LDFLAGS += -L/cineca/prod/opt/compilers/intel/pe-xe-2018/binary/lib/intel64 -lsvml
LDFLAGS += -L/cineca/prod/opt/compilers/intel/pe-xe-2018/binary/lib/intel64 -lirng
LDFLAGS += -L/cineca/prod/opt/compilers/intel/pe-xe-2018/binary/lib/intel64/ -lintlc

So now it seems to find the libraries but in the end I get a huge number of errors due to "undefined reference" or "riferimento indefinito" in italian, here is the result of make:

[ERROR.txt](https://github.com/SmileiPIC/Smilei/files/3576153/ERROR.txt)

Hope you can help me out! thanks

**Comment by jderouillat** [comment]
The `nm` comand contains an error, some `"` are missing :  
`nm -o /cineca/prod/opt/compilers/intel/pe-xe-2018/binary/lib/intel64/libimf.so|grep "T __libm_sse2_sincos"`  
You can use this kind of command to find the missing libraries which might be `-liomp5` :  
`nm -o /gpfs1l/opt/Intel/composer_xe_2015.0.090/compiler/lib/intel64/*.so |grep "T __kmpc_barrier"`

**Comment by xxirii** [comment]
Yes, as suggested by @jderouillat , you should add to the LDFLAGS : 
```
LDFLAGS += -L/cineca/prod/opt/compilers/intel/pe-xe-2018/binary/lib/intel64 -limf -lsvml -lirng -lintlc -liomp5
```
Errors seem to be related to OMP.

**Comment by flavorenti** [comment]
Ok now it works, thanks for the help!
