### ISSUE TITLE
Cannot run with AMcylindrical geometry

### ISSUE THREAD

**Issue by GeorgeHicks1** [SmileiPIC/Smilei#161]
## Description

I am trying to run a cylindrically symmetric simulation of a plasma slab. When I try to run the script I get the error `[Python] ValueError: invalid literal for int() with base 10: 'A'`. I believe this is Smilei saying it cannot read the simulation geometry, which would normally be 1,2 or 3D cartesian (hence the int() call). This suggests I am not using a version of Smilei compatible with cylindrical symmetry. According to the releases page, cylindrical symmetry was only included with v4.2.

The version of Smilei I am using was cloned yesterday (04/09/2019), I expected this to be v4.2, but my log file says I am using v4.1-562-gcb4bf21-master.
[log.txt](https://github.com/SmileiPIC/Smilei/files/3578499/log.txt)

I have also tried using Smilei 4.2 from the [releases](http://www.maisondelasimulation.fr/smilei/releases.html) page, but this gives the same results.

Output from log file:
```
                    _            _
  ___           _  | |        _  \ \   Version : v4.1-562-gcb4bf21-master
 / __|  _ __   (_) | |  ___  (_)  | |   
 \__ \ | '  \   _  | | / -_)  _   | |
 |___/ |_|_|_| |_| |_| \___| |_|  | |  
                                 /_/    
 
 

 Reading the simulation parameters
 --------------------------------------------------------------------------------
 HDF5 version 1.10.1
	 Python version 2.7.5
	 Parsing pyinit.py
	 Parsing v4.1-562-gcb4bf21-master
	 Parsing pyprofiles.py
	 Parsing namelist.py
	 [Python] ValueError: invalid literal for int() with base 10: 'A'
	[ERROR](0) src/Params/Params.cpp:1178 (runScript) error parsing namelist.py
```

## Steps to reproduce the problem

-Clone the git
-Compile Smilei
-Submit the namelist below

## Parameters

- Smilei version 4.1-562-gcb4bf21-master
- Input file  [namelist.txt](https://github.com/SmileiPIC/Smilei/files/3578503/namelist.txt)
- Commands or script used to run the faulty simulation? [pbsdebug.txt](https://github.com/SmileiPIC/Smilei/files/3578506/pbsdebug.txt)
- Computing resources
  - type of computer- Imperial College supercomputer
  - OS- linux
  - C++ compiler-  4.8.5
  - MPI version- intel-2018
  - HDF5 version- 1.10.1
  - Python version- 2.7.5

**Comment by beck-llr** [comment]
Hi
The short answer is that  `timestep_over_CFL` is not supported in `AMcylindrical` geometry yet. Sorry for the inconvenience, the error message should have been more explicit. Let me remind you that the `AMcylindrical` geometry is functional but still in beta so you might face other issues like this one in the future.
Thanks a lot for reporting them. In the process, we can help you go through the different steps and you help us improve the code :-)
Cheers

**Comment by beck-llr** [comment]
Let me add that the correct CFL is still correctly checked for this geometry and you'll get a warning if you do not respect it.

**Comment by GeorgeHicks1** [comment]
Hi,

Thanks for the quick response. I have now progressed further and discovered another possible bug.

When defining the particle boundary conditions, if I use `boundary_conditions = [["remove"]]`, I get the error `[ERROR](0) src/Species/SpeciesFactory.h:448 (create)  In AM geometry particle boundary conditions supported in Rmax are 'remove' and 'stop'`.

However, if I use `boundary_conditions = [["remove","remove"]]`, it works ok. Is this expected?

**Comment by mccoys** [comment]
This not expected, but part of the reason why it is still in beta

**Comment by beck-llr** [comment]
I am fixing those little details as you post them George. Thanks.

**Comment by GeorgeHicks1** [comment]
Thank you for your responses. I'm glad that these tests can improve Smilei!

I have now got Smieli running up until it solves the Poisson at time t=0 where it crashes. The file with the error message is [h2_5nc_azi.e526429.txt](https://github.com/SmileiPIC/Smilei/files/3583913/h2_5nc_azi.e526429.txt). For completion here is my [namelist.txt](https://github.com/SmileiPIC/Smilei/files/3583917/namelist.txt) and submission script [pbsplasma.sh.txt](https://github.com/SmileiPIC/Smilei/files/3583919/pbsplasma.sh.txt).

Do you have any thoughts on how to correct this?

**Comment by beck-llr** [comment]
The easiest way to avoid this error is to set `solvePoisson` to `False` in the `Main` class. With your particle initialization you do not need it anyway since the charge density is exactly 0 everywhere initially.
By the way if your ions are in the simulation as a simple neutralizing background, you can remove them completely and keep `solvePoisson` to False. With the charge conserving deposition scheme, a neutralizing background is mechanically assumed.

**Comment by beck-llr** [comment]
The features supporting `timestep_over_CFL` and single dimension particles boundary conditions specification have just been pushed in the master branch if I am not mistaken.  
Does the `solvePoisosn=False` solve your last issue ?

**Comment by GeorgeHicks1** [comment]
Great, thanks for making the changes. `solve_poisson=False` does fix my problem and I have my fields diagnostic. However, I don't quite understand what I am seeing. I suspect I have far too low resolution but need to investigate.

On an additional note, I tried to output the density of the electron and proton species in my fields diagnostic, however, they are not available in happi. Have I requested them correctly?

`DiagFields(every = globalEvery, fields = ["El_mode_0", "Er_mode_0", "Rho_electron", "Rho_proton"], )`

**Comment by beck-llr** [comment]
Yes they should be available but remember they are described by their modes as well.
`DiagFields(every = globalEvery, fields = ["El_mode_0", "Er_mode_0", "Rho_electron_mode_0", "Rho_proton_mode_0"], `
If I were you I would also add modes 1 which correspond to the modulation of the density by the laser. But if you're only interested in the average plasma response mode 0 is fine.

**Comment by GeorgeHicks1** [comment]
Thanks, I'll add in mode 1 for my next simulation with plasma. For now I have been trying to simply simulate a laser propagating in vacuum.

I have tried with this [namelist](https://github.com/SmileiPIC/Smilei/files/3609261/namelist.txt) and I see the laser propagate normally to begin with and then I see very large fields start in the corner of the simulation box and subsequently fill the box as shown in the three images below.
![t16](https://user-images.githubusercontent.com/37219451/64848952-452b6680-d60a-11e9-87e1-c9d687a9df79.png)
![t23](https://user-images.githubusercontent.com/37219451/64848957-478dc080-d60a-11e9-9b87-7ad80a4d1494.png)
![t27](https://user-images.githubusercontent.com/37219451/64848960-49578400-d60a-11e9-9acd-3c15b0a580bb.png)

Do you have any thoughts what could cause these?

In these images I have tried two ways of extracting the fields, one is in x-r using 
`Er_data=S.Field(diagNumber=0, field="Er",theta=np.pi).getData()
`
and the other is in x-y using 
`Er_3D=S.Field(diagNumber=0, field="Er",build3d=[[0,S.namelist.Main.grid_length[0],5],[-S.namelist.Main.grid_length[1],S.namelist.Main.grid_length[1],3],[-S.namelist.Main.grid_length[1],S.namelist.Main.grid_length[1],3]])
`.
My analysis script is here for reference: [smilei_cylindrical.txt](https://github.com/SmileiPIC/Smilei/files/3609269/smilei_cylindrical.txt).


I have a number of additional questions:
1) I want my laser to focus at r=0, but from the documentation, the laser focus is defined in xyz, have a defined the laser correctly in my namelist? This is different from the benchmark script `tstAM_04_laser_propagation.py`, where the laser focus is given in 2D.
2) Am I extracting the fields correctly? In the 3D extraction, I have empty cells at |y|>250
3) The benchmark script `tstAM_04_laser_propagation.py` uses a probe diagnostic, but in the documentation, we are told that only fields diagnostics are available:



> The "AMcylindrical" geometry is currently proposed in alpha version. It has not been thoroughly tested and only Fields diagnostics are available.

**Comment by beck-llr** [comment]
Hi George
Apologies for not responding faster, I completely missed out your message. Thanks for the reminder to @mccoys .

1. The laser focus must be given in [x,r] coordinates as in the benchmark script. The focus you are using should trigger an error. I'll try to fix this. And I also need to fix the doc which is obviously wrong here. Thanks for reporting it !  You should try to rerun the simulation with
```
laser_focus_position = [targ_x, 0]
```
to have focus on axis. This might explain the error you see.
2. I have not played a lot with the build3d feature but what you do looks correct. But notice that the 3d box you are using is actually larger than the cylinder of axis `y=z=0` and radius `R=Main.grid_length[1]` which is your simulation domain. So it is normal to have empty cells in the corners.
3.  The documentation was lagging behind the development. It has been updated now. Probes are indeed functional now. They do work exactly like probes in 3D in terms of definition in cartesian space (x,y,z) and available fields (cartesian components Ex, Ey, Ez, etc.).
