### ISSUE TITLE
Definition Scalar Diagnostics

### ISSUE THREAD

**Issue by DRobinR** [SmileiPIC/Smilei#163]
Hi everybody,

for me the definition of some Scalar Diagnostics (Ukin_bnd, Uelm_bnd, PoyXminInst,PoyXmin) is a bit unclear could you give me a more precise definition?

Especially is seems to me that Ukin_bnd, Uelm_bnd are used in Ubal as the energy lost/gained at the boundary up to the current moment, but the definition in the documentation sounds as they would give the exchanged energy in one time step.

Thanks and best regards

**Comment by mccoys** [comment]
I quote the doc:

> Ukin_bnd, Kinetic contribution exchanged at the boundaries during the timestep
> Uelm_bnd, EM contribution exchanged at boundaries during the timestep 
> PoyXminInst, Poynting contribution through xmin boundary during the timestep
> PoyXmin, Time-accumulated Poynting contribution through xmin boundary

This means they are all the exchanged energies at the boundaries during the latest timestep, except PoyXmin which is integrated over time. `kin` contains the particle kinetic energy, and `elm` the electromagnetic energy.

These quantities are accounted for in `Uexp`, as it contains the lost and gained energies at the border. Hence, they are also in `Ubal`.

**Comment by DRobinR** [comment]
Thanks for your quick reply. 
I had a closer look at this quantities and my confusen became even bigger.

 Running the attached code Ukin_bnd exceeds the total energy in the system which leads to a negative Uexp. An empty system has a total energy of 0. Therefore I don't understand what negative values of Uexp means. At the same time Utot is only changing slightly.

Furthermore I computed Uexp in a python script using Uexp[n] = Utot[0]-Uelm_bnd[n]-Ukin_bnd[n].
So I used Uelm_bnd and Ukin_bnd as the energies lost/gained up to(and including) the timestep n. The result is the same as the Uexp of the Scalar Diagnostics. So it seems to me that Uelm_bnd and Ukin_bnd are used as quantities integrated over time.

Namelist python script and plot are attached.
Thanks for your help, do not hestitate to ask for clarifications if my question is too vague.
[09_09_mwe_Ukin_bnd.zip](https://github.com/SmileiPIC/Smilei/files/3594619/09_09_mwe_Ukin_bnd.zip)

**Comment by mccoys** [comment]
My mistake, the `Ukin_bnd` and `Uelm_bnd` energies are accumulated in time. The documentation is wrong.

Concerning Uexp being negative, I recall seeing something similar, which we attributed to some error accumulation in the way the poynting flux is calculated. It might be a bug in the diagnostic that I will investigate.

**Comment by mccoys** [comment]
Actually, there seems to be something wrong in `Ukin_bnd`, as it increases too much compared to the number of lost particles.

**Comment by DRobinR** [comment]
Thanks
So that means that PoyXminInst PoyXmin aren't reliable either?

**Comment by mccoys** [comment]
No, I did not see anything wrong with Poynting fluxes in your case. Only the particles crossing boundaries. This does not affects the simulation, but only this diagnostic.

**Comment by mccoys** [comment]
The last version should now give the proper `Ukin_bnd`. Please confirm that it works for you.

**Comment by DRobinR** [comment]
The new version gives reasonable results. Thanks
