### ISSUE TITLE
Numpy array for positions and momenta of the species’ particles.

### ISSUE THREAD

**Issue by Kantmq** [SmileiPIC/Smilei#164]
Hello everyone

I'm a new SMILEI user.
I have an issue on specie initialization.
The idea is to initialize isotropic mono-energetic Cosmic ray particle.
To do that, I would like to initialize a Specie using a numpy array defining all the positions and momenta of the species’ particles.
The distribution function must look like that.

![momemtum_ini](https://user-images.githubusercontent.com/55799854/65613475-66029d00-dfb6-11e9-91d0-10356f4e1549.png)

I have created the tables (Ndim+1, Npart) and (3, Npart), for position and momentum using python function.  
The setup is this one

[input_test.txt](https://github.com/SmileiPIC/Smilei/files/3653240/input_test.txt)

SMILEI are able to read the table for the CR specie, however a segmentation fault appear after that and the output did not give me any error.
Here are the error message and the PIC output.

[out.txt](https://github.com/SmileiPIC/Smilei/files/3653260/out.txt)
[err.txt](https://github.com/SmileiPIC/Smilei/files/3653259/err.txt)

I don't know if this error is due to a wrong initialization in my input file or if it is related to the cluster.
I'm currently working on OCCIGEN, the CINES's cluster.

Thanks in advance!

**Comment by beck-llr** [comment]
Hi
Thanks for reporting your issue. I can easily reproduce your problem and your input file looks correct indeed. The functionality of importing numpy array for particle initialization has not been thoroughly tested for 1D simulations so I'll try to find a solution asap.

**Comment by Kantmq** [comment]
Thanks for your quick answer.!

**Comment by beck-llr** [comment]
Okay I've pushed the needed fix on our develop branch. It should be avaible on the master branch soon (maybe tomorrow). I'll post another message to let you know.
Let me just remind you that Smilei does not allow single character species name. You will have to rename your species `i` and `e` with longer names.
Thanks again for reporting this problem !

**Comment by Kantmq** [comment]
Great thanks.
However, just to let you know that I've performed simulations (with simple maxwell-juettner distribution function) using single character species name like i and e and it works (using the Smilei-4 version).

**Comment by mccoys** [comment]
The change concerning single characters has been made very recently. When you update, you will have to use multiple characters.

**Comment by beck-llr** [comment]
It should be ok now. Thanks again for the report and let us know how this goes for you. I'll let you close the issue if the code now behaves as expected.

**Comment by Kantmq** [comment]
Thanks, I will check it soon.

**Comment by Kantmq** [comment]
It works, great thanks!!!
