### ISSUE TITLE
Implementing circular polarization for 2D gaussian laser pulse

### ISSUE THREAD

**Issue by LPlasma** [SmileiPIC/Smilei#166]
I have been looking at implementing circular polarization for a 2D gaussian laser pulse and was wondering if there was an optimal was to achieve this? The notes for the v4.2 release mention a change to the convention for circular polarization implementation. Could you elaborate?

**Comment by mccoys** [comment]
The delay_phase argument was added to the various lasers so that it is easier to manipulate the two components y, z on the case of a circular or elliptical polarisation.

Look at the LaserGaussian2D block in the doc. It is able to produce a circulary polarised Gaussian beam

**Comment by mccoys** [comment]
@LPlasma did you manage to produce a circularly polarised beam? Please close the issue when resolved
