### ISSUE TITLE
AM cylindrical

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#167]
Hi Smilei team,

I try to use Smilei in Cylindrical geometry with azimuthal Fourier decomposition but Smilei crashes with this error :

[Python] NameError: name 'LaserGaussianAM' is not defined

I let you my input. I have compiled the last version of smilei...

Thanks 
Julien
[gasaxisym.txt](https://github.com/SmileiPIC/Smilei/files/3669205/gasaxisym.txt)
[job_curta.txt](https://github.com/SmileiPIC/Smilei/files/3669209/job_curta.txt)

**Comment by beck-llr** [comment]
Hi
Sorry but I can not reproduce your problem. When I run `smilei_test` on your input file I get
```
Creating Species : eon
        [ERROR](0) src/Species/SpeciesFactory.h:644 (create) For species 'eon', boundary_conditions must be of size 2.
```
which is normal. Looking at your inputfile you will have several other issues a little bit like this one due to wrong dimensioning of lists but there should not be any problem with your laser.
Make sure to recompile the last release and use the correct executable.
Cheers

**Comment by juliencelia** [comment]
OK it works...
For the coordinates, I don't understand something. With species in documentation: 
"In the "AMcylindrical" case, all grid coordinates are 2-dimensional (x,r), while particle coordinates (in Species) are expressed in the 3-dimensional Cartesian frame (x,y,z)"
So when I define species bloks, must I use 3D coordinates in cartesian fram or 2D x,r coordinates?
And in diags?

Moreover, Aranud, you said me to be careful with coordinates. If r is in the interval [0,40], for example y is in [-40,40]?

**Comment by beck-llr** [comment]
For diags, Probes are defined with Cartesian 3D coordinates and Fields with 2D cylindrical coordinates.

**Comment by juliencelia** [comment]
OK. Thank you very much...
On KNL, il works...let's see the results in few hours ;)

**Comment by beck-llr** [comment]
You can have a look at AM benchmarks if you need namelist examples.
