### ISSUE TITLE
Finding reflected laser fraction

### ISSUE THREAD

**Issue by ottcsconsult** [SmileiPIC/Smilei#168]
Hi Smilei-Community,

First let me say that I'm having a very good time working with Smilei. It's very well written and documented and its parallel scaling is quite superb (I've been using it on up to 16 nodes with 24 cores each, running hybrid OpenMP-MPI with 12 cores per thread). Thank you so much for providing this code as open source!

I now have an analysis question. I'm looking at a 1D laser plasma instability problem, focused on  stimulated Raman scattering. A key quantity to analyze is the "reflected fraction" -- how much of the incident laser intensity comes out through the left (x=0) boundary from which the laser is injected.

I'm wondering how to best approach this. Naively, I'm currently using a Probe at x=0 to extract the fields, then I compute the instantaneous Poynting flux, and average it over the entire simulation time (Savg). Then I simply compute: I_reflected = 1.0 - Savg/I_0, where I_0 is the dialed in laser intensity.

Is this how you would do it or is there a better way?

One idea I have is to inject the laser at some x0 > xmin. In that way, I could extract any left-propagating Poynting flux between xmin and x0. Is there a way to do this in Smilei?

Thanks!

 - Christian

**Comment by mccoys** [comment]
It is not possible to inject the laser away from boundaries in the usual way. However, it is possible to setup an `Antenna` with the correct shape to reproduce a laser starting somewhere in the box. The problem is that it will propagate both directions, thus useless for you.

Your probe technique is fine. However, you already have the poynting flux calculated in the Scalar diagnostics, so that you don't need a probe at all.

Another approach is to save the whole fields (or probe) in the box, then do a fourier transform in time and space. You may then extract the portion, in fourier space, corresponding to forward or backwards waves and compute their respective energies.

**Comment by MickaelGrech** [comment]
Hi Christian,

Thanks a lot for your positive feedback.
@mccoys is right, Fourier transform in space & time is a nice diagnostics for getting the backward & forward waves, in particular in 2 or 3D (even though it then start to be computationally costly).

For your case however (1D simulation) there is a much simpler trick that will allow you decompose the forward moving & reflected light.
Indeed, writing the electric field (let's assume y-polarization) of the forward-moving (+) wave in the form:
E_y^{+} = E0 cos(w*t-k*x)
the corresponding Bz field is:
B_z^{+} = (k/w) E_y^{+}.
In contrast, for the backward-moving (-) wave, 
B_z^{-} = -(k/w) E_y^{+}.
Thus, you have for the total fields (the one you measure in the simulation):
E_y           = E_y^{+} + E_y^{-}
(w/k) B_z = E_y^{+} - E_y^{-}     (from B_z = B_z^{+} + B_z^{-})
Finally, you can get the electric field associated to the forward moving & backward moving waves very easily using:
E_y^{+} = (1/2) [ E_y + (w/k) B_z ]
E_y^{-} = (1/2) [ E_y - (w/k) B_z ],
where E_y and B_z are the fields extracted from the simulation (btw, I would use 'Bz_m' in SMILEI, which is computed at the same time (integer timestep) that the electric field, for this diagnostics.

In particular, if your probe(s) is(are) in the vacuum (or in a plasma with very low density) w/k = 1 (or w/k~1), and this equation is super easy to compute.

**Comment by ottcsconsult** [comment]
Thanks, mccoys & MickaelGrech, this is very helpful.

I should have realized that my idea with injecting the laser interior to the boundary was flawed. 

I very much like MickaelGrech's suggestion about separating forward and backward moving waves in 1D. It's very smart. I'm running at 0.1 n_critical, so I'm getting quite a bit dispersion. Also, my scattered (backward moving) wave has a frequency that's about 0.64 of the laser frequency. I'll try out the method and compare it to what I'm doing right now.

My Fourier transformation experience is limited to doing transforms in one variable. Could you possibly point me to an example that shows how to do the 1D space & time transform to isolate forward and backward moving components? Please don't spend a lot of time on this, but if you have something readily on hand, sharing it would be very helpful! Thanks again!

**Comment by mccoys** [comment]
Concerning the fourier transform, I don't have something right now, but it is fairly easy to use numpy or any other utility to compute the FFT of a 2D array (x,t).
