### ISSUE TITLE
Error in 1D simulation that I cannot find...

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#169]
Dear Smilei users,

Sorry but since few days, I cannot find the error in my input. It's just 1d simulation...
If someone can help...

[CH1d.txt](https://github.com/SmileiPIC/Smilei/files/3696020/CH1d.txt)

[out.txt](https://github.com/SmileiPIC/Smilei/files/3696024/out.txt)

Thank you very much

Julien

**Comment by mccoys** [comment]
You use a 2D laser for a 1D simulation ;)

**Comment by mccoys** [comment]
I must admit the error is not very explicit

**Comment by jderouillat** [comment]
Hi,
You are defining a LaserGaussian2D with a single coordinate focus.

Julien

**Comment by juliencelia** [comment]
Hi

.... Really sorry.
I'm not used to competing in 1D anymore....;)
