### ISSUE TITLE
Parameters in Smilei

### ISSUE THREAD

**Issue by bitalm** [SmileiPIC/Smilei#17]
Hi All,

Thanks for developing the Smilei code and open it to the public.
I want to use the code for a 2D laser plasma accelerator simulation.
I had some questions regarding the parameters if possible:

I'm using the 2d py file (tst2d_4_laser_wake.py) from the benchmark and I want to change the parameters for the following 
simulation:

dt = 1.0920358205802873e-16
LASER_A0 = 3.52
$ XLENGTH = 3.17e-05
$ PULSE_LEN = 8.50e-06
$ NOM_DEN_E = 1.00e+25
$ RAMP_LEN = 1.00e-05
$ WAVELENGTH = 8.00e-07
$ LASER_W0 = 1.20e-05
$ NDIM = 2.00e+00
$ FOCUS_DEPTH = 6.00e-05
$ YLENGTH = 5.00e-05
$ RAMP_START = 1.00e-05
$ K0 = ((TWOPI/WAVELENGTH))
$ OMEGA = ((LIGHTSPEED*K0))
$ LASER_W0INV = (1/ LASER_W0)
$ LASER_ZRINV = (2 * LASER_W0INV**2 / K0)
$ LASER_DENOMY = (1 + (NDIM>1)*(FOCUS_DEPTH * LASER_ZRINV)**2)
$ LASER_DENOMZ = (1 + (NDIM>2)*(FOCUS_DEPTH * LASER_ZRINV)**2)
$ LASER_AMPFACTOR = ((LASER_DENOMY * LASER_DENOMZ)**(-0.25))
$ LASER_E0 = (ELECMASS * LIGHTSPEED * OMEGA * LASER_A0 / ELEMCHARGE)
$ RAMP_KAY = (PI/RAMP_LEN)
$ PULSE_DURATION = (PULSE_LEN/LIGHTSPEED)
$ PULSE_OMEGA = (TWOPI/PULSE_DURATION)
$ OMEGA_P2 = (NOM_DEN_E*ELEMCHARGE*ELEMCHARGE/(ELECMASS*EPSILON0))
$ OMEGA_P = (sqrt(OMEGA_P2))
$ FREQ_P = (OMEGA_P/TWOPI)
$ PLASMA_WAVELEN = (LIGHTSPEED/FREQ_P)
$ YMAX = (0.5*YLENGTH)
$ YMIN = (-YMAX)
$ FLAT_START = (RAMP_START+RAMP_LEN)

The parameters are in SI units,
Just I want to set the number density as 1.00e+25 m-3(m-2?).
Just I do not know how number density is calculated from n_part_per_cell parameter?

and from this, omega_p would be set. Also for laser we have omega0 (laser angular frequency), 
In this case that we have 2 omega_r, which one would be accounted as the reference frequency (omega_r)?

ATB

**Comment by beck-llr** [comment]
Hi and welcome

First of all, let me remind you that this benchmark is just a benchmark. For scientific results it is strongly **not** recommended to run laser plasma acceleration simulation in Cartesian 2D because the self focusing of the laser is very poorly described.

For any units problem, please read the [Units](http://www.maisondelasimulation.fr/projects/Smilei/html/units.html) section at our website.

The number density is not determined by the number of particles per cell which is only a numerical parameter of the PIC method. The number density or charge density can both be defined for each species. This is documented in the [Species](http://www.maisondelasimulation.fr/projects/Smilei/html/namelist.html#species) section of the doc.

The simulation is correct for any value of the reference frequency. You just have to chose which one you want and normalize your input parameters accordingly because SMILEI only handles dimensionless variables (see [Units](http://www.maisondelasimulation.fr/projects/Smilei/html/units.html) ).

I hope this helps and keep SMILEIng

**Comment by mccoys** [comment]
I would like to add that the input file (the namelist) is in the *python* language. If you are not familiar with python, I suggest you learn first about the basic syntax of python. This is straightforward and intuitive.

The online documentation of Smilei (http://www.maisondelasimulation.fr/smilei) contains a lot of information on how to write a namelist (section *write a namelist*). That can be useful for you to find out about all possible keywords.

The input values you provided are not written in python, so make sure you convert them.

**Comment by bitalm** [comment]
Dear All,

Many thanks for your comments and helps and sorry for being late.
Thanks for the comment about the 2D usage for the laser plasma acceleration, Arnaud.
Hope that 2D also would be possible for the near future.

Dear mccoys
I tried to make the namelist for the laser as (I will change it for 3D):
BTW is the charge_density, number density (m-3)?
Just I'm not sure if L_FWHM is correct:
#n0=1.e25, omega_p =1.7e14, c/omega_p=1.76E-06
dx = 1.75e-2  #=(3.17e-5/1024)/(c/omega_p)
dy =1.11e-1  #(5.e-5/256)/(c/omega_p)
dt = 0.188  # =0.188/omega_p
nx = 1024
Lx = nx * dx
npatch_x = 128
laser_fwhm = 19.80

Main(
    geometry = "2d3v",
    
    interpolation_order = 2,
    
    timestep = dt,
    sim_time = 20000*dt,
    
    cell_length  = [dx, dy],
    sim_length = [3.17e-5, 5.e-5],

    number_of_cells = [1024, 256],
    
    number_of_patches = [npatch_x, 4],
    
    clrw = nx/npatch_x,
    
    bc_em_type_x = ["silver-muller","silver-muller"],
    bc_em_type_y = ["silver-muller","silver-muller"],
    
    solve_poisson = False,
    print_every = 100,

    random_seed = smilei_mpi_rank
)


    n_part_per_cell = 16,
    c_part_max = 1.0,
    mass = 1.0,
    charge = -1.0,
    charge_density = 1.,

LaserGaussian2D(
    boxSide         = "xmin",
    a0              = 3.52,
    omega           = 13.9,  #11omega_p
    focus           = [0., Main.sim_length[1]/2.],
    waist           = 26.16,
    time_envelope   = tgaussian(center=2**0.5*laser_fwhm, fwhm=laser_fwhm)
)

ATB

**Comment by mccoys** [comment]
@bitalm, note that the parameters `n_part_per_cell`, `mass`, `charge`, and `charge_density` must be included in a `Species(...)` block, as explained in the documentation.

The `charge_density` parameter is, as its name suggests, the charge density; not the number density. In SI units, it would have the dimension of C/m^2, but in the code, it is in more complicated units, as shown in [the doc](http://www.maisondelasimulation.fr/smilei/units.html): ε0 me ωr^2 /e

**Comment by bitalm** [comment]
Dear @mccoys , Thanks for your reply. Yes I will add them in the Species(...).

BTW,  ε0. me. ωr^2 /e^2 is number density, charge density should be different.

**Comment by mccoys** [comment]
@bitalm, Indeed, I wrote
>    ε0 me ωr^2 /e, 

and not

>    ε0 me ωr^2 /e^2

**Comment by bitalm** [comment]
@mccoys, Thanks for your comments and helps
