### ISSUE TITLE
TrackParticles diag in loop

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#170]
I dont know if it's a bug on this particular diag (because no problem on other diags) with a loop, Smilei crachs when I put a TrackParticle diag in a loop for species.
See attach below input and log files

[out.txt](https://github.com/SmileiPIC/Smilei/files/3701652/out.txt)
[CH1d.txt](https://github.com/SmileiPIC/Smilei/files/3701653/CH1d.txt)

Thanks

Julien

Explain your issue here.

```
If available, copy-paste faulty code, warnings, errors, etc.
```

## Steps to reproduce the problem

If relevant, provide a step-by-step guide

## Parameters

- Smilei version ?
- Input file ?
- Commands or script used to run the faulty simulation ?
- Computing resources
  - type of computer
  - OS
  - C++ compiler (to get some information `g++ --version`)
  - MPI version (`mpic++ --version`, `mpic++ -show`)
  - HDF5 version (`h5cc --version`)
  - Python version (`python --version`)
  - ...

**Comment by juliencelia** [comment]
And It's the version 4.2 of smilei

**Comment by mccoys** [comment]
You have a quite clear error message:
```
[ERROR](0) src/Tools/PyTools.h:358 (extract) Looking for single value "species" in DiagTrackParticles #0 but got a list.
```

This means you have put a list `[...]` in your tracked particles, but it is only waiting for one species name.

**Comment by juliencelia** [comment]
OK but the diag is in a loop like others diags (screen en Particlebinning) so why it is a problem for the track Particle?

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by mccoys** [comment]
I don't understand the question. It has nothing to do with the loop. You simply have to remove the []

**Comment by juliencelia** [comment]
Yes I understood... 
It is just strange that others diags accepts lists and not trackParticles. But it's OK it works 
thanks Mccoys. one more time ;) 


De: "mccoys" <notifications@github.com> 
À: "SmileiPIC" <Smilei@noreply.github.com> 
Cc: "Julien Bonvalet" <julien.bonvalet@u-bordeaux.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 8 Octobre 2019 18:50:54 
Objet: Re: [SmileiPIC/Smilei] TrackParticles diag in loop (#170) 



I don't understand the question. It has nothing to do with the loop. You simply have to remove the []

**Comment by mccoys** [comment]
Other diags accept lists because they can sum the contribution of several species. This is not the case for tracked particles

**Comment by juliencelia** [comment]
OK that's clear. Thanks again 


De: "mccoys" <notifications@github.com> 
À: "SmileiPIC" <Smilei@noreply.github.com> 
Cc: "Julien Bonvalet" <julien.bonvalet@u-bordeaux.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 9 Octobre 2019 09:12:12 
Objet: Re: [SmileiPIC/Smilei] TrackParticles diag in loop (#170) 



Other diags accept lists because they can sum the contribution of several species. This is not the case for tracked particles
