### ISSUE TITLE
Bug in happi

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#172]
Hi,

I have a problem with the method .animate of happi with the last version of smilei(4.2)
See screenshot below.

![Capture d’écran de 2019-10-15 10-37-31](https://user-images.githubusercontent.com/48507571/66815095-f68a2880-ef37-11e9-9bc1-7651cfdb952c.png)

thanks

Julien

**Comment by mccoys** [comment]
Hi,

What is the bug ?

**Comment by mccoys** [comment]
If you are considering the warnings, this is simply because you have zeros, but you ask for log-scale, which results in NaN.

You can try setting vmin and vmax.
