### ISSUE TITLE
Cell Sorting

### ISSUE THREAD

**Issue by DRobinR** [SmileiPIC/Smilei#174]
Hi,
when I use particle merging, smilei demands cell sorting or vectorization to be turned on.
I can't find anything about the cell sorting in the documentation, so I wanted to ask what the effects of this option are.

Best regards

**Comment by mccoys** [comment]
There should be very little effect to enable `cell_sorting=True`. In some extreme cases, the sorting can be time consuming, but usually it should be ok.

**Comment by DRobinR** [comment]
Thanks for the quick answer. 
I also don't understand how the cell sorting is used by the particle merging?

**Comment by beck-llr** [comment]
Only particles located in the same cell can be merged. Therefore it helps to have particles already sorted per cell before running the merging algorithm.
