### ISSUE TITLE
How many particles are injected by Particle Injector per step? 

### ISSUE THREAD

**Issue by Infinemen** [SmileiPIC/Smilei#175]
PIC simulation has an issue that the macro particles will lost as simulation goes on. Therefore the particle injector is really an essential Improved methods to make up the loss of the particles. But there some unclear things.
I think particle injector can act as a source, so it should has an important parameter like particle flux or current or something that can tell me how many particles are injected per step. 
So my question are,
(1) with present injector, how many particles are initialized per step ? I know some of these particles which are initialized behind the boundary will not enter the simulation domain, but that really make it difficult to control the injection number precisely. And I wonder is it easy for me to change the source code to make all the particles which are behind the boundary injected into simulation domain? If it is easy, where or which function should I change? (something like step 1 initializing them behind of the boundary -> step 2 let all the particles' position be 0.1 cell.length away from the boundary in simulation domain and then they are same as the normal particles pushed by EM fields. )
(2) can I decide how many times will the injector inject particles during the simulation by the parameter "time_envelope"?
(3) Dose the parameter "position_initialization" just decide how particles will be initialized on the cells which are behind the injected boundary (the gray cells in the illustration picture)? What if I do 1D simulation and want to inject particles at one end? 

Thanks for your great job, and waiting for your reply!

**Comment by xxirii** [comment]
Dear @Infinemen 

(1) The number of injected macro-particles is not constant and depend on the injection parameters as you have understood. You could change the source code to initialize the particles in the domain for instance. This step is done in vectorPatch.cpp. I can make a full description of the implementation if you want.

(2) The injector will inject particle one time per iteration. You can indeed use the time envelop to tune injection frequency. You will have to use a custom function.

(3) Indeed, `Position_initialization` works exactly like species in the grey cells behind the boundary. If you do 1D and want to inject only from one side, you only specify injectors for this side by using the parameter `box_side`.

**Comment by Infinemen** [comment]
Dear professor,
I am very glad to receive your reply. Actually, the code has been commented pretty well, I still can't modify the code by myself because of the unfamiliar framework, even though I  have a try. 
 I really need the description about the code, and your help about the implementation is greatly appreciated!

**Comment by xxirii** [comment]
Dear @Infinemen,

There is a simple trick to do what you want to do: injectall particles in the domain and not in the first cell behind the boundaries.

First, let's have a look to `Patch/VectorPatch.cpp`:

This part (line 584) corresponds to the creation of the particles. For this aim we use the ParticleCreator class also used at initialization. 

```C++
                    // Particle creator object
                    ParticleCreator particle_creator;
                    particle_creator.associate(particle_injector, particles, injector_species);
                    particle_creator.add_new_particle_energy_ = false;
                    
                    //particle_index[i_injector] = previous_particle_number_per_species[i_species];
                    // Creation of the particles in local_particles_vector
                    particle_creator.create( init_space, params, patch, new_cell_idx, itime );
```

After this step, the particles are in fact created in the domain in the first cell near the boundary. This is the parameter `init_space` that enables this.

Then, what we do is that we shift the position to put the new particles outside the domain (line 595):

```C++
            // Shift to update the positions
            double position_shift[3];
            if ( patch->isXmin() ) {
                position_shift[0] = -params.cell_length[0];
            } else if ( patch->isXmax() ) {
                position_shift[0] = params.cell_length[0];
            } else {
                position_shift[0] = 0;
            }
```

The shift obviously depends on the boundary side.

The shift is applied line 640:

```C++
                        for ( unsigned int ip = 0; ip < particles->size() ; ip++ ) {
                            particles->Position[i][ip] += ( params.timestep*particles->Momentum[i][ip]
                                                        * particles->inv_lor_fac(ip) + position_shift[i]);
                        }
```

You can see as well that we push the particles with time step `params.timestep` to determine if they go inside the domain or not.

I think for your own purpose you can start to play with this.

Be aware that the next part of the particle injector algorithm consists on sorting particles and putting them in the final particle arrays.

**Comment by Infinemen** [comment]
Dear professor,
With your help, I understand how to inject all particles into the domain now.  I am still  trying to read and modifying the source code to meet the actual physical problem.  
Thank you so much for you help!

**Comment by xxirii** [comment]
Dear @Infinemen, you can call me Mathieu if you want.

All questions or suggestions are welcome if you need.
