### ISSUE TITLE
gcc8 not supported on Darwin 19

### ISSUE THREAD

**Issue by FlorianCondamine** [SmileiPIC/Smilei#176]
During the step 'sudo port install openmpi-gcc7 +threads' :  

Error: gcc8 8.3.0 is (currently) not supported on Darwin 19
Error: See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90835 for more details
Error: Until the issue is addressed in Xcode, please instead install gcc9 / libgcc9
Error: Failed to fetch libgcc8: incompatible OS X version
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc8/libgcc8/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port openmpi-gcc7 failed

I believe this is due to Catalina ?

**Comment by iltommi** [comment]
You could try using `openmpi-gcc9` (since openmpi version 4 the equivalent of `+threads` flag is  already included).

I have no experience with Catalina and none of the core devs uses macports,  so the macport documentation is probably outdated. 

Feel free to point errors and suggest changes either here or on a PR.

**Comment by mccoys** [comment]
@FlorianCondamine did you manage to get a working configuration? If so, we are interested to include it in the doc

**Comment by FlorianCondamine** [comment]
Hello,

I have a problem with the enable-parallel option and HDF5 with macport. I am trying to solve this on my free time.
As soon as I solved it, I’ll let you know.

Best,
Florian.

**Comment by copilco** [comment]
I have the same problem 
src/Tools/H5.h:16:2: error: #error "HDF5 was not built with --enable-parallel option
Using Mac os 10.14, Macports 2.6.2 and using the command  
sudo port install hdf5 +openmpi+gcc7+threads

**Comment by iltommi** [comment]
could you check the libraries that smilei is linked to?
`otool -L ./smilei` 
Then could you repeat the `otool` to the hdf5 lib found:
`otool -L [...]/hdf5-1.8.18/hdf5/lib/libhdf5.10.dylib`

**Comment by copilco** [comment]
Can not compile, with the Mac os 10.14, Macports 2.6.2  after i do make
Creating binary char for src/Python/pyinit.py
Creating binary char for src/Python/pycontrol.py
Creating binary char for src/Python/pyprofiles.py
Checking dependencies for src/picsar_interface/interface.cpp
In file included from src/Radiation/RadiationTables.h:21:0,
                 from src/Radiation/Radiation.h:20,
                 from src/Species/Species.h:17,
                 from src/ElectroMagn/ElectroMagn.h:11,
                 from src/ElectroMagn/ElectroMagn3D.h:4,
                 from src/picsar_interface/interface.h:10,
                 from src/picsar_interface/interface.cpp:1:
src/Tools/H5.h:16:2: error: #error "HDF5 was not built with --enable-parallel option"
 #error "HDF5 was not built with --enable-parallel option"
  ^~~~~

**Comment by iltommi** [comment]
sorry I misunderstood. 

Anyway you should find the `libhdf5.dylib` and check the output of `otool -L [path to]/libhdf5.dylib`

**Comment by copilco** [comment]
otool -L libhdf5.dylib
libhdf5.dylib:
	/opt/local/lib/libhdf5.103.dylib (compatibility version 105.0.0, current version 105.0.0)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/opt/local/lib/openmpi-gcc7/libmpi.40.dylib (compatibility version 61.0.0, current version 61.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
	/opt/local/lib/libgcc/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)

**Comment by iltommi** [comment]
Ok so the lib looks ok. 

Next step: headers
you should look in /opt for a file called `H5pubconf.h`(`find /opt -name H5pubconf.h`)  in which you should have this line:
```
#define H5_HAVE_PARALLEL 1
```
(mine is around line 268)
The most common cause is that somehow smilei is including the wrong hdf5 headers. In this case, can you send the output of `make env` inside the smilei dir?

If it's not the case and you have something like
```
/* #undef H5_HAVE_PARALLEL */
```
this means macport installed the wrong headers file. In this case you should try to reinstall from scratch the hdf5 package

**Comment by copilco** [comment]
The macport header file has the right line
grep  H5_HAVE_PARALLEL /opt/local/include/H5pubconf.h 
#define H5_HAVE_PARALLEL 1

The make env seems ok

 make env
SMILEICXX : mpicxx
PYTHONEXE : python
MPIVERSION : 
VERSION : b'v4.3-2-g442f29e7'-b'master'
OPENMP_FLAG : -fopenmp -D_OMP
HDF5_ROOT_DIR : /opt/local/lib
SITEDIR : /Users/camilo/.local/lib/python3.6/site-packages
PY_CXXFLAGS : -I/anaconda3/include/python3.6m -I/anaconda3/include/python3.6m -I/anaconda3/lib/python3.6/site-packages/numpy/core/include -DSMILEI_USE_NUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
PY_LDFLAGS : -L/anaconda3/lib/python3.6/config-3.6m-darwin -lpython3.6m -ldl -framework CoreFoundation -Wl,-stack_size,1000000 -framework CoreFoundation
CXXFLAGS : -D__VERSION=\"b'v4.3-2-g442f29e7'-b'master'\" -D_VECTO -std=c++11 -Wall  -I/opt/local/lib/include -Isrc -Isrc/Ionization -Isrc/MovWindow -Isrc/ParticleInjector -Isrc/Tools -Isrc/Checkpoint -Isrc/Projector -Isrc/Interpolator -Isrc/SmileiMPI -Isrc/ElectroMagnBC -Isrc/Python -Isrc/Pusher -Isrc/ElectroMagn -Isrc/Radiation -Isrc/Diagnostic -Isrc/ElectroMagnSolver -Isrc/Collisions -Isrc/Species -Isrc/Field -Isrc/Patch -Isrc/MultiphotonBreitWheeler -Isrc/picsar_interface -Isrc/Params -Isrc/DomainDecomposition -Isrc/Profiles -Isrc/Merging -Isrc/ParticleCreator -Ibuild/src/Python -I/anaconda3/include/python3.6m -I/anaconda3/include/python3.6m -I/anaconda3/lib/python3.6/site-packages/numpy/core/include -DSMILEI_USE_NUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D_VECTO -O3 -g  -fopenmp -D_OMP
LDFLAGS : -L/opt/local/lib/lib  -lhdf5 -L/anaconda3/lib/python3.6/config-3.6m-darwin -lpython3.6m -ldl -framework CoreFoundation -Wl,-stack_size,1000000 -framework CoreFoundation -lm -fopenmp -D_OMP

I have another copy of the header for other application
/usr/local/hdf5-1.8.15/include/H5pubconf.h

I just need to tell Smilei to compile using the macport header.
How do i do that?

**Comment by copilco** [comment]
It compiles ! 
I just had to fix 
export HDF5_ROOT_DIR=/opt/local/
instead of
export HDF5_ROOT_DIR=/opt/local/lib

Thanks

**Comment by iltommi** [comment]
Great! Not so many people use macports and the doc is a bit outdated...

Would it be possible for you to update installation using macports  (https://github.com/SmileiPIC/Smilei/blob/master/doc/Sphinx/install_macos.rst#macports--install-dependencies)

Or just recall here the packages you installed and the variables you set?

Thanks

**Comment by FlorianCondamine** [comment]
Thank you for the help. I will try this week if this works for me too.

Best.
