### ISSUE TITLE
stucking cpu for 3D laser plasma sample

### ISSUE THREAD

**Issue by bitalm** [SmileiPIC/Smilei#18]
Dear All,

I tried to run the 3D laser plasma benchmark sample:
tst3d_4_laser_wake.py

on a i7 cpu labtop on centos 7, 8GB Ram, but it seems does not proceed both for ncpus=4 and 1:
I also set the thread number to1.

Attached please find the log file:

[test log.pdf](https://github.com/SmileiPIC/Smilei/files/1323728/test.log.pdf)

ATB

**Comment by beck-llr** [comment]
Hi
The 3D benchmark is more demanding in terms of resources than most of the other benchmarks. Even with 4 cores it might be very long and maybe not even fit in your memory. Try to run on an HPC system.

FYI, this run takes 224 seconds on 76 cores on my system and generates approximately 1GB of data (fields and probes).

**Comment by bitalm** [comment]
HI Arnaud,

Thanks for your e-mail. Yes, it needs more resources
I will try to reduce the size, to be able to run on 4 cpus as well.
ATB
