### ISSUE TITLE
Unexpected Track particle data on more than 1 core

### ISSUE THREAD

**Issue by Mi3Sangal** [SmileiPIC/Smilei#181]
Dear developers,

We used the latest version of Smilei downloaded today (19.11.2019) to run the following input file.

We have used a Track Particles diagnostic in order to obtain the initial positions of all the particles.

[input_track_particles.txt](https://github.com/SmileiPIC/Smilei/files/3864181/input_track_particles.txt)

When we plot the charge density profile of the species  "electron_beam" at t = 0, using Field Diagnostics, we see what is expected.

However, when we read the data from the TrackParticles Diagnostic, we notice that major portion of the position array returns "NaN". 

This does not happen if we run the same input file on a single core. 

Could you please explain what could be causing this issue? 

Thank you very much for your time and help.

**Comment by mccoys** [comment]
Usually, NaNs appear in the file when particles exit or enter the box (they are not tracked anymore). In your case, open boundary conditions will destroy particles, which can create NaNs. However, it should be the same whatever the number of particles. I will investigate

**Comment by mccoys** [comment]
Ah, one question. When you say cores, do you mean as separate MPI processes, or openMP threads?

**Comment by Mi3Sangal** [comment]
Thank you for your response.

By many cores, we mean "separate MPI processes". We specify 1 OMP thread in our submit script.

We plot the beam density at t= 0 using Field Diagnostics. At this time, none of the particles has left the box. This diagnostic returns the correct/expected density profile as follows : 

![Rho_beam_manycores](https://user-images.githubusercontent.com/34055763/69229613-0d025000-0b86-11ea-8279-47d275c5b85d.png)


For t = 0 itself, we read the corresponding data (particle positions) from Track Particles diagnostic. And for this time itself, it returns "NaN" as the position for most of the particles. 
(This happens only if we run the above input file on more than 1 MPI processes)

**Comment by mccoys** [comment]
Please try the latest fix. I have corrected a bug, but I'm not sure it is yours.

**Comment by mccoys** [comment]
Note that you do not need to make a new simulation. Just remove the file `TrackParticles_electron_beam.h5` and start your analysis with the new version of happi. Do NOT remove the file that contains `Disordered`

Please also report of this was successful

**Comment by Mi3Sangal** [comment]
Thank you for your response. 
We will be able to check this and get back to you with the result in a few days.

**Comment by Mi3Sangal** [comment]
Dear developers,

We checked this with the latest fix as you suggested. This works fine now. 

Thank you for your help!
