### ISSUE TITLE
Questions on collisions in 1,2d and PIC in low resolution

### ISSUE THREAD

**Issue by talmiller2** [SmileiPIC/Smilei#182]
Dear developers, 2 questions:

1. As far as I understand, even if we have a 1d or 2d symmetric system, collisions will break the symmetry. In 1Dcartesian or 2Dcartesian geometry, how are the collisions implemented? Where do the particles scatter?
2. When studying a system where the main effects have much larger length and time scales compared to some small scales (like the Larmor and Debye scales, depending on the system), usually it is recommended to use hybrid/gyrokinetic codes that effectively average out the smaller scale behaviour. Do you think that using PIC in lower resolution (compared to the small scales) would also average out the smaller scales in some meaningful way, or would it be garbage-in-garbage-out?

Thanks a lot.

**Comment by mccoys** [comment]
Collisions occur the same way in all geometries. There is no spatial information used apart from the fact that only particles in the same cell may collide. In terms of momentum, there is no restriction no matter the geometry. Momentum is always 3d. So yes, collisions might break the symmetry, but not in average.

A PIC simulation should not have a resolution to large wrt the debye length. Thus it can't simulate very large volumes. It doesn't work as some sort of average model.

**Comment by mccoys** [comment]
Please close the issue if your question is answered
