### ISSUE TITLE
Filter for Particle tracking at initial time

### ISSUE THREAD

**Issue by Kantmq** [SmileiPIC/Smilei#183]
Hello,

I have a question concerning the particle tracking module.
I want to use a filter in space to track particle coming from a specific region.
The filter works but it stay active during all the simulation time, which mean that the particles, which at t=0 were followed in this filtered region, are not tracked anymore when they leave the specific region.
I've put a simple example to illustrate my point, where tracked particles are defined in a thin region in the y-axis, with an initial velocity along y, after a certain time they will leave the region and will not be followed anymore.
Is it possible to only use this filter at t=0 to define the track particles?

[input.txt](https://github.com/SmileiPIC/Smilei/files/3886694/input.txt)

Best

**Comment by mccoys** [comment]
Hi
Read the doc carefully. There are tips about `Main.iteration` which is the current iteration in the PIC loop. There is also an explanation about the IDs that are zero as long as they have not passed the filter. This can be used to do what you need.

One example:
```python
if Main.iteration == 0:
    return p.x<1.
else:
    return p.id>0
```

**Comment by Kantmq** [comment]
Hi,
Really sorry, I don't saw it.
Thanks for the quick reply.
Best

**Comment by mccoys** [comment]
You are welcome

Please close the issue if it is solved for you
