### ISSUE TITLE
toVTK() error for Probe diagnostic

### ISSUE THREAD

**Issue by OliverEt** [SmileiPIC/Smilei#184]
Hi - I am getting thrown an error when trying to use the toVTK function with a Probe (see below). I get the error "only length-1 arrays can be converted to Python scalars". 

The function works with ParticleBinning diagnostics. Can anyone tell me if I am doing something really stupid?

Thanks,
Ollie

TypeError                                 Traceback (most recent call last)
<ipython-input-28-0e5367cae361> in <module>()
----> 1 S.Probe(0,"Ey").toVTK()

/Volumes/oe113/home/smilei-v4.2/happi/_Diagnostics/Diagnostic.py in toVTK(self, numberOfPieces)
    856                                 filename = fileprefix+"_{:08d}.pvti".format(int(self._timesteps[itime]))
    857                                 if self._verbose: print("* Processing {}".format(filename))
--> 858                                 vtk.WriteImage(arr, origin, extent, spacings, filename, numberOfPieces)
    859                         if self._verbose: print("Successfully exported 3D plot to VTK, folder='"+self._exportDir)

/Volumes/oe113/home/smilei-v4.2/happi/_Utils.py in WriteImage(self, array, origin, extent, spacings, file, numberOfPieces)
    595                 img.SetOrigin(origin)
    596                 img.SetExtent(extent)
--> 597                 img.SetSpacing(spacings)
    598                 img.GetPointData().SetScalars(array)
    599                 writer = self.vtk.vtkXMLPImageDataWriter()

TypeError: SetSpacing argument 1: only length-1 arrays can be converted to Python scalars

**Comment by mccoys** [comment]
Is this a 3D probe ?
I think we might not have support for 1D and 2D toVTK

**Comment by OliverEt** [comment]
Sorry, yes this is a 3D simulation

**Comment by mccoys** [comment]
3D simulation, but 3D probe

**Comment by OliverEt** [comment]
Yes, the probe is 3D also

**Comment by mccoys** [comment]
I just pushed a quick fix.
Note that this will only give something correct if your probe has orthogonal axes.

**Comment by OliverEt** [comment]
Great, the fix works. Thanks for your help
