### ISSUE TITLE
AMcylindrical Documentation

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#186]
Hi Smilei Team,

Juste a suggestion. I think it could be a good thing to have a specific documentation or a section in "UNDERSTAND" about AMcylindrical geometry / Fourier decomposition.
Because It is a bit tricky I think and users want to keep smiling ;)

Julien

**Comment by mccoys** [comment]
Yes, this will be done. But, for now, this is still considered as experimental, and we do not wish that people think it is ready as a core part of the code. It has not been fully tested.

**Comment by beck-llr** [comment]
Exactly. We're still modifying the AM part of the code quite a lot at the moment. We do know that a better doc on this part is absolutely necessary. Keep sending us your feed back to speed up the process :-)

**Comment by juliencelia** [comment]
I just compiled 4.3 version on knl...
Just to be sure, from now I can use poisson solver?

**Comment by beck-llr** [comment]
Yes you should be able to. Classic or relativistic. Francesco added it only a few days ago though so let us know how it goes for you.

**Comment by Z10Frank** [comment]
@juliencelia Thank you for your feedback, we will try to work on a dedicated doc page as soon as possible.

Apart from the explanation of the decomposition technique, is there any particular related aspect that you think it would be important to have in the doc? (e.g. the Poisson problem, the envelope model, or more words about the diags or Profiles definitions).

**Comment by juliencelia** [comment]
Hi

Yes I think this geometry could have his own documentation because many things are a bit tricky in the initialization (species, Poisson solver, ..)

**Comment by Z10Frank** [comment]
Thanks! 
We will work on this. For the Poisson solver in cylindrical geometry, for the moment  you have a brief explanation in the relativistic Poisson problem page (https://smileipic.github.io/Smilei/relativistic_fields_initialization.html, end of first section), but it could be moved to the future page dedicated to azimuthal modes decomposition. The non relativistic Poisson problem should be added as well.

**Comment by juliencelia** [comment]
Thanks.
And for example, in the documentation, it is said "In the "AMcylindrical" case, all grid coordinates are 2-dimensional (x,r), while particle coordinates (in Species) are expressed in the 3-dimensional Cartesian frame (x,y,z)."

When you define a density profile function, it seems to be in 2D(x,r) and not in 3D... no?

**Comment by beck-llr** [comment]
Yes because a density is a grid quantity. But I agree that the documentation could be clearer about that in order to guide the user a bit more.

**Comment by mccoys** [comment]
By the way, this is an important point. Densities should not be a grid quantity, right? They could be in x,y,z. Is there anything against it?

**Comment by beck-llr** [comment]
Yes there is. The user is technically limited to describing an (x,r) profile for each mode. Not all 3D profiles can be decomposed into a finite number of azimuthal modes.

**Comment by mccoys** [comment]
I am not talking about EM modes, but particles, which can have any 3D position, thus any shape for their profile. Correct?

**Comment by Z10Frank** [comment]
In principle yes, you can initialise particles in 3D with the Python array method, i.e. giving all the positions and momenta of the particles. This way you could initialise indirectly any 3D density profile, but the code would project the density on the 2D grid and keeping only the chosen number of azimuthal modes, so very  asymmetrical features would be neglected in any case.

As @beck-llr was saying, if instead you select to initialise a density profile with a function of the grid, you have to do it on the dimension of the grid, that is in  2D.

**Comment by beck-llr** [comment]
@mccoys All grid quantites are decomposed into azimuthal modes. The decomposition is not limited to EM fields. It includes currents and charge density.

**Comment by Z10Frank** [comment]
@juliencelia A doc page dedicated to the AM is now available:
https://smileipic.github.io/Smilei/azimuthal_modes_decomposition.html

Can you check it (together with the namelist and post processing pages) to see if you the answers you were looking for can be found?

**Comment by juliencelia** [comment]
Hi @Z10Frank ,

The section about the namelist is clear and very helpful for new user in this geometry.
Thanks.
I have to do several 3D simulations in ion acceleration configuration. I will try to understudy in AMcylindrical to compare results! You will have a feedback:)

**Comment by mccoys** [comment]
@beck-llr I believe this should be closed. Let us open new issues for specific documentation points that are missing
