### ISSUE TITLE
"thermalize" boundary condition unknown in Z-direction

### ISSUE THREAD

**Issue by jpsikal** [SmileiPIC/Smilei#189]
I have tested a set-up for my 3D simulation with Smilei 4.3 version. 
The simulation failed when I used boundary_conditions = [ ['remove'], ['thermalize'],['thermalize'] ]  in the namelist and the output shows error message "Zmin boundary condition unknown". 

I looked into the source code file Species/PartBoundCond.cpp and there is missing something like else if( species->boundary_conditions[2][0] == "thermalize" ) below the line 201. 

Is there any serious reason for that?
Is it possible to add only a few lines ("else if" conditions) into the source code file below the line 201 or is it required to modify more parts of the code?

Probably, I could change the simulation geometry and use boundary_conditions = [ ['thermalize'],['thermalize'],['remove']].
Anyway, I do not see any reason why 'thermalize' boundary condition cannot be applied in z-direction in the current version of the code.

**Comment by MickaelGrech** [comment]
Ciao Jan!
I just had a quick look at BoundaryConditionType.h.
There are definitely some cleaning to do there (when we have time, I don't think it should change anything as long as ``thermal_boundary_velocity=0``).
However, you are right that the code should right now correctly handle thermalizing BCs in the z-direction. 
Could you check if adding the ``else if`` conditions after line 201 (for BCs [2][0], Zmin) and after line 218 (for BCs [2][1], Zmax) fixes your pb?

**Comment by jpsikal** [comment]
I implemented a new version of PartBoundCond.cpp into the code and after first test it seems that it works fine. It is simple modification as you suggested. 
The modified file is attached
[PartBoundCond.cpp.txt](https://github.com/SmileiPIC/Smilei/files/3973872/PartBoundCond.cpp.txt)

I will let you know if I would meet some problems with this boundary condition in the future. 

Jan

**Comment by MickaelGrech** [comment]
Sweet! let us know if you meet any pb.
We will update the code accordingly.

**Comment by beck-llr** [comment]
I am in favour of implementing this change as soon as possible. Thank you Jan for spotting this !

**Comment by jderouillat** [comment]
Integrated from 8b0379aaa7022a24c391b171aa5adf7bb6ac7558
