### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by Infinemen** [SmileiPIC/Smilei#19]
When I compiled, i got two errors:

     (1) src/Collisions/Collisions.cpp:444:68: error: ‘H5Pset_fapl_mpio’ was not declared in this scope
     (2) src/Collisions/Collisions.cpp:461:56: error: ‘H5Pset_dxpl_mpio’ was not declared in this scope
And my environment is:

      gcc 4.9.1
      openmpi 1.6.5
      hdf5 1.8.13

**Comment by iltommi** [comment]
It looks like your hdf5 libraries are compiled without support for mpi:

https://smileipic.github.io/Smilei/installation.html#on-older-release

**Comment by Infinemen** [comment]
Thank for your reply!
