### ISSUE TITLE
Segmentation fault during test for particle merging 

### ISSUE THREAD

**Issue by arsampath** [SmileiPIC/Smilei#190]
I was trying to use the particle merging module which was recently added in SMILEI. 

I try to simulate the head-on collision of two lasers with a0=700, in the presence of few seed electrons. I keep these seed electrons frozen for some time, so that they do not escape out of the focal region before laser peak arrives.

The program crashes with a '**_segmentation fault_**' roughly around the same time the seed electrons move.

- Smilei version: Downloaded master branch from github on 03 December 2019 
- Input file:  [test_merging.txt](https://github.com/SmileiPIC/Smilei/files/3945514/test_merging.txt)
- Output file: [stdout.txt](https://github.com/SmileiPIC/Smilei/files/3945791/stdout.txt)
- Error file: [stderr.txt](https://github.com/SmileiPIC/Smilei/files/3945792/stderr.txt)

Kindly let me know what could be the reason for this, and if I have used the particle merging module correctly. 

Thank you for your time.

**Comment by xxirii** [comment]
Dear @arsampath, you may have found a bug in the particle merging. A first look at your input file does not show any error. I need to investigate.

Can you give me some pieces of information:
- number of MPI / OpenMP threads
- compiler

Thank you

**Comment by arsampath** [comment]
Dear @xxirii , 

-- Number of MPI process : 400 
-- Number of thread per MPI process : 1
I used gnu compiler with openmpi-2.0.1-gcc62-sl7 and HDF5 version 1.10.1 on my cluster. 

Please find the attached submit script: [submit.txt](https://github.com/SmileiPIC/Smilei/files/3955966/submit.txt)

Thank you for your time.

**Comment by xxirii** [comment]
I have managed to produce the bug. I will now investigate to further understand from where it comes.

**Comment by xxirii** [comment]
Dear @arsampath,

I have finally found the bug. I will let you know when the master branch is corrected.

**Comment by xxirii** [comment]
The bug is corrected and the master branch is up-to-date. Let us know if it works for you.
