### ISSUE TITLE
strange behavior when a large amount of data is produced on output

### ISSUE THREAD

**Issue by jpsikal** [SmileiPIC/Smilei#191]
When I have tested a setup of 3D simulation with SMILEI on a large computer cluster, at some moment my simulation run is frozen - it further consumes computational time, but it does not continue in fact. 
It is very dangerous since the user can spend a lot of computational time (up to wall clock time limit on supercomputer) without obtaining any valuable output. 
The moment when the simulation starts to be frozen is during writing output data (to Field diagnostics in my case, it works when creating checkpoints on the other hand). 

Do you have any tips how to solve this problem?
What is probable reason for such problems? (HDF5 version, for example?)

**Comment by mccoys** [comment]
We have discovered such a deadlock situation in the latest version. It seems that it might be related to the no_mpi_tm compilation mode. Is it your case ?

**Comment by jpsikal** [comment]
I am not sure. I did not use option "make config=no_mpi_tm" for compilation. On the other hand, I received warning messages "some OpenMP processing was skipped to constrain compile time, consider overriding limits -qoverride_limits" during compilation. 
I am thinking about HDF5 version. When I used "module load HDF5", I received a message: "The following have been reloaded with a version change: 1) HDF5/1.10.4-intel-2018a-parallel => HDF5/1.10.5-intel-2017c". 
Anyway, you are probably right that this problem is related to Smilei version 4.3. When I did some tests with version 4.2, the same problem does not occur (without using OpenMP).

**Comment by jderouillat** [comment]
Hi, 

OpenMP warnings are not a problem, it appears from many time in non critical functions.  

Before going on an issue with this release of Smilei, it's important to clarify the HDF5 environment : did/could you recompile Smilei in a coherent environment where the code and the HDF5 library are compiled with the same compiler and the same MPI library ?

About the problem itself what is the amount of resources used ? Number of MPI process, of OpenMP threads, of nodes ?  The MPI library ?
Which kind of physics are you doing, with which diagnostics ?  
Could you provide the namelist and the logfile ? 

Regards

Julien

**Comment by jpsikal** [comment]
Thanks for your fast reply. I have done more tests and I found that this problem is not related to a specific version of Smilei (4.3), the deadlock occurred also with Smilei version 4.2. According to my observations, it depends on simulation parameters I have used. And similar problem occurred on two different computer clusters. 
For simplicity, I have tested the propagation of laser pulse in the simulation box without any plasma (particles). When the simulation box was larger (3200x560x560 cells), the simulation run was successfully completed running on 8 cluster nodes (with 192 CPU cores in total, e.g. 24 cores per node) and Fields diagnostics worked well (also I successfully imaged outputs).  However, when I reduced the simulation box size (on 3200x128x128 cells) and ran it on the same number of nodes and on the same number of CPU cores, the deadlock occurred in the moment when Fields diagnostics was activated (it saved the first 470 MB of data and then the deadlock occurred). It is interesting that saving of the checkpoints worked when I switched off the Fields diagnostics in the beginning of the simulation, but later the deadlock occurred when the Field diagnostics was firstly activated. 
I observed such a deadlock on the second computer cluster using 20 nodes and 320 CPU cores in total (each node has 16 cores in this case) when I slightly reduced the simulation box from 3200x1280x1280 cells to 3200x1120x1120 cells (in the first case the simulation run was successfully completed, in the second case the deadlock occured). So, it seems that the deadlock happened just when reduced the number of cells in the simulation. Note that I did not meet any problems with 2D simulations (running them on 2 cluster nodes). On this computer cluster, I saw warning message "HDF5: infinite loop closing library" in the log file. 

Concerning compilation of HDF5 library, I am not sure. I would need to contact supercomputer administrators and it would be time consuming ...
Based on my observations which I described above, are you able to give me some advice? Note that Fields diagnostics I mentioned works for some simulation parameters and it does not work for other simulation parameters. Could it be related to the number of patches used in the simulation run?
Two namelists - namelist1 with simulation parameters and diagnostics which is working in my case and namelist2 for the simulation when deadlock occurs - are attached.

[namelist1.py.txt](https://github.com/SmileiPIC/Smilei/files/3955135/namelist1.py.txt)
[namelist2.py.txt](https://github.com/SmileiPIC/Smilei/files/3955136/namelist2.py.txt)

**Comment by jderouillat** [comment]
For namelist2 (3200x128x128 cells), it runs fine on 20 nodes of the supercomputer I use (16 cores per nodes), in MPI only (320 MPI) and MPI x OpenMP (40 MPI x 8 oMP), with the main part of time in the end of the simulation ie when Fields are dumped. In attachments logs of both simulations.

[smilei_namelist2_40MPI_8oMP.log](https://github.com/SmileiPIC/Smilei/files/3956569/smilei_namelist2_40MPI_8oMP.log)
[smilei_namelist2_320MPI_1oMP.log](https://github.com/SmileiPIC/Smilei/files/3956570/smilei_namelist2_320MPI_1oMP.log)

The problem could be a mix of the code and of the environment, as @mccoys says, he met a deadlock with OpenMPI on which we have a workaround which consists in inhibiting an OpenMPI protocol (`export OMPI_MCA_btl_portals4_use_rdma=0`). My simulations were IntelMPI simulations, what is the library that you are using ?

For namelist1, on 20 nodes, in MPI x OpenMP, it's running (fields have been dumped at timestep 192).

**Comment by jpsikal** [comment]
Thanks for your tests. By the way, I found that the deadlock does not occur in some case when I only decreased the number of patches from [64,16,16] to [32,16,16] compared with previous case when deadlock occurred. Anyway, this behaviour is very unstable and unpredictable. Probably, you are right the problem is a mix of the code and of the environment. I have no good control about the modules loaded on the supercomputer I used. 
For example, I loaded on the supercomputer: module load HDF5/1.10.4-intel-2018a-parallel and then:  module load Python/2.7.11-intel-2017a. 
(Then, I run Smilei simulation. )
After the second load (Python module), it gives me this message on the output:
The following have been reloaded with a version change:
  1) icc/2018.1.163-GCC-6.3.0-2.27 => icc/2017.1.132-GCC-6.3.0-2.27
  2) iccifort/2018.1.163-GCC-6.3.0-2.27 => iccifort/2017.1.132-GCC-6.3.0-2.27
  3) ifort/2018.1.163-GCC-6.3.0-2.27 => ifort/2017.1.132-GCC-6.3.0-2.27
  4) iimpi/2018a => iimpi/2017a
  5) imkl/2018.1.163-iimpi-2018a => imkl/2017.1.132-iimpi-2017a
  6) impi/2018.1.163-iccifort-2018.1.163-GCC-6.3.0-2.27 => impi/2017.1.132-iccifort-2017.1.132-GCC-6.3.0-2.27
  7) intel/2018a => intel/2017a
  8) zlib/1.2.11 => zlib/1.2.11-GCCcore-6.3.0
Using module list command gives me the following output: 
Currently Loaded Modules:
  1) GCCcore/6.3.0
  2) binutils/2.27-GCCcore-6.3.0
  3) Szip/2.1
  4) HDF5/1.10.4-intel-2018a-parallel
  5) iccifort/2017.1.132-GCC-6.3.0-2.27
  6) icc/2017.1.132-GCC-6.3.0-2.27
  7) ifort/2017.1.132-GCC-6.3.0-2.27
  8) impi/2017.1.132-iccifort-2017.1.132-GCC-6.3.0-2.27
  9) iimpi/2017a
 10) imkl/2017.1.132-iimpi-2017a
 11) intel/2017a
 12) bzip2/1.0.6-intel-2017a                            (C6)
 13) zlib/1.2.11-GCCcore-6.3.0                          (C6)
 14) ncurses/6.0-intel-2017a                            (C6)
 15) libreadline/6.3-intel-2017a                        (C6)
 16) Tcl/8.6.5-intel-2017a                              (C6)
 17) SQLite/3.13.0-intel-2017a                          (C6)
 18) Tk/8.6.5-intel-2017a                               (C6)
 19) GMP/6.1.1-intel-2017a                              (C6)
 20) libffi/3.2.1-intel-2017a                           (C6)
 21) Python/2.7.11-intel-2017a                          (C6)

  Where:
   C6:  Old CentOS6 module

For me, it is difficult to say you which library is used. 

For what I should ask supercomputer administrators?
Should I ask how they compiled HDF5 library (which version of compiler and MPI library)?
Should I ask them if they compiled OpenMPI  with --enable-mpi-thread-multiple?
showing this link http://www.maisondelasimulation.fr/smilei/install_linux.html

Hardware of the computer cluster I use is specified below this link:
https://docs.it4i.cz/salomon/hardware-overview/

**Comment by jpsikal** [comment]
So, after some recommendations from supercomputer administrators (which modules I should load) and after changing HDF5_ROOT_DIR?=$(HDF5_DIR) from HDF5_ROOT_DIR?=$(HDF5_ROOT) in makefile before the compilation of the code, it seems that it works well. Thanks for your advice and patience. Jan

**Comment by mccoys** [comment]
Do not change the makefile because it will perturb future updates.

Instead, add this (or equivalent) in a setup script:
```bash
export HDF5_ROOT_DIR=$(HDF5_DIR)
```
