### ISSUE TITLE
ImportError: No module named numpy.core._multiarray_umath on mac os 10.12

### ISSUE THREAD

**Issue by copilco** [SmileiPIC/Smilei#192]
Hello

I managed to compile the code after some effort with macports. Now it compiles but when i run it shows an error with the numpy library.

As i have several python and numpy version installed i have created a conda enviroment to use python 2.7 with numpy 4.8.0

But the error keep showing when i run the code

(py27) dresden:Smilei camilo$ make env
SMILEICXX : /opt/local/bin/mpicxx
PYTHONEXE : python
MPIVERSION : 
VERSION : v4.3-2-g442f29e7-master
OPENMP_FLAG : -fopenmp -D_OMP
HDF5_ROOT_DIR : 
SITEDIR : /Users/camilo/.local/lib/python2.7/site-packages
PY_CXXFLAGS : -I/anaconda3/envs/py27/include/python2.7 -I/anaconda3/envs/py27/include/python2.7 -I/anaconda3/envs/py27/lib/python2.7/site-packages/numpy/core/include -DSMILEI_USE_NUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
PY_LDFLAGS : -lpython2.7 -ldl -framework CoreFoundation -u _PyMac_Error
CXXFLAGS : -D__VERSION=\"v4.3-2-g442f29e7-master\" -D_VECTO -std=c++11 -Wall  -Isrc -Isrc/Checkpoint -Isrc/Collisions -Isrc/Diagnostic -Isrc/DomainDecomposition -Isrc/ElectroMagn -Isrc/ElectroMagnBC -Isrc/ElectroMagnSolver -Isrc/Field -Isrc/Interpolator -Isrc/Ionization -Isrc/Merging -Isrc/MovWindow -Isrc/MultiphotonBreitWheeler -Isrc/Params -Isrc/ParticleCreator -Isrc/ParticleInjector -Isrc/Patch -Isrc/picsar_interface -Isrc/Profiles -Isrc/Projector -Isrc/Pusher -Isrc/Python -Isrc/Radiation -Isrc/SmileiMPI -Isrc/Species -Isrc/Tools -Ibuild/src/Python -I/anaconda3/envs/py27/include/python2.7 -I/anaconda3/envs/py27/include/python2.7 -I/anaconda3/envs/py27/lib/python2.7/site-packages/numpy/core/include -DSMILEI_USE_NUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D_VECTO -O3 -g  -fopenmp -D_OMP
LDFLAGS : -lhdf5 -lpython2.7 -ldl -framework CoreFoundation -u _PyMac_Error -lm -fopenmp -D_OMP
(py27) dresden:Smilei camilo$ export HDF5_ROOT_DIR=/opt/local/

(py27) dresden:Smilei camilo$ cd Test001/
(py27) dresden:Test001 camilo$ ls
tst1d_04_radiation_pressure_acc.py
(py27) dresden:Test001 camilo$ ../smilei tst1d_04_radiation_pressure_acc.py 
                    _            _
  ___           _  | |        _  \ \   Version : v4.3-2-g442f29e7-master
 / __|  _ __   (_) | |  ___  (_)  | |   
 \__ \ | '  \   _  | | / -_)  _   | |
 |___/ |_|_|_| |_| |_| \___| |_|  | |  
                                 /_/    
 
 

 Reading the simulation parameters
 --------------------------------------------------------------------------------
 HDF5 version 1.10.5
ImportError: No module named numpy.core._multiarray_umath
Stack trace (most recent call last):
#1    Object "smilei", at 0x1061e8e91, in main + 961
#0    Object "smilei", at 0x1060d1f17, in Params::Params(SmileiMPI*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >) + 1127
Segmentation fault: 11
(py27) dresden:Test001 camilo$

**Comment by mccoys** [comment]
numpy 4.8 ? The latest version is 1.17 ...

Anyways, this is an issue of versions of numpy vs other packages in your python installation. It has little to do with smilei. See for instance https://github.com/numpy/numpy/issues/11871. Try to upgrade numpy : `pip install --upgrade numpy`

**Comment by copilco** [comment]
Fixed with pip install --upgrade numpy
