### ISSUE TITLE
Cannot define "Compute_table" in RadiationReaction block

### ISSUE THREAD

**Issue by mjirka** [SmileiPIC/Smilei#193]
Hi,

if I set `compute_table = True` in _RadiationReaction_ block I get this error when reading the simulation parameters:

`Parsing input.py`
`[Python] Exception: ERROR in the namelist: cannot define compute_table in block RadiationReaction()`
`[ERROR](0) src/Params/Params.cpp:1178 (runScript) error parsing input.py`

When `compute_table = True` is commented out, the simulation runs.

Any advice how to enable table computing?

Thanks

**Comment by xxirii** [comment]
Dear @mjirka,

I am surprised because this is tested regularly in our CI.

Can you confirm you use the last version of Smilei? Can you also provide me the full input file?

Thank you

**Comment by iltommi** [comment]
you can have a look at file `benchmarks/tst1d_14_tables.py`

https://github.com/SmileiPIC/Smilei/blob/master/benchmarks/tst1d_14_tables.py#L107

**Comment by mjirka** [comment]
Hi, using the latest version of Smilei-v4.3 solved the issue. I have tested it with `benchmarks/tst1d_14_tables.py`. Thanks
