### ISSUE TITLE
CFL condition in AMCylindrical geometry

### ISSUE THREAD

**Issue by lesnat** [SmileiPIC/Smilei#194]
Hi everyone !
I hope everything is going right for the Smilei team ; and thank you for your work on cylindrical geometry ! We at CELIA are very interested about this feature, so be ready to probably receive some bug reports about it for the new year ;)

For now I only have a quick question:
How to choose a proper timestep to match the CFL condition in AMCylindrical geometry ?

The paper R. Nuter et al., Eur. Phys. J. D 68, 177 (2014). gives the stability condition for the Yee scheme and some other maxwell solvers, but I have no idea of what to use for this geometry. I searched on the reference paper A. F. Lifschitz et al.,Journal of Computational Physics 228, 1803 (2009). but found nothing about it.

I also tried to use the `timestep_over_CFL` parameter in `Main`, as proposed [in this issue](https://github.com/SmileiPIC/Smilei/issues/161#issuecomment-529906463), but even with the last version of the code it gives me the following error (which is not very clear)

> 	[ERROR] (0) src/Params/Params.cpp:1183 (runScript) error parsing namelist.py
	 [Python] AttributeError: type object 'Main' has no attribute 'number_of_modes'
	[ERROR] (0) src/Params/Params.cpp:1183 (runScript) error parsing namelist.py

Thank's a lot !
Cheers,
Léo.

**Comment by beck-llr** [comment]
Hi Leo
I expect more "misusage of the code" reports than bug reports actually :-)
Anyway, we're glad to help ! In your specific case the problem comes from the fact that you do not specify the number of azimuthal modes you want to use in your simulation. This is mandatory as explained in the error message and the documentation. Look for `number_of_AM`.

To answer your question, yes the feature `timestep_over_CFL` is supposed to work.

**Comment by beck-llr** [comment]
I may have spoken a bit too quickly. It is not well explained in the doc. I'll fix that ! Thanks. By the way we are currently working on a new complete documentation of this feature and it should come out soon.

**Comment by beck-llr** [comment]
I take it back again and there was indeed a bug :-)  I've pushed a correction which should be available soon in the master branch.
In the meantime, you can force your timestep to be correct. The formula is the following:
```
Main.timestep = Main.timestep_over_CFL / math.sqrt(1./Main.cell_length[0]**2 + ((Main.number_of_AM-1)/Main.cell_length[1])**2 )
```

**Comment by lesnat** [comment]
This is exactly what I needed

> ```Main.timestep = Main.timestep_over_CFL / math.sqrt(1./Main.cell_length[0]**2 + ((Main.number_of_AM-1)/Main.cell_length[1])**2 )```

Thank's !
