### ISSUE TITLE
How  to   Fast Fourier transform

### ISSUE THREAD

**Issue by jafarimjafar** [SmileiPIC/Smilei#198]
Hi dear Smilei team,
Many thanks for the  Smilei  code
How to get Fourier transform field file by using Field.h5  file.
my .h5  file including  Ex  and  Ey.

so thanks.

**Comment by mccoys** [comment]
Hi

Smilei does not include the fft. You have to obtain the data using the python module happi (look in the documentation for getData) then use some fft module to compute the Fourier transform
