### ISSUE TITLE
Cannot import module into namelist

### ISSUE THREAD

**Issue by GeorgeHicks1** [SmileiPIC/Smilei#199]
Hi,

I would like to be able to import my own module into a Smilei namelist, however, whenever I try I get an error ` [Python] ImportError: No module named my_module`, even when the module is in the same directory as Smilei and the namelist.

Smieli log:
[log.txt](https://github.com/SmileiPIC/Smilei/files/4077816/log.txt)

Namelist: (converted to .txt for uploading here)
[namelist.txt](https://github.com/SmileiPIC/Smilei/files/4077823/namelist.txt)

My test module: (converted to .txt for uploading here)
[my_module.txt](https://github.com/SmileiPIC/Smilei/files/4077819/my_module.txt)

Does anyone have any ideas what I'm doing wrong?

Thanks,
George

**Comment by mccoys** [comment]
You must place your module where python can find it. For instance, use the environment variable PYTHONPATH.

More info https://www.learnpython.org/en/Modules_and_Packages

**Comment by mccoys** [comment]
Note that the module can simply be in your current directory (that is not necessarily that of smilei or the namelist)

**Comment by GeorgeHicks1** [comment]
Thank you. It appears smilei was being run in a different directory from what I expected. The solution I've gone for is having this code in my namelist:

`import os`
`import sys`
`sys.path.append(os.getcwd())`
`import my_module`
