### ISSUE TITLE
abs(coeff2*qqm*term3*term5)

### ISSUE THREAD

**Issue by wphu** [SmileiPIC/Smilei#2]
In line 325 of the file /src/Collisions/Collisions.cpp, should the expression `abs(coeff2*qqm*term3*term5)` be `abs(coeff2*qqm*term3*term5*term5)` ?

**Comment by mccoys** [comment]
Hi,

This is not an error. In Ref [http://dx.doi.org/10.1063/1.4742167], the corresponding formula indeed shows a squared expression that should be written `term5*term5`, but this was a typo.

The correct expression has no squared term, as I just verified from the expressions given in the article. The calculation of the minimum deviation angle can be derived from Ref [http://dx.doi.org/10.1143/JPSJ.67.4084] with some effort.

I will make a note about this in the documentation.

Cheers

**Comment by wphu** [comment]
OK, thank you very much.
