### ISSUE TITLE
Bug that dos not exist with version Smilei 4.1

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#200]
Hi dear Smilei team, Happy new year to all of you!

I have a problem with this simulation. The err information clearly overtake me... But this simulation worked with past version of Smilei it's sure.

If you can help me... Here are the out, err and namelist CH2d.py

[out.txt](https://github.com/SmileiPIC/Smilei/files/4084711/out.txt)
[err.txt](https://github.com/SmileiPIC/Smilei/files/4084712/err.txt)
[CH2d.txt](https://github.com/SmileiPIC/Smilei/files/4084715/CH2d.txt)

Thanks

Julien

**Comment by mccoys** [comment]
I have no idea about this error, but did you `make clean`?

**Comment by juliencelia** [comment]
I try with the version 4.3.
I turn off vectorization to be sure.

**Comment by juliencelia** [comment]
OK.I made clean.
And recompile.
It seems this is a bug with boris pusher (cf out.txt)

This simulation start with a mix of CH cold and non ionized...

I don't understand... With ionized gas I have no issue. And I am sure that simulation worked well with smilei 4.1 (it is the same namelist as before I retested)

[CH2d.txt](https://github.com/SmileiPIC/Smilei/files/4108251/CH2d.txt)
[err.txt](https://github.com/SmileiPIC/Smilei/files/4108252/err.txt)
[out.txt](https://github.com/SmileiPIC/Smilei/files/4108253/out.txt)

Thanks

**Comment by jderouillat** [comment]
Not sure.  
Indeed `> Pusher: boris` is the last print in the log file. But there is also the error above in the error file  :
```bash
#0    Object "./smilei", at 0x856d45, in Profile::Profile(_object*, unsigned int, std::string, bool)
```
After the creation of the pusher, there is the creation of the density profile. For instance, in the last simulation I ran :
```
                 > Pusher: boris
                 > Density profile: 2D user-defined function (does not use numpy)
```
I think that there is a problem with the profile or with the management of the profile by the code on this supercomputer.

**Comment by juliencelia** [comment]
I will try the hotline.

I would like to try this simulation on skylake... I compiled smilei on this partition but I think I have an issue with job sumission due to configuration of this partition. Anyone in the team use skl?

**Comment by MickaelGrech** [comment]
Hey @juliencelia ,
Yes, I'm using the SKL machine.

So, first, all my environment data are in a file in my home which I called `.env_smilei_skl`.
In this file I have the following:
`# environment for Smilei on Irene-SKL`
`module purge`
`module load intel/18.0.3.222`
`module load mpi/intelmpi/2018.0.3.222`
`export HDF5_ROOT=/ccc/work/cont003/smilei/derouilj/hdf5-1.8.16-intelmpi2018.18`
`export PATH=${HDF5_ROOT}/bin:${PATH}`
`export LD_LIBRARY_PATH=${HDF5_ROOT}/lib:${LD_LIBRARY_PATH}`
`export HDF5_ROOT_DIR=${HDF5_ROOT}`
Note that you need to be granted access to the SMILEI project on the Irene SKL machine to export  HDF5_ROOT correctly. You can ask @beck-llr to grant you access.

Then, here is an example of the submission script I use:
`#!/bin/bash`
`#MSUB -r generate_RadiationTables`
`#MSUB -n 1024`
`#MSUB -c 1`
`#MSUB -N 22`
`#MSUB -T 3600`
`#MSUB -o out.o`
`#MSUB -e err.e`
`#MSUB -A gen7678`
`#MSUB -q skylake`
`#MSUB -m work,scratch`
`#MSUB -x`
`source /ccc/cont003/home/luli/grechm/.env_smilei_skl`
`export OMP_NUM_THREADS=1`
`export OMP_SCHEDULE=dynamic`
`export OMP_PROC_BIND=true`
`ccc_mprun ./smilei generate_RadiationTables.py`

**Comment by juliencelia** [comment]
@beck-llr Dear Arnaud,

I am interested ;)

**Comment by beck-llr** [comment]
Sure. Please **email** me your login on Irene.

**Comment by juliencelia** [comment]
@beck-llr Dear Arnaud,

I am interested ;)

**Comment by juliencelia** [comment]
My login is : bonvalej
Thanks

**Comment by beck-llr** [comment]
I bolded the word **email** in my previous post for a reason ...

**Comment by juliencelia** [comment]
Hi,

Hotline solved this issue.It was a problem between smilei compilation and numpy version it seems.
Nevermind,it works!

Thanks

Julien
