### ISSUE TITLE
Errors initialising species/Inject particles from txt file

### ISSUE THREAD

**Issue by YCAOsz** [SmileiPIC/Smilei#202]
Hi.  I encountered a problem when trying to inject particles from a txt file (with position_initialisation and momentum as arrays). 
Here are the script and txt files:
[seriesbunch3.txt](https://github.com/SmileiPIC/Smilei/files/4129212/seriesbunch3.txt)
[smilei_012720_envelope_inject.py.zip](https://github.com/SmileiPIC/Smilei/files/4129225/smilei_012720_envelope_inject.py.zip)

The output scripts keeps saying:

 Initializing species
 --------------------------------------------------------------------------------
	 
	 Creating Species : electron
		 > Pusher: ponderomotive_boris
		 > Density profile: 1D user-defined function (does not use numpy)
	 
	 Creating Species : beam1
		 > Pusher: ponderomotive_boris
	[ERROR](0) src/Species/SpeciesFactory.h:541 (create) For species 'beam1' non valid position_initialization. It must be either a string or a numpy array.

I made sure the positions and momentums are ndarrays. I also tried np.stack or np.vstack and they don't work either. I wonder what went wrong.
Thanks

**Comment by beck-llr** [comment]
Hi
Thank you for your feedback and congratulations to you because your namelist is Smilable. I was indeed able to run more than 100k iterations of your simulation on our local cluster: 
[log_beam1.txt](https://github.com/SmileiPIC/Smilei/files/4129336/log_beam1.txt)


This means that the problem you are facing probably comes from your software stack. From the look of your namelist I guess your are running Smilei on an Apple computer ? I am no expert at all but I'm sure someone will be able to help you around here.

**Comment by YCAOsz** [comment]
I think it does work on the cluster after I updated it to the newest version. That problem may be due to a different python version and an old version smilei script. Thank you anyway.

**Comment by Z10Frank** [comment]
So, changing the Python version and updating smilei and the script solved your problem?

**Comment by YCAOsz** [comment]
It ran well for a few days. However, after I changed some packages in my anaconda personal directory (for some other code to work) and modified a few parameters for the input script, it shows segmentation error: 
Stack trace (most recent call last):
#9    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#8    Object "/rds/general/ephemeral/user/yc15818/ephemeral/Smilei_a02_7e23_Inj_020520/smilei", at 0x5dfdf3, in 
#7    Object "/lib64/libc.so.6", at 0x2aec7d553504, in __libc_start_main
#6    Object "/rds/general/ephemeral/user/yc15818/ephemeral/Smilei_a02_7e23_Inj_020520/smilei", at 0x90a911, in main
#5    Object "/rds/general/ephemeral/user/yc15818/ephemeral/Smilei_a02_7e23_Inj_020520/smilei", at 0x90d301, in PatchesFactory::createVector(VectorPatch&, Params&, SmileiMPI*, OpenPMDparams&, unsigned int, unsigned int)
#4    Object "/rds/general/ephemeral/user/yc15818/ephemeral/Smilei_a02_7e23_Inj_020520/smilei", at 0x8383a9, in Patch1D::Patch1D(Params&, SmileiMPI*, DomainDecomposition*, unsigned int, unsigned int)
#3    Object "/rds/general/ephemeral/user/yc15818/ephemeral/Smilei_a02_7e23_Inj_020520/smilei", at 0x7e7813, in Patch::finishCreation(Params&, SmileiMPI*, DomainDecomposition*)
#2    Object "/rds/general/ephemeral/user/yc15818/ephemeral/Smilei_a02_7e23_Inj_020520/smilei", at 0x7ee4cd, in SpeciesFactory::createVector(Params&, Patch*)
#1    Object "/rds/general/ephemeral/user/yc15818/ephemeral/Smilei_a02_7e23_Inj_020520/smilei", at 0x7f7bdc, in SpeciesFactory::create(Params&, int, Patch*)
#0    Object "/rds/general/ephemeral/user/yc15818/ephemeral/Smilei_a02_7e23_Inj_020520/smilei", at 0x85ab46, in Profile::Profile(_object*, unsigned int, std::string, bool)
Segmentation fault (Address not mapped to object [0x10])

Can you specify the version of packages/python that is compatible with the current smilei code?
Thank you

**Comment by Z10Frank** [comment]
Normally this information is in the Install page of the documentation: https://smileipic.github.io/Smilei/installation.html

**Comment by mccoys** [comment]
Could you provide your new input script ? This might also be a bug.

**Comment by mccoys** [comment]
Note that smilei is supposed to be compatible with python 2.7 and 3+, although there are corner cases that still have not been updated for 3+. Python modules should not interfere as none is really needed by smilei, except for numpy. However, I don't think anybody has found some issue related to the version of numpy yet.

**Comment by YCAOsz** [comment]
This is the script. The python version used is 3.6.6 
Thank you
[InputModified.txt](https://github.com/SmileiPIC/Smilei/files/4170928/InputModified.txt)

**Comment by mccoys** [comment]
It does not seem to be a bug in Smilei as I could succesfully run your simulation up to 20000 timesteps. This is my setup :

* HDF5 version 1.10.6
* Python version 3.7.5
* g++-8
* Open MPI 4.0.2

It is probably an error in your python installation.

**Comment by YCAOsz** [comment]
Is it possible that I run this on anaconda/personal and initialize a conda environment (to keep the code running at one specific version)? I'm now using a supercomputer cluster and it seems hard to specify which default python/hdf5 or other packages version to use. Do I need to compile the code again in order to do so?

I tried to install smilei for another person and there still seem to have error compiling from the instructing below (which worked before). I think the code couldn't call the same path to use these packages after the system (cx1) upgrade. It would be great if you could have a make version suitable for imperial cx1 cluster. Thanks ) 

When in your cx1 home directory, type in terminal `tar xvzf Smilei.tar.gz'
Navigate to the new directory via terminal or finder and open the makefile. Edit line 10 so it reads:
HDF5_ROOT_DIR ?=/apps/hdf5/1.10.1/
Compile smilei by navigating to the smilei folder and running the commands
module load intel-suite/2017 
module load mpi/intel-2018
 module load hdf5/1.10.1
 make
You should get a lot of text appearing saying that everything is compiling. Afterwards, you should have a smilei unix executable in your smilei directory.

**Comment by mccoys** [comment]
It is very hard to figure out how to setup your system without having access to it.

There are environment variables that can be set before compilation:
```
export HDF5_ROOT_DIR=path/to/hdf5/library
export PYTHONEXE=path/to/python
export PYTHONHOME=path/to/python/folder
export CXXFLAGS="flags for compiler"
export LDFLAGS="flags for linker"
```
Then compile.

Don't hesitate to `make clean` before compiling when you change your setup in order to clean older compilation.

We have had trouble with anaconda in the past, because it seems to provide header files different from the python executable in some circumstances.

It is technically possible to install another version of python in your home directory and use that version.

**Comment by mccoys** [comment]
Please let us know if you managed to get a working configuration

**Comment by Z10Frank** [comment]
I'll close the issue if there are no updates. Please feel free to reopen it in case you have news.
