### ISSUE TITLE
Segmentation fault in VectorPatch::dynamics(...)

### ISSUE THREAD

**Issue by andsunds** [SmileiPIC/Smilei#203]
When I try to run a fairly large scale collisional 2D simulation on a cluster, the simulation seems to crash as soon as `time_frozen` has ended for the two species. Input files (with slurm submission scrips) together with the error and outputs generated when running are attached below.

A similar simulation at a much smaller scale (lower resolution and lower particles per cell) ran fine when I tested it (inputs with outputs also attached). Although this may indicate that I am running out of memory, the reported expected memory usage seems to be well within the 128 GB per node of the cluster.

I write that the simulation is with collisions, however, I do not know yet if it is really the collisions that are causing the issue.

### Technical details
[The hardware I'm running on](https://www.hpc2n.umu.se/resources/hardware/kebnekaise) (running on the "compute" nodes.)

[input.zip](https://github.com/SmileiPIC/Smilei/files/4133056/input.zip)
[err.txt](https://github.com/SmileiPIC/Smilei/files/4133036/err.txt)
[out.txt](https://github.com/SmileiPIC/Smilei/files/4132891/out.txt)

[input_small_working.zip](https://github.com/SmileiPIC/Smilei/files/4133035/input_small_working.zip)

**Comment by mccoys** [comment]
Look at your out.txt. There is a warning showing you do not comply with the CFL condition. This is why it segfaults

**Comment by andsunds** [comment]
Oh, sorry! I will change this immediately!
