### ISSUE TITLE
ModuleNotFoundError: No module named 'encodings' in running smilei

### ISSUE THREAD

**Issue by Michael-Gong** [SmileiPIC/Smilei#204]
Dear all,

Thanks for your time.

I have already succeeded in make, but when I run "./smilei input.py" in my Mac terminal, the error comes out:

                    _            _
  ___           _  | |        _  \ \   Version : bv4.3-78-g03aa8828-bmaster
 / __|  _ __   (_) | |  ___  (_)  | |   
 \__ \ | '  \   _  | | / -_)  _   | |
 |___/ |_|_|_| |_| |_| \___| |_|  | |  
                                 /_/    
 
 
 Reading the simulation parameters
 --------------------------------------------------------------------------------
 HDF5 version 1.10.5
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x0000000113db15c0 (most recent call first):
Stack trace (most recent call last):

**Comment by mccoys** [comment]
Your python installation appears faulty. As indicated by the error message, please set the environment variable PYTHONHOME to the folder containing the python executable

**Comment by Michael-Gong** [comment]
> Your python installation appears faulty. As indicated by the error message, please set the environment variable PYTHONHOME to the folder containing the python executable

Thanks. After I set the 
export PYTHONHOME="/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7"
in my .bash_profile
make clean
make

That works.

Thanks for your quick reply. I really appreciate.

**Comment by Michael-Gong** [comment]
The problem has been resolved
