### ISSUE TITLE
problem with checkpointing

### ISSUE THREAD

**Issue by iplasma** [SmileiPIC/Smilei#205]
## Description

I have a run that I need to checkpoint and restart. For my first run, I have the following block in the input deck

```
Checkpoints(
    #restart_dir = "./",
    dump_step = 2500,
    dump_minutes = 15.5*60,
    exit_after_dump = False,
    keep_n_dumps = 2,
)
```
I get checkpoint files from all processors (1440 total) at step 2500, however, I don't get any checkpoint file for the dump at the time limit specified (15.5 hours or 930 minutes, the job run time limit is 16 hours). There is not even any output regarding this in the log file, but I do see the corresponding lines for the dump at step 2500. The time stamps of all these 1440 files show they are dumped within about 2 minutes.

What is more strange is that for the first restart run from checkpoint step 2500, for which I used the following block in input deck to restart,

```
Checkpoints(
    restart_dir = "../",
    restart_number = 0,
    dump_step = 2500,
    dump_minutes = 15.5*60,
    exit_after_dump = False,
    keep_n_dumps = 2,
)
```
I can see the output in the log file corresponding to the dump_minutes, see below 

```
   4340/6731     6.4479e+01     5.5246e+04   (  3.2583e+02 )
   4350/6731     6.4628e+01     5.5592e+04   (  3.4641e+02 )
 Reached time limit : 930.726 minutes. Dump timestep : 4356
 Step 4356 : DUMP fields and particles 1
   4360/6731     6.4777e+01     5.6067e+04   (  4.7506e+02 )
   4370/6731     6.4925e+01     5.6398e+04   (  3.3029e+02 )
   4380/6731     6.5074e+01     5.6727e+04   (  3.2990e+02 )
   4390/6731     6.5222e+01     5.7055e+04   (  3.2799e+02 )
   4400/6731     6.5371e+01     5.7405e+04   (  3.4910e+02 )
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
```
but a lot of the checkpoint files for this dump are missing.  For those checkpoint files dumped (1068 out of 1440), the time stamps show they are dumped within about 3 minutes, and the run is terminated about 26 minutes later, so there should be enough time to write to disk.  

I am wondering why I don't get dump corresponding to the time specified in the first run, but can get incomplete dump in the restart run? Any thoughts on how to troubleshoot this problem will be appreciated. 

Update: 
Initially I though this is due to dynamic load balancing. But this problem persists after I practically disable load balancing by using a very large period.
The simulation result seems normal for both the first and second runs, but I cannot restart any more due to missing checkpoint files.

## Parameters

- Smilei version : bv4.1-917-g9e16924-bmaster
- Computing resources
  - OS : Red Hat Linux
  - C++ compiler (to get some information `g++ --version`) : intel/19.0.4
  - MPI version (`mpic++ --version`, `mpic++ -show`) : intel-mpi/2019.4
  - HDF5 version (`h5cc --version`) : 1.8.16
  - Python version (`python --version`) : 3.6.3

**Comment by mccoys** [comment]
One idea that comes to mind. Some file systems are not very good at handling folders with many files, and may cause missing files in that case. You could try the fike_grouping argument if that's the problem

**Comment by beck-llr** [comment]
What @mccoys suggest did solve the problem of the partially missing files for me once. I used `file_grouping = 4` for 1200 MPI processes.

 Stranger is that you didn't get anything (not even an output in the log !!) at the first dump_minute ... Maybe we should investigate that with intel 2019. But it is apparently difficult to reproduce since it worked on your restart which shouldn't make any difference.
Thanks for reporting this !

**Comment by beck-llr** [comment]
edit: `file_grouping=400` of course. Not 4 as I first entered by error.

**Comment by iplasma** [comment]
Thank you for the suggestion! I will try and let you know.

**Comment by mccoys** [comment]
I doubt ionisation or collisions will cause this kind of problem

**Comment by iplasma** [comment]
I tried the suggestion of file_grouping with the following block in the input deck 

```
Checkpoints(
    #restart_dir = "./",
    dump_step = 2500,
    dump_minutes = 5,
    exit_after_dump = False,
    keep_n_dumps = 2,
    file_grouping=400,
)
```
However, I got this error 

```
[ERROR](0) src/Tools/PyTools.h:246 (checkPyError) TypeError: 'float' object cannot be interpreted as an integer
```
I thought maybe my Smilei version is old, and I check out the latest one on github. But the error remains. 

```
                    _            _
  ___           _  | |        _  \ \   Version : bv4.3-92-g6b25773-bmaster
 / __|  _ __   (_) | |  ___  (_)  | |
 \__ \ | '  \   _  | | / -_)  _   | |
 |___/ |_|_|_| |_| |_| \___| |_|  | |
                                 /_/



 Reading the simulation parameters
 --------------------------------------------------------------------------------
 HDF5 version 1.8.16
     Python version 3.6.3
     Parsing pyinit.py
     Parsing bv4.3-92-g6b25773-bmaster
     Parsing pyprofiles.py
     Parsing inp.py
     Parsing pycontrol.py
     Check for function preprocess()
     python preprocess function does not exist
     Calling python _smilei_check
     Calling python _prepare_checkpoint_dir
    [ERROR](0) src/Tools/PyTools.h:246 (checkPyError) TypeError: 'float' object cannot be interpreted as an integer
```

Am I doing anything wrong?

**Comment by mccoys** [comment]
It might be something we have not yet made compatible with python 3.6. Let me check

**Comment by iplasma** [comment]
Update:

The error with file_grouping occurs for both Python 3.5 and 3.6, but disappears with Python 2.7.

If dump_step is hit first, dump_minutes will not be activated. However, if dump_minutes is hit first, dump_step still works. 

Now I can restart with file_grouping in a test run. I will test the run with 1440 processors later.

**Comment by mccoys** [comment]
I have found the bug. Will post it soon.

**Comment by mccoys** [comment]
Should be fixed now. If you can try again and check, please close the issue. Otherwise tell me and I will close.
Cheers

**Comment by iplasma** [comment]
I can confirm that the error message regarding file_grouping in the input deck no longer appear with python 3.6. 

But I got an error message if the number of groups > 10, 

```
#003: ../../src/H5FDsec2.c line 339 in H5FD_sec2_open(): unable to open file: name = 'checkpoints/00/dump-00000-0000000000.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242
```

it looks like the naming of the sub directory is not consistent as the actual directory created is "checkpoints/0". 

The issue with dump_minutes not activated if dump_step is hit first is still there. This is not a big issue but perhaps can be documented to avoid confusion.

I ran test for restarting with file_grouping on 1080 processors. There is no missing file. This is the limit of processors I can test on an interactive queue, but I think the longer run with 1440 processor should be okay. Will report back.

Thanks for the help!

**Comment by mccoys** [comment]
Be careful that the file_grouping for your second simulation is the same as that for the first one

**Comment by iplasma** [comment]
The error for "unable to open file" happens for the first simulation when it is writing checkpoint files. It seems the code is trying to write to files in "checkpoints/00" directory but the actual directory created in named "checkpoints/0".

**Comment by mccoys** [comment]
Ok there was some error remaining due to python 3+ compatibility. Please try will the latest changes.

**Comment by iplasma** [comment]
The problem of ""unable to open file" is fixed. Thanks!
