### ISSUE TITLE
"charge" from TrackParticles diag

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#207]
Dear Smilei team,

I have a question about charge of species. I ran a simulation with a CH target irradiated by a laser with I=5e19W/cm2 on 1.5ps. 
I use a TrackParticles diag to record all the carbon ions coming out from the target.

**And charge is always 6.**

Physically, that seems strange. I used 'tunnel' ionisation model. 
What do you think about that?

[CH2d.txt](https://github.com/SmileiPIC/Smilei/files/4185280/CH2d.txt)

**Comment by mccoys** [comment]
Why is that strange ? Could you follow how the charge evolves ?

**Comment by juliencelia** [comment]
Yes! 
I will try to follow that with a PaticleBinning with axis "charge".
very good idea.

Thanks Mccoys!

**Comment by juliencelia** [comment]
![avg_chargeC](https://user-images.githubusercontent.com/48507571/74239470-325faf80-4cd8-11ea-8269-f5feda52258d.png)

With Scalar I can see that charge go from 0 to 6 for carbon ions in 500fs.... I had the idea that carbon ions 5+, 4+ could survive...

**Comment by juliencelia** [comment]
OK. The simulation doesn't match with the experiment (we have C5+). But it must be from the recombination. That could be cool that SMILEI deals with that physics ;)))

**Comment by mccoys** [comment]
Recombination is often slower. Make sure you have the right parameters for the laser / prepulse. This is often a source of error.
