### ISSUE TITLE
plasma full ionization

### ISSUE THREAD

**Issue by jafarimjafar** [SmileiPIC/Smilei#210]
Hi dear Smilei team,
Many thanks for the Smilei code. I faced a problem in the input file as below.
I have set a thin AL full ionized  target with 13 charge number. we set the equal number density for electron and ion in the input file. My question is; does the code itself arrange the electron density as 13 times of ion density? 
In fact set the equal density number for electron and ion for fully ionized plasma (except of hydrogen) is right or not?
I was wondering if you could help me with these questions.
Best regards,

**Comment by mccoys** [comment]
Hi

You did not provide your input file.
Smilei will not automatically adjust the density of one species compared to another.
You have to use either `number_density` (the number of real particles per unit volume) or the `charge_density` (which is obvious) for each species. If you set the same `charge_density` then they will surely have the same charge density ! This is quite obvious I think.

**Comment by jafarimjafar** [comment]
thanks
