### ISSUE TITLE
DiagFields subgridded with AMcylindrical geometry doesn't work

### ISSUE THREAD

**Issue by unpairedbracket** [SmileiPIC/Smilei#211]
## Description

It is possible to request DiagFields output to use a subgrid, but when using AMcylindrical geometry the subgrid is not applied. I can't see any reference to this limitation in the "Write a Namelist" page of the documentation, and `happi` seems to get confused by the size of the diagnostic grid not matching the subgrid (e.g. if I define a `::8` subgrid in one direction, `happi` thinks the spatial separation of field points is 8 times larger than it actually is, as this would be the resolution if the subgrid were applied). I belive this is because the subgrid is not accounted for in `DiagnosticFieldsAM.cpp` - `findSubgridIntersection` is not called, as it is in the `DiagnosticFieldsND.cpp` versions of the class, but I'm not familiar enough with this code to propose a fix myself. If it's not possible to fix, I would suggest not allowing the user to set this option at all.

## Steps to reproduce the problem

Add the line `from numpy import s_`  at the top of, and `subgrid = s_[::10, ::10]` inside the active DiagField block in the benchmark file `tstAM_00_em_propagation.py`. The simulation grid is 800x100 cells so we expect the Fields to be dumped with 80x10 resolution, but the full 800x100 grid is dumped instead.

## Parameters

- Smilei from master branch at commit https://github.com/SmileiPIC/Smilei/commit/4bee4371164744db1e5b4fa4e124912abf4b3963

**Comment by mccoys** [comment]
Indeed, subgrid is not available for the AM geometry and this should be documented. I am adding the feature-request tag for future implementation.

**Comment by mccoys** [comment]
Let me add that we recommend using Probes instead of Field diagnostics. They allow for as many points as you like.

**Comment by mccoys** [comment]
@beck-llr @jderouillat is there a technical reason for not having subgrid in AM? Or is it simply by lack of time?

**Comment by jderouillat** [comment]
Hi,
I think that it's just because the `DiagnosticFieldsAM` implementation is older than the sub-grid’s.
A priori, there is no reason to not implement it.

**Comment by mccoys** [comment]
This feature is now available in v4.4.

@unpairedbracket Could you try and close if it works ?

**Comment by unpairedbracket** [comment]
Sorry it's taken while to respond to this, but I agree this is now fixed. Thanks for the help everyone.
