### ISSUE TITLE
crash "....CollisionsSingle.o" catastrophic error compilation irene joliot curie

### ISSUE THREAD

**Issue by kevinCassou** [SmileiPIC/Smilei#212]
Hello 
I'm facing the following error on irene compiling last version of Smilei 
`make -j4 machine=joliot_curie_skl config=verbose`
is ending with 
`build/src/Collisions/CollisionsSingle.o": catastrophic error: error while writing object file
compilation aborted for src/Collisions/CollisionsSingle.cpp (code 4)`
`make: *** [build/src/Collisions/CollisionsSingle.o] Error 4`
`make: *** Waiting for unfinished jobs....
build/src/Collisions/CollisionalIonization.o": catastrophic error: error while writing object file
compilation aborted for src/Collisions/CollisionalIonization.cpp (code 4)`
`make: *** [build/src/Collisions/CollisionalIonization.o] Error 4
build/src/Collisions/Collisions.o": catastrophic error: error while writing object file
compilation aborted for src/Collisions/Collisions.cpp (code 4)`
`make: *** [build/src/Collisions/Collisions.o] Error 4
build/src/Checkpoint/Checkpoint.o": catastrophic error: error while writing object file
compilation aborted for src/Checkpoint/Checkpoint.cpp (code 4)`
`make: *** [build/src/Checkpoint/Checkpoint.o] Error 4`

the result of the command 
`make env`
is  attached. [results_makeenv.txt](https://github.com/SmileiPIC/Smilei/files/4256362/results_makeenv.txt)

**Comment by beck-llr** [comment]
Hi Kevin
I am not able to reproduce that error on Irene with the latest master branch and the same compilation command. Maybe you could try to `make clean` before recompiling Smilei ? This is usually not necessary but sometimes you have to.

**Comment by kevinCassou** [comment]
Hi Arnaud,
Did a _make clean_ and  I got exactly the same error... 
I also check that the env is set right

**Comment by beck-llr** [comment]
You are in your $WORKDIR right ? Could you try to do the compilation in your $HOME ? This is not the normal workflow but I'm just trying to understand what the problem could be ... It is weird that the error happens while writing the object file.

**Comment by kevinCassou** [comment]
Well done ! It's working in my $Home ! I don't understand why

**Comment by beck-llr** [comment]
They might have a temporary problem with their file system. Do not hesitate to write to them to signal the problem ( hotline.tgcc@cea.fr) in case they are not aware of it.
Also if you're happy with the resolution of your issue you can close it :-)

**Comment by kevinCassou** [comment]
Many thanks. Closing ;-)
