### ISSUE TITLE
Ukin_bnd bigger than Uelm

### ISSUE THREAD

**Issue by Iuliana19** [SmileiPIC/Smilei#213]
Dear SMILEI developers,

I am trying to study the laser energy absorption in plasma using the scalar diagnostics, but I got some difficulties with Ukin_bnd. It seems that this diagnostic is bigger than the initial total energy in my system (Uelm=10^7 and Ukin_bnd=10^9). 
The current version of Smilei is: v4.3-98-g4bee437-master

I checked an older simulation with a previous Smilei version (6530a06-master) and there the Ukin_bnd gives a good result (Ukin_bnd = 10^6).

Could you help me please?

Please let me know if you need additional information.
Thank you!

Iuliana

**Comment by mccoys** [comment]
We have also had reports of this kind of problem. It seems related to some handling of boundary conditions in special cases. Is it possible for you to send an input file to reproduce the error ?

**Comment by Iuliana19** [comment]
Hello!
Thank you for your quick reply! 

I attached my script :)
[laserplasmacase1515.txt](https://github.com/SmileiPIC/Smilei/files/4267260/laserplasmacase1515.txt)

**Comment by mccoys** [comment]
I have corrected the bug in the last version (the mass of the ion was multiplied twice). Please try and tell us if it works now.

@juliencelia I believe you had this issue as well ?

**Comment by juliencelia** [comment]
The bug was about Ubal and Ubal_norm but the problem of mass could be the problem...
I have some simulations in the starting blocks.
When it s finished I ll update smilei and tell you ;)

**Comment by Iuliana19** [comment]
Thank you very much @mccoys! Its working perfect now! 
I will close this issue
