### ISSUE TITLE
deadlock occured when HDF5 is not able to open (read) restart (dump) file from a checkpoint

### ISSUE THREAD

**Issue by jpsikal** [SmileiPIC/Smilei#214]
Dear SMILEI developers, 

I have met problems during 3D simulations on large computer cluster when my simulation run should start from a checkpoint with damaged dump files (or with a set of many newly created dump files and an older dump file from previous checkpoint with the same name). 
In this case, the deadlock occurs and the simulation run does not terminate automatically. 
That can be dangerous in the case of large 3D simulations when the user does not know that some dump files are not complete or are older than the others. 
The user can simply loose a plenty of computational time on the cluster. 

The log file reporting error messages started as follows:
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 1038:
  #000: H5F.c line 509 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file

Is it possible to implement in SMILEI code that the run will terminate when the reported error occurs?

**Comment by beck-llr** [comment]
Hi !
I am actually experiencing a similar problem (job doesn't start but doesn't crash either and eats up all my computational allocation) but mine doesn't say anything at all in the log. As you report, it is also a case of failed restart because of some filesystem misfunction.

To the extent of my limited knowledge, it will never be possible to account for all logs given by hardware/software combinations possible. What could be possible is to try to catch an exception when opening the restart files maybe. We'll think about it.

**Comment by mccoys** [comment]
Yes, HDF5 provides error flags that we could detect and throw an error if it happens. This is also true when opening files or adding data when there is no more space

**Comment by jpsikal** [comment]
That is exactly what I had in mind. Add something like TRY ... CATCH/EXCEPT ... blocks into the code.

**Comment by mccoys** [comment]
I have added a verification in the latest push. Could you try on your faulty restart ?

**Comment by jpsikal** [comment]
I have tried it but the problem persists. There is still a deadlock after an attempt to read dump files. The only difference is that I see in log file the following message : [ERROR](0) src/Checkpoint/Checkpoint.cpp:112 (Checkpoint) Cannot find a valid restart file
instead of the message generated by the previous version of the code:
[ERROR](0) src/Tools/H5.h:369 (getVect) Reading vector patch_count is not 1D but -1D

I thought that with the new code version the simulation run will terminate automatically when the error occur but it is not the case.

**Comment by mccoys** [comment]
I pushed another fix. The problem was deeper than I thought. Could you try again ?

**Comment by jpsikal** [comment]
I tried it again and it works now (the simulation run automatically terminated after the error). Thanks, Jan.
