### ISSUE TITLE
Define a 'ParticleInjector' from 'zmin', which does nothing...

### ISSUE THREAD

**Issue by ekapadi** [SmileiPIC/Smilei#217]
## The problem and the context

**smilei_test accepts the namelist file without indicating any errors.**  (This is pretty bad.  :(  )

## The solution

Why should a codebase at the level of 'Smilei' accept a limitation like this?  I had to look at the C++ code before I could see that only the 'xmin' / 'xmax' settings did anything.  (To give credit where due, the documentation does only mention 'xmin' / 'xmax', but I thought that must just be an editing oversight.)

Please also see my other recent issues.  At the moment, I'm setting up a simulation using Smilei.  Getting this simulation to go forward is my highest priority, and with that in mind, I will initially just fork and just fix all of these things on my branch.
After that,  depending on how easy it is to submit pull requests to your central branch / release, I would be glad to submit the fixes for some of these issues.

**Comment by xxirii** [comment]
Dear @ekapadi,

I am glad you are interested in this feature. It was until recently experimental and only xmin/xmax was introduced. I agree that an error should be thrown in smilei_test. Are you extending the code on your side (injection from all directions) or do you request this feature?

**Comment by ekapadi** [comment]
Hi:

Sorry for my delayed response!  Right now, my plan is to implement this
feature.  If I run into any problems (i.e. before the "pull request"
stage), I'll get back in touch with you.

Yours,

Kort
--------------------------
*P.S.:  Problems so far*:  Smilei seems to have quite counter-intuitive
behavior with respect to particle initialization (, not even getting to
particle injection yet).  For example, why does the following
namelist-block create any particles at all?  My simulation requirement is
to start with *no* particles, and then *add* particles to the simulation
only via injection:

Species(
name = 'electrons0',
position_initialization = 'random',
momentum_initialization = 'cold',
ionization_model = 'none',
particles_per_cell = 16,
c_part_max = 1.0,
mass = 1.0,
charge = -1.0,
charge_density = np.zeros((4,0), dtype=float),
mean_velocity = [v_e, 0., 0.],
temperature = [0.],
time_frozen = 0.0,
boundary_conditions = [
["remove"],
["remove"],
["remove"],
],
)

As a software developer, I'm sure I can figure this out.  However, as a
Physicist end-user, it makes no sense to me at all, that
'particles_per_cell' would ever override a clearly-specified
charge_density, which seems to be the case.  (And I'll note that
'charge_density' and 'charge' imply 'number_density'.)

**Comment by beck-llr** [comment]
Hi
I am not sure why you pass a numpy array to `charge_density`. It is supposed to be either a float or a function. Maybe try to simply pass the float `0.`. That should behave as expected i.e. not create any particle.

**Comment by xxirii** [comment]
Dear @ekapadi,

The new version of Smilei does now include the injection in all directions. I will therefore close this issue.
