### ISSUE TITLE
parameter restart_number in Checkpoints block does not work properly

### ISSUE THREAD

**Issue by jpsikal** [SmileiPIC/Smilei#218]
I tested restart of large 3D simulation and I found the following issue.

I set restart_number = 0 in Checkpoints block:
Checkpoints(
    restart_dir = "../CHexp05r21",
    restart_number = 0,
    dump_step = RestEvery,
    exit_after_dump = False,
    keep_n_dumps = 2,
)
Note that there are two checkpoints in CHexp05r21 directory (files named dump-00000-*.h5 and dump-00001-*.h5)

I would expect that the simulation will restart from dump-00000-*.h5. 
Nevertheless, I was surprised that the simulation started from dump-00001-*.h5 (I see "Restarting fields and particles at step: 2594; master file: ../CHexp05r21/checkpoints/dump-00001-0000000000.h5" in the log file)

It works correctly only after I removed files dump-00001-*.h5 from the checkpoints subdirectory. 
Then, I got correctly "Restarting fields and particles at step: 2354; master file: ../CHexp05r21/checkpoints/dump-00000-0000000000.h5" in the log file.

Note that I do not want to use newer dump files (created at time step 2594 in my case) since some of them were not saved correctly. 
Anyway, according to SMILEI documentation it should load "dump-00000-*.h5" with the parameter restart_number = 0. So, there is a bug in the code.

Jan

**Comment by mccoys** [comment]
This is indeed not the expected behaviour. I will investigate.

**Comment by mccoys** [comment]
This should be solved now. There was a basic error when restart_number == 0

**Comment by jpsikal** [comment]
Based on my test, it seems that it works properly now, so I am closing this issue. 
Thanks, Jan
