### ISSUE TITLE
Checkpoints creation bug

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#219]
Hi Smilei team,

I have an issue with checkpoints at the first launch :

Reached time limit : 1380.002 minutes. Dump timestep : 162667
	[ERROR](0) src/Checkpoint/Checkpoint.cpp:203 (dumpAll) Can't open file for writing checkpoint checkpoints/00/dump-00000-0000000022.h5

I use "file_grouping" option because I had another issue when I restarted a big simulation (500nodes). I don't know if this is a part of the problem...

[out.txt](https://github.com/SmileiPIC/Smilei/files/4277378/out.txt)
[err.txt](https://github.com/SmileiPIC/Smilei/files/4277380/err.txt)
[BNH2d.txt](https://github.com/SmileiPIC/Smilei/files/4277381/BNH2d.txt)

**Comment by mccoys** [comment]
Could you check whether the folder checkpoints and the several folders inside were created ? Could you check the permissions on these folders to make sure you have access ? Please also check you have enough disk space.

**Comment by juliencelia** [comment]
There is a folder checkpoints/ that contains folders 0 to 17. Only the folder 10 have something inside (30 filesdump-000....h5). So I think I have access. 
I have 4To of datas on my scratch. I am on TGCC. But I don't know how much we can have on scratch...

**Comment by juliencelia** [comment]
Hotliine gave me the limits of spaceson TGCC:
100To for SCRATCH
20Go for HOME
5To for WORK
no limit for STORE

So with my 4To on SCRATCH it is clearly not a disk space problem...

**Comment by mccoys** [comment]
could you check all permissions on all folders ?

```
ls -l *
``

**Comment by juliencelia** [comment]
checkpoints:
total 72
drwxr-s---. 2 bonvalej gen6129 4096 Mar  1 20:46  0
drwxr-s---. 2 bonvalej gen6129 4096 Mar  1 20:46  1
drwxr-s---. 2 bonvalej gen6129 4096 Mar  2 19:46 10
drwxr-s---. 2 bonvalej gen6129 4096 Mar  2 19:46 11
drwxr-s---. 2 bonvalej gen6129 4096 Mar  2 19:46 12
drwxr-s---. 2 bonvalej gen6129 4096 Mar  2 19:46 13
drwxr-s---. 2 bonvalej gen6129 4096 Mar  2 19:46 14
drwxr-s---. 2 bonvalej gen6129 4096 Mar  2 19:46 15
drwxr-s---. 2 bonvalej gen6129 4096 Mar  2 19:46 16
drwxr-s---. 2 bonvalej gen6129 4096 Mar  2 19:46 17
drwxr-s---. 2 bonvalej gen6129 4096 Mar  1 20:46  2
drwxr-s---. 2 bonvalej gen6129 4096 Mar  1 20:46  3
drwxr-s---. 2 bonvalej gen6129 4096 Mar  1 20:46  4
drwxr-s---. 2 bonvalej gen6129 4096 Mar  1 20:46  5
drwxr-s---. 2 bonvalej gen6129 4096 Mar  1 20:46  6
drwxr-s---. 2 bonvalej gen6129 4096 Mar  1 20:46  7
drwxr-s---. 2 bonvalej gen6129 4096 Mar  1 20:46  8
drwxr-s---. 2 bonvalej gen6129 4096 Mar  1 20:46  9

**Comment by mccoys** [comment]
I think I have found the bug, but it was resolved 25 days ago. You have to update to the github version and relaunch your simulation.

If you have updated, but your initial simulation is older, then you need to change your folder names:
`0` becomes `00`, `1` becomes `01`, `2` becomes `02`, etc.

**Comment by juliencelia** [comment]
OK. I will try that.

**Comment by mccoys** [comment]
Does it work ?

**Comment by juliencelia** [comment]
I installed Smilei for KNL and SKL 3 weeks ago. It works for KNL but not for SKL. 
But I wont work again on SKL for other reasons. 

Sure It is OK on KNL so I think it is a problem of update in my SKL env...
