### ISSUE TITLE
PostProcess in Centos

### ISSUE THREAD

**Issue by bitalm** [SmileiPIC/Smilei#22]
Dear All,

I try to open the post-process part by running:
S = happi.Open("/home/xx/yy/cc")
which /home/xx/yy/cc is the path to the h5 files. (Fields0.h5)
but seems it does not work in linux:
bash: syntax error near unexpected token `('

PS: previously I run like:
mpirun -n 4 ./smilei  my_namelist.py

ALL THE BEST

**Comment by mccoys** [comment]
Hi

You seem to have run the `happi.Open` command in your bash terminal. However, this is a python command. You first need to install the happi package using `make happi` in the original Smilei directory. This has to be done only once in your machine.

Then, open a python prompt using the `python` command, or any other python such as `ipython`. In this prompt, you have to `import happi` then you may run the command `Open` as you did above.

**Comment by mccoys** [comment]
I would like to add that the resolution to your problem is already [explicit in the documentation](http://www.maisondelasimulation.fr/smilei/post-processing.html).

If the doc is not clear for you, please explain what it lacks.

**Comment by bitalm** [comment]
Dear @mccoys ,

Thanks for your e-mail and sorry that I did not look to the documentation.
I tried to install happy, by typing make happi in the shell but I could not,
I tried to execute Diagnostics.py file as follows, but seems still error exists:
(maybe it is due to my system, I use devtoolset -3 for GCC 4.9, but python is with GCC 4.8.5)

>>> execfile("/home/amin/work/Smilei-master/scripts/Diagnostics.py")
>>> S = happi.Open("/home/amin/work/Smilei-master")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'happi' is not defined

ALL The Best

**Comment by iltommi** [comment]
You need to type ``make happi`` in the smilei follder.

```
cd  /home/work/Smilei-master
make happi
```

what the above lines return?

**Comment by iltommi** [comment]
Howeevr it seems that point 2 in https://smileipic.github.io/Smilei/installation.html#install-the-happi-module is no more valid for the latest release.

@mccoys can you confirm?

**Comment by bitalm** [comment]
Dear @iltommi @mccoys  ,

Thanks and sorry.
I used the previous version of Smilei and there was no happi folder, I compiled the new version and now I can use happi, ^_~

All The Best

**Comment by mccoys** [comment]
@iltommi the Diagnostics.py technique should still work

@bitalm indeed the module happi is new and you need the newest version of smilei :)

**Comment by iltommi** [comment]
I get this error when trying to directly import happi

```
In [1]: execfile("happi/__init__.py")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-d13963d2b9f6> in <module>()
----> 1 execfile("happi/__init__.py")

/Users/tommaso/local/src/smilei/happi/__init__.py in <module>()
----> 1 from ._core import Open
      2 from ._Utils import multiPlot, Units

ValueError: Attempted relative import in non-package
```

**Comment by mccoys** [comment]
@iltommi but this is not the right file to import. You must import `scripts/Diagnostics.py`

**Comment by bitalm** [comment]
Dear @mccoys  and  @iltommi ,

Also I think I need h5py, when I run the
 S = happi.Open("/home/work/Smilei-master/tst2d_4_laser_wake")
I receive as:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amin/work/Smilei-master_h/happi/_core.py", line 512, in Open
    return SmileiSimulation(*args, **kwargs)
  File "/home/amin/work/Smilei-master_h/happi/_core.py", line 538, in __init__
    import h5py
ImportError: No module named h5py

All The Best

**Comment by bitalm** [comment]
Dear @mccoys  and @iltommi 

I could solve the issue of h5py using anaconda python I guess,
Thanks :)
All The Best
