### ISSUE TITLE
Double counting ion density from ionization

### ISSUE THREAD

**Issue by iplasma** [SmileiPIC/Smilei#221]
Hi,

I encountered a problem with ionization that seems to be related to the time_frozen flag. When I used this flag to make sure ion pusher is off, the ion density become twice larger. 

This can be shown in the tst1d_05_tunnel_ionization test by adding time_frozen = 100000000.0 to the carbon species (I also set hydrogen number density to 0 to make the run simpler). However, electron density does not show the same problem. 

Why would this flag affect the density of the ion?  

Thanks!

**Comment by beck-llr** [comment]
Hi
This is a known bug and is already corrected in the upcoming release (should be available today or in the next couple of days). FYI, this problem only affects diagnostics and the simulation is still valid.
Thanks for reporting !

**Comment by Z10Frank** [comment]
Hello,
thank you for reporting this bug. Can you retry the simulation with frozen ions using the last version of the code?

The correction to this problem (commit 7c8c471) should have been pushed yesterday.

**Comment by iplasma** [comment]
I can confirm that the this problem is fixed in the latest version on github. Thank you very much!
