### ISSUE TITLE
wrong behavior of happi.Field with units, operation between fields

### ISSUE THREAD

**Issue by ywppku** [SmileiPIC/Smilei#222]
Dear Developers,

I am new in Smilei, and I use the python class `happi` to visualize my data.

However, when I try to check my initialization of plasmas with **units**, I find something bizarre.

The density distribution is simply:

```python
def f1(x):
    if x < L_x / 2.:
        return 1.
    else:
        return 0.

def f2(x):
    if x >= L_x / 2.:
        return .5
    else:
        return 0.
```

And when I plot their density distribution separately, i.e. `S.Field(0,'Rho_ion1',units=Units)` and `S.Field(0,'Rho_ion2',units=Units)`, everything is fine. (see the plots below)

![image](https://user-images.githubusercontent.com/37392893/75896379-4b6f0280-5e37-11ea-8bc6-4b3f0a07136a.png)

![image](https://user-images.githubusercontent.com/37392893/75896331-398d5f80-5e37-11ea-8615-b29b261d8977.png)

However, when I try to add them together by `S.Field(0,'Rho_ion1+Rho_ion2',units=Units)`, the absolute value becomes twice:

![image](https://user-images.githubusercontent.com/37392893/75897018-334bb300-5e38-11ea-98da-20fcb1b75632.png)

The Python version is `Python 2.7.16 :: Anaconda, Inc.`

Thanks in advance.
Yao

**Comment by mccoys** [comment]
This is not the correct usage of ``Units``. You need to provide some actual units, for instance ``units=["um","cm^-3"]``

**Comment by mccoys** [comment]
Nevertheless, there might be an issue that I will check.

**Comment by ywppku** [comment]
@mccoys 
When I use `S.Field(0,'Rho_ion2+Rho_ion1',units=["um","cm^-3"]).plot()`, this issue is still here:

![image](https://user-images.githubusercontent.com/37392893/75898524-7575f400-5e3a-11ea-8739-ea79f005d738.png)

Before, I use 
```
S = happi.Open('/Users/yao/Documents/mnt_hercules/Smilei/opt1d_12/',reference_angular_frequency_SI=79726367785030.64)
Units = happi.Units("um", "cm^{-3}", "ns", "V/m", "T", "um/ns","m_ec^2")
```
together with `S.Field(0,'Rho_ion2+Rho_ion1',units=Units).plot()`.
Because in this way, not only the `x` and `y` axes but also the `time` can have the units I want.

**Comment by mccoys** [comment]
Ok, I see.

Could you provide a small input file ?

**Comment by ywppku** [comment]
@mccoys  Here is the input file.

[test.py.txt](https://github.com/SmileiPIC/Smilei/files/4288371/test.py.txt)

**Comment by mccoys** [comment]
Could you try the latest push ?

**Comment by ywppku** [comment]
Yes, it's working! Thanks. @mccoys
