### ISSUE TITLE
Smilei units

### ISSUE THREAD

**Issue by Toader22** [SmileiPIC/Smilei#224]
Dear developers, 

I have some misunderstanding regarding units in SMILEI. I am trying to understand the Laser Propagation tutorial. Exactly why is l0 = 2. * pi? 
I am trying to simulate the propagation of a laser with these parameters: 
lambda0 = 800 nm
fwhm=5.6 μm
a0=100
τ=25 fs (pulse duration)
period =2.7 fs 
but I can't convert these from SI to SMILEI units.  

from math import sqrt

c = 299792458.
lambda_SI = 0.8e-6 # laser wavelength
k0_SI = 2.*pi/lambda_SI
w0_SI = c*k0_SI
one_meter = 1.*k0_SI
one_micron = 1.e-6*k0_SI
one_fs = 1.e-15*w0_SI 
t0 = lambda_SI                  
Lsim = [60.*one_micron, 75.*one_micron]  # length of the simulation
Tsim = 230.*one_fs           # duration of the simulation
resx = 16.               # nb of cells in one laser wavelength
rest = resx*sqrt(2.)/0.95 # nb of timesteps in one optical cycle 

Main(
    geometry = "2Dcartesian",
    
    interpolation_order = 2 ,
    
    cell_length = [lambda_SI/resx,lambda_SI/resx],
    grid_length  = Lsim,
    
    number_of_patches = [ 8, 8 ],
    
    timestep = 0.033*one_fs,
    simulation_time = Tsim,
     
    EM_boundary_conditions = [
        ['silver-muller'],
        ['silver-muller'],
    ],
    
    random_seed = smilei_mpi_rank
)

LaserGaussian2D(
    a0              = 100., # normalized amplitude
    omega           = 1.,
    focus           = [0, Lsim/2.], # coordinates of laser focus
    waist           = 5*lambda_SI,
    incidence_angle = 0.,
    time_envelope   = tgaussian(fwhm=5.6*one_micron, center=None)
)

DiagScalar(
    every = rest
)

DiagFields(
    every = rest,
    fields = ['Ex','Ey','Ez','Bx','By','Bz']
)

# 2-dimensional grid diagnostic
DiagProbe(
    every = 100,
    number = [100, 100], # number of points in the grid
    origin = [0., 10.*lambda_SI], # coordinates of origin point
    corners = [
        [20.*lambda_SI, 0.*lambda_SI], # coordinates of first corner of the grid
        [3.*lambda_SI , 40.*lambda_SI], # coordinates of second corner of the grid
    ],
    fields = [] 
)

DiagProbe(
    every = 10,
    origin = [0.1*Lsim, 0.5*Lsim],
    fields = []
)

I tried to write the code in SI but I can't figure it out. Can somebody please explain in more detail? Thank you!

**Comment by beck-llr** [comment]
Hi Toader.
You are correct that units must be converted from SI to SMILEI (normalized) units. In order to do that you must divide any quantity by a reference quantity. For instance, in order to normalize a length expressed in S.I, (like your `cell_length`) you must divide it by the reference length also expressed in S.I.

If you refer to https://smileipic.github.io/Smilei/units.html, you'll see that the reference length is `c/w_r`. You can pick any `w_r` you like but usually `w_r` is chosen as the laser frequency. Of course, you must pick the same `w_r` for all normalizations of a given simulation (time, number density, ...)

I hope this helps.

**Comment by Toader22** [comment]
Thank you for your answer!
So, any length L=c/w0 with w0 being the laser angular frequency 
that means L = c/(2pi*f) = lambda0/2pi? Is this correct?  
So if I want to simulate the laser propagation in vacuum I need to define the units like this? But in the tutorial there was no reference length defined, just the wavelength. 

lambda_0=800*10e-9
w_0=2*math.pi*c/lambda_laser
Lr=c/w_laser
Tr=1/w_laser

Can you please show me how to transform those 800nm to Smilei units? Sorry again for the silly question.

**Comment by beck-llr** [comment]
Once your `w_r` is defined all other reference quantities are defined. So any length `L` is normalized by the length `Lr` that you have correctly defined. This means you have the following relation for any length `L`:
```
L[normalized] = L/Lr
```
So if I want to normalize lambda_0:
```
lambda_0[normalized] = lambda_0 / Lr
```
But as you noticed, `Lr = c/w_laser = lambda_0/2Pi`.
This gives you `lambda_0[normalized] = 2Pi`.

**Comment by mccoys** [comment]
@Toader22 please read carefully the Units documentation. This should be all explained.

**Comment by Toader22** [comment]
Thank you for all the support :)
