### ISSUE TITLE
Probe Rho_abc doesn't work in AM geometry

### ISSUE THREAD

**Issue by bjjjjjjjj** [SmileiPIC/Smilei#226]
Firstly, I would like to thank Smilei developers for creating such a powerful tool for scientists.

When trying to make a probe diagnostic with Rho_abc as a field (density for my "abc" species) in AM geometry, I get the following error:

`> [ERROR](0) src/Diagnostic/DiagnosticProbes.cpp:275 (DiagnosticProbes) Probe #0: unknown field Rho_abc`

In 1D, 2D and 3D everything works fine. Choosing "Rho" as a field in AM geometry works well, but it doesn't allow to study species' dynamics separately (e.g., electrons & ions). This restriction is not explicitly stated in docs. Could it be implemented? Or, maybe, there exists a solution?

Field diagnostics in AM support "Rho_abc". However, as soon as subgrids in AM geometry are also not supported, there is currently no way to store time-resolved density evolution in less-than-100+Gb files for my grid setup.

**Comment by beck-llr** [comment]
Hi
I believe a workaround to that problem is to ask for `Rho_abc_mode_0` and `Rho_abc_mode_1`. This is temporary and should be improved of course.

**Comment by bjjjjjjjj** [comment]
It indeed works. Just to clarify: is the real density simply equals `Rho_abc = Rho_abc_mode_0 + Rho_abc_mode_1` in the default laser polarization plane (_z_ = 0 cut of the 3D grid)?

**Comment by mccoys** [comment]
@bjjjjjjjj In the latest release (4.4), the probe now works differently : you should simply use `Rho_abc`
