### ISSUE TITLE
Probe bug in AM geometry

### ISSUE THREAD

**Issue by bjjjjjjjj** [SmileiPIC/Smilei#227]
I run a simple simulation of laser propagation in vacuum in AM geometry and try make a probe of the electric field in the transverse plane. The code executes normally.
The resulting array at a fixed time should have length 300x300 = 90000. But, instead, it has a length of 36272.
Trying to animate this diagnostic with happi results in a wrong map.
Namelist and all output data are attached.

[AM_probe_bug.zip](https://github.com/SmileiPIC/Smilei/files/4349646/AM_probe_bug.zip)

**Comment by mccoys** [comment]
I will try to fix the bug.

In the meantime, you can reverse the ordering of the two `corners`. It should  work.

**Comment by bjjjjjjjj** [comment]
It worked, thank you.

**Comment by mccoys** [comment]
@bjjjjjjjj This should be fixed now
