### ISSUE TITLE
Most suitable OpenMPI + HDF5 versions ?

### ISSUE THREAD

**Issue by lesnat** [SmileiPIC/Smilei#229]
Hi everyone !
I hope you and your families are fine in these days.

I am personally working at home, and then trying to install Smilei on my own computer. I actually post this issue since I often face the same question when I need to install Smilei's dependencies:

**What are the most suitable versions of OpenMPI and HDF5 to use with the Smilei's current version ?**

The documentation linked to the OpenMPI and HDF5 download web pages, but doesn't give any information about a specific version to use.

Especially, on the HDF5 website, it is written today

> Applications that were created with earlier HDF5 releases may not compile with 1.12 by default.

and then I don't know if Smilei actually fit in this condition or not.

On the `Install` page of the Smilei's doc, it is also recommended to use

> an MPI library (by default a version supporting MPI_THREAD_MULTIPLE is required: v4.0 or newer recommended)
> 
> an HDF5 library compatible with your versions of C++ and MPI

but I don't know if MPI v4.0 or newer means OpenMPI v4.0, or if the MPI protocol versions and its OpenMPI implementation versions are labelled differently (and what about IntelMPI versions ?).

It's however possible to find the supported version of MPI implementations by a specific HDF5 release in its release documentation, but it wasn't very clear to me where to search for this information. I can propose you a change in the documentation:

> an HDF5 library compatible with your versions of C++ and MPI (supported versions can be found on the HDF5 release documentation)

Maybe it could also be possible to add a line in the documentation to specify what has been tested ? Such as
> Tested on Ubuntu xx.xx with OpenMPI version x.xx.xx and HDF5 version x.xx.xx

BTW I also have troubles with my hdf5 installation, but I'll first wait your answer on specific versions before sending you the eventual error messages I could have.

Thank's a lot,
Cheers,
Léo.

**Comment by mccoys** [comment]
C++11
MPI v4+
OpenMPI v2+, although there are some tweaks for v2 I believe
HDF5 1.8+. I am not sure about 1.12 (probably nobody tried yet). I suggest 1.10.*

It is hard for us to test many versions. Things evolve fast and we just don't have the manpower. We could simply report our system parameters somewhere, but the list would be very long and I am not sure if we can maintain it.

**Comment by lesnat** [comment]
Ok thank you !

I just solved my problem so I post the solution here.

I compiled OpenMPI v2.1.6 with no problem, but when I launched the `sudo make install` command for HDF5 v1.8.21 I got the following error

> /opt/hdf5-1.8.21/libtool: line 10545: mpicc: command not found
> libtool:   error: error: relink 'libhdf5_hl.la' with the above command before installing it

The solution is given [at this adress](https://forum.hdfgroup.org/t/command-not-found-mpiicc/6647/2), and my compilation problem was because the PATH environment variable was updated for the user, so but not for super-user.

One solution is to use the command `sudo env “PATH=$PATH” make install` instead of `sudo make install` in the hdf5 folder (after `configure` and `make` commands).

With this command HDF5 compiled properly and the Smilei installation also.

Thank's again,
Léo.

**Comment by mccoys** [comment]
Thank you for the tip.

Note that there is another way, which is done by default in some linux distributions. It is somewhat nicer because it keeps the whole environment of the user when doing sudo.
```bash
sudo visudo
```
Then you are able to edit the sudoers file. Just add the following line after the few first `Default` lines:
```bash
Defaults        exempt_group="yourlogin"
```
Replace `yourlogin` by your login of course.
