### ISSUE TITLE
Issue with QED benchmark namelists

### ISSUE THREAD

**Issue by ujjwalsinhaist** [SmileiPIC/Smilei#23]
Hi All,
I am trying to run the namelists 
tst1d_10_pair_electron_laser_collision.py
and
tst2d_10_multiphoton_Breit_Wheeler.py
using smilei-v3.3 (with QED module). 
I am getting the following errors,

 Initializing radiation reaction
 --------------------------------------------------------------------------------
         The Monte-Carlo Compton radiation module is requested by some species.

         Factor classical raidated power: 2.0051e+03
         Threshold on the quantum parameter for radiation: 1.0000e-03
         Threshold on the quantum parameter for discontinuous radiation: 1.0000e-02
         Table path: ./
 
         --- Integration F/chipa table:
             MPI repartition:
             Rank: 0 imin: 0 length: 32
             Rank: 1 imin: 32 length: 32
             Rank: 2 imin: 64 length: 32
             Rank: 3 imin: 96 length: 32
             Computation:
	[ERROR](0) src/Tools/userFunctions.cpp:148 (modified_bessel_IK) x too large in modified_bessel_IK; try asymptotic expansion
	[ERROR](0) src/Tools/userFunctions.cpp:148 (modified_bessel_IK) x too large in modified_bessel_IK; try asymptotic expansion
	[ERROR](0) src/Tools/userFunctions.cpp:148 (modified_bessel_IK) x too large in modified_bessel_IK; try asymptotic expansion
	[ERROR](0) src/Tools/userFunctions.cpp:148 (modified_bessel_IK) x too large in modified_bessel_IK; try asymptotic expansion
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[33710,1],0]
  Exit code:    1

Please help!

**Comment by mccoys** [comment]
Hello,

If you found a solution to this problem, could you share it for others? We haven't had time to review it yet.

Cheers

**Comment by ujjwalsinhaist** [comment]
Hi Mccoys,

I have not been able to find the solution. I rephrased the problem properly in another issue with title "Problem running radiation reaction module on more than one cores"

Best,
