### ISSUE TITLE
numpy error on Simlei initialisation 

### ISSUE THREAD

**Issue by GeorgeHicks1** [SmileiPIC/Smilei#230]
Hi,

I have recently encountered a problem when my simulation initialises. The specific error message is
`ImportError: numpy.core.multiarray failed to import`. Has anyone seen this error message before?

I have included my namelist, submission script, log and full error message below.

Kind regards,
George

[namelist.txt](https://github.com/SmileiPIC/Smilei/files/4382189/namelist.txt)
[pbsplasma.txt](https://github.com/SmileiPIC/Smilei/files/4382130/pbsplasma.txt)
[log.txt](https://github.com/SmileiPIC/Smilei/files/4382158/log.txt)
[ELI_a03_01H_lin_r2.txt](https://github.com/SmileiPIC/Smilei/files/4382169/ELI_a03_01H_lin_r2.txt)

**Comment by mccoys** [comment]
Hi

This is probably not due to Smilei. You have a faulty numpy installation, or something is missing in your python environment to support numpy. I suggest you directly run a python command (not running Smilei) that imports numpy. If this fails, then you must contact your sysadmin.

**Comment by beck-llr** [comment]
Hi George
I am no expert but this looks like an error from your system. A quick search in google pointed that way
https://github.com/tensorflow/tensorflow/issues/559

Hope this helps

**Comment by GeorgeHicks1** [comment]
Hi both,

Thanks for the quick responses. I have contacted my sysadmin, but they're understandably pretty swamped at the moment.

I'll post back here when I find the solution.

**Comment by GeorgeHicks1** [comment]
Hi,

I found the problem was with a specific queue on my university's computing system. Running it on a different queue solved the problem. Sorry for bothering you!

Thanks,
George
