### ISSUE TITLE
Simulation crash in AMcylindrical without error message

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#234]
Hi Smilei Team,

Hope that all oy you are fine!

I try to run this simulation for few days ago. It always craches at 2000 timesteps without error message in log. And in err file, it is not clear for me.

[CH2daxi.txt](https://github.com/SmileiPIC/Smilei/files/4422713/CH2daxi.txt)
[out.txt](https://github.com/SmileiPIC/Smilei/files/4422714/out.txt)
[err.txt](https://github.com/SmileiPIC/Smilei/files/4422717/err.txt)

Thanks 

Julien

**Comment by mccoys** [comment]
Maybe you went passed the maximum time allowed for your job ?

**Comment by juliencelia** [comment]
I am ashamed..... I forgot one zero.
Thanks @mccoys
