### ISSUE TITLE
Ukin_bnd decreases in time

### ISSUE THREAD

**Issue by Iuliana19** [SmileiPIC/Smilei#235]
Dear Smilei team,

I observed that the Ukin_bnd decreases for a thick target (50mu) and this makes the total energy in the system to decrease.

I attached the graph obtained and the script for them. And also my input file. Could you have a look at them please and tell me if there is something wrong in the simulation setup which makes the Ukin_bnd to decrease? 

Smilei version: v4.3-117-gf922f56-master

Thank you!
Iuliana

[AbsorptionComponents.pdf](https://github.com/SmileiPIC/Smilei/files/4425977/AbsorptionComponents.pdf)
[AbsorptionModel.txt](https://github.com/SmileiPIC/Smilei/files/4425978/AbsorptionModel.txt)
[AbsorptionTransmissionReflection.pdf](https://github.com/SmileiPIC/Smilei/files/4425979/AbsorptionTransmissionReflection.pdf)
[laserplasmacase1050.txt](https://github.com/SmileiPIC/Smilei/files/4425980/laserplasmacase1050.txt)

**Comment by mccoys** [comment]
Thank you for reporting this bug. Is it possible for you to produce a smaller case which gives the bug ? This one is too large for debugging.

**Comment by mccoys** [comment]
Nevermind, I got something fast enough.

**Comment by mccoys** [comment]
I pushed a fix: there was some mishandling of `Ukin_bnd` during load balancing. Sorry for the inconvenience.

**Comment by Iuliana19** [comment]
Thank you very much!
