### ISSUE TITLE
External fields time profile

### ISSUE THREAD

**Issue by czajah** [SmileiPIC/Smilei#236]
Hi,

Is there a way to turn a field on and off during simulation?

**Comment by MickaelGrech** [comment]
You're lucky, we have just released v4.4 where the user can now define some prescribed fields.
Here is the [corresponding doc](https://smileipic.github.io/Smilei/namelist.html#prescribed-fields).
Note that these fields are not considered by the Maxwell solver, but only to push particles (they appear in the Fields or Probe diagnostics though).

**Comment by czajah** [comment]
Thank You :) It should do for what I need

**Comment by mccoys** [comment]
Please note that we have made an important fix to this feature in v4.5. A bug was present in some cases with OpenMP.
