### ISSUE TITLE
Incorrect scalar Urad with moving window

### ISSUE THREAD

**Issue by xsgeng** [SmileiPIC/Smilei#240]
Dear developers,

Urad of a species should be monotonic when the particles radiate. But Urad decreases when the window starts moving, which is abnormal for an accumulated value. It seems to be a bug relevant to the MPI messaging of this scalar.

Best Regards,
xsgeng

**Comment by mccoys** [comment]
Indeed, the radiated energy is stored in each patch, and is destroyed when a patch is moved out of the box. This explains the observed behaviour, and we should find a solution soon.

**Comment by mccoys** [comment]
Today's tag should fix this issue. Please tell us if it works for you.
