### ISSUE TITLE
Get axis names from Particle Binning diagnostic

### ISSUE THREAD

**Issue by GeorgeHicks1** [SmileiPIC/Smilei#243]
Hi,

I would like to retrieve the name of the axes of a ParticleBinning diagnostic using happi. I then pass the axis name to getaxis() to retrieve the axis limits. I have found a way to do this that is quite slow (~10s):

`list(S.ParticleBinning(0).get().keys())[-2:]`

Is there a faster way to do this I am not aware of?

Also, is there a way to retrieve the deposited quantity from a ParticleBinning diagnostic, e.g. weight/weight_ekin etc.

Kind regards,
George

**Comment by mccoys** [comment]
```python
S.ParticleBinning(0)._type
```

It is also possible to extract it from the namelist:
```python
S.namelist.DiagParticleBinning[0].axes
```

I will create a dedicated function if more people require it.

**Comment by GeorgeHicks1** [comment]
Hi,

Thank you, that's exactly what I needed.

Kind refards,
George
