### ISSUE TITLE
RadiationSpectrum diagnostics doesn't accept python functions as axes

### ISSUE THREAD

**Issue by humanoid-v1911** [SmileiPIC/Smilei#248]
I was trying to create a angularly-resolved radiation spectrum of created radiation with the help of the RadiationSpectrum diagnostics as described in the SMILEI documentation (with a few modifications as to when to take samples and how to average):

the code from the documentation itself showed the same behaviour/error:

from numpy import arctan2, pi

def angle(p):
    return arctan2(p.py,p.px)

DiagRadiationSpectrum(
    every = 10,
    species = ["electrons"],
    photon_energy_axis = [0., 1000., 100, 'logscale'],
    axes = [
        [angle,-pi,pi,90]
    ]
)

But when running the simulation Smilei stopped when parsing this diagnostic. The error message then tells me, that the RadiationSpectrum diagnostics need an axis of the string type "axis". Using the standard "axis" string ("x", "y", etc.) works fine but doesn't help me get the angularly-resolved spectrum. I don't really know how else I could get this spectrum nor how to fix the issue since this is a suggested piece of code in the SMILEI documentation.

## Parameters

- Smilei version: v-80bffabc
- submitted with qsub
- Computing resources
  - SuperComputer/Cluster running on 256 cores
  - C++ compiler: g++ 4.8.5 20150623 (Red Hat 4.8.5-39)
  - MPI version: g++ 6.2.0
  - HDF5 version 1.8.21
  - Python version: 3.7.2

**Comment by MickaelGrech** [comment]
Ciao! now this is weird! can you send us an input file that creates the pb for you?

**Comment by mccoys** [comment]
Two things: first, you will not be able to obtain an angularly resolved spectrum for the photons, as your axis acts on emitting particles. Second, I have made changes that will be available soon, and I expect this will solve your problem. Please wait for the next version in the coming week.

**Comment by mccoys** [comment]
Nevermind my first comment above. If you assume photons are emitted on the same direction as electrons, then this is fine.

**Comment by humanoid-v1911** [comment]
So I've attached the current namelist that I'm running (had to convert to .txt to upload it). And yes I expect the radiation to be emitted in the electrons direction, still this doesn't change the problem in itself.
When will the next version be available? Got a bit pressure of time.
[LaserChannel Kopie.txt](https://github.com/SmileiPIC/Smilei/files/4584055/LaserChannel.Kopie.txt)

**Comment by mccoys** [comment]
There are a number of small errors in your file: `every` and `time_average` should be integers (numbers of timesteps), not floats. However, this is unrelated to the error you obtained. I can confirm this works in our next version expected in a few days.

**Comment by mccoys** [comment]
@humanoid-v1911 Actually, maybe your error is due to the absence of numpy in your python. This would be worth checking.

**Comment by MickaelGrech** [comment]
@humanoid-v1911 @mccoys there is actually a call to numpy right before the arctan2 is called.
The problem comes from the way arctan2 is called, which is incorrect in your input file. 
Numpy arctan2 takes 2 arguments not a single one in the form of a fraction.

You should rather use:
```python
from numpy import arctan2
def angle(p):
    return np.arctan2(p.py,p.px)
```
Also take care to call the function angle, and not the string "angle":
```python
#Angle-resolved total spectrum
DiagRadiationSpectrum(
                   every = 500,
                   species = ["electron"],
                   photon_energy_axis = [0., 1000., 100, 'logscale'],
                   axes = [[angle,-np.pi,np.pi,45]]
)
```
I could run your input file with this modification.

**Comment by mccoys** [comment]
I checked with @MickaelGrech 's changes in v4.5 (released today), and it works,

**Comment by humanoid-v1911** [comment]
@MickaelGrech it is highly possible that there are some errors in the diagnostic block in that namelist, since I was already plaing around with it due to the one suggested in the documentation (as written in the original post) didn't work. I will try your version and update my SMILEI install to v4.5 once my current simulations are done.
@mccoys I manually checked for this before, but numpy was available.

Already thanks for your help.

**Comment by humanoid-v1911** [comment]
I was trying to compile the new release v4.5. but have run into the same issue over and over, thus was unable to yet resolve the problem. 
I get an error message as follows:

`>Checking dependencies for src/Checkpoint/Checkpoint.cpp
>  File "scripts/compile_tools/check_make_options.py", line 11
>   print option, "do not exist for", keyword
>               ^
>SyntaxError: Missing parentheses in call to 'print'. Did you mean print(option, "do not exist for", >keyword)?
>make: *** [check] Fehler 1`

The changes suggested by @MickaelGrech alone didn't resolve the issue.

**Comment by iltommi** [comment]
Could you try again? 17ed572 should fit this

**Comment by humanoid-v1911** [comment]
@iltommi see my edit of the above comment.

**Comment by ywppku** [comment]
I met with the same error when first try v4.5.
And it appears to be a small print issue of python2 -> python3.

I made it work by just adding parentheses at the place indicated by the error message, namely,

    print(option, "do not exist for", keyword)

Please try if this fix your problem.

Yao
