### ISSUE TITLE
Labels for diagnostics

### ISSUE THREAD

**Issue by vasimos** [SmileiPIC/Smilei#249]
Hello! It would be handy to add an optional label argument for the diagnostics so that one could refer to each diagnostic by a user-defined label when post-processing. The reason that this would be useful is that numbering for diagnostics can change when diagnostics are added or removed, requiring one to update the corresponding post-processing scripts. Moreover, it would make it easier for diagnostic scripts to work across different simulations.

**Comment by GeorgeHicks1** [comment]
Hi vasimos,

One option you have for making post-processing easier is extracting the axes, species and deposited quantity from a diagnostic.

I personally use:
`''.join(S.namelist.DiagParticleBinning[i].species)+ ' '+''.join(S.ParticleBinning(i)._type) + ' ' + S.namelist.DiagParticleBinning[i].deposited_quantity` where i is an iterable. This gives, for example `'electron xy weight'`.

**Comment by mccoys** [comment]
Note that the requested feature has been implemented but is not available yet. Will keep you posted.

**Comment by mccoys** [comment]
Actually, I forgot to mention that this feature is implemented and available. Please test it when possible
