### ISSUE TITLE
Problem with space_time_profile for a user-defined laser beam

### ISSUE THREAD

**Issue by lucafedeli88** [SmileiPIC/Smilei#25]
Hello everyone.

I'm experiencing some issues with the initialization of a generic laser beam with
a space_time_profile function.

The simplest case which reproduces the issue is the following.

I took the example "tst1d_0_em_propagation.py" (which runs smoothly) 
and I replaced the laser definition with these lines:

```

def zero(t):
    return 0.0
def f(t):
    return math.cos(t)

Laser(
     space_time_profile = [  zero,  f ],
)

```
The output shows that the Laser definition has been parsed correctly

> 
> 	[WARNING] Laser #0: space-time profile defined, dismissing time_envelope space_envelope omega chirp_profile phase 
>  		Laser #0: space-time profile
> 			first  axis : 1D user-defined function
> 			second axis : 1D user-defined function

And the code runs for all the timesteps

> 
>   timestep       sim time   cpu time [s]   (    diff [s] )
>     51/408     3.1724e+00     1.2952e+00   (  1.2952e+00 )
>    102/408     6.3140e+00     2.6316e+00   (  1.3364e+00 )
>    153/408     9.4556e+00     3.9847e+00   (  1.3531e+00 )
>    204/408     1.2597e+01     5.5216e+00   (  1.5369e+00 )
>    255/408     1.5739e+01     7.3499e+00   (  1.8283e+00 )
>    306/408     1.8880e+01     9.1586e+00   (  1.8087e+00 )
>    357/408     2.2022e+01     1.0807e+01   (  1.6482e+00 )
>    408/408     2.5164e+01     1.2235e+01   (  1.4280e+00 )

However, the execution ends with an error:

> 	 Printed times are averaged per MPI process
>  		 See advanced metrics in profil.txt
> [debian:18154] *** Process received signal ***
> [debian:18154] Signal: Segmentation fault (11)
> [debian:18154] Signal code: Address not mapped (1)
> [debian:18154] Failing at address: 0x21
> Segmentation fault

And the fields in the output are zero.

Am I doing something wrong? 
I would be glad if you could help me with this issue.

Best regards

Luca

**Comment by mccoys** [comment]
Hi

I just found out we haven't done it in 1D yet !

Let me add it very soon.

**Comment by mccoys** [comment]
As soon as the pull request #26 is merged, you should be able to run a 1D, custom laser profile.

**Comment by lucafedeli88** [comment]
Thanks for the prompt reply! 
Now it works nicely.
