### ISSUE TITLE
Number of cells different in PIC box and Field diag?

### ISSUE THREAD

**Issue by phkorneev** [SmileiPIC/Smilei#250]
Hi Smileiers,
a simple question: I set up 3D cartesian PIC, I have 

> 	 dimension 0 - (Spatial resolution, Grid length) : (0.015915, 24127.431580)
> 	             - (Number of cells,    Cell length)  : (384, 62.831853)

in the log. For the Field diags I don't set any restrictions, waiting for the whole grid in the output. But I get in dimension "0" 385 cells. How can this be? What I am doing wrong?
Best
ph

**Comment by MickaelGrech** [comment]
Hi Philipp,

There's nothing wrong here.
Fields are defined on the nodes of the cells, hence if you have N cells in a given direction, you have N+1 nodes.

Just a quick note: In principle, this is true for fields that are defined on the primal grid (e.g. like Ey, Ez and Bx in the x-direction). But for diagnostic purposes, we always take N+1 points for all fields, whether they are defined on the primal or dual grid.

**Comment by phkorneev** [comment]
Hi  Mickael, thanks! It was my bug. Of course I always added this "+1" to the number of cells which I obtain from the PIC grid, and it was everything OK before with my script. This happened because all this time I used int() to get the integer this number from the namelist instead of round() in Python - when I changed resolution it failed. Sorry for this.
Best
Ph
