### ISSUE TITLE
Calculate fields from DiagTrackParticles data

### ISSUE THREAD

**Issue by czajah** [SmileiPIC/Smilei#251]
Hi,

I have positions of particles and I want to calculate electric field in arbitrary positions comming from those particles. Is there any tool for that or what will be the simplest way to do that?

**Comment by mccoys** [comment]
The tracking diagnostic does have the option to save fields at particles positions. Check the doc

**Comment by czajah** [comment]
@mccoys I want to be able to calculate electric field at any given position (unspecified at simulation start) having particles positions and knowing theirs weight and charge

**Comment by MickaelGrech** [comment]
@czajah what you want to do is not straightforward and would in general require you know the full trajectory of the particle and that you reconstruct the field from, e.g. retarded potentials. In the electrostatic limit, you could also just compute the electrostatic field by the particle. In any case, this is not included in Smilei and you'll have to recompute the fields yourself.
