### ISSUE TITLE
Error in External field profile 

### ISSUE THREAD

**Issue by flavorenti** [SmileiPIC/Smilei#254]
## Description

Hello, I'm having a problem with a peculiar initialization of the external field "Bz".
So far I've always used an analytical function for the external magnetic field, the problem is that now I want to use a numerical array for Bz.

In particular I have a numpy array "A_array" defined on the x-grid which then I interpolate in order to get a function A(x) to use in Bz(x).
Here you can see an extract of the namelist which explains the procedure (x_array and A_array are numpy arrays computed in the namelist):

```
A = interpolate.interp1d(x_array, A_array)
```

```
def Bz(x,y):
                A1 = float(A(x/m.sqrt(mime)))
                return B0*np.sqrt( 2*( PBC - n(A1)*T ) )
```

So the **problem** when running is the following, and the code starts hanging afterwards:
```
>  Applying external fields at time t = 0
 --------------------------------------------------------------------------------
        [ERROR](0) src/Tools/PyTools.cpp:94 (get_py_result) Function does not return a valid Python object
        [ERROR](0) src/Tools/PyTools.cpp:94 (get_py_result) Function does not return a valid Python object
        [ERROR](0) src/Tools/PyTools.cpp:94 (get_py_result) Function does not return a valid Python object



 Applying prescribed fields at time t = 0
 --------------------------------------------------------------------------------
        [ERROR](0) src/Tools/PyTools.cpp:94 (get_py_result) Function does not return a valid Python object
        [ERROR](0) src/Tools/PyTools.cpp:94 (get_py_result) Function does not return a valid Python object

```

## Parameters
- Smilei version - the latest
- Input file - LHDI_simu2D.txt namelist attached
[LHDI_simu2D.txt](https://github.com/SmileiPIC/Smilei/files/4632161/LHDI_simu2D.txt)
- Output file - RUN.txt attached
[RUN.txt](https://github.com/SmileiPIC/Smilei/files/4632166/RUN.txt)
- Computing resources - OCCIGEN standard installation

**Comment by flavorenti** [comment]
I've tried to look into src/Tools/PyTools line 94 but it is not so clear what is the issue with Bz (at least for me). I hope it will make some more sense to you, let me know and thanks in advance!

Federico Lavorenti

**Comment by mccoys** [comment]
Try to print the output of your function to see what is going on. For example, you interpolation might be returning NaNs at some points (at the borders?) which are not accepted. You could try extrapolation as well

**Comment by mccoys** [comment]
Ah, and the float function could be an issue as it converts an array to a float.

**Comment by flavorenti** [comment]
Alright, thanks. I changed the interpolation function to scipy.interp (which takes values also outside of the given interval) and it works.
Thanks
