### ISSUE TITLE
static electric field applications

### ISSUE THREAD

**Issue by ZippoFight** [SmileiPIC/Smilei#255]
Can Smilei be used to run simulations for applications with static electric field? For example, a discharge plasma between two parallel metal planes, with a high voltage applied across the gap?

**Comment by mccoys** [comment]
Smilei has the capability to add prescribed fields, but it is still an electromagnetic solver. If you need an electrostatic solver then it is not adequate. If you only need to calculate particle trajectories, you could simply deactivate the solver, but it would be strange to use such a code for this purpose.

**Comment by ZippoFight** [comment]
can I add an external electric field, which may be spatially non-uniform and time-dependent, to the resulting electromagnetic field in each step, and then use the total field to push the particles to their new positions? 
if this is possible, I can calculate this external electrostatic field by other code and introduce it into Smilei.

**Comment by mccoys** [comment]
Yes it is possible: it is called prescribed fields in Smilei. They are added to the particle pusher, but do not participate in the Maxwell solver. Now, solving the electromagnetic equations is not often necessary for discharges (and it is very costly). Usually, only electrostatics are solved. Be aware of this.

**Comment by ZippoFight** [comment]
Thank you. I now solving electromagnetic equations is costly, but I am looking for a code that is capable of simulating discharge with a large domain, for example 1 mm * 1 mm with a grid size of 10nm, and I found Smilei has been optimized to run on latest HPC, so I want to try to use this.
Do you know any other code that is open source and solving electrostatic equations?

**Comment by MickaelGrech** [comment]
You can check a previous discussion [issue #171](https://github.com/SmileiPIC/Smilei/issues/171).
A list of codes was discussed in the last posts.

For your simulation, if you don't need to treat electromagnetic phenomena, having such a high-resolution with such a large box will be problematic to treat with an electromagnetic solver due to the CFL condition that will require you to use extremely small time steps.
