### ISSUE TITLE
Collect particles in a certain region to plot the energy spectrum using ParticleBinning()

### ISSUE THREAD

**Issue by ywppku** [SmileiPIC/Smilei#256]
Dear Smilei Developers and Users,

I want to plot the energy spectrum of particles **in a certain region**.
Is there a smart way to do so using `ParticleBinning()`?

Usually, I use the following code snippet to plot the energy spectrum of **all the particles**.

```python
DiagParticleBinning(
    deposited_quantity = "weight",
    every = diag_every,
    time_average = 1,
    species = ["ion2"],
    axes = [["ekin",   ene_min,  ene_max,   1200 ] ]
)
```

And when I check the documents, there's a `sum={'x':[start, end]}` property in `ParticleBinning()`.

1. Maybe I can take advantage of this property?
2. But that means I have to add an `'x'` axes in the above snippet and re-run all of my simulations?
3. Or actually there're more elegant way to do so using other functions?

Thanks for your help.
Best regards,
Yao

**Comment by MickaelGrech** [comment]
Hi Yao!
Indeed, adding a spatial axis ``'x'`` (maybe also ``'y'``or ``'z'``depending on your geometry) will do it. You can define the axis ``['x',xmin,xmax,nbin]`` either (i) directly chosing ``xmin`` and ``xmax`` for the region you want to select (in that case you can also use ``nbin=1``); or (ii) you can define a larger ``xmin`` and ``xmax`` and then use the ``sum={'x':[start, end]`` tool in Happi.
Unfortunately, this will most likely require you re-run your simulation. If the only thing you have now is the diagnostic ``ParticleBinning()`` as you give in your issue, it is constructed by summing the contribution (here ``weight``) of each particle, whereever it is in the simulation. So the information on the particles' location is lost in this diagnostic, and I see no way to retrieve it.

**Comment by ywppku** [comment]
Dear @MickaelGrech 

Thanks for your timely reply.
I have a clear answer for my questions now.

I will close this issue then.
