### ISSUE TITLE
Transparent kwarg in field diagnostic

### ISSUE THREAD

**Issue by humanoid-v1911** [SmileiPIC/Smilei#257]
So in the documentation the kwarg "transparent" for field diagnsotics is introduced with the options "over", "under" and "both", which then require additional numerical values to make the colormap of the field tranparent in the such described intervall. 

The problem is, that from the documentation itself, it is unclear how to actually use thise kwarg. Could somebody explain how it works? 

Otherwise I'll have to extract the raw data and work with that, which would be a bit inconvinient.

**Comment by mccoys** [comment]
Indeed, the documentation is scarce:

> transparent: None (by default), "over", "under" or "both" makes the colormap transparent outside the requested boundary.

The "boundary" is chosen with the arguments `vmin` and `vmax` which are the data limits. The transparency is active *outside* this interval when `transparent="both"`.

**Comment by mccoys** [comment]
@humanoid-v1911 Is it clearer with this sentence ?

> ``transparent``: ``None`` (by default), ``"over"``, ``"under"`` or ``"both"``.
  The colormap becomes transparent *over*, *under*, or *outside both* the boundaries
  set by ``vmin`` and ``vmax``.

I can change the doc if yes

**Comment by humanoid-v1911** [comment]
@mccoys yes this was very helpful.
