### ISSUE TITLE
The units of momentum in TrackParticle diagnostic

### ISSUE THREAD

**Issue by ywppku** [SmileiPIC/Smilei#260]
Dear Developers,

I am not clear about the units of momentum (i.e. px of the proton) I get from TraceParticle diagnosis.
I've looked for this in the documentation and former issues, and I found some discussions about it.
But it's not clear to me what exactly the latest version uses.

Thanks for your help!
Best,
Yao

**Comment by mccoys** [comment]
Hello
The documentation explains the units : http://www.maisondelasimulation.fr/smilei/units.html
For momentum, it is `me c`.

A few months ago, there was a bug in this diagnostic, and the mass of the particle was not correctly multiplied, but it is fixed now.

**Comment by ywppku** [comment]
How about the filter for the TrackParticle diagnostic in the namelist?

For example, I have a filter like this for protons, by which I want to track those with energy higher than 0.1 MeV.

```
E0 = 0.1 # energy in MeV
def my_filter(particles):
    return (np.sqrt(particles.px**2 + particles.py**2 + particles.pz**2) > np.sqrt(E0/911.))
```

I found in the results that the lower limit of the trace particle energy is actually around 0.05 MeV.

What is the more elegant way to do so?

Many thanks!
Yao

**Comment by mccoys** [comment]
Indeed something is missing in the documentation. The `particles.px` quantity in the filter is actually reaching the true quantity inside the code, which is not momentum, but the velocity (in units of c) multiplied by the lorentz factor. In order to obtain the momentum (in units of me*c), you must multiply by the mass of the particle (in units of the electron mass).

**Comment by ywppku** [comment]
Thanks for the clarification. 
It makes sense, I should think of this.
Maybe more physical examples in the filter of TrackParticle diagnostic will be of great help.

Thanks again and I will close the issue.
