### ISSUE TITLE
Fatal error in MPI_Recv: Invalid rank - IJC skylake

### ISSUE THREAD

**Issue by kevinCassou** [SmileiPIC/Smilei#261]
## Description

running version 4.4 and 4.5 of smilei on Irene Joliot curie skylake with AM and ionization give the following error 

```
Fatal error in MPI_Recv: Invalid rank, error stack:
MPI_Recv(224): MPI_Recv(buf=0x94c4cb0, count=1, MPI_INT, src=40, tag=253953, MPI_COMM_WORLD, status=0x7ffc9dd7422c) failed
MPI_Recv(123): Invalid rank has value 40 but must be nonnegative and less than 40
In: PMI_Abort(805956358, Fatal error in MPI_Recv: Invalid rank, error stack:
MPI_Recv(224): MPI_Recv(buf=0x94c4cb0, count=1, MPI_INT, src=40, tag=253953, MPI_COMM_WORLD, status=0x7ffc9dd7422c) failed
MPI_Recv(123): Invalid rank has value 40 but must be nonnegative and less than 40)
```
the error appears always at the same timesteps 10200
## Steps to reproduce the problem

Changing in the submission script `runSmilei-lpi-ii-case0.sh`  

```#MSUB -n 40```
to 
```#MSUB -n 32```

makes the error disappear.

## Parameters

- Smilei version : 4.4 and 4.5 
- Input file attach to the issue or look to the following directory on irene : 
`/ccc/scratch/cont003/smilei/cassouke/lpi-ii-test0`
4 directories with different version of  Smilei et `-n 32` or `-n 40`

[test0-am-ii-msubn40.zip](https://github.com/SmileiPIC/Smilei/files/4728125/test0-am-ii-msubn40.zip
 
- Computing resources
  - type of computer
  - OS: linux / TGCC irene Joliot Curie skylake
  - C++ compiler : g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

**Comment by jderouillat** [comment]
Hi,
It seems to an error that we reproduce with OpenMPI which is not the library recommended on Irene (because it do not support `MPI_THREAD_MULTIPLE`).  
2 solutions, go to IntelMPI (which supports `MPI_THREAD_MULTIPLE`) or compile with `config=no_mpi_tm`.

To access to the recommended environment, follow instructions given by `make help machine=joliot_curie_skl : 
```bash
...
# module load intel/18.0.3.222
# module load mpi/intelmpi/2018.0.3.222
#
# You have to install your own hdf5:
# export HDF5_ROOT=<path to your installation folder>
# export HDF5_ROOT=/ccc/work/cont003/smilei/derouilj/hdf5-1.8.16-intelmpi2018.18
# export PATH=${HDF5_ROOT}/bin:${PATH}
# export LD_LIBRARY_PATH=${HDF5_ROOT}/lib:${LD_LIBRARY_PATH}
# export HDF5_ROOT_DIR=${HDF5_ROOT}
```

**Comment by kevinCassou** [comment]
Hi 
I load the right environment at login 
```source env_skl.sh```
and then I compile with
```make -j 4 machine=joliot_curie_skl```
It that right ? should i add `config=no_mpi_tm`?

**Comment by mccoys** [comment]
You need to add the environment in your submission script as well

**Comment by beck-llr** [comment]
Unless it is already in the `.bash_profile` . In which case the issue comes from somewhere else.

**Comment by kevinCassou** [comment]
no it is not `.bash_profile`but in .bashrc which it is the same

**Comment by jderouillat** [comment]
> Hi
> I load the right environment at login
> `source env_skl.sh`
> and then I compile with
> `make -j 4 machine=joliot_curie_skl`
> It that right ? should i add `config=no_mpi_tm`?

It depends, what is in the `env_skl.sh` file ?

**Comment by kevinCassou** [comment]
here the `env_skl.sh`

```
#!/bin/bash

module purge 
module load intel/18.0.3.222
module load mpi/intelmpi/2018.0.3.222

export HDF5_ROOT=/ccc/work/cont003/smilei/derouilj/hdf5-1.8.16-intelmpi2018.18
export PATH=${HDF5_ROOT}/bin:${PATH}
export LD_LIBRARY_PATH=${HDF5_ROOT}/lib:${LD_LIBRARY_PATH}
export HDF5_ROOT_DIR=${HDF5_ROOT}


export PYTHONHOME=/ccc/work/cont003/smilei/derouilj/anaconda2
export PATH=$PYTHONHOME/bin:$PATH
export LD_LIBRARY_PATH=$PYTHONHOME/lib:$LD_LIBRARY_PATH
```

**Comment by jderouillat** [comment]
So, I think that @mccoys is right.  
The `source env_skl.sh` is missing in your script ` runSmilei-lpi-ii-case0.sh`.

**Comment by kevinCassou** [comment]
Ok many thanks I'll test it .

**Comment by kevinCassou** [comment]
I confirm that putting the line 
```source env_skl.sh ```
at the beginning of the run script remove the error. 

Many thanks for your help

**Comment by kevinCassou** [comment]
Hi,

just a quick add, during the checking the run (with the add in the script of `source env_skl.sh`  did not scratch at `timesteps = 10200` but later at `timesteps = 52100` with the following error 

```
Fatal error in PMPI_Isend: Invalid rank, error stack:
PMPI_Isend(171): MPI_Isend(buf=0x2ae8205f1440, count=1, MPI_INT, dest=40, tag=253922, MPI_COMM_WORLD, request=0x2ae8201cf850) failed
PMPI_Isend(111): Invalid rank has value 40 but must be nonnegative and less than 40
```

**Comment by jderouillat** [comment]
Hi,
You don't have any `env_skl.sh` in your running directory, so it's useless. You can the error in the error file :
```bash
+ source env_skl.sh
/tmp/jobstart.61490: line 3: env_skl.sh: No such file or directory
```
For your successful simulation, you may have execute the `source env_skl.sh` in your shell before submitting. To ensure the behaviour of the simulation copy the env file in your directory or specify the pass to it. `source ~/env_skl.sh` ?

**Comment by kevinCassou** [comment]
Hi, thanks and  sorry for this stupid mistake.
