### ISSUE TITLE
Expected energy inconsistency

### ISSUE THREAD

**Issue by Nikolai-mephi** [SmileiPIC/Smilei#262]
## Description

Dear Smilei team,
I am conducting simulations studying dynamics of a plasma cloud irradiated by an intense laser pulse and I keep running into certain physical inconsistency. It is related to expected and consequently balance energy in scalar diagnostics. While field diagnostic outputs as well as all other scalar diagnostic energies don't look catastrophically incorrect, expected energy at some point - when the laser energy has reached its maximum and the total energy stabilizes - suddenly spikes towards negative values that are orders of magnitude higher than total energy at this moment. So I would like to know what could possible cause such behaviour. Can it be a bug in expected energy calculations?
Thank you in advance for your help. 
[ni_log0000156000.pdf](https://github.com/SmileiPIC/Smilei/files/4754629/ni_log0000156000.pdf)
[Uelm.pdf](https://github.com/SmileiPIC/Smilei/files/4754620/Uelm.pdf)
[Uexp.pdf](https://github.com/SmileiPIC/Smilei/files/4754622/Uexp.pdf)
[Ukin.pdf](https://github.com/SmileiPIC/Smilei/files/4754623/Ukin.pdf)
[Utot.pdf](https://github.com/SmileiPIC/Smilei/files/4754624/Utot.pdf)

## Parameters

- Smilei version: Smilei 4.3 v2b-103cca
- Input file 
[rect_2D.txt](https://github.com/SmileiPIC/Smilei/files/4754656/rect_2D.txt)
- Commands or script used to run the faulty simulation 
[smilei_2D.txt](https://github.com/SmileiPIC/Smilei/files/4754670/smilei_2D.txt)
- Computing resources
  - type of computer: HPC
  - OS: Debian GNU/Linux 10 (buster)
  - HDF5 version: 1.10.4
  - Python version: 2.7.16

**Comment by mccoys** [comment]
Hi,

You are using Smilei 4.3. The releases website shows that:
* In v4.4: `Scalar Ukin for ions was incorrect, thus Ubal was also wrong`
* In v4.5: `Scalar Ukin_bnd was sometimes wrong with load balancing`

I would suggest upgrading to v4.5 to see if those bugfixes address your issue.

**Comment by Nikolai-mephi** [comment]
I have upgraded smilei to v.4.5 and run the same simulation again. Now the behaviour of expected energy at the moment when laser pulse ends as well as later moments looks correct and is in agreement with the total energy. So v4.5 bugfixes really seem to have resolved my issue, thanks!
