### ISSUE TITLE
Problem when installing Smilei on Mac

### ISSUE THREAD

**Issue by areija** [SmileiPIC/Smilei#263]
Good morning:

I'm currently trying to install Smilei on my MacBook. I've followed the instructions given on the website, particularly I've completed the following steps on the "Prerequisites" section: "Macports: install dependencies" and "Brew: install Smilei". After doing that, I cloned the latest version of Smilei on my computer as it's said on the instalation guide, but after doing:

cd Smilei
make

I get this errors:

<img width="684" alt="Captura de pantalla 2020-06-11 a las 11 06 47" src="https://user-images.githubusercontent.com/66775217/84367479-976ad980-abd4-11ea-8256-1ae849241c91.png">

Hope you can help me.

Kind regards.

Alicia.

**Comment by iltommi** [comment]
Hi Alicia,
could you provide the output of `make env` ?

I think we did not explicitly mention that it's either brew or macports. Mixing both might cause some problems (and I suppose it's your case). We have to fix the doc.

About which one to use: I prefer brew, but if someone has already installed macports it's possible to install brew with it. I would suggest to uninstall macports if you can.

**Comment by areija** [comment]
Hi, 

thank you for your answer. This is the output of `make env`:
<img width="936" alt="Captura de pantalla 2020-06-11 a las 11 31 53" src="https://user-images.githubusercontent.com/66775217/84369625-6f30aa00-abd7-11ea-95c9-677b8abab6a2.png">
Yes, I think that might be the problem. Should I uninstall Macports and install the dependencies following "Brew: install dependencies"?

Thank you! 

Alicia.

**Comment by iltommi** [comment]
yes!

**Comment by areija** [comment]
Hi, thank you for your quick reply. I followed the steps and finally got the Smilei executable, so I think it's working fine now.

Have a nice day! 

Alicia.
