### ISSUE TITLE
TNSA in 2-d

### ISSUE THREAD

**Issue by San-thosh** [SmileiPIC/Smilei#264]
Dear Smilei Team,

Thank you very much for developing Smilei and making it open to all.

I am trying to simulate TNSA from laser foil interaction in 2-d regime. My target is an aluminum foil with a proton layer at the rear surface (have included proton layer because in experiments usually there will be hydrocarbon contaminant layer on the surface of target). My objective is to observe these protons accelerated via TNSA mechanism. For comparison, I have also replaced proton layer with a hydrogen layer and defined a seperate species for electrons which are obtained as a result of ionization of hydrogen layer.

The spectrum in case of proton shows a maximum of about 17.5MeV whereas in case of hydrogen it shows about 20MeV.

Q1. Why is neutral hydrogen getting accelerated to higher energy when compared to protons? TNSA in this case should have produced relatively higher energy protons in contrary to the observation.

Q2. From the spectrum it is indicative that the low energy (0MeV) protons are significantly lower in number which physically means that almost all of the protons are accelerated. This seems unphysical.

Could you please address these questions and how to resolve them as I am unaware of whether these are phyical errors or numerical errors. I am very new to smilei, It would be very helpful if someone could point out my mistakes and help me improvise.

Thanks in advance :)

![al_hyd_spec](https://user-images.githubusercontent.com/66816175/84468038-7620f080-ac9b-11ea-9e4a-70cd97274e24.png)
![al_pro_spec](https://user-images.githubusercontent.com/66816175/84468041-77521d80-ac9b-11ea-804e-bc6c405b8705.png)
[al_hyd.docx](https://github.com/SmileiPIC/Smilei/files/4768928/al_hyd.docx)
[al_pro.docx](https://github.com/SmileiPIC/Smilei/files/4768929/al_pro.docx)

**Comment by mccoys** [comment]
Hi
I would like to point out that these questions are not relevant to this website. These issues are dedicated to reporting bugs or things that are unclear how to use. We do not provide support concerning the understanding of the physics occurring in your simulations. If you believe there is a bug, then you need to provide some indications why.
Q1: there will be slight differences while the hydrogen atoms are ionized, and the resulting acceleration will depend on the details of the simulation. This requires a physical study that is not relevant on this website.
Q2: It is not necessarily wrong that all protons are accelerated. They all see a strong field after all. But again, this is a physics study for which this website does not provide support.

If you want to talk to other Smilei users, we recently started a Riot.im chat. Maybe some people would be happy to help : [riot chat](https://riot.im/app/#/room/!LQrdVpOJEohPSWMlmf:matrix.org)
