### ISSUE TITLE
Units in happi plots

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#265]
![Ex](https://user-images.githubusercontent.com/48507571/84701123-a9da6f80-af54-11ea-866d-560e15429953.png)
Hi Smilei team,

Hope everybody is fine!
A question : when I plot a Field diag with happi, units of Ex is not recognized (everything is ok for x in L_r and time in T_r or respectivly in um and fs if I use pint). I have this : 
WARNING: units unknown: E_r

I think it was OK in last versions...

Julien

**Comment by juliencelia** [comment]
If that can help it the same issue with others diags and it seems there is a confusion between y and v for vmin,ymin for example

**Comment by mccoys** [comment]
Can you check the last push ? It should fix your bug
