### ISSUE TITLE
Pair creation advanced tutorial

### ISSUE THREAD

**Issue by areija** [SmileiPIC/Smilei#266]
Good afternoon,

I was about to start the "Multiphoton Breit-Wheeler pair creation process" advanced tutorial when I found out that the script "AdvancedPractical2.tar.gz" is not avaliable (it says "file not found"). Could you please provide it to me or tell me where can I find it?

Thank you,

Alicia.

**Comment by mccoys** [comment]
We need to update the link.
In the meantime, please use https://smileipic.github.io/tutorials/AdvancedTutorial2.tar.gz
