### ISSUE TITLE
Is there a way to remove the colorbar when using happi.multiPlot?

### ISSUE THREAD

**Issue by ywppku** [SmileiPIC/Smilei#268]
Dear Developers,

I want a quick check about the field and phase space structures at a certain time, at a certain position.
![image](https://user-images.githubusercontent.com/37392893/85811424-6c4cc200-b75e-11ea-8ef5-ed59020869a7.png)

Is there a quick way to remove the colorbar for the phase space, so that the x-axis of the above three plots are in line with each other?
Maybe also remove the title and the legend at the upper-right corner?

Or for this kind of customized visualization, I need to get the data out and play with them, instead of using happi's plotting functions?

Thanks so much for your help.

**Comment by mccoys** [comment]
I am not sure, but the colorbar might be removed by setting `cbaspect=0` in the corresponding diagnostic.

The titles can be removed using `title=""` in each diagnostic.

To "play" with the data, use `getData()` and create your own plotting scripts.

**Comment by mccoys** [comment]
I forgot about the legend. Unfortunately, this cannot be avoided yet. I will have to work on that.
You can only remove the legend afterwards using `cla().get_legend().remove()` or similar.

**Comment by ywppku** [comment]
Dear @mccoys 

Thanks for your reply, it works!
