### ISSUE TITLE
userfunction in Smilei version 4.5 does not work in ParticleBinning diagnostics

### ISSUE THREAD

**Issue by jpsikal** [SmileiPIC/Smilei#269]
Dear Smilei developers, 

I found a bug in Smilei v4.5.

I applied a userfunction in ParticleBinning diagnostics in Smilei code, version 4.3 which worked well. 
However, it stopped to work with Smilei version 4.5

error in logfile with Smilei version 4.5:
```
[ERROR](0) src/Diagnostic/HistogramFactory.h:167 (createAxis) DiagParticleBinning #3, axis 0: : First item must be a string (axis type)
```

logfile with Smilei version 4.3 (it runs correctly):
```
Created ParticleBinning diagnostic #3: species proton
                 Axis user_function0 from -180 to 180 in 360 steps
                 Axis ekin from 0 to 600 in 200 steps

my userfunction:

def angley(particles):
    px1=particles.px
    py1=particles.py
    theta=numpy.zeros(len(px1))
    for k in range(0, len(px1)):
        if (px1[k]>0):
            theta[k]=math.atan(py1[k]/px1[k])*180./math.pi
        elif (px1[k]<0)*(py1[k]>0):
            theta[k]=180.+math.atan(py1[k]/px1[k])*180./math.pi
        elif (px1[k]<0)*(py1[k]<=0):
            theta[k]=-180.+math.atan(py1[k]/px1[k])*180./math.pi
        elif (px1[k]==0)*(py1[k]<0):
            theta[k]=-90.
        else:
            theta[k]=90.
    return theta
```

my ParticleBinning diagnostics related to userfunction:

```
DiagParticleBinning(
    deposited_quantity = 'weight',
    every = [diagStartB2,diagEveryB2],
    time_average = 1,
    species = ['proton'],
    axes = [
        [angley, -180., 180., 360],
        ['ekin', 0., 200., 200]
    ]
)
```

**Comment by mccoys** [comment]
Which version are you using exactly ? Downloaded tar from the website, or a specific pull from github ?

By the way, you can use directly numpy's function for your arctan: `arctan2(py1,px1)`

**Comment by mccoys** [comment]
I just realized that your error occurs only if numpy was not detected in your python installation. Could you provide the "intro" of your log (where versions are given) as well as the result of `make env`.

**Comment by jpsikal** [comment]
I solved this problem simply by using the older version of Smilei (4.3) where it works in my case. 
Nevertheless, I wanted to point out a potential bug in newer Smilei version. 

I used tar versions from the website http://www.maisondelasimulation.fr/smilei/releases.html

Intro of log files:
 Reading the simulation parameters
 --------------------------------------------------------------------------------
 HDF5 version 1.12.0
         Python version 2.7.5
         Parsing pyinit.py
         Parsing ??-??
         Parsing pyprofiles.py
         Parsing 2DCHexp05.py
         Parsing pycontrol.py
         Check for function preprocess()
         python preprocess function does not exist
         Calling python _smilei_check
         Calling python _prepare_checkpoint_dir

The result of make env for smilei v4.5:
SMILEICXX : mpicxx
PYTHONEXE : python
MPIVERSION :
VERSION : ??-??
OPENMP_FLAG : -fopenmp -D_OMP
HDF5_ROOT_DIR : /usr/local/hdf5
SITEDIR : /home/klimo/.local/lib/python2.7/site-packages
PY_CXXFLAGS : -I/usr/include/python2.7 -I/usr/include/python2.7 -I/usr/lib64/python2.7/site-packages/numpy/core/include -DSMILEI_USE_NUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
PY_LDFLAGS : -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic
CXXFLAGS : -D__VERSION=\"??-??\" -D_VECTO -std=c++11 -Wall  -I/usr/local/hdf5/include -Isrc -Isrc/Profiles -Isrc/MovWindow -Isrc/Tools -Isrc/Collisions -Isrc/Checkpoint -Isrc/Particles -Isrc/ElectroMagnBC -Isrc/picsar_interface -Isrc/Radiation -Isrc/Field -Isrc/ElectroMagnSolver -Isrc/Params -Isrc/ElectroMagn -Isrc/DomainDecomposition -Isrc/Python -Isrc/Species -Isrc/Ionization -Isrc/Projector -Isrc/Interpolator -Isrc/ParticleInjector -Isrc/Merging -Isrc/Patch -Isrc/Diagnostic -Isrc/MultiphotonBreitWheeler -Isrc/Pusher -Isrc/SmileiMPI -Ibuild/src/Python -I/usr/include/python2.7 -I/usr/include/python2.7 -I/usr/lib64/python2.7/site-packages/numpy/core/include -DSMILEI_USE_NUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D_VECTO -O3 -g  -fopenmp -D_OMP
LDFLAGS : -L/usr/local/hdf5/lib   -lhdf5 -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -lm -fopenmp -D_OMP

The result of make env for smilei v4.3:
SMILEICXX : mpicxx
PYTHONEXE : python
MPIVERSION :
VERSION : ??-??
OPENMP_FLAG : -fopenmp -D_OMP
HDF5_ROOT_DIR : /usr/local/hdf5
SITEDIR : /home/klimo/.local/lib/python2.7/site-packages
PY_CXXFLAGS : -I/usr/include/python2.7 -I/usr/include/python2.7 -I/usr/lib64/python2.7/site-packages/numpy/core/include -DSMILEI_USE_NUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
PY_LDFLAGS : -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic
CXXFLAGS : -D__VERSION=\"??-??\" -D_VECTO -std=c++11 -Wall  -I/usr/local/hdf5/include -Isrc -Isrc/Profiles -Isrc/MovWindow -Isrc/Tools -Isrc/Collisions -Isrc/Checkpoint -Isrc/ElectroMagnBC -Isrc/picsar_interface -Isrc/Radiation -Isrc/Field -Isrc/ElectroMagnSolver -Isrc/Params -Isrc/ElectroMagn -Isrc/DomainDecomposition -Isrc/Python -Isrc/Species -Isrc/Ionization -Isrc/Projector -Isrc/Interpolator -Isrc/ParticleInjector -Isrc/Merging -Isrc/ParticleCreator -Isrc/Patch -Isrc/Diagnostic -Isrc/MultiphotonBreitWheeler -Isrc/Pusher -Isrc/SmileiMPI -Ibuild/src/Python -I/usr/include/python2.7 -I/usr/include/python2.7 -I/usr/lib64/python2.7/site-packages/numpy/core/include -DSMILEI_USE_NUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D_VECTO -O3 -g  -fopenmp -D_OMP
LDFLAGS : -L/usr/local/hdf5/lib  -lhdf5 -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -lm -fopenmp -D_OMP

**Comment by mccoys** [comment]
Is it possible for you to try the last push on github ?

**Comment by jpsikal** [comment]
Did you mean to use git clone https://github.com/SmileiPIC/Smilei.git for download the latest Smilei version?

I downloaded it, compiled it and have tested it. 
Now the userfunction in ParticleBinning diagnostics works.


Intro of log file:

 HDF5 version 1.12.0
         Python version 2.7.5
         Parsing pyinit.py
         Parsing v4.4-700-gd511fb9-master
         Parsing pyprofiles.py
         Parsing 2DCHexp05.py
         Parsing pycontrol.py
         Check for function preprocess()
         python preprocess function does not exist
         Calling python _smilei_check

**Comment by mccoys** [comment]
Ok, this must be due to some issues with python compatibility we had at the release for 4.5
