### ISSUE TITLE
Error when compiling with `machine=XXX` with Smilei v4.5 [FIXED] 

### ISSUE THREAD

**Issue by lesnat** [SmileiPIC/Smilei#272]
Hi there !

Once again, I'm installing Smilei on another machine.

This time I got an error that was quite easy to solve, so I give you the context and the solution.
When I used the parameter `machine` of the `make` command I got the following error:

> [...]
Compiling src/Collisions/CollisionsSingle.cpp
ls: cannot access scripts/CompileTools/machine: No such file or directory
joliot_curie_knl do not exist for machine
Use one of :  
make: *** [check] Error 255
make: *** Waiting for unfinished jobs....

I then searched for files containing `CompileTools` using `grep -r` and found the line 37 of the file `scripts/compile_tools/check_make_options.py` containing
```python
cmd = subprocess.Popen('ls -1 scripts/CompileTools/machine', shell=True, stdout=subprocess.PIPE)
```

I then only replaced the path `scripts/CompileTools/machine` by `scripts/compile_tools/machine` and everything seems to run right.

I wanted to do a merge request to fix this directly but it seems that the file `check_make_options.py` has disappear in the current state of the master branch, so I just let you know this and let you deal with it ;) 

That's all !

Cheers,
Léo.

**Comment by jderouillat** [comment]
Hi Léo,  
We indeed changed recently the way to check options passed to the build system fixing this bug.
Regards

Julien
