### ISSUE TITLE
MPI_Recv error with user created module 

### ISSUE THREAD

**Issue by arsampath** [SmileiPIC/Smilei#275]
Dear developers,

I have tried to implement bremsstrahlung emission in Smilei 4.4.
When I have this bremsstrahlung emission activated, the outcome (created number of photons) is as expected. These photons also successfully convert into multiphoton Breit-Wheeler pairs when needed. 
But I get a MPI_Recv error when these new pairs (created by bremsstrahlung photons) are emitting via synchrotron emission.

Could you confirm if I need to swtich on some specific tag/ID for synchrotron emission? 
I can discuss further about this on Riot/email when you are available.

Any help regarding this is much appreciated! Thank you for your time.

**Comment by mccoys** [comment]
Hi, it is interesting that you are considering bremsstrahlung emission. We also have someone working on this subject here.

Your problem of MPI_Recv is probably connected to the way Smilei handles new particles and how it needs to sort them. This affect their communication between processes. Have you looked at how it is done in ionization or radiation reaction ?

**Comment by arsampath** [comment]
Thank you for a prompt response. 
The bremsstrahlung module is implemented within the Collision algorithm. 
Hence I have tried to import the new particles similar to how it is done for Collisional ionization. 
Once, the bremsstrahlung photon is emitted (within the collision module), I set the particle attributes (position, momentum, weight, charge, tau(if needed) and chi (if needed)), then use vecSpecies-> importParticles(params, patch, particles_that_are_needed_to_be_imported, localDiags).

**Comment by jderouillat** [comment]
Hi,
Are you able to produce a single patch test ? Without periodic conditions, which are handled through MPI.
The idea is to run a communication less simulation to check that the bremsstrahlung algorithm works in the simplest context.

Julien

**Comment by xxirii** [comment]
Dear @arsampath,

We are working on implementing the Bremsstrahlung emission in Smilei with a master student. I will contact you in private via Riot to exchange about it. It seems we want to do the same thing.

**Comment by mccoys** [comment]
Should we close this issue?

**Comment by arsampath** [comment]
Yes, thank you!
