### ISSUE TITLE
Batch submission of jobs

### ISSUE THREAD

**Issue by HighIander** [SmileiPIC/Smilei#276]
Following the advice I got from @beck-llr at riot, I here provide my scripts/workflow to do batch submission.
I hope there are not too many errors below, but the idea should become clear :-)

[batch.zip](https://github.com/SmileiPIC/Smilei/files/4896085/batch.zip) contains:
1) The smilei.profile, in oder to set path variables to find the tbg script and to set other variables.
2) The tbg script.
3) A sample submit script.
4) A sample input.py
5) A sample inputBatch.py

### How to do it:
**Preparation (once):**
* put the source in $PICSRC
* put the smilei.profile somewhere and modify it to your needs
* put the sample cases in separate directories in $PICINPUTS
* put the path to tbg in the PATH variable

**Setup of a simulation (for each scan):**
* create a directory in $PICINPUTS, e.g. 'myscan'
* in 'myscan', create your input file and submitscript as usual. Important: tbg assumes them to be named as defined in the smilei.profile
* copy the inputBatch.py and change it for your needs. Here you define the scan parameters for each case, identified by a running number (currentSim)
* run tbg either with or without batch mode enabled -> done! Careful, though, you might spawn thousands of jobs at once :-)

### how to submit/i.e. how to use tbg (run tbg -h for more information):
**tbg without batchmode:**
tbg -t [path_to_where_the_output_shall_go]
what it does:
--> the input file and submit script and $PICSRC are all copied to [path_to_where_the_output_shall_go]
--> the job is submitted using the command defined in the profile

**tbg in batchmode:**
tbg -t [path_to_where_the_output_shall_go] -b 1 -n 2
what it does:
* it submits n cases, starting at b (in the above example, this would be case 1 and 2)
* so in the input batch file you should have defined those parameters for currentSim==1 and currentSim==2 which you need in the input file
* for each case i:
--> the inputBatch file, input file, submit script and $PICSRC are all copied by tbg to [path_to_where_the_output_shall_go]/$i
--> the inputBatch file gets prepended to the input file
--> a file current.py is created which defines the variable currentSim = $i and appended to the input file
--> the simulation name is appended with $i in the submitscript
--> the case is submitted

Obviously, you can submit a parameter scan setup with tbg without batchmode. For this, you can define default parameters in the input file, eg. to set var to val if not otherwise set during batch submission simply use `set('var',val)`
I don't like this, so maybe someone has a better solution to `set`

**Comment by beck-llr** [comment]
Thanks for sharing ! This is much appreciated.
