### ISSUE TITLE
How to read initial profiles from an existed file?

### ISSUE THREAD

**Issue by smallrainbow** [SmileiPIC/Smilei#278]
Dear developers, 

How to read initial profiles: e.g., electromagnetic fields, particle density, temperature, bulk velocity profiles from existed files generated by fortran (e.g., [inital.zip](https://github.com/SmileiPIC/Smilei/files/4953886/inital.zip)) or python in the namelist, please?

Thank you very much!

**Comment by mccoys** [comment]
There is currently a way to load particles one by one from a numpy array. It is not very efficient and we are working on alternate possibilities.

Profiles (density, fields, etc) are given in user-defined functions which you can tune to read your own files. If you have better ideas on how to improve this, you are welcome to suggest them here.

**Comment by smallrainbow** [comment]
@mccoys 
Dear Mccoys, thanks for your reply. 
Could you add a way to read existed files as EPOCH (developed by UK group... we prefer SMILEI which has a better normalization system), please?
Motivation: 
(1) Sometimes, the initial state might be complex and issued from observations. Functions are difficult to describe the profiles (more like a data driven simulation).
(2) In addition, velocity distribution functions (VDF) at the initial time could be non-Maxwellian (e.g., shell distribution for pickup ions -> freshly ionized; maxwellian core plus a power-lar tail etc.) If users define such specific VDF, then the namelist can use it instead of the default one.
Thank you very much if you can bring this feature in future versions.

**Comment by beck-llr** [comment]
You can already do so as @mccoys said. It is just that it will not scale very well on huge 3D simulations for the moment, especially for particles.
For particles, you just have to write a python function that reads your file and put the required information into numpy arrays as specified in the documentation and you particles will be initialized as you want.
For fields, you need to use the Externalfields class and write a python function which reads data from your fortran file. If the data has not the same resolution as your simulation you will need to use an interpolator.

**Comment by smallrainbow** [comment]
@beck-llr Thanks.

**Comment by mccoys** [comment]
I added the feature-request label again, so that we can keep this issue open until we have a more efficient system.

**Comment by mccoys** [comment]
There are two ways to have profiles imported from files:
1. The file must contain exactly the same number of cells as the simulation. This requires knowledge from the user that fields all have different number of points in different directions (primal/dual grids).
2. The file is assumed to have the same box size as the simulation, but not necessarily the same number of cells. An interpolation (linear?) is made in smilei to recover the values at grid points.

Can we share some opinions on this subject ?

**Comment by juliencelia** [comment]
Hi mccoys,

For the number 2, I personally read a file txt or hdf5 from hydro codes (grids are very bigger than PIC code).
To read in 1D, the use of scipy.interpolate.interp1D is very efficient with linear, cubic and even quadratic.
For 2D simulation, be carefull with memory for interpolation. Use of scipy.griddata method is efficient with "nearest" method. If the grid is large (lots of cells), the use of linear interpolation is too costly.

If that can help....

**Comment by DoubleAgentDave** [comment]
I've tried doing this by loading a numpy array and then creating a function to access it, but I'm a little concerned with how well the memory consumption of this scales:

density_array = np.array(stuff)
# where stuff is a 3D array the same size as the sim box
def dens_func(density_array,dx,dy,dz):
      def density_input(x,y,z):
            try:
                return density_array[int(x/dx),int(y/dy),int(z/dz)]
            except IndexError:
                # for a moving window this is necessary
                return 0.0
      return density_input

electron_dens = dens_func(density_array,dx,dy,dz)

and then I just put electron_dens into the number_density or charge_density bit in the species section. The trouble being that this could be a large amount of memory used. It works fine on a tiny 3D grid on my laptop with 4 MPI tasks, but if this function is stored for each MPI task this could get large. I've not tried this on a large scale simulation yet, but I'll need to for some of the weird etched targets we've been talking about using.

**Comment by mccoys** [comment]
@DoubleAgentDave I believe some people have managed to reduce the memory footprint by loading only the useful piece of the file depending on the value of `x`, `y` and `z`. The trick is that most profiles can be of 2 types: either the classic function (x, y, and z are floats) or a function of numpy arrays (x, y and z are arrays of the same shape as the current patch being treated). Smilei first tries the second option, and falls back to the first one if it fails. This way, the user can try to find out which part of the box is currently being loaded by the corresponding MPI task, and only extract the right portion of the file.

This technique is quite advanced, so we have been wondering how this could be improved. The whole thing could actually be done directly in Smilei. The user could just specify a file name and Smilei does the rest. However, we have not decided on how this should be done, as it strongly restricts the versatility of the process. Users would have to provide a well-formatted file, with the correct size, and so on ... Or there could be some automated interpolation process, but this is even more advanced. This needs to be discussed and figured out.

**Comment by mccoys** [comment]
Let me add that users are welcome to give their opinion on this subject or suggest a good way to make it user-friendly.

**Comment by DoubleAgentDave** [comment]
Thanks I think I see what you're saying, I'd have to load the file somehow using the smilei_mpi_rank and smilei_mpi_size I can thenlet the patches take the bits they need. The only problem with that is to know where in space the mpi task sits and what shape it is, if it's a piece of a hilbertian it's not trivial. If I can write a function like this that works I'll share it here. Getting the patches to load bits is easy, but is there an easy way to obtain the box shape from the MPI task?

If you guys aren't going to add this feature then maybe some sort of tutorial on it in the smilei documentation would be useful. It's a feature that would be really useful when intergrating smilei into a chain of different simulations, e.g. using FLASH or something for pre-plasma calculations where the pre-plasma extent isn't an easily analysed function, so I can see a lot of people using it at some point.

**Comment by mccoys** [comment]
@DoubleAgentDave I was maybe not very clear before, but the `x` `y` and `z` variables (or the custom function) are arrays that correspond to all the cells of the current patch. So you can obtain the exact location of all these points. For example, `x.min()` and `x.max()` gives you access to the boundaries in `x` and `x.shape[0]` gives you the number of points in the `x` direction (and so on). You may use these info to extract the correct location in the file.

One additional issue may be to open a file simultaneously on many MPI ranks. This is not always supported on some filesystems. You may have to use some python MPI manager (such as mpi4py) to coordinate the reading tasks.

**Comment by DoubleAgentDave** [comment]
OK, I was thinking of opening the thing on the MPI task level rather than the patch level for that reason.

**Comment by mccoys** [comment]
Today's release (v4.6) now allows to import a profile from a file. You are welcome to test it and report whether it is convenient for your cases.
