### ISSUE TITLE
Setting fontsize in *.plot() and happi.multiplot()

### ISSUE THREAD

**Issue by humanoid-v1911** [SmileiPIC/Smilei#279]
I am trying to edit the details of my figures, especially (general) fontsize. However I can't figure out the kwarg to do the job of setting the fontsize of ticks, labels, nor titles or in general the fontsize itself. I've tried "fontsize", "labelsize", "textsize" and "titlesize" but none of them works. 

Is there a way to use pyplots *.rc() command or how does setting the (general) fontsize work?

Additionally I have a similar problem with creating a label for colorbars, however this is not the main concern.

**Comment by mccoys** [comment]
Setting fonts is actually possible but not documented, because it is not very easy to use.
Example:
```python
S.Field(0,"Ex").plot( title = dict(label="my_title", fontdict={"fontsize":20, 'fontweight':'bold'}) )
```

I added a new way to use fonts that is not available yet in the main repository:
```python
S.Field(0,"Ex").plot( title="my_title", title_font={"fontsize":20, 'fontweight':'bold'} )
```
This will be documented and released soon.

**Comment by Tissot11** [comment]
I want to expand on this question and ask if one can change fonts family, _x_ and _y_ labels while using happi's commands to visualise the results etc. This is particularly useful when using the streak() and animate commands, since saving a mp4 movie in Python is not always trivial and it seems to work with happi very well.

**Comment by humanoid-v1911** [comment]
I was able to globaly set font specs by using the Matplotlib command

`.rcParams[ ]`

Although very simple and useful this sets the reference font parameter for all texts used globaly.

**Comment by mccoys** [comment]
> I want to expand on this question and ask if one can change fonts family, _x_ and _y_ labels while using happi's commands to visualise the results etc. This is particularly useful when using the streak() and animate commands, since saving a mp4 movie in Python is not always trivial and it seems to work with happi very well.

The `fontdict` may contain more information, such as the font family : https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.set_title.html#matplotlib-axes-axes-set-title

This will be explained in a new version soon
