### ISSUE TITLE
Prescribed fields divergence

### ISSUE THREAD

**Issue by babjarob** [SmileiPIC/Smilei#281]
Dear developers,

I am trying to use Prescribed Fields in the simulation consisting only of test electrons and counter-propagating laser pulses. However, using Prescribed Fields leads to divergence in electromagnetic field, see figure below.
![bz](https://user-images.githubusercontent.com/48128952/89063390-656e2c00-d368-11ea-8b7f-a69a85c7c035.png)

I've tried using pre-defined profiles, my own profile as a function and none of them seems to work. 
I use Smilei version 4.5, input file is here:  [pf.txt](https://github.com/SmileiPIC/Smilei/files/5008402/pf.txt)

Is there any mistake in a way I define the field?

Thank you for your response

**Comment by mccoys** [comment]
I am not sure what is happening, but can you use ExternalField instead ?

**Comment by afzalraghavi** [comment]
Actually I'm trying to simulate a free electron laser. In the absence of constant magnetic wiggler field I can see the electric and magnetic fields of defined laser pulse but as magnetic wiggler field is imposed, either using prescribed or external field blocks, the laser fields disapear.

**Comment by afzalraghavi** [comment]
Actually I'm trying to simulate a free electron laser. In the absence of constant magnetic wiggler field I can see the electric and magnetic fields of defined laser pulse but as magnetic wiggler field is imposed, either using prescribed or external field blocks, the laser fields disapear.

**Comment by afzalraghavi** [comment]
Actually I'm trying to simulate a free electron laser. In the absence of constant magnetic wiggler field I can see the electric and magnetic fields of defined laser pulse but as magnetic wiggler field is imposed, either using prescribed or external field blocks, the laser fields disappear.
Meanwhile, external field could not be used because it does not stay constant during the simulation as a real constant external field.

**Comment by mccoys** [comment]
@afzalraghavi  This seems like a different subject than that of @babjarob. Please open a new issue and give more details on your simulation.

@babjarob Your namelist seems to work for me. Could you try again with the last commit available here on github ? Could you specify your number of processes and threads ?

**Comment by jderouillat** [comment]
Hi,  
Could you test the branch `prescribed_field` (https://github.com/SmileiPIC/Smilei/issues/287#issuecomment-683627303) ?  
We find an inconsistency in the algorithm.
Regards

Julien

**Comment by mccoys** [comment]
@babjarob This issue should be resolved now in branch "master".

@phi-kafka this should solve your issue #298 as well

**Comment by phi-kafka** [comment]
Thanks mccoys! Yes, it looks solved.
