### ISSUE TITLE
Simulation in 2DCartesian geometry freeze on IRENE cluster

### ISSUE THREAD

**Issue by lesnat** [SmileiPIC/Smilei#286]
Hi,

I'm currently running some simulations with an UHI laser interacting with a solid foil in 2DCartesian geometry on the IRENE cluster, and Smilei exhibit a very strange behaviour.

The simulations runs properly up to some timestep, and then it seems that everything freeze for no reason. The simulation does not seems to crash, because the job continues and there is no particular error message in the error file, but its progression is stopped, until the job is killed by me or by the cluster timeout.

To give you an example, this is the output I got in one of my simulations
[output_log.txt](https://github.com/SmileiPIC/Smilei/files/5125005/output_log.txt)

As you can see, everything seems to work well : each 100 timesteps took about 3 to 4 minutes to compute (with 10 nodes, 640 cores), and the 9500 first timesteps have taken about 3 hours to be computed.

Surprisingly, this output is however the one I get after 19 hours of computation (~10 000 CPU h), implying that about 16 hours have not been sufficient to compute 100 timesteps that took about 3 minutes just before.

The behavior of the physics in this simulation seems OK up to the freezing point, and this particular timestep have in my opinion no physical reason to take such a long time (few timesteps after the laser reflection in this case).

When the problem appears I was trying to compare the target width in three simulations, and the problem occurs for all of them.

I expected a problem with the cluster, and then used the checkpoints to re-run the simulation from previous timestep. However, if the operation succeed for one of them (the simulation runs to the end), the two other had the same freeze at the same timestep as previously (or more rigorously in the same 100 timestep, as this is the only information I can get from the output).

I then deleted the whole output folder for these two simulations, and tried to launch them back. For one of them the freeze happened at the same timestep as previously, while for the other the freeze also happened but a little bit earlier than previously.

Here are the error files in got from one of the simulation (the one freezing at timestep 9500)

[error_log_1.txt](https://github.com/SmileiPIC/Smilei/files/5125006/error_log_1.txt)

[error_log_2.txt](https://github.com/SmileiPIC/Smilei/files/5125008/error_log_2.txt)

Here is the namelist that seems to have the same freezing behavior at timestep 9500 each time (I tried 3 times and got the freeze the 3 times).

[namelist.py.txt](https://github.com/SmileiPIC/Smilei/files/5125010/namelist.py.txt)

Note that the rear of the target is stuck to the right side of the box, with absorbing boundary conditions both for fields and particles, neutral target with no electrons at the beginning of the simulation + tunnel ionization activated, and that I'm using a subgrid on DiagField and a custom filter on DiagTrackParticles to record particles that goes outside of the box (if this can help you ...).

I'm not using this cluster from a long time, but I have however also perform simulations with very similar geometry and diagnostics that runs properly up to the end with no error and freezing. I also tried with vacuum between the rear side of the target and the right side of the box.

When searching in my simulation folders, I see 1 simulation with vacuum at the rear of the target that worked properly, 1 simulation with no vacuum at the rear of the target that runs properly at the first time, and another that I think I have restarted at a checkpoint after a freeze (I don't remember exactly).

This is the launching script I'm using on IRENE

[run_irene_knl.sh.txt](https://github.com/SmileiPIC/Smilei/files/5125014/run_irene_knl.sh.txt)

where the file `.env_smilei_knl` contains

```
module purge
module load mpi
module load hdf5
module switch flavor/hdf5/serial flavor/hdf5/parallel
export HDF5_ROOT_DIR=${HDF5_ROOT}
```

The default version of hdf5 is 1.8.20 and the default mpi load the following modules

```
load module flavor/mkl/single_node (MKL without mpi interface)
load module flavor/buildmpi/openmpi/2.0 (MPI build flavor)
load module flavor/openmpi/standard (Open MPI flavor)
load module feature/openmpi/net/auto (MPI Network backend feature)
load module flavor/buildcompiler/intel/17 (Compiler build flavor)
load module feature/mkl/lp64 (MKL feature)
load module feature/mkl/sequential (MKL feature)
load module feature/mkl/vector/auto (MKL vectorization feature)
load module mkl/17.0.6.256 (Intel MKL LP64 Sequential without mpi interfaces)
load module licsrv/intel (License service)
load module c/intel/17.0.6.256 (Intel C Compiler)
load module c++/intel/17.0.6.256 (Intel C++ Compiler)
load module fortran/intel/17.0.6.256 (Intel Fortran compiler)
load module intel/17.0.6.256 (Intel Compiler Suite)
load module mpi/openmpi/2.0.4 (Open MPI)

```

I compiled Smilei v4.5 (v-3a7ca3b4) with option `machine=joliot_curie_knl`.

Sorry about this, I know that non reproducible bugs with no error codes are the kind of nightmares of programmers :/ :/ :/

Please ask me if you need more details,
Thank's a lot and good luck,
Léo.

**Comment by mccoys** [comment]
Did you use the following line for the compilation environment ?
`export OMPI_MCA_btl_portals4_use_rdma=0`

**Comment by mccoys** [comment]
Actually, this line might be needed for the execution environment as well.

KNL setup on irene is a bit special

**Comment by lesnat** [comment]
Nope I only used the parameter `machine=joliot_curie_knl`, and it seems that the line `export OMPI_MCA_btl_portals4_use_rdma=0` have been commented in the compilation scripts.

I try to compile and re-run the simulation with this options and let you know in few hours.

Thank you :)

**Comment by jderouillat** [comment]
Hi,
All informations related to the shell environment is indeed commented in thess of files in which are only set `Makefile` variables such as `CXXFLAGS`. It's a kind of embedded documentation for required modules and variables (compile time and runtime to simplfy) per supercomputer.  
Concerning the variable indicated by @mccoys, it's a runtime variable which is more than recommended on TGCC's KNL. Without we experimented deadlocks like you do.
Regards

Julien

**Comment by lesnat** [comment]
Ok I understand thank's a lot ! :)

After checking once again, I've actually also used the compilation parameter `config=no_mpi_tm` when I compiled smilei v4.5.

I've added `export OMPI_MCA_btl_portals4_use_rdma=0` to my `.env_smilei_knl` file and then `make clean`, `source .env_smilei_knl` before `make -j4 config=no_mpi_tm machine=joliot_curie_knl` to recompile smilei v4.5.

When relaunching the same simulation as I indicated before, unfortunately it seems that the simulation still freeze at timestep 9500 :/ :/

**Comment by mccoys** [comment]
Sorry, this line is needed in the runtime environment, not in the compilation environment

**Comment by lesnat** [comment]
Actually my launching script also contains `source .env_smilei_knl` so the variable should have been set before the simulation ?

Should I also put `export OMPI_MCA_btl_portals4_use_rdma=0` in my bashrc ?

**Comment by jderouillat** [comment]
No, it's ok.

I'll try to reproduce it with your namelist, I let you know.

Some comments on the parameters on parallelism that you are using :
- 512 x 256 patches for 40 process and 16 threads seems huge. It's more than 3000 patches per process, the synchronization overhead could be very significant. A 128 x 128 patches could be more appropriate.  
- On KNL with Smilei we advise to use 2 threads per core, you can set the number of threads to 32 : `export OMP_NUM_THREADS=32` in your submission script.

**Comment by lesnat** [comment]
Ok, thank you for your help !

What do you think is an acceptable number of patches per process ? In your proposition 128 x 128 patches means about 400 patches per process. I know that this should probably be very linked to the specific situation, but, talking about order of magnitudes, few 100 could be better than few 1000 or only few 10 patches per process, right ? 
I suppose this is an equilibrium between time spend in patches exchange between processes vs time lost because of very inhomogeneous computation load between processes. I'll maybe do some tests later for my specific case :)

Concerning the number of processes and threads, I didn't find many informations on the KNL cluster ; I've just followed what Julien Bonvalet (who was working on IRENE before me) recommended me.

Since you gave me some advices (and thank you for this :+1:), do you mind if I ask you what do you think about the `#MSUB` directives at the beginning of my submission script ? Julien B. recommended me to use 4 process per node, but I don't really understand why (the informations I have about the nodes just indicate "manycore", but no specific number of sockets). Maybe you have more documentation, and probably more experiment with this cluster than I have :)

I changed the instruction `export OMP_NUM_THREADS=16` to 32 in my submission script, and have also changed the line  `#MSUB -c 16` to `#MSUB -c 32` to change the number of thread per process.

To be clear about it, do you recommend me to keep 4 process per node and change the number of thread per process to 32 to get 2 thread per core (both in the `#MSUB -c` directive and in `export OMP_NUM_THREADS` instruction), or to change both the number of thread per process (from 16 to 32) and also the number of process per node (from 4 to 2 maybe) ?

**Comment by lesnat** [comment]
Maybe I could have ask these informations to the TGCC hotline instead of you, but it seems that this cluster is very special so you probably are the most qualified to answer to these questions (: (:

**Comment by jderouillat** [comment]
_10 patches per process, right ?_ For my point of view the order of magnitude to start is 10 patchs per **thread**, then as you said it depends of cases. 

For KNL, there is no socket but regarding how it is configured, the architecture could be virtually divided in quadrant. If I remember correctly it's not the case on Irene.  
The choice of 4 MPI is more to moderate the number of threads per process, because as I said to take advantage of KNL, it's necessary to overload cores with 2 or 4 threads. With Smilei, better performance on KNL have been achieved with 2 threads per core. So with 2 MPI per KNL, you should use 64 threads. Again it depends of cases.

Concerning your submission file, you should not have change the `#MSUC -c` because the idea is to use KNL hardware threads (with up to 4 threads per core). The `#MSUB -c` is for the number of cores and this does not change .

```bash
#MSUB -N 10                 # Total number of nodes
#MSUB -n 40                 # Total number of tasks to use
#MSUB -c 16                 # Number of threads per task to use

export OMP_NUM_THREADS=32
```

The same with  `#MSUC -c 32` produces an error, no ?

**Comment by lesnat** [comment]
> For my point of view the order of magnitude to start is 10 patchs per thread, then as you said it depends of cases.

Ok thank's :)

> The same with `#MSUC -c 32` produces an error, no ?

Yes, exactly
```
error: Batch job submission failed: Requested node configuration is not available
```

I've commented *Number of threads per task to use* about the `#MSUB -c` directive while it is actually not what it means, but it seems that it is more about the number of CPU per task. I'll ask for more documentation at the TGCC hotline to understand these directives better.

Thank you for these advices :+1:

**Comment by lesnat** [comment]
I'm trying to re-launch the simulation with 128 x 128 patches, 32 OpenMP thread per MPI process, and I'm also using 20 nodes instead of 10, and the simulation have computed yet up to timestep 18000 (9500 before).

I just had a discussion with Julien B at CELIA and we might have found that the freezing behaviour might be explained by a too low amount of memory. 

To remind you, I initialized the target with non-ionized atoms and activated the tunnel ionization physics module. The simulation is launched on 10 nodes of 96 Go of RAM each. At the beginning of the simulation there is no electron (the target is not ionized) so the total number of particles is about 10^8. 
When the simulation runs, the laser start to ionize the target, and then creates large amount of electrons (since the target is CH, it could be up to 7 times more than what was present at the beginning of the simulation). The memory then start to be filled by these new electrons. These electrons propagating creates huge field that contributes to ionize more and more neutral atoms, and then creates more and more macro-electrons that fill the memory. At a given point, the memory of the nodes are full, and the simulation then just takes very very long time to continue.
This might explain why the simulation starts with no problem, and doesn't really crash, because technically the computation still continue but very slowly. It also explains why when using 20 nodes it seems that the simulation continue with no problem, and that I could have done previous simulation earlier that computed also with no problem !

**Comment by mccoys** [comment]
Is there any news on this ? Was the problem resolved ?

**Comment by lesnat** [comment]
My simulations have run properly with higher number of nodes, so I suppose that a memory saturation caused by the macro-electrons created by tunnel ionization was the problem.

This was a bit of my fault, so sorry for the loss of your time, but your comments helped me a lot, thank you for this :)

I'm closing the issue,
See you !
Léo.
