### ISSUE TITLE
Incompatibility between the laser and prescribed fields

### ISSUE THREAD

**Issue by afzalraghavi** [SmileiPIC/Smilei#287]
## Description
Dear developers, 
I'm trying to simulate a Free Electron Laser (FEL) that consists of an electron beam, a seed laser and a static periodic magnetic field (wiggler). But when I insert the static magnetic field using the PrescribedField block then the electric field of laser pulse disappears. The same problem exist with the ExternalField block.

```
###### Namelist for 2D FEL

import math
c = 299792458
lambdar = 1e-6
wr = 2*math.pi*c/lambdar
#gamma= 15.0 # relativistic lorentz factor
l0 = 2.0*math.pi              # laser wavelength
t0 = l0                       # optical cicle
dx = .2
dtrans = 3.
dt = 0.95*dx
nx = 256*10
ntrans = 64*20
Lx = nx * dx
lw = Lx/1#2*gamma**2*l0
kw=2.*math.pi/lw
gamma = (math.sqrt(lw/2./l0))
beta = math.sqrt(1.-1./gamma**2)
Ltrans = ntrans*dtrans
npatch_x = 4
npatch_r = 4
bunch_sigma_x = 5*lw
bunch_sigma_r = 0.05*Ltrans 
center_bunch = 1.5*bunch_sigma_x
n0 = 0.00
alpha = 1

# normalized density of a cylindrical bunch
def nbunch_(x,y):
        
	profile_x = math.exp(-(x-center_bunch)**2/2./bunch_sigma_x**2)
	profile_r = math.exp(-((y-Ltrans/2.)**2)/2./bunch_sigma_r**2)
        profile = alpha*n0*profile_x*profile_r
	if ( (  (x-center_bunch)**2/(4.*bunch_sigma_x)**2 + ((y-Ltrans/2.)**2)/(4.*bunch_sigma_r)**2 ) < 1. ):
		return profile
	else:
		return 0.

Main(
    geometry = "2Dcartesian",
    interpolation_order = 2,
    timestep = dt,
    simulation_time = 10*Lx, #int(1*Lx/dt)*dt,
    cell_length  = [dx, dtrans],
    grid_length = [ Lx,  Ltrans],
    number_of_patches = [npatch_x, npatch_r],
    clrw = nx/npatch_x,
    EM_boundary_conditions = [ ["silver-muller","silver-muller"],
                               ["silver-muller","silver-muller"] 
    ],
    solve_poisson = False,
    solve_relativistic_poisson = True,
    print_every = 100,
    reference_angular_frequency_SI = wr,
    random_seed = smilei_mpi_rank
)



Species( 
    name = "eon",
    position_initialization = "random",
    momentum_initialization = "cold",
#    relativistic_field_initialization = True,
    particles_per_cell = 1,
    c_part_max = 1.0,
    mass = 1.0,
    charge = -1.0,
    charge_density = nbunch_,
    mean_velocity = [beta, 0.0, 0.0],
    pusher = "vay",    
    radiation_model = "Landau-Lifshitz",
    time_frozen = 1,
    boundary_conditions = [
        ["remove", "remove"],
        ["remove", "remove"],
    ],
)
RadiationReaction(
    minimum_chi_continuous = 1e-3,
#    minimum_chi_discontinuous = 1e-2,
    table_path = "/gpfshome/mds/staff/mlobet/smilei/databases/"
)

LaserGaussian2D(
    box_side         = "xmin",
    a0              = 0.001,
    omega           = 1.,
    focus           = [0*Lx, 0.5*Ltrans],
    waist           = 2*bunch_sigma_r,#1.e5*Ltrans,
    time_envelope  =  tgaussian(start=0,duration=2*lw,fwhm=2*lw/3,center=lw,order=2)
)

#Define the wiggler field
B0 = 0.05
def Bz(x,z,t):
	return B0*math.sin(kw*x)
PrescribedField(
	field = "Bz",
	profile = Bz
)

list_fields = ['Ez','Ey','Bz','Rho_eon']

DiagFields(
    every = 100,
        fields = list_fields
)

DiagScalar(every = 10, vars=['Uelm','Ukin_eon','Utot','Uexp'])

                                                                                                                                                                 


```

## Steps to reproduce the problem

If relevant, provide a step-by-step guide

## Parameters

- Smilei version 4.5
- Input file ?
- Commands or script used to run the faulty simulation ?
- Computing resources
  - type of computer
  - OS
  - C++ compiler (to get some information `g++ --version`)
  - MPI version (`mpic++ --version`, `mpic++ -show`)
  - HDF5 version (`h5cc --version`)
  - Python version (`python --version`)
  - ...

**Comment by jderouillat** [comment]
Hi,  
Could you test the branch `prescribed_fields` ? We find an inconsistency in the algorithm.
Regards

Julien

**Comment by raghavi-a** [comment]
> Hi,
> Could you test the branch `prescribed_fields` ? We find an inconsistency in the algorithm.
> Regards
> 
> Julien

Dear Julien,
thank you very much for your quick reply, but I don't understand how to use this branch. May you let me know?
Sincerely,
Afzal

**Comment by mccoys** [comment]
@raghavi-a how did you get smilei ? Did you clone the repository or did you download the zip ?

* If you cloned the repository, use the commands
```bash
git checkout prescribed_fields
git pull
```

* If you downloaded the zip, you can find the new branch here : https://github.com/SmileiPIC/Smilei/archive/prescribed_fields.zip

**Comment by jderouillat** [comment]
Hi Afzal,
Do you succeed to run the `prescribed_fields` branch ? With the expected behavior ?
In case, we'll integrate it in the main branch.
Regards

Julien

**Comment by raghavi-a** [comment]
Dear Julien,I replaced all containing of my smilei folder with the ones of prescribed-fields branch and then tested again my code but it didn't get the desired results. Am I right with using the prescribed-field branch?Sincerely yours,Afzal
    On Friday, September 11, 2020, 11:44:02 AM GMT+4:30, jderouillat <notifications@github.com> wrote:  
 
 


Hi Afzal,
Do you succeed to run the prescribed_fields branch ? With the expected behavior ?
In case, we'll integrate it in the main branch.
Regards

Julien

**Comment by raghavi-a** [comment]
Dear Julien,
I replaced all containing of smilei folder with the ones of prescribed-fields branch and then tested again my code. But it didn't get the desired results. Am I right with using the prescribed-field branch?
Sincerely,
Afzal

**Comment by jderouillat** [comment]
Just to be sure, did you recompile the new version of the code ? Can you send me the output logs of your last run ?

**Comment by raghavi-a** [comment]
Yes I did. This is the profile of the last run:
[profil.txt](https://github.com/SmileiPIC/Smilei/files/5249073/profil.txt)
and here is the electric field of laser pulse, with and without prescribed magnetic field
![Ey_with_prescribed field](https://user-images.githubusercontent.com/70030783/93658890-e090bc00-fa54-11ea-9377-0e0a239aa823.jpeg)
![Ey_without_prescribed filed](https://user-images.githubusercontent.com/70030783/93658892-ebe3e780-fa54-11ea-8ee8-da720ff49cbe.jpeg)

![Bz_prescribed_magnetic_field](https://user-images.githubusercontent.com/70030783/93658895-f4d4b900-fa54-11ea-9c1c-145bbf306df7.png)
Sincerely yours,
Afzal

**Comment by mccoys** [comment]
@raghavi-a The last version in "master" branch should solve your problem. Can you check ?

**Comment by raghavi-a** [comment]
Yes it works. Thank you very much dear mccoys!
