### ISSUE TITLE
Corners in Probe

### ISSUE THREAD

**Issue by Tissot11** [SmileiPIC/Smilei#289]
I'm having issue with defining the _corners_ for the _Probe_. Since _Probe_ is much faster than _Fields_, I wanted to use it. I attach the namelist and the stdout file. I also write the block for _Probe_

_
DiagProbe(
    every = 10,
    origin = [0.0],
    corners = [[0.99*Lsim]],
    number = [Nx],
    fields = ['Rho_eon1', 'Rho_eon2', 'Rho_ion1', 'Rho_ion2', 'Ex', 'Bz']
)
_

if I use it in this configuration, simulation fails saying that there _Probe has no points in the box_ (see the stdout file). However, setting the _Nx=1000_ works fine. If I used _corners=Lsim_ then strangely it will make field decay to zero at the right boundary. Intuitively, I would have thought that _corners=Lsim_ should be in  simulation box as well. 

[namelist.txt](https://github.com/SmileiPIC/Smilei/files/5149435/namelist.txt)

[stdout.8722846.txt](https://github.com/SmileiPIC/Smilei/files/5149440/stdout.8722846.txt)

**Comment by mccoys** [comment]
You have written :
```python
Nx = numpy.int(Lsim/dx),
```
Be careful of the comma at the end. Python interprets this as a tuple, not an integer.

**Comment by Tissot11** [comment]
Thanks. I guess I put it, because sometimes due to the lack of comma, python complains too. The other question, is using _corners=Lsim_ advised or using _0.99*Lsim_ is recommended. _Probes_ don't affect the interaction?

**Comment by mccoys** [comment]
Probes do not affect the interaction. They are a diagnostic. You should do as you find most appropriate
