### ISSUE TITLE
External field replaced by Poisson

### ISSUE THREAD

**Issue by xsgeng** [SmileiPIC/Smilei#290]
## Description

The external field applied at t=0 is replaced by the Poisson result.

## Steps to reproduce the problem

1. Use periodical boundaries and apply an external field `Ex = -0.1`.
2. Put an electron bunch in the simulation box and solve the non-relativistic Poisson.
3. The field at t=0 is the result of the Poisson solution and contains no information about the external field.

## Possible solution

I put `vecPatches.applyExternalFields()` after the Poisson solver and it fixes the problem in 2D geometry.
I am not sure if it will cause other effects.

## Parameters

- Smilei version 17ed5724f49cabc541437bce0eed8e6ac25e7ed7
- Commands or script used to run the faulty simulation ?
- Computing resources
  - C++ compiler: 4.8.5 20150623 (Red Hat 4.8.5-16)
  - MPI version: mpiicpc for the Intel(R) MPI Library 2019 Update 5 for Linux
  - Python version: Python 3.6.9 :: Intel Corporation

**Comment by jderouillat** [comment]
Hi,  
This problem has been fixed today in 6df05a72c236d2ee5de2b7de72401f13b2f73dd6.  
Regards

Julien
