### ISSUE TITLE
Initialising a magnetic piston

### ISSUE THREAD

**Issue by Tissot11** [SmileiPIC/Smilei#292]
I have a question regarding using _Antenna_ or _PrescribedField_ blocks. I'm interested in launching a magnetic piston that reflects the particle like reflecting boundary condition and move in the simulation box. It appears to me _PrescribedField_ is a good option but does _Antenna_ block also do the same thing?  Also these blocks work well with the moving window?

**Comment by mccoys** [comment]
PrescribedField is not a physical thing. It is a field imposed on the system that does not satisfy Maxwell's equation. Use at your own risk. 

An Antenna is just a current. Not a field. It will surely create a field indirectly, but nobody has tried to use it for a piston as far as I know.

Both options will use the usual coordinates in accordance with the moving window.

**Comment by Tissot11** [comment]
I have come across a paper where they used an _Antenna_ type current to generate an indirect field to launch a piston. I attach that paper here. Please have a look and let me know if _Antenna_ in _SMILEI_ in principle can do this.

[Self-consistent study of a perpendicular collisionless and nonresistive shock-PhysFluids_30_1767.pdf](https://github.com/SmileiPIC/Smilei/files/5182606/Self-consistent.study.of.a.perpendicular.collisionless.and.nonresistive.shock-PhysFluids_30_1767.pdf)

For _PrescribeField_, in principle I can launch a magnetic piston and reflect particles like the _PartWall_ does in _SMILEI_. Since it's not used in Maxwell equation, it won't have any energy depletion. Just out of curiosity, can _PartWall_ be given a velocity?

Is it possible that I can create an infinitely long plasma (in _1D_) by using _xplateau =1e5*Lsim_, where _Lsim_ is the length of the simulation box, in _trapezoidal_ function and then use _movingWindow_ to have a constant plasma (with zero drift) coming from the right as the _movingWindow_ moves to the right. In principle this would amount to injecting a plasma with zero drift from right in the _movingWindow_. Or it's not possible because of the _boundaryconditions_ used with _movingWindow_?

**Comment by mccoys** [comment]
Thank you for sharing this article, but I don't have time to read it, and it is not the purpose of issues. If you want to know what is possible, just ask precisely what you need to do (not the physical scenario, but the technical principle).

PartWall cannot have a velocity. Look at the doc.

A moving window just looks at a different portion of the plasma as time advances. You can have a plasma that is outside of the box. It will be created as the window advances.

**Comment by Tissot11** [comment]
So what I need to do to generate a propagating magnetic field (_+x_ direction) with either _Antenna_ or _PrescribedField_ block? For the _Antenna_ block, I can define a current and modulate with some frequency, so this should a propagating electromagnetic field?

Similarly, can I use built-in _laser_ to launch a piston in _PrescribedField_?

**Comment by MickaelGrech** [comment]
The Antenna module in Smilei was actually built to do exactly this.
The piston technique with the antenna is already used in Smilei by Philippe Savoini, who is a long-time collaborator of one of the author of the paper you mentioned. As far as I remember, he uses this technique to drive a collisionless shock similar to the Earth bow shock.
On our side (the dev-team) we can help you on technical issues with the code, it is however not possible to support you further on the physics aspect. I can only encourage you to contact either Savoini or Lambège who will maybe be help you.

**Comment by Tissot11** [comment]
Thanks for the answer. I understand and I can work out physics issue by myself. I wanted to just confirm if I have indeed understood  the _Antenna_ block correctly.

**Comment by MickaelGrech** [comment]
Ok, so to be clear on this side:
- an Antenna corresponds to a user-defined current density that depends on both space and time and act as a source term for the Maxwell's equations, it can be used to generate electromagnetic fields in the simulation box. Not that for this to work the Antenna needs to be defined in the box (I say this because you mentioned the moving window).
- a PrescribedField is an electric or magnetic field defined by the user as a function of both time and space and that is added to the other electromagnetic field of the simulation (those obtained by solving the Maxwell's eqs). As such, it has to be handle carefully and I would actually not use it to drive a piston.
- a Laser (in Smilei) is a boundary condition on the electromagnetic field. It can do something quite similar to the Antenna but will work only at the boundary of the simulation. In the case you use the moving window, this will not work however as lasers are turned of when the moving window starts (way too difficult to handle otherwise).

**Comment by Tissot11** [comment]
Thanks for these insights! This is indeed helpful. I'll try to generate a piston by other methods. I'll post in another thread some questions about the _ParticleInjector_ block that I had raised in another thread. Please have a look and if you can give some hints about what is the problem, this will indeed be great.
