### ISSUE TITLE
[Python] exception:error in the namelist: can not define 'position initialization' in block 'species'

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#294]
How to remove this error ? in which block we can define position initialization for the charge particle?
![Error](https://user-images.githubusercontent.com/67734147/92917108-123acf00-f426-11ea-932b-19de2aa1e181.JPG)

**Comment by mccoys** [comment]
You have a capital letter. Be careful :)

**Comment by Sanjeev273** [comment]
Thank you so much
