### ISSUE TITLE
[error](0) src/Diagnostic/HistogramFactory.h:106 (creat) Diagnostic particles #0: axis #0 mustbe a list

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#295]
I am getting the following error: mentioned in the scren shot attached here. also the script attached here. please help me how to resolve it. 
![error](https://user-images.githubusercontent.com/67734147/92990500-e9254780-f4d4-11ea-8de9-a230277ceea1.JPG)
![error](https://user-images.githubusercontent.com/67734147/92990515-035f2580-f4d5-11ea-831f-c776b242a7d5.JPG)

**Comment by Sanjeev273** [comment]
spell mistake

**Comment by mccoys** [comment]
The error is very clear. The axis must be a list. Have you followed the documentation?  Do you know what is a python list?

**Comment by Sanjeev273** [comment]
> 
> 
> The error is very clear. The axis must be a list. Have you followed the documentation? Do you know what is a python list?

@mccoys Thank you for replying me. I am new to the smilei and Pythan also. Can you guide me about the documentation and pythan list. please send me the link, where I can follow the instruction. Thanks 1

**Comment by mccoys** [comment]
This is the link to the doc
https://smileipic.github.io/Smilei/namelist.html#species
