### ISSUE TITLE
Why "DiagScalar(" is invalid syntax error ?

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#296]
I am a getting a strange error: (invalid syntax:  "DiagScalar(\n))".  A screen shot for the error msg and script attached here. How to remove this error? Thanks ! 

![error](https://user-images.githubusercontent.com/67734147/93018146-895a9980-f5c5-11ea-8fc0-8c4b3a67bb35.JPG)
![script](https://user-images.githubusercontent.com/67734147/93018147-8a8bc680-f5c5-11ea-8875-c31fc8343f9b.JPG)

**Comment by mccoys** [comment]
You forgot a comma. Please be more careful and try to solve your mistakes by yourself!!! We cannot always check your errors all the time.

**Comment by Sanjeev273** [comment]
> 
> 
> You forgot a comma. Please be more careful and try to solve your mistakes by yourself!!! We cannot always check your errors all the time.
Thank you for reply me. its not a problem of comma. with its still not working.

**Comment by MickaelGrech** [comment]
Check how you define Ukin(elm)_inj_mvw.
I think you have a capital letter in the "inJ".

**Comment by Sanjeev273** [comment]
> Check how you define Ukin(elm)_inj_mvw.
> I think you have a capital letter in the "inJ".
Therror is in the line: "DiagScalar (" not the other lines. I have checked all

**Comment by MickaelGrech** [comment]
Ukin_inj_mvw and Uelm_inj_mvw are in DiagScalar().
Also, do not include screenshot, it is much better to attach your input file as .txt file.

**Comment by Sanjeev273** [comment]
> 
> 
> Ukin_inj_mvw and Uelm_inj_mvw are in DiagScalar().
> Also, do not include screenshot, it is much better to attach your input file as .txt file.

Please find the attached file here
[ActivePlasmaBeamDump_2D.txt](https://github.com/SmileiPIC/Smilei/files/5214622/ActivePlasmaBeamDump_2D.txt)

**Comment by Sanjeev273** [comment]
Thanks Problem solved.
