### ISSUE TITLE
Error in runing same script on two pc. 

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#299]
Dear all,
The script is running in my local pc successfully. But if I am running the same script on HPC cluster remotely . There is an Error: "[Python] SyntaxError: ('invalid syntax', ('<string>', 2, 1, '/opt/apps/apps/intel-18.0/smilei/4.5/benchmarks/ActiveBeamPlasmaDumping.py\n'))".

I checked everything is fine in the script. The script is attached here with. Please help me to resolve the isue ?

[ActivePlasma.txt](https://github.com/SmileiPIC/Smilei/files/5245370/ActivePlasma.txt)

**Comment by iltommi** [comment]
This doesn't seem to be related with smilei but rather with the cluster job submission queue. 
Could you check that you can run any code at all on the cluster? 
Could you ask administrator/support for help in submitting the job?

**Comment by Sanjeev273** [comment]
the  other script which was already in the cluster folder, is running succesfully. but this one is getting error.

**Comment by iltommi** [comment]
Could you paste here the whole error and output?

**Comment by Sanjeev273** [comment]
output:
                   _            _
  ___           _  | |        _  \ \   Version : v-3a7ca3b4
 / __|  _ __   (_) | |  ___  (_)  | |   
 \__ \ | '  \   _  | | / -_)  _   | |
 |___/ |_|_|_| |_| |_| \___| |_|  | |  
                                 /_/    
 
 

 Reading the simulation parameters
 --------------------------------------------------------------------------------
 HDF5 version 1.10.5
	 Python version 2.7.5
	 Parsing pyinit.py
	 Parsing v-3a7ca3b4
	 Parsing pyprofiles.py
	 Parsing 2
	 Parsing /opt/apps/apps/intel-18.0/smilei/4.5/benchmarks/ActiveBeamPlasmaDumping.py
	 [Python] SyntaxError: ('invalid syntax', ('<string>', 2, 1, '/opt/apps/apps/intel-18.0/smilei/4.5/benchmarks/ActiveBeamPlasmaDumping.py\n'))
	[ERROR](0) src/Params/Params.cpp:1250 (runScript) error parsing /opt/apps/apps/intel-18.0/smilei/4.5/benchmarks/ActiveBeamPlasmaDumping.py

**Comment by Sanjeev273** [comment]
the error is: 
[node406.pri.csf3.alces.network:03667] pml_ucx.c:285  Error: UCP worker does not support MPI_THREAD_MULTIPLE

**Comment by Sanjeev273** [comment]
> 
> 
> Could you paste here the whole error and output?

Error: 
[node406.pri.csf3.alces.network:03667] pml_ucx.c:285  Error: UCP worker does not support MPI_THREAD_MULTIPLE

**Comment by iltommi** [comment]
It seems to me that the version running on the cluster has not been updated, it seems to run the 3a7ca3b4 which is of may 11th.

**Comment by jderouillat** [comment]
Hi,
There is a compile mode of Smilei without MPI_THREAD_MULTIPLE using `make clean ; make config=no_mpi_tm`.

Julien

**Comment by Sanjeev273** [comment]
> 
> 
> Hi,
> There is a compile mode of Smilei without MPI_THREAD_MULTIPLE using `make clean ; make config=no_mpi_tm`.
> 
> Julien
Thanks !

MY script to submit the job on cluster is as follows: 

#!/bin/bash --login
#$-cwd
#$-pe smp.pe 2
#$ -l short
module load apps/intel-18.0/smilei/4.5

smilei $NSLOTS $SMILEIDIR/benchmarks/tst2d_00_em_propagation.py

Can I add these command to into the job script for submission of file ?
