### ISSUE TITLE
[Python] ImportError: No module named happi

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#300]
I am trying to plot the post simulation results. 

import happi
S=happi.Open("/mnt/iusers01/fatpou01/phy01/v55735sk/scratch/SIM/Fields0.h5")
ne=S.Fields0(0, field = "-Rho_electron", labelb= "ne")
np = S.Fields0( 0, field= "Rho_proton", label = "np")
happi.multiPlot(ne, np, saveAs= " ./dens.png" )
raw_input() 

The error is as follows in outputfile:

                   _            _
  ___           _  | |        _  \ \   Version : v-3a7ca3b4
 / __|  _ __   (_) | |  ___  (_)  | |   
 \__ \ | '  \   _  | | / -_)  _   | |
 |___/ |_|_|_| |_| |_| \___| |_|  | |  
                                 /_/    
 
 

 Reading the simulation parameters
 --------------------------------------------------------------------------------
 HDF5 version 1.10.5
	 Python version 2.7.5
	 Parsing pyinit.py
	 Parsing v-3a7ca3b4
	 Parsing pyprofiles.py
	 Parsing 2
	 Parsing /mnt/iusers01/fatpou01/phy01/v55735sk/scratch/SIM/density.py
	 [Python] ImportError: No module named happi
	[ERROR](0) src/Params/Params.cpp:1250 (runScript) error parsing /mnt/iusers01/fatpou01/phy01/v55735sk/scratch/SIM/density.py

How to solve this issue? please help me.

**Comment by iltommi** [comment]
According to the doc (https://smileipic.github.io/Smilei/post-processing.html) in `happi.Open` takes a directory not a `.h5`

Change this line

```
S=happi.Open("/mnt/iusers01/fatpou01/phy01/v55735sk/scratch/SIM/Fields0.h5")
```

with
```
S=happi.Open("/mnt/iusers01/fatpou01/phy01/v55735sk/scratch/SIM")
```

**Comment by iltommi** [comment]
I just realized you are trying to run a `smilei` simulation with `happi` commands.
You don't need. 

Once you do a  `make happi`, the module `happi` should be available in Python

**Comment by mccoys** [comment]
`happi` is for **post-processing**. It should not be inside a simulation.

**Comment by Sanjeev273** [comment]
This is my scrip: 

import happi
S = happi.Open("/mnt/iusers01/fatpou01/phy01/v55735sk/scratch/SIM")
ne = S . Field(0, field = "-Rho_electron", labelb= "ne")
np = S . Field( 0, field= "Rho_proton", label = "np")
happi.multiPlot(ne, np, saveAs= " ./dens.png" )
raw_input()

the submitted job script is 

#!/bin/bash --login
#$-cwd
#$-pe smp.pe 2

module load apps/python/pip/19.2.3

python $NSLOTS /mnt/iusers01/fatpou01/phy01/v55735sk/scratch/SIM/density.py


The error is: 
python: can't open file '2': [Errno 2] No such file or directory

**Comment by iltommi** [comment]
this script is not meant to run in parallel.

python is complaining about the parameter `$NSLOTS` please ask to your sysadmin/helpdesk on how to postprocess simulations
