### ISSUE TITLE
Moving window and the right boundary

### ISSUE THREAD

**Issue by Tissot11** [SmileiPIC/Smilei#301]
## Description

I see something strange happening at the right boundary when I use _movingWindow_ in Smilei.  I initialise an infinite plasma extending to the right with some external field components. I was expecting plasma to enter smoothly from the right when the window starts moving from the left. I see a spike forming up at the right boundary, which I may not understand physically. I don't know if it is connected with the issue with reflection from the right boundary in #293. I attach the _Namelist_ here

[Piston6.py.txt](https://github.com/SmileiPIC/Smilei/files/5255824/Piston6.py.txt)

I also attach two snapshots of the electron density. One can see that a spike is developing close to the right boundary, which one would not have expected since the infinite stationary plasma to supposed to enter from the right. The value going to zero at the right boundary is probably connected to _Probes_ diagnostic but it should not affect the interaction. Please have a look.

![elecDens](https://user-images.githubusercontent.com/31315017/93776995-7f1f4780-fc24-11ea-9987-ea0f43b54b25.png)
![Elecdens1](https://user-images.githubusercontent.com/31315017/93776997-7f1f4780-fc24-11ea-9d16-269098dc2b0c.png)

**Comment by Tissot11** [comment]
I can see that it appears at a time when the _movingWindow_ has traveled distance equal to the _xvacuum_ of the density but the piston is still behind due to _movingWindow_. I attach figures to demonstrate this. I need to do more tests but I'm getting curious if it has to do anything with the right boundary?

![Alldens1](https://user-images.githubusercontent.com/31315017/93786381-8a2ba500-fc2f-11ea-9111-860b71916691.png)
![Alldens2](https://user-images.githubusercontent.com/31315017/93786383-8ac43b80-fc2f-11ea-8074-8ddd607fc96a.png)
![Alldens](https://user-images.githubusercontent.com/31315017/93786385-8b5cd200-fc2f-11ea-8814-6edcb7d569b3.png)

**Comment by Tissot11** [comment]
So Now I removed the piston and used plasma everywhere in the simulation box. Again I see the same spike at the same time. I attach the _Namelist_  and some shots of the density. Please have a look.

[Piston9.py.txt](https://github.com/SmileiPIC/Smilei/files/5259395/Piston9.py.txt)
![Dens1](https://user-images.githubusercontent.com/31315017/93847958-b20b1f00-fca8-11ea-950a-93364fba1fba.png)
![Dens2](https://user-images.githubusercontent.com/31315017/93847960-b2a3b580-fca8-11ea-81a6-35eed775906b.png)

**Comment by mccoys** [comment]
Possibly, there is something missing for movingWindow and external fields. I am not sure we have considered that possibility. And there could be some missing field initialization as the window moves.

**Comment by mccoys** [comment]
Ok actually you have a problem of escaping electrons. They are too hot and escape the boundary. This makes a density jump when the window moves. Either choose a smaller temperature or a faster window. This is true in general: the window must be faster than traveling particles.

**Comment by Tissot11** [comment]
But the thermal velocity of electrons in my case is _0.02c_ and the moving window velocity is _0.15c_ which is a factor of 7 larger than the thermal velocity of electrons. So I'm not sure if your explanation is actually correct.

**Comment by mccoys** [comment]
Try it.

If you only have a few electrons escaping, this could be enough problem.

**Comment by Tissot11** [comment]
I can try it but I have a physical situation which necessitates using parameters like these. So this means that I can't use _movingWindow_ with these parameters.

**Comment by mccoys** [comment]
Indeed. Or you could try different boundary conditions ... but I don't know if there would be other problems.

**Comment by Tissot11** [comment]
But with _movingWindow_ only _remove_ boundary condition works? This is the message I got when I tried other boundary conditions.

**Comment by mccoys** [comment]
@beck-llr Do you know why movingWindow forces "remove" conditions on xmax ? I understand for xmin, but not for xmax.

**Comment by Tissot11** [comment]
> Indeed. Or you could try different boundary conditions ... but I don't know if there would be other problems.

I just tried with _velocity_x = 0.5,_keeping other parameters same, so the electron thermal velocity is 25 times slower than moving window velocity. I still see spike but it's now shifted in time and it appears later. Does this mean that for higher velocity for example _velocity_x = 0.99, it will only be shifted in time and one runs this simulation long enough, then it might show up again? For _vth=0.02 c_ what in your opinion should __velocity_x_ be to overcome this issue?

![Dens](https://user-images.githubusercontent.com/31315017/93900314-83fffc00-fcf5-11ea-90a8-6736d7106c5f.png)

Choosing _thermalize_ for the _xmax_ failed the start of the simulation saying that _remove_ is mandatory for _movingWindow_.

**Comment by Z10Frank** [comment]
Hello,
in LWFA simulations I have seen that density spike on the right border, yet it does not seem to influence the physics I study inside the moving window. The spike may come from diags, or projection at the border, I have not investigated it thoroughly. 

To be sure that the physics is not disturbed by the moving window, it is necessary to avoid the arrival of phenomena on the right border, or you'll see unexpected results. I am not even sure that Silver-Müller conditions could work properly on the right border with a moving window, so be sure that what you are simulating does not arrive there. The hypothesis of the moving window is an unperturbed plasma (if a large plasma constitutes your target) filling a new patch on the right side, shifting on the left all the patches and cutting a patch on the left side. So, the longer is your patch along the x direction, the farther your phenomena should stay from the right border. For this reason, with a moving window I try to reduce as much as possible the length of a patch along the x direction.

To avoid that something arrives to the right border, choose the window long enough in the x direction and choose appropriately the moving window speed and the moment when it starts moving. If these requirements are met, your plasma at the right border will stay unperturbed and the moving window will not influence it even if you will keep seeing that spike.

I hope these recommendations can help.

**Comment by Tissot11** [comment]
Thanks for your tips!
