### ISSUE TITLE
Thermal boundary velocity

### ISSUE THREAD

**Issue by Tissot11** [SmileiPIC/Smilei#302]
I have a question regarding the _thermal_boundary_velocity_. What it physically describes? If I define the temperature of _thermal boundary_ then I can inject back the particles back into the simulation from this boundary and it should have temperature sampled from a distribution function whose temperature I have provided. But then what is role of the _thermal_boundary_velocity_? Does it help in defining the drifts in other directions since the _thermal_boundary_temperature_ accepts only one argument (as mentioned in the documentation)? A clarification will be helpful.

**Comment by mccoys** [comment]
I thought the doc was clear:

> A list of floats representing the components of the drift velocity of the thermal boundaries (those set to "thermalize" in boundary_conditions).

A temperature does not define a drift.

**Comment by Tissot11** [comment]
What is confusing in this description is drift velocity of thermal boundaries? To put it in another way do you mean that this _thermal_boundary_velocity_ represents the drift velocity of plasma species that is to be injected back into the simulation box? So if I only _thermalize_ plasma electrons which have zero drift velocity then I put _thermal_boundary_velocity=0_?

Theoretically, a drift can be used to define temperature in that particular direction.

**Comment by mccoys** [comment]
A drift velocity does **never** represent a temperature. In all textbooks, *drift* means average velocity added to the overall distribution. If you don't want particles to drift, then put it to 0 indeed.

The only thing I agree is that the formulation "drift velocity of the thermal boundaries" is somewhat slightly misleading. We could replace by "drift velocity of particles after encountering the thermal boundaries". Is that clearer ?

**Comment by Tissot11** [comment]
> A drift velocity does **never** represent a temperature. In all textbooks, _drift_ means average velocity added to the overall distribution. If you don't want particles to drift, then put it to 0 indeed.

I think you have misunderstood me. Of course a drift doesn't define temperature. But in some cases, it maybe needed to calculate temperature in a particular direction.

> 
> The only thing I agree is that the formulation "drift velocity of the thermal boundaries" is somewhat slightly misleading. We could replace by "drift velocity of particles after encountering the thermal boundaries". Is that clearer ?

Yeah, this would be better. Before I thought the documentation meant the boundary itself moves, that's why I needed to clarify.

As stated in the documentation, currently Smilei accepts only one argument for _thermal_boundary_temperature_. So if one wants to have anisotropic temperature distributions of the boundaries, (for example in 2D simulations) it won't work as of now?

**Comment by mccoys** [comment]
> if one wants to have anisotropic temperature distributions of the boundaries, (for example in 2D simulations) it won't work as of now?

correct
