### ISSUE TITLE
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#303]
I am getting the error in output file. Anyone have the idea about this error please help.

[node734.pri.csf3.alces.network:138176] pml_ucx.c:285  Error: UCP worker does not support MPI_THREAD_MULTIPLE
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: H5F.c line 444 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1567 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file

**Comment by iltommi** [comment]
From what you've written, we can't even figure out if this is about `smilei` or `happi` or neither of the two.
Could you please elaborate a bit more?

**Comment by Sanjeev273** [comment]
> 
> 
> From what you've written, we can't even figure out if this is about `smilei` or `happi` or neither of the two.
> Could you please elaborate a bit more?

I run the smilei script on HPC cluster. in error file I am getting these error. but simulation didn't interrupt. its completed succesfully. all the output data file is created in directory. when I am trying to open the *.h5 file. it's not open also.  I don't understand What is this error.

**Comment by iltommi** [comment]
Due to these errors, I would be very surprised that the .h5 files are properly written. 
What size do they have?
how do you try to open the *.h5 files? 

About the error is pretty clear: your compiler does not support MPI_THREAD_MULTIPLE. You need to compile smilei with the option `no_mpi_tm` as @jderouillat pointed out in https://github.com/SmileiPIC/Smilei/issues/299#issuecomment-694863552

**Comment by mccoys** [comment]
You have 2 errors that are very clear and that you should search on the web:
* "Error: UCP worker does not support MPI_THREAD_MULTIPLE". This is mentionned in [our webpage](http://www.maisondelasimulation.fr/smilei/installation.html)
* "unable to create file" -> this is a problem on your side. Smilei is not able to create a file (it cannot write data). Ask your system admin why.

I would like to tell you that you keep asking questions that are not issues about Smilei. You are simply not aware of how to run these programs. Please do more research on the web or get help from your system admins. This github page is suppose to address issues or poor documentation about Smilei. We cannot spend much time helping people to learn about computing.

**Comment by Sanjeev273** [comment]
> 
> 
> Due to these errors, I would be very surprised that the .h5 files are properly written.
> What size do they have?
> how do you try to open the *.h5 files?
> 
> About the error is pretty clear: your compiler does not support MPI_THREAD_MULTIPLE. You need to compile smilei with the option `no_mpi_tm` as @jderouillat pointed out in [#299 (comment)](https://github.com/SmileiPIC/Smilei/issues/299#issuecomment-694863552)

* h5 file is 5069 KB. because I run this simulation for very short time (200fs).
I run the script to open it:

import happi
S = happi.Open("/mnt/iusers01/fatpou01/phy01/v55735sk/scratch/SIM")
ne = S.Scalar(0, field = "-Rho_electron", label= "ne")
np = S.Scalar( 0, field= "Rho_proton", label = "np")
happi.multiPlot(ne, np, saveAs= " ./dens.png" )
raw_input()
