### ISSUE TITLE
Charges of species - nb_density does not seem to return a correct value

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#304]
Hi Smilei team,

I try to run a simulation that reads (again sorry) hydrodynamics data in a txt file. It is just in 1D.
For the first time, I read also charges of ions that changes as function of target depth (target of CH : H is always at 1+ but C goes from 0 to 6+).

The simulation gives me an error: Profile `nb_density iZ6`: does not seem to return a correct value

[out.txt](https://github.com/SmileiPIC/Smilei/files/5266887/out.txt)

I am sorry but I cannot find my error since few days... If you have 5min to look at my input please.

[CH1d.txt](https://github.com/SmileiPIC/Smilei/files/5266975/CH1d.txt)

Thanks in advance.
Julien

**Comment by mccoys** [comment]
try to put `print()` statements and check what the function returns

**Comment by juliencelia** [comment]
Thanks. It works.
An error on global charge but I believed simulation runs even if plasma explode...
