### ISSUE TITLE
happi.Open('./') on python3.X

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#306]
I am tying to load the post processing smilei output data through ipython session using the following command: 

import happi
S = happi.Open('/mnt/iusers01/fatpou01/phy01/v55735sk/scratch/SIM') 

and the error msg is: 
AttributeError: module 'happi' has no attribute 'Open'

Can any one help me where is the mistake.

**Comment by mccoys** [comment]
Could you type these commands in ipython and paste the result ?
```python
import happi
dir(happi)
```

**Comment by Sanjeev273** [comment]
> 
> 
> Could you type these commands in ipython and paste the result ?
> 
> ```python
> import happi
> dir(happi)
> ```

there are output : 
Out[5]:
['Client',
 'Device',
 'EntryInfo',
 'HappiItem',
 'OphydItem',
 'SearchResult',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_version',
 'backends',
 'cache',
 'client',
 'containers',
 'device',
 'errors',
 'from_container',
 'item',
 'load_devices',
 'loader',
 'utils']

**Comment by Sanjeev273** [comment]
![happi](https://user-images.githubusercontent.com/67734147/94426052-e426f000-0184-11eb-8d16-33106d616294.JPG)

**Comment by iltommi** [comment]
It doesn't look like this is the module we provide.
Could you check in which directory it is with:
```
import happi
happi.__path__
```

**Comment by Sanjeev273** [comment]
> happi.__path__

![happi2](https://user-images.githubusercontent.com/67734147/94431830-b98d6500-018d-11eb-8452-c3e12e2f9fec.JPG)

**Comment by Sanjeev273** [comment]
> 
> 
> It doesn't look like this is the module we provide.
> Could you check in which directory it is with:
> 
> ```
> import happi
> happi.__path__
> ```
I used the following commands in order to import the happi on remote system:

[v55735sk@hlogin1 [csf3] SIM]$ module load apps/binapps/anaconda3/2020.07
[v55735sk@hlogin1 [csf3] SIM]$ module load tools/env/proxy
[v55735sk@hlogin1 [csf3] SIM]$ module load apps/intel-18.0/smilei/4.5
[v55735sk@hlogin1 [csf3] SIM]$ make -C $SMILEIDIR happi
make: Entering directory `/opt/apps/apps/intel-18.0/smilei/4.5'
Installing /mnt/iusers01/fatpou01/phy01/v55735sk/.local/lib/python3.8/site-packages/smilei.pth
make: Leaving directory `/opt/apps/apps/intel-18.0/smilei/4.5'
[v55735sk@hlogin1 [csf3] SIM]$ ipython
Python 3.8.3 (default, Jul  2 2020, 16:21:59)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import happi

**Comment by iltommi** [comment]
Almost ! 
Could you now give use the result of the command `happi.__path__` or ` print(happi.__path__)` in your ipython ?

This is very strange indeed. I suspect that you have a directory named "happi" in the folder you're running the ipython. In this particular case, python will try to load it as module and will not load the module we provide (which is written in `/mnt/iusers01/fatpou01/phy01/v55735sk/.local/lib/python3.8/site-packages/smilei.pth`)

**Comment by Sanjeev273** [comment]
> 
> 
> Almost !
> Could you now give use the result of the command `happi.__path__` or ` print(happi.__path__)` in your ipython ?
> 
> This is very strange indeed. I suspect that you have a directory named "happi" in the folder you're running the ipython. In this particular case, python will try to load it as module and will not load the module we provide (which is written in `/mnt/iusers01/fatpou01/phy01/v55735sk/.local/lib/python3.8/site-packages/smilei.pth`)

![happi3](https://user-images.githubusercontent.com/67734147/94434510-d330ab80-0191-11eb-847a-6b27cc6c80c1.JPG)

**Comment by iltommi** [comment]
there are 2 underscore on each side of the word path.

**Comment by Sanjeev273** [comment]
> 
> 
> > Almost !
> > Could you now give use the result of the command `happi.__path__` or ` print(happi.__path__)` in your ipython ?
> > This is very strange indeed. I suspect that you have a directory named "happi" in the folder you're running the ipython. In this particular case, python will try to load it as module and will not load the module we provide (which is written in `/mnt/iusers01/fatpou01/phy01/v55735sk/.local/lib/python3.8/site-packages/smilei.pth`)
> 
> ![happi3](https://user-images.githubusercontent.com/67734147/94434510-d330ab80-0191-11eb-847a-6b27cc6c80c1.JPG)
@iltommi Thanks !
![happi4](https://user-images.githubusercontent.com/67734147/94435734-70401400-0193-11eb-9b8d-a17635acb5fa.JPG)

**Comment by Sanjeev273** [comment]
> 
> 
> Almost !
> Could you now give use the result of the command `happi.__path__` or ` print(happi.__path__)` in your ipython ?
> 
> This is very strange indeed. I suspect that you have a directory named "happi" in the folder you're running the ipython. In this particular case, python will try to load it as module and will not load the module we provide (which is written in `/mnt/iusers01/fatpou01/phy01/v55735sk/.local/lib/python3.8/site-packages/smilei.pth`)

your suspection is right. Now what to do to load the correct module of happi ? can you help me please ?

**Comment by iltommi** [comment]
That's easy. Just run it in an folder that does not contain a subfolder named happi.

**Comment by Sanjeev273** [comment]
> 
> 
> That's easy. Just run it in an folder that does not contain a subfolder named happi.

Thanks ! I am runing it  remotely on HPC cluster using my user account. I have access only to this folder. is there any alternative option? or can I remove this folder ? Please suggest me to resolve it?

**Comment by mccoys** [comment]
Make a new folder ?

**Comment by Sanjeev273** [comment]
> 
> 
> It doesn't look like this is the module we provide.
> Could you check in which directory it is with:
> 
> ```
> import happi
> happi.__path__
> ```

What output should be after the command: 'dir(happi)' for the correct module of happi ?

**Comment by iltommi** [comment]
```

In [1]: import happi

In [2]: dir(happi)
Out[2]: 
['Open',
 'Units',
 '_Diagnostics',
 '_Utils',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_core',
 '_os',
 'happi_directory',
 'multiPlot',
 'openNamelist']
```

**Comment by mccoys** [comment]
@Sanjeev273 I am really surprised you have a folder named happi in your home folder. And that this folder is not the correct happi folder. Are you sure you did not make a mistake somewhere ?

**Comment by Sanjeev273** [comment]
> 
> 
> @Sanjeev273 I am really surprised you have a folder named happi in your home folder. And that this folder is not the correct happi folder. Are you sure you did not make a mistake somewhere ?

@mccoys I am new to smilei and python. Maybe I did some mistakes at the time of installation. please help me remove this folder 'happi' from my home folder and how to install correct one?  Thanks !

**Comment by mccoys** [comment]
I am sorry but we cannot take care of everybody who needs help with understanding python. This place is only for discussing about issues about Smilei. Let me simply repeat what you should have done, according to the documentation.
* Download the Smilei folder
* Go into that folder with a command line
* Type `make happi`
Then happi should be available in python.

If you have done something else, it is your work to learn how to fix it. If you have created a folder by mistake, you should learn how to remove a folder.

**Comment by Sanjeev273** [comment]
> 
> 
> ```
> 
> In [1]: import happi
> 
> In [2]: dir(happi)
> Out[2]: 
> ['Open',
>  'Units',
>  '_Diagnostics',
>  '_Utils',
>  '__builtins__',
>  '__cached__',
>  '__doc__',
>  '__file__',
>  '__loader__',
>  '__name__',
>  '__package__',
>  '__path__',
>  '__spec__',
>  '_core',
>  '_os',
>  'happi_directory',
>  'multiPlot',
>  'openNamelist']
> ```

Now I realize my mistake. I used the command to install happi: 'pip install --user happi'
It's create the sub-folder 'happi' in my home folder. Now I uninstalled it and details are as follows:
![happi1](https://user-images.githubusercontent.com/67734147/94668371-db125c00-0307-11eb-8e8a-ab5c8b40955e.JPG)

**Comment by mccoys** [comment]
It should be ok now. Please read the documentation next time.
