### ISSUE TITLE
Change the unit in S.ParticleBinning()

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#310]
Post processing of smilei data, I am trying to plot the data. I am getting the plots in code units. How to change that units into real units ? I used the following command lines: 
eenspectr = S.ParticleBinning(1, timesteps= [ntfrozen, ntstop], data_log = True, label = "electrons")
penspectr = S.ParticleBinning(0, timesteps= [ntfrozen, ntstop], label = "protons")
 happi.multiPlot(eenspectr, penspectr)

A graphs attached here. 

![Capture](https://user-images.githubusercontent.com/67734147/95113559-8a9d6300-073a-11eb-9df9-cd74cfcdc898.JPG)

**Comment by iltommi** [comment]
It's explained here: https://smileipic.github.io/Smilei/namelist.html#reference_angular_frequency_SI

**Comment by Sanjeev273** [comment]
In the command line "happi.Open(results_path='.', show=True, reference_angular_frequency_SI=None, verbose=True)"

What should be the option for "reference_angular_frequency_SI=?", to change the unit of particle number density. 
in my code wrote: "reference_angular_frequency_SI=weight". but it is not working. 

In [9]: S=happi.Open(results_path='/mnt/iusers01/fatpou01/phy01/v55735sk/scratch/SIM',show = True, reference_ang
   ...: ular_frequency_SI=weight, verbose= True)

any help?

**Comment by mccoys** [comment]
Read this: http://www.maisondelasimulation.fr/smilei/namelist.html#reference_angular_frequency_SI
