### ISSUE TITLE
ERROR: you need the 'ffmpeg' software to make movies

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#312]
I am trying to create the movie from Smilei data. but I ma getting the following ERROR: you need the 'ffmpeg' software to make movies. I already installed "ffmpeg". but still getting the error. installed "ffmpeg" details are as follows:
![ffmpeg](https://user-images.githubusercontent.com/67734147/95466512-50b7a100-0974-11eb-8baf-647895aa0d16.JPG)

Can you help me why is this error even sofware is already installed?

**Comment by iltommi** [comment]
you somehow installed a python package named ffmpeg. 
Please be sure you have an **executable** called `ffmpeg` in your PATH. It will be called by `happi` to produce movies.

**Comment by Sanjeev273** [comment]
> 
> 
> you somehow installed a python package named ffmpeg.
> Please be sure you have an **executable** called `ffmpeg` in your PATH. It will be called by `happi` to produce movies.

currently its in my home folder. but happi is in Smilei directory.  is there other way to install correctly ?

**Comment by iltommi** [comment]
Again, as we told you yesterday, **this is not the place to ask help for basic computer usage**. This is a place to report issues related to the Smilei code. We are willing to help, but please read carefully the answers we provide. 

I already told you what you need to do: 

> Please be sure you have an **executable** called `ffmpeg` in your PATH.

**Comment by xxirii** [comment]
Hi @Sanjeev273, if you are using ubuntu or a Debian OS you can install ffmpeg by using the apt-get command:

```
Sudo apt install ffmpeg
```

On a mac you can probably do it with homebrew.

Else have a look online how to install ffmpeg for your os.

**Comment by Sanjeev273** [comment]
> 
> 
> Hi @Sanjeev273, if you are using ubuntu or a Debian OS you can install ffmpeg by using the apt-get command:
> 
> ```
> Sudo apt install ffmpeg
> ```
> 
> On a mac you can probably do it with homebrew.
> 
> Else have a look online how to install ffmpeg for your os.

@xxirii Thanks, I am running it on HPC cluster remotely.

**Comment by xxirii** [comment]
In this case you can try to compile it from the sources. You can possibility get that on their official website. However this can be painful if there are dependencies. Personally, I prefer to generate a list of png at different time steps, then I bring back the files on my computer, then I build the movie using ffmpeg locally.
