### ISSUE TITLE
Define transverse beam waist along each axis

### ISSUE THREAD

**Issue by ajh97** [SmileiPIC/Smilei#313]
For example, for defining a linearly polarised laser pulse that is elliptical in shape (not circularly symmetric) in the transverse direction. Is there any way to be able to define the beam waist of a laser pulse along the y-axis and z-axis separately (laser pulse travelling in x-direction)?

**Comment by mccoys** [comment]
If you know an analytical expression for this, you can input the whole expression. Alternately you could use the LaserOffset feature, but be careful of its numerical cost.

**Comment by Z10Frank** [comment]
@ajh97  Maybe you are looking for an astigmatic gaussian beam (Eq. 1 of https://www.osapublishing.org/ao/abstract.cfm?uri=ao-52-24-6030 for example, after obtaining the real field from the complex amplitude).

In `pyprofiles.py` there are definitions for gaussian beams in different geometries, like `def LaserGaussian3D`. In that file you can define a different gaussian beam with the characteristics you want, inserting the analytical expression.

Alternatively, you can define the spatio-temporal profile of this kind of laser directly in the input namelist, like it is done in the benchmark `tst2d_02_radiation_pressure_acc.py` of the `benchmarks` folder, using the same analytical expression.
