### ISSUE TITLE
Does vectorization work in 1D?

### ISSUE THREAD

**Issue by andsunds** [SmileiPIC/Smilei#314]
I just started experimenting with vectorization. However, I get this error message:
```
 Vectorization: 
 --------------------------------------------------------------------------------
	 Mode: on
	[ERROR](0) src/Params/Params.cpp:1041 (check_consistency) Vectorized algorithms not implemented for this geometry
```
I'm using the standard `1Dcartesian` geometry.

My question is simply if vectorization only works in higher dimensionality? I couldn't find anything about this on your web page.

**Comment by mccoys** [comment]
Indeed, there is no vectorization in 1D yet.

**Comment by andsunds** [comment]
Alright, thank you very much!
