### ISSUE TITLE
Electric field behavior with external magnetic fields 

### ISSUE THREAD

**Issue by ycaophysics** [SmileiPIC/Smilei#315]
## Description
Hi. I've been doing one simulation about Faraday rotation in 2D. I put a large trapezoidal Bx field along with a plasma species. However, the result shows some weird Ez field behavior at the boundary between constant B field and B=0.
I don't think this phenomenon is really physical and I don't know what happened. Thank you  
<img width="863" alt="Screen Shot 2020-10-14 at 6 41 58 PM" src="https://user-images.githubusercontent.com/70364621/95986908-48ba9e00-0e59-11eb-8d34-5f761ad90b80.png">

![image](https://user-images.githubusercontent.com/70364621/95986582-d5b12780-0e58-11eb-9686-9c09839a32e3.png)

(The code is attached here)

[Ref1_Script.py.txt](https://github.com/SmileiPIC/Smilei/files/5378059/Ref1_Script.py.txt)

**Comment by mccoys** [comment]
Why do you say this is nonphysical ? The curl of B contains a term in dBy/dx, so this makes a Ez field.

**Comment by ycaophysics** [comment]
Oh okay that makes sense. But is there anyway to remove that effect? Thanks

**Comment by mccoys** [comment]
No. That would mean make wrong physics.

You should leave the magnetic field continue up to the border of the box.

**Comment by ycaophysics** [comment]
The boundary phenomenon still happens after I removed the trapezoidal condition on y (uniform in transverse direction) and this Ez phenomenon still happens. Should I make the field uniform in all space?
<img width="888" alt="Screen Shot 2020-10-14 at 9 16 16 PM" src="https://user-images.githubusercontent.com/70364621/95994192-8ec82f80-0e62-11eb-8e74-d9a4152bcc5b.png">
 Thanks

**Comment by MickaelGrech** [comment]
Could you try using periodic boundary conditions in the y-direction?
Also, make sure that you don't have a profile in x, your initial field have to be divergence-free.

**Comment by mccoys** [comment]
@ycaophysics are you sure your profile is constant past the limits of the box ? Could you provide your profile code ?

**Comment by ycaophysics** [comment]
Okay I changed to the periodic boundary condition and made the Bx field to all space and that phenomenon disappears (though I still don't know why it happens). Thanks

**Comment by mccoys** [comment]
No. If you remove the y part in the trapezoidal profile, it will put yvacuum to 0. meaning that there will be 0 fields outside of the box. It will thus have non-uniformity at the border.
