### ISSUE TITLE
Run out of memory

### ISSUE THREAD

**Issue by lovecandy126** [SmileiPIC/Smilei#316]
Dear developers,
I run out of memory at  'Running diags at time t = 0 ' with Smilei 4.5 compiled by intel 2018update 3 and hdf5 v1.12.0  gcc4.8.5  python2.7.5 . But no problem with smilei 4.4  .Why?
Thanks!

**Comment by lovecandy126** [comment]
when   Running diags at time t = 0  ,out of memories.

**Comment by lovecandy126** [comment]
> Dear developers,
> I run out of memory with Smilei 4.5 compiled by intel 2018update 3 and hdf5 v1.12.0 gcc4.8.5 . But no problem with smilei 4.4 .Why?
> Thanks!
  python2.7.5

**Comment by mccoys** [comment]
Hi, could you list the diagnostics you were using?

**Comment by lovecandy126** [comment]
> Hi, could you list the diagnostics you were using?
Here is the input:
[ICS.txt](https://github.com/SmileiPIC/Smilei/files/5389740/ICS.txt)

Thanks!

**Comment by mccoys** [comment]
Could you please specify:
* The exact versions of smilei : from the downloads in the website, or from the repository ?
* What is the error exactly ?
* Are you sure you use the exact same namelist ? I can see, for example, that you have commented some lines, but not the corresponding `for` loop, which makes a lot of useless duplicated for DiagProbes

**Comment by mccoys** [comment]
Actually, I might have found something that could be an issue depending on your version of python. You define the number of points in the probe as float numbers, but they should be integers. That might cause undefined behaviour and crash. I will fix this, but could you test whether this is the issue by forcing these numbers to be integers ?
