### ISSUE TITLE
Logcale for ekin in ParticleBinning diagnostic

### ISSUE THREAD

**Issue by Tissot11** [SmileiPIC/Smilei#319]
I tried to save the `ekin` of ion species with and without `logscale ` option. With this block

`DiagParticleBinning(
    name = "ekin_ion",
    deposited_quantity = "weight_ekin",
    every = 10,
    time_average = 1,
    species = ["ion"],
    axes = [
        ["ekin", 0, 10, 1000, "logscale", "edge_inclusive"] ]
)`

I see a blank spectrum 

![ekin_ion_log](https://user-images.githubusercontent.com/31315017/96567675-59d73500-12c7-11eb-8b73-e39d06dfcfc5.png)

While running the same simulation with 

`DiagParticleBinning(
    name = "ekin_ion",
    deposited_quantity = "weight_ekin",
    every = 10,
    time_average = 1,
    species = ["ion"],
    axes = [
        ["ekin", 0, 10, 1000] ]
)`

I get
![ekin_ion](https://user-images.githubusercontent.com/31315017/96567773-78d5c700-12c7-11eb-868e-19f26e7ab3c2.png)

The _x-axis_ in the first figure is by default that comes out on using _happi_. If I try to change the scale then I get the following message 
_Cannot format x ticks (typically happens with log-scale)_

Also note that I have tried both `weight` and `weight_ekin`. I also assume `ekin=\gamma -1` in Smilei?

**Comment by mccoys** [comment]
`axes = [ ["ekin", 0, 10, 1000, "logscale", "edge_inclusive"] ]`

You should not start a log scale at 0. It makes -infinity

**Comment by Tissot11** [comment]
Thanks for the explanation. It works.
