### ISSUE TITLE
question on multiple species in ParticleBinning diagnostics

### ISSUE THREAD

**Issue by aeriforme** [SmileiPIC/Smilei#32]
Hello everyone. 

I just have a small question on ParticleBinning diagnostics. 
Say that in my namelist I put the following block:

DiagParticleBinning(
    deposited_quantity = "weight",
    every = myEvery,
    time_average = 1,
    species = ["electrons","ions"],
    axes = [
        ["ekin", 0, 100, 1000] 
    ]
)

Will the ParticleBinningX.h5 file contain two different spectra for the electron and ion species or will it rather create one only spectrum for both joined species? If the former is the case, how do I access the two spectra? If the latter is the case, then I need to put as many blocks like the one above as many are the species of which I want the spectra, right?  

I tried to look it up in your guide (which by the way is very well done and useful), but I couldn't find this specific information.

Thank you in advance! 

Arianna

**Comment by mccoys** [comment]
Hello

The two species will be combined, with no way to distinguish them. This will be explained in the next release of the documentation (thanks for the catch).

To have separated species, you must have two blocks, but you may use a loop in python:

```python
for s in ["electrons","ions"]:
    DiagParticleBinning(
        deposited_quantity = "weight",
        every = myEvery,
        time_average = 1,
        species = [s],
        axes = [
            ["ekin", 0, 100, 1000]
        ]
    )
```

**Comment by aeriforme** [comment]
Ok, I will do that. 
Thanks for the prompt reply.
