### ISSUE TITLE
refrence frequency w_r

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#320]
If we have both laser frequency and plasma frequency in our simulation, which one we should consider as reference frequency ?

**Comment by beck-llr** [comment]
From the simulation point of view, it does not matter. It is just a matter of how the user looks at the physics at play. It is usually standard to use the laser frequency as reference because most of the time it is what drives the rest. But theoretically the choice is always up to the user.

**Comment by Sanjeev273** [comment]
> 
> 
> From the simulation point of view, it does not matter. It is just a matter of how the user looks at the physics at play. It is usually standard to use the laser frequency as reference because most of the time it is what drives the rest. But theoretically the choice is always up to the user.
Thank you.
