### ISSUE TITLE
How to inject electron bunch to initiate the plasma wake 

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#321]
I want to inject the electron bunch with specific profile in order to generate the plasma wake using following parameter:
1. Beam energy
2. beam total charge
3. beam length
4.beam radius
5. particle density

How to define the these parameter in block? how to inject the particle at specific position and time in to the wake field?

**Comment by MickaelGrech** [comment]
There is something unclear in your message: do you want to generate the wakefield from the particle beam or not.
From your last sentence, I guess not.
So I will answer the question how to initialize a particle beam at a specific position and given time.
To do this, you can create a particle species (with the good density profile, velocity, etc to mimic the different points you mentioned) and have it frozen up to the time at which you want it to start moving using ``time_frozen`` (see [here](https://smileipic.github.io/Smilei/namelist.html#species) for details).

Now concerning the additional details you asked (specifying the beam energy, total charge, length etc) you'll have to work it out yourself. Everything you need is in the doc ;)

**Comment by Sanjeev273** [comment]
> 
> 
> There is something unclear in your message: do you want to generate the wakefield from the particle beam or not.
> From your last sentence, I guess not.
> So I will answer the question how to initialize a particle beam at a specific position and given time.
> To do this, you can create a particle species (with the good density profile, velocity, etc to mimic the different points you mentioned) and have it frozen up to the time at which you want it to start moving using `time_frozen` (see [here](https://smileipic.github.io/Smilei/namelist.html#species) for details).
> 
> Now concerning the additional details you asked (specifying the beam energy, total charge, length etc) you'll have to work it out yourself. Everything you need is in the doc ;)

Thank you for replying me. I want to generate the wake filed using the electron bunch instead of Laser.

**Comment by MickaelGrech** [comment]
Then I would initialize the electron beam at time t=0 outside the plasma (define a new electron species that has the good characteristics, in particular that flows in the good direction with the good velocity, etc).
At first, I would use of ``solve_poisson=False`` (in the ``Main()`` block) to neglect all initial electric fields (make sure that the 2 other species describing the plasma onto which you'll send the electron beam are neutral though!).
Let on, you can try using the relativistic particle solver discussed [here](https://smileipic.github.io/Smilei/relativistic_fields_initialization.html).

**Comment by Sanjeev273** [comment]
> 
> 
> Then I would initialize the electron beam at time t=0 outside the plasma (define a new electron species that has the good characteristics, in particular that flows in the good direction with the good velocity, etc).
> At first, I would use of `solve_poisson=False` (in the `Main()` block) to neglect all initial electric fields (make sure that the 2 other species describing the plasma onto which you'll send the electron beam are neutral though!).
> Let on, you can try using the relativistic particle solver discussed [here](https://smileipic.github.io/Smilei/relativistic_fields_initialization.html).

Thank you so much
