### ISSUE TITLE
MPI_Iprobe issue

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#322]
Hi Smilei team (but I think it will be a @jderouillat problem;)),

On ROME partition, with a 1D simulation, I have now a problem of MPI. The simulation crashes at the first timestep after initialization steps.

Here are the files:

[gsi1d.txt](https://github.com/SmileiPIC/Smilei/files/5444865/gsi1d.txt)
[hydro.txt](https://github.com/SmileiPIC/Smilei/files/5444866/hydro.txt)
[out.txt](https://github.com/SmileiPIC/Smilei/files/5444867/out.txt)
[err.txt](https://github.com/SmileiPIC/Smilei/files/5444868/err.txt)

Thanks in advance for your help.

Julien

**Comment by jderouillat** [comment]
Fix (https://github.com/SmileiPIC/Smilei/commit/9419ec9ef184ee18a922bd787fe46da530f479a4) pushed in the main repository this morning, solved for #307.
