### ISSUE TITLE
MP-LWFA in Smilei

### ISSUE THREAD

**Issue by Sonuphd** [SmileiPIC/Smilei#324]
## The problem and the context

I want to work with MP-LWFA but I am facing a problem with building a code for this. Please suggest any idea.

## The solution

I would like to ...

## Failed attempts

I have tried other things already ...

**Comment by beck-llr** [comment]
I am sorry but this is not a receivable issue.

> Please suggest any idea.

I suggest you finish describing the issue you have with Smilei in more details. If your issue is not related to Smilei you are probably in the wrong place.
