### ISSUE TITLE
Colorbar fontsize in post-processing

### ISSUE THREAD

**Issue by Sonuphd** [SmileiPIC/Smilei#325]
Dear Sir,

Please add font -size details of color-bar in post-processing details of smilei pic.

**Comment by mccoys** [comment]
Why did you close this issue?

**Comment by Sonuphd** [comment]
How to change colorbar font size.

diag = S.Field(0,"Rho",units=["cm^-3","um","fs"],cmap="seismic_r",title_font = {'fontsize': 14, 'fontweight': 'bold', 'fontfamily':'s
    ...: erif', 'color': 'k'}, xlabel_font={'fontsize': 14, 'fontweight': 'bold', 'fontfamily':'serif', 'color': 'k'},ylabel_font={'fontsize':
    ...:  14, 'fontweight': 'bold', 'fontfamily':'serif', 'color': 'k'}, xticklabels_font={'fontsize': 14, 'fontweight': 'bold', 'fontfamily':
    ...: 'serif', 'color': 'k'}, yticklabels_font={'fontsize': 14, 'fontweight': 'bold', 'fontfamily':'serif', 'color': 'k'})

**Comment by mccoys** [comment]
as you said, it is not possible yet

**Comment by mccoys** [comment]
I forgot to indicate that this has been fixed a couple weeks ago. Here is a copy of the new documentation

> For fonts: title_font, xlabel_font, xticklabels_font, ylabel_font, yticklabels_font, colorbar_font
> 
>     These options are dictionnaries that may contain the entries available in matplotlib’s text options, for instance:
> 
>     title_font = {'size': 15, 'weight': 'bold', 'family':'serif', 'color': 'k'}
> 
>
