### ISSUE TITLE
post processing Laser amplitude and electric field profile

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#326]
I am using the following space time profile of laser to regenerate the wake filed.  

```
time_envelope = tgaussian(center=center_laser, fwhm=laser_fwhm)
focus = [focus_laser, Main.grid_length[1]/2., Main.grid_length[2]/2.]
Zr = omega * waist**2/2.
w  = math.sqrt(1./(1.+(focus[0]/Zr)**2))
invWaist2 = (w/waist)**2
coeff = -omega * focus[0] * w**2 / (2.*Zr**2)
def By(y,z,t):
    return 0.
def Bz(y,z,t):
    r2 = (y-focus[1])**2 + (z-focus[2])**2
    omegat = omega*t - coeff*r2
    return a0 * w * math.exp( -invWaist2*r2  ) * time_envelope( omegat/omega ) * math.sin( omegat )
Laser(
    box_side = "xmin",
    space_time_profile = [By, Bz]
)
```

Now I want to see the laser amplitude and field post processing. I already include the parameter for laser diagnostic

```
list_fields = ["Ex","Ey","Ez","Bx","By","Bz","Rho","Jx","Jy","Jz","Env_A_abs","Env_E_abs","Env_Ex_abs"] #all fields

DiagFields(
    every = 100,
    fields = list_fields
)
```

When I plot the data I am getting the value 0 for  Env_A_abs, Env_E_abs, Env_Ex_abs in the plot.  but I am getting the wake filed profile 
Can suggest me what is happing with laser envelope? or there is other way to define laser profile to get envelope profile in the output ?

**Comment by mccoys** [comment]
Have you read this doc ?
http://www.maisondelasimulation.fr/smilei/namelist.html#laser-envelope-model

**Comment by Z10Frank** [comment]
Hello,
you are defining the laser with all the carrier oscillations, its electromagnetic field is evolved through Maxwell's equations and its inteaction with the particles is modeled through the particles J and Lorentz Force. 
Those quantities you are looking at, like `Env_E_abs`, are available only if you model the laser with a `Laser Envelope` model, as described in the documentation page linked by @mccoys in the previous answer (which I recommend to read), so in your case `happi` will not automatically show the envelope of the laser field.

So, either you use a `Laser Envelope` model, but I don't know if it is suited for your simulations (check the documentation), or you can extract the electromagnetic field data on the grid through the `getData()` option for the Fields and the Probes. Afterwards, to retrieve the envelope of this field (provided that it is dominated by the laser field), you need to use the concept of analytic signal.

Here is a Python Script (with an example) to extract the envelope of a high frequency oscillating field:

```
### Test to compute analytic signal of a given input signal

import matplotlib.pyplot as plt
import numpy as np
import math



def analytic_signal(x):
	N=np.size(x)
	if N%2==1:
		print ('works only with signals with even-number of points')
		exit(0)

	y=np.fft.fft(x)
	
	for i in range(0,N):
		if   (i==0):
			y[0] = 0.
		elif (i>=1 and i<(N/2-1)):
			y[i] = 2*y[i]
		elif (i==(N/2)):
			y[i] = y[i]
		elif (i>=(N/2+1)):
			y[i] = 0.
	y=np.fft.ifft(y)
	return y


t = np.linspace(0.,1.,10000)

low_freq = np.ones(np.size(t))+np.sin(np.multiply((2.*math.pi*20),t))
high_freq = np.cos(np.multiply((2.*math.pi*200),t))

x = np.multiply(low_freq,high_freq)

if (np.size(x)%2==1):
	x=x[0:-1]
	t=t[0:-1]

h=analytic_signal(x)
envelope = np.absolute(h)

ax=plt.subplot(111)
plt.plot(t,x,'b',linewidth=3.0,label='A')
plt.plot(t,envelope,'r',linewidth=3.0,label='Absolute value of the envelope of A')
plt.legend()
ax.set_xlim([0., 0.1 ])
plt.show()
```

**Comment by Sanjeev273** [comment]
Hello Francesco Massimo @Z10Frank ,
Thank you so much for explaining in detail. I need the space-time profile in order to simulate the result. I don't think laser envelope model will work in my case. I will try the script you suggested. In this script, x is the input data ?

**Comment by Z10Frank** [comment]
You can define a space-time profile even if you use the `Laser Envelope` model. The suitability of this model to your case depends on what physical phenomena you want to simulate (to know this, again please read the documentation).

My script is only an example. Supposing your laser is propagating in the x direction, you need to use getData for your iteration, finding a matrix E, which represents the field on the grid. The lines (or columns depending on how you defined/transposed the matrix) correspond to the slices along x and along y. If your laser oscillations are along the x direction as I was saying, adapt my script to work in loop for each slice representing a line parallel to the x axis. This way you'll find a matrix with the envelope of the laser.
