### ISSUE TITLE
Font size change during post - processing

### ISSUE THREAD

**Issue by Sonuphd** [SmileiPIC/Smilei#327]
Dear Sir,

Font size properties is not working.

In [1]: import happi                                                            

In [2]: S=happi.Open("/home/sonu/LWFA23")                                       
Loaded simulation '/home/sonu/LWFA23'
Scanning for Scalar diagnostics
Scanning for Field diagnostics
Scanning for Probe diagnostics
Scanning for ParticleBinning diagnostics
Scanning for RadiationSpectrum diagnostics
Scanning for Performance diagnostics
Scanning for Screen diagnostics
Scanning for Tracked particle diagnostics

In [3]: diag=S.Probe(0,"Rho",title_font = {'fontsize': 15, 'fontweight': 'bold', 'fontfamily':'serif', 'color': 'k'})                         

In [4]: diag.plot()                                                                                                                           
Diagnostic is invalid
The following keyword-arguments are unknown: title_font

```
If available, copy-paste faulty code, warnings, errors, etc.
```

## Steps to reproduce the problem

If relevant, provide a step-by-step guide

## Parameters

- Smilei version ?
- Input file ?
- Commands or script used to run the faulty simulation ?
- Computing resources
  - type of computer
  - OS
  - C++ compiler (to get some information `g++ --version`)
  - MPI version (`mpic++ --version`, `mpic++ -show`)
  - HDF5 version (`h5cc --version`)
  - Python version (`python --version`)
  - ...

**Comment by mccoys** [comment]
Please provide your version of smilei

**Comment by Sonuphd** [comment]
(base) sonu@sonu-HP-15-Notebook-PC:~/LWFA117$ mpirun -n 2 ~/Smilei/smilei LWFA.py
                    _            _
  ___           _  | |        _  \ \   Version : v-b5c12a5a
 / __|  _ __   (_) | |  ___  (_)  | |   
 \__ \ | '  \   _  | | / -_)  _   | |
 |___/ |_|_|_| |_| |_| \___| |_|  | |  
                                 /_/    
 
 

 Reading the simulation parameters
 --------------------------------------------------------------------------------
 HDF5 version 1.12.0
	 Python version 2.7.18
	 Parsing pyinit.py
	 Parsing v-b5c12a5a
	 Parsing pyprofiles.py
	 Parsing LWFA.py
	 Parsing pycontrol.py
	 Check for function preprocess()
	 python preprocess function does not exist
	 Calling python _smilei_check
	 Calling python _prepare_checkpoint_dir
	[WARNING] Patches distribution: hilbertian

**Comment by Sonuphd** [comment]
I am using latest version of smilei.

**Comment by mccoys** [comment]
You are not using the latest version, but a version from last July. The documentation you are reading is more recent. Please update your version with that from github.

**Comment by Sonuphd** [comment]
I have updated the latest version of smilei and the problem is solved. Thanks for the suggestion.
