### ISSUE TITLE
Binary collisions, beam thermalization. Possibly wrong charge dependence?

### ISSUE THREAD

**Issue by pordyna** [SmileiPIC/Smilei#328]
## Description

Hi, I'm working currently on a binary-collision algorithm implementation for [`PIConGPU`](https://github.com/ComputationalRadiationPhysics/picongpu) [(collisions PR)](https://github.com/ComputationalRadiationPhysics/picongpu/pull/3416). I'm trying to reproduce your test cases from your [documentation](https://smileipic.github.io/Smilei/collisions.html). Right now, I keep getting different results with the 3rd case of the beam relaxation test (1st and 2nd case with  ion charge equal 1 matches `smilei`) .  I have noticed that in your post-processing script, at the point where the theoretical curve is calculated, the parameter ν_0 depends linearly on the ion charge https://github.com/SmileiPIC/Smilei/blob/1ed1f370b04bc0f94572208d852ab66234d073ac/benchmarks/collisions/beam_relaxation789.py#L76  but in your docs and in the the [NRL Plasma Formulary](https://www.nrl.navy.mil/ppd/sites/www.nrl.navy.mil.ppd/files/pdfs/NRL_Formulary_2019.pdf) (page 31) the ion charge is squared.  

I would assume that it is `PIConGPU` that is generating wrong results here, since it's a new and not very well tested implementation. But weirdly enough, when I draw the theory curve with the ion charge squared it actually matches the `PIConGPU` output quite well. 

Here are the results (black curve is theory):
**`PIConGPU`, ion charge squared:**
![beam_relaxation7_sq_PIC](https://user-images.githubusercontent.com/41141557/98362316-52d15600-202d-11eb-9275-57c74f0a71af.png)
**`smilei`, ion charge squared:**
![beam_relaxation7_sq](https://user-images.githubusercontent.com/41141557/98362319-5369ec80-202d-11eb-96fe-710da30140df.png)
**`smilei`, ion charge not squared, original script:**
![beam_relaxation7_lin](https://user-images.githubusercontent.com/41141557/98362357-6086db80-202d-11eb-96d1-0be1a405d370.png)

 I have probably overlooked something and there is probably a reason for this missing square but if this was a typo then there could be something wrong with `smilei`'s algorithm. 

## Parameters

- Smilei version version 1.8.20
- Input file https://github.com/SmileiPIC/Smilei/blob/master/benchmarks/collisions/beam_relaxation7.py

**Comment by mccoys** [comment]
Thank you for this report. I will look into it. Note that your smilei version 1.8.20 does not exist ! Was this HDF5 version ?

**Comment by mccoys** [comment]
Actually, the variable `density_ion` is not very well named. It is a charge density.
```python
density_ion          = np.double(sim.namelist.Species["ion1"].charge_density)
```
This makes the theoretical `nu0` proportionnal to Z². Does that make sense ?

**Comment by pordyna** [comment]
@mccoys  indeed, it was HDF5.

**Comment by pordyna** [comment]
@mccoys oh yes this makes a lot of sense !

**Comment by pordyna** [comment]
This actually has helped a lot. My `PIConGPU` setup corresponded to setting `denisty=10` for ions in `smilei` and not `charge_denisty=10` as in the benchmark input file. This issue can be closed. Thank you for your fast help!
