### ISSUE TITLE
Please add temporal gaussian pulse train envelope profile

### ISSUE THREAD

**Issue by Sonuphd** [SmileiPIC/Smilei#329]
Dear Sir,

I need to use multiple gaussian envelope laser pulse separated by a plasma period for LWFA.

**Comment by MickaelGrech** [comment]
Dear @Sonuphd, 
Everything you need to create a train of gaussian pulses is already available.
You should check the documentation carefully, in particular this section:  [https://smileipic.github.io/Smilei/namelist.html#lasers](https://smileipic.github.io/Smilei/namelist.html#lasers).
Before opening an issue, please make sure you invest enough time in reading the documentation and/or trying to solve the problem by yourself. 
When reporting an issue, please take the time to fully report your problems/needs. You can also use the [element forum](https://app.element.io/#/room/#Smilei-users:matrix.org) to ask quick question as the one you've posted here.
