### ISSUE TITLE
One dimensional TNSA

### ISSUE THREAD

**Issue by cdavidson-strath** [SmileiPIC/Smilei#330]
Hi there,

I have been using Smilei for the past month, I'm fairly new to it (and PIC codes in general). I have had some good results with 2D simulations but I have come across some trouble with 1D simulations. I have been trying to replicate some results from a paper, PHYSICAL REVIEW E 68, 026408 (2003), on 1D TNSA with aluminium plasma foils. When I run the simulation, the transverse electric field starts out as expected but once it reaches the plasma slab in the centre, it reaches extremely high values. I wouldn't expect them in a TNSA simulation. I have attached the namelist file as a TXT file for reference and a few figures of the effect. Have I got something wrong in the namelist file and/or using the wrong objects for a 1D simulation?

Any help would be very much appreciated. If you need any more info please let me know.

![figure_1](https://user-images.githubusercontent.com/74268364/98728482-78de5980-2391-11eb-9685-53c607daacd5.png)
![figure_2](https://user-images.githubusercontent.com/74268364/98728488-7976f000-2391-11eb-95a1-abe8c5a7b0b2.png)
![figure_3](https://user-images.githubusercontent.com/74268364/98728490-7976f000-2391-11eb-816a-0ea29f3917e5.png)

[laser_wake.txt](https://github.com/SmileiPIC/Smilei/files/5519921/laser_wake.txt)

**Comment by mccoys** [comment]
Hi, Could you paste the output log from this simulation ?

**Comment by Sanjeev273** [comment]
> 
> 
> Hi, Could you paste the output log from this simulation ?
Plz find the attached file here.

[activebeamdumping.sge.o1512088.txt](https://github.com/SmileiPIC/Smilei/files/5520548/activebeamdumping.sge.o1512088.txt)

**Comment by cdavidson-strath** [comment]
Hi, I have attached the output log for this simulation.

[output.txt](https://github.com/SmileiPIC/Smilei/files/5520577/output.txt)

**Comment by mccoys** [comment]
I have not had the chance to look at your case yet, but have you made sure the debye length is somewhat resolved? Do you have the same result increasing resolution?

**Comment by cdavidson-strath** [comment]
I am repeating the simulation with a higher time resolution after discussion with colleagues and your advice @mccoys. We suspect it is a numerical stability issue, I'll let you know the results.

**Comment by mccoys** [comment]
More importantly, check the spatial resolution. Compare it to the debye length

**Comment by cdavidson-strath** [comment]
The problem was my time and spatial resolution resulted in a CFL condition on boundary of stability. Reducing my time resolution got rid of the numerical instability. Thank you all for the help.
