### ISSUE TITLE
Post process for accelerated electron bunch

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#331]
Dear smilei team member,

I am trying to extract the energy of the electron bunch accelerating in laser driven Wakefield in order to get the energy gain or loss. Which diagnostics can provide this information?
I use the following commands to get energy:

S=happi.Open('/mnt/iusers01/fatpou01/phy01/v55735sk/scratch/SIM', reference_angular_frequency_SI= 2.*ma
    ...: th.pi*299792458/0.8e-6)
S.Scalar("Ukin_electronbunch", units = ["MeV/m^3", "fs", "um"]).plot()
![beam](https://user-images.githubusercontent.com/67734147/98728797-dd011d80-2391-11eb-9990-fb3632a89c4a.JPG)

1. How to get the value of kinetic energy density in SI unit?
2. how to get the energy evolution of electron bunch with respect to propagation distance ? 

  @mccoys @Z10Frank

**Comment by Z10Frank** [comment]
1. What do you mean by kinetic energy density?
2. Your accelerated bunch must propagate near the speed of light to be trapped and accelerated by the wave, so if you don't need high accuracy you can just multiply the time by c in your plot and subtract the approximate position where the bunch was injected.

Anyway, I always find easier and more accurate to analyze the extracted bunch through the Track Particle diagnostics. You specify the species from where the bunch will come (the background electrons if self-injection), then you put a filter on those particles to be tracked, e.g. tracking only the particles with px>20 m_e*c. Then, in the postprocessing you can choose the particles to be considered as bunch among those extracted from the Track Particles diagnostics and you can compute quantities like energy, energy spread, emittance, bunch position etc through numpy.

**Comment by Sanjeev273** [comment]
> 
> 
>     1. What do you mean by kinetic energy density?
> 
>     2. Your accelerated bunch must propagate near the speed of light to be trapped and accelerated by the wave, so if you don't need high accuracy you can just multiply the time by c in your plot and subtract the approximate position where the bunch was injected.
> 
> 
> Anyway, I always find easier and more accurate to analyze the extracted bunch through the Track Particle diagnostics. You specify the species from where the bunch will come (the background electrons if self-injection), then you put a filter on those particles to be tracked, e.g. tracking only the particles with px>20 m_e*c. Then, in the postprocessing you can choose the particles to be considered as bunch among those extracted from the Track Particles diagnostics and you can compute quantities like energy, energy spread, emittance, bunch position etc through numpy.
 I use the namelist:

def my_filter(particles):
    return particles.px> 20*me*c
    
DiagTrackParticles(
    species = "electronbunch",
    every = 100,
    filter = my_filter,
    attributes = ["x", "px", "Ex", "py", "Ey"] 
)

for Post process:

track = S.TrackParticles("electronbunch", axes= ["px"], units = ["kg*m/s", "fs", "um", "V/m"]).plot()
![ParticleTrack](https://user-images.githubusercontent.com/67734147/98746384-4cd0d180-23ad-11eb-9989-c79372fa5e2a.JPG)

**Comment by Sanjeev273** [comment]
can you suggest me what's going wrong in the code ?

**Comment by mccoys** [comment]
> how to correct it ?

How to correct what ?

>  can you suggest me what's going wrong in the code ?

What is wrong ? You have to be clearer.
