### ISSUE TITLE
TrackParticle Diagnostic for elctron bunh 

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#332]
Dear smilei team members,

I want to track  the accelerated electrons in laser wake field. The smilei script for the name-list attached here. 
[beamdumping1D.txt](https://github.com/SmileiPIC/Smilei/files/5523775/beamdumping1D.txt)

in my case the initial energy of moving particle is approximate 100MeV. As the simulation runs for the small length (few steps). The tracked particle energy should be near to this value. but  Its look like particle filter not working. can some one help to solve the issue ?

In the post process getting the strange output.
![ParticleTrack](https://user-images.githubusercontent.com/67734147/98808269-bc79a780-2413-11eb-9be2-c1ed17465ac6.JPG)

**Comment by abonatto** [comment]
Dear Sanjeev,

I do not see any issue in this diagnostic. It just shows that the particle energies mostly did not change along the propagated distance. Indeed, after 350 fs, the beam propagated distance is still quite short (approximately 0.1 mm). Depending on your plasma, beam (and laser, if you are trying to set an active plasma beam dump), you may need run it for a longer time to observe appreciable beam energy loss / gain.

**Comment by Sanjeev273** [comment]
> 
> 
> Dear Sanjeev,
> 
> I do not see any issue in this diagnostic. It just shows that the particle energies mostly did not change along the propagated distance. Indeed, after 350 fs, the beam propagated distance is still quite short (approximately 0.1 mm). Depending on your plasma, beam (and laser, if you are trying to set an active plasma beam dump), you may need run it for a longer time to observe appreciable beam energy loss / gain.

Hi Alex ,
Thank you. I tried with double time of this. but was the same. Now I can try with much longer time. I will let you know. Thanks !

**Comment by mccoys** [comment]
@Sanjeev273 please do not add the bug label if you don't know if it is a bug
