### ISSUE TITLE
Problem in restart from dump 

### ISSUE THREAD

**Issue by flavorenti** [SmileiPIC/Smilei#335]
## Background

Hello, I am actually running very heavy 3D simulations on the cluster OCCIGEN with your code (using 512 nodes and ~ 12 billion particles). These simulations are done to study kinetic instabilities (like the lower-hybrid-drift) in steep planetary magnetopauses. Project supervised by Pierre Henri. Past issues on same project: #258 
@MickaelGrech 

## Description Issue

Now, I have a problem in restarting one simulation from checkpoint. My <run3> should restart from the directory <run2_dump>, but when arriving at finalizing MPI in the output file it does show this error (below) for several MPI-processes.
This has probably something to do with how HDF5 reads the dump.
Maybe an easy solution would be to re-do run2 in order to create a new dump (in case something went wrong when dumping run2) but I would like to avoid that since we have limited computational time and each run takes a lot!
```
 finalize MPI
 --------------------------------------------------------------------------------
	 Done initializing diagnostics, antennas, and external fields
	 READING fields and particles for restart
HDF5-DIAG: Error detected in HDF5 (1.8.18) MPI-process 345:
  #000: H5D.c line 358 in H5Dopen2(): not found
    major: Dataset
    minor: Object not found
  #001: H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #002: H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 641 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #004: H5Gloc.c line 385 in H5G_loc_find_cb(): object 'Id' doesn't exist
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.8.18) MPI-process 345:
  #000: H5D.c line 460 in H5Dget_space(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.8.18) MPI-process 345:
  #000: H5S.c line 791 in H5Sget_simple_extent_ndims(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
	[ERROR](0) src/Tools/H5.h:392 (getVect) Reading vector Id is not 1D but -1D
```
## Parameters

- Smilei version v4.4-532-g17ed572-master
- Input file: 
[LHDI_simu2D.txt](https://github.com/SmileiPIC/Smilei/files/5559458/LHDI_simu2D.txt)
- Output file: 
[RUN.txt](https://github.com/SmileiPIC/Smilei/files/5559459/RUN.txt)
- Computing resources: CINES
 - type of computer: OCCIGEN 
 - MPI version: intelmpi/5.1.3.258
 - HDF5 version 1.8.18
 - Python version 2.7.12

Thanks for the help!

**Comment by beck-llr** [comment]
Hi flavorenti.

I see that you are using `dump_step` and not `dump_minute` with which we've had some issues so the dumps should be correct but I'm no expert in that area so I hope someone else can confirm.

I also see this warning in your output: 
```
 [WARNING] Resources allocated 24576 underloaded regarding the total number of patches 16384
```
This means that you use much more threads than patches. Meaning that many of your threads are constantly idle. You are paying twice the price of your simulation (and maybe more).
I suggest trying to restart on a much reduced number of nodes (at least half but I would divide that number by 4) but you must keep the same number of MPI processes. Maybe it will help restarting in better conditions. At least it will save you a lot of computational time.

If you absolutely want (or need) to use the same amount of ressources, you should divide your domain into more (and smaller) patches and restart from `t=0`.

Let us know how that goes.

P.S: Here is the link to the doc about parallelization, have a look at the practical setup section: https://smileipic.github.io/Smilei/parallelization.html

**Comment by iltommi** [comment]
looks like there's a corrupted file. 
Does the previous simulations from which you're restarting shows any error in dumping?

**Comment by flavorenti** [comment]
@beck-llr Thanks for the very nice tip! I've been wondering for a while why that warning was popping up...
Anyways, clearly I'm not an expert in parallelization, and writing the <.slurm> job file each time gives me a very hard time (especially the syntax which is  not unique, and there are always multiple names for the same thing node,process,task or core,thread,cpu etc.). The file I was using so far to launch this simulation is this one:  [job_LHDI.txt](https://github.com/SmileiPIC/Smilei/files/5560723/job_LHDI.txt)

The MPI part was something like:
<#SBATCH --nodes=512                 #number of nodes
#SBATCH --ntasks=1024                #number MPI tasks - should not exceed the number of nodes (openMP is more efficent)
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=12         #number of cores per MPI task = number of cores per node
#SBATCH --threads-per-core=2>

Now, how can I change this part in order to:
1) reduce number of nodes, so solve the threads/patches underload warning ?
2) restart from the past run1 simulation (which had 1024 MPI processes) if possible ?
Thanks in advance (maybe, for the future, a quick example of how to write a <.slurm> basic file in your site could be very very useful!)

-------------------------------------------------

@iltommi The past simulation (run2_dump) from which I'm restarting did not seem to have problem in the dumping -- Anyways I was afraid my problem is due to a corrupted dump... In this case there is no solution, just redo the run2 simulation?

**Comment by mccoys** [comment]
I recommend to have several dumps for each simulation. Depending on the machine, HDF5 libraries might be unstable when you use many nodes.

Concerning the parallelization, there is some introduction to it on the Smilei website. That can clarify some things. Your setup seems alright, but your simulation is too small for that many cores. You have to use less nodes.

**Comment by iltommi** [comment]
@flavorenti I'm afraid that if dump is corrupted, you will not be able to restart from it

**Comment by beck-llr** [comment]
Flavorenti,
I would advise to try the following but please be aware that we are supposed to give support for SMILEI and not for CINES who has its own hotline. We cannot maintain job submission scripts for all computing centers where smilei runs unfortunately. And these scripts might differ from a user to another one.

```
#SBATCH --nodes=256 # divide number of nodes by 2
#SBATCH --ntasks=1024 #keep the same number of MPI in order to be able to restart. Otherwise it is best to have 2 MPI per node
#SBATCH --ntasks-per-node=4 # this number is simply deduced from the previous 4 = 1024/256
#SBATCH --cpus-per-task=6 # I assume you use the haswell partition with 12 cores per socket.
#SBATCH --threads-per-core=1 # We strongly encourage not to use multi threading
```

You will also have to adjust your number of openMP threads to 6 (number of cpus per task).

Say hi to Pierre for me and good luck !

**Comment by flavorenti** [comment]
All right, thanks @iltommi @mccoys So, the only solution is to redo the run that provided the corrupted dump on less nodes.

@beck-llr, thanks a lot for the tips and Pierre says Hi as well.

**Comment by beck-llr** [comment]
Hi
Any progress on that issue ? We are not convinced it is a bug from Smilei. Have you managed to restart from another, not corrupted, dump ?

**Comment by weipengyao** [comment]
Dear Developers,

I also have met with a restart issue, after finalize MPI. 
It says,

```
finalize MPI
 --------------------------------------------------------------------------------
         Done initializing diagnostics, antennas, and external fields
         READING fields and particles for restart
        [ERROR](0) src/Tools/H5.h:576 (vect) Cannot read dataset Bx_val
        [ERROR](0) src/Tools/H5.h:576 (vect) Cannot read dataset Bx_val [ERROR](0) src/Tools/H5.h:576 (vect) Cannot read dataset Bx_val
        [ERROR](0) src/Tools/H5.h:576 (vect) Cannot read dataset Bx_val
        [ERROR](0) src/Tools/H5.h:576 (vect) Cannot read dataset Bx_val
        [ERROR](0) src/Tools/H5.h:576 (vect) Cannot read dataset Bx_val
        [ERROR](0) src/Tools/H5.h:576 (vect) Cannot read dataset Bx_val
        [ERROR](0) src/Tools/H5.h:576 (vect) Cannot read dataset Bx_val
        [ERROR](0) src/Tools/H5.h:576 (vect) Cannot read dataset Bx_val
        [ERROR](0) src/Tools/H5.h:576 (vect) Cannot read dataset Bx_val
        ......
        ===================================================================================
        =   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
        =   RANK 560 PID 192459 RUNNING AT nia0739
        =   KILLED BY SIGNAL: 9 (Killed)
        ===================================================================================
        ......
```

and in the .err file, it gives:

```
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 101:
  #000: H5D.c line 292 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: H5Dint.c line 1384 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #002: H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: H5Gloc.c line 378 in H5G__loc_find_cb(): object 'Bx_val' doesn't exist
    major: Symbol table
    minor: Object not found
......
```

In my namelist, the checkpoints section is:
```
Checkpoints(
    restart_dir = "absolute_directory",
    restart_number = 0,
    dump_minutes = 1400.,
    exit_after_dump = True,
    file_grouping = 40,
    keep_n_dumps = 1,
)
```

Here I used `dump_minutes` instead, but still there's this similar problem. 

Any idea about how to resolve this?

Many thanks and happy holidays.

**Comment by mccoys** [comment]
We have found some potential issue with `dump_minutes`. Until we solve this, can you try `dump_step`?

**Comment by weipengyao** [comment]
@mccoys Thanks for the quick reply. Yes, I will try to use `dump_step` instead for the same model, and I will keep you updated.

**Comment by weipengyao** [comment]
@mccoys I've tried to use `dump_step` for the same model, but still, I got the same error message, i.e. `src/Tools/H5.h:576 (vect) Cannot read dataset Bx_val`, for the same reason.

Any ideas about other reasons that may cause this problem?

**Comment by mccoys** [comment]
Ah, but your previous simulation is faulty because of dump_minutes. It probably created corrupted files. Unfortunately, these cannot be recovered and you have to run your previous simulation with dump_step as well

**Comment by weipengyao** [comment]
@mccoys Thanks for the timely reply, especially during the holidays, and Merry Christmas! 

But, in fact I do re-run the original simulation with `dump_step`, and then when I tried to restart, I got the same error.

**Comment by weipengyao** [comment]
When I check the original output, everything seems fine in the .out file, but I find that in fact there's a series of messages telling me something is wrong:

```
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 6:
  #000: H5D.c line 145 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #001: H5Dint.c line 329 in H5D__create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #002: H5L.c line 1557 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #003: H5L.c line 1798 in H5L__create_real(): can't insert link
    major: Links
    minor: Unable to insert object
  #004: H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #005: H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #006: H5L.c line 1593 in H5L__link_cb(): name already exists
    major: Links
    minor: Object already exists
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 6:
  #000: H5Dio.c line 314 in H5Dwrite(): dset_id is not a dataset ID
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 6:
  #000: H5D.c line 145 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #001: H5Dint.c line 329 in H5D__create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #002: H5L.c line 1557 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #003: H5L.c line 1798 in H5L__create_real(): can't insert link
    major: Links
    minor: Unable to insert object
  #004: H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
#005: H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #006: H5L.c line 1593 in H5L__link_cb(): name already exists
    major: Links
    minor: Object already exists
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 6:
  #000: H5Dio.c line 314 in H5Dwrite(): dset_id is not a dataset ID
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 6:
  #000: H5D.c line 145 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #001: H5Dint.c line 329 in H5D__create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #002: H5L.c line 1557 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #003: H5L.c line 1798 in H5L__create_real(): can't insert link
    major: Links
    minor: Unable to insert object
  #004: H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #005: H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #006: H5L.c line 1593 in H5L__link_cb(): name already exists
    major: Links
    minor: Object already exists
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 6:
  #000: H5Dio.c line 314 in H5Dwrite(): dset_id is not a dataset ID
    major: Invalid arguments to routine
    minor: Inappropriate type
......
```

I think something is wrong when HDF5 writing the files for restart at the end of the original simulation, and the restart run can't read the data needed. 
But how should I avoid this in the original run? Anything related to the HDF5 version? Now I am using hdf5.1.10.5. 

I will try if 1.10.7 works.

**Comment by weipengyao** [comment]
I've tried HDF5-1.10.7 and 1.8.21, and pull the latest commit version of SMILEI from github, all not working. 
At the timestep of the `dump_step`, it will give error messages like above. 

I also tried to vary the `dump_step`, avoiding the average timestep and the output timestep, still not working.

**Comment by mccoys** [comment]
Did you remove all the files from your directory before running the simulation? Did you run the simulation in another directory?

**Comment by weipengyao** [comment]
> Did you remove all the files from your directory before running the simulation? Did you run the simulation in another directory?

@mccoys  Yes, I remove the whole directory before running the simulation, since I use the `smilei.sh` script. And I found this problem is related to the external B-field that I use. 

Please check #348 .

**Comment by weipengyao** [comment]
@flavorenti Hi, I notice that in your case, you also have external B-field applied, so as #348 it might have already been solved with the latest push thanks to @mccoys. Maybe you want to try your case with the updated version.

Also, in my case, in the first run, there're a few error messages in the `*.err` output file, saying that at the restart point, some files/variables are not dumped. And that's the reason why in the following run, I can't restart.
So, besides the `*.out` file, you may also want to check the `*.err` file to see if there's anything useful.

Hope it can help.
