### ISSUE TITLE
Weight for the ion momentum diagnostic

### ISSUE THREAD

**Issue by Tissot11** [SmileiPIC/Smilei#337]
I understand that the momentum is defined in electron mass, so the ion momentum has to be rescaled if one wants to express it in term of the ion rest mass. However, I was wondering if the `weight` has to be also rescaled in this case?  Specifically, I construct a diagnostic 

`DiagParticleBinning(
    name = "p_ion",
    deposited_quantity = "weight",
    every = 10,
    time_average = 1,
    species = ["ion1", "ion2"],
    axes = [
        ["p", 0.1, 20, 1000, "logscale", "edge_inclusive"] ]
)`

I have already included the ion mass in the `p` axis above. So on post-processing, I rescale it by dividing it with the ion to electron mass ratio. For the weight, I extract it

`pDiagIon = S.ParticleBinning( "p_ion", timesteps=last ) and 
pWeight = np.array( pDiagIon.getData()[0] ).T`

Should I also rescale the `weight` in `pWeight`?. I think it should not be rescaled but after reading  #91 and #277, I got a bit confused, so I want to clarify this.

**Comment by mccoys** [comment]
The weight has nothing to do with mass. The issues you cite were about `weight_px_vx`, which includes momentum. So the question was about the `px` not about the `weight`.

**Comment by MickaelGrech** [comment]
No! `weight`refer to numerical weight, and basically measures a density and/or number of real particles corresponding to a given macro-particle. It is in no way related to a mass

**Comment by MickaelGrech** [comment]
(sorry, got disturbed by @mccoys' comment as I was writing mine, basically the same!)

**Comment by Tissot11** [comment]
Ok. Thanks for the clarification!
