### ISSUE TITLE
species issue to induce the the plasma wake field

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#339]
Hi all smilei team member,

Recently, I noticed that when I used the species electron and proton then simulation stuck after some time. but there is no error msg and simulation status is running but there is no progress. When I use single species only electron then its working fine. Can any one suggest me why this problem occurred with two species

**Comment by mccoys** [comment]
Hi,
We need more information. We run simulations with many species without problem. Please join your input file or give more details.

**Comment by Sanjeev273** [comment]
[passivebeamdumping1D.txt](https://github.com/SmileiPIC/Smilei/files/5572583/passivebeamdumping1D.txt)
 Plz fined here the input file.

**Comment by mccoys** [comment]
Could you try to use `print_every=1` and see if there is really no progress at all ? Maybe it is just very slow.

**Comment by Sanjeev273** [comment]
> 
> 
> Could you try to use `print_every=1` and see if there is really no progress at all ? Maybe it is just very slow.

@mccoys  I use 'print_every = 1'.  There is no progress after 5221 iteration.

**Comment by mccoys** [comment]
So it keeps running well until 5221, but it stops afterwards ?

**Comment by Sanjeev273** [comment]
> 
> 
> So it keeps running well until 5221, but it stops afterwards ?

Yes I can see the progress up to 5221. afterward there is no progress. but in the status I can the the job is running. I monitor the status for 4 hours after 5221 iterations.

**Comment by mccoys** [comment]
Your input file works fine with or without ions on my computer. This means there is some issue with your installation. Could you show us your log output ?
You may try some things (one by one) to pinpoint the problem:
* run with only 1 thread and 1 MPI process.
* remove LoadBalancing
* remove diagnostics

**Comment by Sanjeev273** [comment]
[passivebeamdumping1D.txt](https://github.com/SmileiPIC/Smilei/files/5574302/passivebeamdumping1D.txt)
[activebeamdumping.sge.o1526532.txt](https://github.com/SmileiPIC/Smilei/files/5574317/activebeamdumping.sge.o1526532.txt)

**Comment by mccoys** [comment]
Wait ... your simulation goes well over 5221 ! Is there really a problem ?

**Comment by Sanjeev273** [comment]
still there is no progress.

**Comment by mccoys** [comment]
The last line of the log output is
`     87600/2229637     1.6644e+04     6.5241e+02   (  7.0798e-`
Is it how it ends ? It is very strange to see the line is cut. Are you sure your system is not having some issues ?

**Comment by Sanjeev273** [comment]
> 
> 
> The last line of the log output is
> ` 87600/2229637 1.6644e+04 6.5241e+02 ( 7.0798e-`
> Is it how it ends ? It is very strange to see the line is cut. Are you sure your system is not having some issues ?

I am using CSF3 facility at university of Manchester. I already sent an email to IT department regarding this issue and waiting for reply.

**Comment by mccoys** [comment]
Just letting you know that some systems have a buffering mechanism that makes the output in the log file only at some points (every minutes or so). The simulation still runs behind.
