### ISSUE TITLE
Mutiple laser envelope gaussian laser pulse

### ISSUE THREAD

**Issue by Sonuphd** [SmileiPIC/Smilei#345]
Dear Sir,

I am working with muliple envelope laser pulse model for LWFA. But I got error during simulation. I am attaching my error. Please suggest any suggestion.

(base) sonu@sonu-HP-15-Notebook-PC:~$ cd LWFA44
(base) sonu@sonu-HP-15-Notebook-PC:~/LWFA44$ mpirun -n 2 ~/Smilei/smilei LWFA.py
                    _            _
  ___           _  | |        _  \ \   Version : v4.4-792-g1ed1f370-master
 / __|  _ __   (_) | |  ___  (_)  | |   
 \__ \ | '  \   _  | | / -_)  _   | |
 |___/ |_|_|_| |_| |_| \___| |_|  | |  
                                 /_/    
 
 

 Reading the simulation parameters
 --------------------------------------------------------------------------------
 HDF5 version 1.12.0
	 Python version 2.7.18
	 Parsing pyinit.py
	 Parsing v4.4-792-g1ed1f370-master
	 Parsing pyprofiles.py
	 Parsing LWFA.py
  On rank 1 [Python] Exception: ERROR in the namelist: cannot define block LaserEnvelope() twice
  On rank 0 [Python] Exception: ERROR in the namelist: cannot define block LaserEnvelope() twice
	[ERROR](0) src/Params/Params.cpp:1286 (runScript) error parsing LWFA.py
	[ERROR](0) src/Params/Params.cpp:1286 (runScript) error parsing LWFA.py

**Comment by mccoys** [comment]
PLEASE **read the error** and stop labeling as BUG 

**Try to solve by yourself before posting here**
