### ISSUE TITLE
Colorbar command error

### ISSUE THREAD

**Issue by Sonuphd** [SmileiPIC/Smilei#346]
Dear Sir,

Please help me for correct command for colorbar command during post-processing. I have pasted my command.

In [23]: diag = S.Field(0,"Rho",units=["cm^-3","um","fs"],title_font = {'size': 15, 'weight': 'bold', 'family':'serif', 'color': 'k'},xlabel_f
    ...: ont={'size': 15, 'weight': 'bold', 'family':'serif', 'color': 'k'},ylabel_font={'size': 15, 'weight': 'bold', 'family':'serif', 'colo
    ...: r': 'k'},xticklabels_font={'size': 15, 'weight': 'bold', 'family':'serif', 'color': 'k'},yticklabels_font={'size': 15, 'weight': 'bol
    ...: d', 'family':'serif', 'color': 'k'},cmap="seismic_r",colorbar_font={'size': 15, 'weight': 'bold', 'family':'serif', 'color': 'k'})   

In [24]: diag.plot()                                                                                                                          
Diagnostic is invalid
The following keyword-arguments are unknown: colorbar_font

**Comment by mccoys** [comment]
Did you update to the last commit on github?  This option is very recent.

Also use the command `make happi` to use the updated version.
