### ISSUE TITLE
Some problems with installation

### ISSUE THREAD

**Issue by taux17** [SmileiPIC/Smilei#347]
Dear SmileiPIC team,  thanks for spending tremendous amount of efforts on this nice general PIC code.  I have recently successfully installed it on my MacOS.  During the process, I have noticed a few very minor things in the documents that might help future Mac users to install SmileiPIC.  FYI, I use Macport on a MacOS 10.15.7 with openmpi-gcc9.  

1,  On the MacOS installation page, the path to HDF5 library probably should be. 

> export HDF5_ROOT_DIR=/opt/local

instead of 

> export HDF5_ROOT_DIR=/opt/local/hdf5/lib/

2,  There is a script 

> scripts/compile_tools/check_make_options.py

that might give the error, even after I change "/usr/bin/env python" to "/usr/bin/env python2"

>File "scripts/compile_tools/check_make_options.py", line 11
>    print option, "do not exist for", keyword
>               ^
>SyntaxError: Missing parentheses in call to 'print'. Did you mean print(option, "do not exist for", keyword)?

So I simply changed the print statement to print function. 

3,  A question:  In this document "https://smileipic.github.io/Smilei/algorithms.html" about PIC algorithms, shouldn't there a cell volume in the definition of the statistical weight "wp", in the part about "Initialization of the simulation"

Thanks. 
".

**Comment by mccoys** [comment]
1. This depends on the version of MacOs I believe. @iltommi do you know more details?
2. This was removed a while ago. Please update.
3. Correct. We have modified the definition of weights a long time ago but we forgot to fix this point in the doc. It has been corrected in the "Units" section though.

**Comment by iltommi** [comment]
I did a clean install on a Mojave via macports and updated the doc.
I dropped the python2 version and used a python3.8.

@taux17 : Thanks for Reporting! I'm closing this issue, feel free to reopen it if something is still wrong
