### ISSUE TITLE
Spatial resolution

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#350]
Dear Smilei Team,

First of all, happy new year !

I have a general question about spatial decomposition. Would it be possible to define different spatial resolution dx in one simulation box? Because when you have a simulation with high density and low Te area and another area with high Te and low density (low Debye length), all the simulation has the same very low dx.

Thanks

Julien

I cannot do ...

## The solution

I would like to ...

## Failed attempts

I have tried other things already ...

**Comment by beck-llr** [comment]
Hi Julien,
Happy new year to you too.

What you are asking for is something we wanted to work on in the next couple of years but it is not going to be available before long so don't expect anything soon on that side.
In the meantime you can have a look at https://www.sciencedirect.com/science/article/pii/S0021999113008152 if you want more details about the technique we are looking at.
