### ISSUE TITLE
happi: TrackParticles cannot open data without the disordered file

### ISSUE THREAD

**Issue by andsunds** [SmileiPIC/Smilei#351]
## Description

After a recent update of the repository, my workflow for working with the TrackParticles diagnostic has broken. What I have been doing before is sorting the particles once, and then deleting the disordered files (`TrackedParticlesDisordered_species.h5`) because of the large file sizes.

The problem now is that happi seems to only look for the disordered file and thus returns the following error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andsunds/SVN/nonlinear/andsunds/PIC-coll-project/simulations/Smilei/analyze_D_py-pz.py", line 25, in <module>
    electrons=S.TrackParticles(species='electron')
  File "/home/andsunds/smilei/Smilei/happi/_core.py", line 585, in __call__
    return TrackParticles.TrackParticles(self._simulation, *args, **kwargs)
  File "/home/andsunds/smilei/Smilei/happi/_Diagnostics/Diagnostic.py", line 71, in __init__
    remaining_kwargs = self._init(*args, **kwargs)
  File "/home/andsunds/smilei/Smilei/happi/_Diagnostics/TrackParticles.py", line 81, in _init
    file = disorderedfiles[0]
TypeError: 'NoneType' object is not subscriptable
```

Since much of my data is only saved in the ordered files, this has become somewhat of a problem for me.

## Steps to reproduce the problem

Run a simulation with the TrackParticles diagnostic. Sort the particles in happi (e.g. through `S.TrackParticles(species='electron', sort=True)`). Delete the disordered file (e.g. `rm TrackedParticlesDisordered_species.h5`)

## Parameters

- Computing resources
  - type of computer: PC
  - Ubuntu 20.04
  - Python version 3.8.5

**Comment by mccoys** [comment]
Never delete the disordered file !
It contains necessary information for analysis.

**Comment by andsunds** [comment]
Have this changed recently? I have never had a problem before when deleting my disordered files. What information is lost in the disordered file?

**Comment by mccoys** [comment]
It has changed about 2 years ago. For now, the only data that is missing is the information about the moving window. Technically, it could be copied into the ordered file, but it is more involved.

**Comment by andsunds** [comment]
Ah, well it seems as if I haven't updated Smilei on my desktop since early 2019, so the ~2 years ago checks out. Does this mean that I haven't lost any data by deleting the disordered files then? I have not used any moving window simulations.

My problem, however, still stands: is there a way for me to use my old data (without the disordered files) now?

**Comment by mccoys** [comment]
If you don't have a moving window, you can comment out (temporarily) these lines in `happi/_Diagnostics/TrackParticles.py`:
```python
		# Add moving_x in the list of properties
		if "x" in self.available_properties:
			file = disorderedfiles[0]
			with self._h5py.File(file, "r") as f:
				try: # python 2
					D = next(f["data"].itervalues())
				except: # python 3
					D = next(iter(f["data"].values()))
				if "x_moved" in D.attrs:
					self.available_properties += ["moving_x"]

```

**Comment by mccoys** [comment]
Please close the issue if this is working for you.

Note that we usually recommend to keep a version of smilei + happi that matches that of your simulation. Over the years, there may be some changes that make old simulations incompatible with recent versions of happi

**Comment by andsunds** [comment]
Yes, this works for me. I will from now on keep an old version of happi along with my old simulations.

May I, however, suggest that it would be good to not have to keep both the ordered and disordered files in the future, since that more or less doubles the disk usage of the same data.
