### ISSUE TITLE
Scalar quantities

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#353]
Dear Smilei team,

I did not use scalar diags for a while....
I checked the energies in the simulation box for a 1D simulation. I am quite surprised with the ion (proton) energy that is really low (it is a case of Hole Boring acceleration in a high density of 200ne target):

![energy_check](https://user-images.githubusercontent.com/48507571/104578600-366c1e00-565b-11eb-8ff1-a6e5e0a53a1b.png)

The ion energy seems to be extremely low. If I just compare ion and electron energies I find that ion energy is 500 TIMES lower than electron energy. I know these quantities Ukin_abc are kinetic energy densities but I am not sure of the simulation numerical heating. If I check the Ubal, Ubal increase but it is nothing compared to Utot in the simulation box.

![EON](https://user-images.githubusercontent.com/48507571/104579942-ee4dfb00-565c-11eb-91cb-8ed00dfd6c6f.png)
![ION](https://user-images.githubusercontent.com/48507571/104579944-eee69180-565c-11eb-91a5-e8549eb1aa56.png)
![Ubal](https://user-images.githubusercontent.com/48507571/104579945-eee69180-565c-11eb-8f3f-bf922fbec3ed.png)

Regarding Ubal, what do you think about this simulation please?

Thanks a lot

Julien

**Comment by mccoys** [comment]
Which version of smilei ?

**Comment by juliencelia** [comment]
Version : v4.4-706-gb5c12a5a-master

**Comment by mccoys** [comment]
Try with the latest version please

**Comment by juliencelia** [comment]
OK. It runs.

**Comment by juliencelia** [comment]
It is OK with the last version!
Thanks!
