### ISSUE TITLE
Collisions module bug

### ISSUE THREAD

**Issue by czajah** [SmileiPIC/Smilei#356]
Collisions.cpp:288

`s1 = patch->vecSpecies[( *sg1 )[0]];` <-- here, species from index "0" can have no particles then two lines down
inside `patch->getPrimalCellVolume` you get seg fault. In my case Patch2D.h:32 `p->position(0,ipart)`

**Comment by mccoys** [comment]
Correct. This was actually fixed recently on our end. It will be made available soon on github.

**Comment by mccoys** [comment]
This is now pushed here on GitHub. Please close the issue if this works for you.

**Comment by czajah** [comment]
Looks like it's working :)
