### ISSUE TITLE
Particle's created in zero-density regions when initialising charge density with numpy array

### ISSUE THREAD

**Issue by GeorgeHicks1** [SmileiPIC/Smilei#357]
## Description

I am initialising the charge density of my hydrogen plasma using a numpy array I create offline. The numpy array has the same dimensions as the simulation box and I save the numpy array as a pickle file before uploading it to the supercomputer. As far as I can tell, there are two ways to apply the numpy array.

1) Directly
```
density_map = pickle.load( open( "curved_BW_targx_1790_08.pickle", "rb" ) )
Species(
    name = 'electron',
    position_initialization = 'regular',
    momentum_initialization  = 'cold',
    particles_per_cell = 1,
    mass = 1.0,
    charge = -1.0,
    charge_density = density_map,
    boundary_conditions = [["remove"]]
)
```

2) With a function
```
density_map = pickle.load( open( "curved_BW_targx_1790_08.pickle", "rb" ) )
def density_fn(x,y):
    return density_map[int(y/res[1]),int(x/res[0])]
Species(
    name = 'electron',
    position_initialization = 'regular',
    momentum_initialization  = 'cold',
    particles_per_cell = 1,
    mass = 1.0,
    charge = -1.0,
    charge_density = density_fn,
    boundary_conditions = [["remove"]]
)
```

When SMILEI creates the particles via method 1 it creates 86507520 particles and method 2 creates 74718336 particles.

86507520 is the number of cells in the simulation, I have 1 particle per cell so SMILEI is creating 1 particle in every cell. However, only 86.3% of cells in my numpy array are non-zero, so SMILEI should just be creating 86507520*0.863=74655990 particles.

Method 2 is doing this correctly and only adding particles in the cells with non-zero density.

To me method 2 is operating properly, but method 1 has a bug where particles with zero weight are being created in regions of zero density.

## Output files
Method 1 [log.txt](https://github.com/SmileiPIC/Smilei/files/5835700/log.txt)
Method 2 [log.txt](https://github.com/SmileiPIC/Smilei/files/5835683/log.txt)

## Steps to reproduce the problem
1) Create 20480x4224 array with 86.3% non-zero values.
2) Save as pickle file
3) Run using either namelist below and observe the different number of particles created

## Parameters

- Smilei version: bv4.4-783-g9183dad-bmaster
- Input files:
[namelist_method1.txt](https://github.com/SmileiPIC/Smilei/files/5835621/namelist_method1.txt)
[namelist_method2.txt](https://github.com/SmileiPIC/Smilei/files/5835608/namelist_method2.txt)

- Commands or script used to run the faulty simulation ?
- Computing resources
  - Imperial College High Performance Computer
  - liunx
  - HDF5 version 1.10.1
  - Python version 3.7.3

**Comment by mccoys** [comment]
By any chance could you try the latest version ? There have been changes recently on this matter

**Comment by GeorgeHicks1** [comment]
I've compiled the most recent version- Version : bv4.4-895-g4ca6e82-bmaster and I still get the same problem.

The problem is, in fact, more severe than I first realised and Smilei is initalising the simulation box with a uniform density of 1 nc, not the array I passed in.

Here I have extracted the electron density in 2 different ways, from the ParticleBinning diagnostic and from the species charge density using the following code:

```
plt.figure(figsize=(14,3))
plt.subplot(1,2,1)
plt.imshow(np.transpose(S.ParticleBinning(0).getData(timestep=0)[0]), vmin=0, vmax=9, extent=[0,20480,4224,0])
plt.title('Particle Binning diagnostic')
plt.colorbar()
plt.subplot(1,2,2)
plt.imshow(S.namelist.Species[0].charge_density, vmin=0, vmax=9)
plt.title('Species charge density')
plt.colorbar()
plt.show()
```

![image](https://user-images.githubusercontent.com/37219451/105050055-43c34700-5a65-11eb-8abf-ff9c76ec9c78.png)

Have I perhaps written my namelist incorrectly?
Namelist: [namelist.txt](https://github.com/SmileiPIC/Smilei/files/5836577/namelist.txt)
Log: [log.txt](https://github.com/SmileiPIC/Smilei/files/5836598/log.txt)

**Comment by mccoys** [comment]
Ah. Indeed this is the issue. A density cannot be an array ! Read the doc carefully and you will find out it can only be a function or a float.

**Comment by GeorgeHicks1** [comment]
Ah I see it now, sorry I misssed that.

> A numpy array ... This initialization is incompatible with number_density, charge_density and particles_per_cell. 

Given this, what is the recommended way of initalisating the density based on an array? A function that calls the array like I have used?
`def density_fn(x,y):
    return density_map[int(y/res[1]),int(x/res[0])]`

**Comment by mccoys** [comment]
Yes your function is fine. We actually have another issue opened for thinking about what would be the best way to directly read from an array. #278

**Comment by GeorgeHicks1** [comment]
Ok, thank you for your help
