### ISSUE TITLE
Same Species (atomic and ionized)

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#358]
Dear SMILEI team,

I try to run a simulation but I have an error in Patches initialization.
I want simulate a plasma of C and H species. For example, a slice of (C6+ and H+) followed by another slice of CH (atomic - no charge) like that in my namelist:

Zion        = [1,6]                         # atomic number of ions
Aion        = [1,12]                        # number of nucleons
Wion        = [1,1]                         # stoichiometric proportions

def profile_ele(x):
      if 50*um<=x<60*um:
          return 100.
      elif 60*um<=x<=70*um:
          return 0.
      else :
	      return 0.

def profile(x):
      if 50*um<=x<60*um:
          return 100./7.
      elif 60*um<=x<=70*um:
          return 0.
      else :
	      return 0.

def profile_z(x):
      if 50*um<=x<60*um:
          return [1.,6.]
      else :
	      return [0.,0.]

def temp_e(x):
    if 50*um<=x<60*um:
        return 1e-4*MeV
    elif 60*um<=x<=70*um:
        return 1e-5*MeV
    else :
        return 0.

Species(                                    # electron specie definition
    name                    = 'eon',
    mass                    = 1.,
    charge                  = -1.,
    temperature             = [lambda x: temp_e(x)],
    position_initialization = 'random',
    momentum_initialization = 'maxwell-juettner',
    particles_per_cell      = ppc,
    number_density          = lambda x: profile_ele(x),
    boundary_conditions     = [
        ['remove','remove'],],
    ionization_model        = 'tunnel',
    # radiation_model         = 'Landau-Lifshitz'
    ionization_electrons         = 'eon'
)

for i in range(len(Zion)):                  # loop over ion species
    Species(                                # ion specie definition
        name                    = 'iZ%s'%Zion[i],
        mass                    = 1836.0 * Aion[i],
        charge                  = lambda x : profile_z(x)[i],
        atomic_number           = Zion[i],
        position_initialization = 'random',
        momentum_initialization = 'maxwell-juettner',
        particles_per_cell      = ppc,
        number_density          = lambda x: profile(x),
        temperature             = [lambda x: temp_e(x)],
        boundary_conditions     = [
          ['remove' , 'remove'],],
        ionization_model        = 'tunnel',
        #ionization_model        = 'none',
        ionization_electrons    = 'eon'
)

I have this error: [ERROR](0) src/Ionization/IonizationFactory.h:27 (create) Charge > atomic_number for species iZ1

Is it due to I have to define two different species for atomic and ionized iZ1 for example?

Thanks

Julien

**Comment by juliencelia** [comment]
Sorry for 'eon' species ionization is 'none' of course. My namelist is OK.

**Comment by beck-llr** [comment]
Hi I am no expert but the error text looks quite self explanatory. A species can not have a charge higher than its atomic number (for obvious physical reasons) which is apparently what you are asking for.

**Comment by juliencelia** [comment]
Actually, at the maximum, I set the charge = atomic number. I would like to know if that is forbidden by the code. It seems to be the case...

**Comment by mccoys** [comment]
You cannot use `charge = lambda x : profile_z(x)[i]`

You are creating a lambda function that depends on the variable `i`. But the variable `i` is available only during the `for` loop. Thus, when the code is running the function, the variable `i` is either destroyed or it kept its previous value. You have to define 2 profiles and use `charge = [profile_z1, profile_z2][i]`.

**Comment by juliencelia** [comment]
Thanks Maccoys!
But profile_z1 and profile_z2 depend on x position. So I need lambda function no?

**Comment by mccoys** [comment]
No. I don't understand why you would need a lambda function. You can use it if you like. A lambda function is exactly the same as a normal function, but it can be written in a single line. So you can use either normal or lambda function. In your case, you need 2 functions.

**Comment by juliencelia** [comment]
Yes I wanted to say 'I need a function'.
Thanks very much.
