### ISSUE TITLE
happi: Moving window function s.Field.getXmoved(timestep) returns simulation units instead of specified units

### ISSUE THREAD

**Issue by DoubleAgentDave** [SmileiPIC/Smilei#359]
When post-processing a field output using happi from a smilei simulation using a moving window the following commands are used to get the spatial axis (in 3D):

    omega = 2*pi*c/(0.8 e-6)
    s = happi.Open(save_dir,reference_angular_frequency_SI=omega)
    units = {"x":"um", "y":"um", "z":"um","v":"statV/cm"} #is this correct?
    RhoC_Field = s.Field(0,'Rho_carbon',units=units)
    times = RhoC_Field.getTimesteps()

    for i in range(len(times)):
       x_Axis = RhoC_Field.getAxis('x')
       x_disp = RhoC_Field.getXmoved(times[])
       print(x_disp)
       y_Axis = RhoC_Field.getAxis('y')
       z_Axis = RhoC_Field.getAxis('z')

unfortunately, while the function getAxis('x') returns the x-axis in microns (as requested) the function getXmoved(times[i]) returns a displacement in simulation units making getting a moving axis tricky. It would be super useful if I could just adjust the axis by doing:
x_Axis += x_disp
to get the moved axis. It's still possible to get this axis by multiplying x_disp by 2*pi/0.8e-6 , but it seems to miss the point of such a useful function to ignore units.

**Comment by DoubleAgentDave** [comment]
This was using the last version on github as of the posting of this message (bv4.4-895-g4ca6e82f-bmaster) (i also tried it with the last downloaded version ??-??)

**Comment by mccoys** [comment]
I have changed the output of `getXmoved` in the last commit. Please close the issue if it works for you.

**Comment by DoubleAgentDave** [comment]
ok, using bv4.5-370-ga59b8295-bmaster i've tried this, please tell me if I'm wrong:
>>> import happi
>>> save_dir = 'window_test_out'
>>> lamb = 0.8e-6
>>> omega=2.0*np.pi*299792458.0/lamb
>>> omega
2354564459136066.5
>>> s = happi.Open(save_dir,reference_angular_frequency_SI=omega)
Loaded simulation 'window_test_out'
Scanning for Scalar diagnostics
Scanning for Field diagnostics
Scanning for Probe diagnostics
Scanning for ParticleBinning diagnostics
Scanning for RadiationSpectrum diagnostics
Scanning for Performance diagnostics
Scanning for Screen diagnostics
Scanning for Tracked particle diagnostics
>>> units = {"x":"um","y":"um"}
>>> RhoC_Field = s.Field(0,'Rho_carbon',units=units)
>>> times = RhoC_Field.getTimesteps()
>>> x_disp = RhoC_Field.getXmoved(times[1])

this gives me a displacement in simulation units not microns as desired.

**Comment by mccoys** [comment]
You cannot use `{"x":"um","y":"um"}` in this case because the `getXmoved` coordinate is not necessarily related to the plot's `x` axis. In fact the simulation's `x` coordinate could be absent from the plot (you may imagine, for instance, that you have a `y-z` plot). As a consequence, you should set the units as `["um"]` so that any length will be in microns, including the `getXmoved`.

**Comment by DoubleAgentDave** [comment]
OK, now I understand. Thanks !
