### ISSUE TITLE
Unit conversion in happi not working for E_r, B_r or N_r, or have I got the syntax wrong?

### ISSUE THREAD

**Issue by DoubleAgentDave** [SmileiPIC/Smilei#360]
Errors for unit conversion in happi:
  WARNING: cannot convert units to <statV/cm>
         : Conversion discarded.
  WARNING: units unknown: E_r

in python 3.9.1 do the following:

    c = 3e8 # i know it's wrong
    lamb = 0.8e-6
    omega=2.0*np.pi*c/lamb
    save_dir = 'bob'
    s = happi.Open(save_dir,reference_angular_frequency_SI=omega)
    units = {"x":"um", "y":"um","v":"statV/cm"} 
    Ex_Field = s.Field(0,'Ex',units=units)

For units same problem with V/m, or V/cm or statV/m, all of these units are defined in 'pint', also same issue when "y":"um" is omitted.

I've attached a zip with the input deck and a plotting function:
[input and plot files.zip](https://github.com/SmileiPIC/Smilei/files/5881415/input.and.plot.files.zip)

I can't provide the smilei executable though it's huge.

**Comment by DoubleAgentDave** [comment]
To be clear, I downloaded the latest version of smilei from github, as of the timestamp of this message, and compiled it on my laptop with the latest versions of python 3.9.1, pint 0.16.

**Comment by mccoys** [comment]
I am very surprised: Your commands work for me as long as I set `units = {"x":"um", "y":"um","v":"V/cm"}`

Python : 3.8.5
Pint : 1.16.1

Have you tried isolating your commands above in a clean python environment ?

**Comment by DoubleAgentDave** [comment]
Having just tried what you said:

>>> import happi
>>> lamb=0.8e-6
>>> omega=2.0*np.pi*ml.cl/lamb>>> omega2354564459136066.5>>> save_dir = 'yin_test_out_no_window'>>> s = happi.Open(save_dir,reference_angular_frequency_SI=omega)
Loaded simulation 'yin_test_out_no_window'
Scanning for Scalar diagnostics
Scanning for Field diagnostics
Scanning for Probe diagnostics
Scanning for ParticleBinning diagnostics
Scanning for RadiationSpectrum diagnostics
Scanning for Performance diagnostics
Scanning for Screen diagnostics
Scanning for Tracked particle diagnostics
>>> units = {"x":"um", "y":"um","v":"statV/cm"}
>>> Ex_Field = s.Field(0,'Ex',units=units)WARNING: cannot convert units to <statV/cm>
       : Conversion discarded.
>>> units = {"x":"um", "y":"um","v":"V/m"}
>>> Ex_Field = s.Field(0,'Ex',units=units)

does work for 'V/m', but not for 'statV/cm' for some reason. I think there might be some conflict between the pint registry i got with pint and the one in happi maybe? (ml.cl just returns the numerical value speed of light in m/s).

**Comment by DoubleAgentDave** [comment]
When I do this: 

>>> import pint
>>> ureg = pint.UnitRegistry()
>>> 'statV' in ureg
True
>>> 'statV' in ureg
True
>>> 'cm' in ureg
True
>>> 'statV/cm' in ureg
True
>>>

I'm finding this a bit weird, while this might not be a bug with smilei or happi I would appreciate some help in making sure the units are defined.

**Comment by mccoys** [comment]
I expect this is a Pint issue. I am not sure how it switches between SI and CGS. Maybe it cannot convert `V` to `statV` ?

**Comment by DoubleAgentDave** [comment]
Yes, I'll try looking into that further.
It seems that if you write a script:

import happi
s= happi.Open(save_dir,reference_angular_frequency_SI=omega)
units = {"x":"um", "y":"um","v":"statV/cm"}
Ex_Field = s.Field(0,'Ex',units=units)WARNING: cannot convert units to <statV/cm>

it works. But if you write a script:

import happi
def start():
    s= happi.Open(save_dir,reference_angular_frequency_SI=omega)
    units = {"x":"um", "y":"um","v":"statV/cm"}
    Ex_Field = s.Field(0,'Ex',units=units)WARNING: cannot convert units to <statV/cm>

if __name__=="__main__":
    start()

it doesn't work and gives 'E_r unknown unit' as described initially. Probably worth closing this issue as it really looks like an issue with pint, if you agree?

**Comment by mccoys** [comment]
The issue seems clearly with pint.

For the problem with the script, try importing happi inside the function ? I am not sure what happens there. Maybe a conflict in opening pint from a different script ?

**Comment by DoubleAgentDave** [comment]
Yeah from the point of view of functionality I can just code around the problem. I don't know exactly why 'statV' and 'V' don't want to convert, but that's nothing to do with smilei or happi so I'll just bash my head against pint and convert to standard SI units.

**Comment by mccoys** [comment]
Note you can multiply by some factor directly in happi
