### ISSUE TITLE
Incorrect density summing results when vectorisation turned on (KNL system)

### ISSUE THREAD

**Issue by DoubleAgentDave** [SmileiPIC/Smilei#361]
Incorrect density summing results when vectorisation turned on (KNL system)

If you turn the vectorisation the density output is correct and code bahaves as expected. Turn the vectorisation on and the density is incorrectly calculated, not just for the output, but in the actual code calculations e.g. a laser will pass through what should be an over-dense block of plasma.

I've included the input decks and the source code in the attached zip as well as python scripts for plotting the output. Have tested with both the xMIC-AVX512 flag on and off. Note that MPI_THREAD_MULTIPLE is turned off (maybe this is the cause?) using the compiler directive

[smilei_bug_test.zip](https://github.com/SmileiPIC/Smilei/files/5900656/smilei_bug_test.zip)

Compile program and run it with vectorisation set to 'on', or 'adaptive' and 'initially=on'.

- Smilei version: Github last commit
- Input file will include in attachment
- Commands or script used to run the faulty simulation ? (out put included in zip)
  run interactive session on KNL node:
export OMP_NUM_THREADS=16
mpirun -n 4 ./smilei namelist
   note also does the same thing if ibrun used in a queued script.
- Computing resources
  - type of computer KNL 7250
  - C++ compiler. Intel compiler 18.0.2
  - MPI version. Intel MPI Library 18.0.2 ?
  - HDF5 version Parallel compiled Version 1.10.4
  - Python version Python 3.7.0

**Comment by DoubleAgentDave** [comment]
Note, if you need access to the machine I'm using this on message me either on the matrix chat room or respond here, the administrator has offered access to stampede for this purpose.

**Comment by DoubleAgentDave** [comment]
i did use the no_mpi_tm option in the makefile though. I'm about to test it once more without that option.

**Comment by DoubleAgentDave** [comment]
Once the update to the file Projector3D4OrderV.cpp is included in the master thing this bug can be closed as that fixed the problem for me as far as I can test. Thanks !

**Comment by DoubleAgentDave** [comment]
I mean once someone else updates it, i can't.

**Comment by xxirii** [comment]
We have updated the master branch. .Commit 3545fe506e3dbb5a6e79c338eb694fdf6b464b79 should correct this bug. Thank you.
