### ISSUE TITLE
Print memory usage for fields and particles before applying prescribed fields, or be able to turn this feature off

### ISSUE THREAD

**Issue by DoubleAgentDave** [SmileiPIC/Smilei#362]
Knowing the memory load of smilei before a proper run is started is really useful when testing. 
One of the following would be useful:

1. include memory calculation in smilei_test (hard if problem is not evenly spread out so maybe not)
2. print memory calculation before external prescribed fields and maybe diags

**Comment by DoubleAgentDave** [comment]
Maybe the memory can be calculated from particles_per_cell instead of actual number of particles loaded in a given patch?

**Comment by mccoys** [comment]
1. Too hard to do as we do not want to compute all the profiles in every cell for the test mode. This is sometimes extremely costly.
2. This may be possible with little work. I will have a look

> Maybe the memory can be calculated from particles_per_cell instead of actual number of particles loaded in a given patch?

Impossible for the same reason as 1.

**Comment by mccoys** [comment]
Request 2 is now done in the last push.
Request 1 will not be done as it is not possible even in theory.
