### ISSUE TITLE
Current problem

### ISSUE THREAD

**Issue by fachernikov** [SmileiPIC/Smilei#363]
Dear developers, 
I tried to calculate current in 1D simulation, in front of expanding plasma. For that I think I can use two different diagnostics:  a Probe diagnostic (flow in time) and a Screen diagnostic (just current) at the same point as the Probe one. I got the number of both electrons and ions and calculated the current as their difference because they have the same charge. 
My question is why these two diagnostics give different numbers. Is it because I can not calculate the current from Probes or from Screens? How to obtain the correct current from the simulation?
input file [test1.txt](https://github.com/SmileiPIC/Smilei/files/5931975/test1.txt)
![untitled folder_probe#0_@pos#0 7_ 'Jx' __px](https://user-images.githubusercontent.com/63446538/107025695-d0d30380-67ba-11eb-9385-03148fbb6fa8.png)
![untitled folder_screen_#0_ion_(t)_px](https://user-images.githubusercontent.com/63446538/107025716-d7fa1180-67ba-11eb-8725-1860d7031d5f.png)

**Comment by mccoys** [comment]
Hi,
I do not recommend Screen diags for current. ParticleBinning is better as it will account for a larger area. The Screen only counts particles going through the surface, thus is sensitive to bad statistics.

There may also be an issue with your setup as your Screen sums the weights (`deposited_quantity = "weight",`) and it should sum the currents (` deposited_quantity = "weight_charge_vx",` or so).

**Comment by phi-kafka** [comment]
Thank you mccoys,
can you please explain the difference in the code between counting a charge, passing a surface, and calculation of currents? Does not the current equal to a charge passing through a surface?
thanks
ph

**Comment by mccoys** [comment]
@phi-kafka Indeed those two definitions are equivalent in physics. In the PIC code, the usual way is to take every particle, and for each of them, calculate `velocity x weight x charge` and add this contribution to the nearby grid points. This results in the current density on the whole grid.

This operation is naturally done by default in the code, as currents are needed to compute Maxwell's equation. These currents can be obtained in the `Field` and `Probe` diagnostics.

Another way is to use the `ParticleBinning` diagnostics for a similar approach. The inconvenient is that you  don't use the same interpolation scheme as in the Maxwell solver, but instead you sum all particle in user-defined bins. The advantage is you have much more control on the way you distinguish particles in different bins (for instance you can distinguish particles by charge state).

Calculating currents by particles passing through a plane is not a good idea as there is way less statistics than interpolating all nearby particles.

**Comment by mccoys** [comment]
I forgot to add that the `Screen` diagnostic accumulates all currents in time. So you don't have an instantaneous value.
