### ISSUE TITLE
Issue with MPI communication when unfreezing particles

### ISSUE THREAD

**Issue by DoubleAgentDave** [SmileiPIC/Smilei#364]
## Description
particles given non zero frozen_time, program crashes shortly after particles unfrozen, I'll include a zip later today with compile options, a namelist and anything else useful.

## Errors:
terminate called after throwing an instance of 'std::bad_alloc'

## Steps to reproduce the problem
Use the namelist included

## Parameters
- Smilei version bv4.5-386-g3545fe506-bmaster
- Input file will be in zip
- Commands or script used to run the faulty simulation 
- Computing resources
  - type of computer KNL (XSEDE Stampede cluster)
  - OS
  - C++ compiler 
  - MPI version intel/18.0.2
  - HDF5 version phdf5/1.10.4
  - Python version 3.7.0
  - ...
I've tried this with and without the no_mpi_tm option and it happens no matter what.

**Comment by DoubleAgentDave** [comment]
Appears only to happen when running on more than one node.

**Comment by mccoys** [comment]
I am unable to reproduce the problem on my computer. Please submit an example when possible.

**Comment by DoubleAgentDave** [comment]
I think this might have been a problem with the system over the weekend, I've just done all the tests I did yesterday with exactly the same parameters and the issue disappears. I'm sorry, I've no idea why this happened.

**Comment by DoubleAgentDave** [comment]
In case anyone else has this problem it's a memory error that happens if there is an output being saved at the same timestep as the particles are being unfrozen, if there is not enough memory it crashes, hence the 'bad_alloc' or if the wind is blowing in the wrong direction inside the cluster I'm using. In order to reproduce it you need to have a large output dump happening at the same time as the unfreezing of the particles, and have bad luck as it doesn't always seem to happen.
