### ISSUE TITLE
TrackParticles select not responding correctly to multiple conditions

### ISSUE THREAD

**Issue by ThatEpicDude** [SmileiPIC/Smilei#367]
## Description

Hello,
I am trying to load a TrackParticles diagnostic with a condition set both on 'x' and on 'px'. I have only tracked a single timestep using the diagnostic as I only require all particle momenta at that specific time. My code line looks as follows:

```
eleclo= S.TrackParticles(species='electrons', select="all(t>0, x>108) * all(t>0, px>0)").getData()
```

happi's output looks as follows:

```
Selecting particles ... (this may take a while)
   Selecting block `all(t>0, x>108)`, at time 1948
   Selecting block `all(t>0, px>0)`, at time 1948
Removing dead particles ...
Kept 187983 particles
Loading data ...
   axis: Id
   axis: x
   axis: px
   axis: py
   axis: pz
   axis: w
   axis: moving_x
Process broken lines ...
done
```

So far so good. However, when I check the output dictionary only the 'px>0' condition is fulfilled while the x condition does not seem to be regarded. Interestingly enough, when I switch the conditions around (i.e. `" all(t>0, px>0) * all(t>0, x>108)"`) only the 'x>108' condition is fulfilled while the px condition is not. I am using `*` as the logical `AND` operation. Is there something I am not seeing here?

## Parameters

- Smilei version v-b5c12a5a
- happi version November 2020
- Computing resources
  - At home PC
  - Win 10
  - Python version 3.8.5
  
 A separate computer was used to run the simulation. Since this is a post-processing issue, I have stated the specifications for the computer on which I am processing the data.

**Comment by mccoys** [comment]
I will look into it. In the meantime, can you use ` all(t>0, (px>0)*(x>108))` ?

**Comment by ThatEpicDude** [comment]
Very good idea! I'm sorry, I should have thought of that. Thank you very much.

**Comment by mccoys** [comment]
I found the bug. It will be released with other improvements when they have passed a number of tests.

**Comment by mccoys** [comment]
This issue should be solved from the last push. Could you try if it works for you ?

**Comment by mccoys** [comment]
Let me close the issue for now. Please reopen if you encounter the problems again.
