### ISSUE TITLE
electron beam energy and gamma extraction using ParticleBinning diagnostic  

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#368]
Hi Smilei team member, 

I am trying to extract the kinetic energy and gamma parameter for electron bunch accelerated in plasma wakefiled by using the particle binning diagnostic. A Smilei1D script attache here.  
[activebeamdumping1D.txt](https://github.com/SmileiPIC/Smilei/files/5996494/activebeamdumping1D.txt)

for post processing I used the following command to get the plot:
S=happi.Open('/mnt/iusers01/fatpou01/phy01/v55735sk/scratch-new/SIM', reference_angular_frequency_SI= 2.
   ...: *math.pi*299792458/0.8e-6)

 eenspectr = S.ParticleBinning(1, units =["MeV", "um", "m^-3/MeV", "fs"], data_log = False,  label = "el
    ...: ectronbunch")
eenspectr.plot()
### 
![Figure_1](https://user-images.githubusercontent.com/67734147/108222591-d45a7900-7130-11eb-85b5-47730f32807d.png)

I am getting the energy density almost zero for electron bunch as well as for species (electrons). I check the densities for the electron bunch and electron species using Field diagnostic that is exist. Can you help me to get energy distribution for accelerated electron bunch and electron species? Thanks !

**Comment by mccoys** [comment]
Your energy range starts at 1. Are you sure there are any particles with enough energy ?

**Comment by Sanjeev273** [comment]
> 
> 
> Your energy range starts at 1. Are you sure there are any particles with enough energy ?
I tried the start range range of from  0 also. the result was same. In my case energy range should be 0 to 500MeV.

**Comment by mccoys** [comment]
* If you want to see 500 MeV Particles, then you `ekin=500.` is wrong.
* You set a wrong temperature
