### ISSUE TITLE
particle diagnostics

### ISSUE THREAD

**Issue by phyax** [SmileiPIC/Smilei#37]
I have some difficulty using the current particle binning diagnostics to do a field-particle correlation. The x-axis of the phase space, is the difference between the gyro-phase of particles and the cyclotron-phase of waves, which is called the relative phase angles. The y-axis is the particle velocity parallel to the background magnetic field.

If I use the particle binning diagnostics, 5 axes are needed, i.e., x, y, vx, vy and vz. Note that x and y are needed to select the location of the wave to be correlated. In this case, the five dimensional data takes more space than the actual particle data since the five dimensional matrix is very sparse (only 288 hundred particles in each x-y cell). For practical parameters, the runs to produce the five dimensional data usually crash.

To do the above field-particle correlations, I wish we can add the diagnostics to output the particle data directly. This may save more space than the binning technique if some high dimensional data is desired in some applications. We may also restrict the range of the axes to allow only a subset of particles to be output.

Let me know if this request is possible or not.

Merry Christmas and Happy the incoming new year :)

**Comment by mccoys** [comment]
Hi

Have you tried the [tracked particles diagnostic] (http://www.maisondelasimulation.fr/smilei/namelist.html#trackparticles-diagnostics) ? 

There is a `filter` option to select particles according to their parameters. 

In the post processing, you can also choose to avoid sorting particles (as you don't need to track them) in order to speed up the process : `sort=False`.

**Comment by phyax** [comment]
It seems that the tracked particle diagnostic is exactly what I need. I should have noticed it in the documentation. Thanks for your kind answer.

Just to confirm, is the 'filter' option be applied at every output? For instance, the subset of particles satisfying the condition 0 < x < 1 may change between two outputs. Does this diagnostic select particles satisfying 0 < x < 1 at every output, or it just does the filtering initially?

**Comment by mccoys** [comment]
It does at every output
