### ISSUE TITLE
Poynting flux of laser only

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#370]
Dear Smilei team,

Perhaps it is a silly question.
I would like to have access to the laser absorption by the plasma in my simulation box.
I can access to PoyXmin PoyXmax PoyYmax etc... with Diag scalar.

At the left boundary from where the laser come in, PoyXmin conatins also the energy of reflected laser part. 
How to have access to the PoyXmin but only due to the laser entrance in the box.

Hope I am quite clear...

Thanks in advance

Julien

**Comment by mccoys** [comment]
The only way I know is to make a simulation without plasma and take the difference to the simulation with plasma.

**Comment by juliencelia** [comment]
Thanks Mccoys. It works with that trick.
