### ISSUE TITLE
"every" Time Selection in TrackedParticle Diagnostic not clearing for new simulation

### ISSUE THREAD

**Issue by ThatEpicDude** [SmileiPIC/Smilei#371]
## Description

Hello,
I have come across what seems to be a curious bug. When using the time selection `every` in `DiagTrackParticles` I tried to select one timestep only using 

```
every = [timestep, timestep, 0]
```
as the `[start, stop, repeat]` syntax. When loading the simulation everything seems to have worked and only one timestep is loaded. However, if I go back to the namelist file and change the timestep I want to record, redo the simulation and try to load again, happi still loads the timestep from the first simulation. If I take care to delete all files in the folder except for the namelist before starting the second simulation the correct timestep is loaded.

I have reproduced this error using the Thermal Plasma tutorial file. I shall attach it as a text file. Making changes to `testfunction` should showcase the problem.

## Parameters

- Smilei version bcfe2802-bmaster
- Computing resources
  - MacBook Pro
  - macOS Big Sur
  - Python version 3.8.5
  - Input file:
[thermal_plasma_1d copy.txt](https://github.com/SmileiPIC/Smilei/files/6028261/thermal_plasma_1d.copy.txt)

**Comment by mccoys** [comment]
It is generally considered that an empty directory is needed for the output of the simulation. Some file conflicts have been reported and there is limited management for overwriting files. I am not sure this should be considered as a bug...

**Comment by ThatEpicDude** [comment]
I see, thank you for your reply.

**Comment by mccoys** [comment]
Ah. I have understood your issue.

Happi creates a file when opening the tracked particles diagnostic. If the file exists already, then it will not create it, so it will remain in the same state as with your previous simulation. You must remove all `TrackParticles_**.h5` files from tracked particles before using happi again. DO NOT REMOVE files named `TrackParticlesDisordered_**.h5`. Unfortunately, I do not see how this could be automated as the files created by happi are not supposed to be overwritten.

In general, it is recommended to use an empty directory anyways
