### ISSUE TITLE
current problem

### ISSUE THREAD

**Issue by fachernikov** [SmileiPIC/Smilei#376]
Dear developers, 

I tried to calculate current in 1D simulation, in front of expanding plasma. I decided to use CurrentFilter to reduce noises. I expected that it will both deal with Field and Probe diagnostic equally. However, results were different and that function reduced noises for Fields diagnostic but for Probe it worked differently. The question is how does this CurrentFilter diagnostic work with Probe diagnostic? 
Thank you for your time.

![without_CF](https://user-images.githubusercontent.com/63446538/110660090-4542fd00-81d4-11eb-824a-dab0b75a1078.png)
![with_CF](https://user-images.githubusercontent.com/63446538/110659925-1462c800-81d4-11eb-97e4-a26b8d982f10.png)
![Probe_with_CurrentFilter](https://user-images.githubusercontent.com/63446538/110659915-1036aa80-81d4-11eb-9b41-6e6ed991df30.png)
![Probe_without_CF](https://user-images.githubusercontent.com/63446538/110660117-4b38de00-81d4-11eb-8b7a-9edc50df7fd4.png)

**Comment by mccoys** [comment]
You plot vs space for fields, then vs time for probes. Are you sure this is a good comparison ?

**Comment by fachernikov** [comment]
Indeed, comparison isn't fully relevant.

**Comment by mccoys** [comment]
Then please show the correct comparison. Currently, it is not clear whether there is a problem or not.

**Comment by fachernikov** [comment]
Give me a little more time please.

**Comment by mccoys** [comment]
Of course !

I did not close the issue. The tag is only here for us to see it is in progress.

**Comment by mccoys** [comment]
@fachernikov I am closing this issue as it has been 2 months without news. Feel free to reopen it when you have new material.
