### ISSUE TITLE
I can't save data into a VTK file

### ISSUE THREAD

**Issue by obudriga** [SmileiPIC/Smilei#378]
## Description

I'm sorry, but after I had copied the modified Utils.py file I've encountered the same issue.
I couldn't save 2D and 3D data into a VTK file.

If available, copy-paste faulty code, warnings, errors, etc.

```

----> 1 s.ParticleBinning(0,export_dir="protdens").toVTK(1)

/home/olimpia/smilei/happi/_Diagnostics/Diagnostic.pyc in toVTK(self, numberOfPieces)
    879                         for itime in range(ntimes):
    880                                 data[:,:,itime] = self._dataAtTime(self._timesteps[itime])
--> 881                         arr = vtk.Array(self._np.ascontiguousarray(data.flatten(order='F'), dtype='float32'), self._title)
    882
    883                         # If all timesteps are regularly spaced

/home/olimpia/smilei/happi/_Utils.pyc in Array(self, data, name)
    720
    721                 else:
--> 722                         raise Exception("In Array: Unknown data type for data ("+str(data.dtype)+")")
    723
    724

Exception: In Array: Unknown data type for data (float32)
```

## Steps to reproduce the problem

If relevant, provide a step-by-step guide

## Parameters

- Smilei version: last version
- Input file ?
- Computing resources
  - type of computer: intel xenon server 
  - OS: linux
  - C++ compiler (to get some information `g++ --version`): g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
  - MPI version (`mpic++ --version`, `mpic++ -show`):
  - HDF5 version (`h5cc --version`):
  - Python version (`python --version`): Python 2.7.5
  - ...

**Comment by mccoys** [comment]
This is clearly not the last version of the file `_Utils.py`. You must have made a mistake while downloading the file. Remember to close python and reopen. Try also `make happi` in case it still does not work.

Note also that you are using a very old version of python. It is deprecated and basic libraries like `numpy` have dropped support a while ago. Smilei will also switch to python 3.* at some point in the near future.

**Comment by obudriga** [comment]
I was able to save the data into a VTK file after I'd run _make happi_. 
Thank you very much for your help.
