### ISSUE TITLE
Scalar diagnostic related issue

### ISSUE THREAD

**Issue by Sonuphd** [SmileiPIC/Smilei#380]
Respected Sir,

How to plot three different simulation data in the same figure with a scalar diagnostic for comparison of results.

**Comment by Z10Frank** [comment]
Hello, 
you can use the function `multiPlot()` of `happi` as explained in the doc https://smileipic.github.io/Smilei/post-processing.html

**Comment by Sonuphd** [comment]
Respected Sir,

 I know about this command but I need to show mutliple line plots  in the same figure.

**Comment by mccoys** [comment]
It will do exactly that. If it does not, please provide the commands you use.

**Comment by Sonuphd** [comment]
Respected Sir,

I am using the command happi.multiPlot(diag1,diag2,diag3,diag4,shape=[2,2]) but how to use this command for three different simulation directory. I want to compare my results of three different simulations. Please solve my problem. I am attaching three figures and I want to merge with one figure.

![Figure_24](https://user-images.githubusercontent.com/42186182/111450260-3b6e4c00-8736-11eb-8855-6a253febeeb7.png)
![Figure_22](https://user-images.githubusercontent.com/42186182/111450446-6658a000-8736-11eb-9694-f76396dc6245.png)
![Figure_122png](https://user-images.githubusercontent.com/42186182/111450578-88eab900-8736-11eb-9ead-3f29dfe52e0d.png)

**Comment by Sanjeev273** [comment]
Use the command : happi.multiPlot(diag1,diag2,diag3,diag4)

> 
> 
> Respected Sir,
> 
> I am using the command happi.multiPlot(diag1,diag2,diag3,diag4,shape=[2,2]) but how to use this command for three different simulation directory. I want to compare my results of three different simulations. Please solve my problem. I am attaching three figures and I want to merge with one figure.
> 
> ![Figure_24](https://user-images.githubusercontent.com/42186182/111450260-3b6e4c00-8736-11eb-8855-6a253febeeb7.png)
> ![Figure_22](https://user-images.githubusercontent.com/42186182/111450446-6658a000-8736-11eb-9694-f76396dc6245.png)
> ![Figure_122png](https://user-images.githubusercontent.com/42186182/111450578-88eab900-8736-11eb-9ead-3f29dfe52e0d.png)
Use the command : happi.multiPlot(diag1,diag2,diag3,diag4)

**Comment by Sanjeev273** [comment]
Use the command : happi.multiPlot(diag1,diag2,diag3,diag4)

**Comment by Sonuphd** [comment]
Respected Sir,

These three plots have three different directory and how to visualize in same figure. When we import 
S=happi.Open("/home/sonu/LWFA8") for 
![image](https://user-images.githubusercontent.com/42186182/111453652-ce5cb580-8739-11eb-9acc-010ca8c844fc.png)
S=happi.Open("/home/sonu/LWFA9") for 
![image](https://user-images.githubusercontent.com/42186182/111453734-e92f2a00-8739-11eb-9ca7-f33bc117bc49.png)
S=happi.Open("/home/sonu/LWFA10") for 
![image](https://user-images.githubusercontent.com/42186182/111453828-019f4480-873a-11eb-81ec-67e57935cd1e.png)

**Comment by mccoys** [comment]
You need to call your variables differently. For instance S1,S2,S3 instead of only S

**Comment by Sanjeev273** [comment]
> 
> 
> Use the command : happi.multiPlot(diag1,diag2,diag3,diag4)
> 
> > Respected Sir,
> > I am using the command happi.multiPlot(diag1,diag2,diag3,diag4,shape=[2,2]) but how to use this command for three different simulation directory. I want to compare my results of three different simulations. Please solve my problem. I am attaching three figures and I want to merge with one figure.
> > ![Figure_24](https://user-images.githubusercontent.com/42186182/111450260-3b6e4c00-8736-11eb-8855-6a253febeeb7.png)
> > ![Figure_22](https://user-images.githubusercontent.com/42186182/111450446-6658a000-8736-11eb-9694-f76396dc6245.png)
> > ![Figure_122png](https://user-images.githubusercontent.com/42186182/111450578-88eab900-8736-11eb-9ead-3f29dfe52e0d.png)
> > Use the command : happi.multiPlot(diag1,diag2,diag3,diag4)


Its simple 
S1 = happi.Open("/home/sonu/LWFA8") 
S2 = happi.Open("/home/sonu/LWFA9")
S3 = happi.Open("/home/sonu/LWFA10")
 Then 
Diag1 = S1.Scalar(....)  
Diag2 = S2.Scalar(....)
Diag3 = S3.Scalar(....)

**Comment by Sonuphd** [comment]
Thank you very much sir. I have solved my problem.
