### ISSUE TITLE
Unable to allocate 9.42 MiB for an array with shape (5121, 241) and data type float64

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#381]
Hello Smilei team member,

I am trying to get the post simulation data for Field diagnostics using following command:
ex = s.Field(0,'Ex',units=units,moving=True).getData()
I got the following error in shown in the image. 
![getData](https://user-images.githubusercontent.com/67734147/111497096-bfc1ce80-8738-11eb-9c61-b4b29e3ab7d6.JPG)

Can you help me to resolve the issue?

- Smilei version:
- smilei 4.5

**Comment by iltommi** [comment]
This is a Python error not related to Smilei/Happi
