### ISSUE TITLE
Post - processing related

### ISSUE THREAD

**Issue by Sonuphd** [SmileiPIC/Smilei#382]
Respected Sir,

How to create legend command during post - processing. In smilei, no any instruction is given. Please add this command.

**Comment by Z10Frank** [comment]
Hello,
it is indeed in the documentation, for example in `Advanced Plotting Options`: https://smileipic.github.io/Smilei/post-processing.html#advancedoptions

In your diagnostic postprocessing you can use optional arguments that you would use with `matplotlib`: in your case `label` to create a legend.

For example:
```
Diag1 = S.Field.Field0("Ex", timesteps=1000, label = "Ex")
Diag1.plot()
```

Please read carefully the documentation on postprocessing.

**Comment by Sonuphd** [comment]
Thank you sir, problem solved.
