### ISSUE TITLE
Track particles diagnostic: select=[ID] error

### ISSUE THREAD

**Issue by Iuliana19** [SmileiPIC/Smilei#383]
Dear developers,

I have trouble using the select=[id] option of the Track particles diagnostic. I continue to crash into the following error message:
**Error: argument 'select' must be a string or a list of particle IDs**

In the input file, I defined the Track particles as:
###Track particles diagnostic###
def filter_track(particle):
    return (particle.px>0.)

DiagTrackParticles(
    species = "ion",
    every = 100,
    filter = filter_track,
    attributes = ["x", "px"]
)

I tried to select the particles ids as:
###post process track particles
import happi
import numpy as np
import matplotlib.pyplot as plt
S = happi.Open("./")

trackion = S.TrackParticles("ion", timesteps=6000).getData();
id = trackion['Id']
print(id)
S.TrackParticles("ion", select=id).plot()

And I got the output:
###Output
>>> trackion = S.TrackParticles("ion", timesteps=6000).getData();
Selecting particles ... (this may take a while)
Removing dead particles ...
Kept 73728000 particles
Loading data ...
   axis: Id
   axis: x
   axis: px
   axis: moving_x
Process broken lines ...
... done
>>> id = trackion['Id']
>>> print(id)
[[         1          2          3 ... 4319004835 4319004836 4319004837]]
>>> S.TrackParticles("ion", select=id).plot()
Diagnostic is invalid
Error: argument 'select' must be a string or a list of particle IDs

If I try to select only a few ids from id list, I get the same error:
>>> S.TrackParticles("ion", select=[4319004835,4319004836, 4319004837]).plot()  
Diagnostic is invalid
Error: argument 'select' must be a string or a list of particle IDs

Could you please tell me what is wrong? 

Smilei version: v4.4-706-gb5c12a5-master

Thank you!

Kind regards,
Iuliana

**Comment by mccoys** [comment]
This part has been changed recently. Could you update smilei ?

**Comment by Iuliana19** [comment]
I updated and now is working fine! Thank you very much!
I will close the issue
