### ISSUE TITLE
electron bunch energy spread and transverse normalize emittance

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#385]
Hi Smilei team Members, 

I am looking for the few more features for the high energy electron bunch acceleration. Is there any possibility to define the beam energy spread and the transverse normalized emittance ? To solve the realistic problems these are the important factor which have to be included in to the calculation.  Most of the PIC codes have a function to set the transverse energy spread and the emittance.  The smilei missing these two.  can you add them if possible? Thanks !

**Comment by Z10Frank** [comment]
Hello,
we are working on an easier way to initialise a relativistic electron bunch, but we still don't know how much time it will take to implement it, test it and release it. 

Meanwhile, you can use the already existing option of initialisation through `numpy` arrays that I have described in the Element chat room.

**Comment by Sanjeev273** [comment]
> 
> 
> Hello,
> we are working on an easier way to initialise a relativistic electron bunch, but we still don't know how much time it will take to implement it, test it and release it.
> 
> Meanwhile, you can use the already existing option of initialisation through `numpy` arrays that I have described in the Element chat room.

Thank you for the update. ! I tried through numpy array. When I defined the bunch profile through numpy array with large no. of particles (187500000), its required lots of memory to run the simulation. These large no. of particles we need to simulate the results for EuPraXiA project.

**Comment by mccoys** [comment]
In this case, please initialise the particles from a file. It is similar to numpy arrays, but each process will only load the necessary particles so that less memory is needed.
