### ISSUE TITLE
Unexpected change of particle momentum and position in Track Particles Diagnostic

### ISSUE THREAD

**Issue by Iuliana19** [SmileiPIC/Smilei#386]
Dear Smilei team,

I noticed a weird change of momentum and position of ions (green curve in ion image), respectively electrons (green&orange curve in electron image) in the px-x diagnostics from Track Particles.

![electron](https://user-images.githubusercontent.com/40409812/112464506-4182af00-8d6c-11eb-8ef9-a60a5548e5fd.png)
![ion](https://user-images.githubusercontent.com/40409812/112464519-45163600-8d6c-11eb-8a96-c0be85538f96.png)

Is this a numerical problem? Or could it be a physical explanation for it?

Thank you!

Kind regards,
Iuliana

**Comment by mccoys** [comment]
There was a bug in a previous version where particle IDs were not correctly passed. Maybe this is causing some strange jumps, actually because the diagnostic is following another particle.

Could you try with a newer version ?

**Comment by Iuliana19** [comment]
Thank you for your answer!

I am a bit confused now. Indeed the simulation was made with an older version of Smilei (v4.4-706-gb5c12a5-master). 

Now, do I need also to run again the simulation with the new version of Smilei in order to get rid of the problem?

**Comment by mccoys** [comment]
Yes. Unfortunately you need to run it again.

But I am a bit confused as the fix should have been done already in your version. Is it difficult for you to run again the simulation and check ?

**Comment by Iuliana19** [comment]
Ok, thank you!
I will run it again and check! I will let you know if the problem persists.

**Comment by Iuliana19** [comment]
Dear Smilei team,

I did not reproduce the problem with the new version of Smilei (or at least, I did not notice any strange trajectory so far). I will close the issue.

Thank you!
