### ISSUE TITLE
Invalid communicator problem

### ISSUE THREAD

**Issue by HaoPengYY** [SmileiPIC/Smilei#387]
Dear developers,

Hi. I managed to install SMILEI on the supercomputer, but when I run it on multicores,(the script can be run successfully on my PC), I got an error:
`Fatal error in PMPI_Comm_size: Invalid communicator, error stack:
PMPI_Comm_size(112): MPI_Comm_size(comm=0x92ba00, size=0x7fffa55e6d60) failed
PMPI_Comm_size(71).: Invalid communicator
`
I use gcc-7.5.0, openmpi-3.1.3 and hdf5-1.8.12, python-3.4.2.
Thanks in advance.

**Comment by mccoys** [comment]
Hello

Could you provide a bit more context:
* Does it fail for all attempts with different input files ?
* When does the error occur in the run ?
* What version of smilei ?

**Comment by mccoys** [comment]
You may also want to try and run a sample program to test your MPI installation:
https://github.com/open-mpi/mtt/blob/master/samples/python/mpi_hello_world.c

**Comment by HaoPengYY** [comment]
Dear @mccoys,
Thanks for your reply.  I tried with `mpi_hello_world.c`, it seem that the Slurm of the cluster does not want me to use openMPI, then I turn to `MPI/Intel/MPICH/3.2-icc2017-dyn` . Now `mpi_hello_world.c` is happy, but smilei is still not. I run two example scripts from the benchmarks folder of smilei: `tst2d_00_em_propagation.py`, `tst3d_00_em_propagation.py `, using the default command of the cluster: `yhrun -n 32 smilei benchmarks/input.py'. The number of cores equals to the patch number(32, 64, respectively). But I still got an error:
`
[][set_real_munmap_ptr] Error getting real munmap(). MVAPICH2 cannot run properly.
[][set_real_munmap_ptr] This error usually means that the program is linked with both static and shared MVAPICH2 libraries.
[][set_real_munmap_ptr] Please check your Makefile or your link command line.
`.

**Comment by mccoys** [comment]
Could you paste here the results of these commands ?
```
   git describe --all --long
   make config=verbose
   make env
   echo $LD_LIBRARY_PATH
   python -m sysconfig
   ldd smilei
```

**Comment by HaoPengYY** [comment]
OK. But the cluster here is not connected to internet, so git should not work.

1.For git:
`fatal: Not a git repository (or any parent up to mount point /WORK)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).`

2. For `make config=verbose`:
`make: Nothing to be done for `default'.`

3. For `make env`:
`SMILEICXX : mpicxx
PYTHONEXE : python
MPIVERSION :
VERSION : ??-??
OPENMP_FLAG : -fopenmp -D_OMP
HDF5_ROOT_DIR : /WORK/app/hdf5/1.8.12/00
SITEDIR : /WORK/szu_cjm_1/.local/lib/python3.4/site-packages
PY_CXXFLAGS : -I/WORK/app/Python/3.4.2/include/python3.4m -I/WORK/app/Python/3.4                                                                      .2/include/python3.4m -I/WORK/app/Python/3.4.2/lib/python3.4/site-packages/numpy                                                                      /core/include -DSMILEI_USE_NUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
PY_LDFLAGS : -lpython3.4m -lpthread -ldl -lutil -lm -Xlinker -export-dynamic
CXXFLAGS : -D__VERSION=\"??-??\" -D_VECTO -std=c++11 -Wall  -I/WORK/app/hdf5/1.8                                                                      .12/00/include -Isrc -Isrc/Patch -Isrc/Ionization -Isrc/ElectroMagn -Isrc/Projec                                                                      tor -Isrc/Python -Isrc/Profiles -Isrc/SmileiMPI -Isrc/Species -Isrc/ElectroMagnS                                                                      olver -Isrc/Pusher -Isrc/ParticleInjector -Isrc/Field -Isrc/ParticleCreator -Isr                                                                      c/Checkpoint -Isrc/Radiation -Isrc/Merging -Isrc/ElectroMagnBC -Isrc/Interpolato                                                                      r -Isrc/picsar_interface -Isrc/Tools -Isrc/Params -Isrc/DomainDecomposition -Isr                                                                      c/Collisions -Isrc/MultiphotonBreitWheeler -Isrc/Diagnostic -Isrc/MovWindow -Ibu                                                                      ild/src/Python -I/WORK/app/Python/3.4.2/include/python3.4m -I/WORK/app/Python/3.                                                                      4.2/include/python3.4m -I/WORK/app/Python/3.4.2/lib/python3.4/site-packages/nump                                                                      y/core/include -DSMILEI_USE_NUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D                                                                      _VECTO -O3 -g  -fopenmp -D_OMP
LDFLAGS : -L/WORK/app/hdf5/1.8.12/00/lib  -lhdf5 -L/WORK/app/Python/3.4.2/lib -l                                                                      pthread -ldl  -lutil -lm  -lpython3.4m -Xlinker -export-dynamic -lpython3.4m -lp                                                                      thread -ldl -lutil -lm -Xlinker -export-dynamic -lm -fopenmp -D_OMP`

4. For `echo $LD_LIBRARY_PATH`:
`/WORK/app/Python/3.4.2/lib:/WORK/app/hdf5/1.8.12/00/lib:/WORK/MPI/Intel/MPICH/3.2-icc2017-dyn/lib:/WORK/app/mpc/0.8.1/lib:/WORK/app/MPFR/2.4.2/lib:/WORK/app/gmp/4.3.2/lib:/WORK/app/gcc/6.3.0/lib64:/WORK/app/gcc/6.3.0/lib:/WORK/app/gcc/6.3.0/libexec:/WORK/app/MPI/Intel/MPICH/3.2-icc2017-dyn/lib:/WORK/app/intel/parallel_studio_xe_2017_update4/compilers_and_libraries_2017.4.196/linux/compiler/lib/intel64:/WORK/app/intel/parallel_studio_xe_2017_update4/compilers_and_libraries_2017.4.196/linux/mpi/intel64/lib:/WORK/app/intel/parallel_studio_xe_2017_update4/compilers_and_libraries_2017.4.196/linux/mpi/mic/lib:/WORK/app/intel/parallel_studio_xe_2017_update4/compilers_and_libraries_2017.4.196/linux/ipp/lib/intel64:/WORK/app/intel/parallel_studio_xe_2017_update4/compilers_and_libraries_2017.4.196/linux/compiler/lib/intel64_lin:/WORK/app/intel/parallel_studio_xe_2017_update4/compilers_and_libraries_2017.4.196/linux/mkl/lib/intel64_lin:/WORK/app/intel/parallel_studio_xe_2017_update4/compilers_and_libraries_2017.4.196/linux/tbb/lib/intel64/gcc4.4:/WORK/app/intel/parallel_studio_xe_2017_update4/debugger_2017/iga/lib:/WORK/app/intel/parallel_studio_xe_2017_update4/debugger_2017/libipt/intel64/lib:/WORK/app/intel/parallel_studio_xe_2017_update4/compilers_and_libraries_2017.4.196/linux/daal/lib/intel64_lin:/WORK/app/gcc/6.3.0/lib64:/WORK/app/gcc/6.3.0/lib:/WORK/app/gcc/6.3.0/libexec:/WORK/app/mpc/0.8.1/lib:/WORK/app/MPFR/2.4.2/lib:/WORK/app/gmp/4.3.2/lib:/WORK/app/hdf5/1.8.12/00/lib:/WORK/app/Python/3.4.2/lib:/WORK/app/git/1.8.3.1/lib64:/WORK/app/git/1.8.3.1/lib:/WORK/app/git/1.8.3.1/libexec:/WORK/szu_cjm_1/penghao/lib/splash/lib:/usr/lib64:/WORK/szu_cjm_1/jk/program/libX:/opt/intel/composer_xe_2013_sp1.2.144/compiler/lib/intel64:/opt/intel/mic/coi/host-linux-release/lib:/opt/intel/mic/myo/lib:/opt/intel/composer_xe_2013_sp1.2.144/mpirt/lib/intel64:/opt/intel/composer_xe_2013_sp1.2.144/ipp/../compiler/lib/intel64:/opt/intel/composer_xe_2013_sp1.2.144/ipp/lib/intel64:/opt/intel/mic/coi/host-linux-release/lib:/opt/intel/mic/myo/lib:/opt/intel/composer_xe_2013_sp1.2.144/compiler/lib/intel64:/opt/intel/composer_xe_2013_sp1.2.144/mkl/lib/intel64:/opt/intel/composer_xe_2013_sp1.2.144/tbb/lib/intel64/gcc4.4:/WORK/szu_cjm_1/lty/new/hdf5/lib`

5. For `python -m sysconfig`: it's just too long:
[python.txt](https://github.com/SmileiPIC/Smilei/files/6249201/python.txt)

6. For `ldd smilei`:
```

        linux-vdso.so.1 =>  (0x00007fff96b1e000)
        libhdf5.so.8 => /WORK/app/hdf5/1.8.12/00/lib/libhdf5.so.8 (0x00002ba314c                                                                      c0000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003d47400000)
        libdl.so.2 => /lib64/libdl.so.2 (0x0000003d47000000)
        libutil.so.1 => /lib64/libutil.so.1 (0x0000003d56400000)
        libm.so.6 => /lib64/libm.so.6 (0x0000003d47800000)
        libpython3.4m.so.1.0 => /WORK/app/Python/3.4.2/lib/libpython3.4m.so.1.0                                                                       (0x00002ba315501000)
        libmpicxx.so.12 => /WORK/app/MPI/Intel/MPICH/3.2-icc2017-dyn/lib/libmpic                                                                      xx.so.12 (0x00002ba315a9b000)
        libmpi.so.12 => /WORK/app/MPI/Intel/MPICH/3.2-icc2017-dyn/lib/libmpi.so.                                                                      12 (0x00002ba315cbe000)
        libstdc++.so.6 => /WORK/app/gcc/6.3.0/lib64/libstdc++.so.6 (0x00002ba316                                                                      1ea000)
        libiomp5.so => /WORK/app/intel/parallel_studio_xe_2017_update4/compilers                                                                      _and_libraries_2017.4.196/linux/compiler/lib/intel64/libiomp5.so (0x00002ba31657                                                                      e000)
        libgcc_s.so.1 => /WORK/app/gcc/6.3.0/lib64/libgcc_s.so.1 (0x00002ba31692                                                                      3000)
        libc.so.6 => /lib64/libc.so.6 (0x0000003d46c00000)
        libz.so.1 => /lib64/libz.so.1 (0x0000003d47c00000)
        librt.so.1 => /lib64/librt.so.1 (0x0000003d48000000)
        libimf.so => /WORK/app/intel/parallel_studio_xe_2017_update4/compilers_a                                                                      nd_libraries_2017.4.196/linux/compiler/lib/intel64/libimf.so (0x00002ba316b3a000                                                                      )
        libsvml.so => /WORK/app/intel/parallel_studio_xe_2017_update4/compilers_                                                                      and_libraries_2017.4.196/linux/compiler/lib/intel64/libsvml.so (0x00002ba3170270                                                                      00)
        libirng.so => /WORK/app/intel/parallel_studio_xe_2017_update4/compilers_                                                                      and_libraries_2017.4.196/linux/compiler/lib/intel64/libirng.so (0x00002ba317f410                                                                      00)
        libintlc.so.5 => /WORK/app/intel/parallel_studio_xe_2017_update4/compile                                                                      rs_and_libraries_2017.4.196/linux/compiler/lib/intel64/libintlc.so.5 (0x00002ba3                                                                      182b6000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003d46800000)
        libcilkrts.so.5 => /WORK/app/gcc/6.3.0/lib64/libcilkrts.so.5 (0x00002ba3                                                                      18522000)
        libifport.so.5 => /WORK/app/intel/parallel_studio_xe_2017_update4/compil                                                                      ers_and_libraries_2017.4.196/linux/compiler/lib/intel64/libifport.so.5 (0x00002b                                                                      a31873e000)
        libifcoremt.so.5 => /WORK/app/intel/parallel_studio_xe_2017_update4/comp                                                                      ilers_and_libraries_2017.4.196/linux/compiler/lib/intel64/libifcoremt.so.5 (0x00                                                                      002ba31896e000)
```

**Comment by iltommi** [comment]
Hi, it's indeed a very strange error. 
To me it looks like MVAPICH2 might be the issue since that's behind he mpi wrapper. One guess is that hdf5 and smilei do not share the same mpi libraries.

Would it be possible to compile this simple hdf5+mpi

```
mpicxx -fopenmp -I/WORK/app/hdf5/1.8 .12/00/include -L/WORK/app/hdf5/1.8.12/00/lib -lhdf5 test.cpp -o test
```


[test.txt](https://github.com/SmileiPIC/Smilei/files/6249645/test.txt)

(sorry I had change the extension of the file from cpp to txt to upload it here...)

**Comment by HaoPengYY** [comment]
@iltommi 
Thanks for reply. I tried to compile `test.cpp`, it did succeed.

**Comment by iltommi** [comment]
@HaoPengYY sorry for this late reply. 
You did compile on the frontal and submitted this `test` executable via the submission queue?

**Comment by HaoPengYY** [comment]
@iltommi I tried to submit `test`, I got the same error when I submit smilei, i.e.
`[][set_real_munmap_ptr] Error getting real munmap(). MVAPICH2 cannot run properly. [][set_real_munmap_ptr] This error usually means that the program is linked with both static and shared MVAPICH2 libraries. [][set_real_munmap_ptr] Please check your Makefile or your link command line.`

**Comment by iltommi** [comment]
This a good news we're going in the right direction, but we still have the problem though... 

It looks like it's a problem in the compile tool-chain / environment .

**Next step:**
Now could you try to compile and run in the submission file?
This might prevent some configuration mismatch between the frontal machine (the one you log into) and the computing node behind (the one where the code runs)

**If this does not work**, I would suggest to ask the computing center admins to help you in either compiling smilei or at least give you the compile flag for the `test.cpp` since 

```
mpicxx -fopenmp -I/WORK/app/hdf5/1.8 .12/00/include -L/WORK/app/hdf5/1.8.12/00/lib -lhdf5 test.cpp -o test
```

is clearly not enough. 
They should be able to tell you the best combination of compilers/flags/environment variables for this.

Good luck (these are annoying problems that pop-up from time to time)
