### ISSUE TITLE
Diag for multiple runs

### ISSUE THREAD

**Issue by phi-kafka** [SmileiPIC/Smilei#389]
Hi guys,
I have a big 3D PIC in several runs with restarts. So, I have several output directories with data: "Run_0", "Run_1", "Run_3"...
One of my Field diagnostics (Field0) has an output only for initial times, so it writes data to "Run_0" only. When postprocessing, I read the simulation from the whole set "./Run_*", it seems OK. But when I then read the fields or times from Field0, it says that there is no valid data:
>Diagnostic is invalid
>String Ex does not seem to include any field

It looks as it uses the last "Run" for reading the data, where indeed there is no output. When I do the same, just reading "Run_0", it works fine. Is it something which I missed or how to explain happi to look through the whole set of simulation directories?

**Comment by mccoys** [comment]
Indeed, happi expects to have data in all runs so it will not be happy in that situation. I will fix it when possible. In the meantime, please open only `Run_0`.

**Comment by phi-kafka** [comment]
Ok, thanks, mccoys.

**Comment by mccoys** [comment]
The last push should fix this issue. Please reopen if necessary.
