### ISSUE TITLE
Corruption of some specific DiagParticleBinning

### ISSUE THREAD

**Issue by a-beth** [SmileiPIC/Smilei#390]
Dear developers,

I have performed a few Smilei simulations for a while without issues with the diagnostics but recently I wanted to check the phase-space plot (x vs vx) for ions and electrons.

## Description
I have added blocks like this one in the code for phase-space:

start_print = 1
t_print_10  = 1000
.....

DiagParticleBinning(
    name="phase_electron_vx",
    deposited_quantity = "weight",
    every = [start_print, t_print_10 ],
    time_average = 1,
    species = ["H2O_e"],
    axes = [ ["x",    14500*dx,   21200*dx,    6700],
             ["vx",   -0.2,   0.2,    100] ]
) 
It is for a 1D simulation. dx is the cell length in SMILEI units. 
I do not get any error messages and the simulation runs (cf. attached slurm file). However, these DiagParticleBinning seem `corrupted': at some timesteps (looks random), the diagnostic gives erroneous values (like zeros, large values or even negative values) over the whole plot or a part of it (see example, vertical blue bar means it is only zero). The errors are not linked to the position x. When I zoom in, the rows at the limit of the blue area are partially filled. Also, it happens at different timesteps, depending on the species or the kind of phase-space (x,vx) or (x,vy). Plots have been made with MATLAB. 
![example1](https://user-images.githubusercontent.com/15929591/114189966-13e05d00-994b-11eb-860e-a754cd94f72c.jpg)
![example2](https://user-images.githubusercontent.com/15929591/114189973-16db4d80-994b-11eb-872c-093ed983ebd0.jpg)

I do not have any issues with other DiagParticleBinning such as pressure or densities or (vx,vy) plots for example.

## Parameters

-Version : bv4.5-370-ga59b829-bmaster
-Ressources: simulation performed over 10 nodes https://www.hpc2n.umu.se/resources/hardware/kebnekaise#compute-nodes
-Output file
[slurm-12517126.txt](https://github.com/SmileiPIC/Smilei/files/6286075/slurm-12517126.txt)

Do you have any idea of the cause?

Arnaud

**Comment by mccoys** [comment]
Hi,

This bug seems very unlikely given the type of diagnostic. It is not written in parallel. I can only imagine there is an issue with the data transfer to the filesystem which is handled by the HDF5 library. Which version do you use ? Is it possible for you to try another version ?

Could you also provide a minimal input file so that we can try to reproduce the bug ?

**Comment by a-beth** [comment]
Hi, 

thank you for your quick answer. I see. 

The details are in the slurm file I attached: HDF5/1.10.1.

I just checked and there are other available versions on the cluster:
HDF5/1.10.5         HDF5/1.8.11         HDF5/1.8.18         
HDF5/1.10.2         HDF5/1.10.6         HDF5/1.8.17         HDF5/1.8.19 

I will try with another version.

I have attached the input file:
[input_script.txt](https://github.com/SmileiPIC/Smilei/files/6286809/input_script.txt)

**Comment by mccoys** [comment]
@a-beth The case you submitted is not quite a minimal example (>130 million particles). Could you try to reproduce the error on a smaller example ?

**Comment by a-beth** [comment]
Hi,

at the moment, I am doing the same run with HDF5/1.10.2 instead of HDF5/1.10.1. So far, no errors at the moment. It seems you were right. I will update once finished.

**Comment by a-beth** [comment]
My run went well without any issue. As I have changed HDF5 version, I also changed versions of Python, OpenMPI, and GCC because of dependencies on the cluster.

Problem solved I guess. Thanks for your help.
