### ISSUE TITLE
SDMD generates a segmentation fault when not enough ghost cells are present.

### ISSUE THREAD

**Issue by DoubleAgentDave** [SmileiPIC/Smilei#391]
## Description

When you put an interpolation order of 4, and leave the SDMD ghost cells setting at the default value of 2 you get a pretty tricky error to understand:

```
#5 Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in
#4 Object "/scratch/07303/drblackm/plasma_mirror_reflect/density_test_o/smilei", at 0x4623a8, in
#3 Object "/lib64/libc.so.6", at 0x2b650606a3d4, in __libc_start_main
#2 Object "/scratch/07303/drblackm/plasma_mirror_reflect/density_test_o/smilei", at 0x5d9de7, in main
#1 Object "/scratch/07303/drblackm/plasma_mirror_reflect/density_test_o/smilei", at 0x5e0bf3, in DoubleGrids::syncCurrentsOnRegion(VectorPatch&, Region&, Params&, SmileiMPI*, Timers&, int)
#0 Object "/scratch/07303/drblackm/plasma_mirror_reflect/density_test_o/smilei", at 0x92beb7, in Field3D::add(Field*, Params&, SmileiMPI*, Patch*, Patch*)
Segmentation fault (Address not mapped to object [0x80564c920])
```

## Steps to reproduce the problem

put:
    interpolation_order = 4,
in Main()
then either put:
MultipleDecomposition(
    region_ghost_cells = 2
)
or just:
MultipleDecomposition()
later in the input file and you get this error.

I'd make a tentative suggestion that this 'bug' should raise an error that's a bit easier for an idiot like myself to understand, or that the default is changed from just 2 to be dependent on the 'interpolation' variable. I completely missed the default setting in the namelist section in the documentation in my excitement in trying this SDMD stuff out.

**Comment by mccoys** [comment]
The last push should fix this issue. Please reopen if necessary.
