### ISSUE TITLE
SDMD reinitialising laser periodically

### ISSUE THREAD

**Issue by DoubleAgentDave** [SmileiPIC/Smilei#394]
When SDMD is switched on Smilei prints that the laser field has been initialised multiple times. e.g.
For this simulation it was at ~100 timesteps intervals

```
    680/4043     1.1889e+02     3.8997e+02   (  1.3942e+01 )     -2147483648
    690/4043     1.2063e+02     3.9424e+02   (  4.2777e+00 )     -2147483648


 Initializing laser parameters
 --------------------------------------------------------------------------------
        [WARNING] Laser #0: space-time profile defined, dismissing time_envelope space_envelope omega chirp_profile phase
                Laser #0: space-time profile
                        first  component : 3D user-defined function
                        second component : 3D user-defined function

    700/4043     1.2238e+02     3.9858e+02   (  4.3399e+00 )     -2147483648
    710/4043     1.2413e+02     4.0286e+02   (  4.2720e+00 )     -2147483648
    720/4043     1.2587e+02     4.0717e+02   (  4.3086e+00 )     -2147483648
```
turn on SDMD and have a laser. The laser field seems to be solved identically with or without SDMD so this doesn't appear to do anything serious affecting results or the time taken to complete the simulation, which is to be expected in the case where there are no particles. Though I can't actually tell if it is actually reinitialising the laser field every time it prints as my laser field is pretty simple. If it is, this might become a performance issue where you have complex laser field intialisations. I had previously submitted, and closed, this bug as I thought it was due to a misconfigured field, however it happens regardless of laser field shape. 

I have attached a namelist.
[laser_test_field.txt](https://github.com/SmileiPIC/Smilei/files/6307664/laser_test_field.txt)

And some output from stdout:
[out.txt](https://github.com/SmileiPIC/Smilei/files/6307665/out.txt)

There is nothing in stderr.

 HDF5 version 1.10.4
 Python version 3.7.0
 Smilei bv4.6-16-g2ebb17f6a-bmaster

**Comment by mccoys** [comment]
This is due to sdmd regions rebuilding periodically the fields (thus the last object) to find a better mapping with patches. We did not remove the printout yet

**Comment by mccoys** [comment]
I cannot find the commit that is displayed in the repository. Are you using a local fork?

**Comment by DoubleAgentDave** [comment]
I just used 'git clone ...' ? I guess if it's just a printout it's not really a big bug.

**Comment by mccoys** [comment]
The last push should fix this issue. Please reopen if necessary.
