### ISSUE TITLE
Finite length for constant density profile

### ISSUE THREAD

**Issue by Sonuphd** [SmileiPIC/Smilei#395]
Respected Sir,

I want to use a constant density profile with an appropriate length How to use a finite length for this density.

**Comment by MickaelGrech** [comment]
Hello @Sonuphd , when you have simple questions as this one, I would suggest you drop a message in the [Element Chatroom](https://app.element.io/#/room/!LQrdVpOJEohPSWMlmf:matrix.org). 
Also, I have seen that many of the questions you ask can find an answer in the online documentation of Smilei.
This is the case for this one, and I will answer your question at the end of the message.

Before I do so, however, I strongly encourage you to:
 (i) read carefully the documentation before posting an issue, 
(ii) follow the [online tutorials](https://smileipic.github.io/tutorials/), you'll find a lot of exercises on the basics of PIC simulation, but also on how to tune your simulation for performance, or more advanced studies involving collisions, QED processes, etc.

Now, back to your question, as discussed in the doc ([here](https://smileipic.github.io/Smilei/namelist.html#species)), `number_density` or `charge_density` can take any function/profile you may want to define.
How to build a profile is discussed [here](https://smileipic.github.io/Smilei/profiles.html). 
In your case, you could do use, as an example, `number_density = myOwnProfile` in the Species block, with `myOwnProfile` a profile you define yourself in your python script, e.g. in the form (here for a 1D simulation):
```
def myOwnProfile(x):
        if (x>x0):
            return n0
        else:
            return 0.
```

**Comment by Sonuphd** [comment]
Thank you, sir
