### ISSUE TITLE
Poynting flux in probe diagnostics?

### ISSUE THREAD

**Issue by iplasma** [SmileiPIC/Smilei#396]
Thank you for making such a great code!

I would like to get the Poynting flux and its time integral at a location inside the box, but it seems this is only possible at the boundary.  

Current I am dumping the fields at each step in order to get the flux and then do the integral.

Would it be possible to add such quantities to the probe diagnostics? I took a casual look into the source code and think this may be the case.

**Comment by mccoys** [comment]
It is actually better to calculate it from probe fields during post processing. In happi, you can  easily compute operations between fields

**Comment by iplasma** [comment]
Dumping fields at each step affects the performance dramatically on our cluster. In my test, dumping two slices of field probe at each step (with flush_every set to about 300 steps, the width of the slice is only 1 cell) in a 2D simulation makes it 6 times slower compared to the case without these two field probes. In this case, I have not turned on the plasma, so I expect with plasma the slow down may be less significant. But still it may be best to avoid such performance degradation as IO is likely to further lag behind the increase of FLOPS in future platforms. 

Another possibility is that if the field values can be assessed in python, maybe it will also user to do any diagnostics from input deck. Just a thought and I am not sure how easy to make the fields available in python.

**Comment by mccoys** [comment]
Indeed you should use Probe instead of Field for better performance. Still you can compute the Poynting flux in post processing using probes.

I don't understand what you mean by available in python

**Comment by mccoys** [comment]
Sorry I completely misread your initial message specifying that you need the integral. This is currently not possible but we will think about it

**Comment by iplasma** [comment]
Thank you for looking into this. 

For the question about python, I mean exposing the fields to the python interpreter, e.g., via pybind.

**Comment by mccoys** [comment]
Hi,
I have added the possibility to have the Poynting flux in Probes and they can be time-accumulated. Note that it may be slow when too many points are requested because this operation is done at every timestep.
