### ISSUE TITLE
Electron dense square in motion (with turned off possion solver)

### ISSUE THREAD

**Issue by smontefiori** [SmileiPIC/Smilei#397]
Hi dear developers,
I am new to Smilei and I am truly sorry to bother you with what you will surely deem to be a silly question. Nonetheless, being unable to find an explanation to it by myself, I am almost forced to turn to you.

The matter here is quite simple: I've launched a two-dimensional simulation (the namelist is in the attachments down below) of a "high density electron square" (I apologize for the quotes, but I think there's no better way to describe it) moving along the x direction. I turned off the classical and relativistic poisson solvers, thus I expected my electron square to trivially move alltogether towards increasing x... Instead, I witness this as strange as charming unphysical behaviour:
- the square undergoes an abrupt deceleration, remaing almost in the same spot throughout the entire simulation
  first timestep
![0 0](https://user-images.githubusercontent.com/83040284/115790560-318bd880-a3c7-11eb-8b05-c772c8c34db6.png)
  last timestep
![4992 0](https://user-images.githubusercontent.com/83040284/115790681-64ce6780-a3c7-11eb-8d89-84dff3295ae8.png)

-the velocities as well behaves strangely
  first timestep
![0 0](https://user-images.githubusercontent.com/83040284/115790822-9fd09b00-a3c7-11eb-9547-328d5be1d424.png)
  laste timestep
![4992 0](https://user-images.githubusercontent.com/83040284/115790854-af4fe400-a3c7-11eb-9dc9-d22acd8bfe0d.png)

- finally, the x and y electric fields remain a puzzle to me
   first timestep
![416 0](https://user-images.githubusercontent.com/83040284/115790980-ede59e80-a3c7-11eb-965a-a75775dfdc31.png)
   last timestep
![4992 0](https://user-images.githubusercontent.com/83040284/115791041-0655b900-a3c8-11eb-92e4-0d253171811c.png)

I am sure I am missing something stupid but, so far, I did not manage to find any clue. So, please let me know if you have any advice or explanation to give me. I attach here under the namelist and the plotting scripts I used (together with the plots themselves).

Thank you in advance for your time and kindness
[moving solid e square no poisson vx.zip](https://github.com/SmileiPIC/Smilei/files/6361555/moving.solid.e.square.no.poisson.vx.zip)
.

**Comment by mccoys** [comment]
I am not sure about the exact reason, but maybe you have a current above the Alfven current ?

Note also that a quick change of current will act like an antenna, thus producing fields and maybe slowing down electrons.

**Comment by MickaelGrech** [comment]
I've had a quick look at your input file.
There are 2 weird stuffs in there that may explain your results.

First, you use a single electron species and then do not solve Poisson's equation at time t=0.
As a result, your code behaves as if there was a neutralizing background that recalls your electrons.
Hence, I guess your electrons will just oscillate around this neutralizing background.
Can you check if it is the case?
If so, then your oscillating electrons are just behaving as an antenna.

Second, you electron density of 10^{26} is insanely large and doesn't make much sense.
You have to identify the characteristic frequency of your problem, here I would say the plasma frequency associated to your bunch density.
Then you use this frequency as a reference frequency, and normalized all your quantities accordingly (see [here ](https://smileipic.github.io/Smilei/units.html) for details). In your case, this would corresponding to putting density 1, and note 10^26. 
Note that this is important not to have the code deal with numbers that are either really small or really large.
So  it is good practice, but I'm not sure it explains what you see. Certainly my 1st point is more important on this aspect.

**Comment by smontefiori** [comment]
Thank you so much for both your quick responses! I will launch some simulations to test your advices as soon as I can. Then I will update you with the results.

I'll be in touch soon.

**Comment by smontefiori** [comment]
Ok, @MickaelGrech @mccoys  I think you were right about the background causing the antenna behaviour.

First, I've relaunched the exact same simulation in which I extended the velocity binning interval to [-1., 1.] (along both x and y direction). This allows us to see the following velocity evolution:
1st timestep
![0 0](https://user-images.githubusercontent.com/83040284/115936977-fa84f800-a496-11eb-9d6b-86b1d1657aee.png)
2nd ts
![416 0](https://user-images.githubusercontent.com/83040284/115936991-040e6000-a497-11eb-8758-5b59e12168d0.png)
3rd ts
![832 0](https://user-images.githubusercontent.com/83040284/115937001-0d97c800-a497-11eb-912f-e348eb2bd889.png)
final ts
![4992 0](https://user-images.githubusercontent.com/83040284/115937022-1be5e400-a497-11eb-9bf8-77202d936a19.png)

I also added a trackParticle diagnosis module, with which I planned to follow the trajectory of a small subset of the electrons inhabiting my square bunch. Unfortunately, though, the trajectories resulted in something like this
![electron_traj_4](https://user-images.githubusercontent.com/83040284/115937223-a7f80b80-a497-11eb-8d03-65a8bc058780.png)
maybe I choose the wrong diags and plots to prove you were right, so please, if you know some other technique to be more efficient, tell me without hesitation (I'm here to learn, afterall)

However, this almost unsuccessful attempt gave me another idea. In fact, in the same conditions of turned off poisson solvers, I prepared a single particle simulation (see namelist [single_free_hevily_charged_electron.txt](https://github.com/SmileiPIC/Smilei/files/6368446/single_free_hevily_charged_electron.txt)), where a particle having the same electron mass but an electric charge a hundreds of times greater was initially moving along the x direction. Even in this case, our "fake electron" suffers a brusque halt. Here you are the vx binning plot
1st ts
![0 0](https://user-images.githubusercontent.com/83040284/115937961-7718d600-a499-11eb-8767-629bd1f898bb.png)
2nd ts
![125 0](https://user-images.githubusercontent.com/83040284/115937972-7f711100-a499-11eb-9838-b2b3d033acc5.png)
3rd ts
![250 0](https://user-images.githubusercontent.com/83040284/115937981-87c94c00-a499-11eb-98ff-134f03bb04d3.png)
4th ts
![375 0](https://user-images.githubusercontent.com/83040284/115938090-d4148c00-a499-11eb-92db-553fc726265d.png)
and so on. I know that from here it may appear unclear, but by looking at the entire set of plots as they were movie frames (see zip 
[vx.zip](https://github.com/SmileiPIC/Smilei/files/6368493/vx.zip)) the oscillation is evident. This causes the particle to emit an EM wave, whose initial timestep's electric and magnetic fields are plotted down below (see [Ex.zip](https://github.com/SmileiPIC/Smilei/files/6368486/Ex.zip) and [Bz.zip](https://github.com/SmileiPIC/Smilei/files/6368484/Bz.zip) for the overall evolution)
Ex 1st ts
![125 0](https://user-images.githubusercontent.com/83040284/115938767-01fad000-a49c-11eb-8692-1eae8bf3744d.png)
Bz 1st ts
![125 0](https://user-images.githubusercontent.com/83040284/115938798-25be1600-a49c-11eb-8174-6333823b65f5.png)

Well, I think the mistery has been revealed... Nonetheless, before closing the issue I have one more question: If I ran the last single particle simulation with a proper electron (that is a particle with charge = -1.0) the ensuing background recall force acting on it would be much weaker than that experienced by the "fake electron" (charge = -100.0), thus letting the proper electron escape from the grid. This would not be a problem, of course, but since I imposed period boundary conditions (same namelist as above with species.charge = -1.0) on both x and y direction, I expected the electron to appear on the left side of the simulation box whenever it exits from the right. Instead it seems to vanish... In order to understand what I mean, see how the charge density map evolves, timestep after timestep, on leaving the grid (the particle is the little point on the rigth):
![1000 0](https://user-images.githubusercontent.com/83040284/115940140-bdbdfe80-a4a0-11eb-84bf-d1df6a0a7768.png)
![1125 0](https://user-images.githubusercontent.com/83040284/115939633-01b00400-a49f-11eb-90cd-8e766c1bd82c.png)
![1250 0](https://user-images.githubusercontent.com/83040284/115939650-0bd20280-a49f-11eb-8291-0eff48b7cebe.png)
![1375 0](https://user-images.githubusercontent.com/83040284/115939662-14c2d400-a49f-11eb-8ad9-68cdb664d06b.png)
and the charge density map remains blank until the very end of the simulation ([Rho.zip](https://github.com/SmileiPIC/Smilei/files/6368602/Rho.zip), [electron_Bz.zip](https://github.com/SmileiPIC/Smilei/files/6368607/electron_Bz.zip), 
[electron_Ex.zip](https://github.com/SmileiPIC/Smilei/files/6368610/electron_Ex.zip))... how do you explain that? I mean: even if the reentering electron interacts with EM field now present throughout the grid, it should at least be taken into account in the total charge density calculation, shouldn't it?

Thank you again, and please forgive the large amount of pictures and zip I attached.

**Comment by MickaelGrech** [comment]
In the Main() block, you have used "Silver-Muller" boundary conditions (BCs) which are not compatible with "periodic" BCs on particles. Try using "periodic" in the Main() block too.

**Comment by smontefiori** [comment]
Yes, you were right. I did not understand the species' and the EM's BCs had to be compatible  while reading the docs. I mean: thought they were sort of independent... Well, I guess I missed this subtelty. Thank you again for all your help, I will surely come back with more questions soon (I hope this is right place to ask them).

Issue closed.
