### ISSUE TITLE
unexpected drift acquired by a charged particle in magnetic field

### ISSUE THREAD

**Issue by smontefiori** [SmileiPIC/Smilei#398]
Hi dear developers,
I've run into another trivial "problem". Since I need to master the software, I decided to simulate a 2D electron moving along the x axis (increasing direction) in a ragion where a constant magnetic field is present (z positive direction). I just wanted to plot the trajectory of the particle and see the usual circular cyclotron motion to emerge. However, as simple as the corresponding namelist can be, the trajectory I get after simulating the particle (for a supposed single gyration lap time) is the following
![electron_traj_4](https://user-images.githubusercontent.com/83040284/116087988-b31e8780-a6a1-11eb-8e93-6c78aa26fec6.png)
where the curve doesn't close on itself. Now, with the parameters I provided in the namelist the expected Larmor radius should be uqual to r = 0.1 (normalized code units). Nonetheless, the final point of the curve seems too far apart from the initial one to be due to some (perfectly natural) numerical defect of the pusher's algrithm.
Thus, in order to ascertain that the particle do not acquire a non zero y-component of the momentum, I had the simulation relaunched for a time three times greater than the previous one. Its trajectory then resulted in
![electron_traj_3_turn](https://user-images.githubusercontent.com/83040284/116100910-a99b1c80-a6ad-11eb-9f15-a1fa14b25ce9.png)
which seems to confirm the y-drift hypothesis... What am I missing? What is giving my particle this py? Here I attach the namelist I used for the 3 laps simulation.
[single_electron_mf.py.txt](https://github.com/SmileiPIC/Smilei/files/6377871/single_electron_mf.py.txt)

Thank you so much for your time and kindness.

**Comment by mccoys** [comment]
Did you try to increase the grid resolution and/or the time resolution ? You might be under-resolving the problem.

In some situations, it is also possible for the electrons to emit radiation. Try to decrease the density by a lot.

**Comment by smontefiori** [comment]
@mccoys You were right! By increasing the grid resolution the trajectory plot improves significantly:
![electron_traj_4](https://user-images.githubusercontent.com/83040284/116158811-7f6a4e80-a6ef-11eb-82c9-98300afc4daf.png)
Many thanks, I did not take into account these aspects.

One more thing: before reading your answer, I wanted to plot the vx and vy components of velocity, so that I could check whether the electron possessed a vy component at the end of the lap. In order to this I added the following ParticleBinning diagnostic block to the namelist:

    DiagParticleBinning(
    deposited_quantity = "weight",
    every = global_every,
    time_average = 1,
    species = ["electron"],
    axes = [
        ["vx", -1., 1., 500],
        ["vy", -1., 1., 500],
    ])

Then, during post-processing, I launched the following simple and straightforward commands (see plot script [binning_vel.py.txt](https://github.com/SmileiPIC/Smilei/files/6380655/binning_vel.py.txt)):

    S.ParticleBinning(1,subset={"vy":[-1.,1.,500]}, title ="vx").plot(i, cmap = "RdBu", interpolation = "bilinear", saveAs = "figures_and_plots/binning/vx/"+str(i)+".png")

and

    S.ParticleBinning(1,subset={"vx":[-1.,1.,500]}, title ="vy").plot(i, cmap = "RdBu", interpolation = "bilinear", saveAs = "figures_and_plots/binning/vy/"+str(i)+".png")

to get the weight distribution of my particle (where you can notice that I used 'particle' (singular) and not 'particles', since I prepared a number density function allowing for the creation of a single electron inside the grid) at each time step, but I got exactly nothing. For instance, in the vx case, I got the following plot at every timestep (including the first one)
![5516 0](https://user-images.githubusercontent.com/83040284/116158220-8fcdf980-a6ee-11eb-9c2a-0d54b8a2c76c.png)
The same situation holds true for the vy component too.

This, instead, is what I was expecting:
![0 0](https://user-images.githubusercontent.com/83040284/116159019-cc4e2500-a6ef-11eb-8b5b-4444da04c3ae.png)

Therefore, again, what am I missing? Did I misunderstand the usage of the ParticleBinning block inside the namelist? Or maybe I did something wrong in the post.processing?

Thank you again in advance, you're helping me a lot.

**Comment by mccoys** [comment]
I really don't understand why you would need a distribution of a single particle. It does not make sense. ParticleBinning is supposed to be used for many particles. It makes histograms of various quantities. Check the doc in details: http://www.maisondelasimulation.fr/smilei/namelist.html#particlebinning-diagnostics
Note that your `subset` is also misused. Read this part of the doc: http://www.maisondelasimulation.fr/smilei/post-processing.html#open-a-particlebinning-diagnostic

If you need the velocity components of a single particle, yo should use the tracking diagnostic that you are already using. Instead of the "x" and "y" axes, you should plot "py".
