### ISSUE TITLE
Field differences when simulating ultrarelativistic bunch traveling in opposite directions

### ISSUE THREAD

**Issue by smontefiori** [SmileiPIC/Smilei#399]
Hi developers! Yesterday I ran into some strange behaviour:
first, I launched a 2D simulation in which an ultrarelativistic bunch was moving along the x axis (towards positive x). Since I had to deal with ultrarelativistic particles, I used `relativistic_field_initialization = True` together with `solve_poisson = False, solve_relativistic_poisson = True`. In this case everything looked fine, the charge distribution was moving in the supposed direction
![0 0](https://user-images.githubusercontent.com/83040284/116775285-92b84980-aa62-11eb-84ad-6f0c8e288a5d.png)
![45 0](https://user-images.githubusercontent.com/83040284/116775296-9b108480-aa62-11eb-9364-abefb51f0f70.png)
(and so on...), the electric field Ex showed the expected noise due to the silver-muller BC I imposed
![23 0](https://user-images.githubusercontent.com/83040284/116775363-f80c3a80-aa62-11eb-9a07-fbd6a723c5ce.png)
![68 0](https://user-images.githubusercontent.com/83040284/116775365-fd698500-aa62-11eb-9ef2-265b92b02c13.png)
![113 0](https://user-images.githubusercontent.com/83040284/116775367-00fd0c00-aa63-11eb-84f0-dda97a28a870.png)
and the Ey field (in its expected form) was following the charge motion
![0 0](https://user-images.githubusercontent.com/83040284/116775727-cc8a4f80-aa64-11eb-9dfd-fbfef0b0ac8f.png)
![45 0](https://user-images.githubusercontent.com/83040284/116775736-d9a73e80-aa64-11eb-994e-b1cdca52b328.png)
![91 0](https://user-images.githubusercontent.com/83040284/116775746-e88df100-aa64-11eb-93a6-445c5df32fb2.png)
Nothin unusual so far.

But, as soon as, in these exact same conditions, I reversed the sign of the velocity in the Species initialization (i.e. I simply switched `mean_velocity = [vel_e, 0.0, 0.0]` to `mean_velocity = [-vel_e, 0.0, 0.0]`) something weird happened. Even though the charge distribution appeared to move in the correct direction (decreasing x), the Ex field not only seemed to evolve exactly as before, while I was expecting its evolution to be a mirror-image of the previous case, but it also showed the presence of a growing "field bubble" in the shape of the initial charge distribution:
![23 0](https://user-images.githubusercontent.com/83040284/116775810-694ced00-aa65-11eb-801c-4f0e0740a33a.png)
![68 0](https://user-images.githubusercontent.com/83040284/116775816-6f42ce00-aa65-11eb-8418-c04eb362c0d4.png)
![113 0](https://user-images.githubusercontent.com/83040284/116775822-74078200-aa65-11eb-828b-1cfb707abb26.png)
Moreover, the Ey field was surprisingly moving in the opposite direction (increasing x)
![0 0](https://user-images.githubusercontent.com/83040284/116776226-9c907b80-aa67-11eb-8fcf-6a0efe41cafe.png)
![45 0](https://user-images.githubusercontent.com/83040284/116776234-a0bc9900-aa67-11eb-9efb-a3b0da029778.png)
![91 0](https://user-images.githubusercontent.com/83040284/116776237-a3b78980-aa67-11eb-99b7-5e5ac4bd4ccc.png)
developing a strange "field bump" in the middle.

Now, the namelist I'm using is quite simple and immediate
[namelist.txt](https://github.com/SmileiPIC/Smilei/files/6409152/namelist.txt)
but I'm well aware that it's very likely that I might be missing something. Do you know any reasons why the fields could be so different just reversing the motion direction? 

Furthermore, I've noticed that by running the same simulation as above, but with the EM BCs set to`EM_boundary_conditions = [['reflective'],['reflective']]`, the numerical noise comes from the upper boundary only.
![23 0](https://user-images.githubusercontent.com/83040284/116826816-40784500-ab96-11eb-9989-07005aa47079.png)
![68 0](https://user-images.githubusercontent.com/83040284/116826819-479f5300-ab96-11eb-8e80-d42e764e4f03.png)
![113 0](https://user-images.githubusercontent.com/83040284/116826823-4cfc9d80-ab96-11eb-9b35-8f488629546d.png)
I know it is expected, but I can't undarstand why the noise is not coming from the bottom as well.

Thank you in advance for your time and kindness.

PS: I'm using v4.5-445-g1558235fb-master

**Comment by mccoys** [comment]
Hi, I never used this option in smilei, but here is one sentence from the doc:

> An important assumption of this calculation is that the species is highly relativistic, moving in the positive direction, with negligible momentum spread. 

Your beam is supposed to go towards positive x otherwise the assumption is wrong.

**Comment by smontefiori** [comment]
Uh, that's true! I missed that part.

Do you happen to have an explanation for the electric field's behaviour in reflective EM BCs too? The plot I posted belongs to an ultrarelativistic bunch going in the right direction, thus I would expect the noise coming from below (I mean the bottom border) as well.

Thank you again.

**Comment by mccoys** [comment]
I have no idea but will ask.

**Comment by Z10Frank** [comment]
Hello, 
in 2D cartesian geometry the solution of relativistic Poisson's equation gives fields at the borders that are high enough to create sensitive border effects (see Issue https://github.com/SmileiPIC/Smilei/issues/137 ). Without PML boundary conditions (still work in progress), boundary effect may arise easily. 

I would recommend to try the AM cylindrical geometry, which will give 3D-like fields with resources comparable to those of a 2D simulation https://smileipic.github.io/Smilei/azimuthal_modes_decomposition.html. These fields should decrease with a more realistic steepness.

Anyway, without PML, even in cylindrical geometry pay attention to define a window that is large enough transversally to allow the decrease of the initial fields.

**Comment by Z10Frank** [comment]
To answer the question about the asymmetry of the border effects, I am not sure about its cause. 

One asymmetry that I see is the calculation of `Ey` through a non symmetric finite difference `( *Ey2D )( i, j ) = ( ( *phi_ )( i, j-1 )-( *phi_ )( i, j ) )/dy;` in `ElectroMagn2D.cpp`. This is done to reduce the number of interpolations to properly center E in the Yee cell after the Poisson solver (`phi` is centered like `rho`). With centered finite differences the calculation would be more symmetric, but then interpolations would be needed to center E in the Yee cell, adding more numerical errors.

**Comment by smontefiori** [comment]
Thank you so much for your explanation... If possible I would take some time to look at `ElectroMagn2D.cpp`, as well as to try and run some 3D simulations. I would like to compare the 3D results with those of a 2D simulation.

Of course I will reach out to you as soon as I have some evidence.

Thank you for your patience.
