### ISSUE TITLE
Post processing activity

### ISSUE THREAD

**Issue by bssharma1958** [SmileiPIC/Smilei#400]
I am facing problem in  adding Open attribute in python/ Pycharm. Could any one help me? Or suggest the alternate method to plot the  simulation results of Smilei.
Thanks

**Comment by mccoys** [comment]
Please explain or show what you try to do and explain what is the problem. You do not give enough details

**Comment by bssharma1958** [comment]
I have compiled and run the code. I am facing problem in post process. I
am unable to  read and plot the results. Could you suggest me what should I
do? Any alternate method to visualising the results or the actual commands
using to perform such tests?

**Comment by mccoys** [comment]
How are you unable to plot and read the results?  What did you try?  Did you read the documentation? Provide details, examples.
