### ISSUE TITLE
'cold' species

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#401]
Hi Smilei team,

I have a question. I did not find anything in the documentation.
When a species (electron) is initialized at 'cold', what does it mean in terms of temperature and Debye length to use a good resolution in the simulation?

Thanks

Julien CELIA

**Comment by mccoys** [comment]
Cold means they don't move. This is not very physical and you cannot define a debye length. However, if there are no fields initially, there will be no numerical heating as nothing moves
