### ISSUE TITLE
supplying two user functions as axes in screen diag

### ISSUE THREAD

**Issue by fyli16** [SmileiPIC/Smilei#403]
## Description

It seems that supplying two (or more than one) user defined functions as axes in the screen diagnostic would be problematic. For example, I wanted to diagnose 2d angular distribution of particles and I used the following two functions as axes:

```
def angle_y(particles):
    return (np.arctan2(particles.py, particles.px) * 180/pi)

def angle_z(particles):
    return (np.arctan2(particles.pz, particles.px) * 180/pi)

DiagScreen(every = dump_freq, shape = "plane", point=[plasma_start+distance, box[1]/2, box[2]/2], 
vector=[1,0,0], direction = "forward", deposited_quantity = "weight", species = ['elec'], 
axes=[ [angle_y, -90, 90, 90], [angle_z, -90, 90, 180] ] )

```

In the output, when I tried to read the axes I found that the names of the two axes are not distinguished; here is the print of the diagnostic info: 

```
#1 - Number density of species # 1
    user_function from -90.0 to 90.0 in 90 steps
    user_function from -90.0 to 90.0 in 180 steps
```

where one can see both axes are taking the name of 'user_function'.  So my question: is supplying more than one user functions as axes in screen (possibly also particlebinning) sth doable? If yes, how to fix the above issue so that one can distinguish the two axes in results. 

I am using the latest v4.6. Thanks.

**Comment by mccoys** [comment]
This does not seem to be an error. It works, right?

What you are citing is simply a display of the two axes which are both user functions. What do you suggest it should display?

**Comment by fyli16** [comment]
@mccoys thank you for prompt response. 

I was thinking perhaps it should display as 'user_function 0'  and 'user_function 1', i.e., with proper labels 0, 1, such that one can access the axis data via 

```
sim = happi.Open()
obj = sim.Screen(1)
ax1 = obj.getAxis('user_function 0')
ax2 = obj.getAxis('user_function 1')
```

Currently, both names are 'user_function', making the above not possible. Or, is there another way to extract the axis data (certainly I can manually provide them, but I want the scripts a bit automatic in processing)?

**Comment by mccoys** [comment]
Ah now I understand the issue. `getAxis` cannot be used with 2 user functions. I will look into it.
