### ISSUE TITLE
Wakefield phase velocity diagnostic

### ISSUE THREAD

**Issue by Sonuphd** [SmileiPIC/Smilei#404]
Respected Sir,

I am doing Laser Wakefield Acceleration and I want up ramp and down ramp density profile and their effect on Wakefield phase velocity. Please add the up ramp and down ramp plasma profile and wakefield phase velocity diagnostic. For reference, I am attaching a paper regarding this.
[Zhang_2018_Plasma_Phys._Control._Fusion_60_024003.pdf](https://github.com/SmileiPIC/Smilei/files/6499729/Zhang_2018_Plasma_Phys._Control._Fusion_60_024003.pdf)

**Comment by Z10Frank** [comment]
Hello,
the phase velocity mentioned in the article can be easily defined only in 1D, you can compute it in postprocessing from the plasma density, which defines the plasma frequency in eq. (1). 

You can already define many density profiles in the input namelist, including up ramp and downramp. As already said, before asking a feature like this **please read carefully the documentation and start learning with the tutorials**, which will show you how to define a plasma density profile for your case.
