### ISSUE TITLE
Automatic min/max axes limits in ParticleBinning diagnostic

### ISSUE THREAD

**Issue by k-they** [SmileiPIC/Smilei#406]
In the ParticleBinning diagnostic, it would be nice to have the option to set the min/max of the axes automatically using the corresponding (global) min/max values for the particles. 

There are a number of situations where it is necessary to capture, for example, the electron energy as it changes over several orders of magnitude (e.g. to characterize the effects of prepulse). In addition, we do not always know the maximum energy particles will obtain prior to running the simulation, and allowing the min/max to be set automatically would avoid the unpleasant surprise of needing to re-run the simulation in order to capture the full energy spectrum.

**Comment by mccoys** [comment]
We did implement this option locally, and it will be available on github soon

**Comment by k-they** [comment]
Excellent, thank you!

**Comment by mccoys** [comment]
It has been pushed on github. Please close the issue if it works for you

**Comment by k-they** [comment]
When I tested this out, I got a segfault after "Running diags at time t = 0" is printed. Is this the correct syntax?

DiagParticleBinning(
    deposited_quantity = "weight",
    every = 100,
    species = ["Electron"],
    axes = [["px","auto","auto",1000]]
)

**Comment by mccoys** [comment]
Hum I guess you might have all px=0
I forgot about this possibility

**Comment by mccoys** [comment]
This should now be fixed. Can you test if this works for you ?
