### ISSUE TITLE
Laser pulse distortion 

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#407]
I run the 2D simulation for laser envelope propagation in plasma. I got the laser pulse distortion during pulse propagation. 
![Ex_bunch_Laser1](https://user-images.githubusercontent.com/67734147/119842618-bc984b00-befe-11eb-91d4-873ddd4084e1.png)

The 2D name list attached herewith. Can any help me to identify the issue ?
[22Dactivebeamdumping.txt](https://github.com/SmileiPIC/Smilei/files/6554702/22Dactivebeamdumping.txt)
 ?

**Comment by Z10Frank** [comment]
Hello, 
when you encounter a behaviour that is not what you expect physically, you should start wondering if it is created by numerical effects. To check this, try always to vary the numerical parameters like spatial resolution, the dt, the number of particles per cell, the box size, etc.

In this case, you are using a laser envelope for the laser and at the same time spatial and temporal resolutions that are exaggerated compared to those typical for an envelope simulation. With a laser envelope model, as explained in the doc https://smileipic.github.io/Smilei/laser_envelope.html (please read it more carefully), you don't need to resolve the laser wavelength. With your resolution and dt, your simulation is unnecessarily cumbersome and can potentially give unexpected results. 

I suggest first to complete the tutorial with a laser envelope model for LWFA https://smileipic.github.io/tutorials/advanced_wakefield_envelope.html and then try with similar resolution and dt. In your case you will need to resolve also the electron bunch size.
