### ISSUE TITLE
Questions on Diagnostic modules

### ISSUE THREAD

**Issue by smontefiori** [SmileiPIC/Smilei#409]
Dear developers, 
hi! I have some questions concerning the diagnostic modules.

1) In the docs, the "Write a namelist" page (https://smileipic.github.io/Smilei/namelist.html) has the "ParticleBinning" section (https://smileipic.github.io/Smilei/namelist.html#particlebinning-diagnostics). Well, I do not seem to understand the last three examples reported in there. For instance, let's take into consideration the following one:
![immagine](https://user-images.githubusercontent.com/83040284/120237746-79bad800-c25c-11eb-83dc-29331d937d6c.png)
If it's true that the axis syntax is `[type, min, max, nsteps, "logscale", "edge_inclusive"]`, I really can't understand the "3 bands of energy" thing. I mean, this should simply be the 2D density map that also bins the energies going from 0 up to 6 (dividing this range in 3 bins), shouldn't it?

2) I've launched a namelist containing the following radiation spectrum block:

`DiagRadiationSpectrum(`
`    every = int(nt/nout_radiation),`
`    species = ["electron_plasma"],`
`    photon_energy_axis = [0., 20000, 2000],`
`    axes = [`
`        ['px', -400., 1400., 2000],`
`        ['py', -400., 1400., 2000]`
`    ]`
`)`

but I'm getting this error:
`[ERROR](0) src/Diagnostic/DiagnosticRadiationSpectrum.cpp:77 (DiagnosticRadiationSpectrum) DiagRadiationSpectrum #0: too many points (8000000000 > 2^312)`
Now,  2^312 should be something like `8.3e+93` and thus greater than `8000000000`. Moreover, considering that my simulation is shared by 64 processes and that the grid is subdivided into `32 * 8` patches, even assuming that each process works on every patch, the number `64*32*6*8000000000` is still lower than `2^312`. So, what does this error mean? I managed to run the simulation by decreasing the steps on every axis ('px', 'py', 'photon_energy_axis') from 2000 to 200.

3) Since I am here asking all these question, I take this opportunity to ask one more: the quantity deposed by the DiagRadiationSpectrum is always the `weight`, isn't it?

Thank you in advance for your time and please forgive the bother.

**Comment by mccoys** [comment]
Hi
1. Indeed the energy range is divided in 3 bins. So that gives you three maps of density (one for each bin), right ?
2. There is a mistake. It should be 2^31.

**Comment by smontefiori** [comment]
Thank you for your quick response!

1) Yes, but I would expect the bins to be [0,2],[2,4],[4,6] and not [0,1],[1,2],[2,inf]. I can't understand why they are divided like that. I do not know, I am surely missing something...
2) Uh, ok! That happens, too.
3) How do I access the data that a RadiationSpectrum diagnostic bins along the `photon_energy_axis`? I tried with `S.RadiationSpectrum(0).get( time )['photon_energy_axis']`, but that was a failure...

Thank you again.

**Comment by mccoys** [comment]
1. Ok I see. It is not specified but it is converted to ~ MeV

**Comment by MickaelGrech** [comment]
Hi!
As for your question 3, the RadiationSpectrum diagnostics is a bit special.
You necessarily define a photon energy axis (3rd line in your block). 
For each macroparticle, and each bin of this energy axis, what you report is not the weight, but the power radiated by the macroparticle at the energy  of the considered bin. Note that the radiation model used here assumes that the radiation is synchrotron like (ok for ultra-relativistic emitting particle, also note that it accounts for quantum corrections), and incoherent (ok for very high frequency radiation).
You can find more info in the doc [here](https://smileipic.github.io/Smilei/radiation_loss.html).

**Comment by mccoys** [comment]
Let me answer to what you asked @MickaelGrech. Your definition is correct, and it is exactly what a "spectrum" is. Note that this diagnostic is unrelated to the actual "macro-photons" emitted in the specific case of the Monte-Carlo radiation model. Instead, the spectrum is artificially calculated according to the electron population (there are no photons in the simulation).

**Comment by smontefiori** [comment]
Thank you! Now everything is clear to me.
The issue is closed.
