### ISSUE TITLE
Issue with happi and Screen diagnostics

### ISSUE THREAD

**Issue by Nikolai-mephi** [SmileiPIC/Smilei#411]
Dear smilei developers and users,

I am trying to perform a 3D simulation on laser plasma interaction with Screen as one of the used diagnostics.
The simulation itself runs fine, but when I attempt to post-process its results and call the Screen diagnostics with happi, I receive an error message, informing me that there is some issue in opening .h5 files.
[error.txt](https://github.com/SmileiPIC/Smilei/files/6598613/error.txt).
The Field diagnostic, which also uses .h5 files, opens without any errors for the same simulation, so the problem is specifically related to the Screen Diagnostics.
I would highly appreciate if you could point out how this issue can be avoided.

## Parameters
I am using the release version of smilei-v4.6 (v-9228ba655).
Here is the input file for the simulation: 
[3D_cuboid_grazing_incidence.txt](https://github.com/SmileiPIC/Smilei/files/6598670/3D_cuboid_grazing_incidence.txt)
- My computing resources:
  - type of computer: HPC
  - OS: Debian GNU/Linux 10 (buster)
  - HDF5 version: 1.10.4
  - Python version: 3.7.3

**Comment by Nikolai-mephi** [comment]
A small update on my problem. 

I have found out that happi cannot properly open .h5 files for the screen diagnostic only for a **currently running simulation**. It seems that these files cannot be opened at the same time by the running simulation for writing the data and by happi for post-processing it, because the already written files for a completed simulation open without any errors. 

Still, I don't quite understand why this problem doesn't occur for the Field diagnostics and whether something can be done to get the ability to read Screen files during the run, which can be useful to check if they results are consistent with the expectations without having to stop the simulation.

**Comment by mccoys** [comment]
We have observed this behavior in some systems but I am not really sure what causes it. The only real difference I see between these 2 diagnostics is that the Screens are only written by 1 MPI process, while the Fields are written in parallel (collective mode) by all MPI processes. I can imagine that there are some parameters in the hdf5 library that control the access to the file, but I am surprised it depends on the parallel mode. In fact it might be related to the filesystem, not to hdf5. 
One reason for this could be that hdf5 has a specific file access for the collective mode which enables the file to be opened at the same time by other processes (such as the one you run with happi), but this mode would not be available for independent access. This need some investigation

**Comment by Sanjeev273** [comment]
> 
> 
> A small update on my problem.
> 
> I have found out that happi cannot properly open .h5 files for the screen diagnostic only for a **currently running simulation**. It seems that these files cannot be opened at the same time by the running simulation for writing the data and by happi for post-processing it, because the already written files for a completed simulation open without any errors.
> 
> Still, I don't quite understand why this problem doesn't occur for the Field diagnostics and whether something can be done to get the ability to read Screen files during the run, which can be useful to check if they results are consistent with the expectations without having to stop the simulation.

It can't be open if the data size is large. If the data file is large, you to load the data file in loop for every iteration. For this you have to write your own script to extract the Data.  Check the details here: https://smileipic.github.io/Smilei/post-processing.html#obtain-the-data

**Comment by Nikolai-mephi** [comment]
Thank you for the suggestion, but what you've said is already implemented in my post-processing script - first I try to obtain available timesteps for a given diagnostics, then get the data and plot it in loop for each timestep. 
The problem is that I cannot make any calls to Screen due to the corresponding .h5 files refusing to open properly at the start of the post-processing script because they are opened by the simulation for writing and cannot be opened by anything else until they are written when the simulation is over.

**Comment by mccoys** [comment]
@Sanjeev273 I believe you might have misunderstood the question. The error shows that files are not accessible.

**Comment by mccoys** [comment]
@Nikolai-mephi I am unable to reproduce this error on the system I use. Could you try to set the following environment variable?
`export HDF5_USE_FILE_LOCKING=FALSE`

**Comment by Nikolai-mephi** [comment]
> @Nikolai-mephi I am unable to reproduce this error on the system I use. Could you try to set the following environment variable?
> `export HDF5_USE_FILE_LOCKING=FALSE`

Thank you very much, @mccoys. I have set this environment variable in my .sh script used for starting the calculations and now I am able to open Screen.h5 files for a running simulation without any errors. I guess the issue may be closed now.
