### ISSUE TITLE
running in parallel using mpich on multiple hosts crashes

### ISSUE THREAD

**Issue by dealfonso** [SmileiPIC/Smilei#412]
## Description

When I try to run smilei using multiple processes on multiple hosts, using the mpich backend, it fails.

```
 HDF5 version 1.10.0
Stack trace (most recent call last):
#4    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in
#3    Object "smilei", at 0x5577c9b4f2c9, in _start
#2    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fdc12c23bf6, in __libc_start_main
#1    Object "smilei", at 0x5577c9b4c078, in main
#0    Object "smilei", at 0x5577c9ce6a78, in Params::Params(SmileiMPI*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)
Segmentation fault (Address not mapped to object [(nil)])
	 Python version 3.6.9
	 Parsing pyinit.py
	 Parsing ??-??
	 Parsing pyprofiles.py
	 Parsing tst1d_00_em_propagation.py
	 Parsing pycontrol.py
	 Check for function preprocess()
	 python preprocess function does not exist

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 16016 RUNNING AT spot01
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
[proxy:0:0@spot00] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:883): assert (!closed) failed
[proxy:0:0@spot00] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:77): callback returned error status
[proxy:0:0@spot00] main (pm/pmiserv/pmip.c:202): demux engine error waiting for event
[mpiexec@spot] HYDT_bscu_wait_for_completion (tools/bootstrap/utils/bscu_wait.c:76): one of the processes terminated badly; aborting
[mpiexec@spot] HYDT_bsci_wait_for_completion (tools/bootstrap/src/bsci_wait.c:23): launcher returned error waiting for completion
[mpiexec@spot] HYD_pmci_wait_for_completion (pm/pmiserv/pmiserv_pmci.c:218): launcher returned error waiting for completion
[mpiexec@spot] main (ui/mpich/mpiexec.c:340): process manager error waiting for completion
```

## Steps to reproduce the problem

On an ubuntu 18.04.5 LTS, simply follow the installation guide, except for using mpich (i.e. packages libhdf5-mpich-dev, libhdf5-mpich-100, mpich, etc.) instead of the openmpi.

And run using 

```
mpirun -hosts spot00,spot01 smilei tst1d_00_em_propagation.py
```

## Parameters

- Smilei version 4.6
- Input file benchmarks/tst1d_00_em_propagation.py
- Commands or script used to run the faulty simulation mpirun -hosts spot00,spot01
- Computing resources
  - type of computer: x86_64
  - OS: ubuntu 18.04.5 LTS
  - C++ compiler (to get some information `g++ --version`) g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
  - MPI version (`mpic++ --version`, `mpic++ -show`) g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, g++ -Wl,-Bsymbolic-functions -Wl,-z,relro -I/usr/include/mpich -L/usr/lib/x86_64-linux-gnu -lmpichcxx -lmpich
  - HDF5 version (`h5cc --version`) gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
  - Python version (`python --version`) Python 3.6.9
  - ...

**Comment by mccoys** [comment]
Hi, have you tried to compile and run a basic MPI "hello world" application with mpich? And with parallel HDF5?

**Comment by dealfonso** [comment]
Hi,
Yes to the MPI app and it works as expected. But I have no expertise with hdf5.

**Comment by iltommi** [comment]
Hi we've got a strange report #387 (staled since).
Could you try to run this https://github.com/SmileiPIC/Smilei/files/6249645/test.txt (simplest example using mpi + hdf5)

**Comment by mccoys** [comment]
Does your installed MPICH version support `MPI_THREAD_MULTIPLE` ?
If it was installed with `configure`, you need the option `--enable-threads=multiple`.

You can test if this is the problem by recompiling smilei with `make config=no_mpi_tm`

**Comment by dealfonso** [comment]
> https://github.com/SmileiPIC/Smilei/files/6249645/test.txt

Hi,

I compiled the example using the next commandline:

```
mpic++ -o test test.c -lhdf5_mpich
```

I run it using this commandline:

```
root@spot:/scratch/tests-bug# mpirun -hosts spot00,spot01 /scratch/tests-bug/test
Warning: Permanently added 'spot00,192.168.0.15' (ECDSA) to the list of known hosts.
Warning: Permanently added 'spot01,192.168.0.11' (ECDSA) to the list of known hosts.
root@spot:/scratch/tests-bug# ls -l
total 32
-rw-r--r-- 1 root root  2944 Jun 11 06:39 data.h5
-rwxrwx--- 1 root root 20832 Jun 11 06:35 test
-rw-rw---- 1 root root  1584 Apr  2 13:12 test.c
```

And it seems to work, as it generates "data.h5".

**Comment by dealfonso** [comment]
> Does your installed MPICH version support `MPI_THREAD_MULTIPLE` ?
> If it was installed with `configure`, you need the option `--enable-threads=multiple`.
> 
> You can test if this is the problem by recompiling smilei with `make config=no_mpi_tm`

I downloaded Smilei again (from main branch) and re-compiled it using the option. The result:

```
Stack trace (most recent call last):
#4    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in
#3    Object "smilei", at 0x555cfa635699, in _start
#2    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fe4eadb1bf6, in __libc_start_main
#1    Object "smilei", at 0x555cfa632448, in main
#0    Object "smilei", at 0x555cfa7cb629, in Params::Params(SmileiMPI*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)
Segmentation fault (Address not mapped to object [(nil)])
	 Python version 3.6.9
	 Parsing pyinit.py
	 Parsing 4.6-151-g68ba686fc-master
	 Parsing pyprofiles.py
	 Parsing /scratch/Smilei/benchmarks/tst1d_00_em_propagation.py
	 Parsing pycontrol.py
	 Check for function preprocess()
	 python preprocess function does not exist

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 29417 RUNNING AT spot01
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
[proxy:0:0@spot00] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:883): assert (!closed) failed
[proxy:0:0@spot00] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:77): callback returned error status
[proxy:0:0@spot00] main (pm/pmiserv/pmip.c:202): demux engine error waiting for event
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```

But I think that the problem is not in the mpi runtime, as the error seems to be in the source of smilei, in `Params::Params`

**Comment by dealfonso** [comment]
Hi,

I have started from scratch, recompiling anything again, and re-installing any host (they were virtual machines), and for some reason it is now working.

Sorry for the inconveniences, and thank you for your support.

Regards.
