### ISSUE TITLE
Python GIL error with user-defined ParticleBinning axis

### ISSUE THREAD

**Issue by k-they** [SmileiPIC/Smilei#413]
I encounter a numpy GIL error when trying to use any user-defined axis for ParticleBinning on the knl nodes of Stampede2. Attached is a MWE namelist, in which I dump px using lambda p: p.px in lieu of the built-in "px".
[example.txt](https://github.com/SmileiPIC/Smilei/files/6651244/example.txt)

This may be a system- or compiler-specific problem, as this same example works as intended on a local machine.

Compilation details:
Module environment I use to build on the knl nodes of stampede2:
  1) intel/18.0.2
  2) libfabric/1.7.0
  3) impi/18.0.2
  4) git/2.24.1
  5) autotools/1.1
  6) cmake/3.16.1
  7) xalt/2.10.2
  8) TACC
  9) python3/3.7.0
 10) phdf5/1.10.4
 11) boost/1.68

Extra compiler flags set in the machine file are:
CXXFLAGS += -D__INTEL_KNL_7250 -xMIC-AVX512 -ip -inline-factor=1000 -qopt-zmm-usage=high -fno-alias

**Comment by mccoys** [comment]
Could you copy-paste the error you obtain?
Have you tried without openMP (single thread)?

**Comment by mccoys** [comment]
I am closing this for now. Please reopen if the problem still occurs
