### ISSUE TITLE
LaserOffset reuse

### ISSUE THREAD

**Issue by Horymir001** [SmileiPIC/Smilei#414]
Dear colleagues,

is it possible to "recycle" the LaserOffset initiated intensity and phase description at the left boundary?
I understand that at first, Thiele's method calculates such description and stores the data to the file LaserOffset0.h5. Then, the data are loaded and the PIC loop is started.

It would be useful to enable using already generated file in other simulation which differs only by plasma parameters (e.g. thicker target, ...). Because that calculation itself is now actually 11% of the total CPUtime in my case.

Is that option missing or it is me who is missing something?

Cheers,

Vojtěch Horný

**Comment by mccoys** [comment]
Hi
I think this is technically possible, but not yet in a user-friendly way.  Look at the end of the pyprofiles.py file where the LaserOffset function is defined. You should be able to copy paste the same and use _propagate=False

**Comment by mccoys** [comment]
This is now available
