### ISSUE TITLE
particle tracking through a second rerun

### ISSUE THREAD

**Issue by fyli16** [SmileiPIC/Smilei#416]
Currently, SMILEI offers particle tracking through 'happi' post-processing of raw particle data dumps that pass some filtration conditions. It gains in time at the expense of space (i.e., storage) by avoding a second rerun. But in some situation it results in exceedingly huge storage if one wants to have complete tracking of particles' history. For example, we might be interested in those particles being accelerated to high energies but also want to know their origins where they start from low energies. In order to see the complete history, a filter of low-energy threshold might be required, resulting in dumping of huge number of particles at fine time steps. 

For this particular case, any insight in design of the filter such that one can use reasonable storage to achieve complete tracking? 

Alternatively, could SIMILEI offer the option of particle tracking through a second rerun? That is, in the first run, one selects those particles of interest (typically of a small population), and then track them throughout in a second rerun. It should require all particles to be assigned a particulur set of IDs in the beginning of the simulation, in order for some particles of interest to be selected and marked after the first run. 

Any comments are appreciated.

**Comment by mccoys** [comment]
Tracking with a rerun is already possible. I suggest you make a checkpoint early in the simulation. You can restart from there and take advantage of the 'filter' argument to get only the requested particle ids.

Recently, we added the option to select particles at the same time as the sorting occurs (during postprocessing). This makes the sorting a bit longer, but avoids high storage requirements.

**Comment by fyli16** [comment]
@mccoys If I understood your method correctly and if I want to track from the very beginning, should it work this way: 

In the 1st run, I define a filter function as the following and dump at a low frequency: 
```
def my_filter(particles):
	if Main.iteration==0:
		return
	else:
		return particles.px>100 # some conditions that select only very energetic particles

DiagTrackParticles(
	filter = my_filter,
        every = 1000,  # dump at low frequency
)
```
That is, it assigns an ID for each particle in the beginning, then only dumps those high-energy electrons at later iterations. 

After the run completes, I extract the IDs of those particles of interest from the later dumps and save as, for example, 'ids.npy'. Then I rerun the simulation and now modify the filter function as below and dump at a high frequency to get smooth trajectories: 
```
ids = np.load('ids.npy')
def my_filter(particles):
	if Main.iteration==0:
		return
	else:
		particles.id in ids # dump only those saved IDs

DiagTrackParticles(
	filter = my_filter,
        every = 5,  # dump at high frequency to have smooth trajectories
)
```
In the above filter function, is the way of filtering IDs (i.e., particles.id in ids) most efficient, or do you have better suggestions?

Is the above whole loop what you meant? 

Also good to know the additional control in happi sorting, very useful. Thanks!

**Comment by mccoys** [comment]
Yes this is almost correct, but you cannot have an empty return from the filter. You must always return a Boolean array.  In fact, you must filter all particles on the first iteration so that they all acquire a positive id.  For instance `return particles.x>0`

**Comment by mccoys** [comment]
Also note that numpy recommends `isin` over `in1d`

**Comment by fyli16** [comment]
Thanks for the help!
