### ISSUE TITLE
Errors initializing particles from numpy arrays

### ISSUE THREAD

**Issue by michaelquin** [SmileiPIC/Smilei#418]
Hi, 

I’m having some issues initialising particles with position_initialization and momentum_initialization as numpy arrays, in the following script:

[test.zip](https://github.com/SmileiPIC/Smilei/files/6769977/test.zip)

 Initializing species
 --------------------------------------------------------------------------------
	 
	 Creating Species #0: electron_beam
		 > Pusher: boris
	[ERROR](0) src/Species/SpeciesFactory.h:566 (create) For species 'electron_beam' non valid position_initialization. It must be either a string or a numpy array.

As far as I can tell, this is is not a bug in Smilei but rather a problem with my setup (a similar problem was reported here https://github.com/SmileiPIC/Smilei/issues/202 but no conclusions were reached on what caused the errors). I use a dedicated virtual environment on a cluster (as opposed to, say, Anaconda) with the following packages;

Python version 3.7.2
(with Numpy version 1.20.2)
HDF5 version 1.8.21
Open MPI version 2.0.1
GCC version 4.8.5

It’s worth noting I have been using Smilei successfully for several months with this setup. 

For some context on the simulation file I have provided: I am interested in the effect of inter electron forces, when an electron bunch collides with a laser pulse. I essentially need each macroparticle to be as close to an individual electron as possible. I realise this can lead to extremely demanding simulations. For anyone running this script, I'm sure it would improve performance to deactivate relativistic_field_initialization before running.

Thanks for any help you can provide,
Michael

**Comment by mccoys** [comment]
Hi, Could you specify how you indicate the version of python to smilei ? Do you set the PYTHONEXE environment variable ? Can you print the result of `make env`

**Comment by michaelquin** [comment]
Hi. I’m not sure if I am correctly indicating the python version to smilei. Usually I submit my jobs in a bash script to our cluster which uses SGE:

directory_smilei=/home/quin/l8/happi_virtualenv	
source ${directory_smilei}/bin/activate
mpirun -x LD_LIBRARY_PATH=$LD_LIBRARY_PATH ${directory_smilei}/smilei test.py

Where in my case, LD_LIBRARY_PATH=/usr/local/Packages/PIC/hdf5-install-1.8.21/lib

I had problems previously when the path to hdf5 was not passed to smilei in this way. Should I also pass the PYTHONEXE variable to smilei like this?


The results of make env are below:

VERSION : v-68ba686fc
SMILEICXX : mpicxx
OPENMP_FLAG : -fopenmp -D_OMP
HDF5_ROOT_DIR : /usr/local/Packages/PIC/hdf5-install-1.8.21
FFTW3_LIB_DIR : 
SITEDIR : /home/quin/.local/lib/python3.7/site-packages
PYTHONEXE : python
PY_CXXFLAGS : -I/usr/local/Packages/Python-3.7.2/include/python3.7m -I/usr/local/Packages/Python-3.7.2/include/python3.7m -I/lfs/l8/theo/quin/happi_virtualenv/lib/python3.7/site-packages/numpy/core/include -DSMILEI_USE_NUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
PY_LDFLAGS : -L/usr/local/Packages/Python-3.7.2/lib/python3.7/config-3.7m-x86_64-linux-gnu -lpython3.7m -lpthread -ldl -lutil -lm -Xlinker -export-dynamic
CXXFLAGS : -Wno-reorder -D__VERSION=\"v-68ba686fc\" -D_VECTO -std=c++11 -Wall  -I/usr/local/Packages/PIC/hdf5-install-1.8.21/include -Isrc -Isrc/Ionization -Isrc/Patch -Isrc/Profiles -Isrc/MultiphotonBreitWheeler -Isrc/Particles -Isrc/Pusher -Isrc/DomainDecomposition -Isrc/MovWindow -Isrc/Diagnostic -Isrc/picsar_interface -Isrc/Field -Isrc/Projector -Isrc/Tools -Isrc/ElectroMagnBC -Isrc/SmileiMPI -Isrc/Merging -Isrc/ElectroMagn -Isrc/Interpolator -Isrc/Python -Isrc/Collisions -Isrc/Params -Isrc/Species -Isrc/ElectroMagnSolver -Isrc/Checkpoint -Isrc/Radiation -Isrc/ParticleInjector -Ibuild/src/Python -I/usr/local/Packages/Python-3.7.2/include/python3.7m -I/usr/local/Packages/Python-3.7.2/include/python3.7m -I/lfs/l8/theo/quin/happi_virtualenv/lib/python3.7/site-packages/numpy/core/include -DSMILEI_USE_NUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -O3 -g  -fopenmp -D_OMP
LDFLAGS : -L/usr/local/Packages/PIC/hdf5-install-1.8.21/lib   -lhdf5 -L/usr/local/Packages/Python-3.7.2/lib/python3.7/config-3.7m-x86_64-linux-gnu -lpython3.7m -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -lm -fopenmp -D_OMP

**Comment by mccoys** [comment]
I am surprised you need to specify LD_LIBRARY_PATH. Do you know the reason?

Are you sure you have done `make env` in the same environment as the compilation? By the way, you should compile and run with the same environment. If you `source` some file, this must be done identically for both compilation and job submission.

The `PYTHONEXE` variable defaults to `python`. If this is the correct executable, then you do not need to set it. At least, your `make env` seems to have worked properly.

**Comment by michaelquin** [comment]
It was on the advice of our system admin. 

I can activate my virtual environment (on one core, in an interactive session on our cluster), compile and run without passing the variable LD_LIBRARY_PATH to mpirun. When I tried submitting a job which uses multiple cores to our cluster (which uses SGE), I received an error like this;

./smilei: error while loading shared libraries: libhdf5.so.10: cannot open shared object file: No such file or directory 

I think this is because the variable LD_LIBRARY_PATH was not known on the single hosts?

I just have one environment, I use it for compilation, and I activate the same environment when I run the scripts on our cluster; this is the environment I did the make env in. But I do seem to have issues accessing the environment variables on the cluster. I’m not sure what you mean by ‘source’ a file?

**Comment by iltommi** [comment]
Hi, this is very strange indeed.

It looks like the python interpreter knows what a `ndarray` is but not the underlining c++ counterpart we use to get into the code.

In particular we use the `PyArray_Check` function (which in your case is returning false) to check whether the `position_initialization` is an array (https://github.com/SmileiPIC/Smilei/blob/21b2d0b8b26243ec6b7b31f346a3dde558e46502/src/Species/SpeciesFactory.h#L534). 

Looking at your `make env` it seems that you compiled with a numy located here `/lfs/l8/theo/quin/happi_virtualenv/lib/python3.7/site-packages/numpy/core/include`. 

Could you check this `print(np.__file__)` somewhere in your input file (maybe before the main)?
In this way we can check which one is using the python interpreter inside Smilei.

**Comment by mccoys** [comment]
I think the error is worse. The same python interpreter is confused between two versions: 
* `/usr/local/Packages/Python-3.7.2/include/`
* `/lfs/l8/theo/quin/happi_virtualenv/lib/python3.7/site-packages/numpy/core/include`
The first one is found using `sysconfig.get_path('include')` and the second with `numpy.get_include()`. I repeat that the two commands are run under the same interpreter.

To me this looks like a bug in numpy installation. Maybe a bug in anaconda ?

**Comment by michaelquin** [comment]
Thanks for the suggestions. 

Perhaps my setup is a little strange. I used a version of Python stored centrally on our cluster to create a virtual environment in my local directory (dir). The command looked something like,

- ${dir}=/lfs/l8/theo/quin/happi_virtualenv

- /usr/local/Packages/Python-3.7.2/bin/virtualenv ${dir}

> Could you check this `print(np.__file__)` somewhere in your input file (maybe before the main)?
> In this way we can check which one is using the python interpreter inside Smilei.

Sure, after submitting my script, it refers to the same version of Python I compiled with:

/lfs/l8/theo/quin/happi_virtualenv/lib/python3.7/site-packages/numpy/\_\_init__.py

**Comment by mccoys** [comment]
You probably don't want a virtualenv in this case. I'm not sure how it handles headers.

And anyways, if you did a virtualenv for happi you do not need it for running the code. Instead, the only thing you need is numpy. If it is not available from your cluster's python (which I doubt), you should make a local numpy install and add it in the PYTHONPATH. This should work better than virtualenv.

**Comment by michaelquin** [comment]
> You probably don't want a virtualenv in this case. I'm not sure how it handles headers.
> 
> And anyways, if you did a virtualenv for happi you do not need it for running the code. Instead, the only thing you need is numpy. If it is not available from your cluster's python (which I doubt), you should make a local numpy install and add it in the PYTHONPATH. This should work better than virtualenv.

Using the cluster's Python (2.7.5) for compiling and running the script, solved the problem. I'll continue using the virtual env just for post processing. 

Thanks for your help!
