### ISSUE TITLE
Q on the current density

### ISSUE THREAD

**Issue by smallrainbow** [SmileiPIC/Smilei#419]
Dear developers,

The current density is usually calculated as follows:
![j](https://user-images.githubusercontent.com/13895919/124724609-b904d480-df3e-11eb-8853-92bf3b6fc79d.png)

May I ask a question about this current calculation, please?
What do we have to change if we want to include the relativistic effect on charge? -> J=gamma*env? or do I missing something?

Thank you!

**Comment by mccoys** [comment]
Please do not use these issues to ask general questions. This is for bugs, unclear documentation, performance issues, etc. Instead, try the chat room https://app.element.io/#/room/!LQrdVpOJEohPSWMlmf:matrix.org

You can find the definition of current everywhere on the web. There is no relativistic correction.

**Comment by smallrainbow** [comment]
@mccoys Thank you! Ok, I withdraw it.
