### ISSUE TITLE
Incidence angle of the laser pulse and box_side

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#423]
Hi dear Smilei team,

Hope you are OK!
I have a general question about laser 2D definition.
If I want to define a laser coming from the left side (box_side='xmin') with an angle of 80° for example, I have to define incidence_angle to 80° or I have to change 'xmin' in 'ymax' with an angle of 10°? I hope you can understand my question...

Thanks

Julien

**Comment by mccoys** [comment]
You cannot really get an angle of 80 deg from the xmin border. Or you would need an extraordinary large box in the y direction. You must have your laser coming from ymin or ymax. Or maybe you can have both xmin+ymin for instance.

**Comment by BenK3nobi** [comment]
Is a laser emission from y min / y max implemented now? 
Last time I checked laser worked only from xmin/xmax?

**Comment by mccoys** [comment]
Yes it is now available from all sides

**Comment by juliencelia** [comment]
It works well but finally it is easier to rotate the initial density when it is imported from hydro profiles and read by SMILEI from hdf5 format.
Thanks Mccoys!!!
