### ISSUE TITLE
Compilation error (OS unbuntu 20.4)

### ISSUE THREAD

**Issue by ncpathak** [SmileiPIC/Smilei#425]
Dear Developers,

I am having problem in compiling the code. I followed the installation instructions, however, getting an error in the final compilation. 

The error message is:
Linking smilei
/usr/bin/ld: cannot find -lhdf5
collect2: error: ld returned 1 exit status
make: *** [makefile:239: smilei] Error 1

I have also attached the information of some of the recommended commands for checking.

Any help is appreciable. 

Thank you.

[echo_LD_Librarypath.txt](https://github.com/SmileiPIC/Smilei/files/6819635/echo_LD_Librarypath.txt)
[python_sysconfig.txt](https://github.com/SmileiPIC/Smilei/files/6819629/python_sysconfig.txt)
[make_env.txt](https://github.com/SmileiPIC/Smilei/files/6819630/make_env.txt)
[make_config_verbose.txt](https://github.com/SmileiPIC/Smilei/files/6819634/make_config_verbose.txt)

**Comment by mccoys** [comment]
How did you install the dependencies?  Did you follow the instructions in the doc?  Did you install hdf5? Also note that you did not set the HDF5_ROOT_DIR variable

**Comment by ncpathak** [comment]
Installation steps I followed:

(1) For downloading hdf5: https://www.hdfgroup.org/downloads/hdf5/source-code/

downloaded the latest version and:

./configure --parallel-enable 
make

(2) downloaded open-mpi versio 4.1.0 and:
./configure
make

(3) Python:
sudo apt-get install python3-h5py
sudo apt-get install python3-numpy
sudo apt-get install python3-matplotlib
sudo apt-get install python3-pint

sudo apt-get install python-dev
sudo apt-get install python3-dev

**Comment by mccoys** [comment]
In the smilei doc, it is indicated that you can simply install the debian package libhdf5-openmpi-dev instead of manually installing hdf5 and openmpi.

Anyways you should set the HDF5_ROOT_DIR variable as stated in my previous answer

**Comment by mccoys** [comment]
Note that, if you really want to install the dependencies from source, instructions are available in the doc

**Comment by ncpathak** [comment]
Thank you for your help. I will try again ....

**Comment by ncpathak** [comment]
I can now compile now and run the test scripts provided in the benchmarks folder. 

Thank you.
