### ISSUE TITLE
some question about the ability of  Smilei

### ISSUE THREAD

**Issue by m-rezaei-p** [SmileiPIC/Smilei#426]
I have three questions:
1-Can I implement a Laser with radial polarization in Smilei?
2-Can I simulate a laser-ion accelerator that ions can ionization more than?
3- Is there any limitation in ions movement between grids (I read in the OSIRIS manual when I wanna simulate ions with more than one ionization occur during interaction  I must assume ions can not move between cells)?

**Comment by mccoys** [comment]
As you already asked these questions in the chat room, I delete this issue
