### ISSUE TITLE
Dielectric function module in PIC

### ISSUE THREAD

**Issue by huetbdo** [SmileiPIC/Smilei#427]
Hello developers, thank you very much for the open source code. 

I have been using Smilei for simulating plasmons in noble metals. So far I have been simulating only the free electrons with PIC. However, I would like to extend the simulation to include dielectric materials. This will make PIC more versatile and can simulate a lot more plasmonic and photonic systems. I would like to suggest a new module in PIC that could deal with dielectric materials, where the charged species can move in. It could start with one as simple as assigning a non-dispersive dielectric constant to certain cells. I suppose this could be done by slightly changing the Maxwell solver to exchange between E and D (?).

I really hope you all will consider this new feature. Thank you very much.

Hue Do

**Comment by Z10Frank** [comment]
Hello, 
thank you for your interest in Smilei and for your suggestion!

Please feel free to experiment with one of the electromagnetic solvers to add a dielectric permittivity in the evolution of `E`.
For this purpose, you may want to use a Field representing the dielectric permittivity in one of the Maxwell-Ampère solvers inside the folder `src/ElectroMagnSolver`. Have a look for example into the file `src/ElectroMagnSolver/MA_Solver2D_norm.cpp` for the Yee solver.

**Comment by mccoys** [comment]
@huetbdo This type of PIC calculation is not common in the community where Smilei is most used. I doubt we have time to spare on this kind of development soon, but we will be happy to assist anybody who would like to do it.

**Comment by huetbdo** [comment]
Thank you very much for your replies. We will try implementing this ourselves and will definitely ask and share more in the future.

**Comment by Z10Frank** [comment]
Sure, please feel free to reopen this Issue if you'll have more questions about this.
