### ISSUE TITLE
Particles lose energy over time, depending on their weights

### ISSUE THREAD

**Issue by michaelquin** [SmileiPIC/Smilei#429]
Hi!

I have a simple 2D simulation of one real electron colliding with a counter propagating plane wave pulse. All quantities are normalized by the plane wave (radial) frequency omega_0, unless stated otherwise. In my case, omega_0 = 2 * pi * c / lambda_0, where the wavelength is lambda_0 = 0.8 x 10^-6 [meters]. I will need to use a very high resolution with these simulations;

dx = dy = 2 * pi / 2000

Please correct me if any of the following logic is flawed. I set the particles per cell ppc = 1, and I want this particle to behave like a real electron, so I define the following 'density' in SI units from the grid resolution:

n_si = 1 / (c * dx / omega_0)^3  [electrons/meter^3]

The reference density is n_ref = epsilon_0 m_e omega_0^2 / e^2 = 1.74 x 10^27  [electrons/meter^3]

So my normalized density is n = n_si / n_ref

Then the particle weight is given by w = n * dx * dy / ppc = 8.85 x 10^-5  	[particles per unit length]

So I generate this particle from positions / weights / momentum defined in a numpy array. The script runs as expected, and the trajectory is close to the analytic solutions. However the particle seems to lose momentum linearly with time, in its initial direction of travel. Disturbingly this occurs even before the electron collides with the plane wave pulse. 

Turning off the field initialization (which should have no effect, given that this is just one particle) or changing the simulation geometry from 2D -> 3D has no effect. Even removing the plane wave and changing the boundary conditions to ‘silver-muller’ in all directions, such that this is just an electron propagating through vacuum, and the electron still loses energy over time. I don’t think this is happening because of a strange boundary effect or field.

From the various simulations I have run, the loss of momentum over some period of time seems to be proportional to the particle weight. So increasing the grid size (dx), and decreasing the particle weight seems to fix the problem. But then this defeats the purpose of my simulation.

Are there maybe some fundamental limitations to Smilei that I am unaware of? Or perhaps I have made a mistake above.

Best,
Michael

![PIC_momentum](https://user-images.githubusercontent.com/60645597/126974959-dcbe5020-979a-4703-b4fa-b2468e3864c6.png)

[pwave.zip](https://github.com/SmileiPIC/Smilei/files/6877476/pwave.zip)

**Comment by Z10Frank** [comment]
Hello,
maybe the electron is changing the field (so higher weight, higher interference) and spuriously interacting with its own self-field (a known problem in Particle in Cell). Can you try defining the electron as a test electron to see if something changes?

Also, to define just one real electron, instead of using the initialization via ppc and density, you can initialise it through numpy array with its position and momentum and the particle weight calculated from the real charge of an electron.

**Comment by michaelquin** [comment]
> Hello,
> maybe the electron is changing the field (so higher weight, higher interference) and spuriously interacting with its own self-field (a known problem in Particle in Cell). Can you try defining the electron as a test electron to see if something changes?

Yes, I also wondered if it is interacting with it’s own field. How do I define a ‘test electron’?

> Also, to define just one real electron, instead of using the initialization via ppc and density, you can initialise it through numpy array with its position, momentum and the particle weight calculated from the real charge of an electron.

In my simulation I initialized the particle using numpy arrays. But I am not sure how to calculate the particle weights in this case (especially in 2D). I included the discussion above about the density and ppc to explain how I calculated the particle weights, but I know these terms are not meaningful for one particle. How would you define the weight from the real charge of the electron? In other PIC codes I usually expect w = 1, in 3D.

**Comment by Z10Frank** [comment]
For a test particle, use `is_test = True` in the `Species` block, as explained in the doc https://smileipic.github.io/Smilei/namelist.html.

For the weight of a bunch `Species `generated through numpy array for `npart` particles, with the same `weight`:
``` 
npart = 1                                                               # number of computational particles to model the electron bunch
Q_bunch = -1.602e-19                         # Coulomb (negative for electrons as usual)
normalized_species_charge = -1                      # For electrons
Q_part  = Q_bunch/npart
weight = Q_part/((c/omega0)**3*ncrit*e*normalized_species_charge)
```
where `ncrit` is the critical density for the reference wavelength. All units there are in SI, and the `weight` is converted in code units through the last command.

**Comment by michaelquin** [comment]
Thanks. Using test particles removes any numerically significant drift in the energy / momentum. I think we can conclude the particle was interacting with its own self field. 

Using real electrons, with weights calculated using your method, the effect is hopefully small enough to neglect (at the final time step in the attached plot, dux = ux_analytic – ux = -8.63 x 10^-5, and for the test particle dux = ux_analytic – ux = -1.59 x 10^-13).

I noticed your weights are dimensionless. But for a 2D simulation I was expecting units of particles / length. Should I be using 
weight = Q_part/((c/omega0)**2* ncrit * e * normalized_species_charge) ?

![momentum](https://user-images.githubusercontent.com/60645597/127131910-2ac12d5d-0cf4-442d-9f38-bc0546251780.png)

**Comment by mccoys** [comment]
@michaelquin There is no such things as "real electrons" in a PIC code (especially in 2D). Macro-electrons will always behave as a portion of a distribution. If you want to make this macro-electron behave as close as possible to a test particle, make its weight as close as possible to 0. It will thus generate a negligible current, thus produce no field (if that is what you need).

**Comment by michaelquin** [comment]
> There is no such things as "real electrons" in a PIC code (especially in 2D). Macro-electrons will always behave as a portion of a distribution. If you want to make this macro-electron behave as close as possible to a test particle, make its weight as close as possible to 0. It will thus generate a negligible current, thus produce no field (if that is what you need).

Sure, I understand. Maybe it would be best if I explain what I am trying to do:

I want to consider a sub wavelength electron bunch colliding with a counter propagating laser pulse. Specifically I am interested in the effect of inter electron forces on the trajectory of the bunch.

For a single particle I need the trajectory to be close to a real electron (otherwise I can’t distinguish the effect of the inter electron forces). But I need the currents / EM fields of the macroparticles to be representative of real electrons.

I need a very small grid size / time step to resolve these inter particle forces (among other reasons). Even having 1 particle per cell is probably more dense that the real electron bunch I will be considering. So the usual PIC technique, of representing many real particles by a macroparticle, isn’t useful in my case. I'm fully aware this is unorthodox. 

If you have any suggestions, or simply want to pour cold water on the idea, I would appreciate it either way :)

**Comment by mccoys** [comment]
From my experience in PIC simulations, this is **not** what a PIC code can do. It does not simulate individual electrons. The fields generated by one macro-particle are not representative of those from one real particle. I guess it would work in 3D for an infinitely-well resolved situation, but I would advise against it.

Anyways, I don't exactly understand what you mean by inter-electron forces. Forces are always given by the total field (the sum from all electron contribution). There is no other source.

**Comment by beck-llr** [comment]
Actually some people (like Laurent Gremillet) argue that if your resolution becomes very high this is doable. But others like myself and @MickaelGrech, if I remember well, disagree because a PIC code is a Vlasov solver and therefore can only evaluate the mean field (basically what @mccoys said). 
Wether or not the mean field converges toward the real inter-particle field when the resolution becomes infinite is still not very clear to me.

**Comment by Z10Frank** [comment]
@michaelquin small-scale forces between electrons are smoothed in a PIC simulation, by using indeed macro-particles that resemble many real particles (see for example sections 1,2 and 4 of https://juser.fz-juelich.de/record/283633/files/Lapenta_KT-2.pdf), so the fields and currents you see are those created by these macro-particles and not single electrons.

**Comment by MickaelGrech** [comment]
> Actually some people (like Laurent Gremillet) argue that if your resolution becomes very high this is doable. But others like myself and @MickaelGrech, if I remember well, disagree because a PIC code is a Vlasov solver and therefore can only evaluate the mean field (basically what @mccoys said).
> Wether or not the mean field converges toward the real inter-particle field when the resolution becomes infinite is still not very clear to me.

Our discussion with Laurent was more philosophical than practical.
In 3D, it would be in principle possible to do what you suggest, but that would require a huge resolution (at the very least you'll need to resolve the closest distance between 2 colliding particles), and it is thus in practice  impossible.
In 2D, your particles are not point particle but infinite wires (because you assume no change in the z-direction).
Hence, you do not treat correctly the microscopic fields responsible for inter-particle interactions, aka collisions.
Doing what you wanna do in 2D is just impossible.

Maybe what you can try if you wanna stick to 2D simulations is to add the collision module?

**Comment by michaeltouati** [comment]
Dear Mickael,

It is not Philosophical but Physical and Numerical.

Laurent Gremillet is right.

I've sent you two years ago during the 2019 SMILEI workshop a paper that I push my previous American colleagues to submit. We´ll submit it soon.

But you can find it again here :
https://mega.nz/file/eHoVxIQA#0rGo0_YftXdFNn7_IWxuKlwo3ZnzMZinQpwS_VEBkzg

A PIC code computes a Klimontovich-like equation for each macro-particle species discretized in space and time coupled to the discretized Maxwell equations. It tends to the Vlasov limit in the limit of an infinite number of macroparticle per cell only. 

The kinetic equation corresponding to a PIC simulation of a stable and stationary electrostatic collisionless plasma using random numbers at the simulation start (that corresponds to the average of an infinite number of the same PIC simulations using different random numbers at the simulation start) is a Vlasov-Lenard-Balescu-like kinetic equation discretized in space and time with space and time aliases of the collision operator that is overestimated by the macroparticle weight. This results can also be found in the book of Birdsall and Langdon published in the 90s using a macroparticle test approach different that the theory of fluctuations used in the paper we're going to submit.

Best regards,
Michaël

**Comment by MickaelGrech** [comment]
Dear Michael,

Vlasov and Klimontovich equations are formally the same.
They differ only on what you want f(x,p,t) to represent. 
If f(x,p,t) is a particle density in phase-space you have Klimontovich, if f(x,p,t) is a one-particle distribution function, you have Vlasov.

When we say that a PIC code solves the Vlasov equation, it means that in the limit of a very large number of macroparticles-per-cell, a PIC code will give you - whatever the spatial resolution your using, assuming of course it is small enough for your simulation not to explode - the behavior of a collisionless plasma. 

In any case, this doesn't help @michaelquin in anyway, as in 2D, he won't get the behavior he expects unless he plugs back in collisions in another form.

**Comment by michaeltouati** [comment]
Dear Mickael,

It is actually a Klimontovich-like because there is a source term corresponding to the interaction of macroparticles with the spatial grid used to compute Maxwell equations (due to the charge deposit).

Besides, I agree with you concerning the fact that Vlasov and Klimontovich equations have the same mathematical "shape" but they mean totally different things exactly as you said : the Klimontovich equations describes the evolution of the exact density of particles in the deterministic phase-space while the Vlasov equation describes the evolution of the 1-body distribution function of particles (from the Probability theory) in the case of an infinite number of particles in the Debye spheres. In Reality, there is always a finite number of particles in the Debye spheres so that you always have fluctuations correlations i.e. a collision operator even for a collisionless plasmas. The chapter 51 of Landau-Lifshitz vol 10 about Physical Kinetics describes very well this point.

I also agree with you concerning the fact that it doesn't help too much @michaelquin especially in 2D where particles are actually infinite charged lines.

**Comment by MickaelGrech** [comment]
On this we'll close the topic of Vlasov vs Klimontovich for this issue. 
But thanks for the references.

**Comment by mccoys** [comment]
Should we close this issue then?

**Comment by michaelquin** [comment]
> Should we close this issue then?

Sure. It seems that to properly treat the collisions I would need 3D, but I doubt I have the computational resources needed for such a simulation.

Thanks to everyone for the advice.
