### ISSUE TITLE
Many species initialization

### ISSUE THREAD

**Issue by ccaizergues** [SmileiPIC/Smilei#432]
Hi Smilei developpers,
I would like to define several species with the same spatial profile but with variable mixing proportions, like this:

Profile = lambda x,y :  some_function(x,y)
Ions              =  [2,12,13, …]
Proportions  =  [0.1, 0.05, 0.15, …]
for i in range(length(Ions)) :
    Species(
        …
        number_density = Profile(x,y) * Proportions[i]
    )

Yet doing like this led to all the species having the same number_density (given by the last value of i at the end of the namelist).
for example, if i runs finally the loop : "for i in species_name_list", then  number_density would even be undefined.

Would you see a practical way to force the deep copy preventing this dependency to the i temporary variable.

**Comment by mccoys** [comment]
Hi
In *python*, you cannot multiply a function by a number.
You must use something like `number_density = lambda x,y :  some_function(x,y) * Proportions[i]`

**Comment by mccoys** [comment]
Note that this is not an issue with smilei. In the future please use the chat room for this kind of request.

**Comment by ccaizergues** [comment]
Dear @mccoys , sorry for not presenting the issue correctly.
This came from an unfortunate mixing between my initial namelist pretty identical to the one you answered:
   number_density = lambda x,y : some_function(x,y) * Proportions[i]
(which is subject to the issue I described, so gives either bad proportions or a bug if i is no more an integer at the end of the namelist)
and the temporary unpractical solution that I implemented (and which works):

some_function_Z(x,y,Zion) = lambda x,y,Zion : some_function(x,y) * Proportions[Zion]
ProfileList = [lamda x,y: some_function_Z(x,y, 1), lamda x,y: some_function_Z(x,y, 2), .... ]
for i in range(length(Ions)) :
Species(
…
     number_density = ProfileList[i]
)

I agree the general problem is related to python.
Yet I was wondering if Smilei interfacing could enable some deepcopy (thanks to C++) and prevent this dependency to i (related to python interpreter kept alive during simulation) and then avoid modifying ProfileList every time a species is added or removed (as well as other diags requiring the same kind of treatment).

**Comment by mccoys** [comment]
Your text formatting is unclear. Are you sure you have correct indentation?

As for the interface with Smilei, there is no deepcopy. Smilei runs a python interpreter and obtains the python variables directly.

**Comment by ccaizergues** [comment]
Of course the declaration in the Species bloc should be with identation.
I raised this issue because it is pretty misleading (but again it is due to python not to Smilei)

**Comment by mccoys** [comment]
You can format code on github. Just surround the text with \``` ... \```

Now I am sure it is possible to do what you want to do. But without a minimal example it is hard to figure your problem.

**Comment by ccaizergues** [comment]
Dear @mccoys, below is a concrete simple example.

[proportions.py.txt](https://github.com/SmileiPIC/Smilei/files/6906880/proportions.py.txt)

You first need to replace i by j in the last diag to avoid error.
Then you do not get good species proportions (all identical between ions giving a non neutral plasma)

The second definition of number_density (commented) gives the good expected ratio.

**Comment by mccoys** [comment]
Ok I understand the issue. This is simply how python works. When you make a function with that uses a variable `i` from outside the function, it will take the value of `i` at the time when the function is called.

The trick is to convert it to a local variable inside an intermediate function:
```python
def make_profile(iZ):
    return lambda x,y: profile_1(x,y)*stoechio[iZ]

for i in range(len(Zion)):
    Species(
        ...
        number_density = make_profile(i),
    )
)
```

**Comment by ccaizergues** [comment]
Great, This worked fine.
thanks
