### ISSUE TITLE
segmentation fault 

### ISSUE THREAD

**Issue by asdg147** [SmileiPIC/Smilei#434]
Hi, I am running Smilei-4.5 on PBS server to simulate 1D Lorentz boosted frame.
As i know, there are no function to use Lorentz boosted frame so that i just gave transverse momentum to the particles.
I am struggling with segmentation fault issues with my simulation and i wonder it is from input file or smilei bug.

Below is the input file(hhg_1d) , job script i used and log file

[job_script.zip](https://github.com/SmileiPIC/Smilei/files/6980766/job_script.zip)
[log.zip](https://github.com/SmileiPIC/Smilei/files/6980764/log.zip)

[hhg_1d.zip](https://github.com/SmileiPIC/Smilei/files/6980760/hhg_1d.zip)

**Comment by mccoys** [comment]
Hi,
I see that the error occurs in `dynamics_resize` where memory is allocated. This could mean you are out of memory on your machine. Please try to increase the allocated resources for this simulation or decrease the number of particles and see if the error remains.

**Comment by asdg147** [comment]
I appreciate for your reply.
Though i tried to increase resources and decrease the number of particles, the error remains.

I defined the number density with exponential function with scale length L.
`def n_e(x):
    x1= x/l0
    if x1< A:
        return ne_max* numpy.exp( (x1-A)/L )
    else:
        return ne_max
`
No matter what machine i use(PBS server or  personal computer), it seems the error always occur if i give L below 0.05.
If L>=0.05, Problem does not occur.

**Comment by mccoys** [comment]
I can reproduce the error and it does not depend on the interpolation order. I will investigate.

**Comment by beck-llr** [comment]
I am no expert but I'm surprised to see in the log that the density functions does not use numpy. Any idea why ?

**Comment by mccoys** [comment]
> I am no expert but I'm surprised to see in the log that the density functions does not use numpy. Any idea why ?

There is a `if / else` statement, which cannot handle numpy arrays.

**Comment by asdg147** [comment]
> > I am no expert but I'm surprised to see in the log that the density functions does not use numpy. Any idea why ?
> 
> There is a `if / else` statement, which cannot handle numpy arrays.

So is it better not to use numpy?

**Comment by mccoys** [comment]
This numpy usage has nothing to do with having numpy functions inside. What @beck-llr is referring to is to have the function apply to numpy arrays instead of simple scalar values. But this is not the point of this issue.

**Comment by mccoys** [comment]
This is now fixed with the last push.
