### ISSUE TITLE
Electromagnetic fields specifically due to species 'abc'

### ISSUE THREAD

**Issue by Nikolai-mephi** [SmileiPIC/Smilei#437]
Dear smilei developers,

I have a question on the possibility of adding a certain feature.

I am conducting simulations of laser-plasma interaction and what would be very useful for my studies is the capability to save electromagnetic fields due to charged particles separately from the total electromagnetic fields resulting from both the particles and the laser. 

Is it possible to implement such option in the field diagnostics, so that I, for example, could add "Bz_abc" into 'fields' list to have the relevant magnetic field component due to species 'abc' written separately from the total field 'Bz'?

**Comment by mccoys** [comment]
I don't think this makes sense. You cannot separate fields like that. Maxwell equations can be superimposed only in vacuum.

If what you mean is to keep a separate `dE/dt = -J` versus `dE/dt = curl B`, I guess it is technically possible. But what will that tell you ? The `curl B` is also generated by particles.

**Comment by Nikolai-mephi** [comment]
Essentially, I was looking for a way to observe a laser-induced discharge wave without the laser field obscuring it, but you have a point. I guess I will try to come out with a different way to do it then.
