### ISSUE TITLE
postprocess in ipython (cluster running)

### ISSUE THREAD

**Issue by bitalm** [SmileiPIC/Smilei#44]
Dear All,

I'm trying to postprocess the data using ipython,
seems all the required steps is done,
but still the folder can not be recognized:

In [1]: import happi

In [2]:  S = happi.Open("xx/smilei/sample_laser_propagation
   ...: ")
Loaded simulation 'xx/smilei/sample_laser_propagation'
Scanning for Scalar diagnostics
Scanning for Field diagnostics
Scanning for Probe diagnostics
Scanning for ParticleBinning diagnostics
Scanning for Screen diagnostics
Scanning for Tracked particle diagnostics

In [3]: This application failed to start because it could not find or load the "
in "".

Reinstalling the application may fix this problem.
Aborted (core dumped)

Thanks in advance.

Cheers

**Comment by bitalm** [comment]
Also can I visualize the data using openpmd_viewer(openPMD_notebook)?
Thanks

**Comment by mccoys** [comment]
This looks like an issue with some graphics backend. Maybe not installed correctly.

How did you install ipython? Do you access it through ssh? 

For example try the following python commands:
```
   import matplotlib.pyplot as plt
   plt.figure()
   print(plt.get_backend())
```

Does it open a matplotlib figure? What information does it print?

**Comment by bitalm** [comment]
Dear @mccoys ,

Thanks fo ryour message and reply. I think I need to solve the plot issue, I received the same error for the above comments in ipython.

Cheers

**Comment by mccoys** [comment]
If this is not an issue with Smilei, please close the issue.
