### ISSUE TITLE
Logscale binning

### ISSUE THREAD

**Issue by Tissot11** [SmileiPIC/Smilei#442]
I have a simple question regarding using the `logscale` option in `ParticleBinning` diagnostic. According to the documentation, this option `logscale sets the axis scale to logarithmic instead of linear`. Does this result in uneven spacing of a quantity while binning or it just autoscales the axis while plotting using `happi`? Suppose I use the following diagnostic

`
DiagParticleBinning(
     deposited_quantity = "weight",
     every = 1000,
     time_average = 1,
     species = ["eon"],
     axes = [ ["p", 0.01, 200, 1000, "logscale", "edge_inclusive"] ]
)
`

Should it give `dN/dp` or `dN/d(ln p)` ? Here `N` is the density. I have checked it with some test runs and it appears that `p` has nonlinear spacing. Though for comparing with some theoretical results, I need to use `dN/dp` to get the correct match.

**Comment by mccoys** [comment]
The bins are really uneven. If you need even bins, you should not use `logscale`.

But note that happi will always give you a result as `dN/dp` because it divides the deposited quantity by each bin size.

**Comment by Tissot11** [comment]
Thanks for the quick reply! I wanted to use nonlinear bins that's why `logscale` option is good. I was a bit confused about `d N/dp`. Thanks for clarifying it!
