### ISSUE TITLE
Track particles from ID in previous identical simulation

### ISSUE THREAD

**Issue by georgeholt1** [SmileiPIC/Smilei#443]
I'm trying to achieve the following workflow and running into some difficulty:

1. Run an LWFA simulation with a moving window and infrequently save `TrackParticles` data particles that meet some criteria.
2. During post-processing, get the particle IDs and save to disk.
3. Run another simulation with frequent saving of particle tracks, with a filter selecting only the particles identified in 2.

My aim is to determine the origin and trajectories of electrons that eventually reach high energies (for example), without having to save data for all the other electrons, which can use huge amounts of disk space.

I've tried to implement a solution as in #416 but no luck so far. In the simulation file for step 1, I define

```python
def filter_high(particles):
    if Main.iteration == 0:
        return particles.x > 0
    else:
        return particles.px > 100
```

The diagnostic reads

```python
DiagTrackParticles(
    filter = filter_high,
    every = 1000,
    species = 'electron'
)
```

In step 2, I get and save the IDs from the final diagnostic dump with

```python
tracks_1 = S1.TrackParticles(species='electron')
np.savetxt('track_ids.txt', tracks.getData()['Id'][-1])
```

The simulation file for step 3 has

```python
track_ids = np.loadtxt('track_ids.txt').astype(int)
def filter_id(particles):
    if Main.iteration == 0:
        return particles.x > 0
    else:
        return np.isin(particles.id, track_ids)

...

DiagTrackParticles(
    filter = filter_id,
    every = 10,
    species = 'electron'
)
```

During post-processing, the number of particles loaded when I call `tracks_3 = S3.TrackParticles(species='electron')` is different to those loaded for the equivalent when post-processing step 1. Furthermore, `np.nanmin(tracks_3.getData()['px'])` returns a number a few decimal places larger than 100, where I expected 0 (since I am using a cold plasma). Also, plotting the trajectories these particles shows they are not the same as the ones from step 1.

Undoubtedly I am doing something wrong. However I can't seem to figure out how to correctly implement this filter having read the docs.

Any pointers are much appreciated!

**Comment by mccoys** [comment]
Are particles created during the simulation? Like ionisation?

**Comment by georgeholt1** [comment]
No ionisation in this case, but would the moving window have the same effect?
