### ISSUE TITLE
particle binning

### ISSUE THREAD

**Issue by ccaizergues** [SmileiPIC/Smilei#446]
Hi Smilei team,

I am testing the ParticleBinning diag with a user-defined function.
Here I expect to retrieve the number of macroparticles per diag cell (800, vs 2560 cells along x, 1Dgeometry).
[binning.py.txt](https://github.com/SmileiPIC/Smilei/files/7137365/binning.py.txt)

A target is placed at the middle of xaxis with 50 macroparticles/cell (and 200 near the sharp boundaries), thus I am expecting to find 160 (640 at boundaries) in the diag: ParticleBinning(1).plot(timestep=0) but there seems to be ~3 times more particles.
![Capture d’écran du 2021-09-09 16-23-47](https://user-images.githubusercontent.com/87831741/132704718-5e4949f8-58a5-4e87-b52d-3d9e8d52188d.png)

Same result with another inerpolation order.

With user-defined functions is the form factor of macro-particles taken into account and how ? (included within particle.weigth ?)

**Comment by mccoys** [comment]
The form factor is not taken into account here. To help a bit, happi should show the units in vertical axis. Is it cut out?

The discrepancy may come from the fact that happi divides by the bin size so that the result is per unit length (in your case).

Note also that you can use `np.ones_like(p.weight)` instead of `p.weight/p.weight`. This can be faster.

**Comment by ccaizergues** [comment]
I get the same graph with units in um or normalized units.
There is no applied coefficient along y (is it what you mean by "cut out" ?)
diag.units.ycoeff = 1.0
diag.units.yname = ''

reported values seem proportional to 1/dx.

For the shape factor, if I understand, only particles within a diag cell are taken into account (neglecting their form: calculation/sum in the bin volume/area, rather than projecting at the nodes of the mesh of the diag).
Particles surrounding closely the diag cell are then ignored with user-defined functions (but not with pre-implemented deposited_quantities as "weigth", etc.)

**Comment by mccoys** [comment]
I meant that the copy paste of the figure may have left out the label of the vertical axis, hiding the units that are generally displayed. 

This diagnostic completely ignores the form factor.

Check the bin size. Happi divides each value by the bin size

**Comment by ccaizergues** [comment]
I get the same result varying the number of diag cell (800, '_bsize': 3.1831040835246514)  --> (400, '_bsize': 1.5915520417623257)
![Capture d’écran du 2021-09-10 10-01-29](https://user-images.githubusercontent.com/87831741/132821046-3b12dcf2-ce8d-4358-9c7e-6393fd245dd7.png)

only varying dx changes the graph

**Comment by mccoys** [comment]
I don't think we understand each other.
The number of particle (in each bin) is divided by the bin size so that the value displayed is `number-of-particle-per-bin / bin-size`.
In your case, the bin size is `251.327 / 800 = 0.314`. So that, when you expect 160 particles in one bin, happi shows `160/0.314 = 509.3`

**Comment by ccaizergues** [comment]
Now I got the point, the y axis should not report no unit ('') but rather 'userdefined / L_r'.
Thus, even with 'um' unit displayed for the xaxis, one retrieve particle/cell with (*dx[Lr]) and particle/bin with (*1/diag._bsize)

By the way, I can't get yfactor working in this case.

**Comment by mccoys** [comment]
Yfactor is for 2D images.  In this case you need vfactor.

The unit could be displayed like you suggested on the vertical axis Indeed

**Comment by ccaizergues** [comment]
In fact I also tested vfactor. This argument is both accepted by ParticleBinning and plot, but do not modify the y axis in this particular case

**Comment by mccoys** [comment]
For some reason the vfactor is not activated. I will fix it soon. Note that you should use a factor directly in the diagnostic:
`S.ParticleBinning("2 * #0")`
