### ISSUE TITLE
Prescribed fields in 2D

### ISSUE THREAD

**Issue by ccaizergues** [SmileiPIC/Smilei#449]
Hi Smilei team,
Is the PrescribedField module available in 2D ?
Using directly the example of the "Write a Namelist" page I logically got
```
  On rank 128 [Python] TypeError: myPrescribedProfile() takes 2 positional arguments but 3 were given
	[ERROR](0) src/Profiles/Profile.cpp:268 (Profile) Profile `PrescribedField[0].profile`: does not seem to return a correct value
```

But adding the required ```y``` dimension
```
def myPrescribedProfile(x,y,t):
      return np.cos(x)*np.cos(y)*np.sin(t)

PrescribedField(
    field = "Ex",
    profile = myPrescribedProfile
)
```
The out file stops at ```Applying prescribed fields at time t = 0```  and I got in the err file
```
[irene4309:28652:0:28652] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x10)
```

code works If no field is prescribed at all.

**Comment by mccoys** [comment]
Someone asked the same question in the chat today. It looks like there is some bug that we need to fix.

Note that prescribed fields are not physical. They are used for test purposes only.

**Comment by ccaizergues** [comment]
We would like to use prescribed fields to perform some test comparisons with hydro simulations (which also have their own imperfections).

Hope the corrected version could be available soon.

If this can help, the bug does not seem to happen with 3Dgeometry

**Comment by mccoys** [comment]
I found the bug and it will be pushed on github soon

**Comment by ccaizergues** [comment]
Great, thanks !
Waiting for the new released.

**Comment by mccoys** [comment]
Should be fixed now
