### ISSUE TITLE
Filtering a few particles in TrackParticles

### ISSUE THREAD

**Issue by ccaizergues** [SmileiPIC/Smilei#450]
Hi, I am trying to select and plot some particle trajectories.

For the particle selection I set the condition (selection probability of 1/1M at iter=0, then follow):
```
def f_all(p):
    cond = (Main.iteration == 0) \
         * (np.random.randn(len(p.x))< 1e-6 ) \
         + (p.id != 0)
    return cond
```
with initial reported numbers in the out file
```
 Species creation summary
 --------------------------------------------------------------------------------
		 Species 0 (eon) created with 24871920 particles
		 Species 1 (aZ1) created with 54274360 particles
		 Species 2 (aZ6) created with 54274360 particles
		 Species 3 (aZ5) created with 54274360 particles
```
Then with 50 outputs and  ``` attributes = ['weight','x','y','px','py','pz','charge']``` I am expecting hdf5 file sizes ```~54*50*(7*8B) = 125kB``` yet I got 
```
53G	TrackParticlesDisordered_aZ1.h5
63G	TrackParticlesDisordered_aZ5.h5
63G	TrackParticlesDisordered_aZ6.h5
26G	TrackParticlesDisordered_eon.h5
```

I Also would like to select some particles during the simulation, for example, new electrons issued from ionization with a selection probability and without considering previously discarded particles, is this possible ? (by setting a special ID for discarded particles ?)

The Doc mention the possibility to select particles by their ```ID```, it is not clear to me how the user can know the ```ID``` and how he can manage it.

**Comment by mccoys** [comment]
The selection is done every timestep. Not every output. This means you get many many more selected.

**Comment by ccaizergues** [comment]
Then applying a python function to all the particles at every step can be costly ? why if output is only required at occasional timesteps ?

Anyway, in previous case the condition included  ```(Main.iteration == 0)```

**Comment by mccoys** [comment]
Sorry I was wrong the filter is not made every timestep.

You use `randn` which makes a normal distribution with negative values ...

**Comment by ccaizergues** [comment]
OK that was a stupid mistake (selecting half of the particles...)

What about handling/ particles ```ID``` ?

I also try to select particles in postprocess (if there are still too many for the graph), yet some condition based on ```np.random.rand``` do not work, as numpy is unknown from Track diag.

**Comment by mccoys** [comment]
Maybe `id % 10 ==1` ?

**Comment by ccaizergues** [comment]
That should work, provide the (Z) bits mentioned in the doc correspond to the smallest variations (then X set bigger values), it looks like so.
If I understand, to identify particles for specific purposes one has to add a multiple of ```2^(56)``` within the condition loop.

```
XXXXXXXXYYYYYYYYYYYYYYYYYYYYYYYYZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
There are 64 bits available. The first 8 (X) are not parsed by the code, but may be set by users for custom purposes.
The next 24 (Y) represent the processor number. For instance, for processor 0, all Y will equal 0; for processor 1, only the last Y will be 1.
The last 32 bits (Z) indicate the particle number.```

**Comment by mccoys** [comment]
>  If I understand, to identify particles for specific purposes one has to add a multiple of 2^(56) within the condition loop.

Yes. Otherwise you can use bitwise operators
https://wiki.python.org/moin/BitwiseOperators
https://numpy.org/doc/stable/reference/generated/numpy.bitwise_and.html
