### ISSUE TITLE
Poisson solver did not converge

### ISSUE THREAD

**Issue by obudriga** [SmileiPIC/Smilei#452]
## Description
I lunched a job and I received the warning message: "Poisson solver did not converge: reached maximum iteration number: 50000". Anyway, the code is running, but the results looks bad.

## Steps to reproduce the problem

If relevant, provide a step-by-step guide

## Parameters

- Smilei version ?
The last version
- Input file ?
import math

c = 299792458.                   # light speed in m/s
lambdar = 3.5e-7                 # laser wavelength in m
lambda1 = 0.351                  # laser wavelength in microns
wr = 2*math.pi*c/lambdar         # laser frequency in Hz

l0 = 2.0*math.pi        # laser wavelength
t0 = l0                 # optical cicle
Lsim = 3584.*l0         # length of the simulation
Tsim = 35900.*t0         # duration of the simulation
resx = 70.              # nb of cells in on laser wavelength
rest = resx/0.95        # time of timestep in one optical cycle (0.95 * CFL)
xvacuum = 285.*l0
Ilas    = 8.e15        # laser intensity in W/cm²
polarisation = 0.
if polarisation==0:
	a0          = 0.85*np.sqrt(Ilas/1e18)*lambda1   # dimensionless laser amplitude a0 in LP
else:
	a0          = 0.60*np.sqrt(Ilas/1e18)*lambda1   # dimensionless laser amplitude a0 in CP

def n0_electron(x):
    if x<=xvacuum: return 0.
    elif x<=2422.*l0: return 7.18e-3+2.82e-3*math.exp((x-285.*l0)/(558.7*l0))
    else: return 0.

def n0_ion(x):
    if x<=xvacuum: return 0.
    elif x<=2422.*l0: return 7.18e-3+2.82e-3*math.exp((x-285.*l0)/(558.7*l0))
    else: return 0.

def te_electron(x): 
    if x<=xvacuum: return 0.
    elif x<=2422.*l0: return 3.2e-3+3.76e-3*math.exp(-(x-3191.*l0)/(428.*l0))/(1+math.exp(-(x-3191.*l0)/(428.*l0)))**2
    else: return 0.

def te_ion(x):
    if x<=xvacuum: return 0.
    elif x<=2422.*l0: return 2.3e-3-4.8e-7*x/l0
    else: return 0.

#print(te_electron(1709.*l0))
 

#Checkpoints(
#    restart_dir = "../tst1d_srs_13_0",
#    dump_step = 500000,
#    dump_minutes = 2880.,
#    exit_after_dump = True,
#    keep_n_dumps = 2,
#    file_grouping = 30,
#)

Main(
    geometry = "1Dcartesian",
    interpolation_order = 2,
    cell_length = [l0/resx],
    grid_length  = [Lsim],
    number_of_patches = [512],
    timestep = t0/rest,
    simulation_time = Tsim,
    EM_boundary_conditions = [ ['silver-muller'] ],
    reference_angular_frequency_SI = wr,
    random_seed = smilei_mpi_rank,
    print_every = 100,
)

Species(
        name = 'eon',
        position_initialization = 'regular',
        momentum_initialization = 'mj',
#        momentum_initialization = 'cold',
        particles_per_cell = 77,
        mass = 1.0,
        charge = -1.0,
        number_density = n0_electron,
        temperature = [te_electron],
#        temperature = [0.],
        boundary_conditions = [
                ["reflective", "remove"],
        ],
)

Species(
        name = 'ion',
        position_initialization = 'regular',
        momentum_initialization = 'mj',
#        momentum_initialization = 'cold',
        particles_per_cell = 22,
        mass = 12852.0,
#	mass = 1836.0,
        charge = 3.5,
        number_density = n0_ion,
        temperature = [te_ion],
#        temperature = [0.],
        boundary_conditions = [
                ["reflective", "remove"],
        ],
)

LaserPlanar1D(
        box_side          = 'xmin',
        a0                = a0,
        omega             = 1.0,
        polarization_phi  = 0.,
        ellipticity       = polarisation,
        time_envelope     = ttrapezoidal(start=0., slope1=4274.*t0, plateau=Tsim-4274.*t0, slope2=0.),
)

Collisions(
	species1 = ["eon","ion"],
        species2 = ['eon',"ion"],
        coulomb_log=10.,
        debug_every=100,
        ionizing=False,
)
        
every = 500

DiagFields(
    every = every,
    fields = ['Ex','Ey','Ez','By','Bz','Rho_ion','Rho_eon']
)

DiagScalar(
    every = every,
    vars = ["Utot", "Ukin", "Uelm"],
    precision = 10
)

DiagParticleBinning(
        deposited_quantity = "weight",
        every = every,
        species = ["eon"],
        axes = [
                ["x",  0., Lsim, 500]
        ]
)

DiagParticleBinning(
        deposited_quantity = "weight",
        every = every,
        species = ["eon"],
        axes = [
                ["x",  0.,   Lsim, 500],
                ["px", -1.0, 1.0, 200]
        ]
)

DiagParticleBinning(
        deposited_quantity = "weight",
        every = every,
        species = ["eon"],
        axes = [
                 ["ekin", 0., 0.8, 200,"edge_inclusive"]
        ]
)

- Commands or script used to run the faulty simulation ?
- Computing resources
  - type of computer: HPC grid
  - OS: linux
  - C++ compiler (to get some information `g++ --version`):  4.8.5
  - MPI version (`mpic++ --version`, `mpic++ -show`): 
  - HDF5 version (`h5cc --version`): Red Hat 4.8.5-44
  - Python version (`python --version`): ipython 3.2.1
  - ...

**Comment by Z10Frank** [comment]
Hello, can you try changing the maximum number of iterations of the Poisson solver in the `Main` block, like  `poisson_max_iteration = 300000`? 
I have tried with 5 MPI and 4 threads OpenMP, obtaining the message `Poisson solver converged at iteration: 250778, relative err is ctrl = 0.940141 x 1e-14`.

**Comment by obudriga** [comment]
I've run on 2 MPI and 88 threads and indeed I've received the same message but the time in Poisson is huge 189.86.
Unfortunately, the job didn't start. I got the error message:
tack trace (most recent call last) in thread 492:
#7    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in
#6    Object "/lib64/libc.so.6", at 0x7f31d319e88c, in clone
#5    Object "/lib64/libpthread.so.0", at 0x7f31d45d6e64, in
#4    Object "/lib64/libgomp.so.1", at 0x7f31d369a3c4, in
#3    Object "/home/olimpia/olimpia-storage1/smilei/olimpia/smilei", at 0x6bd3ae, in
#2    Object "/home/olimpia/olimpia-storage1/smilei/olimpia/smilei", at 0x5fe802, in VectorPatch::applyCollisions(Params&, int, Timers&)
#1    Object "/home/olimpia/olimpia-storage1/smilei/olimpia/smilei", at 0x4718d1, in Collisions::collide(Params&, Patch*, int, std::vector<Diagnostic*, std::allocator<Diagnostic*> >&)
#0    Object "/home/olimpia/olimpia-storage1/smilei/olimpia/smilei", at 0x658d07, in Patch1D::getPrimalCellVolume(Particles*, unsigned int, Params&)
Segmentation fault (Address not mapped to object [(nil)])
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node compute1 exited on signal 11 (Segmentation fault).

**Comment by Z10Frank** [comment]
The Poisson solver is parallelized with MPI but not with OpenMP, so increasing the number of OpenMP threads will not reduce the solver time. I suggest then to increase the number of MPI processes to reduce the time: how many cores are available for your use?

Really strange for the segmentation fault, we'll investigate.

**Comment by MickaelGrech** [comment]
Olympia, two things:
1) When you wanna attach your input file, please just rename [your_input_file].py to a in [your_input_file].txt and attach it to your post. This way we can download it and run it (as it is, I would have to rewrite most of it).
2) Now, for the reason given above, I did not run your case. However, it looks to me reading your post that `n0_electron` and `n0_ion` return the same value. Hence, if you have the same `number_density`but an ion charge different than 1 (3.5 in your case) I would expect you to have a net charge. Try using `charge_density` instead of `number_density` for the ion species.

**Comment by obudriga** [comment]
Thank you very much, Mickael!

> 
> 
> The Poisson solver is parallelized with MPI but not with OpenMP, so increasing the number of OpenMP threads will not reduce the solver time. I suggest then to increase the number of MPI processes and reduce the threads to reduce the time: how many cores are available for you?
> 
> Really strange for the segmentation fault, we'll investigate.

I have a server with 2 processors, each of them has 44 threads.

**Comment by obudriga** [comment]
The code is running now, after I've changed the parameter poisson_max_iteration = 300000 and I changed the ion number density. I hope that the results will be correct.
Thank you very much!

**Comment by Z10Frank** [comment]
Indeed I thought that you wanted to have a net charge, I forgot what you had written in the Element chat before, my bad.
In that case, following Mickael's advice you should have zero net charge and no need to increase the maximum number of iterations.
