### ISSUE TITLE
What is the incindence_angle in a 3D gaussian wave?

### ISSUE THREAD

**Issue by obudriga** [SmileiPIC/Smilei#454]
I have a dilemma in defining the incidence angle for a 3D Gaussian laser pulse.
The list of the parameters incidence_angle contains two angles. These angles are described as the rotation angles around y and z-axis. 
These angles are theta and phi angles from the spherical coordinates?
I want to define a 3D Gaussian laser pulse which is propagating on a given incidence angle with the respect of x-axis (for example, of 0.1 degree).

**Comment by mccoys** [comment]
The two angles are very clear: rotation AROUND y means the axis of rotation is y. The initial propagation axis is x.

**Comment by obudriga** [comment]
OK. Thank you very much!
