### ISSUE TITLE
python3 linking

### ISSUE THREAD

**Issue by ccaizergues** [SmileiPIC/Smilei#455]
I have a linking problem in compiling the latest version of smilei downloaded with git on Irene Rome.
the environment file ```env_pyth3``` countains:
```
module purge
module load python3/3.7.5
module sw feature/hcoll/multicast/disable
module sw feature/openmpi/net/ib/ucx-ud
module load flavor/hdf5/parallel
module load hdf5
export PYTHONEXE=python3
```
and the launched script in shell is:
```
source $HOME/env_pyth3
cd $WORK/smilei3
make clean
make -j8 config=no_mpi_tm machine=joliot_curie_rome 
cd ../.
```
Previously, I already got issues with the linking for python3, so I added the following line in the makefile after lhdf5 :
```
LDFLAGS += -lhdf5
LDFLAGS += -L${PYTHON3_ROOT}lib/ -lpython3.7m
```
This (unadvised) solution still works in recompiling the former version that I used

**Comment by ccaizergues** [comment]
former version ``` Version : 4.6-237-g21b2d0b8b-master```
and error message 
```
Linking smilei
ld: cannot find -lpython3.7m
ld: cannot find -lpython3.7m
 ```

**Comment by mccoys** [comment]
Nothing has changed in the makefile since april. Your former version is from july. Something else is going on. Please check your setup is correct and use `make clean`

**Comment by mccoys** [comment]
These are the same number
