### ISSUE TITLE
Screen at cylinder

### ISSUE THREAD

**Issue by ccaizergues** [SmileiPIC/Smilei#456]
Hi,
I was wondering if a ```cylinder``` surface could be added to the TrackParticle diag.
This should fit better for some cases (```AMcylindrical``` for example)

**Comment by mccoys** [comment]
Do you mean Screen ?

**Comment by ccaizergues** [comment]
yes, sorry.

**Comment by mccoys** [comment]
This should be easy. I'll do it when possible

**Comment by mccoys** [comment]
This is now available.
