### ISSUE TITLE
happi multiplot

### ISSUE THREAD

**Issue by ccaizergues** [SmileiPIC/Smilei#458]
Hi Smilei team,

I am using happi.multiplot to plot together several curves from different simulations and follow time evolution.
Do you know if it is possible to add a legend during the animation ?

As the number of simulations to be compared can vary, which requires to regularly modify postprocess scripts, I was wondering if it could be possible to add to the usual syntax
```happi.multiPlot(D[0],D[1],D[2],D[3],D[4],D[5],.... , shape=[1,1],  ) ```
the arguments as a list of diags:
```happi.multiPlot(Dlist, shape=[1,1],  ) ```

Ideally, accepting a list of lists could even enable to compare easily different quantities from several simulations.
A close approach, may be to pass a subaxis as plot argument  ```figure=subaxis```, then not erasing the whole figure but just the sub part.
(dont' know how complicated these might be to implement).

For 2D graph videos, I tried ```skipAnimation``` to speed up the costly distant-display phase, yet it seems that the created movie only displays the very last frame.

**Comment by mccoys** [comment]
No way to plot 2 families of curves yet

For show=False you need to start python without matplotlib. I cannot remember which ipyhton option makes this possible

**Comment by mccoys** [comment]
By the way, these are questions, but not really issues about the code. If you want to ask questions on how to do things, it is better to use the Element chat (see main page), unless the question is very long.
