### ISSUE TITLE
Function with arguments which are numpy arrays

### ISSUE THREAD

**Issue by srozario121** [SmileiPIC/Smilei#46]
Hello,
I've tried to implement an arbitrary python function for the Species profile in Smilei as a float and it was found to be very slow. So in the documentation it states that it is possible to have the input arguments as numpy arrays which allows for quicker sampling of the Species profile. I'm using Smilei v3.3.

I've externally verified that my code works (using Jupyter) and returns a numpy array which is the same size as its input arguments.
![image](https://user-images.githubusercontent.com/37711146/37914635-9578caf2-310f-11e8-9dfa-0d7200b300c6.png)

In my namelist, in the species block it looks like:
![image](https://user-images.githubusercontent.com/37711146/37914503-405a3a24-310f-11e8-8a35-46f3b79c32c3.png)

However I keeping getting an error that the function does not return a correct value:
![image](https://user-images.githubusercontent.com/37711146/37914439-1f2efd8a-310f-11e8-9283-51dcb1910faa.png)

What do I have to do to make smilei use numpy arrays on external functions for profiles?
Thanks
Savio

**Comment by mccoys** [comment]
Hello,
I think one thing is missing, but it should be checked: the input and output arrays can be 2D or 3D as well. Your function seems to accept only 1D arrays.

Even if you can make it work, I doubt this will gain much speed. You are not making much use of numpy's vectorized computation. I would recommend to refactor your code by removing ``for`` loops and using only numpy vectorized operations.

**Comment by srozario121** [comment]
I've refactored my code to not have explicit for-loops and replaced with as many numpy only operations
Now this function can take and return N-dimensional arrays


![image](https://user-images.githubusercontent.com/37711146/37936971-949f651a-314f-11e8-84e4-0d46f04121de.png)

However the error has not gone away
![image](https://user-images.githubusercontent.com/37711146/37936991-afb8e8b2-314f-11e8-8e38-92e4faf37383.png)

**Comment by mccoys** [comment]
Ok, some things to make sure:
- Numpy is available when you run the simulation.
- The function returns only arrays of floats

You can also try in debug mode to have slightly more info, but I would first try a more basic function that makes use of numpy. There could be an exception thrown within the function that does not appear in the log.

You may also use the ``try`` and ``except`` directives inside the function to print out some information on whether there was a bug or not.

**Comment by srozario121** [comment]
Thanks for your help! I believe it was the fact that numpy wasn't available when the simulation runs and I couldn't handle arrays and numpy arrays as inputs.
I'm leaving a minimal working solution here if anyone else is stuck on this:
![image](https://user-images.githubusercontent.com/37711146/37968349-c74a7c04-31c5-11e8-856e-abb8f05546b1.png)
