### ISSUE TITLE
Initialization / Memory consumption

### ISSUE THREAD

**Issue by ccaizergues** [SmileiPIC/Smilei#464]
Hi developers,
I have some questions related to the initialization phase, and the use of the RAM.

I am often using experimental profiles for densities, function profiles for macro-particle ```particles_per_cell```, as well as a lot of diags, and altogether it can take quite a long time before launching ```iter=0``` (I would say usually a time close to hundreds or some thousands of regular iterations).
Do you see some explanations for the slowness during this early stage ?

I feel this is maybe too much in my case, may I have missed something in the way of using the ```profiles``` (like some declaration to force using numpy arrays rather than individual numbers ?  (also, I am not using nested ```for loops```).

I tried to follow simultaneously the progression of the initialization (in the out file) and processors activities.
It seems that the initialization phase is not OMP parallelized, then using many OMP threads can lead to a huge increase in delays.

The ```patch initialization``` phase can be very long, but does not seem memory consuming, hence I was wandering what is done there ?

After the ```Patch initialization``` section, there is a sudden and temporary peak in the memory consumption (x2 in my case) ? 
This seems related to the writing of Bin-based diagnostics (same phenomenon at later iterations) and should have been responsible for previous simulation failures.
It also appears that a lot of memory is devoted permanently to these Bin-diags (so even for non output iterations).

For example:
With only ```Fields``` and ```Scalar``` diags, I end up with a constant ```33GB``` RAM.
With Bin-diags I end up with ```45GB``` and ```90GB``` at ```every=output```.

By the way, I was surprised that the ```Fields``` diag is often reported to consume a lot of time (in comparison to similar Bin-diags)  
while the data are supposed to be available right from the grid.

**Comment by mccoys** [comment]
* initialisation is not OMP parallel due to calls to python
* Usually the most time consuming are calling profiles on every single point of the grid. That's simply python being slow. The best solution is to have numpy profiles or use a file. 
* the patch initialization creates fields and particles by evaluating profiles on each cell
* Memory is kept for binning diags when time average is requested. I don't see why you should need more than ~10 such diags. If you have many you might as well dump all particles (track) and post process. It could speed up the simulation and reduce both memory and disk usage
* Field diags are slow because of the patch decomposition that spreads the memory in many small pieces.

**Comment by ccaizergues** [comment]
The RAM is of course necessary for Screen diagnostics.
Here the issue comes from Particle Binning diagnostics. The more of these diags there are, the more the RAM is peaked at the output times.
For my test cases, there was something like ```45GB``` increase in the RAM consumption just during iteration outputs (and for every node, 4).
In the same time there are less than ```10GB``` of written data for the whole simulation and all diags (~ 5 outputs).

I do not understand why the Field diagnostic could be slower than an equivalent Binning diag (since this one needs to perform additionnal computations).

What are the possible reasons for the delays with the Hilbert curve ? I really need some balancing during the simulations, if this is required latter can the Hilbert curve correctly addapt (at its best) without severe delays (the initial postponed ones).

**Comment by mccoys** [comment]
Sorry for the delay.  

* I will test this memory issue with binning diags when possible
* Field diags do only fields and currents. You cannot choose the number of points. Plus, those currents are interpolated,  this is not the same as binning. In the end it is hard to compare the two types of diags
* I believe that the initial slowness for the hilbert curve will not appear afterwards (or at least not as slow). The balancing should occur well.

**Comment by mccoys** [comment]
I have made changes recently that should resolve the memory consumption for binning diags. Please test and reopen if the issue persists
