### ISSUE TITLE
Error when compiling Smilei

### ISSUE THREAD

**Issue by gremie** [SmileiPIC/Smilei#472]
Dear all,

I am trying to install Smilei on my Mac but I have the following messages when I compile Smilei with "make":

clang: warning: -lmpi: 'linker' input unused [-Wunused-command-line-argument]
clang: error: unsupported option '-fopenmp'

I followed these steps from https://smileipic.github.io/Smilei/installation.html :

1) xcode-select --install => OK
2) /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" => OK
3) brew install --HEAD iltommi/brews/smilei => OK
4) pip3 install ipython h5py pint numpy matplotlib scipy => OK
5) git clone https://github.com/SmileiPIC/Smilei.git => OK
6) cd Smilei -> make => ERROR

I suspect the problem is coming from the compiler but I don't know how to install correctly the "C++11 compiler".

I attached results of the following commands:

   command1: git describe --all --long
   command2: make config=verbose
   command3: make env
   command4: echo $LD_LIBRARY_PATH
   command5: python -m sysconfig
   command6: ldd smilei

[cmd1_results.txt](https://github.com/SmileiPIC/Smilei/files/7492226/cmd1_results.txt)
[cmd2_results.txt](https://github.com/SmileiPIC/Smilei/files/7492227/cmd2_results.txt)
[cmd3_results.txt](https://github.com/SmileiPIC/Smilei/files/7492228/cmd3_results.txt)
[cmd4_results.txt](https://github.com/SmileiPIC/Smilei/files/7492229/cmd4_results.txt)
[cmd5_results.txt](https://github.com/SmileiPIC/Smilei/files/7492230/cmd5_results.txt)
[cmd6_results.txt](https://github.com/SmileiPIC/Smilei/files/7492231/cmd6_results.txt)

Any suggestions will be appreciated.

Thanks

Jeremie

**Comment by iltommi** [comment]
If you want to compile Smilei by yourself, you need to install the dependencies:

I've seen you're using brew, follow these steps:

https://smileipic.github.io/Smilei/install_macos.html#brew-install-dependencies

**Comment by mccoys** [comment]
I believe the unclear part is that you don't need to do `make`.
You probably already have the executable `smilei` in the directory.

The dependencies need to be installed if you want to compile again.
