### ISSUE TITLE
Missing version number

### ISSUE THREAD

**Issue by ccaizergues** [SmileiPIC/Smilei#473]
Hi, I have downloaded and install git version last Friday, everything seems ok except the identification number is reported missing.
Did anyone else notice such behavior ?
sorry for the triviality of the point.
```
  ___           _  | |        _  \ \   Version : ??-??
 / __|  _ __   (_) | |  ___  (_)  | |   
 \__ \ | '  \   _  | | / -_)  _   | |
 |___/ |_|_|_| |_| |_| \___| |_|  | |  
                                 /_/    
 
 

 Reading the simulation parameters
 --------------------------------------------------------------------------------
 HDF5 version 1.8.20
	 Python version 3.7.5
	 Parsing pyinit.py
	 Parsing ??-??
	 Parsing pyprofiles
```

**Comment by mccoys** [comment]
This happens if you download a zip. There is no way to recover the version

**Comment by ccaizergues** [comment]
I used ```git clone https://github.com/SmileiPIC/Smilei.git``` then ```scp -r``` to ccrt.
no zip was involved, yet I had initially some "Sticky Bit"/ownership issues.

**Comment by mccoys** [comment]
Can you try the command
`git describe`

**Comment by ccaizergues** [comment]
It returns
```
fatal: ni ceci ni aucun de ses répertoires parents (jusqu'au point de montage /home) n'est un dépôt git
Arrêt à la limite du système de fichiers (GIT_DISCOVERY_ACROSS_FILESYSTEM n'est pas défini).
```
same with just re-cloned version.

for former version I get:
```
/smilei_git_2021_10_06$ git describe
v4.4-1398-g0b066a8da
/smilei_git_2021_10_06$ git describe --tags
v4.6-303-g0b066a8da
```

**Comment by mccoys** [comment]
Do you have the first version only on ccrt ? If yes, this is a ccrt problem

**Comment by iltommi** [comment]
maybe you forgot to copy the hidden folder `.git` ?

**Comment by ccaizergues** [comment]
OK, I think missed to recopy hidden files wile moving cloned version.
thanks for your help.
