### ISSUE TITLE
Field ionisation with remove boundary conditions

### ISSUE THREAD

**Issue by rl3418** [SmileiPIC/Smilei#474]
I'm trying to model the temperature distribution of the field ionized electrons. The field ionization requires laser envelopes, which only supports reflective boundary condition. The thermalization takes place in a few pico-seconds, so I don't want the laser to bounce around. 

I thought of restarting the simulation based on the initial run, such that the envelope is removed manually. The easiest way is to use checkpoints, but for that the namelist needs to remain the same, which means I still have laser bouncing around. I think I can use pickle files to dump the data from the initial run, and start another simulation based on that, but again field ionization with remove boundary conditions just makes life easier.

**Comment by beck-llr** [comment]
Just for info, we are currently finishing the implementation of "Perfectly Matched Layer" boundary conditions. We hope to be able to propose an extension of these improved absorbing boundaries for the envelope too. So stay tune and check out the next releases !

>The field ionization requires laser envelopes
This is not accurate. You can run a standard simulation (meaning without envelope and with a standard laser) with field ionization. It is even more accurate but it is also more costly in terms of computation time.

**Comment by rl3418** [comment]
> Hello, yes, that's a problem of the envelope model, it does not have non-reflective boundary conditions. I have looked into the literature for absorbing boundary conditions for an envelope model, without success for the moment.
> 
> I don't know how many particles are in your simulation, so this solution may be infeasible: you could export the phase space coordinates of the particles obtained with the ionising envelope and then initialise a simulation without envelope with those particles, and let them thermalise.

That's exactly what I'm doing at the moment.

**Comment by rl3418** [comment]
> Just for info, we are currently finishing the implementation of "Perfectly Matched Layer" boundary conditions. We hope to be able to propose an extension of these improved absorbing boundaries for the envelope too. So stay tune and check out the next releases !
> 
> > The field ionization requires laser envelopes
> 
> This is not accurate. You can run a standard simulation (meaning without envelope and with a standard laser) with field ionization. It is even more accurate but it is also more costly in terms of computation time.

For field ionization we need to set the 'ionization_model' to 'tunnel_envelope_averaged' which requires the envelope function right? Is there an alternative option?

**Comment by rl3418** [comment]
Emmm I checked the documentation. Are you saying that I can set 'ionization_model' to 'tunnel' and define a standard laser?

**Comment by rl3418** [comment]
What is the difference between 'ponderomotive_boris' and 'boris'? If I define a standard laser 'ponderomotive_boris' cannot be used right?

**Comment by rl3418** [comment]
Also is it okay to turn off pondermotive_dynamics?

**Comment by Z10Frank** [comment]
Yes, `tunnel` is the ADK tunnel ionization model used for ionization from a full laser (or another electric field sufficiently high). The `tunnel_envelope_averaged` model is used only if a laser envelope model (https://smileipic.github.io/Smilei/laser_envelope.html) is present.

The pusher called `ponderomotive_boris` can be used only with a laser envelope model. 

If you try to use `tunnel` or `ponderomotive_boris`  without an envelope you should have an error, and vice versa if you have an envelope and specify a different ionization model (other than `none`) or pusher you should have an error.

The flag `pondermotive_dynamics` is not used anymore in the current version of the code, you may want to use `git pull` and update the code.

**Comment by rl3418** [comment]
Cool, thanks for the help.

**Comment by Z10Frank** [comment]
You're welcome! For the moment I'll close the issue then, feel free to reopen it if you have other related questions, or to open new ones for other themes.
