### ISSUE TITLE
Nuclear Reaction Species Charge

### ISSUE THREAD

**Issue by ccaizergues** [SmileiPIC/Smilei#475]
Hi,
I have two simulations identical except in the declaration of the ```charge``` for the He3 nuclear product in the species bloc.
Dens_He3 and Ukin_He3 seem the same from scalar diag, however not the number of macroparticules Ntot_He3 which clearly differ.

How can the declaration of the charge matter for the simulation, then how is the charge attributed to He3, if not from the sum of parent D charges ?

**Comment by mccoys** [comment]
Could you specify the difference you see,  and the difference you have made in the input?

**Comment by ccaizergues** [comment]
The only difference in the whole namelist is on the replacement with ```charge = 2``` in the following species bloc
```
name = "He3"
Msp += [3*m_u]
Species(
    name                    = name,
    mass                    = Msp[-1],
    atomic_number           = 2,
    charge                  = 0.,
    boundary_conditions     = [["remove"]],
    position_initialization = 'random',
    momentum_initialization = 'mj',
    particles_per_cell      = 0,
    number_density          = targ_,
    #ionization_model        = 'tunnel',
    #ionization_electrons    = 'eon',
    thermal_boundary_temperature = [1e-5],
)
```

For the numerical differences, I did not notice it previously, but there is also a departure on the energies.
I think that with charge=2 some particles are early charged and then accelerated out of the box.

![image](https://user-images.githubusercontent.com/87831741/142406251-20e9cfa1-7fab-4dd4-a995-39d0d3305733.png)

**Comment by mccoys** [comment]
I am unable to reproduce this error. Could you provide a minimal input file?

**Comment by ccaizergues** [comment]
Here is what I got with following namelist: [charge=2.txt](https://github.com/SmileiPIC/Smilei/files/7579749/charge.2.txt) (change by ```charge=0``` in the He3 species bloc, for the second case)
![image](https://user-images.githubusercontent.com/87831741/142836808-24c050a5-f18f-457d-adc8-f6ba2efafc25.png)

Maybe it has something to do with random seed ?

**Comment by mccoys** [comment]
Indeed it might be related to the seed. You should remove `    random_seed             = smilei_mpi_rank,` it is not a good thing with the latest version of smilei.

**Comment by mccoys** [comment]
I really don't understand your initial Ntot plot. There is a jump in the Ntot value for He, which makes no sense. Was there anything special? Maybe a checkpoint?

**Comment by mccoys** [comment]
Did you update Smilei recently? With your example I see 0 difference with charge = 0 and charge = 2. 
The random system was modified to be more reproducible.

**Comment by ccaizergues** [comment]
I am still using the version of november the 5th (the one where I missed the version number...)

What is the problem with ``` random_seed = smilei_mpi_rank``` in the latest versions, is this just an issue of reproducibility (while changing mpi/patch numbers, I guess) or are there some related numerical bias/bug that might have been fixed since then ?
I have other simulations with similar departures between consecutive runs, then do the fluctuations enable to infer the physical ones (assuming perfect/stable experimental setting).

So you advice to set ```random_seed = k , with k>0``` ?

There was no checkpoint in the initial simulations.
Sometimes the boundary conditions can trigger a change in the rate of reactions/ number of macro-particles.
Yet, here, the jump occurs too early for the particles to reach the boundaries.

With ```charge=2``` there are some hot spots (5/6) in the map of He3 macro-particle density (no such a thing in the density map).
These appear near the start of the jump, then expand during the rise. The down slope corresponds the macro He3 absorbed at the boundary.

Maybe, this jump could be related to the numerical treatment with ```nuclear_reaction_multiplier = 0,``` while some macro-particles are of very different weight (solid part and plasma ramp mixed by the laser pulse).

**Comment by mccoys** [comment]
`random_seed = smilei_mpi_rank` was used to set a different seed in each process. Now this is done internally at the patch level. You can either set it to 0 or to any value, or you can simply not set it.

Could you share the hot spot plots?

I don't really see how `nuclear_reaction_multiplier = 0` would make a jump.

**Comment by ccaizergues** [comment]
Here a zoom on area of interest
upper part is proportional to macro-He3 density, and lower to He3 density (two closest times left/right).
![image](https://user-images.githubusercontent.com/87831741/143010930-f2696d25-de19-495d-a74b-3080d55b8ce4.png)

**Comment by mccoys** [comment]
This is not expected. I don't see how this could be related to the `charge`, as this is used only for initialization.

**Comment by ccaizergues** [comment]
If dummy ```charge``` is no way used for non pre-existing species, one possibility could be that the numerical artifacts are due to random fluctuations (unfortunately observed with the ```charge=2```, but it may have been otherwise then).
Yet, there several "hot spots".

**Comment by mccoys** [comment]
After some tests, I don't see how this could have happened. In the current version of the code, there is no variation at all with charge = 2. Did you get the error twice on the same simulation?

**Comment by ccaizergues** [comment]
I performed additional tests since last time.
I relaunched the problematic simulation, but did not get again the discontinuity  in ```Ntot_He3``` population.
Only found another previous simulation result presenting the same kind of discontinuity.
No difference using the latest Smilei version, or changing the seed initialization, I still get important departure between cases (same with charge=0 or 2).

Yet, I got a significant effect regarding the chosen computational machine, using Skylake partition instead of Rome the departure vanishes:
![image](https://user-images.githubusercontent.com/87831741/144865582-7c966286-e08c-456a-b0a0-bc45b7c3e4d1.png)


Don't know if it might be a related problem, I got another bug on Rome (not on Skylake) running embarrassingly parallel jobs, the same MPI are re-attributed to the successive job. (for the present issue, I wonder if some conflict between processors might induce the observed progressive dispersion)

**Comment by mccoys** [comment]
I don't clearly understand your message.
* Do you still get the discontinuity? If yes, in which cases?
* What did you change between your 5 cases on skylake or rome?
* Did you find the discontinuity on rome or skylake?

**Comment by mccoys** [comment]
The rome case is very strange. There should be absolutely 0 differences between rome or skylake, even with different number of MPIs. The only thing that can make the results change is a different number of patches.

Have you changed the source code ?

**Comment by ccaizergues** [comment]
No

**Comment by ccaizergues** [comment]
I have performed additional tests on three series of cases without collisions :
```sky``` (skylake and   ```random_seed = smilei_mpi_rank```), ```rome``` (rome and  ```random_seed = smilei_mpi_rank```), and ```rseed``` (rome and  ```random_seed = fixed_number```.

![image](https://user-images.githubusercontent.com/87831741/146750559-310a3620-b449-4595-afd6-5eb40adeb26d.png)

For all cases I have the following instructions in my submission file
```
export OMP_SCHEDULE=dynamic
#export OMP_PROC_BIND=true
export OMPI_MCA_btl_portals4_use_rdma=0
```

**Comment by mccoys** [comment]
With the last version of Smilei you should never use smilei_mpi_rank. It makes no sense.

I am surprised that rome gives you varying results. Did you clean an recompile on Rome?

**Comment by ccaizergues** [comment]
I also relaunched a series on rome with the more recent 15th december version, and without ```random_seed = smilei_mpi_rank``` (stems from former namelists).
![image](https://user-images.githubusercontent.com/87831741/146785642-60d9b16c-86b8-44d8-8276-8a3fcea1fe77.png)

This executable and previous ones were compiled on Rome.
Rome executable is the very first to be compiled, so build directory does not even exist initially.

**Comment by mccoys** [comment]
This is very strange. I will test on Rome when I go back to my office in January. The only way I see to have a difference is to change the number of patches

**Comment by ccaizergues** [comment]
Nothing changed between cases a to f in the namelist.
I performed an additional test on skylake, where I impose different values for the seed (```random_seed = 1..6```), then it reproduces the variations observed for rome (without setting the seed).

So it seems that these variations may be physical, but triggered by a different gestion of the seed between the computers.

The management of the ```affinity``` on rome is different that for skylake, can this enters in the definition of the seeds for the patches ?

**Comment by mccoys** [comment]
The seed is attached to the patch, not to the threads so it should not have an effect. I am still investigating.

**Comment by mccoys** [comment]
I have found the issue on ROME !

The compiler is GCC, which has a lot of options to make floating point operations faster, but not as accurate. I have seen that the intel compiler on SKL and the gcc compiler on ROME compute slightly different numbers. Sometimes, this makes a different outcome when you have a particle that is very close to a limit. When you accumulate this over billions of particles, you see the difference grow. In your case, what makes most difference is probably the thermal boundaries which randomize the distribution.

I have not found the GCC options that can prevent this random behavior, but this is not a bug in smilei.

**Comment by mccoys** [comment]
Sorry about my mistake. This was not GCC but Intel + openMPI. I will now investigate the intel flags that could matter.

**Comment by mccoys** [comment]
Ok the culprit is intel floating point calculation. Using the flag `-fp-model=strict` solves the issue (simulations may become a bit slower). I still don't understand why it is not necessary on skylake, but I can imagine it is due to the different architecture.
