### ISSUE TITLE
charge neutrality when using species of initial charge state

### ISSUE THREAD

**Issue by iplasma** [SmileiPIC/Smilei#476]
Hi, 

I have a question about initializing an ion species with initial charge state for simulation with ionization. When these species are initialized in the simulation, should I also manually initialize the electrons corresponding to the initial charge state? I am not talking about the subsequent ionized electrons, but the initial electrons. If not, since the simulation starts from zero space charge field, I think it implies there is an immobile negative charge background initially. But this is not what I want. Any thought on this?

Thanks!

**Comment by mccoys** [comment]
You need to specify an electron species. It is not automatically added. 

To easily ensure charge neutrality, use the argument charge_density

**Comment by iplasma** [comment]
Thanks for the suggestion!
