### ISSUE TITLE
run speed on cluster

### ISSUE THREAD

**Issue by m-rezaei-p** [SmileiPIC/Smilei#479]
## Description

Dear Expert,
I have a question when I try to run my code on cluster, the run is more than my PC or runs on one node in the cluster.
I read https://smileipic.github.io/Smilei/parallelization.html but I can not find any solution to this issue.
also when I try to run I got some errors about **segmentation fault**    so I add this line  patch_arrangement = "linearized_XY",  # 2D

## Parameters

- Smilei version :Version : 4.6-244
- Input file :
[laser_wakefiel_150TW.txt](https://github.com/SmileiPIC/Smilei/files/7613418/laser_wakefiel_150TW.txt)
 
- Commands or script used to run the faulty simulation : this is my bash that I use for  runing my script on cluster:
-
[laser_wakefiel_150TW_run.txt](https://github.com/SmileiPIC/Smilei/files/7613421/laser_wakefiel_150TW_run.txt)
 
  - OS: Linux

  - C++ compiler (to get some information `g++ --version`)
-  Cluster:g++ (GCC) 8.3.0
- -PC:g++ (Debian 11.2.0-10) 11.2.0
---
- MPI version (`mpic++ --version`, `mpic++ -show`)
 -Cluster:g++ (GCC) 8.3.0
 -g++ -I/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/include -pthread -Wl,-rpath -Wl,/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib -Wl,--enable-new-dtags -L/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib -lmpi_cxx -lmpi
***
 -  -PC:g++ (Debian 11.2.0-10) 11.2.0
 -  -g++ -I/opt/openmpi/include -pthread -Wl,-rpath -Wl,/opt/openmpi/lib -Wl,--enable-new-dtags -L/opt/openmpi/lib -lmpi
---
  - HDF5 version (`h5cc --version`)
   - PC and cluster: bash: h5cc: command not found...
   - PC and Cluster HDF5 version 1.12.1
---
  - Python version (`python --version`)
   - Cluster:Python 3.6.8
   - PC:Python 3.9.9
---
there are my log for:
---
run on my PC:
[log_PC.txt](https://github.com/SmileiPIC/Smilei/files/7613440/log_PC.txt)
[patch_load_PC.txt](https://github.com/SmileiPIC/Smilei/files/7613441/patch_load_PC.txt)
[profil_PC.txt](https://github.com/SmileiPIC/Smilei/files/7613442/profil_PC.txt)
[CPU_PC.txt](https://github.com/SmileiPIC/Smilei/files/7613443/CPU_PC.txt)
---
run on one node in Cluster:

[CPU_cluster_one_node.txt](https://github.com/SmileiPIC/Smilei/files/7613446/CPU_cluster_one_node.txt)
[patch_load_cluster_one_node.txt](https://github.com/SmileiPIC/Smilei/files/7613447/patch_load_cluster_one_node.txt)
[profil_cluster_one_node.txt](https://github.com/SmileiPIC/Smilei/files/7613448/profil_cluster_one_node.txt)
[log_cluster_one_node.txt](https://github.com/SmileiPIC/Smilei/files/7613449/log_cluster_one_node.txt)
---
run on 64 nodes in cluster:
[patch_load__cluster_64_node.txt](https://github.com/SmileiPIC/Smilei/files/7613450/patch_load__cluster_64_node.txt)
[Log_cluster_64_node.txt](https://github.com/SmileiPIC/Smilei/files/7613451/Log_cluster_64_node.txt)
[profil__cluster_64_node.txt](https://github.com/SmileiPIC/Smilei/files/7613452/profil__cluster_64_node.txt)

**Comment by mccoys** [comment]
You probably don't have enough particles to run on 512 cores ! Only 3 million particles.  This is typically good for 8 to 128 cores.

**Comment by mccoys** [comment]
If you have a segfault, please send some report

**Comment by m-rezaei-p** [comment]
> If you have a segfault, please send some report

I think some things in log file is not true:
when I get information about each node return: 16 CPU and Thread(s) per core:    1
but I do not know how Smilei say Thread(s) per MPI :    8
that is mean I run my code on 64CPU and in real situation total :64 cores but Smilei say 512cores.
Do you have any idea about this?

**Comment by xxirii** [comment]
Hi @m-rezaei-p 

Can you try this:
```
#!/bin/bash

#SBATCH -J rezaei               # Job name
#SBATCH -o job.%j.out         # Name of stdout output file (%j expands to jobId)
#SBATCH -p p1                # Partition to be used: p1, p2, or pa (=p1+p2)
#SBATCH -n 64             # Total number of mpi tasks requested
#SBATCH -c 1                # Number of threads per task
#SBATCH -t 165:00:00           # Run time (hh:mm:ss) - 1.5 hours, Run time should be less than 168 hours!
#SBATCH --export=ALL
# Available paritions
# p1: support up to 96 MPI tasks, default partition
# p2: support up to 64 MPI tasks
# pa: support up to 160 MPI tasks, actually p1+p2

export INSTALL_DIR=/home/rezaei/Smilei/hdf5_smile
export SMILEI_ROOT=/home/rezaei/Smilei
export PATH=${INSTALL_DIR}/bin:${PATH}
export LD_LIBRARY_PATH=${INSTALL_DIR}/lib:${LD_LIBRARY_PATH}
export HDF5_ROOT_DIR=${INSTALL_DIR}
export PYTHONEXE=python3
source /home/rezaei/pyt_libs/Smile_py/bin/activate

export CURRENT_RUN=/home/rezaei/Smile_simulation/tutorials/2d_propagation/test_speed
export NAME_RUN=laser_wakefiel_150TW.py

# OMP parameters
export OMP_NUM_THREADS=1

start=$(date +%s.%N)

prun  ${CURRENT_RUN}/smilei   ${CURRENT_RUN}/${NAME_RUN}>${NAME_RUN}.stdout


duration=$(echo "$(date +%s.%N) - $start" | bc)
execution_time=`printf "%.2f seconds" $duration`

echo "Script Execution Time: $execution_time" >time.stdout
```

You can see that I have added the following lines:
- `#SBATCH -c 1` that explicitly indicates to SLURM to use 1 cpu per mpi task
- `export OMP_NUM_THREADS=1` to use only 1 omp threads per mpi

**Comment by m-rezaei-p** [comment]
> Hi @m-rezaei-p
> 
> Can you try this:
> 
> ```
> #!/bin/bash
> 
> #SBATCH -J rezaei               # Job name
> #SBATCH -o job.%j.out         # Name of stdout output file (%j expands to jobId)
> #SBATCH -p p1                # Partition to be used: p1, p2, or pa (=p1+p2)
> #SBATCH -n 64             # Total number of mpi tasks requested
> #SBATCH -c 1                # Number of threads per task
> #SBATCH -t 165:00:00           # Run time (hh:mm:ss) - 1.5 hours, Run time should be less than 168 hours!
> #SBATCH --export=ALL
> # Available paritions
> # p1: support up to 96 MPI tasks, default partition
> # p2: support up to 64 MPI tasks
> # pa: support up to 160 MPI tasks, actually p1+p2
> 
> export INSTALL_DIR=/home/rezaei/Smilei/hdf5_smile
> export SMILEI_ROOT=/home/rezaei/Smilei
> export PATH=${INSTALL_DIR}/bin:${PATH}
> export LD_LIBRARY_PATH=${INSTALL_DIR}/lib:${LD_LIBRARY_PATH}
> export HDF5_ROOT_DIR=${INSTALL_DIR}
> export PYTHONEXE=python3
> source /home/rezaei/pyt_libs/Smile_py/bin/activate
> 
> export CURRENT_RUN=/home/rezaei/Smile_simulation/tutorials/2d_propagation/test_speed
> export NAME_RUN=laser_wakefiel_150TW.py
> 
> # OMP parameters
> export OMP_NUM_THREADS=1
> 
> start=$(date +%s.%N)
> 
> prun  ${CURRENT_RUN}/smilei   ${CURRENT_RUN}/${NAME_RUN}>${NAME_RUN}.stdout
> 
> 
> duration=$(echo "$(date +%s.%N) - $start" | bc)
> execution_time=`printf "%.2f seconds" $duration`
> 
> echo "Script Execution Time: $execution_time" >time.stdout
> ```
> 
> You can see that I have added the following lines:
> 
> * `#SBATCH -c 1` that explicitly indicates to SLURM to use 1 cpu per mpi task
> * `export OMP_NUM_THREADS=1` to use only 1 omp threads per mpi

Dear @xxirii 
Thanks now the run time of my code(3 hours) is half of the time with the previous setting(6 hours). 
Do you have any recommendation for bench mark?
Best regards,
Mohammad.

**Comment by mccoys** [comment]
What do you mean by benchmark?

It is generally recommended to change performance settings one by one and check the "push time" that is indicated in the log file. The smaller the best. Try to use a bit less cpus. Try to use Hilbert curve. Try to use load balancing. etc.

You don't need to run the whole simulation. Just check the push time for the first few timesteps.

**Comment by xxirii** [comment]
Hi @m-rezaei-p 

Sorry for my late answer, I missed the notification. I have the same question as @mccoys , what do you mean by benchmark? Do you mean a good benchmark to measure the performance on your system via Smilei? Or a physical case to test?

Concerning code performance, it is not easy to find the perfect parameters. In your case, you may try to follow @mccoys 's advice. I can see as well that you use the GNU compiler. If you have some info about the type of processor on your machine I can propose you some compilation flags to speedup the code.

**Comment by m-rezaei-p** [comment]
@xxirii  Thanks so much and I  am so sorry for reply by delay.
this is information about my CPU:
`Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   36 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           58
Model name:                      Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Stepping:                        9
CPU MHz:                         1829.201
CPU max MHz:                     3900.0000
CPU min MHz:                     1600.0000
BogoMIPS:                        6784.31
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        8 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, STIBP disabled, RSB filling
Vulnerability Srbds:             Vulnerable: No microcode
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti fsgsbase smep erms xsaveopt dtherm ida arat pln pts
`

**Comment by mccoys** [comment]
In addition, if you still have a segfault, please provide the log, and an example input file.
