### ISSUE TITLE
What does the cell index mean in a Scalar Diagnostic?

### ISSUE THREAD

**Issue by obudriga** [SmileiPIC/Smilei#481]
In the scalar.txt file there are cell indexes for the maximum values of the fields. What does these indexes mean?
E. g., the index for Ey maximum value in a 3D simulation is 12356039 at a simulation time.
I don't understand, because I have a simulation box with [1600 cells,240 cells, 240 cells]. 
This means that I have cell indexes on x-axis from 0 to 1600, on y-axis and z-axis from 0 to 241, but why 12356039?

**Comment by xxirii** [comment]
Hello @obudriga ,

Please can you provide more information like the `scalar.txt` file but also the input file and the configuration that you use.

Thank you

**Comment by obudriga** [comment]
[scalars.txt](https://github.com/SmileiPIC/Smilei/files/7668668/scalars.txt
[laser3d_cone3d.txt](https://github.com/SmileiPIC/Smilei/files/7668677/laser3d_cone3d.txt)
)
Can you see the files content?

**Comment by xxirii** [comment]
Yes thank you

**Comment by xxirii** [comment]
As far as I understand, it is a global 1d index so in your case, this index can be between 0 and `1600*240*240`, you then have to convert this index back to 3d. I am waiting for confirmation about it.

**Comment by obudriga** [comment]
I found the solution in numpy documentation.
