### ISSUE TITLE
Antenna with complex profile

### ISSUE THREAD

**Issue by Nikolai-mephi** [SmileiPIC/Smilei#483]
Dear Smilei community,

I am looking for a way to make a simulation with extra current (antenna), defined by a complex space and time profile, described by a single Python function of 4 variables Prof(x,y,z,t), that cannot be written as a product of space profile and time profile S_prof(x,y,z)*T_prof(t). From what I can see, right now it is only possible to set space and time profiles separately as two python functions that will simply be multiplied, which is not possible in my case. 

The only solution I can think of is to set multiple antennas in different parts of the simulation box and have a separate profile for each, by that is very inconvenient and the number of antennas would probably be too high.

So my question is - is it possible through, for example, modification of some source files, make antenna block accept a single function of 4 variables instead of 2 functions for space and time profile? If so, which files should I look at and what should be modified?

**Comment by mccoys** [comment]
Hi,
This needs some rewriting of the antenna code in the source. Note that calculating profiles in the entire box for each timestep can be very costly, unless the profile is computed with numpy.

**Comment by mccoys** [comment]
There is not so much to change actually. I have started and will push the modifications when possible.

**Comment by Nikolai-mephi** [comment]
Glad to hear it. Thank you very much!

**Comment by mccoys** [comment]
This is available now, but not thoroughly tested. Do not hesitate to report issues.
