### ISSUE TITLE
The program broke down in midstream (core dumped)

### ISSUE THREAD

**Issue by xiaowang119** [SmileiPIC/Smilei#487]
## Description

When I extend the simulation time, the program breaks in the middle (Tsim = 50 * t0 is fine but Tsim = 150 * t0 will give an error) . But clearly this is not a matter of low memory..

If available, copy-paste faulty code, warnings, errors, etc.
[My-3D-Collision.txt](https://github.com/SmileiPIC/Smilei/files/7738941/My-3D-Collision.txt)
[Error.txt](https://github.com/SmileiPIC/Smilei/files/7738940/Error.txt)

## Steps to reproduce the problem
Set the Tsim to a larger value, say 150 * t0 or higher; then run it directly.

## Parameters

- Smilei version ?  ==> Smilei 4.6
- Computing resources
  - type of computer  ==> Linux version 5.4.0-89-generic (buildd@lgw01-amd64-044) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04))
  - MPI version (`mpic++ --version`, `mpic++ -show`)  ==>  g++ -I/usr/local/openmpi/include -pthread -Wl,-rpath -Wl,/usr/local/openmpi/lib -Wl,--enable-new-dtags -L/usr/local/openmpi/lib -lmpi
  - HDF5 version (`h5cc --version`)  ==>  gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
  - Python version (`python --version`)  ==>  Python 3.8.10
  - ...

**Comment by xiaowang119** [comment]
/collision/9yuan-3D/21-12-15$ free -g
              total        used        free      shared  buff/cache   available
Mem:             62           3          16           0          43          58
Swap:             1           0           1

**Comment by mccoys** [comment]
Could you specify the number of cores / nodes and the number of threads/ MPI for this run?
In addition, if you know how to generate a stack trace, that would be helpful.

**Comment by xiaowang119** [comment]
1. We do not specify a specific number of running audits or threads, which is entirely at the discretion of the computer. We seem to be using OpenMP instead of MPI. Maybe. Sorry, I don’t know much about computers. And The CPU information on our computer is as follows:
> Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          104
On-line CPU(s) list:             0-103
Thread(s) per core:              2
Core(s) per socket:              26
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6


2. From the core file that was generated when the debugger was interrupted, I got the following:
> [Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
--Type <RET> for more, q to quit, c to continue without paging--c
Core was generated by `/home/fcb/pic/source/polpic0/smilei My-3D-Collision.py'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055fbc69293d1 in Projector3D2Order::currents (this=this@entry=0x55fbc9b49d10, Jx=0x55fbc9c36870, Jy=0x55fbc9c3e910, Jz=0x55fbc9c47140, particles=..., ipart=ipart@entry=378, invgf=<optimized out>, iold=0x7fc6340518c8, deltaold=0x7fc6342bdf30) at src/Projector/Projector3D2Order.cpp:131
131	    Sx1[ip_m_ipo+1] = 0.5 * ( delta2-delta+0.25 );
[Current thread is 1 (Thread 0x7fc742d86700 (LWP 5827))]

**Comment by xiaowang119** [comment]
Similarly, today the result is as follow:

> [New LWP 12064]
Cannot access memory at address 0x7ff09e09f168
Cannot access memory at address 0x7ff09e09f160
Failed to read a valid object file image from memory.
--Type <RET> for more, q to quit, c to continue without paging--c
Core was generated by `/home/fcb/pic/source/polpic0/smilei My-3D-Collision.py'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005650944fa3d1 in Projector3D2Order::currents (this=0x56509a9f5ab0, Jx=0x56509b3e0f70, Jy=<error reading variable: Cannot access memory at address 0x7ff0774a74b0>, Jz=<error reading variable: Cannot access memory at address 0x7ff0774a74b8>, particles=..., ipart=379, invgf=<optimized out>, iold=<error reading variable: Cannot access memory at address 0x7ff0774a7a10>, deltaold=<error reading variable: Cannot access memory at address 0x7ff0774a7a18>) at src/Projector/Projector3D2Order.cpp:131
131	    Sx1[ip_m_ipo+1] = 0.5 * ( delta2-delta+0.25 );
[Current thread is 1 (LWP 12041)]

**Comment by mccoys** [comment]
Could you provide the full log (Error.txt is incomplete)

**Comment by xiaowang119** [comment]
[error_full.txt](https://github.com/SmileiPIC/Smilei/files/7745408/error_full.txt)

**Comment by mccoys** [comment]
You have a CFL issue. Look at the first warning

**Comment by xiaowang119** [comment]
You’re absolutely right! Thanks for the answer.
