### ISSUE TITLE
Collision every

### ISSUE THREAD

**Issue by ccaizergues** [SmileiPIC/Smilei#488]
Hi Smilei team,
I am trying to evaluate accuracy & performance of the newly enabled ```every``` in ```collision``` blocs, with a series of test cases.
Initially all species (electron and 3 ion species) have same number of macro-particles (and ionization level close to 70%)
Here is reported the time (s) to reach iteration=75k:
```
case1: no collisions, only DiagScalar      2.3930e+04
case2: no collisions                       2.7096e+04
case3: e-e collisions, every=5             2.8721e+04

case4: e-e e-ions, every=1                 8.5357e+04
case5: e-e e-ions, every=2                 6.7353e+04
case6: e-e e-ions, every=5                 5.6721e+04
case7: e-e e-ions, every=10                5.3536e+04
```
While the cost of e-e collisions seems little, there is a net increase when enabling e-ions collisions.
The cost is no more significantly reduced for ```every>2``` and do not converge towards the no collision cases.

Density maps seem very similar between case7 and case4 (which is hopped).

total_load maps differ between case[1-3]  and case[4-7], with rather constant aspects throughout the simulation (case3 left, case7 rigth, at iter=75k) and little time directly attributed to collisions.

![image](https://user-images.githubusercontent.com/87831741/146761461-ad112a2e-b706-4589-a780-f212595dd0eb.png)
![image](https://user-images.githubusercontent.com/87831741/146761336-dd4bb43d-4d05-4895-8670-b3c625c54a97.png)

**Comment by mccoys** [comment]
Is there any issue with these numbers?
Collision cost is very complicated and has much to do with data locality so that it may depend heavily on the number of particles in each cell.

**Comment by ccaizergues** [comment]
Globally, issue would state:
If collisions carried every=1 are expected to take something like 60% of computation time
Then why carrying them every=10 do not lead to a strong reduction of simulation time (something like speed up > x2).
Hence, is the collision cost well evaluated to prevent true overloading of some cells (which would not be reported in the performance graphs or correctly detected by Smilei).

Concretely, which weighting is added to particle load when collisions are enabled ? (vs particles which do not participate to collisions).

And what is (and is not) accounted for in timer_collisions ? as the reported time does not fit computation time increase.

**Comment by mccoys** [comment]
The particle load is unaffected by collisions.  I guess this is something we should evaluate. 

The timer encompasses the treatment of collisions. There are no global communications involved, unless you use debug_every

**Comment by ccaizergues** [comment]
If the timer takes into account the treatment of collisions, why does the timer_collisions map report so little numbers in comparison to total_load map, and regarding the additional global simulation time (~ x2).
I do not use debug_every.

To redistribute some work on processors with less particles, I tried to increase particle load (froze initially + ```frozen_particle_load=2``` ) and/or to decrease cell load (```cell_load = 0.3```) but none of this helped.

**Comment by mccoys** [comment]
> If the timer takes into account the treatment of collisions, why does the timer_collisions map report so little numbers in comparison to total_load map, and regarding the additional global simulation time (~ x2).

There is an error in happi. The `total_load` is not seconds, but a number of particles (multiplied by some coeff for frozen particles) plus a number of cells (multiplied by the coeff cell_load). So you cannot compare it to the timer_collisions.

What is the collision time compared to the total timer?

**Comment by ccaizergues** [comment]
For a case with Coulomb and impact collisions (```every=5```), I got ```47e3s``` of total computation time, from which only ```Collisions    4.272049e+03    9.1e+00%``` declared in the out file.

Same case with no collisions gave ```24e3s``` execution time.
And case with only Coulomb collisions (```every=5```), gave ```30e3s``` with ```Collisions    1.711209e+03    5.6e+00%```.

Does the impact collisions also benefit from the ```every``` treatment, cause they seem to be responsible for most of the extra computation cost ?

**Comment by ccaizergues** [comment]
For the precedent cases, I report the computation times for the 100 first iterations, 100 iterations before iteration 2000 and the cumulated time (i.e. : ```(100-0) | cumulated-2000 (2000-1900)``` in second).

case1: no collisions, only DiagScalar    (  4.0143e+01 )  |   8.3776e+02   (  3.3801e+01 )
case2: no collisions                         (  4.0687e+01 )  |    8.9254e+02   (  5.1287e+01 )
case3: e-e collisions, every=5         (  4.3849e+01 )  |  9.5552e+02   (  5.2496e+01 )

case4: e-e e-ions, every=1               (  6.4915e+01 )   |   1.3692e+03   (  7.3517e+01 )
case5: e-e e-ions, every=2               (  5.4045e+01 )   |  1.1481e+03   (  6.3124e+01 )
case6: e-e e-ions, every=5               (  4.7673e+01 )   |  1.0298e+03   (  5.6904e+01 )
case7: e-e e-ions, every=10             (  4.5651e+01 )   |   9.8934e+02   (  5.7359e+01 )

1) For the 100 first iterations, collisions do not seem to significantly increase computation time (and the extra-cost is well related to the ```every``` parameter, particularly for small ```every```).
Is there some tests in the code leading to short-cuts  (e.g., do no not sort particles if already sorted) which would underestimate the load of collisions at these times ?

2) These correspond to early times, in particular, cold particles are initialized at same positions and laser has still not arrived on to target (no fields, no evolving target). Then I would expect computation time, to remain constant.
Yet, for all the cases, there is an initial tendency to increasing computation times (same observation in other simulations with similar initial conditions - can be deleterious sometimes), then followed by a decrease.
For this reason, I wonder if the management of the load is not responsible for the progressive increase of computation time with collisions.


How would you compute only collisions (and estimate effect on integrated simulation) ?

**Comment by mccoys** [comment]
1. There are only somewhat faster computations for low velocities.
2. I expect particle exchanges may create loaded cells. When there are many particles in one cell, the load may become larger than the cache and this is bad for the random memory access that the collisions need. But this effect is not easy to study.

You can use `time_fields_frozen` to prevent the computation of the field-related operations, and `time_frozen` to prevent particle push. You will still have collisions as they are outside the pusher.

It is hard to study the integrated simulation, as the load balancing effects can be very strong and advanced debugging is necessary.
