### ISSUE TITLE
ParticleBinning: "sum" actually averages

### ISSUE THREAD

**Issue by HighIander** [SmileiPIC/Smilei#490]
## Description

The ParticleBinning diagnostics "sum" option actually returns the average.

```
simulation = [ path_to_sim ]
s = happi.Open( simulation, verbose = False )
a = s.ParticleBinning( 0, sum = { "y" : "all" }, timesteps = 45000 ).getData()[-1]
b = s.ParticleBinning( 0, timesteps=45000 ).getData()[-1]
plt.figure()
plt.plot(a)
plt.plot( np.average( b, axis = 1 ) )
```

**Comment by mccoys** [comment]
It actually does a sum. But the bin size has changed so that it is equal to the total size along y. As the result is divided by the bin size, the two operations are equivalent. 

The terminology is a bit confusing but I am not convinced "average" would be clearer

**Comment by HighIander** [comment]
Well, for the Field diagnostics the corresponding option is named "average" correctly. So at least using "sum" in ParticleBinning is inconsistent, I think.
However, imho dividing the sum by the length is actually not the "sum" but exactly what is called "average". So "sum" would really be not only confusing, but in fact rather be the wrong terminology here, mathematically.

**Comment by mccoys** [comment]
I see your point, but an average would be a division by a finite number of samples. This is exactly what we do in Field diagnostics. Here we divide by the bin size as we want a density.

I guess average is better as we can see it as an average of the final result. I will ask around what people prefer. I also need to think whether this applies in all situations.

**Comment by mccoys** [comment]
This is done now in 9104b8ccccf64269857d89914051731227d00ff9
