### ISSUE TITLE
Shape function  of quasi particles

### ISSUE THREAD

**Issue by therunomask** [SmileiPIC/Smilei#491]
I'm still trying to get into understanding PIC codes and Smilei seems to be a good candidate for this purpose.

In the documentation all the information on the shape function of the quasi particles I found is
https://smileipic.github.io/Smilei/namelist.html
"Interpolation order, defines particle shape function." Where the default value is 2 which corresponds to "3 points stencil, supported in all configurations".

I'm having trouble interpreting this statement, when googling x point stencil I find finite difference schemes to approximately calculate derivatives of functions. This clearly solves a different problem than defining a shape function for a particle.

So my questions are
1. What actually is the shape function of the quasi particles
2. Would it be possible to clarify this point in the documentation

**Comment by beck-llr** [comment]
Hi
We are trying to put up the best documentation possible but unfortunately it is not possible to cover every aspect of the PIC method. There are entire books dedicated to it !
So I suggest you refer to one of these books for clarification of very broad questions such as this one. Birdsall and Langdon "Plasma Physics via computer simulation" is considered a reference.

A short answer to your question is that the shape function of a macro-particle is its density distribution in space. It affects how many grid points will be affected by its charge deposition. At order 2, 3 points are affected per dimension.

**Comment by therunomask** [comment]
I understand what the meaning of this shape function is. What I do not know is which concrete function is used in Smilei. 3 Point Stencil seems to be an inadequate answer

**Comment by beck-llr** [comment]
You will find details about the shape function in Smilei in the appendix of 
https://www.sciencedirect.com/science/article/abs/pii/S0010465517303314?via%3Dihub

It is probably the same as the PSC code since this is all very standard.

**Comment by therunomask** [comment]
thanks a lot! I found the definition. I also think it agrees with PSC.

**Comment by Z10Frank** [comment]
As good introduction to PIC codes, I would recommend:
- https://juser.fz-juelich.de/record/283633/files/Lapenta_KT-2.pdf

For more details:
- https://indico.math.cnrs.fr/event/4002/attachments/2261/2722/Grech_PIC_SMILEI2ndTrainingWshop.pdf
- https://e-publishing.cern.ch/index.php/CYR/article/view/220/162
