### ISSUE TITLE
multiple lasers in a simulation

### ISSUE THREAD

**Issue by rl3418** [SmileiPIC/Smilei#493]
I defined two lasers via LaserGaussian2D in my simulation. According to the output log two lasers were generated, but it seems that the field diagnostic (I collected 'Ez') only collected the E field for the first laser. Is there a different variable defined to store the field components of the second laser? 
![image](https://user-images.githubusercontent.com/81304719/148993329-35f6509e-089f-48de-8d22-732bdbf4e80a.png)

**Comment by mccoys** [comment]
This is not expected. Do you have a simple input file to reproduce this?

**Comment by rl3418** [comment]
[movie.txt](https://github.com/SmileiPIC/Smilei/files/7856600/movie.txt)
[laser.txt](https://github.com/SmileiPIC/Smilei/files/7856601/laser.txt)

laser.txt is the namelist I used, and movie.txt is the script I used for post-processing. According to the output log the total duration of the simulation is around 400T_r. The second laser should start at 100T_r, but only the first laser seems to be present in Ez.avi.

**Comment by rl3418** [comment]
I loaded 'intel-suite/2019.4', 'mpi/intel-2019', 'hdf5/1.10.5-parallel' and 'python 3.9'.

**Comment by rl3418** [comment]
Never mind. Forget to redefine center in tgaussian for the second laser

**Comment by Koalaaaaaa** [comment]
I saw some Chinese in your picture like "编辑器", so are you Chinese? I am studying something with multiple laser too. May I have your WeChat to ask your some questions? 
Best wishes.

**Comment by Koalaaaaaa** [comment]
> Never mind. Forget to redefine center in tgaussian for the second laser

I saw some Chinese in your picture like "编辑器", so are you Chinese? I am studying something with multiple laser too. May I have your WeChat to ask your some questions?
Best wishes.
