### ISSUE TITLE
Thomson scattering in smilei

### ISSUE THREAD

**Issue by rl3418** [SmileiPIC/Smilei#495]
Is it possible to simulate thomson scattering in smilei?

**Comment by mccoys** [comment]
No.
This is done usually in post-processing with dedicated tools. Do you have a good reason to need it included in Smilei directly?

**Comment by mccoys** [comment]
Note that, for general questions of this type, we have a chat room
https://app.element.io/#/room/!LQrdVpOJEohPSWMlmf:matrix.org

Please use issues for bugs, feature requests or other problems with the code.

**Comment by rl3418** [comment]
Cool, I will use the chat room next time. I wished to use Thomson scattering to analyze the plasma properties. Just wondering if Smilei can model the mechanism, so that I can extract the spectrum based on field outputs.

**Comment by mccoys** [comment]
My question was really why in Smilei an not use an external tool. If there is no advantage in having it inline instead of post-processing, then it will not be done

**Comment by rl3418** [comment]
Okay I will try an external tool then.
