### ISSUE TITLE
Problems with Particle injector

### ISSUE THREAD

**Issue by VadimRomansky** [SmileiPIC/Smilei#496]
## Description

I have setup with electron-positron flux, flowing from the left boundary. Problem happend when i added particle injectors. Smilei failed during initialization

## Steps to reproduce the problem

run this input file

## Parameters

- Smilei version latest
- Input file in attachment
- Commands or script used to run the faulty simulation in attachment

gcc7.2.0
[errorlog.txt](https://github.com/SmileiPIC/Smilei/files/7870803/errorlog.txt)
[input.txt](https://github.com/SmileiPIC/Smilei/files/7870804/input.txt)
[smilei_output.txt](https://github.com/SmileiPIC/Smilei/files/7870805/smilei_output.txt)
[starting_script.txt](https://github.com/SmileiPIC/Smilei/files/7870806/starting_script.txt)

python/3.5.2
openmpi/3.0.0/gcc/7.2.0
hdf5/1.10.1/gcc72

**Comment by mccoys** [comment]
I am not sure you can have an injector copying the positions of another injector if that first injector is copying positions of a species.  It must be centered or regular

**Comment by VadimRomansky** [comment]
> I am not sure you can have an injector copying the positions of another injector if that first injector is copying positions of a species. It must be centered or regular

It didn't help. Still the same error

**Comment by xxirii** [comment]
Hi @VadimRomansky,

There is indeed an incompatibility between the way you initialize the species and how you create the injectors. For the species, you use the arrays `coords1` and  `coords2` but these arrays can be used to inject particles. However, the injector will try to read from the related species all the parameters that it needs such as: 
- `number_density`
- `position_initialization`
- `particles_per_cell`

Here you have no choice than giving all parameters to the injectors like that for instance: 
```python
ParticleInjector(
	name      = "injector1",
	species   = "positrons",
	position_initialization = "regular",
	momentum_initialization = 'maxwell-juettner',
	#c_part_max = 1.0,
	particles_per_cell = 16,
	mean_velocity = [mean_velocity,0.,0.],
	temperature = [0.2],
	number_density = 1,
	box_side  = "xmin",
)
```

**Comment by VadimRomansky** [comment]
> Hi @VadimRomansky,
> 
> There is indeed an incompatibility between the way you initialize the species and how you create the injectors. For the species, you use the arrays `coords1` and `coords2` but these arrays cannot be used to inject particles. However, the injector will try to read from the related species all the parameters that it needs such as:
> 
>     * `number_density`
> 
>     * `position_initialization`
> 
>     * `particles_per_cell`
> 
> 
> Here you have no choice than giving all parameters to the injectors like that for instance:
> 
> ```python
> ParticleInjector(
> 	name      = "injector1",
> 	species   = "positrons",
> 	position_initialization = "regular",
> 	momentum_initialization = 'maxwell-juettner',
> 	#c_part_max = 1.0,
> 	particles_per_cell = 16,
> 	mean_velocity = [mean_velocity,0.,0.],
> 	temperature = [0.2],
> 	number_density = 1,
> 	box_side  = "xmin",
> )
> ```
> 
> I think however that Smilei should return a understandable error to the user here.

Great! That works. Thank you

**Comment by xxirii** [comment]
Hello, good to know. I can see that you have closed and reopened the issue. Can I close it?

**Comment by mccoys** [comment]
We should keep it open until smilei has a better error displayed

**Comment by mccoys** [comment]
The error is now updated.
