### ISSUE TITLE
EUV induced plasma

### ISSUE THREAD

**Issue by Koalaaaaaa** [SmileiPIC/Smilei#497]
hello everyone and happy new year!
In my simulation, a beam of extreme ultra-violet shoot into the box and ionize the background low pressure hydrogen. So I choose the tunnel ionization model to simulate the process of ionization, I do not know if it is right.
For the EUV whose wave length is L = 13.5nm, so the frequency is w = c/L, so I defined the reference frequency as wr = 2*pi*w. In the Laser block , the omega = 1 (unit in wr). Does it right?
Thanks for your help and best wishes!

**Comment by Z10Frank** [comment]
Yes, the `Laser` block's `omega` should be equal to 1, while the reference frequency in the `Main` block equal to `reference_angular_frequency_SI=2*math.pi*c/L`, where `L` and `c` are in `m` and `m/s` respectively.

**Comment by Koalaaaaaa** [comment]
but when I read the literature, they always define the pulse frequency as 50kHz or 25kHz, so I'm really confused.
I have another question, after the first pulse, would the electron and ion recombined? When I shoot the second pulse after the electron density tend to be stable, the density doesn't change any more. It seems like un physical.

**Comment by Z10Frank** [comment]
In this case for example https://www.osapublishing.org/abstract.cfm?uri=ASSL-2021-ATh3A.4 50 kHz is the repetition rate of the ultraviolet laser. So they are multiple ultraviolet pulses shot with a frequency of 50 kHz. But since they are ultraviolet, the carrier frequency of the pulses will be in the ultraviolet range. Can it be also your case?

**Comment by Koalaaaaaa** [comment]
so the smilei code identifies the light is in the range of EUV by the wr I difined. Got it, thank your sir.
emmmm, when I define the spatial and temprol resolution according  to the debye length and plasma frequency, my simulation should last at least for 20us. There is an error about Segment error (core dumped). When I decrease the simulation time, no error. I don't know if it is because I just use a normal laptop without MPI.
really thanks for your helps in this two days.

**Comment by Koalaaaaaa** [comment]
> In this case for example https://www.osapublishing.org/abstract.cfm?uri=ASSL-2021-ATh3A.4 50 kHz is the repetition rate of the ultraviolet laser. So they are multiple ultraviolet pulses shot with a frequency of 50 kHz. But since they are ultraviolet, the carrier frequency of the pulses will be in the ultraviolet range. Can it be also your case?

oh I think the 50kHz I should define in the time_envelope

**Comment by Z10Frank** [comment]
In the `time_envelope` you should define the temporal profile of the single pulse, not the whole train of pulses. Physically a ultraviolet laser with 50 kHz repetition rate is given by a sequence of pulses with carrier frequency in the ultraviolet range, the distance between the pulses given by c/50kHz~6e3 m. This distance is enormous, you don't simulate the train of pulses.

Instead, with this repetition rate you typically simulate the effect of the single pulse. If each pulse is a gaussian, then in the `time_envelope` you should put this gaussian profile. Note that in this case you have three characteristic lengths: 
- the distance between the pulses, c/50kHz, which will not be of interest for your simulation as far as I understand
- the length of your gaussian, which will appear in your `time_envelope` in the `Laser` block.
- The carrier wavelength in the ultraviolet range, which you use to compute the reference frequency in the `Main` block.

Please use Issues to ask questions or to report bugs only after you have a clear idea of what you want to simulate. The chat room is more suited for this kind of questions.
