### ISSUE TITLE
setting npatches in the input file

### ISSUE THREAD

**Issue by jafarimjafar** [SmileiPIC/Smilei#498]
To whom it may concern,

Dear Mr/Mis

This is Mohammad Jafari, a user of Smilei code. Thanks for providing the conditions for asking our questions. I was wondering if you could help me with my problem. My question is about the setting npatches in the input file and number of processors to run a program. Are these two parameters (npatch & np) related to each other? And how can we have optimal conditions in running a program from the “time” point of view.

I am looking forward to hearing from you.

Best regard

M. Jafari

**Comment by mccoys** [comment]
Dear M. Jafari

The page https://smileipic.github.io/Smilei/parallelization.html explains various concepts about parallelization. The number of processors is not directly related to the number of patches but it must be considered carefully when choosing the number of patches. Very importantly, you must know the number of cores in each processor. In the end, npatch must be at least larger than nproc * ncore_per_proc. It may be good to have it much larger depending on the situation. Finding optimal conditions is not obvious. I can vary strongly from one simulation to another. The best advice is to test on a few timesteps many different options.

**Comment by mccoys** [comment]
Note also that the chat room is a better place to ask this kind of questions.  Issues should address bugs or feature requests
