### ISSUE TITLE
Different results for different total simulation times in 3D geometry

### ISSUE THREAD

**Issue by obudriga** [SmileiPIC/Smilei#499]
## Description

When I run the same 3D configuration but for different simulation times I obtain different results.
I attach the 2D maps of Ex^2+Ey^2 for total simulation times of 35*laser_period and 60*laser_period:

![ExEy10micr35tau01500tstnew](https://user-images.githubusercontent.com/54900357/151403443-91b4a605-968c-4104-8b7e-8f9311849c9c.png)

![ExEy_10micr60tau01tip_1500new](https://user-images.githubusercontent.com/54900357/151403333-36ec83b9-2096-4cca-a3a5-4f04953db09d.png)

## Parameters

- Smilei version: 4.6
- Input file ?
[laser3d_gauss_cone3d_10.txt](https://github.com/SmileiPIC/Smilei/files/7952151/laser3d_gauss_cone3d_10.txt)
- Commands or script used to run the faulty simulation
[smileioli.txt](https://github.com/SmileiPIC/Smilei/files/7952171/smileioli.txt)
- Computing resources
  - type of computer: HPC
  - OS: Red Hat 4.8.5-44
  - C++ compiler (to get some information `g++ --version`):
  - MPI version (`mpic++ --version`, `mpic++ -show`):
  - HDF5 version (`h5cc --version`):
  - Python version (`python --version`): 2.7.5
  - ...

**Comment by mccoys** [comment]
What are the times of the plots ?

**Comment by mccoys** [comment]
I'm not sure what is shown exactly, but it looks like there is no targeton the first case. Are you sure you ran the same thing?

**Comment by obudriga** [comment]
Yes. These are the two namelists:
[laser3d_gauss_cone3d_10_35tau0.txt](https://github.com/SmileiPIC/Smilei/files/7953829/laser3d_gauss_cone3d_10_35tau0.txt)
[laser3d_gauss_cone3d_10_60tau0.txt](https://github.com/SmileiPIC/Smilei/files/7953831/laser3d_gauss_cone3d_10_60tau0.txt)

**Comment by mccoys** [comment]
Could you try to plot the electron density?

**Comment by obudriga** [comment]
These are the electron density at 4*laser_period and 29*laser_period:
![eldens_35tau0_4tau0new](https://user-images.githubusercontent.com/54900357/151542784-c8f8a72e-e849-48f4-9a1c-ab1a40975219.png)
![eldens_35tau0_29tau0new](https://user-images.githubusercontent.com/54900357/151542821-49f2d682-7c13-4f68-a3d9-1ec4447dc524.png)
![eldens_60tau0_29tau0](https://user-images.githubusercontent.com/54900357/151542904-8120154d-4da4-4484-ba74-3ffa3c5ae5f9.png)
![eldens_60tau0_4tau0](https://user-images.githubusercontent.com/54900357/151542920-38f6cdde-b9e5-47bc-8535-a07bbd984fac.png)
As you can see the initial electron densities look similar for both total simulation times.

**Comment by mccoys** [comment]
I just submitted a fix although I have not tested it fully yet

**Comment by obudriga** [comment]
I'm sorry, but is it necessary to recompile SMILEI?

**Comment by mccoys** [comment]
yes unfortunately. But instead, you can set the parameter `center` in the function `tgaussian` for all your runs.
