### ISSUE TITLE
If the spatial step equals to the time step, the simulation result becomes weird, does anyone know why?

### ISSUE THREAD

**Issue by Goo-JZhang** [SmileiPIC/Smilei#500]
## Description

The results of different cases are in attachments.
matched.avi presents the result of spatial and time steps are equal, and notmatched.avi presents the results of not equal.
As well as the namelist code,
`f=10.

l0  = 2.*pi         # wavelength in normalized units
t0  = l0            # optical cycle in normalized units
resx = 64.          # nb cells in 1 wavelength
rest = resx/0.95    # temporal resolution
Lv   = f*l0
Lp   = f*l0/32.
Lx   = f*2.*l0+Lp      # simulation length in x direction
Ly   = f*2.*l0+Lp      # simulation length in y direction`
t0/rest is time step while l0/resx is spatial step.

## Steps to reproduce the problem

You can set rest=resx to get the weird result.

## Parameters

- Smilei version v4.6
- Computing resources
  - type of computer
  - OS ubuntu20.04
  - C++ compiler (g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0)
  - HDF5 version (not found)
  - Python version (3.9.7)

[movies_and_code.zip](https://github.com/SmileiPIC/Smilei/files/7963854/movies_and_code.zip)

**Comment by mccoys** [comment]
This is known as the cfl condition. Particles may move more than one cell in one timestep when close to the speed of light. This is bad for the solver but also for the particle management

**Comment by mccoys** [comment]
Basically you need the timestep smaller than a fraction of the spatial step.  That exact value depends on the solver details
