### ISSUE TITLE
out-of-memory crash when initializing particles from an array

### ISSUE THREAD

**Issue by fyli16** [SmileiPIC/Smilei#501]
Hi, I am trying out initializing particles from an array (in order to have some special velocity distributions). The run crashed when initializing species, with the following error: 

> slurmstepd: error: Detected 1 oom-kill event(s) in StepId=54305938.0 cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.

It looks like caused by out-of-memory. My array files were loaded in the input deck using numpy.load, 
> position = np.load("path_to_file.npy")
>  momentum = np.load("path_to_file.npy.npy")

These two files (position & momentum) were of size 1.8 GB each for about 78 million particles. Is this too big to consider this initialization option? I have tested with reduced number of particles (~3M particles and ~70MB for each file) and it has worked. 

Any comments on loading a big chunk of particles this way? And any advice on how to do it most efficiently? Thanks!

**Comment by mccoys** [comment]
This is too much memory for many machines.

In that situation, you should first create an hdf5 file containing these arrays, then provide the path to this file in the input deck. You will find instructions here https://smileipic.github.io/Smilei/particle_initialization.html

**Comment by fyli16** [comment]
Thanks @mccoys 

I am wondering why the memory issue would be overcome by loading from a hdf5 file? Is this another solution than the more tricky one provided in this issue #258 which I came cross after submitting the present issue.

**Comment by mccoys** [comment]
Only the part of the hdf5 fille belonging to the local domain is read into memory

**Comment by mccoys** [comment]
Let me add that this initialization from file was introduced specifically to solve isuue #258

**Comment by fyli16** [comment]
Great! sorry I am reopening with a follow-up issue. 

I tried to create hdf5 files as follows: 


> f1 = h5.File('position.h5', 'w')
f2 = h5.File('momentum.h5', 'w')
f1.create_dataset('position/x', data=position[0,:])
f1.create_dataset('position/y', data=position[1,:])
f1.create_dataset('weight', data=position[2,:])
f2.create_dataset('momentum/x', data=momentum[0,:])
f2.create_dataset('momentum/y', data=momentum[1,:])
f2.create_dataset('momentum/z', data=momentum[2,:])
f1.close()
f2.close()

I supplied these hdf5 files in the input deck, but the code failed when reading the files, with the error messages attached here: 
[error.txt](https://github.com/SmileiPIC/Smilei/files/7991973/error.txt)
I have checked with HDFView that the datasets are fine and the structures follow the instructions given here: https://smileipic.github.io/Smilei/particle_initialization.html 

Is there anything wrong with the way I created the hdf5 files? Thanks.

**Comment by mccoys** [comment]
Did you provide the full path ?

**Comment by fyli16** [comment]
Yes, I provided the full and absolute paths and can confirm the paths are correct. 

> position_initialization = "/global/homes/f/fyli/nbs/chorus/data/xp/position.h5", 
momentum_initialization = "/global/homes/f/fyli/nbs/chorus/data/xp/momentum.h5",

**Comment by mccoys** [comment]
What about reading permission on this file?

**Comment by fyli16** [comment]
I just put the files in the same folder as the input deck, confirmed the 'rw' permissions, and tried again. I got the same errors.

**Comment by mccoys** [comment]
I think I have found the bug.
Momenta are searched in the same file as positions (momentum file is not read). For now, please put everything in the same file and it should work.

**Comment by fyli16** [comment]
It worked, thanks!

**Comment by mccoys** [comment]
This is fixed in the last commits
