### ISSUE TITLE
Issue with only some units appearing in plots 

### ISSUE THREAD

**Issue by robintimmis** [SmileiPIC/Smilei#504]
```
import pint
file = "/work/e281/e281/robtim2/smilei/Smilei/scripts/Diagnostics.py"
exec(compile(open(file).read(), file, 'exec'))
S = happi.Open('.')
S.ParticleBinning(0,units = ["um", "fs"]).plot(timestep=0, saveAs= 'img.png')
```

Gives the following

![img000000](https://user-images.githubusercontent.com/44679848/153065040-273224f4-86bd-4fcf-822c-2770481a3771.png)

No units next to number density. Should it have units?

If I don't include the units for x/y axes and time, ie

```
import pint
file = "/work/e281/e281/robtim2/smilei/Smilei/scripts/Diagnostics.py"
exec(compile(open(file).read(), file, 'exec'))
S = happi.Open('.')
S.ParticleBinning(0).plot(timestep=0, saveAs= 'img.png')
```

Then I get

![img](https://user-images.githubusercontent.com/44679848/153066380-65939c7a-6fc8-4d0b-933b-2afb50c6fa14.png)

Here you can see that Smilei knows about the units for x/y/t but there are none given for number density. Is number density dimensionless in Smilei? This is the case also for other diagnostics eg Ex,Bx,ekin.

**Comment by mccoys** [comment]
Could you show the definition of the binning diagnostic in your input file?

**Comment by mccoys** [comment]
The last commit should fix this issue. Please also make sure you have the package babel installed
