### ISSUE TITLE
Warning #823 when compiling Smilei

### ISSUE THREAD

**Issue by GeorgeHicks1** [SmileiPIC/Smilei#506]
Hi,

I am coming back to Smilei after a while and I am trying to compile the repository version to use the updated Diagnostics features. I have successfully compiled and run Smilei, but saw some errors during compilation,

I compiled Smilei on the Imperial College London supercomputer cx1 and cloned the git using:
`git clone https://github.com/SmileiPIC/Smilei.git`

To compile I run the commands:
```
module load intel-suite
module load mpi
module load hdf5/1.10.5-parallel
module load anaconda3/personal
make &> make_log.txt
```
My make files and the output from the make are attached here:
[makefile.txt](https://github.com/SmileiPIC/Smilei/files/8034095/makefile.txt)
[make_log.txt](https://github.com/SmileiPIC/Smilei/files/8034098/make_log.txt)

A repeated warning is:
`src/Profiles/Function.h(963): warning #823: reference is to variable "i" (declared at line 961) -- under old for-init scoping rules it would have been variable "i" (declared at line 963)`

which is then followed by an error, e.g.:
                  `ERROR( "2D polynomial profile has a wrong number of coefficients for order "<<orders[i] );`

Is this a problem?

Kind regards,
George

**Comment by mccoys** [comment]
@xxirii this might be caused by your new ERROR macros which use a for-loop with index "i". Maybe it should use another variable name like __i ?

**Comment by mccoys** [comment]
@GeorgeHicks1 I doubt this will cause problems but we will fix the warning just in case

**Comment by mccoys** [comment]
The warning should be gone in 3af5c5fd11599eae9462ec141d29343ead18c414
