### ISSUE TITLE
Weird ionization when the spatial step is comparable large.

### ISSUE THREAD

**Issue by Goo-JZhang** [SmileiPIC/Smilei#507]
I've construct a 2-specie slab whose left part is carbon and the right part is aluminum, with thickness of `0.3*`wavelength and total length of `9*`wavelength, where wavelength=0.8µm.
When I set spatial step as wavelength/32, time step=period/64, the ionized electron density is weird, which seems like electrons from aluminum part diffuse to carbon part. But when I set spatial step as wavelength/64, time step=period/128, the electron density looks normal. Dose anyone knows why?
The attachment includes movies of 2 time-spatial step and the python namelist file
[2deledis.zip](https://github.com/SmileiPIC/Smilei/files/8047590/2deledis.zip)
.

**Comment by mccoys** [comment]
I have not checked the numbers, but you must verify that your resolution is not too high with respect to the Debye length otherwise density perturbations will not be properly screened. You must also make sure that the timestep is much smaller than the plasma wave period so that plasma waves are well reproduced.

**Comment by Z10Frank** [comment]
Hello, 
together with @mccoys checks, I have some others to recommend.

There are some things in your namelist that I am not sure will work properly, so these suggestions may also help you understand what's going on:
1) for each `Species` that is ionised, use a separate `Species` of electrons from ionization, e.g. `electronfromAluminum`, `electronfromCarbon`. These species should have an initial number of particles per cell equal to zero.
2) Use a different `Species` for the neutralising electrons, e.g. `neutralizingelectrons`, that will have an initial number of particles per cell equal to `ppc`, and pay attention to have an initial `Rho = 0` everywhere at `t=0` to ensure local charge neutrality.

Currently your `electron` `Species` is gathering all electrons from these three groups (two from ionization and the background), so my suggestion is to separate them in three different `Species` to see if something changes. If the results are still weird, try to check the three groups separately, to see if more information can be retrieved.

**Comment by Goo-JZhang** [comment]
This phenomenon seems could be solved by increasing the resolution of the space or decreasing the density of slab, but I still don't know why it happens, is it related to some detailed algorithm in the code?

**Comment by Z10Frank** [comment]
Can you try my previous suggestions to see if something changes?

**Comment by Z10Frank** [comment]
I am comparing the two simulations with the mentioned resolutions at the same number of timesteps, something strange happens looking at the laser field:
```
import happi; S=happi.Open()
S.Field.Field0("Ex").slide(figure=1,vmin=-0.1*S.namelist.aL,vmax=0.1*S.namelist.aL)
```
<img width="1262" alt="Screenshot 2022-02-17 at 19 09 07" src="https://user-images.githubusercontent.com/9608804/154544942-464ea15e-f8fe-4544-92e9-8ed6208fa955.png">

The two plots come from the two simulations, one with double temporal and spatial resolution, after ~70 iterations. In one case the timestep is the double, so it's normal that `~70 iterations * timestep` gives a time that is double in code units. But the two panels are showing the same situation at different time steps, it means that in one simulation the laser is injected later. @mccoys The resolution should not change the phase of the laser in this case, right? The electrons seem to move differently when the laser is at the same injection phase, so @Goo-JZhang following @mccoys advice, what is the ratio between the Debye length and `dx`?

**Comment by mccoys** [comment]
Indeed,  please compare dx to the Debye length and dt to the plasma frequency.

**Comment by Goo-JZhang** [comment]
> 

Yep, according to my calculation, the debye length is in the order of  0.1A, my spatial step is indeed larger than that. However, the plasma frequency is of the same magnitude as laser frequency (omega_plasma=omega_laser*sqrt(number density in the code unit), if my formula is correct), and I need to set time step to very small to get the right result (for Aluminum, time step≈period/450). I'm wondering why I need such high time resolution.

**Comment by Goo-JZhang** [comment]
> 

Yep, according to my calculation, the debye length is in the order of  0.1A, my spatial step is indeed larger than that. However, the plasma frequency is of the same magnitude as laser frequency (omega_plasma=omega_laser*sqrt(number density in the code unit), if my formula is correct), and I need to set time step to very small to get the right result (for Aluminum, time step≈period/450). I'm wondering why I need such high time resolution.

**Comment by mccoys** [comment]
You need to resolve the plasma scales at which kinetic effects take place. This is the basic requirement of a kinetic code, otherwise you will encounter well-known unphysical behaviour. There are some complicated techniques that allow to have a somewhat lower resolution, but if you need a much lower resolution, you may not be using the right tool.

The Debye length requirement is usually not a strong limit. If you have a resolution coarser that the Debye length, it may still work for a while before showing unphysical heating. On the contrary, the plasma period requirement is usually a strong limit, and the simulation will quickly become unstable if not satisfied.

**Comment by Goo-JZhang** [comment]
> You need to resolve the plasma scales at which kinetic effects take place. This is the basic requirement of a kinetic code, otherwise you will encounter well-known unphysical behaviour. There are some complicated techniques that allow to have a somewhat lower resolution, but if you need a much lower resolution, you may not be using the right tool.
> 
> The Debye length requirement is usually not a strong limit. If you have a resolution coarser that the Debye length, it may still work for a while before showing unphysical heating. On the contrary, the plasma period requirement is usually a strong limit, and the simulation will quickly become unstable if not satisfied.
> 
> EDIT: I had misunderstood your question. Your electron density is ~100 so that you do resolve the plasma period indeed. I guess the issue comes from the Debye length. Now, it is unclear to me the details of the numerical heating depending on the spatial or temporal resolution. In the initial post, you mentioned that you decreased both and found good results. In your last post you seem to decrease only the time resolution.

Yeah, In a 1D-model where a laser beam comes to an Aluminum slab, I fixed the spatial step and changed the time step. I found that the result may be largely depend on time resolution. In this case, the correct electron number density is about 30, and the corresponding plasma frequency is about 5.5. In my opinion, if we want to produce a wave with frequency w, the time step about 1/(10*w) is enough (10 points in a wave length)
[1d_lasb.zip](https://github.com/SmileiPIC/Smilei/files/8103724/1d_lasb.zip)

**Comment by Z10Frank** [comment]
Edit for my third answer: my plot had a problem, for some reason it was stuck with the wrong iterations. Comparing the `Ex` of the two simulations with at the same physical time (at the top of the plot) shows the laser at the same position as it should be, with electrons moving differently.

**Comment by Goo-JZhang** [comment]
Such phenomenon is complex as I've tried different parameters, it's related to the laser intensity, spatial and time resolution, number of particles per cell... I still got no idea about the reason.
