### ISSUE TITLE
the density of species in happi seems not match with the species block

### ISSUE THREAD

**Issue by Koalaaaaaa** [SmileiPIC/Smilei#509]
hello everyone!
In my simulation, I emit some photon to the background gas hydrogen, then some hydrogen ion H+ are created by photoionization. 
In the species block, I define the hydrogen for a mass of 1836 and charge of 0 which means hydrogen atom. And the hydrogen has a initial density.
In the happi, I got the density of hydrogen in Field diagnostics: 
![48705a8fcaa149917c67afd3cb1a66b](https://user-images.githubusercontent.com/72902097/153827875-93e922c7-8d40-4c17-8287-718e297da240.png)
The density start at 0, not my initial density.
I also define a charge distribution of hydrogen in ParticleBinning.
![charge](https://user-images.githubusercontent.com/72902097/153830072-54d28dc8-3b88-4be9-b26b-437f3e5ca64e.png)
These 2 data are equal means that the density of hydrogen in Field diagnostics is the hydrogen ion.
So how can I get the data of hydrogen atom?
In fact, I expect to get double hydrogen ion (H2)+ and triple hydrogen ion (H3)+. Could this be achived in smilei?

Thanks a lot and best wishes!

**Comment by mccoys** [comment]
The first plot reveals a bug in `happi`. The `Rho_***` fields are charge densities, not number densities. Thus it displays the wrong units `N_r` instead of `Q_r * N_r`. I will fix this soon.

What it means is that the hydrogen is initially neutral so that the charge density is 0.

**Comment by Koalaaaaaa** [comment]
> The first plot reveals a bug in `happi`. The `Rho_***` fields are charge densities, not number densities. Thus it displays the wrong units `N_r` instead of `Q_r * N_r`. I will fix this soon.
> 
> What it means is that the hydrogen is initially neutral so that the charge density is 0.

thanks a lot!
And my second question, could smilei simulate the complex ionization process? 
![image](https://user-images.githubusercontent.com/72902097/153848746-8089b006-064b-4934-b3bf-fe347088ddd7.png)
I hope to get the data of (H2)+ even (H3)+. Maybe I should define the cross section of the these reaction in the code?

**Comment by mccoys** [comment]
There is no consideration of molecules in Smilei. All particles are considered like point charges with a given mass. The ionization processes assume they correspond to isolated atoms.

**Comment by Koalaaaaaa** [comment]
> There is no consideration of molecules in Smilei. All particles are considered like point charges with a given mass. The ionization processes assume they correspond to isolated atoms.

got it!

**Comment by mccoys** [comment]
The `Rho` fields now display the correct units
