### ISSUE TITLE
model hung in writing TrackParticlesDisordered_e_on.h5

### ISSUE THREAD

**Issue by kihangyoun** [SmileiPIC/Smilei#510]
Hello all,

There is a problem in performing the model.
Depending on the MPI rank, the point at which the model stops is different.
More specifically, the model performs a little bit more as I increase the MPI rank. 
Is there anything to check in a situation like the one above?
If you need additional information to help us identify the problem, please let us know.

Ex)
MPI rank 760,    Stuck at Initializing Patches phase (80% created)
MPI rank 1520,  Stuck on creating TrackParticles fields after Initializing Patches done
MPI rank 3820, Time-loop starts,  Stuck writing Fields0.h5 (9GB) at 2000 timestep
MPI rank 7600, Time-loop starts, Stuck writing Fields0.h5 (13GB) at 2000 timestep
MPI rank 11400, Time-loop starts, Stuck while writing Fields0.h5(47GB), Fields0.h5(69GB) at 2000 timestep

==== Libraries ====
Intel compiler 21.3
Intel MPI 2021.3.0
HDF5-parallel 1.10.3
python 2.7.14

**Comment by mccoys** [comment]
Hello, 
Is there any error message? How do you know the point at which it stops?

**Comment by kihangyoun** [comment]
@mccoys 

Error messages are kind of MPI error messages like below.

BAD TERMINATION OF ONE OF YOUR APPLICATION PRECESSES
RANK 2204 PID 487061 RUNNING AT HOSTNAME
KILLED BY SIGNAL; 9 (Killed)

[mpiexec@hostname] HYD_sock_write (hydra_sock_intel.c:360) : write error (Bad file desciptor)
[mpiexec@hostname] wait_proxies_to_terminate (i_mpiexec.c:541): downstream from host hostname was killed by signal 13 (Broken pipe)

**Comment by mccoys** [comment]
Please send a more detailed error report to investigate

**Comment by mccoys** [comment]
Let me close this issue. Please reopen if you think the error comes from Smilei instead of a memory issue.
