### ISSUE TITLE
no electrons are created after collisional ionization

### ISSUE THREAD

**Issue by Koalaaaaaa** [SmileiPIC/Smilei#511]
see you again! so much questions in these few days.
In my model, the background gas hydrogen is ionized by the laser and creat some electrons which I called "electron". "electron" would collision with hydrogen so that "electron2" are created by collisional ionization. However, there is no change about the "electron2" in happi. By the way, I use S.Scalar("Ntot_electron2").plot() to plot it.
![c9edf66f6fa8e6f0ad1f932e64d3c20](https://user-images.githubusercontent.com/72902097/154490334-6ac4541b-570b-4c7e-8e4f-8583ec3a4098.png)

Actually, I didn't find this problem at first. 
At first, my Collisions block is :
`Collisions(
    species1 = ["electron"],
    species2 = ["hydrogen"],
    ionizing = "electron",
    debug_every = 100
)`
In the figure above, the number of electron changes to nonzero at timestep = 600, while the number of hydrogen changes at the timestep = 650. They doesn't happen at the same time. So where are the small fraction of electrons from? At the top of the number of electron, it is about 2100. The reduced number of hydrogen atoms is not equal to 2100 at the same time obviously. Actually the ionized hydrogen atoms are just about 10. So I changed the Collisions block to see if it is because the different electrons.
`Collisions(
    species1 = ["electron"],
    species2 = ["hydrogen"],
    ionizing = "electron2",
    debug_every = 100
)`
Then I found that there seems to be no collisional ionization.
I hope I have made my questions clear.

**Comment by mccoys** [comment]
The number `Ntot_.....` is not a good value as it provides the number of macro particles, but not the number of real particles. Use instead `Dens_...` or make a dedicated `ParticleBinning` diagnostic. Then we can try to understand your issue better.

Note that the collisionnal ionisation might be very inefficient in your situation, for instance if electrons have a low energy.

**Comment by Koalaaaaaa** [comment]
> The number `Ntot_.....` is not a good value as it provides the number of macro particles, but not the number of real particles. Use instead `Dens_...` or make a dedicated `ParticleBinning` diagnostic. Then we can try to understand your issue better.
> 
> Note that the collisionnal ionisation might be very inefficient in your situation, for instance if electrons have a low energy.

thanks for your reply！I will try a ParticleBinning to analyze my simulation tomorrow and reply you. It’s already midnight in my country 😂

**Comment by mccoys** [comment]
If you are doing a 2d simulation, Dens is the total number of real particles per unit of distance z. You can obtain a density if you divide by the simulation box volume.  Read the Units doc for details. 

Rho is a charge density. 

The electron energy created by the laser might be too low indeed. But the reason might be different

**Comment by Koalaaaaaa** [comment]
OK, I will try a simple benchmark to test the collision model. 
Thanks for your patient reply!

**Comment by Koalaaaaaa** [comment]
> If you are doing a 2d simulation, Dens is the total number of real particles per unit of distance z. You can obtain a density if you divide by the simulation box volume. Read the Units doc for details.
> 
> Rho is a charge density.
> 
> The electron energy created by the laser might be too low indeed. But the reason might be different

one more question.
Could smilei realize the recombination process of electrons and ions after ionization?

**Comment by mccoys** [comment]
There is no recombination at the moment. It is much more difficult to do, and the gain is not very important unless you are considering specific conditions where the temporal scale of the simulation is much larger than the recombination time. Typically, for laser-plasma interaction, the recombination is not very significant.

**Comment by Koalaaaaaa** [comment]
> There is no recombination at the moment. It is much more difficult to do, and the gain is not very important unless you are considering specific conditions where the temporal scale of the simulation is much larger than the recombination time. Typically, for laser-plasma interaction, the recombination is not very significant.

got it
But how to explain the decrease of the average density in the whole space after pulse?( `S.Field(0,"-Rho_electron",average = {"x":"all","y":"all"},units = ["s","1/m**3"])`) The boundary conditions are all periodic. If there is no recombination, why did the average density decrease?
![eb4befeb3c1a32ead8cdc0d47271032](https://user-images.githubusercontent.com/72902097/154663117-decd794a-03d7-4cb6-9f8d-6d58a2fbb4bc.png)

**Comment by mccoys** [comment]
I don't know your simulation so it is hard to answer. Could you provide an example input file?

**Comment by mccoys** [comment]
I found out that we do not show an error whereas there should be one in your case. You cannot have periodic boundaries where the fields are not periodic. In your simulation, this means the "periodic" argument was discarded on the "x" axis and particles were escaping. I will push a fix soon so that an error is displayed. If you want to keep particles in the box, use either "reflective" or "thermalize"

**Comment by mccoys** [comment]
You will find the 1.37e18 constant by replacing the laser frequency by 2 pi c / lambda

Note that this type of general questions should be asked in the chat as it is not an issue with Smilei
