### ISSUE TITLE
Problem opening simulation using happi

### ISSUE THREAD

**Issue by DipBlue** [SmileiPIC/Smilei#512]
## Description

Explain your issue here.

Hello :) I am having an issue during post-processing using happi. The simulation seems to run fine with no errors but when it finishes and I try to open it with happi.Open it fails. Specifically, it fails during 'scanning field diagnostics'. If the field file is not present then the other diagnostics (scalar and particle binning) open just fine. 

If available, copy-paste faulty code, warnings, errors, etc.
Python gives me the following error message:
```
Traceback (most recent call last):
  File "range_evaluation.py", line 5, in <module>
    S = happi.Open(os.getcwd())  # Open the simulation.
  File "/auto/brno2/home/arsenios/smilei/Smilei/happi/__init__.py", line 36, in                                                                                                              Open
    return SmileiSimulation(*args, **kwargs)
  File "/auto/brno2/home/arsenios/smilei/Smilei/happi/_SmileiSimulation.py", lin                                                                                                             e 68, in __init__
    self.Field = FieldFactory(self)
  File "/auto/brno2/home/arsenios/smilei/Smilei/happi/_Factories.py", line 104,                                                                                                              in __init__
    child = FieldFactory(simulation, diag)
  File "/auto/brno2/home/arsenios/smilei/Smilei/happi/_Factories.py", line 115,                                                                                                              in __init__
    fields = simulation.fieldInfo(diagNumber)["fields"]
  File "/auto/brno2/home/arsenios/smilei/Smilei/happi/_SmileiSimulation.py", lin                                                                                                             e 265, in fieldInfo
    these_fields =  set(next(iter(values)).keys())
AttributeError: 'NoneType' object has no attribute 'keys'
```

## Steps to reproduce the problem

I am attaching all the relevant files for the simulation and the files I use for post-processing.

## Parameters

- Smilei version ?
- Input file ?
- Commands or script used to run the faulty simulation ?
- Computing resources
  - type of computer
  - OS
  - C++ compiler (to get some information `g++ --version`)
  - MPI version (`mpic++ --version`, `mpic++ -show`)
  - HDF5 version (`h5cc --version`)
  - Python version (`python --version`)

[2D_preplasma_skirt.py.txt](https://github.com/SmileiPIC/Smilei/files/8095175/2D_preplasma_skirt.py.txt)

[run_sim.sh.txt](https://github.com/SmileiPIC/Smilei/files/8095178/run_sim.sh.txt)

[output_sim.txt](https://github.com/SmileiPIC/Smilei/files/8095179/output_sim.txt)

[run_py_analysis.sh.txt](https://github.com/SmileiPIC/Smilei/files/8095180/run_py_analysis.sh.txt)

[range_evaluation.py.txt](https://github.com/SmileiPIC/Smilei/files/8095183/range_evaluation.py.txt)

[output_range.txt](https://github.com/SmileiPIC/Smilei/files/8095184/output_range.txt)

I am fairly new to Smilei and cluster computing so if you see any other flaws with my simulation please let me know! Thank you :)

**Comment by mccoys** [comment]
The file might be corrupted.  Is it possible to run the simulation again in a different folder?

**Comment by DipBlue** [comment]
Thank you for the quick respons. I will make a new directory and run it again. It will take around 8 hours but hopefully this fixes it! I will update you once it's finished.

**Comment by DipBlue** [comment]
I have the simulation running at the moment but I noticed there is a file in the directory during runtime which I haven't seen before. This *.lock file disappears after the simulation finishes. The contents of the directory during runtime are:

run_sim.sh      
2D_preplasma_skirt.py      
output_sim           
smilei
profil.txt      
patch_load.txt  
scalars.txt
Fields0.h5    
**Fields0.h5-459145217.lock**  
ParticleBinning0.h5  
ParticleBinning1.h5  
smilei.py

I am not sure if this file is related to the problem but I thought this piece of information might help :) Thank you.

**Comment by DipBlue** [comment]
So I run the simulation in a new folder and unfortunately I still get the same problem during post-processing :(

**Comment by mccoys** [comment]
Try to open the file with another hdf5 reader and see if it works

**Comment by DipBlue** [comment]
I am not sure what you mean. I don't know much about hdf5 files format...

**Comment by DipBlue** [comment]
I tried opening the file with python and it seems fine. I got this code from https://stackoverflow.com/questions/28170623/how-to-read-hdf5-files-in-python. Do you think I can read this file like I would with numpy and get the timesteps as numpy arrays?

>>> Python 3.6.2 (default, Aug  3 2017, 10:31:36)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
>>> import numpy as np
>>> f1 = h5py.File('Fields0.h5','r+')
>>> with h5py.File('Fields0.h5','r') as f:
...     print ('Keys: %s' % f.keys())
...     a_group_key = list(f.keys())[0]
...     data = list(f[a_group_key])
...
Keys: <KeysViewHDF5 ['data', 'tmp']>

**Comment by mccoys** [comment]
There still might be a bug in smilei. I will try a bit more reproducing the issue

**Comment by mccoys** [comment]
I cannot reproduce this issue. It is very strange that you are able to open it with python otherwise. Could you try these commands ?
```
with h5py.File("Fields0.h5", "r") as f:
    values = f["data"].values()
    print(values)
    print(next(iter(values)))
    print(next(iter(values)).keys())
```

**Comment by mccoys** [comment]
Note also that your namelist has something wrong: 
```
	if isinstance(x, np.ndarray):
             ...
	else:
		return np.zeros(10)
		```
This is a bad way to do. Smilei gets lost as it finds an array whereas it expects a single float if x is a float. You must choose either x being a float or an array.

**Comment by DipBlue** [comment]
> I cannot reproduce this issue. It is very strange that you are able to open it with python otherwise. Could you try these commands ?
> 
> ```
> with h5py.File("Fields0.h5", "r") as f:
>     values = f["data"].values()
>     print(values)
>     print(next(iter(values)))
>     print(next(iter(values)).keys())
> ```

Python 3.6.2 (default, Aug  3 2017, 10:31:36)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
>>> with h5py.File("Fields0.h5","r") as f:
...     values = f["data"].values()
...     print(values)
...     print(next(iter(values)))
...     print(next(iter(values)).keys())
...
ValuesViewHDF5(<HDF5 group "/data" (51 members)>)
None
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by DipBlue** [comment]
> Note also that your namelist has something wrong:
> 
> ```
> 	if isinstance(x, np.ndarray):
>              ...
> 	else:
> 		return np.zeros(10)
> ```
> 
> This is a bad way to do. Smilei gets lost as it finds an array whereas it expects a single float if x is a float. You must choose either x being a float or an array.

![profiles](https://user-images.githubusercontent.com/42233342/154854542-e894ef99-219a-47d2-b955-6dfaa5c2c3c4.png)

I based my code on this section but when I tried it in this form:

def ndens(x,y):
	D = np.zeros(x.shape)
	mask1 = (x>=cutoff1) & (x<plaS) # preplasma mask
	mask2 = (x>=plaS) & (x<plaE)    # plateau mask
	mask3 = (x>=plaE) & (x<cutoff2) # skirt mask
	D[mask1] = ne*np.exp((x[mask1]-plaS)/l1) 
	D[mask2] = ne
	D[mask3] = ne*np.exp((plaE-x[mask3])/l2) 
	return D

I get the error contained in this file:

[output_sim.txt](https://github.com/SmileiPIC/Smilei/files/8104465/output_sim.txt)
( On rank 0 [Python] **AttributeError: 'float' object has no attribute 'shape'**
	[ERROR](0) src/Profiles/Profile.cpp:268 (Profile) Profile `nb_density electron`: does not seem to return a correct value)

Based on this I assumed that smilei first "checks" if the function can accept floats and this is the reason for the error when trying the shape attribute. My error handling is very primitive. I basically "force" Smilei to recognize that my function outputs an array even if it tries to input a float. I probably understood this very wrong, so it would be great if you could shed some more light on how to use numpy for species profile functions. Thanks.

**Comment by mccoys** [comment]
Concerning the messages commands you executed in python, it is very strange. It is just as if the "data" group could not be read in the same way as on my PC. Could you specify what is your version of h5py?
```python
import h5py
print(h5py.version.version)
print(h5py.version.hdf5_version)
```

Now could you also try this on your system?
```python
with h5py.File("Fields0.h5", "r") as f:
    print( set(f["data"].visititems(lambda k,v:v).keys()) )
```

Concerning the last point on the ndens function, it is actually a bug related to the load balancing with the option ``initial_balance = True``

**Comment by DipBlue** [comment]
Python 3.6.2 (default, Aug  3 2017, 10:31:36)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
>>> print(h5py.version.version)
2.9.0
>>> print(h5py.version.hdf5_version)
1.10.4
>>> with h5py.File("Fields0.h5","r") as f:
...     print ( set(f["data"].visititems(lambda k,v:v).keys()) )
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/software/python-3.6.2/gcc/lib/python3.6/site-packages/h5py/_hl/group.py", line 563, in visititems
    return h5o.visit(self.id, proxy)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 355, in h5py.h5o.visit
RuntimeError: Object visitation failed (unable to determine object type)

Thanks. So if I do "git clone https://github.com/SmileiPIC/Smilei.git" after you fix the bug I will get the latest version of Smilei and this ndens error should disappear, right?

**Comment by mccoys** [comment]
1) Concerning the pasted commands. There is definitely an issue with reading those files. Maybe your python hdf5 version is incompatible with the hdf5 used by c++ in smilei? Are you using the same version?
Could you try this:
```python
with h5py.File("Fields0.h5","r") as f:
     k = f["data"].keys()
     print( k )
     print( f["data"][list(k)[0]] ) 
```

2) concerning the bug, yes you can do a git clone. Now if you have already done that before, you will just need `git pull`

**Comment by DipBlue** [comment]
>>> with h5py.File("Fields0.h5","r") as f:
...     k = f["data"].keys()
...     print(k)
...     print( f["data"][**list(k)[0]**] )
...
<KeysViewHDF5 ['0000000000', '0000000331', '0000000662', '0000000993', '0000001324', '0000001655', '0000001986', '0000002317', '0000002648', '0000002979', '0000003310', '0000003641', '0000003972', '0000004303', '0000004634', '0000004965', '0000005296', '0000005627', '0000005958', '0000006289', '0000006620', '0000006951', '0000007282', '0000007613', '0000007944', '0000008275', '0000008606', '0000008937', '0000009268', '0000009599', '0000009930', '0000010261', '0000010592', '0000010923', '0000011254', '0000011585', '0000011916', '0000012247', '0000012578', '0000012909', '0000013240', '0000013571', '0000013902', '0000014233', '0000014564', '0000014895', '0000015226', '0000015557', '0000015888', '0000016219', '0000016550']>
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/software/python-3.6.2/gcc/lib/python3.6/site-packages/h5py/_hl/group.py", line 262, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (unable to determine object type)'


 with h5py.File("Fields0.h5","r") as f:
...     k = f["data"].keys()
...     print(k)
...     print( f["data"][**list(k)[1]**] )
...
<KeysViewHDF5 ['0000000000', '0000000331', '0000000662', '0000000993', '0000001324', '0000001655', '0000001986', '0000002317', '0000002648', '0000002979', '0000003310', '0000003641', '0000003972', '0000004303', '0000004634', '0000004965', '0000005296', '0000005627', '0000005958', '0000006289', '0000006620', '0000006951', '0000007282', '0000007613', '0000007944', '0000008275', '0000008606', '0000008937', '0000009268', '0000009599', '0000009930', '0000010261', '0000010592', '0000010923', '0000011254', '0000011585', '0000011916', '0000012247', '0000012578', '0000012909', '0000013240', '0000013571', '0000013902', '0000014233', '0000014564', '0000014895', '0000015226', '0000015557', '0000015888', '0000016219', '0000016550']>
<HDF5 group "/data/0000000331" (4 members)>

I had noticed this behaviour before. Somehow there is something wrong with the 0th element but the rest are fine... That is why in my solution to the problem I iterate through the list starting from item 1:

"""
import h5py
import numpy as np

Ex = [] ; Ey = [] ; Rho_e = [] ; Rho_p = []
Comment: List of data arrays (one array for each timestep).

with h5py.File("Fields0.h5", "r") as f:
timeKeys = list(f['data'].keys())
for t in **timeKeys[1:]**:
print(t)
Ex.append(np.array(f["/data/" + t + "/Ex"][:]))
Ey.append(np.array(f["/data/" + t + "/Ey"][:]))
Rho_e.append(np.array(f["/data/" + t + "/Rho_electron"][:]))
Rho_p.append(np.array(f["/data/" + t + "/Rho_proton"][:]))
"""

**Comment by mccoys** [comment]
This is not a good behavior for h5py. Your installation is faulty. Either from your hdf5 library or from h5py itself.

**Comment by mccoys** [comment]
As this error is likely to originate from your installation, is it possible to close the issue, or is there more you wish to add?

**Comment by DipBlue** [comment]
Sure, thank you for the assistance :)
