### ISSUE TITLE
Post processing of vtk format

### ISSUE THREAD

**Issue by Sonuphd** [SmileiPIC/Smilei#513]
Respected Sir,

I am facing a difficulty during converting my 3D result into vtk format. I have attached a screenshot related with this issue. Please solve my problem.

Thanks and Regards,
Sonu Kumar

![Screenshot (15)](https://user-images.githubusercontent.com/42186182/154836147-db8cf353-3298-4849-b656-01b1b79f4261.png)

**Comment by mccoys** [comment]
Please update to the last version as some bugs were fixed recently.  Please provide an example that is quick to run, and the happi commands that do not work

**Comment by Sonuphd** [comment]
Respected Sir,

I am providing you my input file and happi command screenshot. Please find the attached scrrenshot.
![Screenshot (16)](https://user-images.githubusercontent.com/42186182/154901171-8c8077a1-0060-45a4-96bb-54023a0379ba.png)



import math


l0 = 2.0*math.pi # laser wavelength [in code units]
t0 = l0  # optical cycle
Lsimx = 300.*l0  # length of the simulation box in x (= 240 mum)
Lsimy = 80.*l0  # length of the simulation box in y (= 64 mum)
Tsim = 900.*t0  # duartion of the simulation (= 2.4 ps)
resx = 16.
resy = 2.  # nb of cells in on laser wavelength
rest = resx/0.8  # nb of timesteps in one optical cycle
dt = t0/rest
nx = 300*16  # nb of cells along x-axis
npatchx = 32 # nb of patches along x-axis

# -----------
# n0max = 5.734e-3 # electron density (code units =>1=plasma critical density)

# initial density profile of electrons
# def n0_electron(x,y):
# return 1./(1.+math.exp((abs(x-x0)-widthx)/Lx))*n0max

#------------



# DEFINING SMILEI's VARIABLES
# All in "bloacks"

Main(
    geometry = "2Dcartesian",
    interpolation_order = 2,
    timestep = dt,
    simulation_time = Tsim,
    cell_length = [l0/resx,l0/resy],
    grid_length = [Lsimx,Lsimy],
    number_of_patches = [32,16],
    clrw = nx/npatchx,
    reference_angular_frequency_SI = 2.0*math.pi*3e8/0.8e-6,
    EM_boundary_conditions = [["silver-muller","silver-muller"],["silver-muller","silver-muller"],],
    solve_poisson = False,
    print_every = 100,
    random_seed = smilei_mpi_rank
    )

    

MovingWindow(
    time_start = 0.9*Main.grid_length[0],
    velocity_x = 0.9997
    )

LoadBalancing(
        initial_balance = False,
    every  = 20,
    cell_load = 1.,

    )

    
Species(
    name = "electron",
    position_initialization = "regular",
    momentum_initialization = "cold",
    particles_per_cell = 4,
    mass = 1.0,
    charge = -1.0,
    number_density = 0.005734,
    mean_velocity = [0.0,0.0,0.0],
    pusher = "boris",
    time_frozen = 0.0,
    boundary_conditions = [["remove","remove"],["remove","remove"],],
    )

FWHMinI = 12.5*l0 #(= 10 mum)
waistinI = FWHMinI/(2.0*math.sqrt(math.log(2.0)))
waistinE = FWHMinI/math.sqrt(2.0*math.log(2.0))
FWHMtinI = 8.0*t0  #(= 21.3 fs)
FWHMtinE = FWHMtinI*math.sqrt(2.0)  

diagEvery = int(37.5*t0/dt) 


LaserGaussian2D(
box_side = "xmin",
a0 = 3.68,  # intensity 2.9 e+19
omega = 1.,
focus = [0.,Main.grid_length[1]/2.],
waist = waistinE,

time_envelope = ttrapezoidal(start=0.,plateau=16.0*FWHMtinE,slope1=2.0*FWHMtinE,slope2=2.0*FWHMtinE)


)
list_fields = ['Ex','Ey','Bz','Rho','Jx']


DiagFields(
every = diagEvery,
fields = list_fields
)

DiagProbe(
    every = diagEvery,
    origin = [0.,Main.grid_length[1]/2.],
    corners = [[Main.grid_length[0],Main.grid_length[1]/2.],
           ],
    number = [nx],
    fields = list_fields
    )

DiagScalar(
    every = int(diagEvery/10),
    vars=['Uelm','Ukin_electron',
          'ExMax','ExMaxCell','EyMax','EyMaxCell','RhoMin',
          'RhoMinCell','Ukin_bnd','Uelm_bnd','Ukin_out_mvw','Ukin_inj_mvw','Uelm_out_mvw','Uelm_inj_mvw','Utot']
    )

DiagParticleBinning(
    deposited_quantity = "weight",
    every = diagEvery,
    species =  ["electron"],
    axes = [
        ["moving_x",0., Lsimx, 300],
        ["ekin",1.,500.,200]
        ]
    )
DiagParticleBinning(
    deposited_quantity = "weight",
    every = diagEvery,
    species =  ["electron"],
    axes = [
        ["moving_x",0., Lsimx, 300],
        ["px",-1.,1.,100]
        ]
    )
DiagParticleBinning(
    deposited_quantity = "weight",
    every = diagEvery,
    species =  ["electron"],
    axes = [
        ["y",0., Lsimy, 300],
        ["py",-1.,1.,100]
        ]
    )

DiagParticleBinning(
    deposited_quantity = "weight",
    every = diagEvery,
    species =  ["electron"],
    axes = [
        ["moving_x",0., Lsimx, 300],
        ["px",-1.,1.,100]
        ]
    )
DiagParticleBinning(
    deposited_quantity = "weight",
    every = diagEvery,
    species =  ["electron"],
    axes = [
        ["y",0., Lsimy, 300],
        ["py",-1.,1.,100]]

        )
DiagPerformances(
    every = diagEvery
    )

**Comment by Sonuphd** [comment]
Respected Sir,

I am using Smilei version 4.5. in my institute HPC account. I have attached a screenshot for happi command and input data.
![Screenshot (16)](https://user-images.githubusercontent.com/42186182/154929139-8f245be4-8886-4a86-a914-500130801066.png)

import math


l0 = 2.0*math.pi # laser wavelength [in code units]
t0 = l0  # optical cycle
Lsimx = 300.*l0  # length of the simulation box in x (= 240 mum)
Lsimy = 80.*l0  # length of the simulation box in y (= 64 mum)
Tsim = 900.*t0  # duartion of the simulation (= 2.4 ps)
resx = 16.
resy = 2.  # nb of cells in on laser wavelength
rest = resx/0.8  # nb of timesteps in one optical cycle
dt = t0/rest
nx = 300*16  # nb of cells along x-axis
npatchx = 32 # nb of patches along x-axis



Main(
    geometry = "2Dcartesian",
    interpolation_order = 2,
    timestep = dt,
    simulation_time = Tsim,
    cell_length = [l0/resx,l0/resy],
    grid_length = [Lsimx,Lsimy],
    number_of_patches = [32,16],
    clrw = nx/npatchx,
    reference_angular_frequency_SI = 2.0*math.pi*3e8/0.8e-6,
    EM_boundary_conditions = [["silver-muller","silver-muller"],["silver-muller","silver-muller"],],
    solve_poisson = False,
    print_every = 100,
    random_seed = smilei_mpi_rank
    )

    

MovingWindow(
    time_start = 0.9*Main.grid_length[0],
    velocity_x = 0.9997
    )

LoadBalancing(
        initial_balance = False,
    every  = 20,
    cell_load = 1.,

    )

    
Species(
    name = "electron",
    position_initialization = "regular",
    momentum_initialization = "cold",
    particles_per_cell = 4,
    mass = 1.0,
    charge = -1.0,
    number_density = 0.005734,
    mean_velocity = [0.0,0.0,0.0],
    pusher = "boris",
    time_frozen = 0.0,
    boundary_conditions = [["remove","remove"],["remove","remove"],],
    )

FWHMinI = 12.5*l0 #(= 10 mum)
waistinI = FWHMinI/(2.0*math.sqrt(math.log(2.0)))
waistinE = FWHMinI/math.sqrt(2.0*math.log(2.0))
FWHMtinI = 8.0*t0  #(= 21.3 fs)
FWHMtinE = FWHMtinI*math.sqrt(2.0)  

diagEvery = int(37.5*t0/dt) 


LaserGaussian2D(
box_side = "xmin",
a0 = 3.68,  # intensity 2.9 e+19
omega = 1.,
focus = [0.,Main.grid_length[1]/2.],
waist = waistinE,

time_envelope = ttrapezoidal(start=0.,plateau=16.0*FWHMtinE,slope1=2.0*FWHMtinE,slope2=2.0*FWHMtinE)


)
list_fields = ['Ex','Ey','Bz','Rho','Jx']


DiagFields(
every = diagEvery,
fields = list_fields
)

DiagProbe(
    every = diagEvery,
    origin = [0.,Main.grid_length[1]/2.],
    corners = [[Main.grid_length[0],Main.grid_length[1]/2.],
           ],
    number = [nx],
    fields = list_fields
    )

DiagScalar(
    every = int(diagEvery/10),
    vars=['Uelm','Ukin_electron',
          'ExMax','ExMaxCell','EyMax','EyMaxCell','RhoMin',
          'RhoMinCell','Ukin_bnd','Uelm_bnd','Ukin_out_mvw','Ukin_inj_mvw','Uelm_out_mvw','Uelm_inj_mvw','Utot']
    )

DiagParticleBinning(
    deposited_quantity = "weight",
    every = diagEvery,
    species =  ["electron"],
    axes = [
        ["moving_x",0., Lsimx, 300],
        ["ekin",1.,500.,200]
        ]
    )
DiagParticleBinning(
    deposited_quantity = "weight",
    every = diagEvery,
    species =  ["electron"],
    axes = [
        ["moving_x",0., Lsimx, 300],
        ["px",-1.,1.,100]
        ]
    )
DiagParticleBinning(
    deposited_quantity = "weight",
    every = diagEvery,
    species =  ["electron"],
    axes = [
        ["y",0., Lsimy, 300],
        ["py",-1.,1.,100]
        ]
    )

DiagParticleBinning(
    deposited_quantity = "weight",
    every = diagEvery,
    species =  ["electron"],
    axes = [
        ["moving_x",0., Lsimx, 300],
        ["px",-1.,1.,100]
        ]
    )
DiagParticleBinning(
    deposited_quantity = "weight",
    every = diagEvery,
    species =  ["electron"],
    axes = [
        ["y",0., Lsimy, 300],
        ["py",-1.,1.,100]]

        )
DiagPerformances(
    every = diagEvery
    )

**Comment by mccoys** [comment]
You have a problem with the vtk module. Contact your administrator to fix it.

Also update to the latest smilei version

**Comment by Sonuphd** [comment]
Respected Sir,

Thank you for your suggestions.
