### ISSUE TITLE
performance issue in writing Parallel HDF5

### ISSUE THREAD

**Issue by kihangyoun** [SmileiPIC/Smilei#514]
## Description

Hi, there are some kind of performance degradation after writing DiagFields and DiagTrackParticles.
But I don't have any experience of Smilei runtime performance. So one thing I want to ask is, is it normal that performance slows down after model start writing? And it takes a lot of time to write. Is there a way to designate a separate compute node in charge of I/O?

Here is a performance that I checked
steps before writing[0001 ~ 2,192] : 550steps/min
single writing step[2,192]                : 24min/3files(under 100GB)
steps after writing[2,192 ~ 2,466]   : 12steps/min

1. Is it normal for it to take 24 minutes to write a 100GB file?
2. After writing the file, the performance deteriorated (550 steps/min -> 12 steps/min), is this normal?
3. Is there a way to check if it works well with parallel HDF5?

```
DiagFields(
	every = [2192, 7672, 274],
	time_average = 1,
	fields = ["Ex", "Ey", "Ez"],
	subgrid = s_[::2, ::2, ::2]
)

DiagFields(
	every = [2192, 7672, 274],
	time_average = 1,
	fields = ["Rho_e_on", "Rho_p_on", "Rho_C_on", "Rho_e1_on", "Rho_p1_on"],
	subgrid = s_[::2, ::2, ::2]
)

DiagTrackParticles(
	species = "e_on",
	every = [2192, 274],
	flush_every = 548,
	filter = e_filter,
	attributes = ["x","y", "z", "px", "py", "pz", "Ex", "Ey", "Ez", "w"]
)
```

## Module output log

 >  **Reading the simulation parameters**
 HDF5 version 1.10.3
	 Python version 2.7.14
	 Parsing pyinit.py
	 Parsing v-9228ba655
	 Parsing pyprofiles.py
	 Parsing smilei_test_0.py
	 Parsing pycontrol.py
	 Check for function preprocess()
	 python preprocess function does not exist
	 Calling python _smilei_check
	 Calling python _prepare_checkpoint_dir
	 Calling python _keep_python_running() :
	[WARNING] Patches distribution: hilbertian
	[WARNING] simulation_time has been redefined from 175.929189 to 175.915256 to match timestep.
	[WARNING] Particles cluster width set to : 1
 
 >  **Geometry: 3Dcartesian**
	 Interpolation order : 2
	 Maxwell solver : Yee
	 (Time resolution, Total simulation time) : (43.651700, 175.915256)
	 (Total number of iterations,   timestep) : (7679, 0.022909)
	            timestep  = 0.990000 * CFL
	 dimension 0 - (Spatial resolution, Grid length) : (40.743665, 125.663706)
	             - (Number of cells,    Cell length)  : (5120, 0.024544)
	 dimension 1 - (Spatial resolution, Grid length) : (10.19, 150.80)
	             - (Number of cells,    Cell length)  : (1536, 0.10)
	 dimension 2 - (Spatial resolution, Grid length) : (10.19, 150.80)
	             - (Number of cells,    Cell length)  : (1536, 0.10)
 
 >  **Initializing MPI**
	 MPI_THREAD_MULTIPLE enabled
	 Number of MPI process : 7600
	 Number of patches : 
		 dimension 0 - number_of_patches : 64
		 dimension 1 - number_of_patches : 32
		 dimension 2 - number_of_patches : 32
	 Patch size :
		 dimension 0 - n_space : 80 cells.
		 dimension 1 - n_space : 48 cells.
		 dimension 2 - n_space : 48 cells.
	 Dynamic load balancing: never
 
  > **OpenMP**
	 Number of thread per MPI process : 4
 
 >  **Initializing moving window**
	 Moving window is active:
		 velocity_x : 1.00
		 time_start : 125.66
 
  > **Initializing species**
 
	 Creating Species #0: e_on
		 > Pusher: boris
		 > Density profile: 3D user-defined function
	 
	 Creating Species #1: p_on
		 > Pusher: boris
		 > Density profile: 3D user-defined function
	 
	 Creating Species #2: C_on
		 > Pusher: boris
		 > Density profile: 3D user-defined function
	 
	 Creating Species #3: e1_on
		 > Pusher: boris
		 > Density profile: 3D user-defined function
	 
	 Creating Species #4: p1_on
		 > Pusher: boris
		 > Density profile: 3D user-defined function
 

  > **Initializing Patches**
	 First patch created
		 Approximately 10% of patches created
		 Approximately 20% of patches created
		 Approximately 30% of patches created
		 Approximately 40% of patches created
		 Approximately 50% of patches created
		 Approximately 60% of patches created
		 Approximately 70% of patches created
		 Approximately 80% of patches created
	 All patches created
 

 >  **Creating Diagnostics, antennas, and external fields**
	 Diagnostic Fields #0  :
		 Ex Ey Ez 
	 Diagnostic Fields #1  :
		 Rho_e_on Rho_p_on Rho_C_on Rho_e1_on Rho_p1_on 
	 Created TrackParticles #0: species e_on
		 id,x,y,z,px,py,pz,Ex,Ey,Ez,w
 

  > **finalize MPI**
	 Done creating diagnostics, antennas, and external fields
 

  > **Minimum memory consumption (does not include all temporary buffers)**
              Particles: Master 0 MB;   Max 1569 MB;   Global 1.99e+03 GB
                 Fields: Master 295 MB;   Max 295 MB;   Global 2.1e+03 GB
            scalars.txt: Master 0 MB;   Max 0 MB;   Global 0 GB
             Fields0.h5: Master 0 MB;   Max 0 MB;   Global 0 GB
             Fields1.h5: Master 0 MB;   Max 0 MB;   Global 0 GB
            TrackParticlesDisordered_e_on.h5: Master 0 MB;   Max 0 MB;   Global 0 GB

 > **Species creation summary**
		 Species 0 (e_on) created with 4831838208 particles
		 Species 1 (p_on) created with 2415919104 particles
		 Species 2 (C_on) created with 2415919104 particles
		 Species 3 (e1_on) created with 13287555072 particles
		 Species 4 (p1_on) created with 13287555072 particles
 

 **Expected disk usage (approximate)**
	 WARNING: disk usage by non-uniform particles maybe strongly underestimated,
	    especially when particles are created at runtime (ionization, pair generation, etc.)
	 
	 Expected disk usage for diagnostics:
		 File Fields0.h5: 197.02 G
		 File Fields1.h5: 328.37 G
		 File TrackParticlesDisordered_e_on.h5: 6.23 T
		 File scalars.txt: 0 bytes
	 Total disk usage for diagnostics: 6.74 T
	 
 

 **Keeping or closing the python runtime environment**
	 Checking for cleanup() function:
	 python cleanup function does not exist
	 Keeping Python interpreter alive

## Parameters

- Smilei version: v4.6
- Computing resources
  - type of computer: cluster
  - OS: CentOS 8.3.2011
  - C++ compiler: Intel icpc 2021.3.0
  - MPI version: OpenMPI 4.1.1
  - HDF5 version: 1.10.3
  - Python version: 2.7.14

**Comment by mccoys** [comment]
Slow writing of the fields diag is a known issue.  Please use the probe diag instead. The tracked particle diag should not be an issue, but it will have an impact as is it very large. If possible, it is recommended to use ParticleBinning

**Comment by kihangyoun** [comment]
Thank you for your quick reply, @mccoys !
Also, in my opinion, when the size of the file being written is compared to the estimated value, it is much larger in the middle of the model execution, giving the impression that the processes are writing in duplicate. 
If it is a known issue, is there any way to alleviate it? (Reduce the number of processes, change the phdf5 version, etc.) 
Because I am in a situation where I must use those functions.

**Comment by mccoys** [comment]
Are you referring to track diags? There should not be duplicates so I am surprised if the extra size.  It is possible that the hdf5 library reserves some space in advance,  but we cannot control this aspect

**Comment by kihangyoun** [comment]
@mccoys,
Since I must use those functions(DiagFields, DiagTrackParticles), I want to find out any workaround or something to improve I/O performance any better if it exist. Please let me know if you have any advice on this.

**Comment by mccoys** [comment]
Why not use probes instead of fields ?

**Comment by mccoys** [comment]
Probes are much faster than Field. They are of a slightly different nature, as Probes make some interpolation of the fields, whereas Field does not. The difference is very small.

ParticleBinning is a completely different approach than TrackParticles. Instead of saving all the data from all particles (which is a huge amount), ParticleBinning produce distribution function of the plasma based on the particle data. They can be much faster of course, but you will not have individual particle data

**Comment by mccoys** [comment]
Please reopen if still needed
