### ISSUE TITLE
Why the number density stored in ParticleBinningx.h5 file is different from that shown by happi

### ISSUE THREAD

**Issue by Goo-JZhang** [SmileiPIC/Smilei#520]
As the title

**Comment by mccoys** [comment]
In the documentation, it is explained that happi does some treatment to convert, for example, from weights to density

**Comment by Goo-JZhang** [comment]
> In the documentation, it is explained that happi does some treatment to convert, for example, from weights to density

Could you figure out in which part of the documentation the related content are or just the ratio between the stored data and shown data?

**Comment by mccoys** [comment]
https://smileipic.github.io/Smilei/post-processing.html#open-a-particlebinning-diagnostic

See the point "units of the results"

> The raw quantity stored in the output file has the units of the [deposited_quantity](https://smileipic.github.io/Smilei/namelist.html#id48). Generally, this is a sum of [macro-particle weights](https://smileipic.github.io/Smilei/units.html#weights). As those weights are not in units of density (but of density multiplied by hypervolume), a correction is applied in happi: it divides the data by an hypervolume. More precisely, for each direction x, y or z, if this direction is not included in one of the diagnostic’s axes, happi divides by the length of the box in that direction.
> In addition, in order to make the units relative to the bin size, happi divides the data in each bin by the bin size.
