### ISSUE TITLE
How can I know the temperature distribution of the species in the simulation, deposited quantity listed does not contain the temperature

### ISSUE THREAD

**Issue by Goo-JZhang** [SmileiPIC/Smilei#523]
as the title

**Comment by mccoys** [comment]
You must choose your definition of temperature.  If it is the average kinetic energy, simply calculate that. If you choose the width of the momentum distribution,  get the momentum distribution

Please do not use this website for general information. This is only for bugs or issues

**Comment by mccoys** [comment]
Let me add that there is a chat room for this kind of questions
