### ISSUE TITLE
make error during smilei upgrade

### ISSUE THREAD

**Issue by areive** [SmileiPIC/Smilei#524]
Hello,

I tried to upgrade smilei and during make I got this error in compiling src/Merging/Merging/VranicSpherical.cpp:

veraw69-249:smilei aliciareijavecino$ brew upgrade --fetch-HEAD smilei
==> Upgrading 1 outdated package:
iltommi/brews/smilei HEAD-4230c58 -> HEAD-76a9f1c
==> Cloning https://github.com/SmileiPIC/Smilei.git
Updating /Users/aliciareijavecino/Library/Caches/Homebrew/smilei--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 76a9f1c3e Update install_macos.rst
==> Upgrading iltommi/brews/smilei
  HEAD-4230c58 -> HEAD-76a9f1c 

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 12.4.

==> make
Last 15 lines from /Users/aliciareijavecino/Library/Logs/Homebrew/smilei/01.make:
Compiling src/Ionization/IonizationFromRate.cpp
Compiling src/Merging/Merging.cpp
Compiling src/Merging/MergingVranicSpherical.cpp
Compiling src/Merging/MergingVranicCartesian.cpp
src/Merging/MergingVranicSpherical.cpp: In member function 'virtual void MergingVranicSpherical::operator()(double, Particles&, std::vector<int>&, SmileiMPI*, int, int, int&)':
**src/Merging/MergingVranicSpherical.cpp:94:53: error: 'aligned_alloc' was not declared in this scope
   94 |         unsigned int  * theta_dim = (unsigned int*) aligned_alloc(64, phi_dim*sizeof(unsigned int));
      |                                                     ^~~~~~~~~~~~~**
src/Merging/MergingVranicCartesian.cpp: In member function 'virtual void MergingVranicCartesian::operator()(double, Particles&, std::vector<int>&, SmileiMPI*, int, int, int&)':
src/Merging/MergingVranicCartesian.cpp:161:63: error: 'aligned_alloc' was not declared in this scope
  161 |         unsigned int  * momentum_cell_index = (unsigned int*) aligned_alloc(64, number_of_particles*sizeof(unsigned int));
      |                                                               ^~~~~~~~~~~~~
make: *** [build/src/Merging/MergingVranicSpherical.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [build/src/Merging/MergingVranicCartesian.o] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/iltommi/homebrew-brews/issues

Error: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 12.4.

==> Running `brew cleanup smilei`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

veraw69-249:smilei aliciareijavecino$ 

Hope you can help me, find attached some outputs.

Alicia
[echo_library_path.txt](https://github.com/SmileiPIC/Smilei/files/8371049/echo_library_path.txt)
[gitdescribe.txt](https://github.com/SmileiPIC/Smilei/files/8371050/gitdescribe.txt)
[make_env.txt](https://github.com/SmileiPIC/Smilei/files/8371051/make_env.txt)
[python_sysconfig.txt](https://github.com/SmileiPIC/Smilei/files/8371052/python_sysconfig.txt)
[make_config_verbose.txt](https://github.com/SmileiPIC/Smilei/files/8371053/make_config_verbose.txt)
[ldd smilei.txt](https://github.com/SmileiPIC/Smilei/files/8371054/ldd.smilei.txt)

**Comment by iltommi** [comment]
Hi Alicia, 
we've had another report of such behaviour on certain mac. 

A first thing to do is to upgrade the command line tools via:
`sudo xcode-select --install`

Another fix, if the above command does not solve the problem, would be to change the Makefile by replacing the `std=c++11` with `std=c++17` everywhere.
This seems to fix the problem.

I'm not sure it's a Smilei problem (https://en.cppreference.com/w/c/memory/aligned_alloc was available in standard c++11) vs. Apple command line tools packaging. That's why we did not change the Smilei sources. 

Hope it helps
