### ISSUE TITLE
Can the implicit PIC techniques be imported?

### ISSUE THREAD

**Issue by xiaowang119** [SmileiPIC/Smilei#525]
## The problem and the context

I cannot simulate my project due to a large space and time scale.

## Failed attempts

I have tried some scaling laws but they didn't give a physically reasonable result.

**Comment by beck-llr** [comment]
Hi

Technically it could. But it is a huge amount of work. Fully or even semi implicit solvers are quite different from the explicit one and require a different approach to the PIC loop (as far as I know). Unfortunately we don't have the manpower to work on this at the moment.
