### ISSUE TITLE
Probe bug in smilei_test

### ISSUE THREAD

**Issue by HaoPengYY** [SmileiPIC/Smilei#528]
Dear Developers,
Hi! 
I was trying to do a simulation with SMILEI, please find the input script attached.  But as I run the test mode with `smilei_test input.py`. It keeps complaining `Probe has no points in the box` as you can see in the attached log file. But when I run without the test mode, i.e.  run the script on the cluster, nothing happens, the simulation goes well.
[logfile.txt](https://github.com/SmileiPIC/Smilei/files/8504580/logfile.txt)

**Comment by mccoys** [comment]
Thank you for spotting the bug. We will fix it soon

**Comment by mccoys** [comment]
It turns out I cannot reproduce the issue. Could you post an example ?
