### ISSUE TITLE
phase within laser time envelope 

### ISSUE THREAD

**Issue by balcon13** [SmileiPIC/Smilei#531]
Hi, 

I was just wondering if it was possible to define temporal phase for a 2D/3D/AM Gaussian laser pulse within the argument for the time envelope. I am going to be attempting to simulate a laser wakefield (where the driving laser has very short pulses) and so phase is going to become important! Ideally I would want to use a gaussian temporal profile but I can't find anything about phase in the documentation. 

I am new to Smilei (and fairly new to coding full stop!) so can often find the coding 'language' within documentation a little confusing so it is very possible that I have missed something. Apologies if this is the case! 

Many thanks in advance.

**Comment by beck-llr** [comment]
Hi,
and welcome to the Smilei users community. `LaserGaussian2D` and other Gaussian lasers are just convenient wrappers of the generic `Laser` block definition with pre-defined profiles. You can have full control on all parameters of your laser profiles if you use the basic `Laser` block instead.
You can either define a `space_time_profile` or independent `space`, `time` and `phase` profiles. It is al in the documentation: https://smileipic.github.io/Smilei/namelist.html#lasers

**Comment by balcon13** [comment]
Thanks very much for your help ! I had not realised that this was the case.
