### ISSUE TITLE
PML boundary conditions

### ISSUE THREAD

**Issue by Tissot11** [SmileiPIC/Smilei#534]
Quick questions on the `PML` boundary conditions in v4.7

1. Are PML boundary conditions supported in 1D geometry? When I ran a 1D simulation it crashed complaining unknown boundary condition `PML`.
2. In the documentation, it is written that in order to use `PML` boundary conditions, all `EM_boundary_conditions` must be `PML`. What you mean that also `boundary_conditions` must be `remove` but not `periodic`?

**Comment by beck-llr** [comment]
Hi 
1. PML are not supported in 1D.
2. What we mean is that all boundaries of the simulation domain need to be PML. You can not combine PML on the Ymin and Ymax axis with periodic in the Xmin and Xmax axis for instance.

We are still working on PML and trying to improve their integration with the rest of the code. If you encounter problems could you please describe them with more details ? For instance include your namelist and the output given by the code. Thanks for the feedback !

**Comment by Tissot11** [comment]
Thanks for your answer. I was a bit confused about the particle `boundary_conditions` being `PML`. 

Anyway, I attach a reduced Namelist for the crashed simulation using `PML` boundary conditions on a supercomputer. Same simulation also crash on a local cluster. I attach both err files for the same simulation here 

[Namelist.txt](https://github.com/SmileiPIC/Smilei/files/8730492/Namelist.txt)
[tjob_hybrid.err.5480290.txt](https://github.com/SmileiPIC/Smilei/files/8730495/tjob_hybrid.err.5480290.txt)
[stderr.907440.txt](https://github.com/SmileiPIC/Smilei/files/8730517/stderr.907440.txt)

**Comment by beck-llr** [comment]
In some corner cases PML might fail when associated to dynamic load balancing. We have a fix for that but it has not been pushed yet.
In the meantime, you can disable dynamic load balancing in order to test the PMLs.

**Comment by beck-llr** [comment]
The correction should be available now.
