### ISSUE TITLE
Simulations with 1e10 particles crash

### ISSUE THREAD

**Issue by smontefiori** [SmileiPIC/Smilei#535]
Dear developers,
hi! I needed some statistics to test something I was working on, and hence I launched a simulation in which 1e10 electrons were evolving in a magnetic fields (with the radiation reaction modules turned on). However, despite everything seems to be properly initialized, the simulation crashes before completeing the first timestep. Thus I tried to simplify the namelist: I removed the magnetic fields and the radiation reaction modules, leaving the electrons only (the namelist is the one attached hereunder)

[namelist_test.txt](https://github.com/SmileiPIC/Smilei/files/8686091/namelist_test.txt)

but the same issue appears (I here attach the standard output and error files (but they don't really say much)).

[stderr.txt](https://github.com/SmileiPIC/Smilei/files/8686112/stderr.txt)
[stdout.txt](https://github.com/SmileiPIC/Smilei/files/8686113/stdout.txt)

Thus I tried to reduce the number of particles (which translates into a pretty straightforward modification of the `particles_per_cell` argument in the `Species` function) to a total of 5e9 and then 7.5e9 electrons in the entire simulation box, but in these cases everything worked just fine. Apparently, the problem comes when N_e (number of electrons) > 1e10.

Do you happen to know what may cause this? In principle we thought it was due to the fact that 1e10 exceeds the unsigned int maximum, but this same consideration holds for 5e9 and 7.5e9 as well, therefore this seems not to be the case.
I'm sorry I don't have further evidence of this, but to be honest I don't really know what other tests could be helpful. So please, if you want me to run some simulation just ask, I'm happy to help.
Of course, it is also possible I'm doing something illegal (that is not expected by smilei).

Thank you so much for your time.
Sam.

**Comment by mccoys** [comment]
It is likely a lack of memory. Each particles owns at least 10 scalar quantities, with each being on 8 bytes. This is without counting fields. Overall you need at the very least 1TB of total memory. With 70 processes each owning 14 cores, assuming 2GB per core, you should have a bit more, but there are situations when memory exceeds the limit locally due to copies of data.

**Comment by beck-llr** [comment]
Hi Sam !
You can try to lower the number of particles just to get the simulation running and use the "Performance" diagnostics to check the memory occupation of each of your MPI processes. If it is dangerously close to your maximum memory it is likely to be the source of your problem.

**Comment by beck-llr** [comment]
For the record I was able to run the namelist you provided successfully on 6 compute nodes with 192 GB of memory on each node, using 12 MPI processes (2 per node) and 24 openMP threads per MPI.

**Comment by smontefiori** [comment]
Uh nice! Thank you all for your feedbacks! Indeed, I was now trying to simulate the namelist by further extending the memory reserved to the simulation. When it finishes I will close the issue (I may have further questions).
For the moment: thank you for your time and patience!
Sam.
