### ISSUE TITLE
TrackParticles postprocessing crashes

### ISSUE THREAD

**Issue by noreasonatall1** [SmileiPIC/Smilei#539]
Dear Smilei developers,

I'm having issues with TrackParticles diagnostic, that maybe you are able to help with. I'm running the 2D simulation with ionization and want to track the particles. As ionization is on, I have no prior knowledge which particles will be accelerated effectively, and therefore need to save large quantities of data. As far as I understood the provided documentation on particle IDs + resolved Git issues, this is the only way to track particles at every step when ionization is on. 
Am I correct?

Regardless, when doing the simulation, I declare the diagnostic:
```
def myfilter(particles):
    if Main.iteration<150.*32.:
        return (particles.y>30*l0)*(particles.y<50.*l0)
    else:
        return particles.px > 2.

DiagTrackParticles(
    species = "electron",
    every = rest/8,
    filter = myfilter,
    attributes = ["x", "y","px", "py", "Ex", "Ey", "Bz"]
)
```
Simulation runs correctly, and I'm able to produce `TrackParticles_electron.h5` file. Some tracks there are ragged, as some of the particles do not suffice `particles.px > 2.` at every step, which is fine. Hovewer, I wanted to look at (mostly) full trajectories, i.e. electrons that satisfy `myfilter` at every time step after some point. Therefore, at postprocessing I add:
`Diag1=S.TrackParticles("electron",select="all((t>2000.), x>0.)")` and run into following error:
```
 Selecting block `all((t>2000.), x>0.)`, at time 8320
   Selecting block `all((t>2000.), x>0.)`, at time 2004
Traceback (most recent call last):
  File "3d_fft_Bz_filtration.py", line 432, in <module>
    Diag1=S.TrackParticles("electron",select="all((t>2000.), x>0.)")
  File "/home/solver/raidDisk/opt/Smilei/scripts/../happi/_Factories.py", line 570, in __call__
    return TrackParticles(self._simulation, *args, **kwargs)
  File "/home/solver/raidDisk/opt/Smilei/scripts/../happi/_Diagnostics/Diagnostic.py", line 71, in __init__
    remaining_kwargs = self._init(*args, **kwargs)
  File "/home/solver/raidDisk/opt/Smilei/scripts/../happi/_Diagnostics/TrackParticles.py", line 154, in _init
    self.selectedParticles = self._selectParticles( select, True, chunksize )
  File "/home/solver/raidDisk/opt/Smilei/scripts/../happi/_Diagnostics/TrackParticles.py", line 363, in _selectParticles
    elif seltype[k] == "all(": selection *= selectionAtTimeT * existing
ValueError: operands could not be broadcast together with shapes (13749962,) (13749961,) (13749962,)
```
When I change it to something like `Diag1=S.TrackParticles("electron",select="any((t>2000.), x>0.)")`, i.e. less strict requirements, everything works well. But from this it can be seen, that particles satisfying `Diag1=S.TrackParticles("electron",select="all((t>2000.), x>0.)")` actually exist. 
I also tried different selections like `Diag1=S.TrackParticles("electron",select="all((t>7000.)*(t<7500.), x>0.)")` with the same error. 

Could you please help me with this?

**Comment by mccoys** [comment]
This happens when bumpy does not have enough memory. Try to select particles directly during the sorting phase in the keyword `sort`

**Comment by noreasonatall1** [comment]
Thank's for the quick response! I'm running Debian 9.13 and it had Python 3.5 on it. Smilei runs on this combination with no issues, so I wasn't expecting it.  Manually installing Python 3.9 + Numpy 1.22.4 helped, now it gets through the sorting process. But still crashes later: 
```
    Ordering @ timestep = 3936
Error in the ordering of the tracked particles
integer division or modulo by zero
Traceback (most recent call last):
  File "/home/solver/raidDisk/opt/20_05_22_ni_11_a0_1_5_tracks/3d_fft_Bz_filtration.py", line 297, in <module>
    Diag1=S.TrackParticles("electron",sort="all((t>7000)*(t<7200), x>0)",sorted_as="new_tracks")
  File "/home/solver/raidDisk/opt/Smilei/scripts/../happi/_Factories.py", line 570, in __call__
    return TrackParticles(self._simulation, *args, **kwargs)
  File "/home/solver/raidDisk/opt/Smilei/scripts/../happi/_Diagnostics/Diagnostic.py", line 71, in __init__
    remaining_kwargs = self._init(*args, **kwargs)
  File "/home/solver/raidDisk/opt/Smilei/scripts/../happi/_Diagnostics/TrackParticles.py", line 103, in _init
    self._orderFiles(orderedfile, chunksize, sort)
  File "/home/solver/raidDisk/opt/Smilei/scripts/../happi/_Diagnostics/TrackParticles.py", line 528, in _orderFiles
    for first_o, last_o, npart_o in ChunkedRange(nparticles_to_write, chunksize):
  File "/home/solver/raidDisk/opt/Smilei/scripts/../happi/_Utils.py", line 71, in __init__
    self.adjustedchunksize = int( (size-1) // self.nchunks + 1 )
ZeroDivisionError: integer division or modulo by zero

```

**Comment by mccoys** [comment]
Does it work at earlier timesteps?

**Comment by mccoys** [comment]
Ahhh there is a bug in happi when there are no particles. Will fix it asap

**Comment by mccoys** [comment]
Could you try replacing the following line 
```
self.nchunks = int( (size-1) // int(chunksize) + 1 )
```
in _Utils.py by
```
self.nchunks = int( max(1,size-1) // int(chunksize) + 1 )
```
Then restart python and try again. You might need to delete the ordered file, but not the disordered one.

**Comment by noreasonatall1** [comment]
I replaced the line and the process succesfully finished - thanks! 
Hovewer, it doesn't seem to find particles correctly? When I white something like `Diag1=S.TrackParticles("electron",sort="all((t>7000)*(t<7200), x>0)",sorted_as="new_tracks")` it ends with `No particles found`. But if I replace `all` with `any` and look into the results, there are definitely particles that satisfy the `all` statement.

**Comment by mccoys** [comment]
Are you sure those particles are always the same? For all timesteps?

**Comment by noreasonatall1** [comment]
What do you mean "the same"?
I'm trying to get only the particles that were tracked at all specified timesteps (hence the `x>0` as it is always `True` if the particle was tracked) and the result is that they are none. But when I'm sorting the particles, that were tracked at least at one of the specified timesteps, inside this array excist several (like several dozens) of particles, that were tracked for all of the needed timesteps. 
I'm looking at the arrays using `.getData()` and saving them. I believe there should be no mismatch in IDs?

**Comment by mccoys** [comment]
I can imagine that particles appear then disappear so that they do not pass the `all`.

With getData there should be no ID mismatch
