### ISSUE TITLE
understanding memory diag, and using PML

### ISSUE THREAD

**Issue by ccaizergues** [SmileiPIC/Smilei#540]
Hi guys,

I am trying to run laser-target simulations but there seems to be reported some memory or communication issues for some cases, particularly, with my larger box cases (with more procs allocated).

Yet, Performance diag « memory_total » maps report low values (e.g. ~6Go/mpi with 16threads/mpi) in comparison to irene rome available RAM. From using Checkpoints with comparable simulations I estimate that the size of the dump directory should be less than 150Go.

I have copied two corresponding runs onto ‘/ccc/scratch/cont003/smilei/caizecle’

repository. S80thread16  uses 16 openmp threads
repository : S80 does not uses openmp

The threaded case seems more comfortable with the memory but fails first (I feel reported memory maps at t=0 do not seem in agreement between the two simulations).

I also would like to test the PML conditions, but even on reduced cases I can’t have the simulations run, unless removing all particle species. The same case with silver-muller conditions works well.

I have also added the corresponding repositories :  test_PML, test_PML_noparticles, test_PML_silvermuller

thanks

**Comment by beck-llr** [comment]
Hi
Could you specify where you see an error message about memory or communication ? I don't see any in S80 or S80thread16 directories. From what I see the problem is simply that Smilei is not even executed for some reasons.

**Comment by beck-llr** [comment]
About PML, I am currently running your namelist on 4 Irene KNL nodes (I do not have time on Rome unfortunately) and I'm up to 400 iterations. What do you mean exactly by you "can't have the simumations run" ?

If you want, you can check the result in `/ccc/scratch/cont003/smilei/beckarna/test_PML`.

**Comment by beck-llr** [comment]
It is possible you have to update your version of Smilei.

**Comment by ccaizergues** [comment]
Hi,

For the PML, it is not clear to me where/what might be the source of the bug, good news if it works on knl (but I have no hours to do these jobs on knl). From the patch_load file, in fact, the case test_PML seems to run till the first patch redistribution. At the end of checkpoint000/out file error is ```mm_posix.c:195  UCX  ERROR open(file_name=/proc/143344/fd/27 flags=0x0) failed: Permission denied``` and ```heap``` issue appears in the checkpoint000/err files.

For the larger cases, S80thread16 runs till 28600/654516 with ```failed: Cannot allocate memory``` at the end of the checkpoint000/out file.
The S80 case runs till 41900/654516 without message at the end of checkpoint000/out file but with some in checkpoint000/err file
```
slurmstepd-irene4460: error: Detected 1 oom-kill event(s) in StepId=5622874.0 cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
srun: error: irene4460: task 960: Out Of Memory
```
The Smilei version used is from may 13th, so quite recent, some bug have been fixed since ?

**Comment by mccoys** [comment]
The error seems clear. You do not have permissions to write in the given folder, or the file is already in use by another program.

Out of memory is clear as well !

**Comment by ccaizergues** [comment]
Only Smilei program is running for these cases (plus python interpreter alive, maybe), this is the same for the 3 test cases, only the case with PML fails.

For the out of memory cases, I do not see how to understand/read/anticipate it from the memory diag.
If reported numbers are reliable/correct the 16threads case is far from the 16*1.8G limit on rome, while for the 1thread/mpi case we already have some mpi with 3Go at t=0 (>1.8Go) then ~7Go at fail time.

**Comment by beck-llr** [comment]
> From the patch_load file, in fact, the case test_PML seems to run till the first patch redistribution.

Ok we have a fix for that but it has not been pushed yet on the master branch. In the meantime you can disable dynamic load balancing and it should work.

**Comment by ccaizergues** [comment]
Indeed, the PML bug seems related to the dynamic patch option. Please forward when fix will be available.

For the out of memory issue, I also tried with MultipleDecomposition bloc, that case fails at 24100/654516. For the three cases, last reported memory map reports peak value close to 7Go. This may have something to do with material, but rome is supposed to have physically 1.8Go per process (while documentation tells 4Go allocated by default).

**Comment by beck-llr** [comment]
About your memory issue on Rome, you should ask this kind of question to TGCC but here is what I understand.

A Rome node has 256 GB of memory. There are 128 cores per node so this gives an average of 2 GB of memory per core. For safety reasons you reserve a part of the memory for the system which brings this number down to 1.8 GB per core in average (so 128*1.8 = 230.4 GB total).

If there was no NUMA consideration, you should be able to have a single MPI process using the whole 230.4 GB. But because of NUMA, all cores can not access the whole memory. I think there are 4 NUMA domains per processor so 8 per node. That brings us to 28.8 GB per NUMA domain (230.4/8). If the sum of the memory needed by all MPI processes running on a single NUMA domain exceeds this value, you will probably run OOM.

Now the reason why your case with threads runs OOM earlier than the other one is unclear and probably related to how you submit your simulation and position your MPI processes. Maybe they are more evenly spread out when you use a single openMP thread and make a better use of all the NUMA domains.

**Comment by beck-llr** [comment]
The correction of dynamic load balancing when using PML has finally been pushed. Sorry for the long delay.
