### ISSUE TITLE
Particle injector with one patch

### ISSUE THREAD

**Issue by VadimRomansky** [SmileiPIC/Smilei#542]
## Description

Explain your issue here.

Particle injectors don't work on xmax boundary if there is only one patch in x direction
```

**Comment by VadimRomansky** [comment]
And one more strange thing - in 2d case, if use random position, it is ok, but with regular - something wron
![random](https://user-images.githubusercontent.com/11965116/172422107-902ddab6-170d-4101-84e2-72b019273979.png)
![regular](https://user-images.githubusercontent.com/11965116/172422123-da1dd727-4d73-4540-8378-98e6325378c4.png)
g

**Comment by VadimRomansky** [comment]
@mccoys did you managed to reproduce?

**Comment by mccoys** [comment]
This is now fixed
