### ISSUE TITLE
extend electric field and increase  numerical noise

### ISSUE THREAD

**Issue by m-rezaei-p** [SmileiPIC/Smilei#543]
## Description

I simulated LWFA in 2D and everything is OK because I want to simulate the near-real case I switch to AMcylindrical geometry.
every parameter is the same just I change some parameters that mention in the manual but I saw some numerical noise when the pulse propagate to plasma. and extent laser field in r direction.....
So my question how can I solve this issue?
```
this is  my log file :
log file:
[log_file.txt](https://github.com/SmileiPIC/Smilei/files/8885934/log_file.txt)



```
in the following you can see different three time of Er:
initial steps:

![1](https://user-images.githubusercontent.com/58806777/173236263-f865668f-1b36-4946-90ca-95c453415929.png)

middle of simulation:
 
![2](https://user-images.githubusercontent.com/58806777/173236301-7a5e7a0e-8822-4218-a5fe-acca1bf55040.png)

near the end of simulation:
![3](https://user-images.githubusercontent.com/58806777/173236341-a1212e80-bb0b-4712-872f-6f0f29bce551.png)

## Steps to reproduce the problem

I tried to decrease size in r direction and increase number of particle in theta direction but it is not useful ....
## Parameters

- Smilei version ?
- Version : 7bfd1d8-master
- Input file ?
- 
[Pure_gas_Radiation.txt](https://github.com/SmileiPIC/Smilei/files/8885946/Pure_gas_Radiation.txt)

- Commands or script used to run the faulty simulation ?
- Computing resources
  - type of computer
  - cluster
  - OS
  - C++ compiler (to get some information `g++ --version`)
  - g++ (GCC) 8.3.0

  - MPI version (`mpic++ --version`, `mpic++ -show`)
  - g++ (GCC) 8.3.0
  - HDF5 version (`h5cc --version`)
  -  HDF5 version 1.12.1

  - Python version (`python --version`)
  -  Python version 3.6.8

  - ...

**Comment by massim0-1** [comment]
Hi, in your second and third figure the laser has already touched the border, generating reflections.
To avoid this, you should increase the window size along the r direction or use a Perfectly Matched Layer.
