### ISSUE TITLE
Smilei Returns  negative value for Urad

### ISSUE THREAD

**Issue by m-rezaei-p** [SmileiPIC/Smilei#544]
## Description

I tried simulation LWFA and see some radiation in the AMcylindrical geometry. but when I radiation part I see some negative value...

this is  my log file :
log file:
[log_file.txt](https://github.com/SmileiPIC/Smilei/files/8885934/log_file.txt)

scalar plot for Urad:
![Urad](https://user-images.githubusercontent.com/58806777/173236624-ab4876e8-66d8-40ab-8e3f-2b9f9466ddef.png)

for total energy:
![Utot](https://user-images.githubusercontent.com/58806777/173236636-70220c43-539b-4d4d-a8ab-ab1dec902fff.png)

for Total kinetic energy:
![Ukin](https://user-images.githubusercontent.com/58806777/173236662-872420e9-13c8-4eec-9dda-b0c8b7475233.png)

## Steps to reproduce the problem

I use this parameter for radiation:
**in the species:** 
radiation_model = "Landau-Lifshitz",
**in RadiationReaction:**
RadiationReaction(
    minimum_chi_continuous = 1e-5,

)

## Parameters

- Smilei version ?
- Version : 7bfd1d8-master
- Input file ?
- 
[Pure_gas_Radiation.txt](https://github.com/SmileiPIC/Smilei/files/8885946/Pure_gas_Radiation.txt)

- Commands or script used to run the faulty simulation ?
- Computing resources
  - type of computer
  - cluster
  - OS
  - C++ compiler (to get some information `g++ --version`)
  - g++ (GCC) 8.3.0

  - MPI version (`mpic++ --version`, `mpic++ -show`)
  - g++ (GCC) 8.3.0
  - HDF5 version (`h5cc --version`)
  -  HDF5 version 1.12.1

  - Python version (`python --version`)
  -  Python version 3.6.8

  - ...

**Comment by mccoys** [comment]
In fact your particles are way too slow. They shouldn't radiate at all, but they are wrongly accounted for due to the parameter `minimum_chi_continuous` that you set too low, and the model diverges for these slow particles. I will push a fix that prevents slow particles to be accounted for. You will then see Urad = 0

**Comment by m-rezaei-p** [comment]
> In fact your particles are way too slow. They shouldn't radiate at all, but they are wrongly accounted for due to the parameter `minimum_chi_continuous` that you set too low, and the model diverges for these slow particles. I will push a fix that prevents slow particles to be accounted for. You will then see Urad = 0

Dear @mccoys  
thanks so much for take time,
I saw this paper : 
https://aip.scitation.org/doi/pdf/10.1063/5.0070670
they calculated THZ with a0=1 and I think for THZ and a0=1 ,minimum_chi_continuous must be too low...


I checked for two cases with same parameters:
case1: LWFA from pure plasma
case2: LWFA from pure Gas(He+3%N2)
for case 1 I see positive Urad and for case 2 I see negative Urad

so do you think this results from a **numerical errors** or it is true?
this part is so important for me to how distinguishes wrong data... 

what do you think about this paper?
 https://aip.scitation.org/doi/pdf/10.1063/5.0070670
because I would like follow some parts of this paper....

thanks in advance

**Comment by mccoys** [comment]
The radiation module is exclusively focused on high-energy particles. Typically gamma > 2. THz radiation is not included.

**Comment by m-rezaei-p** [comment]
> The radiation module is exclusively focused on high-energy particles. Typically gamma > 2. THz radiation is not included.
> 
> For low gamma, the results will be completely wrong.

I am a little confuse: I have 3 questions:
1. that means for gamma>2(gamma of particle) , Can  I say the results is right?
2. You mention **"THz radiation is not included."** that is mean : the results of this paper are wrong?

**Comment by mccoys** [comment]
1. If gamma of the particle > 2, then the radiation module is correct.
2. The paper is correct. It does not use the radiation module. As far as I understand, the THz radiation is visible on the grid as EM waves. It does not need to be produced by an external module.

**Comment by m-rezaei-p** [comment]
> 1. If gamma of the particle > 2, then the radiation module is correct.
> 2. The paper is correct. It does not use the radiation module. As far as I understand, the THz radiation is visible on the grid as EM waves. It does not need to be produced by an external module.

Sorry I think I use wrong words, I say radiation module  means:
```
in the species:
radiation_model = "Landau-Lifshitz",
in RadiationReaction:
RadiationReaction(
minimum_chi_continuous = 1e-5,

)
```
So I think, they active this , By the way I will check it...

**So for some  fix about slow particle, when can I get update code?**
Because I must comparing some radiation and this is my first step... form pure gas

thanks for advance

**Comment by mccoys** [comment]
The radiation module is indeed what you mention. But I think they don't use it. You can see the THz radiation on their graphs. So it is NOT from this module.

The fix will come soon. You can still use minimum_chi_continuous = 1e-3. It does almost the same.

**Comment by mccoys** [comment]
Fix done
