### ISSUE TITLE
Errors with TrackParticles.animate() and TrackParticles.toVTK()

### ISSUE THREAD

**Issue by whh467** [SmileiPIC/Smilei#55]
Greetings,

I have been trying out the various Happi diagnostics, and I am receiving errors with TrackParticles.animate() and TrackParticles.toVTK(). I am uncertain what is causing these issues. Other diagnostics such as Field.animate() and Field.toVTK() seem to work perfect. 

I've been trying these diagnostics with a (slightly modified) copy of "tst3d_1_thermal_plasma.py" from the benchmarks folder:

[tst3d_1_thermal_plasma.txt](https://github.com/SmileiPIC/Smilei/files/2161264/tst3d_1_thermal_plasma.txt)

Here is the Happi file used for TrackParticles.animate():
[happi_thermalplasma_animate.txt](https://github.com/SmileiPIC/Smilei/files/2161268/happi_thermalplasma_animate.txt)

This is the output for TrackParticles.animate():
[animate_error.txt](https://github.com/SmileiPIC/Smilei/files/2161270/animate_error.txt)

A completely blank Matplotlib window appears, but never loads any data.  The program seems to freeze at timestep=0. Furthermore, my laptop slows down considerably. It is possible that there is too much data for my computer to handle (although I have let the program run for quite some time without a change in the result.) I have tried adjusting the variable "n0" in "tst3d_1_thermal_plasma.py", but I still see an output indicating that species 'proton' contains 140608 particles (the same value as before). 

The Happi code for TrackParticles.toVTK() is the following:
[happi_thermalplasma_toVTK.txt](https://github.com/SmileiPIC/Smilei/files/2161271/happi_thermalplasma_toVTK.txt)

And the error is:
[toVTK_error.txt](https://github.com/SmileiPIC/Smilei/files/2161272/toVTK_error.txt)

Essentially, toVTK() does not recognize 'rendering':

    TypeError: toVTK() got an unexpected keyword argument 'rendering'

Any help would be greatly appreciated.

Best regards,

Will

**Comment by mccoys** [comment]
We actually just release [v3.4](https://github.com/SmileiPIC/Smilei/releases/tag/v3.4) !

**Comment by whh467** [comment]
These solutions have worked. Thank you very much.
