### ISSUE TITLE
Laser polarization

### ISSUE THREAD

**Issue by balcon13** [SmileiPIC/Smilei#552]
Hi,

In the laser documentation, there is a comment which states that the default polarization is linear along the y direction. I understand that you are able to change the polarization from linear to circularly polarized using the ellipticity = 0, +/-1 argument, but is there an argument which would allow me to linearly polarize my laser out of the simulation plane?

Thanks in advance for your help, apologies if I have missed something here.

**Comment by mccoys** [comment]
Check the argument `polarizatin_phi`

Note that github is for issues or bugs. For usage and general questions, use the chatroom (link on the website)
