### ISSUE TITLE
Bug of Initialize particles from an array or a file.

### ISSUE THREAD

**Issue by zhazhajust** [SmileiPIC/Smilei#553]
## Description

I was loading species use  "initialize particles from an array or a file". But when i use hdf5 file to initialize the species. I get the wrong species parameters, which is different the data in hdf5 file. 

Init from numpy array can get right species parameters, but each mpi node load the array once, so that it cost too mach memory.
![Error](https://user-images.githubusercontent.com/56915687/179666432-2b38e3b5-ae29-4fb6-bbe6-cd86dbeb958f.jpg)

## Steps to reproduce the problem

If relevant, provide a step-by-step guide

at first, I run a Smilei code, and get a hdf5 file of trackparticles, and then i use it as input file of "initialize particles from an array or a file", but when i check trackparticles from the output hdf5 file, i find out that it's different from the input. And i changed to Numpy array as a input file of that, it works correctly, but just cost too much memory.

## Parameters

- Smilei version v4.7
- Input file
[DLT_test.txt](https://github.com/SmileiPIC/Smilei/files/9137518/DLT_test.txt)

- Commands or script used to run the faulty simulation: both of them was tested
- Computing resources
  - type of computer: super computer
  - OS: centos 7
  - C++ compiler (to get some information `g++ --version`):gcc 4.8.5
  - MPI version (`mpic++ --version`, `mpic++ -show`) :mpirun --version intel 2018.1 mpicxx --version gcc 4.8.5
  - HDF5 version (`h5cc --version`) 1.10.4 and 1.12.1 and 1.8.22 was tested
  - Python version (`python --version`) 3.8.3
  - ...

**Comment by mccoys** [comment]
It looks like there are negative numbers. Maybe the type of numbers (uint32 or int32 for instance) is incorrect. Have you checked the hdf5 file manually?

**Comment by zhazhajust** [comment]
Thanks a lot for your suggestion, I checked the HDF5 data manually according to your suggestion.

At first, this is the input file of hdf5.

<img width="669" alt="input_fromHDF5" src="https://user-images.githubusercontent.com/56915687/180128661-5e3697f3-9ad6-454c-afb7-538a74373bc7.png">

And I find that if i use hdf5 as input file, the output will be different. The "x", and "y" was according to the input file, but the "weight", "px", "py", "pz" was totally different.  

<img width="621" alt="output_fromHDF5" src="https://user-images.githubusercontent.com/56915687/180128672-7e106eed-6e54-4c67-80aa-26ed7538d242.png">

For the situation us Numpy array as input, the output as show in below, the data is consistent with the initial data, but the order is different.

<img width="673" alt="output_fromNumpy" src="https://user-images.githubusercontent.com/56915687/180128676-05f1c277-3848-4b40-a9b9-09db51c6e261.png">

**Comment by mccoys** [comment]
There is definitely an issue in reading it writing the file. I cannot test right now, but I believe we have automated testing for this.

Are you sure those numbers are the ones you read from the hdf5 file? Not the ones you write? So you read and write the file on the same system?

**Comment by zhazhajust** [comment]
I'm sure that the wrong hdf5 file was read from "TrackParticlesDisordered_electrons.h5" in dataset "data/0000000000/particles/electrons/", and the input hdf5 file was writed by h5py which was according to the hdf5 version.

In fact, i had test to use the output hdf5 file of smilei as the input file, for the path "path_of_wkdir/TrackParticlesDisordered_electrons.h5/data/0000000000/particles/electrons", but it also seem to exist the same question above.

**Comment by mccoys** [comment]
I have a hard time understanding all the details. 

If you make the file with h5py, or if you reuse the output of smilei, you get a bad result in both cases?

If you open these files by hand, is the data correct?

Thank you for these precisions

**Comment by zhazhajust** [comment]
I'm sorry for not expressing my question clearly.
And in fact, both of making the file with h5py and reuse the output of smilei leading a bad result.
At first, i use the hdf5 file that i use h5py writed, and i get the wrong results, and i check the output hdf5 file manually. Then i find that all data except position "x", "y" are wrong, and the weight even appears negative.
And then i reuse the output of smilei as the input hdf5 file, it has the same problem. The "weight" still seem to have negative values.
Finnaly, i choose to use numpy array as initiation, and luckly it works. So that i can get right data and image by ndarray only. And if i use Numpy array init, i find that each process will load the array once so that the memory quickly use up. I can run it correctly by reduce the process to a low level.

**Comment by mccoys** [comment]
This bug will be fixed soon. In the meantime, please use numpy array initialization.

**Comment by mccoys** [comment]
This bug is now fixed
