### ISSUE TITLE
How to prescribe EM Fields at the boundaries

### ISSUE THREAD

**Issue by arghyadeep-paul** [SmileiPIC/Smilei#555]
I have been looking into the documentation, it is unclear to me that how do I specify Magnetic Field components at a boundary. Say, in a 2D box one want to specify a constant `By` (say By= 5 nanoTeslas) at the `xmin` and `xmax` boundary. What is the process for that?

**Comment by mccoys** [comment]
Have you tried with a generic Laser?

**Comment by arghyadeep-paul** [comment]
Yes, i did look into the documentation of Lasers but it was mentioned that Lasers prescribe `oscillating` boundary conditions for the magnetic field on one of the box sides. However, my profile would not be an oscillatory one. Would it then be as simple as defining a function with arguments (coordinate, time) and just not use the 'time' variable in the return value?

**Comment by mccoys** [comment]
I think it would be as simple as that. However, I have never tried it so there might be unexpected results

**Comment by arghyadeep-paul** [comment]
Okay. I will try it and let you know here. I shall close this thread for now. Thanks
