### ISSUE TITLE
How to improve quality figure in  cylindrical geometry simulation

### ISSUE THREAD

**Issue by m-rezaei-p** [SmileiPIC/Smilei#558]
Dear Experts,
I used cylindrical geometry for simulation LWFA, but I have a problem with the quality of figures output.
For example, for this prob:
```
DiagProbe(
   
every = diagEvery,
   
origin   = [0., -nr*dr,1*dr],
   
corners  = [ [nx*dx,-nr*dr,0], [0,nr*dr,0] ],
   
number   = [nx, 2*nr],
   
fields = ['Ex','Ey','Ez','Rho_electron']
)
```
I start with regular_number=[1,1,8](case1), and after that I increase number of particles per cell(case2,3,4),
Also, I used the binomial filter to reduce noise but it is not good for this case(case3) 
But I cannot remove the line noise at the center (around r=0).
![compare_results](https://user-images.githubusercontent.com/58806777/185431637-a5b78162-d75a-4d2a-a93a-d6d288771b72.png)

also this is my name list:
[case16.txt](https://github.com/SmileiPIC/Smilei/files/9375090/case16.txt)

**Comment by Z10Frank** [comment]
In cylindrical geometry it is normal to have strange effects on the axis. 
Mathematically r=0 is a singularity, so even with proper boundary conditions the noise on the axis will not be completely eliminated.

Your figures with 32 particles per cell have axis noise in the second and third wave buckets, so you can try increasing even more the number of particles to see if it is reduced. Normally one is interested in the acceleration of particles in the first bucket, where you do not have much noise. For this purpose this level of axis noise should be ok.

It looks like the binomial filter in this case is giving strange effects on the density, so I suggest to avoid using it or try with an equal number of passes in both directions.

If your concern is only about the quality of figures, you can try changing the plot options to make the axis effects less visible.
1) when you use imshow, you can use interpolation https://matplotlib.org/stable/gallery/images_contours_and_fields/interpolation_methods.html
3) You can try a custom gaussian filter, and play with the sigma parameter https://datacarpentry.org/image-processing/06-blurring/
