### ISSUE TITLE
collision ionization with two ion species

### ISSUE THREAD

**Issue by iplasma** [SmileiPIC/Smilei#560]
Hi,

I am trying to do collision ionization with two ion species. However, Smilei crashes if these species do not have the same atomic_number. 

For example, using the following the simulation will crash

```
species =["ion1",  "ion2", 'electron']

Species(name = 'ion1', position_initialization = 'regular', momentum_initialization = "maxwell-juettner", temperature = [0.01/511]*3, particles_per_cell = 10, atomic_number=6, mass = 12*1836.0, charge = 2.0, number_density = 1.0, boundary_conditions = [ ["periodic", 'periodic'],], time_frozen=10,)

Species(name = 'ion2', position_initialization = 'regular', momentum_initialization = "maxwell-juettner", temperature = [0.01/511]*3, particles_per_cell = 10, atomic_number=1, mass = 1.0*1836.0, charge = 1.0, number_density = 1.0, boundary_conditions = [ ["periodic", 'periodic'],], time_frozen=10,)

Species(name = 'electron',position_initialization = 'regular', momentum_initialization = "maxwell-juettner", mean_velocity= [0]*3, temperature = [0.01/511]*3, particles_per_cell = 10, mass = 1.0, charge = -1.0, number_density = 1.0, boundary_conditions = [ ["periodic", 'periodic'],], time_frozen=10)

for sp in species:
  if sp!="electron" :
     Collisions(
        species1 = ["electron"],
        species2 = [sp],
        coulomb_log = 0,
        ionizing = True
     )
```

But it runs fine if both ion species have the same atomic number. The document mentions "One of the species groups must be all electrons ([mass](https://smileipic.github.io/Smilei/namelist.html#mass) = 1), and the other one all ions of the same [atomic_number](https://smileipic.github.io/Smilei/namelist.html#atomic_number).", but I am not using all ions in the same group. So how should I make the electron collide with more than one ion species?

I am using the latest version of smilei on github. 

Thanks!

**Comment by mccoys** [comment]
Could you provide the crash report?

**Comment by mccoys** [comment]
Ok I found and fixed the bug. It should work now.
