### ISSUE TITLE
Nuclear reaction

### ISSUE THREAD

**Issue by denisbertini** [SmileiPIC/Smilei#561]
I have seen that in Smilei the Nuclear Reaction are modelled using  binary collision approach inspired by the article/work of Higginson.

```
A Pairwise Nuclear Fusion Algorithm for Weighted Particle-in-Cell Plasma
Simulations
Drew Pitney Higginson, Anthony Link, Andrea Schmidt
```  
According to the article, this method 
`has been benchmarked  with like-particles, D(d,n)3He, unlike-particles, D(t,n)4He, thermonuclear plasmas, beam-target fusion, and for large difference in macro-particle weights.`
Now i see that  Smilei also can simulate `Nuclear Reaction` so my questions

- Are you using the same approach as Higginson for the fusion mechanism
- If yes could you imagine to use this approach also for fission reaction ?

**Comment by mccoys** [comment]
Hi
Yes the approach is basically the same, with some modifications: 
* The multiplier is automatically adjusted, but the method to do that is specific to Smilei as the article from Higginson et al. does not provide a method.
* Only the reaction D(d,n)3He has been implemented as of yet.

The method should work fine for fission, but it requires implementing the cross sections for a given reaction, and the angular distribution of the products.

**Comment by mccoys** [comment]
The R multiplier adjustment method is specific to smilei. It is identical for any reaction you would apply.
Check it out [here](https://github.com/SmileiPIC/Smilei/blob/master/src/Collisions/CollisionalNuclearReaction.cpp#L168)

**Comment by denisbertini** [comment]
I see
This famous R multiplier is adjusted for statistics ... 
Just curious though ... how did you estimate the different R values  ?

**Comment by mccoys** [comment]
The method simply relies on the amount of reactions that have happened. If no reactions were seen, increase R. If reactions were seen but to few for good statistics, increase R a bit. If the number of created macro particles is too high, reduce R.

**Comment by denisbertini** [comment]
Thanks for the detailed explanation !
Another question concerning cross section as a function of energy used in the case of nuclear fusion in `CollisionalFusionDD.cc`. 
More precisely the cross section data used at Line:
https://github.com/SmileiPIC/Smilei/blob/ebf6eb1e473e55875058fd0f6bea730f3f56b414/src/Collisions/CollisionalFusionDD.cpp#L11
Do you have any reference where the cross section data come from and how interpolation/extrapolation is done ?

**Comment by mccoys** [comment]
I must admit the documentation is sparse on nuclear reactions.
I took this reference and fitted the curves:
https://doi.org/10.1016/j.adt.2017.05.006

**Comment by mccoys** [comment]
If you have more questions, please reopen or use the chat
