### ISSUE TITLE
Mac ld linker problem while installation

### ISSUE THREAD

**Issue by jacky200901** [SmileiPIC/Smilei#563]
Hi.

 I've been using Smilei normally for months. Recently I tried to re-install Smilei on my Mac with Homebrew  and kept running into the same error while linking the Smilei program:

> ==> Installing iltommi/brews/smilei --HEAD
==> make
Last 15 lines from /Users/lichentong/Library/Logs/Homebrew/smilei/01.make:
1  0x101d9a28d  mach_o::relocatable::Parser<x86_64>::parse(mach_o::relocatable::ParserOptions const&) + 4989
2  0x101d8af8f  mach_o::relocatable::Parser<x86_64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 207
3  0x101e019d4  ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 2036
4  0x101e04fa0  ___ZN2ld4tool10InputFilesC2ER7Options_block_invoke + 48
5  0x7ff80e68234a  _dispatch_client_callout2 + 8
6  0x7ff80e6938f5  _dispatch_apply_invoke + 213
7  0x7ff80e682317  _dispatch_client_callout + 8
8  0x7ff80e691c0c  _dispatch_root_queue_drain + 673
9  0x7ff80e69225c  _dispatch_worker_thread2 + 160
10  0x7ff80e835f8a  _pthread_wqthread + 256
A linker snapshot was created at:
	/tmp/smilei-2022-09-19-182115.ld-snapshot
ld: Assertion failed: (_file->_atomsArrayCount == computedAtomCount && "more atoms allocated than expected"), function parse, file macho_relocatable_file.cpp, line 2061.
collect2: error: ld returned 1 exit status
make: *** [smilei] Error 1

>% git describe --all --long                               
heads/master-0-g55a173980

I followed the procedure in https://smileipic.github.io/Smilei/Use/install_macos.html and all other dependencies seem to operate normally. I have re-installed Xcode-select and Homebrew several times and the error still happens. It seems that no relevant problems have been reported.

is there any way to get through this?

attached is the ld-snapshot, if that may help

Thank you in advance.

[smilei-2022-09-19-182115.ld-snapshot.zip](https://github.com/SmileiPIC/Smilei/files/9601531/smilei-2022-09-19-182115.ld-snapshot.zip)

**Comment by iltommi** [comment]
Hi,
I just tried again and can't reproduce the problem.

I'm not on the laster macos version (I'm on Big Sur 11.6.8)

would it be possible for you to do a manual installation as explained here: https://smileipic.github.io/Smilei/Use/install_macos.html#brew-install-dependencies 
?

Thanks

**Comment by iltommi** [comment]
I've seen this: https://developer.apple.com/forums/thread/714565 which seems to point to a brew fault somehow...

In case the manual compilation fails, could you try to compile with llvm clang++ ? (standard macos clang is not an option since it lacks a lot of new features)

you need to install llvm via `brew install llvm`
and then 
`export OMPI_CXX=`brew --prefix llvm`/bin/clang++`

than `make clean` and `make`
clang is way more strict than gcc and will throw a LOT of warnings, don't be afraid...

**Comment by jacky200901** [comment]
> I've seen this: https://developer.apple.com/forums/thread/714565 which seems to point to a brew fault somehow...
> 
> In case the manual compilation fails, could you try to compile with llvm clang++ ? (standard macos clang is not an option since it lacks a lot of new features)
> 
> you need to install llvm via `brew install llvm` and then `export OMPI_CXX=`brew --prefix llvm`/bin/clang++`
> 
> than `make clean` and `make` clang is way more strict than gcc and will throw a LOT of warnings, don't be afraid...

thank you for the reply. it seems that make directly with gcc still causes the same problem, but making with llvm clang seem to work.
