### ISSUE TITLE
Why was Jupyter Notebook Widget Support Commented Out?

### ISSUE THREAD

**Issue by jshin313** [SmileiPIC/Smilei#570]
Hello,

I'm using Jupyter Notebook to visualize the data using Happi for ease of use and since I don't have a GUI on my remote server. However, widgets like the animation and slider don't work. 

I saw that there was preliminary code to support Jupyter Notebook, but then it was commented out.

Are there any suggested workarounds?

**Comment by jshin313** [comment]
Update: I found out I can use `%matplotlib notebook` at the top of the jupyter notebook cell and get the widgets to work.

**Comment by mccoys** [comment]
Indeed that is the reason why it was commented out!
