### ISSUE TITLE
Weird out of memory problem when running on a slurm cluster

### ISSUE THREAD

**Issue by jacky200901** [SmileiPIC/Smilei#573]
Hi.

I've been trying to run some simulation on a cluster with the following setup:
>OS:  Linux redhat 7.3 64bit with Slurm 17.02 
Dependencies: HDF5-1.12.2 built with --with-slurm config, OpenMPI-4.1.4 with gcc-4.8.5
Smilei: v4.7

None of these reported error while installation, and a test run with a 1-d namelist from the Benchmark folder ended successfully. 

But when trying to run my own simulation the program always ends up with weird out-of-memory failure several steps after successful initialization.
It seems the code runs normally on my 16GB RAM PC but fails with OOM on cluster nodes.

here's the output of the task:
[res_smilei.2546987.out.txt](https://github.com/SmileiPIC/Smilei/files/10049946/res_smilei.2546987.out.txt)
and the script to submit the task:

> #!/bin/bash
#SBATCH -o res_smilei.%j.out
#SBATCH -J smilei_coil_simu
#SBATCH -p C032M0512G
#SBATCH --qos=normal
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
module load ~/modulefiles/openmpi-hdf5p-smilei
srun hostname -s | sort -n >slurm.hosts
mpirun --mca btl_openib_allow_ib 1 -machinefile slurm.hosts smilei ./my-simulation.py

Could you help me find out what is going wrong on my system?

Thank you in advance 
Ct. Li

**Comment by mccoys** [comment]
You might not be setting up correctly the number of mpi and omp. Do you have sysadmin to help you?

**Comment by jacky200901** [comment]
> You might not be setting up correctly the number of mpi and omp. Do you have sysadmin to help you?

Thanks for the advice. I have consulted sysadmin and it seem that I had some misunderstanding setting up the task resources.
