### ISSUE TITLE
obliquely incident laser beam in 2D focused on target - wrong laser beam waist parameter

### ISSUE THREAD

**Issue by jpsikal** [SmileiPIC/Smilei#577]
Dear Smilei developers and users,

I found a bug when using focused laser beam incident obliquely on a target compared with focused laser beam incident normally. 
Total energies of laser beams differ. 

Namely, I used the following laser blocks for normal and oblique incidence (for example):

LaserGaussian2D(
    box_side        = "xmin",
    a0              = 27.,  # intensity 1.0e+21
    omega           = 1.,                  # wavelength 1 mum
    focus           = [21.2*l0, Main.grid_length[1]/2.],
    waist           = waistinE
    incidence_angle = 0.,   # 0 deg
    polarization_phi = 0.,
    ellipticity     = 0.,
    time_envelope   = ramp3gauss
)

LaserGaussian2D(
    box_side        = "xmin",
    a0              = 27.,  # intensity 1.0e+21
    omega           = 1.,                  # wavelength 1 mum
    focus           = [30.0*l0, Main.grid_length[1]/2.+13.4*l0],
    waist           = waistinE
    incidence_angle = 0.7854,   # 45 deg
    polarization_phi = 0.,
    ellipticity     = 0.,
    time_envelope   = ramp3gauss
)

When waist parameter is equal to the same constant in both cases  (waist= waistinE), the total energy of laser pulse is larger for obliquely incident pulse. 
Almost the same energy of the pulse can be obtained when I used waist= waistinE/1.414=waistinE/cos(45/180*pi) for oblique incidence and waist=waistinE for normal incidence. 
Thus, there is a mistake in calculation with cos() factor in /src/Python/pyprofiles.py

I am not sure what would happen in 3D case (when using block LaserGaussian3D) as I have not tested it yet. 
I guess there could be similar problem.

In my simulations, I can use "correction factor" 1/cos(angle) in the namelist, but it should be corrected in the source code for other users ... 

Jan

**Comment by jpsikal** [comment]
> Have you checked the maximum field is different than the requested a0?

The maximum field has the same value as requested (a0=27) at focus. 
It does not depend on waist parameter.  
For time envelope, I used the function ramp3gauss which is defined as follows (in test cases):
def ramp3gauss(t):
    A1=1.0
    sigma1=4.5*t0    #= 15 fs
    return A1*math.exp(-(t-30.*t0)**2/(4.*sigma1**2))

Here, it is simplified envelope for tests (in fact, it is gaussian function).

**Comment by mccoys** [comment]
@jpsikal I am not able to reproduce the error. Note that I did not measure the total energy (which is not a good way because it depends on when the pulse started, etc.) but I measured the width of the envelope at best focus. It does not depend on the angle, as long as I am careful to have a boundary large enough to contain all the laser.

**Comment by mccoys** [comment]
@jpsikal Could you comment on my last answer?

**Comment by jpsikal** [comment]
> @jpsikal Could you comment on my last answer?

I can provide you my namelists for normal incidence and oblique incidence (45 degrees). 
[LIGHTnoramp1e19d0a.py.txt](https://github.com/SmileiPIC/Smilei/files/10794251/LIGHTnoramp1e19d0a.py.txt)
[LIGHTnoramp1e19d45a.py.txt](https://github.com/SmileiPIC/Smilei/files/10794256/LIGHTnoramp1e19d45a.py.txt)

Note that in the namelist LIGHTnoramp1e19d45a.py I used 
LaserGaussian2D(
......................................................................
    waist           = waistinE/1.4142,
.......................................................................
)

instead of 

LaserGaussian2D(
......................................................................
    waist           = waistinE,
.......................................................................
)

in order to solve the problem I met and described earlier. 
I used "correction factor" 1/cos(incidence_angle) = 1.4142. 
In my opinion, there is a mistake in calculation with cos() factor in /src/Python/pyprofiles.py

I also attach energy balances in both simulations which show roughly the same maximum of electromagnetic energy in the simulation box (green line). 
Without the correction factor I used, the maximum energies (equal to the total energy of the laser pulse) would be very different.
![enbalance-0deg](https://user-images.githubusercontent.com/53087545/220370023-366667c5-e1d5-4170-8fb0-29ad946a22a5.png)
![enbalance-45deg](https://user-images.githubusercontent.com/53087545/220370166-4878c1c6-f1c8-4dc0-97d9-253d097a0ca4.png)


Jan

**Comment by mccoys** [comment]
Ok I think I found the problem. There is no issue with the waist actually, and the definition of `LaserGaussian2D` seems correct. However, the injecting boundary conditions are imperfect for most incidences, but there is an option to change the optimal incidence: `EM_boundary_conditions_k`. For an angle `theta` you should use:
```python
    EM_boundary_conditions_k = [[cos(theta),sin(theta)],[-1.,0.],[0.,1.],[0.,-1.]] 
```

**Comment by jpsikal** [comment]
Thank you for your help. It seems that I was not careful when reading SMILEI documentation about EM_boundary_conditions.
