### ISSUE TITLE
Number density plot in unit of 10^20 cm^-3

### ISSUE THREAD

**Issue by Sonuphd** [SmileiPIC/Smilei#579]
Dear Sir, 
I am facing an issue with plotting of number density plot in unit of 10 ^20 cm^-3. When I use Rho in units of 10^20 cm^-3 e, I have found the plot but when I use Rho in unit of 10^20 cm^-3, I have not found the plot and this has been happened after the update of Smilei version. I have used this command.
 
When I use this command: diag1=S1.Field(0,"Rho",units=["10^20 cm^-3e","um","fs"],title_font = font,xlabel_font = font,ylabel_font =font,xticklabels_font = font,yticklabels_font = font,colorbar_font= font,cmap="seismic_r",vmin=0,vmax=-1), I have found the result but
 when I use the command: diag1=S1.Field(0,"Rho",units=["10^20 cm^-3","um","fs"],title_font = font,xlabel_font = font,ylabel_font =font,xticklabels_font = font,yticklabels_font = font,colorbar_font= font,cmap="seismic_r",vmin=0,vmax=-1), I have not found the results but this has been not happend with previous version of Smilei. I have attached an screenshot with my Smilei version.

![Screenshot (265)](https://user-images.githubusercontent.com/42186182/203809948-6e126d58-0e32-446b-8aac-ecfc19cc0b51.png)

**Comment by mccoys** [comment]
Please explain what you mean by "I have not found the result"

**Comment by Sonuphd** [comment]
When I use unit 10^20 cm^-3 e for Rho which is charge density and results has been found and but if I use unit 10^20 cm^-3, results not found. How to plot number density in unit of 10^20 cm^-3.

**Comment by mccoys** [comment]
What result? What do you mean "found"?

**Comment by mccoys** [comment]
Do you see an error message? Do you see a plot window? Is it empty?

**Comment by Sonuphd** [comment]
diag1=S1.Field(0,"Rho",units=["10^20 cm^-3","um","fs"],title_font = font,xlabel_font = font,ylabel_font =font,xticklabels_font = font,yticklabels_font =
   ...:  font,colorbar_font= font,cmap="seismic_r",vmin=0,vmax=-1)
![Screenshot (284)](https://user-images.githubusercontent.com/42186182/204238210-45518d8f-32ca-4f6f-811b-a977f0515b31.png)

**Comment by mccoys** [comment]
Yes because Rho is in units of charge per volume. Please specify `e/cm^3`

**Comment by Sonuphd** [comment]
But this is charge density plot and I want number density plot.

**Comment by mccoys** [comment]
Well this is not the right diagnostic. Try particle binning.
