### ISSUE TITLE
How to set parameters in large moving window 3D simulations to avoid crashes

### ISSUE THREAD

**Issue by XiangTangUSTC** [SmileiPIC/Smilei#586]
Hello developers:

I have a crash problem in the large moving window 3D simulation. I think it's due to memory.
The simulation cell numbers is 1024×1024×1024. Cell length is 0.02um×0.02um×0.02um. There is a foil in y-z plane of Lx/2. The PPC on the surface of the foil is 120, and the PPC on the back is 10. The patch arrangement is default，number_of_patches = [128, 128, 128].
In the moving window simulation, it is very easy to crash when the window starts moving. There is no error file output, but some tips at the end of the out file:

[out.txt](https://github.com/SmileiPIC/Smilei/files/10173154/out.txt)

My script for submitting the job is：
#!/bin/sh
#SBATCH -J smilei_MwHpLt
#SBATCH -p hfac
#SBATCH -N 32
#SBATCH -n 4096    
#SBATCH -o out.%j
#SBATCH -e err.%j
#SBATCH -t 10:00:00
export OMP_NUM_THREADS=2
export OMP_SCHEDULE=dynamic
mpirun -np 2048 ./smilei smilei_MwHpLt.py

The hardware of each node is:
Processor | 2× AMD 7702, 2.0 GHz, 64-core
Cores per node | 128 (2× 64-core processors)

I want to know how to set the number of processes and threads and the patch arrangement to avoid the crash of the simulation.

**Comment by mccoys** [comment]
* I suggest you update to a more recent version of Smilei
* It is likely better to have more threads for less processes per node. You have only 2 threads per process and 32 processes per node. Try the opposite: 2 processes per node and 32 threads per process.

**Comment by XiangTangUSTC** [comment]
Thank you for your suggestion.
I actually tried to install a new version of smileI a month ago, but I failed.When I tried to compile a new version of smilei, I had some problems. So I try to rely on Python instead of miniconda. Here's how I installed it:

export PATH=/public/home/ac9tbj9ze4/soft/py3.6.11/bin:$PATH
export LD_LIBRARY_PATH=/public/home/ac9tbj9ze4/soft/py3.6.11/lib:$LD_LIBRARY_PATH
export PYTHONEXE=/public/home/ac9tbj9ze4/soft/py3.6.11/bin/python3
export INCLUDE=/public/home/ac9tbj9ze4/soft/py3.6.11/include:$INCLUDE
![image](https://user-images.githubusercontent.com/117325352/206375196-1fa77f41-66ff-427e-b726-b97169a1ad37.png)
make -j 4
[process of make.txt](https://github.com/SmileiPIC/Smilei/files/10182768/process.of.make.txt)
/public/software/compiler/devtoolset-7/root/usr/bin/../libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -lpython3.6m
collect2: error: ld returned 1 exit status
make: *** [makefile:298：smilei] error 1

**Comment by xxirii** [comment]
Hi,

Can you check that the path `/public/home/ac9tbj9ze4/soft/py3.6.11/lib` is correct and that the python lib 3.6 is well in this directory ?

Can you try as well :
```
export LD_LIBRARY=/public/home/ac9tbj9ze4/soft/py3.6.11/lib:$LD_LIBRARY
```

Thank you

**Comment by XiangTangUSTC** [comment]
@xxirii Thank you very much for your help. According to the guidance you give, I have successfully compiled the latest version of Smilei. And thanks to all the developers above.

@iltommi It's a pity that I can't give the results at that time because I have compiled. However, I tried to restore the situation at that time, and the following is the result according to what you said. I am very sorry that I may not be able to give you too much feedback.
[sysconfig.txt](https://github.com/SmileiPIC/Smilei/files/10184939/sysconfig.txt)

**Comment by xxirii** [comment]
Good, let us know about the `moving window` issue.

**Comment by XiangTangUSTC** [comment]
Hi，developers!
I sorted out the situations I encountered and found the following two problems.

1. The first problem is that in high-precision simulation, if I use multiple threads, it is easy to crash when creating patches. I wonder if it's because a foil in y-z plane of Lx/2 in the simulation box (patch_arrangement = "linearized_ZYX"). Or openmpi was not compiled successfully. There is no output in the error file in this case, only “EXIT CODE: 9” at the end of the out file.

[run.sh.txt](https://github.com/SmileiPIC/Smilei/files/10193727/run.sh.txt)
[out1857853.log](https://github.com/SmileiPIC/Smilei/files/10193698/out1857853.log)

2. For the situation above, I can only use MPI processes as much as possible. In the simulation with moving window, the simulation often crashes shortly after the window starts moving.
[run2.sh.txt](https://github.com/SmileiPIC/Smilei/files/10193749/run2.sh.txt)
[out1851971.txt](https://github.com/SmileiPIC/Smilei/files/10193750/out1851971.txt)
I used performance diagnostics because I suspected there might be a memory overflow.  Below is a diagram of memory usage and load before the crash.
<img width="701" alt="1" src="https://user-images.githubusercontent.com/117325352/206679330-a9915194-fb8a-46ce-b0d2-9419da31f98a.png">
<img width="712" alt="2" src="https://user-images.githubusercontent.com/117325352/206679334-f58ccf87-14f0-42ab-813d-5878e305da6b.png">
<img width="708" alt="3" src="https://user-images.githubusercontent.com/117325352/206679338-1d570b9d-d04b-4a48-831a-42cd16b40559.png">

**Comment by XiangTangUSTC** [comment]
Hi,developers!
I browsed the ISSUSE section and found that perhaps OpenMPI would be better, so I compiled another SmileI based on OpemMPI.

[ac9tbj9ze4@login05 testOMP]$ `mpirun --version`
mpirun (Open MPI) 4.1.1

Report bugs to http://www.open-mpi.org/community/help/

But there are problems running when trying to multithreaded:
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/117325352/206908650-53c108f5-b2a7-449b-8f71-31ebb9f5d637.png">
It seems that there are some problems when starting the diagnostic function, which I have not encountered when using the intelmpi.

The error file:
![image](https://user-images.githubusercontent.com/117325352/206908955-d8ffae0a-7bb3-4212-b9c9-4757e979b9a3.png)

This is the output file：
[out.txt](https://github.com/SmileiPIC/Smilei/files/10202410/out.txt)

**Comment by xxirii** [comment]
Hi,

I just want to be sure, you have tried to install by hand OpenMPI on a cluster ?

If yes, OpenMPI is probably not correctly configured for your network resulting in this message. By default, OpenMPI will certainly try to use the administration network and not the infiniband network. There are some options to pass to OpenMPI for it but this is the work of the super-computer administration. I am surprised there is no OpenMPI modules available ? Are you familiar with that ?

**Comment by xxirii** [comment]
If you have a public documentation for your cluster, I can have a look.

**Comment by XiangTangUSTC** [comment]
Hello, 
The problem shown above is to use the OpenMPI provided by the super-computer administration(`module load mpi/openmpi/gcc/4.1.1`). At the same time, I tried to compile a new version of OpenMPI myself today, and I encountered the same problem. I'm sorry I'm not familiar with this. I will first solve this problem with the supercomputer technician and then communicate with you.

**Comment by xxirii** [comment]
Please yes, was it with the same configuration : 2048 mpis and 2 openmp threads per MPI ?

**Comment by XiangTangUSTC** [comment]
Unfortunately, the computer administrator did not solve the OpenMPI problem and there was no public documentation, and he recommended that I use Intel MPI. The above test on OpenMPI is only a general simulation, just for testing purposes (not  2048 mpis and 2 openmp threads per MPI). I've tried several combinations of threads and processes (1024MPI×2OPM,245MPI×8OPM,64MPI×32OPM). Programs usually run but are inefficient. It pains me so much that it really takes me too much time to test OpenMPI. So I was wondering if I could continue my simulation with Intel MPI.（>﹏<）

**Comment by XiangTangUSTC** [comment]
Returning to the initial question, regarding the large simulation with moving windows, I found that when the windows started moving, there were some peak memory of MPI processes that started abnormally.I did three tests for the same simulation( window starts moving in step 2140).
1. 4096MPI×1OpenMP
![image](https://user-images.githubusercontent.com/117325352/207036232-b26ca5ad-999a-48c6-9d4b-c930bb525350.png)
![image](https://user-images.githubusercontent.com/117325352/207036290-4d89b729-8332-4ef1-ae57-2f950377b16f.png)
![image](https://user-images.githubusercontent.com/117325352/207036329-0cc5df8e-b14b-43d7-8e6c-f4c3532b3f65.png)

2. 2048MPI×2OpenMP
![image](https://user-images.githubusercontent.com/117325352/207036401-27605b87-1625-4753-9177-6ab95894c619.png)
![image](https://user-images.githubusercontent.com/117325352/207036454-2e8fd944-16ab-4455-a897-0492d125cd89.png)
![image](https://user-images.githubusercontent.com/117325352/207036484-5f157590-877a-473e-b4a4-469dc68b804b.png)

3. 2432MPI×1OpenMP
![image](https://user-images.githubusercontent.com/117325352/207036652-2d89c531-c38e-4dd6-974f-5bda8cb2b01c.png)
![image](https://user-images.githubusercontent.com/117325352/207036685-0bcb9199-1288-4a17-8388-e39474f0bda3.png)
![image](https://user-images.githubusercontent.com/117325352/207036710-293a07e2-988e-4e88-8c9c-b1f73a16dd0e.png)

**Comment by mccoys** [comment]
This could be the same issue as #405

**Comment by XiangTangUSTC** [comment]
> This could be the same issue as #405

Yes, I've also looked at ISSUE #405 . Can you give me some suggestions on parameter settings or hdf5, MPI versions for my next test? I am anxious to complete this simulation.

**Comment by xxirii** [comment]
Can I have a version of your namelist ? If possible the smallest size that crashes. Thank you

**Comment by XiangTangUSTC** [comment]
Sorry, I can't share this because my simulation work is a subject provided by my tutor. But what's exciting is that last night's simulation was successfully completed.
In several of my tests, I found that there always seemed to be individual MPI processes with high memory peaks, which seemed to have little to do with the number of MPI processes. So I just need to minimize the number of MPI processes and increase OpenMP threads so that each MPI process has a larger memory capacity. Finally, with 1024MPI×4OpenMP, the simulation is completed.
[out.3.txt](https://github.com/SmileiPIC/Smilei/files/10213620/out.3.txt)

The hardware of each node is:
Processor | 2× AMD 7702, 2.0 GHz, 64-core
Cores per node | 128 (2× 64-core processors)

Depending on the hardware of each node in the cluster, 2 processes per node and 64 threads per process seems better.
However, as fewer processes and more threads are added, the creation of patches will be slow. I will continue to do some tests to find the most efficient settings.

**Comment by xxirii** [comment]
Hi,

On AMD Epyc processor such as the one you use, we advice to use 4 MPI processes per socket (so 8 per node in your case since you have 2 sockets per node) and 16 OpenMP threads per MPI. The reason is that there are 4 NUMA domains on a single AMD processors.

For the namelist, in case you still have problems, I suggest you send something that reproduces the problem without all the parameters of your studies.

**Comment by XiangTangUSTC** [comment]
Hi，

Thank you for your patient answers. I have learned a lot from your communication. Your answers are very helpful to me. Everything is developing in a good direction. The compilation of Smilei, the MPI version and the number of process, threads have been set correctly. The multithreading encountered above will cause the speed to slow down, which is probably a problem with the patch arrangement method.

My current parameter settings are:
Cell numbers is 1024×1024×1024. Cell length is 0.02um×0.02um×0.02um. There is a foil in y-z plane of Lx/2. The patch arrangement is `patch_arrangement = "linearized_ZYX"`，number_of_patches = [128, 128, 128].

How to choose the appropriate number of patches and MPI process is appropriate, and ensure that Field diagnostics are available. Could you give me some advice?

**Comment by XiangTangUSTC** [comment]
After several days of testing, I have completely solved this problem and achieved considerable efficiency. The main influencing factors are as follows:

1. Reasonable patch creation. For foil, the patch arrangement is `patch_arrangement = "linearized_ZYX"` and set the appropriate number of patches in each direction.
2. Choose the number of MPI and OpenMPI, with real core architecture settings. More threads seem to alleviate memory spikes.
3. Keep a newer version of SmileI.

**Comment by xxirii** [comment]
Thank you for your feedback, we appreciate when we have all these pieces of information. To add an extra complexity, you may want to try the hilbertian patch arrangement with load balancing at some point ;)
