### ISSUE TITLE
unit conversion and "moving" argument does not work in AMcylindrical

### ISSUE THREAD

**Issue by spadova-a** [SmileiPIC/Smilei#588]
Hi all, 

I tried to convert units with pint package in my AM geometry simulation, but the syntax, which works in 2D geometry, doesn't work for me (example: el = sim.Field.Field0("El", theta=0.,modes=0, units = ["fs", "um"], moving=True)). What is even more weird, is that I don't have a physical axis at all, there is only the number of cells, instead of the code units. Note this is problem only for Fields diagnostic, ParticleBinning works fine.
Another problem, which I think is related to this, is the "moving" argument is not working at all. This is really unfortunate, because it is quite complicated to find the physical x-coordinate for the given timestep.

I use Smilei version 4.7-148

Do you have an idea, what can be done about this?
Thanks for your help.

**Comment by mccoys** [comment]
Please indicate your version of smilei.

**Comment by mccoys** [comment]
I am unable to reproduce the bug completely. The axis does not move according to the window (this is a bug) but I do have a physical axis and it is correctly converted to um.

**Comment by mccoys** [comment]
If you use git, the correction for the moving axis has been introduced in the branch `develop`.

**Comment by mccoys** [comment]
Please reopen if you find it did not work for you
