### ISSUE TITLE
Particle Injector Crash 

### ISSUE THREAD

**Issue by danielseipt** [SmileiPIC/Smilei#593]
## Description

Smilei crashes when trying to inject a particle beam with temperature (T=1.0) from a side wall (ymin) in a 3D simulation. The particle injector uses **tgaussian** as temporal profile. The code crashes at the timestep when the first partilcles should be injected. The crashes do not occur if the temperature is set to a very small value, e.g. 1e-30.

A minimal namelist showing the faulty behavior is attached.

```
 Time-Loop started: number of time-steps n_time = 100
 --------------------------------------------------------------------------------
[;33m
[WARNING](0) src/Params/Params.cpp:1414 (print_timestep_headers) The following `push time` assumes a global number of 128 cores (hyperthreading is unknown)[0m
  timestep       sim time   cpu time [s]   (    diff [s] )   push time [ns]
     1/100     8.5737e-01     6.6125e-01   (  6.6125e-01 )    ?? 
     2/100     1.4289e+00     1.2794e+00   (  6.1819e-01 )    ?? 
     3/100     2.0005e+00     1.8754e+00   (  5.9600e-01 )    ?? 
     4/100     2.5721e+00     2.4535e+00   (  5.7804e-01 )    ?? 
     5/100     3.1437e+00     3.0432e+00   (  5.8974e-01 )    ?? 
     6/100     3.7152e+00     3.6338e+00   (  5.9063e-01 )    ?? 
     7/100     4.2868e+00     4.2061e+00   (  5.7224e-01 )    ?? 
     8/100     4.8584e+00     4.7667e+00   (  5.6060e-01 )    ?? 
corrupted size vs. prev_size
corrupted size vs. prev_size
```

## Parameters

- Smilei version: 7add17e-master
- Input file [namelist.txt](https://github.com/SmileiPIC/Smilei/files/10373664/namelist.txt)
- C++ compiler g++ (GCC) 10.2.1 20200804 (Red Hat 10.2.1-2)
- HDF5 version 1.10.7
-  Python version 3.8.6
 - MPI version OpenMPI 4.1.0

**Comment by mccoys** [comment]
@danielseipt Could you check whether the fix done for #611 also solves your problem?
It is available in the `develop` branch -> 9f6da66ff3d
