### ISSUE TITLE
Possible memory leak during run (EPYC)

### ISSUE THREAD

**Issue by kcm1976** [SmileiPIC/Smilei#596]
## Description

Explain your issue here.
I am simulating two counter-propagating charge flows in 2D with periodic boundary conditions; filamentation appears with the total particle number retained (the invariance of the particle number was confirmed from the scalar diagnostics). In the beginning, the occupied memory is 15 GB, but it steadily increases to be 54 GB toward the end. The machine has a 64-core EPYC CPU and a 64-GB RAM (1 MPI process, 8x8 patches).  Because of the memory increase, I could not perform higher-resolution runs.  
<checkpoint and restart>
In the first run for checkpointing, the particle data consumes 15 GB (the field data ~ a few MB) initially, but the total memory usage becomes 24 GB upon timestepping. I made a checkpoint when the memory usage increased to 42 GB (timestep=360). When I restarted from the step, the memory usage began with a value of 29 GB and remained within 30 GB till the end. Thus, it seems a memory leak.

```
If available, copy-paste faulty code, warnings, errors, `etc.`
```

## Steps to reproduce the problem
Run the program while observing the memory consumption with the command top. 
(OMP_NUM_THREADS=64, OMP_SCHEDULE=dynamic, OMP_PROC_BIND=true)

If relevant, provide a step-by-step guide

## Parameters

- Smilei version ? 4.7-239-g94441699d-master
- Input file ? 
# rwi.py

```
from math import pi, sqrt

n0i = 1.0    # density: ion
n0p = 0.5    # density: e+
v0p = 0.9    # velocity: e+ 
n0n = 0.5    # density: e-
v0n = -0.9    # velocity: e- 
vth = 0.01    # thermal velocity
nppc= 1600


L0 = 2.*pi   # plasma wavelength = 2pi * (skin depth)
resx = resy = 64      # # of cells in one laser wavelength
dx  = dy = L0/resx
Lsimx = Lsimy = 4*L0


T0 = 2.*pi    # plasma period = 2pi / (angular plasma frequency)
Tsim = 8*T0                # duration of the simulation
rest = sqrt(resx**2 + resy**2)/0.95     # # fo timesteps in one optical period
dt   = T0/rest
diag_steps = int(T0/16/dt)


Main(
    geometry = "2Dcartesian",
    interpolation_order = 2 ,
    cell_length = [dx, dy],
    grid_length  = [Lsimx, Lsimy],
    number_of_patches = [8,8],
    
    timestep = dt,
    simulation_time = Tsim,
     
    EM_boundary_conditions = [["periodic"]],
    print_every = diag_steps,
    random_seed = smilei_mpi_rank
)


Species(
    name = "ion",
    position_initialization = "random",
    momentum_initialization = "maxwell-juettner",
    particles_per_cell = nppc,
    mass = 1836,
    charge = 1.0, 
    number_density = n0i,
    temperature = [vth**2,vth**2,vth**2],
    boundary_conditions = [["periodic"]]
)


Species(
    name = "eonp",
    position_initialization = "random",
    momentum_initialization = "maxwell-juettner",
    particles_per_cell = nppc,
    mass = 1.0,
    charge = -1.0, 
    number_density = n0p,
    mean_velocity = [0,0,v0p],
    temperature = [vth**2,vth**2,vth**2],
    boundary_conditions = [["periodic"]]
)


Species(
    name = "eonn",
    position_initialization = "random",
    momentum_initialization = "maxwell-juettner",
    particles_per_cell = nppc,
    mass = 1.0,
    charge = -1.0, 
    number_density = n0n,
    mean_velocity = [0,0,v0n],
    temperature = [vth**2,vth**2,vth**2],
    boundary_conditions = [["periodic"]]
)


DiagScalar(
    every = diag_steps
)

Checkpoints(
    dump_step = 360,
    exit_after_dump = False,
)
```

- Commands or script used to run the faulty simulation ? 
- Computing resources
  - type of computer: AMD EPYC 7763 64-Core (1 CPU)
  - OS: Ubuntu 22.04.1 LTS
  - C++ compiler (to get some information `g++ --version`): g++ 11.3.0
  - MPI version (`mpic++ --version`, `mpic++ -show`): openmpi-4.1.4
  - HDF5 version (`h5cc --version`): hdf5-1.10.9
  - Python version (`python --version`): 3.10.6
  - ...

**Comment by beck-llr** [comment]
Hi and thanks for your report.

Because of the NUMA architecture of the EPYC, it is strongly recommended tu use 4 MPI processes with 16 cores associated to each.
This should also help a bit with your memory problem since some buffers are sized to match the number of openMP threads. It will probably not completely solve your problem but it is definitely worth trying. Could you please try it and give us some feedback ?

Be careful to pin one MPI process per quadrant of the EPYC and not all on the same quadrant => make sure 16 cores are associated to each MPI process.

**Comment by kcm1976** [comment]
Thanks for your suggestion.
I tried it but failed to find a difference: actually the memory usage increased slightly probably due to multiple processes. 
The occupied memory was 24.3 GB in the beginning but increased to 44 GB @ timestep=360.
To have 4 MPI processes and 16 threads for each process, I set OMP_NUM_THREADS=16 and unset OMP_PROC_BIND. 
The output of "top" showed 4 processes and %CPU~<1600 for each process.

**Comment by beck-llr** [comment]
Ok thanks. FYI you can leave the `OMP_PROC_BIND` to true since you still want your openMP threads to be pinned to a given physical core. But that is probably a detail for now.

One last thing you might want to try is to use smaller patches. Once again by doing that you slightly increase the memory overhead due to patch boundaries but you also shrink the size of the particle vector by a significant amount and I am curious to see if this has an effect or not. So would you please try to use twice as many patches in each direction ? Just change the number of patches from 8 to 16 in the `Main`.

And finally, how exactly to you measure the memory occupancy ?

**Comment by kcm1976** [comment]
I don't know why, but unsetting OMP_PROC_BIND was necessary to have the intended number of MPI processes and OpenMP threads.

I increased the number of patches to 16x16. The timestepping stage began with 18 GB, much smaller than the previous runs, but at timestep=360 the memory consumption reached 43 GB as before.

I also tried 64 MPI processes (OMP_NUM_THREADS=1) but found no meaningful difference.

To find the memory occupancy, I used the command 'top'.

**Comment by kcm1976** [comment]
I'd like to report that the memory leak problem disappeared when I replaced the EPYC 7763 with a Xeon E5-2690 (8 cores). All the software remained the same. I ran 1 MPI process consisting of 8 threads and 8 MPI processes (1 thread/process). In both cases, the memory increase was about 1 GB throughout the simulation. The problem might be specific to the EPYC CPU.

**Comment by mccoys** [comment]
Even the compiler was identical?

**Comment by kcm1976** [comment]
Yes. The compiler was gcc 11.3.0 for both cases.

**Comment by beck-llr** [comment]
Some strange memory leaks with openMP on AMD Epyc has also been observed within pytorch  see https://github.com/pytorch/pytorch/issues/32008 and https://github.com/pytorch/pytorch/pull/90891.

If you still have time, could you please try to compile Smilei without openMP: `make smilei -j 20 config=noopenmp` and try again your run on 64 MPI processes please ?

**Comment by kcm1976** [comment]
Thank you very much for the information and your suggestion. I will try it and report the results in two days; I am on leave at the moment.

**Comment by kcm1976** [comment]
I recompiled Smilei w/o openmp, but the memory leak persisted. 

I consider to recompile all the relevant software with the option -march=znver3.

**Comment by kcm1976** [comment]
Setting the option -march=znver3 had no effect.

**Comment by beck-llr** [comment]
Thank you very much for your feedback. I'm out of idea for the moment and the fact that we can not reproduce it makes it difficult to investigate. Hopefully you can do your simulations on the Xeon for now.

**Comment by kcm1976** [comment]
I appreciate your help very much.
