### ISSUE TITLE
Radial momentum initialisation in AMcylindrical geometry

### ISSUE THREAD

**Issue by Z10Frank** [SmileiPIC/Smilei#599]
Here is a namelist for a simple, electrostatic plasma wave in cylindrical geometry (1 mode, i.e. perfect cylindrical symmetry):
[plasma_wave.py.txt](https://github.com/SmileiPIC/Smilei/files/10661904/plasma_wave.py.txt)

The wave is initialised with a sinusoidal initial perturbation of the momentum along the x direction in a uniform plasma, for example:
```
def initial_momentum_x(x,r):
    #radius = np.abs(r)
    return 0.5*np.sin(2.*math.pi/plasma_wavelength*x)*np.exp(-r*r/2./plasma_wavelength/plasma_wavelength)

def initial_momentum_y(x,r):
    return 0.

def initial_momentum_z(x,r):
    return 0.
```

`mean_velocity = [initial_momentum_x,initial_momentum_y,initial_momentum_z],`

Now, this creates a 1D perturbation, with particles oscillating mostly in the x direction.
 
To have a sinusoidal wave with radial oscillations (similar to those in a laser wakefield) an initial momentum in the radial direction should be defined.

Thus I think that in this geometry, as alternative, it should be possible to also define a radial velocity.

For the moment the only way I see to do it without a radial momentum profile is to define the species with numpy arrays.

**Comment by mccoys** [comment]
Mean_velocity can be set as a profile maybe? Isn't it the case already?

**Comment by Z10Frank** [comment]
Sure, they can be profiles, but aren't they the x,y,z components of velocity? What I mean is that the code should offer also the possibility of defining the vx and vr profiles

**Comment by mccoys** [comment]
But if you can define profiles of vx vy and vz as a function of x,y and z, it is equivalent right?

**Comment by Z10Frank** [comment]
Yes, but in `AMcylindrical` the profiles are function of only `x` and `r`, or not?

**Comment by mccoys** [comment]
I believe that profiles are always function of x, y and z. Even in AM.

**Comment by Z10Frank** [comment]
If I define them as function of x, y, z I obtain the error: `Profile `mean_velocity[0] eon` has 3 arguments but requires 2`

**Comment by beck-llr** [comment]
You probably have to go through a numpy array to define each single particle in order to do that. Then you can specify the 3 Cartesian components of the velocity for each particle.

**Comment by Z10Frank** [comment]
@beck-llr : yes, precisely. 
This can be particularly cumbersome at the initialisation (and when reading the smiley.py during postprocessing).
I think in AM it would make sense to have also the possibility of defining the cylindrical components for the initial velocity.

**Comment by mccoys** [comment]
Ok I have to go through the code but this part is not well documented. The number of coordinates in a profile is nDim_field, but I thought it would be nDim_particles for the particle profiles. @beck-llr any idea why?

**Comment by beck-llr** [comment]
It makes perfect sense. The `mean velocity` is a correction of the momentum applied identically to all particles of a cell which otherwise have a mean velocity of 0. In AM geometry cells only have 2 coordinates therefore the mean velocity profile must be 2D.

@Z10Frank What you are suggesting is technically possible  but requires to give up the assumption that all particles of the same cell have the same correction applied to their momentum and that this correction is now also function of the particle position.

**Comment by Z10Frank** [comment]
@beck-llr yes, for example with a radial mean velocity correction, the particles in the same cell would have the same radial velocity `vr`, but `vy` and `vz` components depending on their angle `theta`.

**Comment by Z10Frank** [comment]
Yes, that would be perfect if feasible.

**Comment by mccoys** [comment]
Done since 3f5b0f8b38e6
