### ISSUE TITLE
Export TrackParticles to VTK without sorting

### ISSUE THREAD

**Issue by Z10Frank** [SmileiPIC/Smilei#602]
Sometimes one needs to export to VTK the macro-particle coordinates from the `TrackParticles` of just one iteration from a large simulation.

In this case it is not really practical to sort the particles before (waiting the ordered file that may be of hundreds of GB) and then export only one iteration.

Also when exporting all the timesteps, sometimes it is not necessary to sort the particles, since only the coordinates (and not necessarily the trajectories) may be of interest.

Would it be possible to implement an export to VTK for this diagnostic without the need to sort the macro-particles?

**Comment by XiangTangUSTC** [comment]
Hi @Z10Frank 
For your question, I think you might consider using Python to read the H5 file directly and then export the read data to VTK.

**Comment by XiangTangUSTC** [comment]
Hi Developer
I also had a problem with particle diagnostics. I want to track the example tracks, but reading data using the happi module requires sorting the particle information. The sorted file size is beyond my tolerance.
Now I'm going to use Python to write a script that satisfies my needs without sorting. Is there any other way to solve the problem skillfully?

**Comment by mccoys** [comment]
@XiangTangUSTC Please use the [chat room](https://app.element.io/#/room/!LQrdVpOJEohPSWMlmf:matrix.org) for general questions. Also check the `sort=False` option to see if it matches your requirements.

**Comment by mccoys** [comment]
This is fixed in 1631707f0eaf35ce1

For now, it is available only in the branch `develop`
