### ISSUE TITLE
Parameter time_frozen set, but collisions occur, however only inside some of the patches

### ISSUE THREAD

**Issue by pjujeczko** [SmileiPIC/Smilei#603]
Hello,

In benchmark files for collisions (e.g. Maxwellianization1.py) there is time_frozen set to a high value for particles (electrons). At the same time in BinaryProcesses.cpp, line 181 there is an if to check if we collide particles (collisions occur when simulation time is above time_frozen):
`
    if( itime < timesteps_frozen_ || itime % every_ != 0 ) {
        return;
    }`

I have added a warning after this statement and I see that despite that time_frozen is set, the simulation actually enters collisions algorithm, but only for several patches (0,6,7 of 8 patches in one of my cases). I'm not an expert on the whole code, but I would expect at least that each of the patches behaves in the same way. So maybe that's a bug? 

Regards,
Pawel

**Comment by mccoys** [comment]
Did you specify the time_frozen in the collisions block?

**Comment by mccoys** [comment]
Ha I believe that those benchmarks actually do not prevent collisions. They prevent the effect of EM fields only.

To prevent collisions, time_frozen must be added in the collisions block.

**Comment by pjujeczko** [comment]
Yes, you are right (it's written explicitly in the docs, sorry for that). Now I found that the problem occurs only if I add another neutral type of particles:
`
Species(
    name = 'neutrals',
    position_initialization = 'random',
    momentum_initialization = 'cold',
    particles_per_cell = 1,
    mass = 1800.,
    charge = 0.,
    number_density = .5e9,
    boundary_conditions = [
        ['periodic', "periodic"],
    ]
)`

to that Maxwellianization1.py
