### ISSUE TITLE
OSError while using happi

### ISSUE THREAD

**Issue by mlyto** [SmileiPIC/Smilei#604]
Hello,

I am using shared library my_lib.so to calculate myPrescribedProfile in my namelist. It seems to work when I run the code on a supercomputer.
Then I download the results so I can process them on my local machine. However, when I use happi to open my results, I got

OSError: ./my_lib.so: cannot open shared object file: No such file or directory

Meanwhile, this file is in the same directory as the namelist and all the results. It was compiled on the supercomputer.
I also have the happi module installed on my local computer and everything works correctly in my other projects with namelists not using the shared library.

Could you please help me. Thank you.

**Comment by mccoys** [comment]
You cannot use locally a library compiled elsewhere. It has to be compiled for your computer

**Comment by mlyto** [comment]
> You cannot use locally a library compiled elsewhere. It has to be compiled for your computer

Thank you for your reply. Yes, I compiled my shared library on the supercomputer where I run simulations. And for post-processing with happi I tried to use both .so files - (i) compiled on the supercomputer and (ii) compiled on my local laptop. Unfortunately, both methods didn't work. Did I miss anything else?

**Comment by mlyto** [comment]
Here's what I got specifically when I tried post-processing with happi and my_lib.so compiled for my computer:
Traceback (most recent call last):
  File "my_post_process.py", line 70, in <module>
    S = happi.Open('results', show=True)        # Open the simulation
  File "/home/my_dir/Documents/PIC_Smilei/Smilei/happi/__init__.py", line 36, in Open
    return SmileiSimulation(*args, **kwargs)
  File "/home/my_dir/Documents/PIC_Smilei/Smilei/happi/_SmileiSimulation.py", line 55, in __init__
    self.reload()
  File "/home/my_dir/Documents/PIC_Smilei/Smilei/happi/_SmileiSimulation.py", line 158, in reload
    self.namelist, ndim_fields, ndim_particles, cell_length, ncels, timestep, reference_angular_frequency_SI = self._openNamelist(path)
  File "/home/my_dir/Documents/PIC_Smilei/Smilei/happi/_SmileiSimulation.py", line 80, in _openNamelist
    exec(open(path+self._os.sep+'smilei.py').read(), namespace) # execute the namelist into an empty namespace
  File "<string>", line 1504, in <module>
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./my_lib.so: cannot open shared object file: No such file or directory

**Comment by mccoys** [comment]
I guess you don't have the library in the correct directory. Try to have the library path given as an absolute path.

**Comment by mlyto** [comment]
> I guess you don't have the library in the correct directory. Try to have the library path given as an absolute path.

To be honest, I don't understand why happi cares about this library at all. I do provide the path on the supercomputer when I do my simulations. And I don't provide access to this library in the post-processing script. I don't even know where (and why) I should put the library path on the post-processing stage. Could you please clarify this for me?

**Comment by iltommi** [comment]
It's probably related to the fact that happy reads the `smilei.py` created in the simulation folder.
In this file you have a bunch of python code than your `.py` and then another bunch of python commands.
You might want to change it and remove the offending commands in that file.  But it's a bit of an hack.

**Comment by mlyto** [comment]
> It's probably related to the fact that happy reads the `smilei.py` created in the simulation folder. In this file you have a bunch of python code than your `.py` and then another bunch of python commands. You might want to change it and remove the offending commands in that file. But it's a bit of an hack.

Yes, you are probably right, `smilei.py` is the source of this `my_lib.so` call. I'd appreciate it if anyone knows how to prevent this behavior in the happi module, as I still don't understand why I need this call to process .txt and .h5 result files.

**Comment by iltommi** [comment]
Since a smilei namelist is a valid python code, Happi parse that to retrieve the simulation parameters without having to write everything in .h5 files
Concerning the possible solutions, I guess it depends what you're doing. 

If this is just a couple of lines, like
```
from ctypes import cdll
mylib = cdll.LoadLibrary('./my-library.so')
mylib.call_my_function('myFunction')
```

one solution (hacky) might be to enclose the "offending commands" into something like:

```
import sys
if 'happi' not in sys.modules:
    print("this will appear in the simulation but not in happi")
    from ctypes import cdll
    mylib = cdll.LoadLibrary('./my-library.so')
    mylib.call_my_function('myFunction')
else:
    mylib=None

```

**Comment by mccoys** [comment]
There is also a `preprocess` function that can be used for task required in the simulation, but not in happi

**Comment by mlyto** [comment]
> one solution (hacky) might be to enclose the "offending commands" into something like:

This solution works. Thank you!

**Comment by iltommi** [comment]
> There is also a `preprocess` function that can be used for task required in the simulation, but not in happi

Ah, right! I forgot there was a solution. 
Bonus point: it's written in the docs: https://smileipic.github.io/Smilei/Use/namelist.html#python-workflow

**Comment by mlyto** [comment]
> There is also a `preprocess` function that can be used for task required in the simulation, but not in happi

When I tried to modify my smilei.py by putting all library stuff within preprocess() I got `invalid syntax`.

**Comment by iltommi** [comment]
Here is an example: https://github.com/SmileiPIC/Smilei/blob/master/benchmarks/tst1d_06_profiles.py

**Comment by mlyto** [comment]
> Here is an example: https://github.com/SmileiPIC/Smilei/blob/master/benchmarks/tst1d_06_profiles.py

Oh, I see. Thank you again!
