### ISSUE TITLE
smilei : numpy not found. 

### ISSUE THREAD

**Issue by jcwright77** [SmileiPIC/Smilei#605]
## Description

Simulations run but results are empty. That is nothing evolves, fields are zero, distributions unchanged except for some MC noise.

smilei_test passes
when smilei is run it complains that 
[WARNING](0) src/Params/Params.cpp:108 (Params) Numpy not found. Some options will not be available

Using python venv with numpy installed.

```
If available, copy-paste faulty code, warnings, errors, etc.
```

## Steps to reproduce the problem

If relevant, provide a step-by-step guide

## Parameters

- Smilei version : brew install   --HEAD iltommi/brews/smilei
- Input file two_stream_1d.py from tutorial
- Commands or script used to run the faulty simulation : smilei two_stream_1d.py
- Computing resources
  - type of computer macbook M1 Max
  - OS OSX13
  - C++ compiler (to get some information `g++ --version`)
  - MPI version (`mpic++ --version`, `mpic++ -show`)
  - HDF5 version (`h5cc --version`)
  - Python version (`python --version`)
  - ...

**Comment by jcwright77** [comment]
smilei seems to ignore the python in the venv and use one installed by homebrew. That one also has numpy installed. Tried reinstalling smilei but same result.

**Comment by mccoys** [comment]
Numpy is optional so you should have results. Which fields are zero?

**Comment by jcwright77** [comment]
Running thermal_plasma_1d.py
Then  loading:
# minus the electron density
ne = S.Field(0,'-Rho_eon', label="e- density")
# ion density
ni = S.Field(0,'Rho_ion', label="ion density")
# Ex field
ex = S.Field(0,'Ex', label="Ex field", vmin=-0.25,vmax=2)
# plotting
happi.multiSlide(ne,ni,ex)

Ion density is constant at 1.
Ex is zero
electron density fluctuates between 0.75 and 1.25

Ex is not identically zero but fluctuates between +- 0.005

Plotting binning at beginning and end shows the same number density distribution aside from small fluctuations. x axis from 0 to 0.001, peaked at 0.0001 and falling almost linearly on the log plot from there.

Running two_stream_1d.py is more interesting and seems to work developing a nice phase space and electric field.

Maybe I am misunderstanding what the thermal 1D plasma is supposed to show? Otherwise it seems to be working .

**Comment by mccoys** [comment]
As the name suggest, it is simply a plasma at a given temperature. The idea is to show the temperature is stable unless the resolution is too coarse.
