### ISSUE TITLE
ionization of molecules and charge exchange possibility

### ISSUE THREAD

**Issue by ZippoFight** [SmileiPIC/Smilei#606]
Hi, I noticed the collisional ionization process is considered based on the method in [Perez2012]. If I understand correctly, this method only applies to atomic ionization, so is it possible to model impact ionization of molecules like hydrogen (H2) and nitrogen (N2)? 

Another thing I am interested in is the charge exchage process between ions and molecules, like Cu ions with hydrogen. Is this possible in Smilei?

**Comment by mccoys** [comment]
This is not currently possible. There is not even the consideration of molecules in smilei as it is devoted to plasma (hot enough to have only ions)
