### ISSUE TITLE
An error when submitting a 3D simulation on the HPC

### ISSUE THREAD

**Issue by jcyu96** [SmileiPIC/Smilei#607]
Hi everyone! I recently encountered a reported error when submitting a 3D simulation on the HPC, does anyone know what I can do to fix this issue? The attachment is my output log and namelist.
[slurm-5955994.txt](https://github.com/SmileiPIC/Smilei/files/10872273/slurm-5955994.txt)
[coil3d00.txt](https://github.com/SmileiPIC/Smilei/files/10872281/coil3d00.txt)

**Comment by beck-llr** [comment]
Could you also share your submission script and some details about the computing resources you are using ? (type of processor, number of cores, memory per node etc.)

**Comment by mccoys** [comment]
You have the error
```
KILLED BY SIGNAL: 9 (Killed)
```
which normally means a lack of memory.

Try to remove all diagnostics in case that is a diagnostics issue. Otherwise try removing features one by one (antenna, load balancing, species) until you spot the faulty one.

**Comment by jcyu96** [comment]
I should consider using fewer grid cells. Maybe this is the best way to complete my simulation.

**Comment by beck-llr** [comment]
256 is the total number of MPI process you are asking for. Do you have a submission script for that ? Depending on how you submit your job, a different number of compute nodes can be allocated and you probably need many for such a large simulation.
So the first thing is to make sure you have enough nodes for your simulation.

Then also make sure that the total number of openMP threads is equal to the total number of cores you are using. At the moment you are asking for 256*2=512 threads. Maybe you should contact your administrator if I am not clear or if you don't know how many cores per node you have on your cluster. He should be able to explain.
You can also read our documentation on parallelization: https://smileipic.github.io/Smilei/Understand/parallelization.html

**Comment by jcyu96** [comment]
[yjc.txt](https://github.com/SmileiPIC/Smilei/files/10873137/yjc.txt)
Here is my submission script and I will consider your advises carefully.

**Comment by beck-llr** [comment]
Ok so you are explicitly asking for 4 compute nodes which is probably just not enough for a 3D simulation.
I don't know what your `amd_256` partition is but it doesn't sound like an intel Xeon. Make sure with an admin that your number of MPI tasks and openMP threads are correct.  We recommend not to use hyper threading (1 thread per physical core).

**Comment by jcyu96** [comment]
> Ok so you are explicitly asking for 4 compute nodes which is probably just not enough for a 3D simulation. I don't know what your `amd_256` partition is but it doesn't sound like an intel Xeon. Make sure with an admin that your number of MPI tasks and openMP threads are correct. We recommend not to use hyper threading (1 thread per physical core).

Thanks for your patience. Do you mean `export OMP_NUM_THREADS=1` will run faster? For the `amd_256` partition, one node contains 64 cores.

Actually, I still can't determine the optimal threads, tasks, etc. parameters based on pacthes after reading this link: https://smileipic.github.io/Smilei/Understand/parallelization.html 
Can you give me an example of how to set the optimal parallelism parameters with my namelist, and explain how you think about it?

**Comment by mccoys** [comment]
You have to try different options, knowing that your processor likely has 32 cores.. 
Start with `export OMP_NUM_THREADS=32` to have 32 cores bound to 1 mpi, and set the number of mpis so that the total number of cores is what you need. For example if you want 4 nodes, this means 4x32 cores in total. Then you need 4 mpis.
Next, without changing the number of nodes, choose 8 mpis, but set `export OMP_NUM_THREADS=16` so that the total number of cores is constant.
Change again until you reach `export OMP_NUM_THREADS=1`.

With all these attempts you should be able to find the optimal configuration

**Comment by jcyu96** [comment]
Do you mean that I need to change the parameters in the submission script as follows:

from
```
#!/bin/bash
#SBATCH -N 8
#SBATCH -p amd_256
#SBATCH -n 512
#SBATCH -t 3600

export OMP_NUM_THREADS=32
mpirun -np 16 ./../../Smilei/build/smilei coil3d00.py
```
to
```
#!/bin/bash
#SBATCH -N 8
#SBATCH -p amd_256
#SBATCH -n 512
#SBATCH -t 3600

export OMP_NUM_THREADS=16
mpirun -np 32 ./../../Smilei/build/smilei coil3d00.py
```
Keep changing parameters `OMP_NUM_THREADS` and `-np` like this to find the optimal configuration. Not sure if my understanding is correct?

**Comment by jcyu96** [comment]
I tried it and found that I should need to change parameters `--ntasks-per-node` and `--cpus-per-task` in the submission script, `OMP_NUM_THREADS` doesn't seem to work. I will continue to test different configurations.

**Comment by mccoys** [comment]
It is likely that "tasks" means MPI process. Thus `ntasks-per-node` is the number of MPI per node, and `cpus-per-task` is the number of cores per MPI. But you should read the documentation of SBATCH for details

**Comment by mccoys** [comment]
@jcyu96 Have you manage to find a good configuration? If so, please close this issue
