### ISSUE TITLE
Load external density profile with moving window simulations

### ISSUE THREAD

**Issue by noreasonatall1** [SmileiPIC/Smilei#610]
Hi! I'm having troubles initializing the `number_density` from external file when trying to do simulations with moving window. Am I inventing the wheel here? Is there a simple solution? 

Here's my attempts at it.
Everything works perfectly fine if the window is static. I just load the 2D array of densities with the size of SMILEI grid.
```
Species(
        ...
	number_density="/Some_path/Some_filename.h5/ni", 
        ...
)
```
The trouble starts when the window is moving. First I did try to load the `number_density` with longer x dimension, but it obviously did not work. The second solution did work in some capacity, but I'm failing to understand some nuances. Here's what I did.

1. Loaded the initial density profile directly in the namelist. The result is that now I have three 1D arrays of x,y, and ni.
```
filename="sample_ni.txt"
f = open(root+filename, "r")
...
x1d=x_2d_full.ravel()
y1d=y_2d_full.ravel()
ni1d=ni_2d_full.ravel()
```
2. Created a function that returns the density in any required point via interpolation and used it to define `number_density`. The code was tested and works correctly on my PC. 
```
def f(x,y):    
    return float(scipy.interpolate.griddata((x1d,y1d), ni1d,(x,y), method='cubic', fill_value=0.)) #works without the float() as well
```
```
Species(
        ...
	number_density=f, 
        ...
)
```
This simulation ran and finished, although with ~1 hour initialization time (it gets stuck on `Species` and `Patches`). The delay is obviously due to interpolation, but it works relatively fast on PC? 
Still worth the time and memory saved on the simulation itself, though. 

So interpolation did work, but when doing it for the first time I forgot to account for units of `l0`, therefore the density scale was `2*np.pi` times smaller. Scaling x and y properly, I got the simulation crashed with C warnings.
```
x1d=l0*x_2d_full.ravel()
y1d=l0*y_2d_full.ravel()
```
```
timestep       sim time   cpu time [s]   (    diff [s] )   push time [ns]
double free or corruption (!prev)
double free or corruption (!prev)
double free or corruption (!prev)
double free or corruption (!prev)
double free or corruption (!prev)
double free or corruption (!prev)
double free or corruption (!prev)
double free or corruption (!prev)
```
Do you have any idea on what caused this error and how to fix it? Or any better solutions to the problem itself?
Thank you in advance!

**Comment by beck-llr** [comment]
Hi
For interpolation I suggest to create an interpolator once and for all (for instance with `scipy.interpolate.RegularGridInterpolator` but there are many kinds) and then use this interpolator function directly as your number density.

Also try to use interpolation methods adapted to your data. If you have a structure, regular data to interpolate, it is very costly and inefficient to use an interpolation supporting unstructured mesh.

I hope this helps.

**Comment by beck-llr** [comment]
Thanks for the detailed feedback and glad it is working for you now. Cheers.
