### ISSUE TITLE
LaserPlanar1D and Prescribed field

### ISSUE THREAD

**Issue by mlyto** [SmileiPIC/Smilei#616]
Hello everyone,
I expected the following two ways to set up the laser to be equivalent, but my tests have shown that this is not the case: even in a vacuum (before entering the plasma region), there is a shift between these waves:

1) through the laser creator

LaserPlanar1D(
    box_side         = "xmin",
    a0               = a0,
    omega            = 1.,
    polarization_phi = 0.,
    ellipticity      = 0.,
    time_envelope    = tgaussian(start=0,duration=Tsim,fwhm=fwhm,center=center,order=2)
)

2) through the prescribed field

def myPrescribed_Ey(x,t):
    efield_y = a0 * sin(x - t + center) * 2.0**(-(2. * (x - t + center)/fwhm)**2)                 
    return efield_y 

def myPrescribed_Bz(x,t):
    bfield_z = a0 * sin(x - t + center) * 2.0**(-(2. * (x - t + center)/fwhm)**2)
    return bfield_z

Maybe someone knows in what form PrescribedProfile should be taken so that the result matches with LaserPlanar1D?

Thank you.

**Comment by mccoys** [comment]
Why would you like prescribed fields? They are not for normal use of a pic code as they are not self consistent.

**Comment by mlyto** [comment]
Yes, I know that the prescribed field is only used as a pusher. However, it seems that the propagation profiles before entering the plasma region should be equivalent. Am I wrong?

**Comment by mlyto** [comment]
> Why would you like prescribed fields? They are not for normal use of a pic code as they are not self consistent.

Say, in the case when the prescribed field is self-consistent (as in the example above), we can consider it as an incident field, and the reaction of the medium as a scattered field. Can we do this using  Smilei?

**Comment by mccoys** [comment]
It is not possible. That would not be a self-consistent field by definition.

**Comment by mlyto** [comment]
Why? The self-consistent system of Vlasov-Maxwell equations allows us to divide the EM field into incident and scattered parts (for linear or weakly nonlinear cases). The incident field (self-consistent in a vacuum) is only meant to push particles, which is the same option that provides the prescribed field in Smilei.

**Comment by mccoys** [comment]
It only works approximately, and it practice you need an extremely dilute plasma to make it work. PIC codes typically require very accurate self-consistent fields, to stay stable. The only case in which I have seen prescribed fields be any use is when all particles are only test particles (they do not deposit currents on the grid so they are completely transparent).

**Comment by mlyto** [comment]
> It only works approximately, and it practice you need an extremely dilute plasma to make it work. PIC codes typically require very accurate self-consistent fields, to stay stable. The only case in which I have seen prescribed fields be any use is when all particles are only test particles (they do not deposit currents on the grid so they are completely transparent).

Thank you for your explanation.

**Comment by mccoys** [comment]
Considering your initial question, there is a delay for the phase introduced in LaserPlanar1D. 

See here
https://github.com/SmileiPIC/Smilei/blob/b937c1524a7c08433ea461b6b2a6437eaa852420/src/Python/pyprofiles.py#L470

**Comment by mlyto** [comment]
> Considering your initial question, there is a delay for the phase introduced in LaserPlanar1D.
> 
> See here
> 
> https://github.com/SmileiPIC/Smilei/blob/b937c1524a7c08433ea461b6b2a6437eaa852420/src/Python/pyprofiles.py#L470

Thank you. Indeed, there is a 'dephasing' parameter, but for polarization_phi=0 and ellipticity = 0 it should be 0 unless atan2(0,0) gives something weird.

**Comment by mccoys** [comment]
It's this a circular instead of a linear polarization you have defined though? How much is the delay?

**Comment by mlyto** [comment]
In my simulations it's a linear polarization. The delay I found was about ~6*dx. It is not accumulation, but present from the very beginning.

**Comment by mccoys** [comment]
Check first whether you are creating a circular polarization

**Comment by mlyto** [comment]
I can create a circularly polarized pulse with a Gaussian envelope using LaserPlanar1D(...), but again this solution does not match the analytical solution or the prescribed field in vacuum. What should be an analytical solution, which corresponds 

LaserPlanar1D(
box_side = "xmin",
a0 = a0,
omega = 1.,
polarization_phi = 0.,
ellipticity = 1.,
time_envelope = tgaussian(start=0,duration=Tsim,fwhm=fwhm,center=center,order=2)
)

in vacuum?

**Comment by mlyto** [comment]
> Check first whether you are creating a circular polarization. I mean with prescribed fields. B and E have 0 phase shift it seems

I can create a circularly polarized pulse with a Gaussian envelope using LaserPlanar1D(...), but again this solution does not match the analytical solution or the prescribed field in vacuum. What should be an analytical solution, which corresponds

LaserPlanar1D(
box_side = "xmin",
a0 = a0*sqrt(2),
omega = 1.,
polarization_phi = 0.,
ellipticity = 1.,
time_envelope = tgaussian(start=0,duration=Tsim,fwhm=fwhm,center=center,order=2)
)

in vacuum? I though it is
efield_y = a0 * sin(x - t + center) * 2.0**(-(2. * (x - t + center)/fwhm)2)
efield_z = a0 * cos(x - t + center) * 2.0(-(2. * (x - t + center)/fwhm)2)
bfield_y = -a0 * cos(x - t + center) * 2.0(-(2. * (x - t + center)/fwhm)2)
bfield_z = a0 * sin(x - t + center) * 2.0(-(2. * (x - t + center)/fwhm)**2)

but I always see a shift between the Laser and analytical solutions

**Comment by mccoys** [comment]
Ok sorry i misread your equations.

If you want to investigate the delay issue, here is where the calculation occurs
https://github.com/SmileiPIC/Smilei/blob/b937c1524a7c08433ea461b6b2a6437eaa852420/src/ElectroMagn/Laser.cpp#L462

I think the delay should be 0 if the phase is 0. 

What is delayed though? Is it the center of the gaussian that is delayed? Or the phase?

**Comment by mlyto** [comment]
> What is delayed though? Is it the center of the gaussian that is delayed? Or the phase?

Both of them. I need to use different correction values for the phase and the gaussian parts to get the analytical solution to match the Smilei laser solutions. Shift appears from the very beginning and does not grow over time (in the case of propagation in a vacuum). I don't see if I can add an example graph here

**Comment by mccoys** [comment]
Yes you should be able to add a figure here if you wish.

You could try to use your own gaussain function instead of tgaussian to see if the problem is there

**Comment by mlyto** [comment]
![shift](https://user-images.githubusercontent.com/74987705/230777985-4229dfed-8153-4a44-a584-e72a0ab90201.png)

**Comment by mlyto** [comment]
if i subtract pi/2 from phase and gauss argument it fits better but still not perfect:
![minuspi_2](https://user-images.githubusercontent.com/74987705/230778639-b7ae3a7f-81fa-4a11-ada8-6505718459b9.png)

**Comment by mccoys** [comment]
Then it is probably pi/2 that is correct. The fields that are set by LaserPlanar1D are the B fields

**Comment by mlyto** [comment]
> Then it is probably pi/2 that is correct. The fields that are set by LaserPlanar1D are the B fields

Yes, I know that in Laser(...) should be By and Bz profiles, but I computed with LaserPlanar1D(...) like (for the CP case)

LaserPlanar1D(
box_side = "xmin",
a0 = a0,
omega = 1.,
polarization_phi = 0.,
ellipticity = 1.,
time_envelope = tgaussian(start=0,duration=Tsim,fwhm=fwhm,center=center,order=2)
)

For diagnostics, I saved Ex, Ey and Ez. Also, even with pi/2 shift it's not perfect, say shift = pi/2-dx works a bit better for phase but still not perfect for amplitude, see
![new_shift](https://user-images.githubusercontent.com/74987705/230791498-12a962e9-770b-4247-9d68-28eca110966f.png)
I asked because I thought this case should be tested first, but I haven't seen anything like this in benchmarks, and my own simulations didn't show convergence in a vacuum.

**Comment by mccoys** [comment]
If you want perfect agreement you need to account for:
- grid discretization: E fields are not all at the same points, as the Yee grid is staggered. And the wave propagation on a discrete grid is not exactly that of a continuous vacuum anyways
- time discretization: this is equivalent, in some sense to grid discretization
- boundary conditions: the injection scheme is imperfect and there are some possible artifacts
- reflection from other boundary at late times

Probably other things I forgot

**Comment by mlyto** [comment]
> If you want perfect agreement you need to account for:

Thanks a lot for this list. I appreciate your help very much.
