### ISSUE TITLE
Using getAxis() for a moving window

### ISSUE THREAD

**Issue by balcon13** [SmileiPIC/Smilei#618]
Hi, I am trying to access the true x axis of a simulation which uses a moving window using the `moving=True` argument in the Field diagnostic.

If I use `S.Field.Field0("-Rho", units = ["um", "ps", "C/cm^3"], moving=True).plot()`, it works fine and I can see the 'real' units on the x axis. However, if I try and access the axis information using `getAxis()` then the `moving=True` argument doesn't seem to do anything.

i.e. `S.Field(0, "-Rho", moving=True, units=units).getAxis("x", timestep=timestep) == S.Field(0, "-Rho", units=units).getAxis("x", timestep=timestep)`

Is there a reason this is the case ? Maybe I am missing something. 

Kind regards.

**Comment by mccoys** [comment]
This should now be fixed in the develop branch
