### ISSUE TITLE
Performance degradation between two machines

### ISSUE THREAD

**Issue by kihangyoun** [SmileiPIC/Smilei#619]
Hi All,
I am just going to ask questions related to a performance difference between two computing systems.
To make a long story short, I have migrated smilei from a machine A to a machine B.
A: Xeon Scalable 6148 40C, Turbo 3.7GHz
B: Xeon Platinum 8360Y 72C, Base 2.4GHz
And I have ran smilei with same inputs on two systems and I got profile data as below.

```
Machine      A       B
Total       38K     94K
Particle    7K      7K
Maxwell     10K     5K
Diagnostics 9K      38K (seriously bad)
Sync Part   1K      1K
Sync Field  0.8K    0.6K
Sync Dens   8K      11K
Grids       0K      29K (seriously bad)
```

I am wondering the reason the performance diff. between two machine on Diagnostics and Grids.
Any advices or suggestions to figure out(eg. That's maybe because some I/O issues, or Communication Issues?)

**Comment by mccoys** [comment]
The diagnostics are usually limited by the disk access which might be lower quality or badly configured. It could be also some obscure hdf5 configuration

I don't know what is the Grids line. Is this what smilei outputs?
