### ISSUE TITLE
Happi performances

### ISSUE THREAD

**Issue by beck-llr** [SmileiPIC/Smilei#622]
Several performance bottlenecks of Happi have been identified in the case of thousands of simulations being processed. A couple of possible improvements are considered.

- [x] Opening a Smilei namelist can be expensive.

A solution would be to propose an optimized opening mode where only the minimal information necessary to the opening of the diagnostics is retrieved from a file gathering these information in a compact format and created at runtime.

- [x] Opening Track and Probe diagnostics triggers many expensive `H5Oopen` calls from h5py.

Hadrien may propose a PR in which calls to this fonction are limited for Trackparticles. The principle would be to reuse as much as possible already opened objects.
For probes a possible improvement would to allow to `changeField` without reopening the whole diagnostic.
Other leads of possible improvements are the use of H5py `References`(a feature dedicated to efficient utilization of already opened structures) and using the latest versions of python 3.11 which supposedly could enhance performances.

- [x] Having pint installed on the system significantly reduces Happi's performances.

 Protection against this effect if pint is not called by the user is necessary.

**Comment by HadrienG2** [comment]
Finalement, j'ai trouvé un temps mort pour faire le profil avec pint aujourd'hui:  [pint.json.tar.gz](https://github.com/SmileiPIC/Smilei/files/11295343/pint.json.tar.gz), du coup je peux te faire l'explication.

En gros, toutes les grosses opérations happi (Open, TrackParticles, Probe...) finissent par faire un appel à [Diagnostic.__init__()](https://github.com/SmileiPIC/Smilei/blob/b937c1524a7c08433ea461b6b2a6437eaa852420/happi/_Diagnostics/Diagnostic.py#L14). Au sein de ce constructeur, il y a [un appel à `self.units.prepare()`](https://github.com/SmileiPIC/Smilei/blob/b937c1524a7c08433ea461b6b2a6437eaa852420/happi/_Diagnostics/Diagnostic.py#L68), et au sein de cette fonction prepare, il y a [un appel à `self.UnitRegistry()`](https://github.com/SmileiPIC/Smilei/blob/b937c1524a7c08433ea461b6b2a6437eaa852420/happi/_Utils.py#L320) où la quasi totalité du temps est passé.

Si on regarde au niveau de l'implémentation de pint, on se retrouve ensuite par un chemin un peu compliqué dans une méthode de classe de base [`PlainRegistry.load_definitions()`](https://github.com/hgrecco/pint/blob/0.20.1/pint/facets/plain/registry.py#L519) qui charge des définitions d'unités et de préfixe depuis un fichier, et il s'avère que le parsing de ce fichier est coûteux.

**Comment by HadrienG2** [comment]
One thing to be careful about is that Units.prepare() then goes on to modify the UnitRegistry it created. So with this proposed design change, it would probably be best so start by making a local copy of the global initialized unit registry before modifying that copy. Is it easy to do this? (I have vague memories of Python using reference semantics in a way that makes object copies a bit complicated)

**Comment by HadrienG2** [comment]
Also, re. TrackParticles/Probe being expensive, one thing we discussed is whether it would be worth it to put a quick note about it in the docs, encouraging users to keep these objects around and reuse them.

**Comment by mccoys** [comment]
@HadrienG2 I did some changes for all the items above. Could you run your workload again and see if it helped?

**Comment by HadrienG2** [comment]
By itself, switching to the develop branch only leads to the ~10% improvement of #623 wrt to previous mster, but from the happi master..develop diff that's expected: most of the improvements require changes to the PALLAS analysis code in order to be leveraged.

From the diff, the other performance-relevant changes that I would expect (correct me if I'm wrong) is:

- A fix to the pint duplicate initialization slowdown. Unfortunately, this is not it: having pint around still results in an enormous slowdown, and quick profiling shows that pint is still re-initialized every time a Diagnostic is created.
- Faster namelist loading via pickle files, whose opening is triggered by a `scan=True` parameter. Obviously, the pickle files are not there in my test dataset, which was generated before this change, so I cannot test this yet. What should the PALLAS team do to produce a dataset that includes them?
- It should now be possible to change Probe fields with Probe.changeField. I'm gonna try this out and see if it helps as much as hoped :)

**Comment by HadrienG2** [comment]
Using Probe.changeField to avoid duplicate Probe creation results in another 8% speedup.

**Comment by mccoys** [comment]
Concerning Pint, I forgot to add an option to completely disable the usage of the module. For now, it only calls the module once per simulation.

The pickle file will be automatically generated in future simulations. I did not provide a tool to create it from previous simulations, but I guess it can be done. I have not tried, but something along these lines (in the repertory of a given simulation):
```python
import happi
happi.openNamelist('.')._writeInfo()
```

**Comment by mccoys** [comment]
About Pint again. Sorry for the confusion. I really did not make the system better as pint is called for every diagnostic. I will make new changes.

**Comment by HadrienG2** [comment]
I also tried this...

> ```python
> import happi
> happi.openNamelist('.')._writeInfo()
> ```

...but it seems you need to point to the namelist file, not directory, and then this happens:

```
>>> happi.openNamelist('namelist_env_ii_4p7-rps.py')._writeInfo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Namelist' object has no attribute '_writeInfo'
```

There is indeed no `writeInfo` in sight in either the happi source code or the namelist files, but I did find one that looks right inside Smilei/src/Python/pycontrol.py, along with comments that suggest this should be appended at the end of user namelists. I guess either happi is not picking this up for some reason, or perhaps it's picking up the wrong version of it from some previous version of smilei?

**Comment by mccoys** [comment]
Ah. I forgot that the function openNamelist does not import names beginning with _. As a temporary workaround, you could remove the _ or make your own version of the _writeInfo function

**Comment by mccoys** [comment]
Ok now I pushed a version where Pint is initialized only once per simulation. It also has the option `pint=False` to avoid Pint completely.

**Comment by beck-llr** [comment]
@mccoys I think you also have implemented an optimized way of opening a simulation now (without re executing the whole namelist). Is this documented somewhere ?

**Comment by mccoys** [comment]
It is not documented as it does not require anything to be done. Just run any simulation and check the new `info.pickle` file

**Comment by HadrienG2** [comment]
> Ah. I forgot that the function openNamelist does not import names beginning with _. As a temporary workaround, you could remove the _ or make your own version of the _writeInfo function

With this change, I can now produce the pickle files and get to a different kind of failure from the PALLAS job:

```
$  python3 postprocess_1step_randomscan_sp.py
Number of configuration :        111 

--------------------------------------------

Post-processing timeStep :       -1
--------------------------------------------

loading data ...         n/Config_22/ 

Traceback (most recent call last):
  File "/home/hadrien/Software/LPAbrew/postprocess/postprocess_1step_randomscan_sp.py", line 188, in <module>
    tmp = getSimData(files[f],timeStep)
  File "/home/hadrien/Software/LPAbrew/postprocess/postprocess_1step_randomscan_sp.py", line 83, in getSimData
    Config = tmp.namelist.external_config['Config']
AttributeError: 'Namelist' object has no attribute 'external_config'
```

For reference, if I open one of the namelists, this `external_config` is defined like this:

```python
# ... lots of stuff ...

####################### External configuration (feeded by jobrunner.py) #################
# uncomment for test

# external_config = {'p_1':40., 'a_0':1.23,'x_of':1100.,'c_N2':0.12}

# range for various parameter
#       a_0 : 1.00 -  1.45
#       c_N2 : 0.001 - 0.15
#       x_of : 100 - 1500 [um] focus offset respect to x_2                 
# if Gaussian beam 
#       p1: 30 - 120 [mbar]
# if FGB 
#       p1: 30 - 60 [mbar]


# External_config

external_config = {'x_of': 1749.4892587070713, 'c_N2': 0.07649500782404901, 'a_0': 1.3322045242364569, 'Config': 22.0, 'p_1': 38.032218106736266}

# ... more stuff ...
```

No idea if this is a standard Smilei thing that should be added to the list of things to be persistified, or a PALLAS-specific thing.

>> @mccoys I think you also have implemented an optimized way of opening a simulation now (without re executing the whole namelist). Is this documented somewhere ?
>
> It is not documented as it does not require anything to be done. Just run any simulation and check the new info.pickle file

Creation of the pickle file is automatic, but to use it, you need to pass a `scan=False` parameter to happi.Open(). It would be nice if happi could autodetect the presence of the pickle file and use it in that case / try to generate it if it's not there, but I could also easily see that leading into some surprising behavior (if e.g. input files are on read only storage).

**Comment by HadrienG2** [comment]
> Ok now I pushed a version where Pint is initialized only once per simulation. It also has the option `pint=False` to avoid Pint completely.

Effects on timings for the PALLAS job:

* Pint not installed or pint=False: 13.9s
* Current develop branch: 69.0s
* Previous develop branch (with one pint initialization per diagnostic): 185s

Clearly, you'll still want to use `pint=False` for this sort of batched simulation processing that does not benefit from fancy unit management. But at least when you do use pint, it's ~3x faster :)

**Comment by mccoys** [comment]
The pickle file does not contain as much info. It is better to avoid using it by default. Only use it when performances are needed. In fact it does not include user variables, but only those used by smilei. And only numbers, strings, or lists of these. I am a little concerned about writing all user variables in the pickle file, as these variables are potentially large.

In your case, do you have a potential workaround?

**Comment by mccoys** [comment]
I see 3 solutions:
* You change your namelists so that they write their own pickled file (for instance using the function `preprocess`, see [here](https://smileipic.github.io/Smilei/Use/namelist.html#python-workflow))
* I change the way the pickled file is written so that it includes more things, like user-defined variables, as long as they are simply pickable
* You hack your way using the current code, so that additional variables are pickled. I think it may be possible with `setattr(Main, "var", value)`. Then the `var` should be pickled (dictionaries are not pickled though). But this means changing the namelists and the post-processing.

what is your favorite option?

**Comment by HadrienG2** [comment]
From my perspective, the best option would be option 2. The least people have to do to get reasonable namelist performance, the better.

**Comment by mccoys** [comment]
Ok I pushed a modified version in branch `develop`:
- `_writeInfo` renamed `writeInfo` to make it usable from `happi.openNamelist`
- `pickle` replaced by `shelve` (which is more or less the same)
- global variables are stored as long as they are numbers, strings or booleans, or python structures of these (tuples, lists or dicts). Numpy arrays are not stored. Functions are not stored either.
- All smilei "blocks" are stored, but with the same limitations as global variables.

**Comment by HadrienG2** [comment]
Thanks! Now it's still unhappy, but because it's trying to access a tiny numpy array:

```
$ python3 postprocess_1step_randomscan_sp.py
Number of configuration :        111 

--------------------------------------------

Post-processing timeStep :       -1
--------------------------------------------

loading data ...         n/Config_22/ 

Traceback (most recent call last):
  File "/home/hadrien/Software/LPAbrew/postprocess/postprocess_1step_randomscan_sp.py", line 188, in <module>
    tmp = getSimData(files[f],timeStep)
  File "/home/hadrien/Software/LPAbrew/postprocess/postprocess_1step_randomscan_sp.py", line 91, in getSimData
    x_p = tmp.namelist.xh_p_um
AttributeError: 'Namelist' object has no attribute 'xh_p_um'
```

...declared in the namelist via this code...

```python
begin_upramp    = 65.0                           # um, Position where the upramp starts
Lupramp         = 1000                           # um, Length of the upramp
L_1             = 500                            # um, Length of the plateau 1
Ldownramp       = 300                            # um, Length of downramp
x_1             = begin_upramp + Lupramp         # um, Start of the plateau 1 input/ sf
begin_downramp  = x_1 + L_1                      # um, Beginning of plasma downramp 1->2
L_2             = 900                            # um, Length of plateau 2
x_2             = begin_downramp + Ldownramp     # um, Beginning of plasma plateau 2
begin_outramp   = x_2 + L_2                      # um, Beginning of plasma outramp
Loutramp        = 2500                           # um, Length of the plasma outramp
finish          = begin_outramp +  Loutramp      # um, End of plasma

xh_p_um         = np.array([begin_upramp, x_1, begin_downramp, x_2,  begin_outramp, finish]) 
```

...so I guess I am, after all, going to need some tolerance for small numpy arrays if I am to make the PALLAS team benefit from this development without changing the way they write their namelists... :cry:

**Comment by HadrienG2** [comment]
...and with that it finally works, and the processing time moves from 11.9s (with previous improvements) to 8.6s, or a nice 28% extra perf improvement! Thanks!

I would probably set the max size threshold a little higher in the final version, because if I consider a typical hard drive, data access latencies are a few milliseconds and after that sequential transfer rates are of the order of 100 MB/s, which means that even arrays with tens of thousands of elements take negligible time to read/write with respect to the time it takes to prepare the disk to write/read them. But it's ultimately your choice :)

**Comment by HadrienG2** [comment]
Here's the final profile: [python3-2023-05-11T10:41:35+02:00.json.tar.gz](https://github.com/SmileiPIC/Smilei/files/11450172/python3-2023-05-11T10.41.35%2B02.00.json.tar.gz)

As you can see with [Speedscope](https://www.speedscope.app/) in left-heavy mode, while the processing time remains largely happi-dominated (only 16% of time is spent in code written by the PALLAS team), it is now spent doing things we know we need to do/are supposed be expensive:

- Initializing one TrackParticles and one Probe object, which can subsequently be reused
    * For TrackParticles, the bottleneck remains the h5py-bound x_moved processing step, which as far as I understand cannot easily be removed.
    * For Probe, most CPU time is spent loading various metadata: available times, initial shape... which in turns triggers h5py-intensive processing. This again probably cannot be avoided.
- Loading data via Probe.getData, iterating over it via TrackParticles.iterParticles...
    * From a quick look through the profile and the associated code, nothing stands out as immediately suspicious on the happi side. Of course, h5py itself may be doing suspicious things, but I don't feel like investigating this today ;)

So I think from the perspective of this PALLAS use case, we're good ;)

**Comment by mccoys** [comment]
Ok Thank for the feedback
I set the numpy limit to 10000. Now pushed to the develop branch
