### ISSUE TITLE
Restart issue

### ISSUE THREAD

**Issue by srozario121** [SmileiPIC/Smilei#63]
Hello,
I'm trying to start a simulation from the output of a previous simulation. I have successfully restarted a simulation from two previous checkpoints. However on the third time I obtain a rather odd error.
''
	 READING fields and particles for restart
	[ERROR](0) src/Tools/H5.h:324 (getVect) Reading vector Position-0 is not 1D but -1D
	[ERROR](0) src/Tools/H5.h:324 (getVect) Reading vector Position-1 is not 1D but -1D
	[ERROR](0) src/Tools/H5.h:324 (getVect) Reading vector Position-1 is not 1D but -1D
	[ERROR](0) src/Tools/H5.h:324 (getVect) Reading vector Position-0 is not 1D but -1D
	[ERROR](0) src/Tools/H5.h:324 (getVect) Reading vector Position-0 is not 1D but -1D
	[ERROR](0) src/Tools/H5.h:324 (getVect) Reading vector Position-0 is not 1D but -1D
	[ERROR](0) src/Checkpoint/Checkpoint.cpp:588 (restartPatch) Number of species differs between dump (0) and namelist (3)
	[ERROR](0) src/Tools/H5.h:324 (getVect) Reading vector Position-0 is not 1D but -1D
	[ERROR](0) src/Tools/H5.h:324 (getVect) Reading vector Momentum-0 is not 1D but -1D
``

I don't understand this error as its trying to read data that smilei has output itself? I've attached all the log and input deck files that I've used for this simulation.

[log_1.txt](https://github.com/SmileiPIC/Smilei/files/2410821/log_1.txt)
[log_2.txt](https://github.com/SmileiPIC/Smilei/files/2410822/log_2.txt)
[log_3.txt](https://github.com/SmileiPIC/Smilei/files/2410823/log_3.txt)
[log_4.txt](https://github.com/SmileiPIC/Smilei/files/2410824/log_4.txt)
[SimulationFiles.zip](https://github.com/SmileiPIC/Smilei/files/2410825/SimulationFiles.zip)

Thanks
Savio Rozario

**Comment by jderouillat** [comment]
Dear Savio,  
This behavior is surprising.  
In my opinion the 1st thing to do is to check the integrity of the checkpoint.  
If  you didn't can you confirm the result of the following command :  
```bash
$ h5dump  -a /patch-000000/species   ../ClusterSim_2/checkpoints/dump-00000-0000000000.h5
```
According to your error, it should return : 
```bash 
... {
ATTRIBUTE "species" {
   DATATYPE  H5T_STD_U32LE
   DATASPACE  SCALAR
   DATA {
   (0): 0
   }
}
}
```
If it's the case don't you have an error file from the third simulation ?

Regards.

Julien

**Comment by iclaserplasma** [comment]
![image](https://user-images.githubusercontent.com/42937440/45962809-a8973f80-c019-11e8-9f13-69aaa9d04354.png)

Seems like it might be the checkpoint file which is corrupted. I've attached the logfile from the final run to show the error that it observes. 
[log5.txt](https://github.com/SmileiPIC/Smilei/files/2411577/log5.txt)

If ClusterSim2 does need to be rerun can you recommend how I avoid this error?
Thanks
Savio

**Comment by iltommi** [comment]
looks like `h5dump` command is not properly installed. So we still don't know if the file is corrupted and why it was corrupted. 

Since the simulation did several checkpoints, a wise thing to try is keep on disk more than one checkpoint. You can achieve this with  `keep_n_dumps` : https://smileipic.github.io/Smilei/namelist.html#keep_n_dumps 

set it to 2 an even if the latest checkpoint is corrupted you will still have the previous one.

**Comment by mccoys** [comment]
One note about this issue. If you terminate your job too early after the time of the checkpoint, then the storage of data into checkpoint files may be interrupted, causing corrupt files. To avoid this, you should let the simulation at least 5 minutes to complete the checkpoint. In some cases, 5 minutes is not sufficient.

**Comment by iclaserplasma** [comment]
The issue was in fact that I had run out of space and the checkpoint file couldn't complete its save! I think it is running fine now.
Thanks!
