### ISSUE TITLE
happi can't find the Path

### ISSUE THREAD

**Issue by Tissot11** [SmileiPIC/Smilei#632]
I am witnessing this strange issue on one machine where `SMILEI `works fine but `happi` has trouble finding the path. For example if I define a `Path1` string for my simulation directory and use `S1=happi.Open(Path1)` then it complains about not finding a valid simulation path. If I `cd` to the simulation directory from `Spyder console`, then I can either use `S2=happi.Open('.')` or `S1=happi.Open(Path1)` and both of the options work fine. If now I go back to my `Python Projects` directory and invoke `S3=happi.Open(Path1)`, then it works fine (presumably due to `__pycache__`). 

Needless to say that I don't see this happening on other machines and I'm able to load simulation data by defining a path string to the simulation directory. I am always using my own miniconda environment for installing `Spyder matplotlib` etc on each machines.

What could possibly the reason behind this strange behaviour?

**Comment by mccoys** [comment]
Is this bug reproducible only from spyder?

Does it happen in a basic python prompt?

**Comment by iltommi** [comment]
Try to use a raw string, by putting r immediately before the string:  `f = open(r'filename', 'r')`
It might be some character conversion

**Comment by Tissot11** [comment]
It's reproducible also when I run the script using `python` command without `Spyder`. I try to your other suggestion

**Comment by Tissot11** [comment]
> Try to use a raw string, by putting r immediately before the string: `Path1 = r'path_to_dir'`
> It might be some character conversion

This also show the same error as before.

**Comment by Tissot11** [comment]
> Could you also check whether the `Path1` exists before calling `happi`:
> 
> ```
> import os
> print(os.path.isdir(Path1))
> ```

If I try this, then I get `False`. So the Path1 doesn't exist before calling `happi`? I used `os.path.join` method to add Simulation directory and the the simulation folder in this directiory for creating the `Path` string.

**Comment by iltommi** [comment]
`Path1` is an absolute path? or a relative one? If it's the latter case, are you sure that you're in the same directory? `print(os.getcwd())` will tell you where you are.

**Comment by Tissot11** [comment]
`Path1` is an absolute path. And `print(os.getcwd())` return the current directory I'm in.

**Comment by mccoys** [comment]
Maybe check the permissions on the directory and on directories above. Maybe you have permissions to access it, but python somehow runs in an environnement in which it does not have the permissions?
