### ISSUE TITLE
Postprocess issue

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#637]
## Description

Suddenly, I am not able to open the postprocess results. like png image or .avi video. Today morning it was working fine and I have not any change in my code. I have cheked it on two different machine. the issue is same. here is an example. Thank you !
![Ex00](https://github.com/SmileiPIC/Smilei/assets/67734147/e1256698-bf95-4c68-8372-b9c312dffe5f)

```

```

## Steps to reproduce the problem

If relevant, provide a step-by-step guide

## Parameters

- Smilei 4.7
- Currently Loaded Modules:
  1) craype-x86-rome                         9) cray-mpich/8.1.23
  2) libfabric/1.12.1.2.2.0.0               10) cray-libsci/22.12.1.1
  3) craype-network-ofi                     11) PrgEnv-cray/8.3.3
  4) perftools-base/22.12.0                 12) bolt/0.8
  5) xpmem/2.5.2-2.4_3.30__gd0f7936.shasta  13) epcc-setup-env
  6) cce/15.0.0                             14) load-epcc-module
  7) craype/2.7.19                          15) cray-hdf5-parallel/1.12.2.1
  8) cray-dsmml/0.2.2                       16) cray-python/3.9.13.1
  - ...

**Comment by mccoys** [comment]
Please explain better what does not work exactly

please update your image again as it did not work
