### ISSUE TITLE
Defining 2D laser profile 

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#638]
I want to define 2D laser with a profile. 
F_p(x, y,t) = (m_ec^2)qa0^2(y/sigma^2)exp(-(y^2/sigma^2 - (t-(x/c))^2/tau^2)/sqrt(1 + exp(-(y^2/sigma^2 - (t-(x/c))^2/tau^2))

Basically its a pondermotive force. So I want only the pondermotive field. How can I write By profile and Bz prifile. if the filed is circularly polarised. I tried but the laser only intitiating at the x_min boundary. I want to fix the position in tne middle of plasma box. Can you help me please. Thank you  !

**Comment by mccoys** [comment]
If you want to have only the ponderomotive force, have a look at the envelope model: https://smileipic.github.io/Smilei/Understand/laser_envelope.html

Concerning the conversion from force to field, then this is not the right place to ask. Try a forum about physics
