### ISSUE TITLE
Only 1 thread per MPI is working when initializing

### ISSUE THREAD

**Issue by xsgeng** [SmileiPIC/Smilei#64]
Dear developers,
I run the code with 2 MPI processes and 10 threads per MPI but I find only 1 thread per MPI is running when the program initializes the patches, calculates the QED tables or solves the relativistic Poisson equation. It really takes some time. I think all these initialization procedures could run in parallel. Is the program designed to do so or is there anything wrong with the settings? 

Thank you.

**Comment by jderouillat** [comment]
Hi, 
Indeed for the moment, the initialization of the code is not parallelized through threads. 
For Poisson solvers, the development of an OpenMP implementation is in progress but not integrated for now in the released code (and not planned in the upcoming version).
For small parallel configuration, you can maybe use more MPI process and less OpenMP threads without degrading the global performance of the code and this will accelerate the initialization which is more parallel regarding MPI.
Regards

Julien

**Comment by xxirii** [comment]
Dear @xsgeng,

Concerning the computation of the QED tables, some of the loops are parallelized with OpenMP. This step will take a lot of time anyway. We advice to use the external tables or to design a run just to create these tables for all the next simulations if the provided tables do not satisfy you.
