### ISSUE TITLE
error: unable to open output file 'build/src/Checkpoint/Checkpoint.o': 'No such file or directory'

### ISSUE THREAD

**Issue by yurivict** [SmileiPIC/Smilei#640]
## Description

Directories for output *.o files aren't created.

```
If available, copy-paste faulty code, warnings, errors, etc.
```

## Steps to reproduce the problem

If relevant, provide a step-by-step guide

## Parameters

- Smilei version ?  rev. 81d858dd9
- Commands or script used to run the faulty simulation ?
- Computing resources
  - type of computer: desktop/server
  - OS: FreeBSD 13.2
  - C++ compiler (to get some information `g++ --version`): clang-15
  - Python version (`python --version`) Python-3.9
  - ...

**Comment by iltommi** [comment]
We've never used on freebsd (I guess it should not be so different from linux) and maybe some tuning has to be done
Can you provide a more detailed error?
How did you compile the code?

**Comment by yurivict** [comment]
I am compiling by just running ```gmake -f makefile```.
The error messages like in the subject are the only errors.
The errors go away when directories are created manually.
FreeBSD is similar to Linux in general.

**Comment by iltommi** [comment]
That's weird because this line should create them: https://github.com/SmileiPIC/Smilei/blob/master/makefile#L303

Can you post the output of `make config=verbose`?

**Comment by yurivict** [comment]
Here's what it prints:
```
===>  Building for smilei-4.7.1037
gmake[1]: Entering directory '/usr/ports/science/smilei/work/Smilei-4.7-1037-g81d858dd9'
Compiling src/Checkpoint/Checkpoint.cpp
mpicxx -O2 -pipe -fstack-protector-strong -fno-strict-aliasing   -D__VERSION=\"12.3-eol-11004-gac46d5a59a46-main\" -DOMPI_SKIP_MPICXX -std=c++11 -Wall -Isrc -Isrc/Checkpoint -Isrc/Collisions -Isrc/Diagnostic -Isrc/DomainDecomposition -Isrc/ElectroMagn -Isrc/ElectroMagnBC -Isrc/ElectroMagnSolver -Isrc/Field -Isrc/Interpolator -Isrc/Ionization -Isrc/Merging -Isrc/MovWindow -Isrc/MultiphotonBreitWheeler -Isrc/Params -Isrc/PartCompTime -Isrc/ParticleBC -Isrc/ParticleInjector -Isrc/Particles -Isrc/Patch -Isrc/Profiles -Isrc/Projector -Isrc/Pusher -Isrc/Python -Isrc/Radiation -Isrc/SmileiMPI -Isrc/Species -Isrc/Tools -Isrc/picsar_interface -Ibuild/src/Python -I/usr/local/include/python3.9 -I/usr/local/include/python3.9 -I/usr/local/lib/python3.9/site-packages/numpy/core/include -DSMILEI_USE_NUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -O3 -g -fopenmp -D_OMP -c src/Checkpoint/Checkpoint.cpp -o build/src/Checkpoint/Checkpoint.o
error: unable to open output file 'build/src/Checkpoint/Checkpoint.o': 'No such file or directory'
1 error generated.
gmake[1]: *** [makefile:325: build/src/Checkpoint/Checkpoint.o] Error 1
gmake[1]: Leaving directory '/usr/ports/science/smilei/work/Smilei-4.7-1037-g81d858dd9'
*** Error code 1
```

No *.d files were created.

**Comment by yurivict** [comment]
Where is the makefile line that make something to depend on on *.d files?

**Comment by mccoys** [comment]
Do you have write permissions?

**Comment by yurivict** [comment]
Certainly

**Comment by mccoys** [comment]
To answer your previous question, the .d files listed in DEPS. They are included after the line defining FILTER_RULE

**Comment by mccoys** [comment]
I wonder if gmake correctly supports these few lines

**Comment by iltommi** [comment]
this should be the line including the `$(DEPS)`:
https://github.com/SmileiPIC/Smilei/blob/master/makefile#L349

**Comment by yurivict** [comment]
Ok. Something doesn't work.


GNU make is too difficult to use for this type of problem. It probably has some quirks or bugs that affect this.

Nowadays cmake does this very easily - you never need to write this type of code and worry about this level of detail.

**Comment by mccoys** [comment]
Actually @iltommi  now that I realize it, the `-include` statement does not require the `.d` files to be written. It just loads them after they are created. I don't see anywhere in the makefile where these files are requested. How come they are created anyway under linux?

My guess is that `make` does not find the files, and decides to make them according to the recipe. But that aspect might be implemented differently in other versions of `make`. @yurivict could you share your version of gmake?

@iltommi Is there a reason why we did it that way? Why not change the recipes?
For now we have
```
$(BUILD_DIR)/%.d: %.cpp
...
$(BUILD_DIR)/%.o : %.cpp
...
```
Why not use
```
$(BUILD_DIR)/%.d: %.cpp
...
$(BUILD_DIR)/%.o : %.d
...
```
This would force the creation of `.d` files when the `.o` file is requested.

**Comment by mccoys** [comment]
Actually the way we do it is the recommended way in gnu make doc.

@yurivict maybe try to replace `-include` by `include` to display potential error messages

**Comment by yurivict** [comment]
@mccoys 
It doesn't print any additional error messages. The error is the same.

**Comment by yurivict** [comment]
Commenting out like this works:
```
#ifeq ($(filter-out $(wildcard print-*),$(MAKECMDGOALS)),)
#    ifeq ($(filter $(FILTER_RULES),$(MAKECMDGOALS)),)
        # Let's try to make the next lines clear: we include $(DEPS) and pygenerator
        include $(DEPS) pygenerator
        # and pygenerator will create all the $(PYHEADERS) (which are files)
        pygenerator : $(PYHEADERS)
#    endif
#endif
```

**Comment by mccoys** [comment]
something in the `ifeq` conditions is off. I don't see how this is possible, but I know very little about FreeBSD

**Comment by yurivict** [comment]
I don't understand what does this code do and why are these conditionals in place.
Does this mean that creating directories is conditional? How can it work w/out directories?

**Comment by mccoys** [comment]
Yes creating the `.d` files (and the directories) is not necessary in many cases, such as making the documentation or other recipes. That is why it is conditional.

**Comment by yurivict** [comment]
Then mkdir shouldn't be attached to *.d file creation:
```
# Calculate dependencies
$(TABLES_BUILD_DIR)/%.d: %.cpp
        @echo "Checking dependencies for $<"
        $(Q) if [ ! -d "$(@D)" ]; then mkdir -p "$(@D)"; fi;
        $(Q) $(SMILEICXX) $(CXXFLAGS) -MF"$@" -MM -MP -MT"$@ $(@:.d=.o)" $<
```

**Comment by mccoys** [comment]
It should be, because these are the first files that are made. They require the directories in the first place.

But I am wondering if you could try `gmake` without `-f makefile`. Maybe these arguments are wrongly interpreted in the filter function. I have little hope though

**Comment by yurivict** [comment]
No, I just removed these 2 conditionals.

**Comment by iltommi** [comment]
You could also try to force the `$(DEPS)` before the `$(OBJS)`:
Replace the line https://github.com/SmileiPIC/Smilei/blob/master/makefile#L328
```
$(EXEC): $(OBJS)
```

with

```
$(EXEC): $(DEPS) $(OBJS)
```

**Comment by mccoys** [comment]
@iltommi @yurivict Do you guys have the possibility to test again this issue after the recent changes from #651 ?

**Comment by iltommi** [comment]
The makefile is now ok for me with GNU Make 4.4
