### ISSUE TITLE
EM Bound conditions 

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#641]
Hi I am using 2 D simulation simulation for counter propagation two laser pulses. But both laser pulses reflecting back from the opposite boundry. Can you help me how to get the absorbe the laser reaching to the other boundary ?

**Comment by beck-llr** [comment]
Do you use a moving window ?

If you don't, Silver-Muller or PML boundary conditions should work.
If it doesn't, try using the PML boundaries and increase the number of PML cells until the reflection suits your needs.

**Comment by mccoys** [comment]
@Sanjeev273 This is not an issue. Please ask questions in the [chat room](https://app.element.io/#/room/!LQrdVpOJEohPSWMlmf:matrix.org)

**Comment by Sanjeev273** [comment]
> 

I am not using moving window.  I used the Silver-Muller but still its not working. 
`Main(
    geometry = "2Dcartesian",
  
    interpolation_order = 2,

    timestep = dt,
    simulation_time = Tsim, #int(1*Lx/dt)*dt,

    cell_length = [ 0.5, 1. ],
    grid_length = [ Lsimx, Lsimy ],

    number_of_patches = [npatch_x, npatch_y],
    
    #clrw = nx/npatch_x,
    
    reference_angular_frequency_SI = 2.0*math.pi*3e8/0.8e-6,
    EM_boundary_conditions = [
        ["silver-muller","silver-muller"],
        ["silver-muller","silver-muller"],
    ],
    EM_boundary_conditions_k =[[1.,0.],[0.,0.],[0.,1.],[0.,-1.]], 
    solve_poisson = False,
    
    solve_relativistic_poisson = True,
    
    print_every = 100,
    
    random_seed = smilei_mpi_rank
)`
