### ISSUE TITLE
Error during installation - Fedora 38 - "pyinit.pyh"

### ISSUE THREAD

**Issue by arv-sharma** [SmileiPIC/Smilei#645]
I am running into an error while trying to install Smilei on Fedora 38. The error is thrown while compiling different files that invoke 'pyinit.pyh', and the message is:
"pyinit.pyh: No such file or directory"

The file attached below shows the outputs from 
$ git describe --all --long
$ make config=verbose
$ make env
$ echo $LD_LIBRARY_PATH
$ python -m sysconfig
$ ldd smilei
[installation_output.txt](https://github.com/SmileiPIC/Smilei/files/12264024/installation_output.txt)

The only file I could find that has 'pyinit' in the filename is in Smilei/src/Python/pyinit.py.

**Comment by mccoys** [comment]
Can you try this solution?
https://github.com/SmileiPIC/Smilei/issues/640#issuecomment-1628416005

**Comment by arv-sharma** [comment]
@mccoys I am not sure I quite follow the suggestion - are you suggesting that I comment out the lines calling "pyinit.pyh" before compiling?

**Comment by mccoys** [comment]
Not really. The suggestion is too comment out a few lines in `makefile`. Find those lines and do the same as in the suggestion.

Then do `make clean` and `make`.

**Comment by arv-sharma** [comment]
@mccoys I commented out the ifeq condition lines in makefile lines 346-353, leaving only the "-include $(DEPS) pygenerator" and "pygenerator : $(PYHEADERS)" lines as suggested. I still get the same error though.

I noticed that the error is from makefile line 325. I am wondering if the header files are not generated until later in the file whereas the error comes from the earlier line. Should I place the pygenerator lines ahead of lines 323-325 perhaps?

**Comment by mccoys** [comment]
I don't really understand where the error originates

Could you give the output of 
```
make print-PYSCRIPTS
make print-PYHEADERS
```

Can you also check the content of the build/src/Python directory, and make sure you have write permissions?

**Comment by arv-sharma** [comment]
Here is the output:

[user@fedora Smilei]$ make print-PYSCRIPTS
Checking dependencies for src/Params/Params.cpp
src/Params/Params.cpp:16:10: fatal error: pyinit.pyh: No such file or directory
   16 | #include "pyinit.pyh"
      |          ^~~~~~~~~~~~
compilation terminated.
PYSCRIPTS : src/Python/pycontrol.py src/Python/pyprofiles.py src/Python/pyinit.py

[user@fedora Smilei]$ make print-PYHEADERS
Checking dependencies for src/Params/Params.cpp
src/Params/Params.cpp:16:10: fatal error: pyinit.pyh: No such file or directory
   16 | #include "pyinit.pyh"
      |          ^~~~~~~~~~~~
compilation terminated.
PYHEADERS : build/src/Python/pycontrol.pyh build/src/Python/pyprofiles.pyh build/src/Python/pyinit.pyh

I do not have the directory build/src/Python created.

**Comment by mccoys** [comment]
Which directories exist? At least `build`? `build/src`?

**Comment by arv-sharma** [comment]
Yes, I have a few directories in build/src (listed below), but no 'Python' directory.

[user@fedora Smilei]$ ls build/src
Checkpoint           ElectroMagnSolver  MultiphotonBreitWheeler  Patch             Smilei.d
Collisions           Field              Params                   picsar_interface  SmileiMPI
Diagnostic           Interpolator       PartCompTime             Profiles          Species
DomainDecomposition  Ionization         ParticleBC               Projector         Tools
ElectroMagn          Merging            ParticleInjector         Pusher
ElectroMagnBC        MovWindow          Particles                Radiation

**Comment by mccoys** [comment]
This is strange. Could you provide the result of `make --version`

**Comment by arv-sharma** [comment]
I tried with the modified makefile, and initially had an "error: ‘uint64_t’ does not name a type" in one of the compiled files. I added a call to cstdint in that file and reran without any errors. I now have a Smilei.sh executable file in my directory.

Here are the outputs:
[modified_makefile_output.txt](https://github.com/SmileiPIC/Smilei/files/12307011/modified_makefile_output.txt)

**Comment by mccoys** [comment]
The error you got with uint64_t looks like it comes from a C compiler using the C99 standard. Instead for smilei you should have a c++11 compiler. I am a bit puzzled by this error. Which compiler are you using?

**Comment by arv-sharma** [comment]
From 'info gcc', it looks like the default C++ compiler is C++17 with GNU extensions, and the default C compiler is 'gnu17'. The gcc version is 13.0.1 20230401 (Red Hat 13.0.1-0). I am not sure very familiar with this, so let me know if this answers your question.

**Comment by mccoys** [comment]
I am still working on the first part of the issue (the fix is temporary and will not work in general). 

@iltommi look at this https://stackoverflow.com/questions/76869759/makefile-to-include-a-phony-target/76870264#76870264
It turns out a recent change in gnu make makes it impossible to include a phony target. This is what happens here. The `pygenerator` is phony, so it is not made in gnu make 4.4. We have to find a better solution

**Comment by mccoys** [comment]
@iltommi Here is my proposal for changes in the makefile: https://github.com/mccoys/Smilei/blob/master/makefile
When you have a chance, please review the changes.

**Comment by mccoys** [comment]
@iltommi Should we go ahead and add the includes as you suggested? Do you see any possible issue with that?

**Comment by arv-sharma** [comment]
> Concerning the error "error: ‘uint64_t’ does not name a type" I think we're missing some headers. You need to add `#include <cstdint>` In both `src/Particles/Particle.h` and `src/Tools/Tools.h` in the begining of the files with all other includes.
> 
> @arv-sharma : can you test this?
> 
> Thanks a lot

I already had to add cstdint library to the two files when I successfully created the Smilei executable on Aug 9. So yes, this worked.
