### ISSUE TITLE
Font size increase of legend

### ISSUE THREAD

**Issue by Sonuphd** [SmileiPIC/Smilei#649]
Dear Sir,

I want to increase the font size of my defined labels in multiplot of probe diagnostics. Please add this feature in happi module. I have attached my command for your reference.

In [25]: diag1=S1.Probe(0,"Ex",units=["TV/m","um","fs"],title_font = font,xlabel_font = font,ylabel_font =font,xticklabels_font = font,yticklabels_font = font ,colorbar_font= font,color="k",linestyle="-",linewidth=2,label="a0=2.6",vmin=-2.0,vmax=2.0)

In [26]: diag2=S2.Probe(0,"Ex",units=["TV/m","um","fs"],title_font = font,xlabel_font = font,ylabel_font =font,xticklabels_font = font,yticklabels_font = font,colorbar_font= font,color="b",linestyle="--",linewidth=2,label="a0=3.9",vmin=-2.0,vmax=2.0)

In [27]: diag3=S3.Probe(0,"Ex",units=["TV/m","um","fs"],title_font = font,xlabel_font = font,ylabel_font =font,xticklabels_font = font,yticklabels_font = font ,colorbar_font= font,color="g",linestyle="-.",linewidth=2,label="a0=5.2",vmin=-2.0,vmax=2.0)

In [28]: diag4=S4.Probe(0,"Ex",units=["TV/m","um","fs"],title_font = font,xlabel_font = font,ylabel_font =font,xticklabels_font = font,yticklabels_font = font ,colorbar_font= font,color="y",linestyle=":",linewidth=2,label="a0=6.5",vmin=-2.0,vmax=2.0)

In [29]: happi.multiPlot(diag1,diag2,diag3,diag4,timesteps=15000)

**Comment by mccoys** [comment]
The `legend_font` option is now available in the `develop` branch

**Comment by Sonuphd** [comment]
Dear Sir,

I have not found any command related to legend font size increase in the advance plotting options in the post-processing section of Smilei pic code.

**Comment by mccoys** [comment]
The online documentation only reflects the code in the master branch. As those changes are only in the develop branch, they do not appear online. If you have sphinx installed you can locally create the documentation using the command `make doc`.

The `multiPlot` and `multiSlide` functions now accept a new argument `legend_font` that works just like other font specifications

**Comment by Sonuphd** [comment]
okay, thank you so much sir.
