### ISSUE TITLE
Font size increase of legend defined

### ISSUE THREAD

**Issue by Sonuphd** [SmileiPIC/Smilei#652]
Dear Sir,

I want to plot multiplot of two different probes diagnostic. But I have found an error with increasing font size of legend defined. I am sharing you my plotting command.

In [10]: diag1 = S1.Probe(0,"Ex",units=["TV/m","um","fs"],title_font=font,xlabel_font=font,xticklabels_font=font,ylabel_font=font,yticklabels_font=font,colo
    ...: rbar_font=font,linestyle='-',linewidth=2,color='k',vmin=-1,vmax=1,label='a0=2.6',legend_font=font)

In [11]: diag2 = S2.Probe(0,"Ex",units=["TV/m","um","fs"],title_font=font,xlabel_font=font,xticklabels_font=font,ylabel_font=font,yticklabels_font=font,colo
    ...: rbar_font=font,linestyle='--',linewidth=2,color='b',vmin=-1,vmax=1,label='a0=5.2',legend_font=font)

In [12]: happi.multiPlot(diag1,diag2,timesteps=1500)
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-12-d436338705ed> in <module>
----> 1 happi.multiPlot(diag1,diag2,timesteps=1500)

~/Smilei/happi/_Utils.py in multiPlot(*Diags, **kwargs)
    749
    750
--> 751         mp = _multiPlotUtil( *Diags, **kwargs )
    752
    753         if mp.sameAxes and Diags[0].dim==0:

~/Smilei/happi/_Utils.py in __init__(self, *Diags, **kwargs)
    543                 for Diag in Diags:
    544                         if not Diag.valid:
--> 545                                 raise Exception( "Cannot multiPlot because invalid diagnostic" )
    546                 self.np  = Diags[0]._np  # numpy
    547                 self.plt = Diags[0]._plt # pyplot

Exception: Cannot multiPlot because invalid diagnostic

**Comment by mccoys** [comment]
The error says your diagnostic is invalid.

**Comment by Sonuphd** [comment]
Dear Sir,

 If I exclude legend font size then I have found the plot.


In [13]: diag1 = S1.Probe(0,"Ex",units=["TV/m","um","fs"],title_font=font,xlabel_font=font,xticklabels_font=font,ylabel_font=font,yticklabels_font=font,colo
    ...: rbar_font=font,linestyle='-',linewidth=2,color='k',vmin=-1,vmax=1,label='a0=2.6')

In [14]: diag2 = S2.Probe(0,"Ex",units=["TV/m","um","fs"],title_font=font,xlabel_font=font,xticklabels_font=font,ylabel_font=font,yticklabels_font=font,colo
    ...: rbar_font=font,linestyle='--',linewidth=2,color='b',vmin=-1,vmax=1,label='a0=5.2')

In [15]: happi.multiPlot(diag1,diag2,timesteps=1500)
findfont: Font family ['serif'] not found. Falling back to DejaVu Sans.
findfont: Generic family 'serif' not found because none of the following families were found: Times New Roman
findfont: Font family ['serif'] not found. Falling back to DejaVu Sans.
findfont: Generic family 'serif' not found because none of the following families were found: Times New Roman
![Screenshot (76)](https://github.com/SmileiPIC/Smilei/assets/42186182/9cbfde5d-5866-4678-b4b4-8c89664f2061)

**Comment by Sonuphd** [comment]
Please suggest me proper command for increase legend font size.

**Comment by mccoys** [comment]
`legend_font` is an argument of `multiPlot` but not and argument of each diagnostic.

**Comment by Sonuphd** [comment]
okay sir
