### ISSUE TITLE
Opening partly written HDF5 files with happi after simulation crash

### ISSUE THREAD

**Issue by DoubleAgentDave** [SmileiPIC/Smilei#655]
Unfortunately some of the clusters I am using occasionally crash. This can caused errors in writing to HDF5 files. Using happi I sometimes can't open HDF5 files with incompletely written lines of data. I.E. in a probe data file there are dumptimes that are half written and some bit of data is missing.

For example I recently ran a simulation with a probe diagnostic which writes a HDF5 data set every 4 timesteps. It is quite likely that if the simulation hits the wall time before a write occurs, or if the simulation crashes during a write, then there will be half written data in the file. But the previously written data could still be useful and the simulation may not need to be rerun.

When you use happi to open these files the following error occurs:

```
signal = Ez_probe.getData()
  File "~/Smilei/happi/_Diagnostics/Diagnostic.py", line 163, in getData
    data.append( self._dataAtTime(t) )
  File "~/Smilei/happi/_Diagnostics/Diagnostic.py", line 862, in _dataLinAtTime
    A = self._getDataAtTime(t)
  File "~/Smilei/happi/_Diagnostics/Probe.py", line 372, in _getDataAtTime
    data = self._dataForTime[t][n,first:last]
TypeError: 'NoneType' object is not subscriptable

```
When I look at the file in something like HDFCompass I can see that there are two empty data lines, but the rest of the data is intact:

![hdfcompass](https://github.com/SmileiPIC/Smilei/assets/47922792/f48c2ac7-61ba-49c4-badd-878cdc1595f1)

I think it would be relatively simple to use a try-except statement somewhere to obtain this data in this scenario.  It would likely be relatively easy to simulate this problem using a correctly written HDF5 file and adding a couple of unexpected data sets at the end of the file.

**Comment by DoubleAgentDave** [comment]
Admittedly the 'flush_every' function helps reduce the chance of the HDF5 file being corrupted during a write while it's running, so part of what I said is not quite right, but the problem still exists that some bits of data at the end of the HDF5 files is miswritten sometimes during a crash.

**Comment by mccoys** [comment]
Thank you for suggesting this. I actually had the same comment a few days ago from a colleague.

**Comment by DoubleAgentDave** [comment]
This is usually enough to clean out badly written datasets:
`
import h5py

def start():
    f = h5py.File("Probes0.h5")
    keys = []
    for key in f:
        keys.append(key)

    with h5py.File("Probes0_fixed.h5", "w") as f_dest:
        with h5py.File("Probes0.h5", "r") as f_src:
            for key in f:
                try:
                    f_dest.create_dataset_like(str(key), f_src[key])
                except KeyError:
                    print("faulty key = " + str(key))


if __name__ == "__main__":
    start()
`

It's usually just the last couple of sets that are messed up as well.

**Comment by DoubleAgentDave** [comment]
Just to note when I use the above script it doesn't always work. The individual attributes must also be tested before the key is written to the new H5 file as sometimes a key can be correctly created but not filled with attributes correctly.

**Comment by mccoys** [comment]
Do you have an idea of to reproduce this? I cannot get a corrupted file

**Comment by DoubleAgentDave** [comment]
I just ran a simulation that got cut off in the middle. if time it right so
that the walltime is midway through a large output it can happen. The most
reliable way I found it to happen is if you have very frequent dumps, I had
a probe diagnostic that was recording every 4 timesteps and then dumping
every 250 timesteps. If the simulation gets cutoff during a write I had a
50% chance the file had a couple of crappy outputs that hadn't been written
properly.

e.g.:
DiagProbe(
    every=4,
    number=[10],
    origin=[0.0 + 5.0 * dx],
    corners=[[Lsim - 5.0 * dx]],

fields=["Ex","Ey","Ez","Bx","By","Bz","Rho_ion","Rho_eon","Jx_eon","Jy_eon","Jz_eon","Jx_ion","Jy_ion","Jz_ion","Jx","Jy","Jz"
],
    flush_every=outputtime / 10,
)

**Comment by mccoys** [comment]
It does not happen on my system for some reason. Would you be able to produce a small example and send it with dropbox or equivalent?

**Comment by DoubleAgentDave** [comment]
Sure, I'll try finding one tomorrow

**Comment by mccoys** [comment]
I have not received it. My name on element is fredpz

**Comment by DoubleAgentDave** [comment]
ok, sent again, hopefully right person this time :)

**Comment by DoubleAgentDave** [comment]
Yes, that seems to allow me to access files which I couldn't before, thanks! That's eliminated a step which was quite annoying and will save me some time too, really appreciated!

**Comment by DoubleAgentDave** [comment]
Just to be clear, with the old version I tried to access a broken probes0.h5 file and got this error:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/media/david_blackman/left_external/broadband/simulation_results/bandwidth/redone_diags/fixed_ions/narrow/../../../../py1D/make_signal_files.py", line 193, in start
    signal = Ez_probe.getData()
  File "/home/david_blackman/codes/smilei_new/Smilei/happi/_Diagnostics/Diagnostic.py", line 163, ingetData
    data.append( self._dataAtTime(t) )
  File "/home/david_blackman/codes/smilei_new/Smilei/happi/_Diagnostics/Diagnostic.py", line 862, in_dataLinAtTime
    A = self._getDataAtTime(t)
  File "/home/david_blackman/codes/smilei_new/Smilei/happi/_Diagnostics/Probe.py", line 372, in _getDataAtTime
    data = self._dataForTime[t][n,first:last]
TypeError: 'NoneType' object is not subscriptable

Now I get no error and successfully build up my probe signals so I can process them properly.!
