### ISSUE TITLE
Probe diagnostics dependent on the number of points in 3D

### ISSUE THREAD

**Issue by spadova-a** [SmileiPIC/Smilei#657]
Hello there, I am running a 3D simulation of laser pulse ionizing a nanoparticle, therefore I am only interested in events near the center of the computational domain (but at the same time I need domain big enough so the laser does not reflect from the borders), therefore using Fields diagnostics results in unnecessary big files. So, I would like to use the Probe diagnostics to choose only a part of the domain (specifically the whole x-axis and only middle part of axes y and z) while preserving the resolution.

I found out, that by choosing different values for the number of points in the Probes diagnostics results differ. I am attaching my input and results for 3 different values of the number variable (please ignore the orange line for number = [1280, 50, 50]).

Note: I am only setting up the simulation, so don't worry about the low resolution or the fact, that there is no nanoparticle to ionize.

I am using Smilei version: 4.8-1-g0293ceb-master (compiled it a few days ago)
[input.txt](https://github.com/SmileiPIC/Smilei/files/12935467/input.txt)

number = [1280, 40, 40]:
![n40](https://github.com/SmileiPIC/Smilei/assets/88655409/3101d53d-2de3-4a41-8563-ead403da3d4a)

number = [1280, 50, 50]:
![n50](https://github.com/SmileiPIC/Smilei/assets/88655409/bc998942-144c-4935-96f3-5053c1f4ca01)

number = [1280, 80, 80]:
![n80](https://github.com/SmileiPIC/Smilei/assets/88655409/416f64b2-62ac-4aba-8074-7ba0ebc959e3)

**Comment by mccoys** [comment]
Can you specify how you obtain your plot? What do you extract from the probe?

**Comment by spadova-a** [comment]
`%matplotlib notebook

dt = sim.Probe(0, "Ex", units=["fs"]).getTimesteps()
t = dt[3]

Ezpy = sim.Probe(0, "Ez", units=["fs", "GV/m"])
Expy = sim.Probe(0, "Ex", units=["fs", "GV/m"])
Eypy = sim.Probe(0, "Ey", units=["fs", "GV/m"])
Ex3 = np.array(Expy.getData(timestep = t))[0]
Ey3 = np.array(Eypy.getData(timestep = t))[0]
Ez3 = np.array(Ezpy.getData(timestep = t))[0]

fig, ax = plt.subplots(figsize=(8, 4), sharex=True, sharey = True)
x = np.linspace(0,55/0.85, 1280)

ax.plot(x, Ez3[:,20,20])
#Er3 = np.sqrt(Ex3**2+Ez3**2+Ey3**2)
#ax.plot(x, Er3[:,40,40])
plt.show()`

**Comment by mccoys** [comment]
As the number of points has changed you cannot use always the same location `Ez3[:,20,20]`. Are you sure you take this into account to make your plots?

**Comment by spadova-a** [comment]
Yes I know, this was for the first graph, for the other ones I sent I always chose the center of the Probe, sorry I wasn't more clear about this. Anyway, this  shouldn't really matter, since the laser focal spot (~15 um) is larger than the area of the Probe in the y- and z-directions. I tried to plot also other locations, but due to the above mentioned reson, the plots does no change much.

**Comment by mccoys** [comment]
One remark: do not use `random_seed = smilei_mpi_rank`. It is only for old versions of Smilei.

**Comment by spadova-a** [comment]
> One remark: do not use `random_seed = smilei_mpi_rank`. It is only for old versions of Smilei.

ok, so the default (or recommended) value is now 0? You think this may be causing the problem, or is it unrelated and just a remark?

**Comment by mccoys** [comment]
it is now a global seed. https://smileipic.github.io/Smilei/Use/namelist.html#random_seed
It is unrelated to the probe issue.

**Comment by mccoys** [comment]
For now I am unable to reproduce your result. As your case is large, I decided to put an external field everywhere in the box and it is well reproduced at early times

**Comment by spadova-a** [comment]
Hi, so I did run a simulation with better resolution, and the diagnostics worked well regardless the number of points. I currently don't have time and resources to investigate this further so, I will close the issue. Hope this was just a random error during the simulation.
