### ISSUE TITLE
multiSlide

### ISSUE THREAD

**Issue by Z10Frank** [SmileiPIC/Smilei#659]
Trying to use `multiSlide` with the input `benchmarks/tstAM_06_envelope_wake.py`:
```
Ex=S.Probe.Probe1("Ex",cmap="Blues_r",vmin=-1e-6,vmax=1e-6)
Env_E = S.Probe.Probe1("Env_E_abs",cmap="hot",vmin=0.004,transparent="under")
happi.multiSlide(Ex,Env_E)
```

The image is correct, but the axis `x` is extended up to negative numbers and the ticks in the colorbar on the left are covered by the colorbar on the right: 
<img width="1111" alt="Screenshot 2023-10-23 at 21 16 00" src="https://github.com/SmileiPIC/Smilei/assets/9608804/06b2c9aa-e76f-4a05-a616-4703a95329d4">

**Comment by mccoys** [comment]
Can you use xmin=0?

**Comment by Z10Frank** [comment]
Thank you! 
With `happi.multiSlide(Ex,Env_E,xmin=0)` the `x` axis is not extended.
Can the colorbars be less superposed?
<img width="822" alt="Screenshot 2023-10-24 at 08 47 05" src="https://github.com/SmileiPIC/Smilei/assets/9608804/c9a5e4fc-49ff-44f8-93eb-d136ba1c6728">

**Comment by mccoys** [comment]
You might try `tight_layout()` and that is potentially something that we could try directly within happi but I find matplotlib to be fairly inconsistent

**Comment by Z10Frank** [comment]
Thank you, `plt.tight_layout()` does not change much the colorbar superposition, and gives:

`UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout()`

**Comment by mccoys** [comment]
I will push soon a fix for the axis limits.
For the colorbar placement, simply use the `pad` argument in each diagnostic

**Comment by mccoys** [comment]
Done in last push
