### ISSUE TITLE
Wrong Magnetic field (Bx) from ParticleBinning diagnostic

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#660]
Hi Smilei Team, I am Runing 3D simulation, Her I ma using Paricle bining Diagnostic for Bx, By and Bz componets. In post processing, it seems I am getting the wrong field. Mainly I am interested in Bx component in Y-Z plane. For the Bx component, I compare to the Probe diagnostic and ParticleBinning diagnostic. Both results are very different. 

For Probe diagnostic 
![BxYZ](https://github.com/SmileiPIC/Smilei/assets/67734147/7d87990b-c325-462c-985c-f3ab27d79366)
 

```
###0# Density in y-z plane ####
DiagParticleBinning(
	deposited_quantity ="weight" ,
	every = 10.,
  time_average = 1,
	species = ["electron"],
	axes = [
    ["y", 0., Main.grid_length[1], 500,],
    ["z", 0., Main.grid_length[1], 500,]
	]
)

###1# Bx component in y-z plane ####
def Bx_comp(particles):
    return particles.weight*particles.Bx
    
DiagParticleBinning(
	deposited_quantity = Bx_comp,
	every = 10.,
  time_average = 1,
	species = ["electron"],
	axes = [
    ["y", 0., Main.grid_length[1], 500,],
    ["z", 0., Main.grid_length[1], 500,]
	]
)
```
In the post process, The second diagnostic is devided by first diag as you suggested me. 
```
Bx = s.ParticleBinning("#1/#0", units=units, transparent= "both", data_log=False, xlabel_font={"size":14}, xticklabels_font={"size":14}, ylabel_font={"size":14}, yticklabels_font={"size":14}, clabel = "$B_x$", colorbar_font={"size":14},  timesteps =[1, 20000]).Plot() 
```
The results from ParticleBinnig Diag.

![Binning_Bx_00](https://github.com/SmileiPIC/Smilei/assets/67734147/18c71ea7-6357-4eba-b22a-65be01264e8b)

The results trend from both diag looks fine but very diffeerent in Units. May I ask your help  to resolve the issue, if I am doing something wrong. Thanks !

## Parameters

- Currently Loaded Modules:
  1) craype-x86-rome                         9) cray-mpich/8.1.23
  2) libfabric/1.12.1.2.2.0.0               10) cray-libsci/22.12.1.1
  3) craype-network-ofi                     11) PrgEnv-cray/8.3.3
  4) perftools-base/22.12.0                 12) bolt/0.8
  5) xpmem/2.5.2-2.4_3.30__gd0f7936.shasta  13) epcc-setup-env
  6) cce/15.0.0                             14) load-epcc-module
  7) craype/2.7.19                          15) cray-python/3.9.13.1
  8) cray-dsmml/0.2.2                       16) cray-hdf5-parallel/1.12.2.1

 

/opt/cray/pe/python/3.9.13.1/bin/python
                    _            _
  ___           _  | |        _  \ \   Version : 4.8-1-g0293ceb2b-master
 / __|  _ __   (_) | |  ___  (_)  | |   
 \__ \ | '  \   _  | | / -_)  _   | |
 |___/ |_|_|_| |_| |_| \___| |_|  | |  
                                 /_/    
 
 
  - ...

**Comment by mccoys** [comment]
I think that happi does not know the units of your first binning diagnostic because it is a user function. It cannot convert to Tesla or anything.

I suggest you use the second binning diag with a function as well so that the output is not converted by happi. The result will not be converted to Tesla, but you can make the conversion yourself easily as the units will simply be B_r.

Alternately, you can disable the handling of units completely with the option `pint=False`
