### ISSUE TITLE
Custom integrated diagnostics

### ISSUE THREAD

**Issue by DoubleAgentDave** [SmileiPIC/Smilei#663]
I would like to calculate several integrated quantities for my simulations, for example the total angular momentum in the electromagnetic fields ( J=int(rxExB)dV ). There are some others I would also like to calculate, but I've not decided yet. The problem is that I would like this to be time-resolved with a high frequency of outputs, i.e. to capture the reflection of a laser pulse or something.

Currently the two ways I can achieve this is either, 

1.  Fields Diagnostics: dumping all the relevant fields at as many timesteps as i can fit on a disk (e.g. in this case 'E' and 'B_m') and calculating this post-process.
2. Probe Diagnostics:  creating a 3D probe with a number of points and dumping it at often as I can, then post-processing the integration.

The problem with both of these approaches is that they require either frequent large dumps, or a lot of memory intensive buffering before even larger IO. I can do this on an HPC cluster, but I have colleagues who don't have access.

One way to decrease this would be to allow a custom dumped variable either in the 'Fields' diagnostic, or the 'Probes' diagnostic, and then integrating it post-process. This would lead to substantially less IO, but the time-resolution would still be limited by the resolution of the probe and field dumps. My preferred method would be to make a custom 'Scalar' diagnostic so that I can dump this more frequently. With a scalar diagnostic it might not cost a lot more than the other integrated quantities that already exist, though I guess that depends on the function and the implementation.

Is this sort of thing possible?

**Comment by mccoys** [comment]
We have recently added the possibility to keep fields that were interpolated on particles. These fields are accessible during a particle binning. Would it be possible to have a test species with 1 particle per cell (or less), then make a time-integrated particle binning diagnostic?

**Comment by DoubleAgentDave** [comment]
Do you mean something along the lines of:

`Species(
    name      = "test_positron",
    position_initialization = "regular",
    momentum_initialization = "cold",
    particles_per_cell = 1,
    number_density = 1.,
    charge = 1.,
    time_frozen = T_end,
    is_test = True,
	)

def field_am_from_part(particles):
    stuff = particles.Ex*particles.By ....
    return stuff

DiagParticleBinning(
    name = "field AM",
    deposited_quantity = "weight",
    every = 5,
    time_average = 1,
    species = ["test_positron"],
    axes = [
        [stuff, 0., 10, 1],
    ]
)`

That might work, I can test when I've got a bit of time on the cluster. I guess I might have to play with the 'axes' thing to make it work.

Thanks :)

P.S. I didn't want a time-integrated diagnostic, I wanted a time-resolved, spatially-integrated diagnostic. But what you've said makes sense in either case.

**Comment by DoubleAgentDave** [comment]
OK, this is effectively already a feature then, thanks! I'll update if it doesn't work, but it should be a closed issue then I guess?

**Comment by mccoys** [comment]
If you feel there is something missing in this way of doing, don't hesitate to reopen this explaining why it is missing something.

**Comment by DoubleAgentDave** [comment]
> If you feel there is something missing in this way of doing, don't hesitate to reopen this explaining why it is missing something.

Sure I will, thanks! 

For anyone looking through old issues I need to add: ,
    keep_interpolated_fields=True,
to the species :)
