### ISSUE TITLE
I get errors whenever I have been trying to use select in TrackParticles diagnostics

### ISSUE THREAD

**Issue by obudriga** [SmileiPIC/Smilei#667]
## Description

Explain your issue here.
I was not able to save to vtk file the trajectories for electrons with the momentum higher than a value.
```
If available, copy-paste faulty code, warnings, errors, etc.
```
Selecting particles ... (this may take a while)
   Selecting block `any(t>1160,px>1000)`, at time 1200
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs/fs1/home/a/anticipa/budriga/Smilei/happi/_Factories.py", line 570, in __call__
    return TrackParticles(self._simulation, *args, **kwargs)
  File "/gpfs/fs1/home/a/anticipa/budriga/Smilei/happi/_Diagnostics/Diagnostic.py", line 71, in __init__
    remaining_kwargs = self._init(*args, **kwargs)
  File "/gpfs/fs1/home/a/anticipa/budriga/Smilei/happi/_Diagnostics/TrackParticles.py", line 154, in _init
    self.selectedParticles = self._selectParticles( select, True, chunksize )
  File "/gpfs/fs1/home/a/anticipa/budriga/Smilei/happi/_Diagnostics/TrackParticles.py", line 356, in _selectParticles
    self._h5items[prop].read_direct(properties[prop], source_sel=self._np.s_[it,chunkstart:chunkstop], dest_sel=self._np.s_[:actual_chunksize])
  File "/gpfs/fs0/scratch/a/anticipa/budriga/envoli/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 970, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 192, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 112, in h5py._proxy.dset_rw
OSError: Can't read data (file read failed: time = Thu Nov 16 06:51:39 2023
, filename = './/TrackParticles_electron.h5', file descriptor = 5, errno = 14, error message = 'Bad address', buf = 0x7f02c26e8710, total read size = 107443072, bytes this sub-read = 107443072, bytes actually read = 18446744073709551615, offset = 0)

## Steps to reproduce the problem

If relevant, provide a step-by-step guide

## Parameters
- Smilei version: 
- Input file: [laser3d_gauss_cone3d_10.txt](https://github.com/SmileiPIC/Smilei/files/13378165/laser3d_gauss_cone3d_10.txt)
- Commands or script used to run the faulty simulation ?
s.TrackParticles('electron',axes=['x','y','z'],timesteps=1200,1920],select="any(t>1160,px>1000)").toVTK(rendering="trajectory",data_format="vtk")
- Computing resources
  - type of computer: cluster
  - OS: linux
  - C++ compiler (to get some information `g++ --version`) 
  - MPI version (`mpic++ --version`, `mpic++ -show`)
  - HDF5 version (`h5cc --version`)
  - Python version (`python --version`): 3.6.8
  - ...

**Comment by mccoys** [comment]
Does it work without select?

**Comment by obudriga** [comment]
Yes, it worked.-------- Mesaj original --------De la: mccoys ***@***.***>Dată: joi, 16 nov. 2023, 19:34Către: SmileiPIC/Smilei ***@***.***>Cc: obudriga ***@***.***>, Author ***@***.***>Subiect: Re: [SmileiPIC/Smilei] I get errors whenever I have been trying to use select in TrackParticles diagnostics (Issue #667)
Does it work without select?

**Comment by mccoys** [comment]
This sounds like a memory issue. Try to reduce the chunksize

**Comment by obudriga** [comment]
Thank you. I will try.Trimis de pe telefonul meu Huawei-------- Mesaj original --------De la: mccoys ***@***.***>Dată: joi, 16 nov. 2023, 21:39Către: SmileiPIC/Smilei ***@***.***>Cc: obudriga ***@***.***>, Author ***@***.***>Subiect: Re: [SmileiPIC/Smilei] I get errors whenever I have been trying to use select in TrackParticles diagnostics (Issue #667)
This sounds like a memory issue. Try to reduce the chunksize
