### ISSUE TITLE
How 'reflective' particle boundary works

### ISSUE THREAD

**Issue by fyli16** [SmileiPIC/Smilei#669]
This is related to #643 which may be simplified as the following question: is SMILEI doing 'reflective' particle boudary as the left or right panel of the following plot? 
<img width="496" alt="image" src="https://github.com/SmileiPIC/Smilei/assets/18069643/cad7233a-1ea1-4fc8-b342-cf88f6ab94cf">
Reading the source code, I found the 'reflective' boundary contains 
`momentum[ ipart ] = -momentum[ ipart ];`
i.e. reversing all velocity components. So, does this mean it works according to the right panel? 

The fact that the right panel could conserve pitch angles can be seen from the following plot: 
<img width="497" alt="image" src="https://github.com/SmileiPIC/Smilei/assets/18069643/1f61a984-1f5a-4ebf-ae4a-f1191d42bdcb">

So I'd appreciate if anyone could confirm which way the 'reflective' boundary works.

**Comment by mccoys** [comment]
If you look at the code source where this momentum reversal is done, you will see that it is done only in the direction of the normal of the boundary. It corresponds to your left hand figure

**Comment by fyli16** [comment]
You're right, thanks! I see how to modiy the code to achieve the right panel
