### ISSUE TITLE
Particle binning of ionisation species

### ISSUE THREAD

**Issue by srozario121** [SmileiPIC/Smilei#67]
Hello all,
I'm trying to do a wakefield simulation in SMILEI with an ionisation species in 2D. For the sake of discussion this is what my species block looks like:
![image](https://user-images.githubusercontent.com/37711146/47847400-02cab380-ddc3-11e8-8ff8-5a4ea9917b00.png)
![image](https://user-images.githubusercontent.com/37711146/47847551-7c62a180-ddc3-11e8-9c66-52753c1c06f7.png)

When I output this via the particle binning diagnostic and look at the hdf files I see that the dimensions of the particle binning diagnostic are indeed correct. But when I look at the values inside them, it does not look right.
![image](https://user-images.githubusercontent.com/37711146/47847436-1ece5500-ddc3-11e8-888e-a3bcf6da0efb.png)

One problem that I see is that the carbon does not appear to ionise? Only C0+ has non-zero density. I know this can't be true as the a0 here is 1 and from ADK rates it should ionise to C5/6.

Essentially what I am looking for is number density as a function of real space (x-y) for electrons which are ionised from different levels. I want to see where these electron are ionised in space and what their equivalent momentum is.

Is the particle binning diagnostic the best way to do this? 
Thanks
Savio

**Comment by mccoys** [comment]
It looks like you are doing the correct type of diagnostics, and I don't see anything wrong in your code although I have not tested it.

Could you share the code you are using to make your plots ?

**Comment by srozario121** [comment]
I've attached the input deck and the log files. I'm using a few matlab scripts to analyse the simulation.
[IonisationSimInputFiles.zip](https://github.com/SmileiPIC/Smilei/files/2542658/IonisationSimInputFiles.zip)
[SmileiIonisation.zip](https://github.com/SmileiPIC/Smilei/files/2542653/SmileiIonisation.zip)

**Comment by mccoys** [comment]
You made a mistake in defining the following variable:
 ```
	reference_angular_frequency_SI=c/kL,
```

It should be `c*kL`

**Comment by mccoys** [comment]
Let me also add a quick note. There is a python module to extract and plot your data. See this example:

```python
import happi
S = happi.Open("path/to/simulation/results")
diags = [S.ParticleBinning(4,subset={"charge":i}) for i in range(6)]
happi.multiPlot(*diags, shape=[2,3])
```

**Comment by srozario121** [comment]
Ah thanks! I'm re-running the simulation just to check everything is fine. I will close this thread once I've checked the simulation outputs.

**Comment by srozario121** [comment]
That seems to have solved the problem of ionisation.
Now I can see the various ionisation states of the ionic species. But is there a way to obtain the density (x-y) map of the ionised electron species and separate them based on which carbon ion they were born from? I want to know where in space the electrons from C5+ and C6+ are born.

From what I can tell the particle binning diagnostic can only separate them by the charge of the binned particles.

**Comment by mccoys** [comment]
I did not see your last message - sorry for the delay.

The ionized electrons cannot be divided into their different origins. We actually never thought of this feature.

You may create another issue specific to this request, but I cannot predict when this could be implemented as it is not a basic change.

**Comment by srozario121** [comment]
Ah I see. I was thinking as a way around this to create several different species of carbon ions each with a species of electrons they can ionise from. It's a workaround for anyone who is looking for a way of doing this.
Thanks for you help. I'll close this thread now!
