### ISSUE TITLE
Particle injector dosen't work with profile

### ISSUE THREAD

**Issue by raghavi55** [SmileiPIC/Smilei#670]
I'm trying to simulate a pre-bunched electron beam, so I have defined a profile for number_density as:
fm = cosine(ne, ne, xvacuum=0., xlength=Lsim[0], xphi=0., xnumber=Lsim[0]/(l2),yvacuum=0., ylength=Lsim[1], yphi=pi/2, ynumber=0.5) 

It works well with the Species block and gives a bunched electron beam, but when I use the same profile for number_density in Particle Injector block, it does not imply the bunching in x direction and gives a uniform density. Please let me know how can I overcome this problem.
Smilei version is 4.8 and what follows are the used Species an Particle Injector blocks;

Species(
	name = 'eon1',
	position_initialization = "random",
	momentum_initialization = 'mj',
	particles_per_cell = 8,
	c_part_max = 1.0,
	mass = 1.0,
	charge = -1.0,
	number_density = fm,
	mean_velocity = [bet,0.,0.],
	time_frozen = 1.0,
	boundary_conditions = [
        ["remove"],
        ["remove"],
    ],
)
ParticleInjector(
    name      = "injector1",
    species   = "eon1",
    box_side  = "xmin",
    time_envelope = tconstant(),
    position_initialization = "random",
    momentum_initialization = "rectangular",
    mean_velocity = [bet,0.,0.],
    temperature = [1e-30],
    number_density = fm,
    particles_per_cell = 8,
)

Here is a sample electron distribution, where, the bunched  section is the Species  profile and the uniform one is due to Particle  Injector. 
![Figure_1](https://github.com/SmileiPIC/Smilei/assets/58202601/95cf85b9-20d5-4254-a246-9b0fb6b2ff79)

**Comment by mccoys** [comment]
The injector exists at the boundary. It will not use the spatial variation of the profile.

Instead you must use the time_envelope
