### ISSUE TITLE
AMcylindrical geometry, origin of transverse axes in Probes

### ISSUE THREAD

**Issue by Z10Frank** [SmileiPIC/Smilei#671]
Although the `Probes` in this geometry are defined in the namelist using the propagation axis as origin for the transverse coordinates, when they are displayed with `happi` the origin follows the same convention of the Cartesian geometries.

For example, in this LWFA simulation the transverse axis was defined between -150 um and 150 um, but the plot shows it from 0 to 300. For the sake of coherence with the namelist, could the plot command perform the shift in the transverse coordinates when this geometry is used?

<img width="636" alt="Screenshot 2023-11-19 at 14 53 02" src="https://github.com/SmileiPIC/Smilei/assets/9608804/04fcc0e4-81cf-45fb-9518-13f9f87b51fe">

**Comment by mccoys** [comment]
I don't think it is possible. The probe axes need not be aligned with the box. If the probe is oblique then the zero is not well defined.

It is best to use useOffset_y although I never tried

**Comment by Z10Frank** [comment]
I tried `S.Probe.Probe1("-Rho_bckgelectron/e", units=["um", "fs", "1/cm^3"]).slide(useOffset_y=-S.namelist.Lr)`.
The plot remains unchanged and a message appears: `Cannot format y ticks (typically happens with log-scale)`.

Of course with oblique Probes the line corresponding to the propagation axis (transverse coordinate = 0) will not be aligned with the plot axes, but since each Probe's coordinates in the AMcylindrical convention are stored it should be possible to shift the transverse coordinates.

**Comment by mccoys** [comment]
There is no obvious way to choose where would be the zero with oblique axes. You would need to specify some projection that has to change at specific angles. To complicated

I'd rather suggest to implement an offset

**Comment by Z10Frank** [comment]
Ok, it seems that an offset in the plot (and `getAxis` I suppose) would be the best solution.

**Comment by mccoys** [comment]
Working on this.

I just realized that this problem does not occur in 2D because we can plot an oblique rectangle already.

The problem occurs in 3D or AM where the probe plane is completely arbitrary. The choice in happi is to have it plotted in the plane of the probe, instead of rendering a 3D plot. The chosen convention is that the plot will have its first coordinate aligned with the first axis of the probe.
In any case, one way to change it would be to define the zero as the point where the origin of the axes would be projected orthogonally on the probe plane. Do you think it makes sense?

**Comment by Z10Frank** [comment]
So, just to confirm, with this `Probe` defined on the `xy` plane, what would be the position of the origin?

```
DiagProbe(
    every = 50,
    origin   = [0., -nr*dr,0.],
    corners  = [ [nx*dx,-nr*dr,0.], [0,nr*dr,0.] ],
    number   = [nx, 2*nr],
    fields = ['Ex','Ey','Rho']
)
```

Where `dr` and `dx` are the radial and longitudinal resolutions, `nr` and `nx` the number of grid points in the window (so y>0, x>0).
The `Probe` goes from negative to positive `y` values.

**Comment by mccoys** [comment]
We would project the origin of the box on the probe plane. In your example, the origin would be centered in y as you wanted.

**Comment by Z10Frank** [comment]
That would be perfect, thank you!

**Comment by mccoys** [comment]
done in last push
