### ISSUE TITLE
error compiling v5.0 with amd_gpu config

### ISSUE THREAD

**Issue by denisbertini** [SmileiPIC/Smilei#672]
Compiling Smilei v5,0 with "amd_gpu" config option gives the following errors

 ```
src/Diagnostic/DiagnosticProbes.cpp:744:15: error: ‘class SmileiMPI’ has no member named ‘resizeDeviceBuffers’; did you mean ‘resizeBuffers’?
         smpi->resizeDeviceBuffers( ithread,
               ^~~~~~~~~~~~~~~~~~~
               resizeBuffers
```
Am i missing something?

**Comment by charlesprouveur** [comment]
Hi, I am assuming you tried something like 
```
make config="gpu_amd" -j 40
```
The issue in that case would be that there were no GPU acceleration specific flags defined at compile time. 
We set such flags with the "machine file" scripts. If you are on a different machine  than Adastra , but using the cray environment with AMD GPUs, you can take inspiration from  /smilei/scripts/compile_tools/machine/adastra. 
If you are on adastra, after sourcing the proper environment you can try:
```
make machine="adastra" config="gpu_amd" -j 40
```

**Comment by denisbertini** [comment]
ok, thanks, i will have a look at the adastra config file.

**Comment by denisbertini** [comment]
what should i use as `CC` in the config?
```
SMILEICXX := CC
```
g++?

**Comment by denisbertini** [comment]
OK i manage to modify the `adastra` config script. I would like to run the GPU tests on the `/benchmarks` directory. Is there some example of SLURM submission script for GPU code that i can use for that ?

**Comment by charlesprouveur** [comment]
> what should i use as `CC` in the config?
> 
> ```
> SMILEICXX := CC
> ```
> 
> g++?

This should not be changed, as we are using an environment variable to set up SMILEICXX. Said environment variable is usually set by the modules loaded.

**Comment by charlesprouveur** [comment]
> OK i manage to modify the `adastra` config script. I would like to run the GPU tests on the `/benchmarks` directory. Is there some example of SLURM submission script for GPU code that i can use for that ?

Are you using adastra?

**Comment by denisbertini** [comment]
yes i am using adastra config

**Comment by charlesprouveur** [comment]
If you are using the adastra supercomputer you can use the following script "script_adastra.sh" where you should change the job name, the account, the name of your namelist (at the bottom of the script). This script uses the binding script "bind" that you can also find attached. Both script should be in the same folder as your namelist + executable smilei
[bind.txt](https://github.com/SmileiPIC/Smilei/files/13425203/bind.txt)
[script_adastra.sh.txt](https://github.com/SmileiPIC/Smilei/files/13425204/script_adastra.sh.txt)

( remove the .txt of the file names, i had to add it to comply with github)

**Comment by denisbertini** [comment]
Thanks !
I am not using directly the adastra computer  but  a similar cluster setup with AMD instinct MI 100.
I guess i will have to adjust the scripts...

**Comment by charlesprouveur** [comment]
I see, in that case you will have to change the topology accordingly. If you encounter an issue with that and if you have a public webpage describing your cluster i would be able to provide more support / adapt the scripts to fit.

**Comment by denisbertini** [comment]
The setup of our local AMD GPU cluster is  kind of "standard"
- **Compute Node**:
1 64-core AMD “Optimized 3rd Gen EPYC” CPU
8 AMD Instinct MI100 GPUs
- **GPU Architecture**: 
AMD Instinct MI100X GPUs,
- **System Interconnect:** 
Infiniband HDR 100

**Comment by charlesprouveur** [comment]
Very good, with this configuration you have the same topology as on adastra. No changes in "bind" should be required. Small changes should be made in the slurm script such as:

```
#SBATCH --job-name=YOUR_JOB_NAME
#SBATCH --constraint=MI250&turbo  # -> to be changed to the partition with M100
#SBATCH --account=YOUR_ACCOUNT
#SBATCH --nodes=1 --ntasks=1            # ntask here is the total number of GPUs and --nodes  should be ntasks/8 once you use fully one node ; ie:  2 gpus: --nodes=1 --ntasks=2 , 8 gpus  --nodes=1 --ntasks=8 , 24 gpus: --nodes=3 --ntasks=24 , etc.
#(...)

LaunchSRun ./smilei YOUR_NAMELIST_NAME.py   # change the namelist name
```

**Comment by denisbertini** [comment]
Just one question, if i want to run on all 8 GPU on one node i have to add
```
--ntasks =8
```
right ?
And to run on N mutiple nodes i have to add

```
--nodes=N
```
accordingly, is that correct?

**Comment by charlesprouveur** [comment]
# ntask here is the total number of GPUs and --nodes  should be ntasks/8 once you use fully one node ;

 ie for 2 gpus: --nodes=1 --ntasks=2 , 8 gpus  --nodes=1 --ntasks=8 , 24 gpus: --nodes=3 --ntasks=24 , etc.
 
 If you want to run on N=4 nodes:
 ```
 #SBATCH --nodes=4 --ntasks=32 
 ```

**Comment by denisbertini** [comment]
ah ok , thanks a lot !

**Comment by charlesprouveur** [comment]
If there are no more problems regarding the compilation and the execution on AMD GPU, i think we can close this issue.

**Comment by denisbertini** [comment]
sure ! thanks again !
