### ISSUE TITLE
Failures in the patch creation due to MPI processes etc

### ISSUE THREAD

**Issue by Tissot11** [SmileiPIC/Smilei#676]
I'm running a 2D simulation with Smilei 5.0 (release version). This simulation runs fine for small box size and cells. However, when increasing the number of cells and also the computational resources, I see following type of messages during the patch creation process and simulations do not start.

`[ERROR](0) src/SmileiMPI/SmileiMPI.cpp:234 (init) The MPI library you are using authorizes as upper bound for a tag : 1048575
Regarding the number of patches you are using and the number of MPI process, Smilei will at least generate as larger tag : 1718438
You should use 2 more MPI process, or 2 less patches or change of MPI library.
This is a trough estimation, which depends of the plasma load imbalance.`

This sort of message seem generic, only suggested numbers above may change.  In general, when I increase the resolution of 2D simulations,  I would receive similar kind of messages as above and changing the number of MPI Processes (by a factor of 2) also didn't help.  For this simulation, I had `number of cells =[1638400, 5120]` and `number of patches=[1024*64, 512]`, implying least 20 and 10 cells per patch in each directions. I had used maximum `number of MPI processes 1536  and 768 OpenMP threads` so totalling  to `9216 cores` on `128 nodes`.

If I lower the number of cells and also computing resources (for 2D simulations), then I don't see such kind of messages. Simulations start but they get stuck during the runtime and crash (sometime related to load imbalancing). However, on increasing the computational resources, they run fine and finish with lower number of cells.

 Is there a way to determine a priori minimum computing resources for the simulation to start and finish normally? I had used recent intel compilers and libraries together with newer hdf5. I can upload the namelist if you want.

**Comment by mccoys** [comment]
There is no general recipe. The memory requirements can vary very strongly and depend on the compiler.

In your case, you have an issue with the maximum tag allowed by intelMPI.
I suggest you read this: https://www.intel.com/content/www/us/en/developer/articles/technical/large-mpi-tags-with-the-intel-mpi.html

It seems you should set the following:
```
export MPIR_CVAR_CH4_OFI_TAG_BITS=25
export MPIR_CVAR_CH4_OFI_RANK_BITS=14
```
This allows for tags up to 33554432 and ranks up to 16384.

**Comment by beck-llr** [comment]
What the message meant to say (not very clearly sorry about that we'll have to make it more explicit) is to use **twice as many MPI processes**. That means you should try 24 MPI processes and 3 OpenMP threads per node.

Also note that the openMP threads are spawned per MPI process, not per node. That means you don't have 768 threads but 1536 * 6 threads ( which is equal to your number of cores as it should).

**Comment by Tissot11** [comment]
Ok. Now I understand what the messages actually meant. However, I did change the number of MPI processes by changing the number of nodes, increasing the MPI processes  and also reducing the number of OpenMP threads per MPI process on a single node, but I kept getting these messages. 

I agree that OpenMP threads are per MPI process. I just meant to list all computing resources to highlight that compute power seem to be sufficient for simulating.

**Comment by Tissot11** [comment]
@mccoys suggestions work for suppressing the error related to intel MPI. However, for these large scale 2D simulations, I often run into memory issues. I can try normal tricks to deal with it but can something like adaptive vectorization help? I have not used it till now.

**Comment by beck-llr** [comment]
No, vectorization will probably not be efficient at memory reduction.
If you don't want to increase the computing resources  I would advise again to reduce the number of patches (use larger patches). Each patch comes with some overhead in communication and memory occupancy. It is convenient for better parallelization and load balancing but if memory is a problem you should try to lower these overheads.

Other options are reducing the number of particles per cell or try particle merging if you have very localized peaks of macro-particle densities.

**Comment by Tissot11** [comment]
@beck-llr, many thanks for your suggestions! I'll try to use particle merging which I haven't tried it yet. 

You can close the ticket now.
