### ISSUE TITLE
VectorPatch Compiling Errors

### ISSUE THREAD

**Issue by W-Wuxian** [SmileiPIC/Smilei#678]
## Description

Errors at Compile time.

```bash
Compiling src/picsar_interface/interface.cpp
src/Patch/VectorPatch.cpp: Dans la fonction membre « void VectorPatch::dynamics(Params&, SmileiMPI*, SimWindow*, RadiationTables&, MultiphotonBreitWheelerTables&, double, Timers&, int) »:
src/Patch/VectorPatch.cpp:353:10: erreur: redéclaration de « bool diag_PartEventTracing »
  353 |     bool diag_PartEventTracing {false};
      |          ^~~~~~~~~~~~~~~~~~~~~
src/Patch/VectorPatch.cpp:334:10: note: « bool diag_PartEventTracing » précédemment déclaré ici
  334 |     bool diag_PartEventTracing {false};
      |          ^~~~~~~~~~~~~~~~~~~~~
src/Patch/VectorPatch.cpp:356:42: erreur: « class SmileiMPI » n'a pas de membre nommé « reference_time »; vouliez-vous utiliser « reference_time_ » ?
  356 |         if (diag_PartEventTracing) smpi->reference_time = MPI_Wtime();
      |                                          ^~~~~~~~~~~~~~
      |                                          reference_time_
src/Patch/VectorPatch.cpp:335:12: attention: variable « reference_time » inutilisée [-Wunused-variable]
  335 |     double reference_time;
      |            ^~~~~~~~~~~~~~
src/Patch/VectorPatch.cpp: Dans la fonction membre « void VectorPatch::ponderomotiveUpdateSusceptibilityAndMomentum(Params&, SmileiMPI*, SimWindow*, double, Timers&, int) »:
src/Patch/VectorPatch.cpp:4352:38: erreur: « class SmileiMPI » n'a pas de membre nommé « reference_time »; vouliez-vous utiliser « reference_time_ » ?
 4352 |     if (diag_PartEventTracing) smpi->reference_time = MPI_Wtime();
      |                                      ^~~~~~~~~~~~~~
      |                                      reference_time_

```

## Steps to reproduce the problem

```bash
module purge

module load python-3.10.13/3.10.13
module load gcc-13.2/13.2.0
module load openmpi/5.0.0/gcc/13.2
module load hdf5/1.14.3/openmpi/5.0.0/gcc/13.2

export HDF5_ROOT_DIR=/opt/apps/hdf5-1.12.0-openmpi/
export BUILD_DIR=/root/Smilei-4.8/Install_openmpi5000_gnucomp

make -j 4 config="omptasks part_event_tracing_tasks_on" machine=Cascadelake_gnu
```

## Parameters

- Smilei version:
  `V4.8.0`
- Input Machine file Cascadelake_gnu:
  `CXXFALGS += -O3 -march=cascadelake -mtune=cascadelake -ftree-vectorize -flto`
  `LDFLAGS += -march=cascadelake -mtune=cascadelake`

- Commands or script used to run the faulty simulation ?
  `make -j 4 config="omptasks part_event_tracing_tasks_on" machine=Cascadelake_gnu`
- Computing resources
  - type of computer
  `4 x Intel® Xeon® Platinum 8260 Processor `
  - OS
  `LSB Version:	:core-4.1-amd64:core-4.1-noarch
  Distributor ID:	CentOS
  Description:	CentOS Linux release 7.9.2009 (Core)
  Release:	7.9.2009
  Codename:	Core`

  - C++ compiler (to get some information `g++ --version`)
    g++ (GCC) 13.2.0
  - MPI version
    - `mpic++ --version: g++ (GCC) 13.2.0`
    - `mpic++ -show:  g++ -I/opt/apps/openmpi/5.0.0/gcc/13.2/include -pthread -L/opt/apps/openmpi/5.0.0/gcc/13.2/lib -Wl,-rpath -Wl,/opt/apps/openmpi/5.0.0/gcc/13.2/lib -Wl,--enable-new-dtags -lmpi`
    
  - HDF5 version `h5pcc --version gcc (GCC) 13.2.0`
  - Python version `python --version Python 3.11.5`

**Comment by Z10Frank** [comment]
Hello,
thank you for spotting this, I will soon push a fix for this compilation error.

Meanwhile, can you try changing `smpi->reference_time` to `smpi->reference_time_` in the lines generating the error? At the start of the method `void VectorPatch::dynamics`, can you remove entirely this code block, then `make clean` and compile again?
```
#ifdef _PARTEVENTTRACING
    bool diag_PartEventTracing {false};
    double reference_time;
#endif
```


Task parallelisation is an experimental feature and unfortunately in case of related issues we will likely not progress rapidly because there are other more pressing developments to implement.

**Comment by W-Wuxian** [comment]
Hi, i will try your fix next weekend as soon as possible, ty for you quick
reply!

Le ven. 15 déc. 2023, 13:26, Francesco Massimo ***@***.***> a
écrit :

**Comment by Z10Frank** [comment]
Hello, 
some compilers do not recognise those variables as allowed variables in the OpenMP task directives.
I am using clang 17.0, I have already compiled it before with intel 20. I remember that intel version 18 or 19 may have that problem, I don't know about gcc.

**Comment by Z10Frank** [comment]
Indeed, from the doc https://smileipic.github.io/Smilei/Use/installation.html#advanced-compilation-options : 
```
make config=omptasks   # use OpenMP task parallelization, not supported by old compilers
```

**Comment by Z10Frank** [comment]
I'll close the issue, feel free to reopen it in case of related questions.
