### ISSUE TITLE
some wrong results in simulation

### ISSUE THREAD

**Issue by songlaps** [SmileiPIC/Smilei#68]
Hello, developers,

Thanks for your code! When I use the smilei-v3.5, I met a problem. The input file is very simple as follows, The program works fine, but the results (both Ey and Rho_eon) are completely wrong. I don't know where the problem is.

Thank you!

import math
from numpy import s_

l0 = 2.0 * math.pi
t0 = 2.0 * math.pi

Lx = 64 * l0
Ly = 36 * l0
Tsim = 50 * t0

resx = 32
resy = 32
ppc = 4
dx = l0 / resx
dy = l0 / resy
dt = 0.5 * dx
nsteps = Tsim / dt

den0 = 0.01
laser_fwhm = 5

Main(
    geometry = "2Dcartesian",
    interpolation_order = 2,
    cell_length = [dx,dy],
    grid_length = [Lx,Ly],
    number_of_patches = [64,64],
    timestep = dt,
    simulation_time = Tsim,
    EM_boundary_conditions = [["silver-muller"]],
    random_seed = smilei_mpi_rank
)

Species( 
    name = "eon",
    position_initialization = "random",
    momentum_initialization = "cold",
    particles_per_cell = ppc,
    c_part_max = 1.0,
    mass = 1.0,
    charge = -1.0,
    charge_density = den0,
    pusher = "boris",    
    boundary_conditions = [["remove"]]
)

Species( 
    name = "ion",
    position_initialization = "random",
    momentum_initialization = "cold",
    particles_per_cell = ppc,
    c_part_max = 1.0,
    mass = 1836.0,
    charge = -1.0,
    charge_density = den0,
    pusher = "boris",    
    boundary_conditions = [["remove"]]
)

LaserGaussian2D(
    box_side        = "xmin",
    a0              = 2.,
    focus           = [0., Main.grid_length[1]/2.],
    waist           = 8,
    time_envelope   = tgaussian(center=2**0.5*laser_fwhm, fwhm=laser_fwhm)
)

DiagFields(
    every = 1600,
    subgrid = s_[::2,::2],
    fields = ['Ey','Rho_eon']
)

![image](https://user-images.githubusercontent.com/35225498/48540165-50cbd500-e8f4-11e8-9d6c-d99aaa6d6ff5.png)
![image](https://user-images.githubusercontent.com/35225498/48540248-8f618f80-e8f4-11e8-8b73-a1412ba0e9b8.png)

- 1.

**Comment by mccoys** [comment]
Hello

Did you notice you have a negative charge for ions ?

**Comment by songlaps** [comment]
Thank you for your prompt reply. I did make a low-level mistake. I ran the program again and got the answer I wanted. 

Thanks again！

**Comment by songlaps** [comment]
> Hello
> 
> Did you notice you have a negative charge for ions ?

Thank you for your prompt reply. I did make a low-level mistake. I ran the program again and got the answer I wanted.

Thanks again！
