### ISSUE TITLE
Incorrect Implementation of output time offset

### ISSUE THREAD

**Issue by skuschel** [SmileiPIC/Smilei#681]
## Description

The Smilei documentation explains, that `Bx` and `Bx_m` are supposed to be fields half a timestep apart from each other ( see https://smileipic.github.io/Smilei/Use/namelist.html?highlight=bx_m#external-fields )

Inspecting the h5 output, this offset is not honored: In the h5 output, both Datasets `Bx` and `Bx_m` have the attribute `timeOffset` set to zero, which is correct for `Bx_m`, but wrong for `Bx`.

Compare
```
$ h5ls -rvd Fields0.h5/data/0000001800/Bx_m | grep -4 timeOffset
    Attribute: position {2}
        Type:      native double
        Data:
               0, 0
    Attribute: timeOffset scalar
        Type:      native double
        Data:
               0
    Attribute: unitDimension {7}
```
and 
```
$ h5ls -rvd Fields0.h5/data/0000001800/Bx | grep -4 timeOffset
    Attribute: position {2}
        Type:      native double
        Data:
               0, 0
    Attribute: timeOffset scalar
        Type:      native double
        Data:
               0
    Attribute: unitDimension {7}
```

This was produced by Smilei v5.0.

The correct meaning of this value is outlined in the openpmd standard at https://github.com/openPMD/openPMD-standard/blob/latest/STANDARD.md#required-attributes-for-the-basepath

Please note, that this is not part of a partial openpmd implementation. Partial means, that some attributes may be missing. Here we have an incorrect implementation, as defined values are **redefined**, which is a recipe for disaster, because any analysis software will misunderstand the stagger.  In a partial implementation the value of the timeOffset would just be **omitted** .

**Comment by mccoys** [comment]
Closing this as it will be fixed together with #682
