### ISSUE TITLE
Crash with GPU computing

### ISSUE THREAD

**Issue by Tissot11** [SmileiPIC/Smilei#685]
Hi,

I managed to compiled the Smilei for Nvidia GPUs. But when I am running simulations, they are crashing with this error

`ib_md.c:1550 UCX  WARN  mlx5_1: relaxed order memory access requested, but unsupported`

What could be the reason.

I used following modules 

module load nvhpcsdk/23 cuda/11.8-nvhpcsdk openmpi/4.1 openmpi_gpu/4.1 hdf5-mpi/1.12.2 anaconda/3/2023.03

and a machine file provided by the administrators

`SMILEICXX.DEPS = g++
THRUSTCXX = nvcc

ACCELERATOR_GPU_FLAGS += -w

ACCELERATOR_GPU_FLAGS += -acc=gpu -gpu=cc80 -std=c++14

ACCELERATOR_GPU_FLAGS +=  -I$(NVHPC_ROOT)/math_libs/11.8/include

ACCELERATOR_GPU_KERNEL_FLAGS += -O3 --std c++14 $(DIRS:%=-I%)
ACCELERATOR_GPU_KERNEL_FLAGS += --expt-relaxed-constexpr
ACCELERATOR_GPU_KERNEL_FLAGS += $(shell $(PYTHONCONFIG) --includes)
ACCELERATOR_GPU_KERNEL_FLAGS += -arch=sm_80
ACCELERATOR_GPU_KERNEL_FLAGS += -I$(OPENMPI_HOME)/include
ACCELERATOR_GPU_KERNEL_FLAGS += -I$(HDF5_HOME)/include -I$(NVHPC_ROOT)/math_libs/11.8/include
ACCELERATOR_GPU_FLAGS        += -Minfo=accel # what is offloaded/copied

ACCELERATOR_GPU_FLAGS += -DSMILEI_OPENACC_MODE
ACCELERATOR_GPU_KERNEL_FLAGS += -DSMILEI_OPENACC_MODE

LDFLAGS += -acc=gpu -gpu=cc80 -std=c++14 -cudalib -L$(NVHPC_ROOT)/math_libs/11.8/lib64 \
	-L$(NVHPC_ROOT)/comm_libs/11.8/nccl/lib \
	-L$(NVHPC_ROOT)/comm_libs/11.8/nvshmem/lib \
	-L$(NVHPC_ROOT)/comm_libs/11.8/hpcx/hpcx-2.14/ucc/lib -lucc \
	-Wl,-rpath,$(NVHPC_ROOT)/comm_libs/11.8/hpcx/hpcx-2.14/ucc/lib \
	-Wl,-rpath,$(HDF5_HOME)/lib \
	-Wl,-rpath,$(NVHPC_ROOT)/math_libs/11.8/lib64 \
	-Wl,-rpath,$(ANACONDA_HOME)/lib
CXXFLAGS +=  -D__GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1`

What could be the reason for the crash?

Does Smilei only support OpenMP for AMD GPUs and not Nvidia?

**Comment by Tissot11** [comment]
I attach the std err and out files. According to the admins, the warning is not the cause of crash. They want to know where exactly the crash happens.

[tjob_hybrid.err.8969072.txt](https://github.com/SmileiPIC/Smilei/files/13916751/tjob_hybrid.err.8969072.txt)
[tjob_hybrid.out.8969072.txt](https://github.com/SmileiPIC/Smilei/files/13916752/tjob_hybrid.out.8969072.txt)

**Comment by mccoys** [comment]
It looks like you are using the injector, but I am not sure the injector has been ported to GPU yet.
@charlesprouveur ?

**Comment by Tissot11** [comment]
Yes, I'm using injectors. If this is not ported yet then perhaps I don't need to use GPUs for the time being.

**Comment by Tissot11** [comment]
If Particle injectors being not ported to GPU was the reason for the crash, then you can close this ticket. When do you expect to support particle injectors on GPU?

**Comment by beck-llr** [comment]
Particle injector has not been ported yet on GPU and we can not tell when it will be. I can tell that unfortunately  it is not very high on our priority list at the moment because there are so many other things to do. Any help on the topic is welcome by the way.
