### ISSUE TITLE
Error on MPI 

### ISSUE THREAD

**Issue by obudriga** [SmileiPIC/Smilei#686]
## Description
I was trying to simulate on 1200 cores and I received a file error. I don't know what is the problem.

```
Error file:
[lasintensa0215foilcion-11815181.txt](https://github.com/SmileiPIC/Smilei/files/13947488/lasintensa0215foilcion-11815181.txt)
```

## Steps to reproduce the problem

If relevant, provide a step-by-step guide

## Parameters

- Smilei version ? 
- Input file ? 

[laser3d_gauss_cone3d_10.txt](https://github.com/SmileiPIC/Smilei/files/13947487/laser3d_gauss_cone3d_10.txt)

- Commands or script used to run the faulty simulation ?  [job_sub.txt](https://github.com/SmileiPIC/Smilei/files/13947486/job_sub.txt)

- Computing resources
-
[lasintensa0215foilcion-11815181_out.txt](https://github.com/SmileiPIC/Smilei/files/13947523/lasintensa0215foilcion-11815181_out.txt)

  - type of computer
  - OS
  - C++ compiler (to get some information `g++ --version`)
  - MPI version (`mpic++ --version`, `mpic++ -show`) 
  - HDF5 version (`h5cc --version`)
  - Python version (`python --version`)
  - ...

**Comment by obudriga** [comment]
Error file
[lasintensa0215foilcion-11815181.txt](https://github.com/SmileiPIC/Smilei/files/13947567/lasintensa0215foilcion-11815181.txt)

**Comment by charlesprouveur** [comment]
Did you try to scale down the problem to see when is the problem occuring? ie: does it work properly on one node? 8 nodes ? etc. It could be an issue with a specific node / hardware issue. It says it failed on node 1080 and 1120, can it be replicated?

**Comment by obudriga** [comment]
The similar errors
[lasintensa0215foilcion-11815573.txt](https://github.com/SmileiPIC/Smilei/files/13949024/lasintensa0215foilcion-11815573.txt)
[lasintensa0215foilcion-11815584.txt](https://github.com/SmileiPIC/Smilei/files/13949025/lasintensa0215foilcion-11815584.txt)

**Comment by obudriga** [comment]
I have also other problems. I've been trying using different number of cores and patches but it seems that the job is running but I haven't obtain output data. There were no errors. I don't know what can happen.
[lasintensa0215foilcion-11755575out.txt](https://github.com/SmileiPIC/Smilei/files/13949147/lasintensa0215foilcion-11755575out.txt)
[lasintensa0215foilcion-11808834out.txt](https://github.com/SmileiPIC/Smilei/files/13949148/lasintensa0215foilcion-11808834out.txt)

**Comment by mccoys** [comment]
I could imagine this is a memory issue. The error appears in MPI that is unable to send it receive data. It uses a pointer out of range. Maybe try less particles or more resources and see if this still happens?

**Comment by beck-llr** [comment]
I'm afraid the pair production mecanism creates more particles that your system can handle. I would strongly advise to monitor the number of positron and/or photons and check if that number is not going through the roof. You can do that pretty easily with a performance diagnostic or a particle binning diagnostic.

If that is what actually happens, I would then suggest to look at the Particle merging feature which could help mitigate the number of e+/e- or photons in time.

**Comment by obudriga** [comment]
I used Particle merging for photons and positrons but I received errors in file 
[lasintensa0215foilcion-11816099.txt](https://github.com/SmileiPIC/Smilei/files/13960556/lasintensa0215foilcion-11816099.txt)
The namelist was 
[laser3d_gauss_cone3d_10_partmerg.txt](https://github.com/SmileiPIC/Smilei/files/13960561/laser3d_gauss_cone3d_10_partmerg.txt)
and the script
[job_sub_2000cores.txt](https://github.com/SmileiPIC/Smilei/files/13960568/job_sub_2000cores.txt)

**Comment by beck-llr** [comment]
When does that happen ?
Have you monitored your number of particles ? (with and without merging)
You are using several advanced features of the code at the same time on a large number of cores. You need to understand precisely what is going on because many things could go wrong.
 The merging algorithm needs to be tuned to the property of the distribution function of your particles. Did you make sure it is the case ?

**Comment by mccoys** [comment]
In the future, we ask that, if you are not sure you found a bug, you should use the chatroom 
https://app.element.io/#/room/!LQrdVpOJEohPSWMlmf:matrix.org

If you need more space to write your problem, use the discussions:
https://github.com/SmileiPIC/Smilei/discussions/categories/q-a

Use issues here when you want to report an actual bug or feature request
