### ISSUE TITLE
Integer wrapper for MPI communication

### ISSUE THREAD

**Issue by td-mpcdf** [SmileiPIC/Smilei#687]
https://github.com/SmileiPIC/Smilei/blob/d8e1d8595693c1633ab737bb8e0c5364d8f0a1a8/src/SmileiMPI/SmileiMPI.cpp#L2299

I am not an expert on the code but debugging an MPI problem with the code on our machines, I came across these two routines.  Do they really what is expected? To my understanding, they do not send around an integer, but the address of an integer (truncated to an MPI_INT). This does not make sense on a distributed memory application and should lead to problems.

**Comment by beck-llr** [comment]
Hi
From what I understand here, the variable `integer` is an `int *`.
The function sends `&integer` so that should be an `int`.

In the future please open a gitHub Discussion for that kind of question.

**Comment by beck-llr** [comment]
It looks like you are right but this function has been around for ages and seems to work somehow. We'll look into it.

**Comment by beck-llr** [comment]
Ok it appears to be an old function which is actually not called anymore. There are actually still some of those lurking around. Thanks for reporting it !
