### ISSUE TITLE
Particle Binning: Axes limits [0, '"auto"] bug

### ISSUE THREAD

**Issue by nkehoe** [SmileiPIC/Smilei#688]
## Description

When using the Particle Binning diagnostic and setting the limits on an axes as [0, "auto"] it encounters a bug and only measures up to the rest mass energy of the electron (0.511MeV).  Already talked about and confirmed in element.io.
```
DiagParticleBinning(
    name = 'proton spectra',
	deposited_quantity = "weight",
	every = every,
	species = ['proton'],
	axes = [
		["ekin", 0., 'auto', specbins]
	]
)
```

## Steps to reproduce the problem

If relevant, provide a step-by-step guide

## Parameters

- Smilei version ?
- Input file ?
- Commands or script used to run the faulty simulation ?
- Computing resources
  - type of computer
  - OS
  - C++ compiler (to get some information `g++ --version`)
  - MPI version (`mpic++ --version`, `mpic++ -show`)
  - HDF5 version (`h5cc --version`)
  - Python version (`python --version`)
  - ...

**Comment by mccoys** [comment]
The fix has been pushed to the branch `develop`.
Please check if it works and close.

Thank you for reporting
