### ISSUE TITLE
Choosing output number

### ISSUE THREAD

**Issue by Z10Frank** [SmileiPIC/Smilei#689]
In some simulations I vary the timestep but not the physical time that is simulated, so instead of specifying the output frequency of a diagnostic directly through a certain number of iterations I use a calculation for the number of iterations required for e.g. 100 um of propagation, e.g.:
```
every = int(200*um/dt)
```

This means that to compare the two simulations (which have a different `dt`) at the same physical time I should use a `getAvailableTimesteps()` to obtain the available iteration numbers for the outputs and then choose the respective nth element as argument for `timesteps` in that diagnostic, e.g. for n=10:
```
selected_timestep =  S.Probe.Probe1("Ex").getAvailableTimesteps()[10]
Ex=S.Probe.Probe1("Ex",timesteps=selected_timestep)
```

Would it be possible to add a keyword e.g. `timestep_index` (not to be used together with `timesteps`) to have a more compact command?

```
Ex=S.Probe.Probe1("Ex",timestep_index=10)
```

The last command would be a shortcut for

```
Ex=S.Probe.Probe1("Ex",timesteps=S.Probe.Probe1("Ex").getAvailableTimesteps()[10])
```

**Comment by mccoys** [comment]
Done in commit 0011999c4098290cb8b8443a198aec5c528977f5

The keyword is `timestep_indices`
