### ISSUE TITLE
Possible bug in converting units when a moving window is involved

### ISSUE THREAD

**Issue by zubairy** [SmileiPIC/Smilei#69]
Dear developers, 

I'm new to Smilei and am testing a 2D EM-propagation simulation with Smilei-v3.5. I used happi module to plot the Ey image. The _x_ axis is right in reference unit (first row in the following figures), however, the result with units conversion seems not right after the windows start to move (last figure). Is this a possible bug or there is something wrong with my command: `S.Field(diagNumber=0,field='Ey',moving=True,timesteps=600,units=["um"]).plot(cmap='jet')`

Thanks

![picture1](https://user-images.githubusercontent.com/12051096/48561337-b1760480-e92a-11e8-899d-80e81b7a802f.png)

**Comment by mccoys** [comment]
Hello,

This appears to be a bug : the movement of the window is added in code units without conversion to microns. But it should be.

I will push a fix ASAP.

**Comment by mccoys** [comment]
Actually, there is still a bug with animations

**Comment by zubairy** [comment]
> Actually, there is still a bug with animations

Hi, @mccoys 
Yes, you noticed that. The `plot()` & `animate()` give correct unit results when specifying `timesteps`, howerver, if `timesteps=None`, `animate()` is still not right.

**Comment by mccoys** [comment]
Fixed in 4bfc3886

**Comment by zubairy** [comment]
> Fixed in [4bfc388](https://github.com/SmileiPIC/Smilei/commit/4bfc3886802321a53c46f2014520a332cb8990fc)

`animate()` works well now. Regards

**Comment by zubairy** [comment]
I reopen this issue since `happi` seems to fail to animate in the right way in moving window again.

The following figure show a LWFA result (Smilei Version: bv4.4-706-gb5c12a5a-bmaster) with down-ramp injection at ~300 \lambda. The upper row using `happi` in 4bfc3886 shows the expected result, while in the lower (`happi` in b5c12a5a, HEAD of current master branch), both the x-axis and the data is incorrect (seems like the x-axis failed to catch up with the data). Could you please kindly check is there some other bugs were being introduced into the code? Thanks.

![image](https://user-images.githubusercontent.com/12051096/89154003-ab113b80-d598-11ea-93b6-683649a6f369.png)
