### ISSUE TITLE
Possibility of adding time-dependent ionization rate

### ISSUE THREAD

**Issue by Jaykim9206** [SmileiPIC/Smilei#690]
Hello, 

I am trying to simulate a setup where we can artificially assign ionization rate to generate a charge-neutral plasma at a given location as a function of space and time (i.e. an ionization rate f(x- v t) ). It seems Smilei already has the capability to implement a user-defined rate for ionization as a function of space. 

The user-defined rate as of now can only be a function of particle properties(x,y,z,px,py,pz,id). I did try to just put time in the benchmark input deck (tst1d_11_ionization_from_rate.py), but it gave an error. Would it be possible to somehow pass in additional parameters (such as the simulation time) so that we could define the ionization rate as some function of space and time? 

I would be happy to try some things out by myself if you can point me to where I need to modify the code to achieve this. Or, if some extra work is required, I would be also be happy to follow up on that. Thank you!

Best,
Jihoon

**Comment by mccoys** [comment]
I believe it is possible to use `Main.iteration` in that function. But i have not tested

**Comment by Jaykim9206** [comment]
Thank you! It works exactly as you described/I wanted!

**Comment by soxzofia** [comment]
Could you please show some examples about how to use `Main.iteration` to define a ionization rate function of space and time?

**Comment by Jaykim9206** [comment]
I used something like this .
![image](https://github.com/user-attachments/assets/c66ee181-8b79-4d8e-9367-43b96f5790a2)
![image](https://github.com/user-attachments/assets/b8640b09-d4da-4d0e-bf17-29f2b0e3b295)

**Comment by soxzofia** [comment]
Thank you! It's very helpful!
