### ISSUE TITLE
This requires setting certain spatial attributes of the materials such as dielectric constants and conductivity in the simulation space.

### ISSUE THREAD

**Issue by chipopt** [SmileiPIC/Smilei#691]
Dear developers,

Hello, I am a student who is currently interested in using materials to modulate the incident electric field and generate near fields for accelerating charged particles. This requires setting certain spatial attributes of the materials such as dielectric constants and conductivity in the simulation space.

However, I'm not very familiar with C++ and I'm not sure if the code can simulate this situation. Could you please provide a simple code example that demonstrates how to simulate a plane wave incident on a glass material? Even this simple example would help me understand how to use it. Thank you very much.

Best regards,

**Comment by mccoys** [comment]
Dear @chipopt,
I am not sure I understand what you want to do. If you want to generate near fields, do you mean so sorts of optics for the laser? That is not a good idea to have this done in Smilei. Better have a simulation to generate the laser profile using another code, and input that profile in Smilei

**Comment by chipopt** [comment]
> Dear @chipopt, I am not sure I understand what you want to do. If you want to generate near fields, do you mean so sorts of optics for the laser? That is not a good idea to have this done in Smilei. Better have a simulation to generate the laser profile using another code, and input that profile in Smilei

Dear developer,
I apologize for any confusion caused by my unclear expression. What I meant to ask is whether the FDTD method in the code can simulate the evolution of electric fields when a laser encounters a material (non-vacuum).

**Comment by mccoys** [comment]
I guess it is technically possible to implement. But is there really a good reason to do this? Please provide an example where that would be required
