### ISSUE TITLE
smilei_test passed, but actual run failed

### ISSUE THREAD

**Issue by fyli16** [SmileiPIC/Smilei#692]
Hi, I am switching to the latest v5.0 and compiled the code using impi, intel, and python2. For my example input deck, smilei_test check passed with the output 
[smilei_test.txt](https://github.com/SmileiPIC/Smilei/files/14078241/smilei_test.txt)
But the actual run failed with the output 
[actual_run.txt](https://github.com/SmileiPIC/Smilei/files/14078247/actual_run.txt)
Looks like it is caused by Python but not sure. Any comments would be greatly appreciated.

**Comment by mccoys** [comment]
Your python version is too old. Make sure you specify PYTHONEXE=python3 in your environment

**Comment by fyli16** [comment]
OK, thanks. Now compiled using Python3 (3.9.2). No problems with compiling, smilei_test run, but again failed at actual run with the following error. Seems it suggest database file issue. Any specific Python version should I work with for this latest smilei? Anything I should modify before I compile the code, e.g. the file scripts/compile_tools/python-config.py?  

`
[ERROR](0) src/Tools/PyTools.h:176 (checkPyError) error: db type could not be determined
 --------------------------------------------------------------------------------
Stack trace (most recent call last):
#7    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in
#6    Object "/home1/07918/fyli/src/smilei_2401/smilei_dipole/smilei", at 0x483588, in
#5    Object "/usr/lib64/libc.so.6", at 0x2adf66c17554, in __libc_start_main
#4    Object "/home1/07918/fyli/src/smilei_2401/smilei_dipole/smilei", at 0x9ca79a, in main
#3    Object "/home1/07918/fyli/src/smilei_2401/smilei_dipole/smilei", at 0x7bd698, in Params::Params(SmileiMPI*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)
#2    Object "/home1/07918/fyli/src/smilei_2401/smilei_dipole/smilei", at 0x7d37f7, in PyTools::runPyFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
#1    Object "/home1/07918/fyli/src/smilei_2401/smilei_dipole/smilei", at 0x4ceae8, in PyTools::checkPyError(bool, bool)
#0    Object "/usr/lib64/libpthread.so.0", at 0x2adf63ca24fb, in raise
Aborted (Signal sent by tkill() 216241 872174)`

**Comment by mccoys** [comment]
It is as if your python could not create the file. I think I saw something similar recently but can't remember exactly.

Have you deleted your folder before launching a new simulation?

Or, could you try, from your environment, to write something using the python module p `pickle` or `shelve`?

**Comment by charlesprouveur** [comment]
Also, did you run the new executable in a new folder? (a previous smilei.py in the execution folder can also be a problem)

**Comment by fyli16** [comment]
It works by starting a new folder, thank you for helping!  I am closing it now.
