### ISSUE TITLE
Operations between quantities in Scalar Diagnostic

### ISSUE THREAD

**Issue by Z10Frank** [SmileiPIC/Smilei#693]
Following a user question on the chat, would it be possible to implement operations in the `Scalar` diagnostic as for `Fields` and `Probes`, e.g.:

```
import happi
S=happi.Open()
S.Scalar("Ukin+10*Uelm").plot()
```

**Comment by mccoys** [comment]
Done in commit c98e26e7f153dc9f6a4242b92cee539250e486da
