### ISSUE TITLE
Initial phase for LaserGaussian3D

### ISSUE THREAD

**Issue by III0K** [SmileiPIC/Smilei#696]
## The problem and the context

I can't use two separate linearly polarized gaussian beams created via LaserGaussian3D block to form a circularly polarized one, because where is no option to put an extra phase delay of pi/2 in one linearly polarized beam. For this simple case it is not actually a problem at all, as there is an option "polarization=+1". 
Nevertheless, the problem mentioned above emerges when one tries to form nearly circularly polarized pulse by combining two linearly polarized pulses propagating at small angle. This scheme may be of importance when dealing with high intensity sources of laser pulses (petawatt, femtosecond range), as there is no reliable way of transforming a linearly polarized light of high intensity into circularly polarized one. Moreover, presently there are multiple multi-petawatt-class laser facilities presently being built are designed on multiple beam architecture. 

## The solution

I would like to have an opportunity to chose arbitrary phase delay of pulses created via LaserGaussian3D block. This can be done by adding an exra keyword in corresponding block in the form "delay_phase = 0.0".

**Comment by mccoys** [comment]
Done here: 8acdf36
