### ISSUE TITLE
Shortcut to profiles in the documentation

### ISSUE THREAD

**Issue by GianlucaOberreit** [SmileiPIC/Smilei#703]
Currently, to find the [profiles](https://smileipic.github.io/Smilei/Use/profiles.html) section of the documentation one needs to see the link in the text of the [namelist](https://smileipic.github.io/Smilei/Use/namelist.html) section.

Would it be possible to have a shortcut in the top menus to [profiles](https://smileipic.github.io/Smilei/Use/profiles.html)?

**Comment by mccoys** [comment]
Do you have a suggestion where exactly it would go?

**Comment by GianlucaOberreit** [comment]
I would say one option would be to add the shortcut as an option when hovering over [Write a namelist](https://smileipic.github.io/Smilei/Use/namelist.html) (such as an expansion to the right of the menu). Otherwise, the contents of the [profiles](https://smileipic.github.io/Smilei/Use/profiles.html) page could be added to the [Write a namelist](https://smileipic.github.io/Smilei/Use/namelist.html) section altogether, either right after [lasers](https://smileipic.github.io/Smilei/Use/namelist.html#lasers)/[Laser envelope model](https://smileipic.github.io/Smilei/Use/namelist.html#laser-envelope-model), following the example of [Time selections](https://smileipic.github.io/Smilei/Use/namelist.html#time-selections), or at the end of the page since it is a pretty large section. A third option would be to have it as a section of [Write a namelist](https://smileipic.github.io/Smilei/Use/namelist.html#) and have the hyperlink in that section or the section itself be the hyperlink.

**Comment by beck-llr** [comment]
I actually have faced the same inconvenience when looking specifically for the profiles description. Thanks for suggesting this idea.
Another alternative would be to add the `Profiles` page to the `Understand` sections.

**Comment by mccoys** [comment]
I precisely removed the profiles section from the Namelist page because it was too long ... The only option that I see possible is to add a section with a link. The other options seem to me too involved technically, or not matching the structure of the doc.

**Comment by beck-llr** [comment]
It looks ok to me.

**Comment by GianlucaOberreit** [comment]
Looks nice, thanks!
