### ISSUE TITLE
Unit conversion in PostProcess

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#707]
## Description

I am using a Particle Binning diagnostic with deposit_ quantity as a function to obtain the magnetic field see the example below: 

```
###3# density in y-z plane at 32 um #####
def Dens(particles):
    return particles.weight


DiagParticleBinning(
	deposited_quantity = Dens,
	every = 10.,
  time_average = 1,
	species = ["electron"],
	axes = [
    ["moving_x", 252., 255., 1],
		["y", 0., Main.grid_length[1], 500],
    ["z", 0., Main.grid_length[2], 500]
	]
)

###4##Bx Field in y-z plane at 32 um ####

def Bx_comp(particles):
    return particles.weight*particles.Bx

DiagParticleBinning(
	deposited_quantity = Bx_comp,
	every = 10.,
  time_average = 1,
	species = ["electron"],
	axes = [
    ["moving_x", 252., 255., 1],
		["y", 0., Main.grid_length[1], 500],
    ["z", 0., Main.grid_length[2], 500]
	]
)
```

## Steps to reproduce the problem

In the post process, When I am trying to convert its unit using the pint module. I got an error: "AttributeError: 'float' object has no attribute 'units' ". Input file for the post process script  attached here with. Please help me remove this error. 
[postDiagParticleBinning.txt](https://github.com/SmileiPIC/Smilei/files/14795758/postDiagParticleBinning.txt)

the screen shot for the error also attached here.

<img width="680" alt="Screenshot1" src="https://github.com/SmileiPIC/Smilei/assets/67734147/d31a4b8e-d3ec-45bc-b196-ef105d362bc2">
<img width="683" alt="Screenshot 2" src="https://github.com/SmileiPIC/Smilei/assets/67734147/3f29dace-d138-4ed3-a450-af0fcee51616">

## Parameters

-/opt/cray/pe/python/3.9.13.1/bin/python
                    _            _
  ___           _  | |        _  \ \   Version : 5.0-108-gb4385fc22-master
 / __|  _ __   (_) | |  ___  (_)  | |   
 \__ \ | '  \   _  | | / -_)  _   | |
 |___/ |_|_|_| |_| |_| \___| |_|  | |  
                                 /_/    
 
 

 Reading the simulation parameters
 -------------------------------------------------------------------------------
 HDF5 version 1.12.2
 Python version 3.9.13
	 Parsing pyinit.py
	 Parsing 5.0-108-gb4385fc22-master
	 Parsing pyprofiles.py
  - ...

**Comment by mccoys** [comment]
This should be resolved now in the develop branch. @Sanjeev273 can you try if it works for you?
