### ISSUE TITLE
Keeping track of number of MPI processes and OpenMP threads

### ISSUE THREAD

**Issue by Z10Frank** [SmileiPIC/Smilei#709]
In cases where a log file is not present (e.g. running with just a `mpirun -n ...` without redirecting the output) or lost, it would be useful to write the number of MPI processes and OpenMP threads that were used for a simulation, for example in the `info.shelf` or `smilei.py` as suggested by @mccoys .

**Comment by mccoys** [comment]
Note that `smilei_mpi_size` already provides the number of MPI processes:
https://smileipic.github.io/Smilei/Use/namelist.html#smilei_mpi_size

It is available through happi `S.namelist.smilei_mpi_size`

**Comment by Z10Frank** [comment]
That's really good, so only the number of OpenMP processes should be added.

**Comment by mccoys** [comment]
Added `smilei_omp_threads` and `smilei_total_cores` in develop
1fc01c700a
