### ISSUE TITLE
Error with "Collisions" block

### ISSUE THREAD

**Issue by Nikolai-mephi** [SmileiPIC/Smilei#712]
Dear Smilei developers,

I have encountered an error appearing when I try to run a simulation with the "Collisions" block included in the namelist. It started to appear only with the recent version of Smilei -- 5.0-185-g5954530c6-master. I have successfully launched the same simulation with Smilei-v4.7 and had no error messages or any incorrect behavior.

The error message itself is not very detailed. It appears when the simulation gets into the PIC loop and tries to calculate the first timestep. The message says:

"Stack trace (most recent call last) in thread 5170:
Floating point exception (core dumped)"

The "Stack trace" line does not always appear, but the "Floating point exception" message does.

The namelist for the simulation is attached.
[namelist.txt](https://github.com/SmileiPIC/Smilei/files/15090850/namelist.txt)

I tried to run this simulation on multiple desktop computers with the recent Ubuntu (22.04.4 LTS) or Mint distributions and Smilei-v5.0, and got the same error every time.

Maybe some of the parameters of the "Species" blocks in my namelist now, with the recent Smilei, are somehow incompatible with the "Collisions"? 

Looking forward to your help.

**Comment by mccoys** [comment]
I can reproduce the bug and will look into it. Thank you for reporting.

Note: do not use `random_seed = smilei_mpi_rank`. This was useful for very old smilei verisons

**Comment by mccoys** [comment]
An error was recently introduced, wrongly checking for 0 particles in a cell. It is fixed in 4564449
