### ISSUE TITLE
Deprecated pyplot register_cmap

### ISSUE THREAD

**Issue by hwlr0** [SmileiPIC/Smilei#722]
## Description

I just messed with my VM and had to reinstall everything. It appears that the latest version of Matplotlib (3.9.0) is not compatible with happi. Indeed, happi uses the function matplotlib.pyplot.register_cmap, which is not present in matplotlib anymore:

[https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.6.0.html#pending-deprecation-top-level-cmap-registration-and-access-functions-in-mpl-cm](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.6.0.html#pending-deprecation-top-level-cmap-registration-and-access-functions-in-mpl-cm)
[https://github.com/matplotlib/matplotlib/issues/20853](https://github.com/matplotlib/matplotlib/issues/20853)

## Steps to reproduce the problem

Just try to happi.Open() a simulation with matplotlib v3.9.

```
  File "/home/wsl_howel/Smilei/happi/_Utils.py", line 45, in register
    matplotlib.pyplot.register_cmap(cmap=cmap)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'matplotlib.pyplot' has no attribute 'register_cmap'
```

## Parameters

- Smilei 5.0
- Matplotlib 3.9.0

**Comment by mccoys** [comment]
Thanks for the report. Will fix soon. In the meantime you can replace the function by `matplotlib.colormaps.register(cmap)`

**Comment by hwlr0** [comment]
Okay, thanks

**Comment by mccoys** [comment]
Should be solved in branch develop. Please reopen if it persists
