### ISSUE TITLE
problems with species creation while using parallelization

### ISSUE THREAD

**Issue by sjgrimm** [SmileiPIC/Smilei#723]
When using the following [namelist.txt](https://github.com/user-attachments/files/15545099/namelist.txt) (converted to .txt as I cannot upload .py) with `smilei namelist.py`(so without parallelization), I get the following output for the species creation summary:

```
 Species creation summary
 -------------------------------------------------------------------------------
Species 0 (Material2_ion) created with 4194304 particles
Species 1 (Material2_electron) created with 22544384 particles
Species 2 (Material1_ion) created with 3670016 particles
Species 3 (Material1_electron) created with 73400320 particles
```

When I do `mpirun -n 8 smilei namelist.py`, however, I get:

```
Species creation summary
-------------------------------------------------------------------------------
Species 0 (Material1_ion) created with 3997696 particles
Species 1 (Material1_electron) created with 41615360 particles
Species 2 (Material2_ion) created with 3866624 particles
Species 3 (Material2_electron) created with 54329344 particles
```

I included a print statement in the code in line 123. There the actual number of particles per species is calculated (number\_of\_cells\_x \* number\_of\_cells\_y \* particles\_per\_cell). This yields:

```
Material1_ion  has  7  particles per cell. Consequently,  3670016  particles should be created.
Material1_electron  has  140  particles per cell. Consequently,  73400320  particles should be created.
Material2_ion  has  8  particles per cell. Consequently,  4194304  particles should be created.
Material2_electron  has  43  particles per cell. Consequently,  22544384  particles should be created.
```

This is the same result as the one I get with `smilei namelist.py`.

You can also see that there is something wrong for `mpirun -n 8 smilei namelist.py`, if you take a look at the ParticleBinning Diagnostics I included:

![grafik](https://github.com/SmileiPIC/Smilei/assets/150433403/b65f0ef8-4900-462f-8adb-baf40eb6a6e1)

I think that this is a problem with the patch-initialization in parallel mode. I tried different density profiles and different patch distributions. The issue persists.

**Comment by mccoys** [comment]
@sjgrimm can you confirm this was tested with develop?

**Comment by sjgrimm** [comment]
Yes, it was tested with develop.

**Comment by sjgrimm** [comment]
I also tested it on a cluster and on a laptop. (And on develop at commits 5954530c6b91ba74189809ea7204cff5a5c48aa7 and e43c85fdfa51b8e761fbcbd31e1540d18f2d9d31.)

**Comment by mccoys** [comment]
I suspect that the problem lies in your use of unordered python objects such as sets and dictionaries, meaning that they are not guaranteed to be looped in the same order as that appearing in your code. Each MPI rank may thus create species in different orders, leading to your error.
