### ISSUE TITLE
Installing SMILEI on ubuntu

### ISSUE THREAD

**Issue by emil-mouz** [SmileiPIC/Smilei#73]
Hello,

I encounter the following problem while trying to install smilei-v4.0.0 in ubuntu 18, so when i compile smilei the following message appears in the terminal

Compiling src/Checkpoint/hdf5-1.10.4/config/cmake_ext_mod/GetTimeOfDayTest.cpp
src/Checkpoint/hdf5-1.10.4/config/cmake_ext_mod/GetTimeOfDayTest.cpp: In function ‘int main(int, char**)’:
src/Checkpoint/hdf5-1.10.4/config/cmake_ext_mod/GetTimeOfDayTest.cpp:23:19: error: aggregate ‘main(int, char**)::timeval t1’ has incomplete type and cannot be defined
    struct timeval t1;
                   ^~
src/Checkpoint/hdf5-1.10.4/config/cmake_ext_mod/GetTimeOfDayTest.cpp:24:4: error: ‘gettimeofday’ was not declared in this scope
    gettimeofday(&t1, 0x00);
    ^~~~~~~~~~~~
makefile:176: recipe for target 'build/src/Checkpoint/hdf5-1.10.4/config/cmake_ext_mod/GetTimeOfDayTest.o' failed
make: *** [build/src/Checkpoint/hdf5-1.10.4/config/cmake_ext_mod/GetTimeOfDayTest.o] Error 1

As i suspect there is a problem with the gettimeoftheday function or something. 
Does anyone knows how to fix this?

**Comment by jderouillat** [comment]
Hi,
It seems that you installed HDF5 in the `src` repository of Smilei.  
Can you move it aside of `src` : 
```bash
$ mv src/Checkpoint/hdf5-1.10.4 .
```
Regards

Julien

**Comment by emil-mouz** [comment]
Thank you very much it worked!

Στις Δευ, 10 Δεκ 2018 στις 11:17 π.μ., ο/η jderouillat <
notifications@github.com> έγραψε:

**Comment by jderouillat** [comment]
Good to hear it. The Smilei's build system was lost.  
When we execute the `make` command we scan all directory in `src` to try to compile ```c++``` files so here it was in trouble with HDF5 files which was maybe requiring more compilation options or dependencies.
