### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by Nkehoe-QUB** [SmileiPIC/Smilei#739]
## Description

The HPC I use got a software upgrade and so I need to rebuild python with updated HDF5 etc. When building, from a clean git clone, I get the following error: `make: execvp: <Path to python environment>: Permission denied`. I set HDF5_ROOT and PYTHONHOME variable.

```
If available, copy-paste faulty code, warnings, errors, etc.
```

## Steps to reproduce the problem

If relevant, provide a step-by-step guide

## Parameters

- Smilei version ?
- Input file ?
- Commands or script used to run the faulty simulation ?
- Computing resources
  - type of computer
  - OS
  - C++ compiler (to get some information `g++ --version`)
  - MPI version (`mpic++ --version`, `mpic++ -show`)
  - HDF5 version (`h5cc --version`)
  - Python version (`python --version`)
  - ...

**Comment by charlesprouveur** [comment]
This is not a bug,  please contact the admin support of your hpc cluster.
