### ISSUE TITLE
GPU Quadro M5000 Installation Failed

### ISSUE THREAD

**Issue by W-Wuxian** [SmileiPIC/Smilei#744]
Hi, please review the attached 
[makelog2.log](https://github.com/user-attachments/files/16976073/makelog2.log)
as a result of the following configuration:
```bash
conda activate smilei_env
module load nvhpc-hpcx-cuda12/ phdf5/nvhpc/
export GPU_COMPILER=nvcc
export SMILEICXX=nvc++
export BUILD_DIR=/opt/apps/libsoft/smilei/nvhpc/5.1
export PYTHONEXE=/opt/apps/miniconda3/env/root/envs/smilei_gpu_env/bin/python
export HDF5_ROOT_DIR=/opt/apps/fileformat/phdf5/nvhpc/1.14.3

export CXXFLAGS="-O3 -march=cascadelake -mtune=cascadelake -noswitcherror -w -v -tp=cascadelake -gpu=cc50 -acc=gpu -std=c++14  -lcurand -cudalib=curand -Minfo=accel -D__GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1"
export GPU_COMPILER_FLAGS="-O3 --std c++14 -arch=sm_50 -v --expt-relaxed-constexpr"
export LDFLAGS="-acc=gpu -gpu=cc50 -v -std=c++14 -cudalib=curand -lcudart -lcurand -lacccuda"
export SMILEICXX_DEPS=g++

make -j 12 config="verbose noopenmp gpu_nvidia" 2>&1 | tee makelog2.log
```
- Computing resources
  - type of computer : Cluster NUMA node + 1 GPU Quadro M5000
  - OS : Linux Ubuntu 22.04.4 LTS
  - NVIDIA-SMI 555.42.06              Driver Version: 555.42.06      CUDA Version: 12.5  
  - C++ compiler g++ (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
  - MPI version:
    +  `mpic++ --version`:
```bash
nvc++ 24.7-0 64-bit target on x86-64 Linux -tp cascadelake 
NVIDIA Compilers and Tools
Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
```
  + `mpic++ -show`:
```bash
nvc++ -I/opt/apps/nvidia-hpc-sdk/24.7/Linux_x86_64/24.7/comm_libs/12.5/hpcx/hpcx-2.19/ompi/include -I/opt/apps/nvidia-hpc-sdk/24.7/Linux_x86_64/24.7/comm_libs/12.5/hpcx/hpcx-2.19/ompi/include/openmpi -I/opt/apps/nvidia-hpc-sdk/24.7/Linux_x86_64/24.7/comm_libs/12.5/hpcx/hpcx-2.19/ompi/include/openmpi/opal/mca/hwloc/hwloc201/hwloc/include -I/opt/apps/nvidia-hpc-sdk/24.7/Linux_x86_64/24.7/comm_libs/12.5/hpcx/hpcx-2.19/ompi/include/openmpi/opal/mca/event/libevent2022/libevent -I/opt/apps/nvidia-hpc-sdk/24.7/Linux_x86_64/24.7/comm_libs/12.5/hpcx/hpcx-2.19/ompi/include/openmpi/opal/mca/event/libevent2022/libevent/include -pthread -L/opt/apps/nvidia-hpc-sdk/24.7/Linux_x86_64/24.7/comm_libs/12.5/hpcx/hpcx-2.19/ompi/lib -Wl,-rpath -Wl,/opt/apps/nvidia-hpc-sdk/24.7/Linux_x86_64/24.7/comm_libs/12.5/hpcx/hpcx-2.19/ompi/lib -Wl,--enable-new-dtags -lmpi
```
  - HDF5 version (`h5cc --version`):
 ```bash
gcc (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
  - Python version (`python --version`) : `Python 3.12.4`
  - CXXFLAGS= `-noswitcherror` 

_Originally posted by @W-Wuxian in https://github.com/SmileiPIC/Smilei/issues/742#issuecomment-2345641109_

**Comment by charlesprouveur** [comment]
As said in https://forums.developer.nvidia.com/t/failed-installation-of-smilei-gpu-nvidia-quadro-m5000/306953
This problème is nvhpc 24.7 specific, 24.5 works fine.

**Comment by W-Wuxian** [comment]
> As said in https://forums.developer.nvidia.com/t/failed-installation-of-smilei-gpu-nvidia-quadro-m5000/306953 This problem is nvhpc 24.7 specific, 24.5 works fine.

Funny I had post this Github ticket on Nvidia, ([it is actually my post](https://forums.developer.nvidia.com/t/failed-installation-of-smilei-gpu-nvidia-quadro-m5000/306953))  to get a useful answer. If you don't want to help people with your code just close your issue section.

**Comment by W-Wuxian** [comment]
> As said in https://forums.developer.nvidia.com/t/failed-installation-of-smilei-gpu-nvidia-quadro-m5000/306953 This problem is nvhpc 24.7 specific, 24.5 works fine.

**Hi it is actually my nvidia ticket that you point me out, but I still get errors, please review the following ticket:**

the "-cuda" option actually fix previous errors msg, but i got new one related to `constexpr` see the attached MAKELOG.log file.
[MAKELOG.log|attachment](upload://pttW4Adfssa8UY4kLOUBMZDSINM.log) (130.2 KB)

to reproduce the error, here is the step by step:
```
conda activate smilei_env
module load nvhpc-hpcx-cuda12/ phdf5/nvhpc/
source NVIDIA_SMILEI_ENV
make -j12 machine="machine_file" config="verbose gpu_nvidia" 2>&1 | tee MAKELOGlog
```

I created a **NVIDIA_SMILEI_ENV.sh**:
```bash
export BUILD_DIR=/opt/apps/libsoft/smilei/nvhpc/5.1

export GPU_COMPILER=nvcc
export SMILEICXX=nvc++

export PYTHONEXE=/opt/apps/miniconda3/env/root/envs/smilei_gpu_env/bin/python
export HDF5_ROOT_DIR=/opt/apps/fileformat/phdf5/nvhpc/1.14.3
```
and used this **mahine_file**:
```bash
SMILEICXX_DEPS = g++
# Options pour nvcxx (Compilateur C++ de NVHP)
CXXFLAGS += -w -v -cuda -noswitcherror
CXXFLAGS += -tp=cascadelake -gpu=cc50 -acc=gpu -std=c++14  -lcurand -cudalib=curand
CXXFLAGS += -Minfo=accel # what is offloaded/copied
CXXFLAGS += -D__GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1

# Options pour NVCC (Compilateur CUDA)
GPU_COMPILER_FLAGS += -O3 --std c++14 -arch=sm_50 -v # --compiler-bindir="mpicc"
GPU_COMPILER_FLAGS += --expt-relaxed-constexpr

LDFLAGS += -acc=gpu -gpu=cc50 -v -std=c++14 -cudalib=curand -lcudart -lcurand -lacccuda
```

**Comment by charlesprouveur** [comment]
Your attachment is missing (MAKELOG.log)

**Comment by W-Wuxian** [comment]
> * but also internally to add on top of the support we provide through element. So we like to provide support and intend to continue doing so but consider this is a lot of work for a small team. Please understand that support might not be provided as fast as you would hope for as we all have a lot of work on our

I would like to apologize for my toxic behavior, and thank you and your team for your patience and teaching. I was only focused on myself without thinking about all your constraints. I repost the error log here [issue745](https://github.com/SmileiPIC/Smilei/issues/745).
