### ISSUE TITLE
Installation Failed  on NVIDIA QUADRO M5000

### ISSUE THREAD

**Issue by W-Wuxian** [SmileiPIC/Smilei#745]
As said in https://forums.developer.nvidia.com/t/failed-installation-of-smilei-gpu-nvidia-quadro-m5000/306953
This problem is nvhpc 24.7 specific, 24.5 works fine.

_Originally posted by @charlesprouveur in https://github.com/SmileiPIC/Smilei/issues/744#issuecomment-2355616325_

> As said in https://forums.developer.nvidia.com/t/failed-installation-of-smilei-gpu-nvidia-quadro-m5000/306953 This problem is nvhpc 24.7 specific, 24.5 works fine.

**Hi it is actually my nvidia ticket that you point me out, but I still get errors, please review the following ticket:**

the "-cuda" option actually fix previous errors msg, but i got new one related to `constexpr` see the attached MAKELOG.log file.
[MAKELOG.log](https://github.com/user-attachments/files/17028896/MAKELOG.log)

to reproduce the error, here is the step by step:
```
conda activate smilei_env
module load nvhpc-hpcx-cuda12/ phdf5/nvhpc/
source NVIDIA_SMILEI_ENV
make -j12 machine="machine_file" config="verbose gpu_nvidia" 2>&1 | tee MAKELOGlog
```

I created a **NVIDIA_SMILEI_ENV.sh**:
```bash
export BUILD_DIR=/opt/apps/libsoft/smilei/nvhpc/5.1

export GPU_COMPILER=nvcc
export SMILEICXX=nvc++

export PYTHONEXE=/opt/apps/miniconda3/env/root/envs/smilei_gpu_env/bin/python
export HDF5_ROOT_DIR=/opt/apps/fileformat/phdf5/nvhpc/1.14.3
```
and used this **mahine_file**:
```bash
SMILEICXX_DEPS = g++
# Options pour nvcxx (Compilateur C++ de NVHP)
CXXFLAGS += -w -v -cuda -noswitcherror
CXXFLAGS += -tp=cascadelake -gpu=cc50 -acc=gpu -std=c++14  -lcurand -cudalib=curand
CXXFLAGS += -Minfo=accel # what is offloaded/copied
CXXFLAGS += -D__GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1

# Options pour NVCC (Compilateur CUDA)
GPU_COMPILER_FLAGS += -O3 --std c++14 -arch=sm_50 -v # --compiler-bindir="mpicc"
GPU_COMPILER_FLAGS += --expt-relaxed-constexpr

LDFLAGS += -acc=gpu -gpu=cc50 -v -std=c++14 -cudalib=curand -lcudart -lcurand -lacccuda
```

**Comment by mccoys** [comment]
Maybe this is not well written `--std c++14` ? in the `GPU_COMPILER_FLAGS`.
Should it be `--std=c++14`? Or is it the same?

**Comment by mccoys** [comment]
Ok. I think it might have something to do with this flag as the `constexpr` error is supposed to happen with c++11 or below. That's the reason for this flag if I remember correctly. Could you give the output of `make env` just in case?

**Comment by charlesprouveur** [comment]
@mccoys  the first issue here for me is that @W-Wuxian is using nvhpc 24.7 according to his log.
 The second is trying to compile for old hardware with cc50 capabilities. Once you compile smilei with nvhpc 24.5, you will encounter the following error 
 ```
 
src/Projector/Projector3D2OrderGPUKernelCUDAHIP.cu(85): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)
                      ::atomicAdd( a_pointer, a_value );
                      ^
/local/home/cprouveur/tools/nvhpc_24.5/Linux_x86_64/24.5/cuda/12.4/include/sm_20_atomic_functions.hpp(82): note #3326-D: function "atomicAdd(float *, float)" does not match because argument #1 does not match parameter
  static __inline__ __attribute__((device)) float atomicAdd(float *address, float val)
 (...)
  ```
  because if i am understanding https://forums.developer.nvidia.com/t/atomicadd-showing-error-no-instance-of-overloaded-function-atomicadd-mathes-the-argument-list/244087 this right, double atomic were not yet implemented in nvhpc. 
 In the end a lot of time is going to be spent for a very limited payoff.
 Unless there is a very good reason, i would suggest switching to a different workstation / a cluster.

**Comment by W-Wuxian** [comment]
> Ok. I think it might have something to do with this flag as the `constexpr` error is supposed to happen with c++11 or below. That's the reason for this flag if I remember correctly. Could you give the output of `make env` just in case?

Here is the attached `make env` file log
[MAKEENV.log](https://github.com/user-attachments/files/17040297/MAKEENV.log)

**Comment by charlesprouveur** [comment]
Very interesting, i did not see such behavior before. What does "echo $CXXFLAGS" before and during compilation? 
( i can imagine setting "export CXXFLAGS = " before the compilation if you see std=c++11 by default.

As the nvidia person mentionned, using -cuda  in CXXFLAGS gives an issue for 3 files (MultiphotonBreitWheeler.cpp, RadiationMonteCarlo.cpp and  RadiationNiel.cpp), i would recommend switching to nvhpc 24.5 to avoid that entirely. (basically we compile .cpp files with nvc++ for the openAcc directives, we do not need cuda for these in theory.

**Comment by mccoys** [comment]
Maybe we should also rethink the way we handle compilers in the `makefile`. We use a `COMPILER_INFO` variable that is very ill-formed for `nvc++`

**Comment by mccoys** [comment]
@W-Wuxian If you closed the issue because it was solved, it would be interesting for other to know what was the solution. Was it about the c++11 flag?

@charlesprouveur I believe there is still something to be clarified with `COMPILER_INFO` as noted above. Should we reopen to fix this point?

**Comment by W-Wuxian** [comment]
> @W-Wuxian If you closed the issue because it was solved, it would be interesting for other to know what was the solution. Was it about the c++11 flag?
> 
> @charlesprouveur I believe there is still something to be clarified with `COMPILER_INFO` as noted above. Should we reopen to fix this point?

Sorry, no I closed it because it seems impossible to solve it and I was running out of solution and unable to force -std=C++14. As suggest I will try to install it on other cluster with newer GPU.

**Comment by mccoys** [comment]
One basic way to try to solve it temporarily would be to open the 'makefile' and replace every mention of c++11 by c++14

**Comment by charlesprouveur** [comment]
Indeed, you run into the issue I mentionned above for 3 files (MultiphotonBreitWheeler.cpp, RadiationMonteCarlo.cpp and RadiationNiel.cpp) . You can either remove -cuda (but it seems necessary in your case due to nvhpc 24.7) or you can run the compilation of the 3 object files manually without the -cuda ie on my system:

```

mpicxx -w -gpu=cc50 -acc=gpu --std c++14  -lcurand -cudalib=curand -Minfo=accel  -D__GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1  -D__VERSION=\"5.1-35-ge9f600df5-develop\" -DOMPI_SKIP_MPICXX -std=c++14  -I/local/home/tools/hdf5_nvcc/HDF5_nvhpc24.5/hdf5-1.14.4-3/install//include -Isrc -Isrc/Species -Isrc/PartCompTime -Isrc/Pusher -Isrc/Checkpoint -Isrc/Collisions -Isrc/Params -Isrc/Tools -Isrc/Field -Isrc/ElectroMagnSolver -Isrc/ElectroMagn -Isrc/ElectroMagnBC -Isrc/DomainDecomposition -Isrc/Projector -Isrc/Profiles -Isrc/MultiphotonBreitWheeler -Isrc/Interpolator -Isrc/ParticleInjector -Isrc/Merging -Isrc/Radiation -Isrc/Particles -Isrc/Python -Isrc/picsar_interface -Isrc/MovWindow -Isrc/Ionization -Isrc/Diagnostic -Isrc/ParticleBC -Isrc/Patch -Isrc/SmileiMPI -Ibuild/src/Python -I/usr/include/python3.8 -I/usr/include/python3.8 -I/local/home/cprouveur/.local/lib/python3.8/site-packages/numpy/core/include -DSMILEI_USE_NUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -O3 -g -D__DETAILED_TIMERS -DSMILEI_ACCELERATOR_GPU -DSMILEI_ACCELERATOR_GPU_OACC -c src/MultiphotonBreitWheeler/MultiphotonBreitWheeler.cpp -o build/src/MultiphotonBreitWheeler/MultiphotonBreitWheeler.o
mpicxx -w -gpu=cc50 -acc=gpu --std c++14  -lcurand -cudalib=curand -Minfo=accel  -D__GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1  -D__VERSION=\"5.1-35-ge9f600df5-develop\" -DOMPI_SKIP_MPICXX -std=c++14  -I/local/home/tools/hdf5_nvcc/HDF5_nvhpc24.5/hdf5-1.14.4-3/install//include -Isrc -Isrc/Species -Isrc/PartCompTime -Isrc/Pusher -Isrc/Checkpoint -Isrc/Collisions -Isrc/Params -Isrc/Tools -Isrc/Field -Isrc/ElectroMagnSolver -Isrc/ElectroMagn -Isrc/ElectroMagnBC -Isrc/DomainDecomposition -Isrc/Projector -Isrc/Profiles -Isrc/MultiphotonBreitWheeler -Isrc/Interpolator -Isrc/ParticleInjector -Isrc/Merging -Isrc/Radiation -Isrc/Particles -Isrc/Python -Isrc/picsar_interface -Isrc/MovWindow -Isrc/Ionization -Isrc/Diagnostic -Isrc/ParticleBC -Isrc/Patch -Isrc/SmileiMPI -Ibuild/src/Python -I/usr/include/python3.8 -I/usr/include/python3.8 -I/local/home/cprouveur/.local/lib/python3.8/site-packages/numpy/core/include -DSMILEI_USE_NUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -O3 -g -D__DETAILED_TIMERS -DSMILEI_ACCELERATOR_GPU -DSMILEI_ACCELERATOR_GPU_OACC -c src/Radiation/RadiationMonteCarlo.cpp -o build/src/Radiation/RadiationMonteCarlo.o
mpicxx -w -gpu=cc50 -acc=gpu --std c++14  -lcurand -cudalib=curand -Minfo=accel  -D__GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1  -D__VERSION=\"5.1-35-ge9f600df5-develop\" -DOMPI_SKIP_MPICXX -std=c++14  -I/local/home/tools/hdf5_nvcc/HDF5_nvhpc24.5/hdf5-1.14.4-3/install//include -Isrc -Isrc/Species -Isrc/PartCompTime -Isrc/Pusher -Isrc/Checkpoint -Isrc/Collisions -Isrc/Params -Isrc/Tools -Isrc/Field -Isrc/ElectroMagnSolver -Isrc/ElectroMagn -Isrc/ElectroMagnBC -Isrc/DomainDecomposition -Isrc/Projector -Isrc/Profiles -Isrc/MultiphotonBreitWheeler -Isrc/Interpolator -Isrc/ParticleInjector -Isrc/Merging -Isrc/Radiation -Isrc/Particles -Isrc/Python -Isrc/picsar_interface -Isrc/MovWindow -Isrc/Ionization -Isrc/Diagnostic -Isrc/ParticleBC -Isrc/Patch -Isrc/SmileiMPI -Ibuild/src/Python -I/usr/include/python3.8 -I/usr/include/python3.8 -I/local/home/cprouveur/.local/lib/python3.8/site-packages/numpy/core/include -DSMILEI_USE_NUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -O3 -g -D__DETAILED_TIMERS -DSMILEI_ACCELERATOR_GPU -DSMILEI_ACCELERATOR_GPU_OACC -c src/Radiation/RadiationNiel.cpp -o build/src/Radiation/RadiationNiel.o

```
