### ISSUE TITLE
Ability to Reconstruct Electromagnetic Fields from One Species of Macroparticle Data Post-Simulation

### ISSUE THREAD

**Issue by strugglepanda** [SmileiPIC/Smilei#747]
## The problem and the context

Dear developers, I am a user of Smilei for particle-in-cell (PIC) simulations and have greatly appreciated its capabilities in my research. In my recent work, I have completed simulations where I have access to the macroparticles' positions and moments at various timesteps. My goal is to reconstruct the electromagnetic fields induced specifically by one species of macroparticles and analyze these fields in detail.

Currently, I haven't found a built-in functionality in Smilei that allows for reconstructing electromagnetic fields solely from existing particle data of a specific species. This makes it challenging to analyze the electromagnetic fields corresponding to particular particle species configurations after the simulation has been completed. This feature could be helpful for many users.

**Comment by strugglepanda** [comment]
> Hi, Unfortunately, I don't think there is a general way to do what you are asking. Generation of EM fields is a collective process involving all species. The only case where that makes sense is when all processes are small enough in amplitude to be linear. However, this case is so specific that I don't think there is a good reason to have a new feature. You can simply run another simulation with only 1 species to isolate its effect.

Dear Developer,

Thank you for your timely reply. Indeed, EM field generation inherently involves all species. In my study, I am trying to determine which species contribute most significantly to the radiation.

Since Smilei already allows for diagnosing the current of one species on the grid, I was wondering if it's possible to incorporate this current source with the FDTD solver to reconstruct the EM fields for a specific species in post-processing. Although this feature may only apply to specific cases, it would be very helpful for detailed physics analysis. Many users could benefit from this addition if it is feasible to implement.

Any of your suggestions or comments would be helpful!

**Comment by mccoys** [comment]
Again, this only makes sense in the linear regime where species don't interact with each other. If your simulation is in this regime (which is probably not the case), you can simply run the simulation again with 1 species only. If your simulation is not in this regime, then isolating the role of 1 species does not make sense.
