### ISSUE TITLE
Compilation with GPU accelerated nodes on the HPC Niflheim

### ISSUE THREAD

**Issue by JohanKoelsenDeWit** [SmileiPIC/Smilei#749]
Dear SMILEI team,

I'm having trouble compiling SMILEI with GPU accelerated nodes on the HPC,  Niflheim’s, NVIDIA A100 nodes.
I'm not experienced with GPU accelerated nodes, and it is very likely me that is making the mistakes. However, if it is not too inconvenient, I was hoping you could help me compile SMILEI with GPU acceleration on Niflheim successfully?

I successfully compile with intel/2023a for CPU but encounter an issue when using CUDA for the A100 GPUs. After exporting the GPU compiler to nvcc and running make config=gpu_nvidia, I get the following error:
`
src/Params/Params.h:421:5: error: body of ‘constexpr’ function ‘static constexpr int Params::getGPUClusterWidth(int)’ not a return-statement
  421 |     }
      |     ^
src/Params/Params.h: In static member function ‘static constexpr int Params::getGPUClusterGhostCellBorderWidth(int)’:
src/Params/Params.h:469:5: error: body of ‘constexpr’ function ‘static constexpr int Params::getGPUClusterGhostCellBorderWidth(int)’ not a return-statement
  469 |     }
      |     ^
src/Params/Params.h: In static member function ‘static constexpr int Params::getGPUInterpolationClusterCellVolume(int, int)’:
src/Params/Params.h:494:5: error: body of ‘constexpr’ function ‘static constexpr int Params::getGPUInterpolationClusterCellVolume(int, int)’ not a return-statement
  494 |     }
      |     ^
`

I see in your installation guide that several flags must be supplied in  $CXXFLAGS and $GPU_COMPILER_FLAGS, and that your environment variables for jean_zay_gpu_A100 are set to:

export CXXFLAGS="-O3 -std=c++14 -fopenmp -D__GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1"
export GPU_COMPILER_FLAGS="-O3 --std=c++14 -arch=sm_80 --expt-relaxed-constexpr"
export LDFLAGS="-lcudart -lcurand -lgomp"

Neither I or the admins for Niflheim are however sure what these flags must be set to in my case. 

Could you please advice me to the correct CXXFLAGS and GPU_COMPILER_FLAGS for Niflheim’s A100 partition?. :-)

Thank you for your help, and kind regards, Johan

**Comment by charlesprouveur** [comment]
Hi Johan, 
We will help you with that.
FIrst, could you open a discussion for this instead of an issue (https://github.com/SmileiPIC/Smilei/discussions)
For us compilation support should not go into "issues"
or we can proceed on element: https://app.element.io/#/room/!LQrdVpOJEohPSWMlmf:matrix.org

**Comment by charlesprouveur** [comment]
To your question:
 Could you specify what environment you are using / what modules have you loaded.
 You mention compiling for CPU with intel oneapi.
 For GPU you should only use the compilers provided in an nvhpc package ( currently i recomment 24.5)
Our dependencies are mostly hdf5 and openmpi, these should be compiled with nvc++ after installing nvhpc
Hdf5 is simple enough and you could install it locally following our guide, for openmpi this should be handled by your support.

Regarding flags, there is lot to be said, you should inspire yourself from the jeanzay A100 example in scripts/compile_tools/machine/ 
FOr starters:
 -fopenmp should NOT be here ,  neither -lgomp
 you are missing the gpu specific flags for CXXFLAGS such as -acc=gpu -gpu=cc80

**Comment by JohanKoelsenDeWit** [comment]
Hi! Thank you kindly. And my apologies for opening it as an 'issue' - I will make a new thread under discussions right away. In the new thread I will reply to this message. :-)
