### ISSUE TITLE
Problem with Scalar Diagnostics

### ISSUE THREAD

**Issue by emil-mouz** [SmileiPIC/Smilei#75]
Hello 
I just run my first simulation on Smilei and I want to see some Scalar quantities. The issue that I'm facing is that when i run the script for the diagnostics in python, it seems that it works pretty normally, but when the graphic window open (with the results), it instantly disappears. Anyone know why this is happening?

![screenshot from 2019-01-18 15-57-30](https://user-images.githubusercontent.com/45740200/51391717-7fa43880-1b3b-11e9-80a7-cc7903040a51.png)
![Uploading Screenshot from 2019-01-18 16-05-28.png…]()

**Comment by emil-mouz** [comment]
Hi, thanks a lot for your answer. Can you tell me how can i run happi
interactively in a python shell? I'm new to that, sorry for the novice
question. ..

Στις Παρασκευή, 18 Ιανουαρίου 2019, ο χρήστης Arnaud beck <
notifications@github.com> έγραψε:

**Comment by mccoys** [comment]
Hi,
The best option is to use `ipython`. Just run the `ipython` command and run your script using:
```ipython
[1]: %run Happi1.py
```

If you don't want to use `ipython`, simply use the `python` command with the `-i` option. It will tell python to stay open:

```bash
python -i Happi1.py
```

**Comment by mccoys** [comment]
@emil-mouz Was your issue solved ?

**Comment by emil-mouz** [comment]
Yes thanks a lot for the answer. Sorry for the late response
