### ISSUE TITLE
Question on a laser envelope simulation problem

### ISSUE THREAD

**Issue by alexanderboe** [SmileiPIC/Smilei#78]
Dear developers / fellow users of SMILEI,

I would like to use the SMILEI laser envelope model, to simulate laser-wakefields _in a non-moving simulation box_. Since absorbing EM boundaries are not currently implemented for the envelope approximation, in such a non-moving simulation domain an initial pulse is reflected from the longitudinal boundaries multiple times.

To work around this issue, I would like to simulate the propagation of the pulse through the plasma, then halt the simulation, _remove the pulse_, and restart the simulation to investigate the wakefield at later times. Can this be done in a practical way? For instance, is it possible to save all particle positions and momenta, after the envelope pulse has propagated through the plasma once, and then use the dumped positions and momenta to commence a new simulation, where the initial fields are calculated from the particle positions? 

Any thoughts on this would be much appreciated! 

Best,

Alexander

**Comment by Z10Frank** [comment]
Dear Alexander,
indeed at the moment unfortunately no absorbing boundary conditions are available for the laser envelope model. 

Unfortunately starting a simulation with all the particles saved from a previous simulation (and I mean exporting them with TrackParticles and then upload them through numpy) would not be sufficient to recreate the same physical system. A Poisson solver on that simulation would give only the electrostatic fields from the charge distribution you have uploaded (and laser wakefields have also magnetic fields). 

To try to recreate the same physical system, you could upload all the particles (with their positions and momenta) and the electromagnetic fields (exporting them through a GetData on the DiagFields and uploading them through External fields). This procedure would be cumbersome and you would need to remap the fields through Python to correctly upload them (without the envelope), but it is possible. 
This system would not be completely equivalent to the one in the simulation with the envelope, as the exported particle's momenta are actually sqrt(1.+u^2+|A|^2/2) [i.e. there is a contribution from the envelope A in these ponderomotive momenta].

Alternatively, you could initialise a very long window populated by plasma particles only in the first part, and while the laser envelope moves in vacuum and is reflected you could study the Wakefield in its trail in the plasma.

Best,
Francesco

**Comment by mccoys** [comment]
@alexanderboe It may be a silly remark, but I fear that it may not be physical to *remove* the upstream plasma, as it may have a feedback towards the downstream plasma. What boundary conditions would the particles have ?
