### ISSUE TITLE
Collisions causing error "Integer divide by zero"

### ISSUE THREAD

**Issue by andsunds** [SmileiPIC/Smilei#79]
Hi,
I'm encountering some errors with the collisions in Smilei (1D). The basic idea I wanted to run was a laser hitting a target, with collisions turned on. However the simulation would crash after just a handful of time steps when I had collisions turned on (without collisions, it runs fine).

I created a minimal example reproducing the bug, attached below together with the output from running it:
[coll_error_py.txt](https://github.com/SmileiPIC/Smilei/files/2817160/coll_error_py.txt)
[coll_error_log.txt](https://github.com/SmileiPIC/Smilei/files/2817161/coll_error_log.txt)

After investigating this a bit further, I believe that the error might be triggered when a particle finds itself alone in a cell, and then it does not have anything to collide with. Some points which support my hypothesis:
 * The error does not occur if I freeze the particles (i.e. no particle will wanter out into the vacuum region).
 * The error also does not occur if I fill the whole simulation box with particles, `Lvac=0` and `L_pl=Lx` (there are no empty cells).
 * Setting a predefined constant `coulomb_log` (e.g. `coulomb_log=5.`) does not solve the problem;(hence it's not the automatic calculation of the Coulomb log causing the error).

**Comment by andsunds** [comment]
To further support my hypothesis that the collisions require something to collide with, I added a "background" species with no charge and very low density (`number_density = constant(1e-10*n0)`), which works without any errors.

[coll_w_background_py.txt](https://github.com/SmileiPIC/Smilei/files/2817309/coll_w_background_py.txt)

**Comment by mccoys** [comment]
Thank you for reporting the bug. The last push should fix it.

**Comment by andsunds** [comment]
Yes! I no longer get this error. Thank you!
