### ISSUE TITLE
slow take-off of two-stream and whistler anisotropy instability

### ISSUE THREAD

**Issue by phyax** [SmileiPIC/Smilei#8]
Hello,

I ran the two stream instability in the benchmark directory. The run was completed successfully. But the simulation experienced a long quiet period before the instability starts to take off. Please find the attached scalar diagnostics to see this quiet starts. I wonder why.

![two_stream_scalar](https://user-images.githubusercontent.com/20483877/27051340-947afb16-4f6a-11e7-850a-20fbf33224b4.png)

I also test this for whistler anisotropy instability with a high anisotropy (A = Tperp/Tpar -1 = 5.25) initialization. It is expected the instability should happen right after the simulation starts. But the simulation again experienced a long quite start (about 1.2 electron cyclotron period) before the instability takes off. Please find the attachment for the associated scalar diagnostics.

![whistler_anisotropy_scalar](https://user-images.githubusercontent.com/20483877/27051699-f2d1cafe-4f6b-11e7-95f7-8d1a0ef5c90d.png)

Thanks.

**Comment by MickaelGrech** [comment]
Hello! 
Nice to have you join the SMILEI community!

At first sight, I would say that the Weibel simulation (and a priori the Whistler one too) looks fine.
In both cases, there is a small error on the total energy (Utot which I guess should be conserved) but it looks to be quite small so I would not be too worried about this.

Also, from your diagnostics as they are presented, I would not say that there is a quite start for the instability! Indeed, in the linear phase you would expect to see not much change at first, which is exactly what you get. However, if you print in log-scale, I guess that you will see the instability growing exponentially, as I guess you expect.
Hence, I suggest you have use a log-scale for the vertical axis of your diagnostics.

Let us know if things are going in the good direction!
Mickael

**Comment by phyax** [comment]
Hi Mickael,

Thanks for you quick response. I tried what you suggested. It does not look like linear curve in a linear-log plot. The electromagnetic energy still does not change much over time in a log scale.

Also, what about the slow take-off of the two-stream instability in the benchmark directory.

Thanks,
Xin

**Comment by phyax** [comment]
Thanks Mickael for your quick response. I realized Uelm includes not only AC electromagnetic field energy but also electromagnetic energy of DC external field. After subtracting the DC field energy from Uelm, the results looks reasonable in a linear-log plot. Thanks again.

**Comment by MickaelGrech** [comment]
Hi Xin!

Indeed, I did not think on this... Uelm accounts for the total field energy, you can get the energy for a given field, e.g. Ey, using Uelm_Ey.

I hope you enjoy your experience with SMILEI!
Do not hesitate to keep us informed, and if you get some results published, please let us know so we can advertise your results in our highlights and/or materials!

Keep SMILEIng!

**Comment by phyax** [comment]
Thanks Mickael. I will keep you informed on my progress.

Xin
