### ISSUE TITLE
corrupted unsorted chunks

### ISSUE THREAD

**Issue by fyli16** [SmileiPIC/Smilei#87]
Hello, I have constantly seen crash of the simulation due to error ''corrupted unsorted chunks:". Detailed simulation log file is attached below
[sm.log](https://github.com/SmileiPIC/Smilei/files/2885959/sm.log)
It did not always crash but did so very often. The code was compiled using gcc-4.8.5 plus own-compiled openmpi-2.1.0, hdf5-1.10.4 libs. 

Have you seen such behavior before? If you need more info please let me know.
Thanks in advance.

**Comment by mccoys** [comment]
I have never seen this error with smilei. Is it always with the same input? At the same timestep? Or more random?

One possibility is that the memory is exceeded during synchronisation. Does it still happen if you have less particles or a smaller grid per processor? 

By any chance, have you tried another mpi library? Or another cpp compiler?

**Comment by fyli16** [comment]
@mccoys It can be with the exactly same input but happens at very different timesteps (such as at the middle of simulation, or close to the end of simulation), so more random in nature. The error messages could also be slightly different such as 'corrupted unsorted chunks', 'memory corruption'. 

It seems OK with fewer particles but need to be tested with more runs.  So it should be related to memory exceeding. 

BTW in all cases, I have turned off vectorization and used multiple threads per MPI process. Haven't got chance to test with another mpi because the admin provided mpi seems not compiled with --enable-mpi-thread-multiple.

**Comment by MickaelGrech** [comment]
From your log file it doesn't look like you are using a lot of particles, so I don't think memory limit is a problem. From what I saw quickly on the net, it could be a problem of initialisation of a pointer or bad allocation of memory somewhere.
As @mccoys suggested, you could try with a different compiler. If your default compiler does not support MPI_THREAD_MULTIPLE, you can compile with: make config=no_mpi_tm (it is not optimal, but it works and allow to use SMILEI with this kind of compilers).
Also, could you send us your input file so that we can try to reproduce your error on our machines?
Last, going through your log, I saw that you use 4MPI x 36OMP threads. Is it correct? What kind of machine are you running on?

**Comment by fyli16** [comment]
Thanks @MickaelGrech Now the input is attached [inp.txt](https://github.com/SmileiPIC/Smilei/files/2890249/inp.txt). As I said it may not crash in a second run without changing anything of the input. 
I will test with the system mpi, but will the performance be much downgraded if MPI_THREAD_MULTIPLE is not enabled? My test with some specific simulations showed that the speed could be 100 times slower if, for example, changing 2MPIx36OMP to 72MPI.
Yes, I was using 4MPIx36OMP threads. Was running on a cluster with info attached as [E5-2695.pdf](https://github.com/SmileiPIC/Smilei/files/2890289/E5-2695.pdf)

**Comment by mccoys** [comment]
Just a remark not directly related to the crash : your system has 18 cores. Not 36. Setting 36 threads per node is unlikely to speed up the simulation, and might cause overheads instead. It is good practice to test 18.

The crash might be a bug in smilei, but we need to manage to replicate it first. We will keep you posted.

**Comment by fyli16** [comment]
@mccoys thanks for bringing this up. It's strange that my choice (4nodes-4mpi-36omp) actually has the best performance at 0.3s per two simulation steps. It became 1.7s for 4nodes-4mpi-18omp, and 3.3s for 4nodes-8mpi-18omp, and 7.7s for 144mpi. 

I think each node has 2 sockets, each 18cores, and 2 NUMA, so the best choice would be 4nodes-8mpi-18omp, but the above tests are against it.

BTW, I have recompiled using system mpi and hdf5 with the option config=no_mpi_tm. With this compilation, it seems stable - haven't seen crashes in a number tests - although the performance is about 30% reduced. It may be a problem of my own-compiled mpi, hdf5, but in compiling them I just followed the configure options provided on the smilei web.

**Comment by beck-llr** [comment]
Hey
Just a remark here.  It is usually sub optimum to use openMP across sockets. What mccoys was suggesting I guess was to use 4 nodes - 8 mpi - 18 omp with 1 mpi per socket instead of 1 mpi per node.
10% loss of performance in `no_mpi_tm` is acceptable. 30% seems a lot but it is case dependent so maybe you are unlucky.
Anyway, thanks again for reporting this to us.

**Comment by fyli16** [comment]
@beck-llr thanks. I understand mccoys was suggesting I use 4 nodes - 8 mpi - 18 omp with 1 mpi per socket, but as I showed, this was not optimal in performance. Quite strange, anyway.

**Comment by jderouillat** [comment]
> My test with some specific simulations showed that the speed could be 100 times slower if, for example, changing 2MPIx36OMP to 72MPI.

Did you check the affinity/placement of MPI processes using the option ``--report-binding`` of the OpenMPI's mpirun ?

**Comment by fyli16** [comment]
@jderouillat I see the problem - I simply commented out 'export OMP_NUM_THREADS=36' to use pure MPI. 
I should have set 'export OMP_NUM_THREADS=1' -now with this setting the performance is much boosted, even about 10 times better than doing hybrid MPI/OpenMP ...

**Comment by fyli16** [comment]
In all, with recompilation using system mpi, smilei has been pretty stable so far  for quite a number of runs, and by setting export OMP_NUM_THREADS=1 the speed is also very acceptable. Thank you all for the comments. If no more comments I would close this issue.

**Comment by mccoys** [comment]
Good to know that this was a config issue, not a smilei issue :)

**Comment by MickaelGrech** [comment]
@fyli16 thanks a lot for your feedback. It does look strange however that 
setting export OMP_NUM_THREADS=1 the speed is also very acceptable. Do you mean it is best for you to use this? In that case, I would be surprised, did you check that you use the dynamic scheduler of openMP (export OMP_SCHEDULE=dynamic)?
Also, going through your input file, I realised that you inject a laser on the xmin bounder, and start the moving window at time t=0. This is very surprising to me. Are you sure you correctly inject your laser? Usually, the moving window should start running once the laser has fully entered the simulation box, and then you keep looking at your laser by following it through the plasma. I'm not sure what you are attempting at doing here is really correct.

**Comment by fyli16** [comment]
Thanks! @jderouillat 

> It does look strange however that setting export OMP_NUM_THREADS=1 the speed is also very acceptable. Do you mean it is best for you to use this?

 yes, it is fastest for my case.

> did you check that you use the dynamic scheduler of openMP (export OMP_SCHEDULE=dynamic)?

no, I have commented out this but simply used export OMP_NUM_THREADS=36 in the hybrid MPI/OpenMP runs. Is this the reason that hybrid scheme runs at slower speed?

> going through your input file, I realised that you inject a laser on the xmin bounder, and start the moving window at time t=0.

no, I am not using Moving window - it's actually commented out.

**Comment by mccoys** [comment]
The dynamic scheduling can indeed be very useful and *might* be the reason for your surprising results. However, the reason could be something else as well (system setup, load imbalance, ...)
