### ISSUE TITLE
Python not initialised error in PyTools

### ISSUE THREAD

**Issue by srozario121** [SmileiPIC/Smilei#88]
Hello,
I've recently pulled a newer version of smilei from this repository and tried to run an old script. I'm encountering a rather odd error.
`src/Tools/PyTools.h:535 (nComponents) Python not initialized: this should not happen`
It only happens when I have an ionisation species block present and it only happens on the newest version of smilei. There are no errors on the compilation stage.
I know the input deck works fine as when I run it on an older version it runs without any issues. 
[SmileiInputDeckAndLogFile.zip](https://github.com/SmileiPIC/Smilei/files/2924945/SmileiInputDeckAndLogFile.zip)
Cheers
Savio

**Comment by mccoys** [comment]
Hi,

I cannot reproduce this error. Have you cleaned your build directory before compiling the new version ? You can use `make clean` before compilation.

**Comment by srozario121** [comment]
The error persists. It only occurs once the moving window begins.

[CompilationOutput_Smilei.txt](https://github.com/SmileiPIC/Smilei/files/2925927/CompilationOutput_Smilei.txt)

**Comment by mccoys** [comment]
I found the error and will try to provide a fix soon

**Comment by mccoys** [comment]
Please check the latest pushes. This should be fixed.

**Comment by srozario121** [comment]
Yep it works! 
Thanks, I'll close this now.
