### ISSUE TITLE
Particle creation

### ISSUE THREAD

**Issue by arsampath** [SmileiPIC/Smilei#89]
Dear Developers,

I am using SMILEI v3.3 to create and destroy some particles. 
Following the structure of your code, I have created particles in the following manner.

1. Particles new_p; 
2. new_p.initialize(5,2); 
3. Assigned the values for position, momentum, charge and weight for these particles.
4. new_sp->importParticles(params, patch, new p, localDiags); 

(new_sp is a species pointer which points to the species from the input deck where I want the new particles to be imported)

Everything seems to work as expected. However, when I switch on TrackDiagnostics, I get segmentation fault during importParticles().

Kindly let me know if I may have missed out on any key modification for importing the particles or if there are any inconsistencies.

Thank you for your support!

**Comment by mccoys** [comment]
@arsampath It is hard for us to support several versions of Smilei. Is it possible for you to upgrate to Smilei 4.1 ?

**Comment by mccoys** [comment]
Note that importing particles requires the overall initialization to be complete. For instance, diagnostics must have been created. Where have you tried to use `importParticles` ?

**Comment by arsampath** [comment]
@mccoys I have added a new file new.cpp which has a function definition. I call this function (written in new.cpp) inside Collisions.cpp file. 
Within this function definition, I initialize the particles, assign values and import the particles into new_sp (species pointer) in a manner followed in SMILEI code. I have hence used importParticles() within new.cpp.
I give the Particle and Species declaration within the Collisions.h (public data members).

Could you give me further insight into overall initialization and creating diagnostics?
Scalar and Field Diagnostics seem to work for the newly created particles.

I will try to upgrade to Smilei v4.1 soon. The modifications I tried were inside Collisions.cpp and since this file has been modified in v4.1, it will take some time to upgrade.

Thank you for the quick response.

**Comment by mccoys** [comment]
The initialization happens at the beginning of the simulation: the input file is read, and all objects are created, including diagnostics.

If you put `importParticles()` in `Collisions.cpp`, make sure it does *not* happen in the constructors, as those are done during initialization. If it appears in other functions, it should be ok.

Note that several things could cause some objects to be destroyed (and they might be needed for `importParticles()`). For instance, the moving window destroys *patches*, which are pieces of the simulation box, when the window moves. Similarly, those patches are destroyed if they are communicated to other MPI processes during the *load balancing*.

Anyways, it is too hard to know what went wrong without knowing more about your implementation. Do you have a public fork of Smilei that we could look at ?

**Comment by arsampath** [comment]
Thank you for the response. I have ensured that importParticles() is not in the constructor of Collisions object. 
I will try to upgrade and implement the creation and destruction of particles with Smilei v4.1.
Could you provide some description of what are the changes in Collisions.cpp in v4.0 and v4.1.
In the previous versions, Smilei made particles collide with all those in the same patch. 
Is the collision process still patch dependent? If not, what criteria is used in the latest release?

**Comment by mccoys** [comment]
In the latest release, the vectorization technique enables a particle sorting per cell. This has allowed collisions to be made per cell (instead of per patch), which is much better for a correct physical description.

In addition, collisions have been duplicated in another class `CollisionsSingle` which is a faster version, but only between 1 species and 1 species. The usual `Collisions` class can collide many species with many species.

There have been other minor changes, such as reorganizing the functions, and changing the random number generator.

**Comment by mccoys** [comment]
Note that v4.0 has an important bug related to collisions! I strongly suggest 4.1 instead.

**Comment by arsampath** [comment]
Dear developers,

I have upgraded to Smilei v4.1 and I still get memory issues (Segmentation fault) with Track Diagnostics when I create my own particles. 
I have attached here a zip file which contains the modified program files, a sample input file only to check creation and destruction of particles and a pdf which explains my modifications in Smilei. 
Kindly let me know if there is some mistake with my implementation.

Thank you for your time.

[modifications.zip](https://github.com/SmileiPIC/Smilei/files/2942839/modifications.zip)

**Comment by mccoys** [comment]
How do you switch on the tracked particles diagnostic ?
I see that you have put the following line:
```c++
    ar_particles.tracked = 1;
```
But this is incorrect. This flag should only be specified by a tracking diagnostic. This is probably why there is a segfault.

You might be able to create a new diagnostic with 
```c++
new DiagnosticTrack( params, smpi, vecPatches, n_diag_track, vecDiagnostics.size(), openPMD )
```

However, this is a little complicated, as it must not interfere with the other tracking diagnostics.

**Comment by arsampath** [comment]
I switch on TrackDiagnostic by using the namelist option in the input_deck. 
I added the ar_particles.tracked = 1 to check if that enables the diagnostic within the code (but I understand it is not the correct method now).

I would like to know if the way in which I have created and destroyed particles is in line with the framework of SMILEI, if I do not intend to use TrackDiagnostics.

**Comment by mccoys** [comment]
I believe the particle creation is ok, although I have not tested it. The trackparticle diagnostic is not correctly used though

**Comment by arsampath** [comment]
Thank you for the quick responses. I do not have any further query regarding this issue.
