### ISSUE TITLE
Time in diags

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#92]
Hi Smilei dev 

A question for Frederic I'm sure.
In a ParticleBinning diag (or any diag animated), is it possible that time at the top of the graph would be real time (in fs for example with pint mudule) and not the timesteps/dt.
Moreover, a question about .streak() on a diag. On the y-axis, it's the same problem it's number of timesteps and not the time or perhaps I don't know the trick to do that. An if you want a t-x graph of a measure it's a problem.
Thanks

Julien
CELIA

**Comment by mccoys** [comment]
I'll fix the first problem soon ;)

Concerning the second issue, it is always possible to manipulate the axis using the `yfactor` argument, and change the `ylabel` to something explicit.

**Comment by mccoys** [comment]
Ok the first issue should be fixed in  d447f73

**Comment by juliencelia** [comment]
Désolé de t'embêter encore Fred j'ai essayé le yfactor... sans effet. Cet argument attend quoi? un float? 
J'ai fait S.ParticleBinning(.....).streak(yfactor=S.namelist.d*1e15,ylabel='time in fs') pas d'erreur renvoyée mais le plot ne change pas j'ai toujours le nombre de timestep en ordonnée. 

Désolé 


De: "mccoys" <notifications@github.com> 
À: "SmileiPIC/Smilei" <Smilei@noreply.github.com> 
Cc: "Julien Bonvalet" <julien.bonvalet@u-bordeaux.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 13 Mars 2019 09:51:04 
Objet: Re: [SmileiPIC/Smilei] Time in diags (#92) 



I'll fix the first problem soon ;) 

Concerning the second issue, it is always possible to manipulate the axis using the yfactor argument, and change the ylabel to something explicit.

**Comment by mccoys** [comment]
Sorry I did not see that the `yfactor` was not included for `streak()`. I fixed it in the last commit 8a89dae

Your code is correct

**Comment by juliencelia** [comment]
Everything is working fine.
Thanks a lot.
