### ISSUE TITLE
Clarification of photon initialisation in tst2d_v_10_multiphoton_Breit_Wheeler.py

### ISSUE THREAD

**Issue by arsampath** [SmileiPIC/Smilei#93]
Dear developers,

I have a very simple question. In the benchmark file **tst2d_v_10_multiphoton_Breit_Wheeler.py,** I see that the species photon is described in the following way. 

Species(
    name = "photon",
    position_initialization = "random",
    momentum_initialization = "cold",
    particles_per_cell = 128,
    c_part_max = 1.0,
    mass = 0,
    charge = 0.,
    number_density = n0_photon,
    mean_velocity = [0.0 ,-gamma, 0.0],
    temperature = [0.],
    pusher = "norm",
    multiphoton_Breit_Wheeler = ["electron","positron"],
    multiphoton_Breit_Wheeler_sampling = [1,1],
    boundary_conditions = [[part_cond], [part_cond]],
)

Here **mean velocity** is given as [0.0, -gamma, 0.0] where **gamma** is the normalised energy.  
So in this case, does mean_velocity mean the photon momentum? If so, then why is this being specified by the velocity tag (which in the documentation is in units of c).

Thank you for your time.

**Comment by mccoys** [comment]
There is a lack of information in the documentation. The parameter `mean_velocity` is actually a *momentum* in the case of massless particles.

**Comment by arsampath** [comment]
@mccoys  Thank you for the prompt response!

**Comment by mccoys** [comment]
Doc was fixed
