### ISSUE TITLE
Maybe a bug about probe

### ISSUE THREAD

**Issue by prlWanted** [SmileiPIC/Smilei#95]
Dear developers,
Hi.  I did a 1d simulation using SMILEI. I opened a DiaFields and a DiagProbe like follows:
![image](https://user-images.githubusercontent.com/22358113/54830192-56796300-4cb8-11e9-91d0-3b970d644ba8.png)
![image](https://user-images.githubusercontent.com/22358113/54830203-5da07100-4cb8-11e9-82ae-a3b00bbc7ada.png)
And I have a species named ion. When I want to plot the ion density from the DiagProbe, something went wrong and I could never succeed. But the DiagFields works fine.
![image](https://user-images.githubusercontent.com/22358113/54830533-f636f100-4cb8-11e9-81c4-eab6d3cec72e.png)

![image](https://user-images.githubusercontent.com/22358113/54830695-41510400-4cb9-11e9-86d2-8a52d23cddb6.png)

It seems like, when I want to get the density data from the probe, all the fields are deposited into  the "Rho_ion".  And I try with S.Probe(0, 'Ex'), it's also the same.

**Comment by mccoys** [comment]
You need to specify "Rho_ion" in the "fields" arguments. It is explained here : 
http://www.maisondelasimulation.fr/smilei/namelist.html#probe-diagnostics

**Comment by prlWanted** [comment]
Thank you! But default [] means ["Ex", "Ey", "Ez", "Bx", "By", "Bz", "Jx", "Jy", "Jz", "Rho"], right? It doesn't work for 'Ex' as well.

**Comment by mccoys** [comment]
It should work for Ex. I just tried and it worked.

Please describe in detail what you are trying (input file and post-processing commands).

Note that you can copy-paste text instead of copying images in github. It helps for us to try to reproduce the errors.

**Comment by mccoys** [comment]
Closing until further information from user
