### ISSUE TITLE
unexpected ep_handle=0x10d4010 in DAPL conn event 0x40004

### ISSUE THREAD

**Issue by illia-thiele** [SmileiPIC/Smilei#96]
Dear SMILEI team,

I want to run a computationally heavy simulation on 4096 procs which does not properly start. I get the following messages in the error and output file:

=== in the error file ===
```
[0:n3106.occigen]  unexpected ep_handle=0x10d4010 in  DAPL conn event 0x40004
Assertion failed in file ../../src/mpid/ch3/channels/nemesis/netmod/dapl/dapl_poll_ud.c at line 478: 0
internal ABORT - process 0
srun: error: n3106: task 0: Exited with exit code 1
```

 === In the output file: ===
```
Initializing MPI
 --------------------------------------------------------------------------------
n3106.occigen:UCM:10d8:b99cc700: 474920649 us(474920649 us!!!):  CM_REPLY: RETRIES EXHAUSTED (lid port qpn) 167 10d8 23626 -> a66 13 14e8c
n3106.occigen:UCM:10d8:b99cc700: 474920876 us(227 us):  CM_REPLY: RETRIES EXHAUSTED (lid port qpn) 167 10d8 23626 -> a66 13 14e68
n3106.occigen:UCM:10d8:b99cc700: 474920881 us(5 us):  CM_REPLY: RETRIES EXHAUSTED (lid port qpn) 167 10d8 23626 -> 331 1d 3627a
```

In contrast, the simulation with a lower spatial resolution works well. I have problems to interpret the output and error messages. Do you have an idea what might go wrong?

Very best regards
Illia

**Comment by beck-llr** [comment]
Hi Illia
4096 does not soud that heavy. I've run Smilei on 14000 Occigen proc several times. So it is probably not a scaling issue.
4096 though is kind of a weird number since each node has either 24 or 28 cores which does not divide 4096. So that means that you're not using the nodes completely. Are you using the submission script that we gave to Evangelos at the workshop for your submission ? In any case, could you paste your submission script here please ?

I have not used Occigen in a while now so it might be hardware related or they may have change something in their configuration too. You can try to get in touch with the cines hotline, they are usually very helpful.

**Comment by jderouillat** [comment]
Dear Illia,
Is it reproducible ? This error looks to a node failure.

**Comment by illia-thiele** [comment]
Thank you for the rapid reply! Sorry, it was 4480 procs - I have posted it incorrectly. I have also contacted the CINES team. The submission file is not the one Evangelos has, its:

#!/bin/bash
#SBATCH -J TNSA_holetarget_2d_aL4d84_Au11_b0d0_dion0d1_set1_highRes
#SBATCH --nodes=160
#SBATCH --ntasks=4480
#SBATCH --threads-per-core=1
#SBATCH --time=23:59:58
#SBATCH --output TNSA_holetarget_2d_aL4d84_Au11_b0d0_dion0d1_set1_highRes.out
#SBATCH --error TNSA_holetarget_2d_aL4d84_Au11_b0d0_dion0d1_set1_highRes.err
#SBATCH --constraint=BDW28
PROC=4480
NAME=TNSA_holetarget_2d_aL4d84_Au11_b0d0_dion0d1_set1_highRes.py
RRUN=no
TIME=23:59:58
THPC=1
DATA='/home/thiele/codes/SMILEI/data'
EXEC='/home/thiele/codes/SMILEI/smilei_git'
WDIR='/scratch/cnt0023/cli6129/thiele/simulations/SMILEI'

DIR=${NAME%.*}

# Preparation of the data to launch the simulations
#=========================================================================

#--- remove the old directory for results
if [[ (-d $WDIR/$DIR) ]]; then
    /bin/rm -r $WDIR/$DIR
    echo 'The old directory' $WDIR/$DIR 'has been removed'
fi

#--- build the new directory for results
mkdir -p $WDIR/$DIR
echo 'The directory' $WDIR/$DIR 'has been built'
cp $EXEC/smilei  $WDIR/$DIR/.
cp $DATA/$NAME  $WDIR/$DIR/.

cd $WDIR/$DIR
echo 'The code is executed in the directory '$WDIR/$DIR

# -- Profiling ------
export IPATH_NO_CPUAFFINITY=1

echo $SLURM_NTASKS

module purge
module load intel intelmpi hdf5/1.8.18 qt/4.8.6 python/2.7.12 mesa/17.2.4 VTK/7.0.0
CXXFLAGS +=  -xHost -O3 -ip

srun --mpi=pmi2 -K1 --resv-ports -n $SLURM_NTASKS smilei $NAME
echo 'Simulation is done'

Cheers
Illia

**Comment by beck-llr** [comment]
Unless you have compiled Smilei with `config=noopenmp` I would strongly advise to `export OMP_NUM_THREADS=1` and `export HYPERTHREADING=OFF` in your script even though I'm not sure this would change something. Just safety measures. Does the Smilei output log went to the point at which it tells you how many openMP threads it is currently using ? Or did it crash even before that ?

I also second @jderouillat 's observations.

**Comment by beck-llr** [comment]
Also note that the modules you are using are not the ones we suggest for Occigen in `script/CompileTools/machine/occigen`.
