### ISSUE TITLE
Possible memory leaks in RadiationTables

### ISSUE THREAD

**Issue by lucafedeli88** [SmileiPIC/Smilei#97]
Hello everyone,

I was looking at the source code in RadiationTables.cpp.
It seems to me that the methods 
RadiationTables::computeRitusSynchrotronEmissivity 
and
RadiationTables::integrateSynchrotronEmissivity
contain new operators unmatched by corresponding delete[] operators.

is there a specific reason for that?

**Comment by mccoys** [comment]
This looks suspicious indeed. There is also a `buffer` variable in other functions that lacks a delete as well.

@xxirii is this on purpose ?

**Comment by xxirii** [comment]
Hi @lucafedeli88, thanks for reporting this issue that is indeed pertinent. Fortunately this phase is not repeated at each iteration, therefore not creating a big memory leak. This will be corrected soon.

**Comment by mccoys** [comment]
@xxirii I think this has been corrected, right?

**Comment by xxirii** [comment]
@mccoys it is corrected in my development branch but not yet on the official repo. I will push the correction with some other features.
